<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Braldun</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <?php if ($this->modificationBraldun === true) :?>
	    	Modification du Braldûn prise en compte.
	    <?php endif; ?>
	    Compte actif : <?php echo $this->braldun["est_compte_actif_braldun"]?><br />
	    Compte en hibernation : <?php echo $this->braldun["est_en_hibernation_braldun"]?><br />
	    PNJ : <?php echo $this->braldun["est_pnj_braldun"]?><br />
	    
	    Lien de validation = <?php echo $this->urlValidation;?>
	    
	    <form action="/Administrationbraldun/braldun/mode/<?php echo $this->mode?>/idbraldun/<?php echo $this->id_braldun?>" method="post">
		<?php if ($this->braldun == null): ?>
			Braldun inconnu 
		<?php else: 
			$nbElement = 0; ?>
			<?php if ($this->user->administrateur) : ?>
				<input type="button"  class='button' name="mode" value="Usurpation sans activation DLA (se deconnecter ensuite!)" onclick="document.location.href='/Administrationbraldun/usurpation/idbraldun/<?php echo $this->id_braldun?>/activation/non'" <?php if ($this->braldun["est_compte_actif_braldun"] != "oui") :echo "disabled='disabled'"; endif;?>/>
				<input type="button"  class='button' name="mode" value="Usurpation avec activation DLA (se deconnecter ensuite!)" onclick="document.location.href='/Administrationbraldun/usurpation/idbraldun/<?php echo $this->id_braldun?>/activation/oui'" <?php if ($this->braldun["est_compte_actif_braldun"] != "oui") :echo "disabled='disabled'"; endif;?>/><br />
				
				<?php if ($this->mode == "simple") :?>
		 	   		<input type="button"  class='button' name="mode" value="Passer en vue complexe" onclick="document.location.href='/Administrationbraldun/braldun/mode/complexe/idbraldun/<?php echo $this->id_braldun?>'"/>
		   	 	<?php else: ?>
		    		<input type="button"  class='button' name="mode" value="Passer en vue simple" onclick="document.location.href='/Administrationbraldun/braldun/mode/simple/idbraldun/<?php echo $this->id_braldun?>'"/>
		    	<?php endif; ?>
	    	<?php endif;?>
	    
	    	<input type='button' name='goProfil' value='Ouvrir Profil Public' class='button'  onclick='javascript:ouvrirWin("/voir/braldun/?braldun=<?php echo $this->id_braldun?>");'>
	    
			<table  align='center'>
			<?php foreach ($this->braldun as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?php echo $key?></td>
				<td>
				<?php if ($key == "id_braldun"): ?>
					<input type='hidden' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
					<?php echo $value ?>
				<?php else: ?>
					<input type='text' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
				<?php endif; ?>
				</td>
				<td>				
				<?php if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button' name="Modifier" value="Modifier le Braldûn" />
				<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
			</table>
			<input type="submit"  class='button' name="Modifier" value="Modifier le Braldûn" />
		<?php endif; ?>
		</form>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>