<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Braldun</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <? if ($this->modificationBraldun === true) :?>
	    	Modification du braldun prise en compte.
	    <? endif; ?>
	    Compte actif : <?=$this->braldun["est_compte_actif_braldun"]?><br />
	    Compte en hibernation : <?=$this->braldun["est_en_hibernation_braldun"]?><br />
	    PNJ : <?=$this->braldun["est_pnj_braldun"]?><br />
	    
	    Lien de validation = <?=$this->urlValidation;?>
	    
	    <form action="/Administrationbraldun/braldun/mode/<?=$this->mode?>/idbraldun/<?=$this->id_braldun?>" method="post">
		<? if ($this->braldun == null): ?>
			Braldun inconnu 
		<? else: 
			$nbElement = 0; ?>
			<? if ($this->user->administrateur) : ?>
				<input type="button"  class='button1' name="mode" value="Usurpation sans activation DLA (se deconnecter ensuite!)" onclick="document.location.href='/Administrationbraldun/usurpation/idbraldun/<?=$this->id_braldun?>/activation/non'" <? if ($this->braldun["est_compte_actif_braldun"] != "oui") :echo "disabled='disabled'"; endif;?>/> 
				<input type="button"  class='button1' name="mode" value="Usurpation avec activation DLA (se deconnecter ensuite!)" onclick="document.location.href='/Administrationbraldun/usurpation/idbraldun/<?=$this->id_braldun?>/activation/oui'" <? if ($this->braldun["est_compte_actif_braldun"] != "oui") :echo "disabled='disabled'"; endif;?>/><br />
				
				<? if ($this->mode == "simple") :?>
		 	   		<input type="button"  class='button1' name="mode" value="Passer en vue complexe" onclick="document.location.href='/Administrationbraldun/braldun/mode/complexe/idbraldun/<?=$this->id_braldun?>'"/>
		   	 	<? else: ?>
		    		<input type="button"  class='button1' name="mode" value="Passer en vue simple" onclick="document.location.href='/Administrationbraldun/braldun/mode/simple/idbraldun/<?=$this->id_braldun?>'"/>
		    	<? endif; ?>
	    	<? endif;?>
	    
	    	<input type='button' name='goProfil' value='Ouvrir Profil Public' class='button1'  onclick='javascript:ouvrirWin("/voir/braldun/?braldun=<?=$this->id_braldun?>");'>
	    
			<table  align='center'>
			<? foreach ($this->braldun as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?=$key?></td>
				<td>
				<? if ($key == "id_braldun"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=stripslashes($value)?>">
					<?=$value ?>
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=stripslashes($value)?>">
				<? endif; ?>
				</td>
				<td>				
				<? if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button1' name="Modifier" value="Modifier le Braldûn" />
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
			<input type="submit"  class='button1' name="Modifier" value="Modifier le Braldûn" />
		<? endif; ?>
		</form>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>