<div class="box_infos_jeu">
<div class="inner">
	<div class="contenu">
	    <div class="box_contenu3 textalib">
	    	<p class="titre textalic textsizeb center" ><a href="/annonces" title="Voir les Archives" style="text-decoration:none">Les Annonces</a></p>
	    		<? if (count($this->annonces) > 0) : ?>
				<?php echo $this->render('annonces/histoires.phtml'); ?> 
				<? endif; ?>
				<br/><a href="/annonces">Archives</a>&nbsp;
	    </div>
	</div>
</div>
</div>