<div class="box_infos_jeu">
<div class="inner">
	<div class="contenu">
	    <ul class="box_contenu3 textalib">
	    	<ul class="titre textalic textsizeb" ><a href="/annonces" title="Voir les Archives" style="text-decoration:none">Les Annonces</a></ul>
	    		<? if (count($this->annonces) > 0) : ?>
				<?php echo $this->render('annonces/histoires.phtml'); ?> 
				<? endif; ?>
				<br><a href="/annonces">Archives</a>&nbsp;
	    </ul>
	</div>
</div>
</div>