<div id="frise">
	<div id="chronologie"></div>
	<!-- taille total : 1200 année pour 100% -->
	<p class="bande bande_0">
	</p>
	<p class="bande bande_1">
		
		<span class="bande_trait" style="left:72.07%;width:130px">
			<span class="bande_texte" style="left:-60px;top:50px;font-size:10pt">Grande Dispersion</span>
		</span>
		
		<span class="bande_trait" style="left:93.25%">| <span class="bande_date" style="left:-0px">404</span> 
			<span class="bande_texte" style="left:-5%">Aujourd'hui</span>
		</span>
		
		<span class="bande_trait" style="left:92.17%;width:50px">| <span class="bande_date" style="left:-28px">403</span> <br/>|<br/>|</span>
			<span class="bande_texte" style="left:61.17%;top:0px;">
			<br /><a href='http://regles.braldahim.com/wiki/La_fin_du_Premier_%C3%82ge'>L'éveil des Braldûns</a>
			<br /><a href='http://regles.braldahim.com/wiki/Chapitre_II_-_L%27%C3%A9veil_des_Gredins'>L'éveil des Gredins</a>
			<br /><a href='http://regles.braldahim.com/wiki/Chapitre_III_-_L%27H%C3%A9ritage_des_Nains'>L'Héritage des Nains</a>
			<br /><a href='http://regles.braldahim.com/wiki/Livre:Braldahim/%C3%89v%C3%A9nements'>Autres événéments</a>
		</span>
		
		
	</p>
	<p class="bande bande_2">
		<span class="bande_trait" style="left:29.17%;width:100px">| <span class="bande_date" style="left:-28px">350 &nbsp;&nbsp;&nbsp;0</span> 
			<span class="bande_texte" style="left:0px;top:0px;">
			<a href='http://regles.braldahim.com/wiki/Les_origines_de_Braldahim'><br/>Premier Thaâl, création de Braldahim</a>
			</span>
		</span>
		
		<span class="bande_trait" style="left:62.07%;width:100px">| <span class="bande_date" style="left:-28px">402 &nbsp;&nbsp;&nbsp;0</span> 
			<span class="bande_texte" style="left:-60px;">
			<a href='http://regles.braldahim.com/wiki/La_fin_du_Premier_%C3%82ge'><br />Cataclysme <br/>de Muarge</a></span>
		</span>
	</p>
	<p class="bande bande_3">
		
	</p>
	<p class="bande bande_4">
		<span class="bande_trait" style="left:12.91%">| <span class="bande_date" style="left:-25px">156</span> 
			<span class="bande_texte" style="left:-60px">Enchantement des runes</span>
		</span>
		
		<span class="bande_trait" style="left:14.17%">| <span class="bande_date">170</span> 
			<span class="bande_texte"><br />|<br />|<br />Départ des Elfes</span>
		</span>
		
		<span class="bande_trait" style="left:19.17%">| <span class="bande_date" style="left:-25px">230</span> 
			<span class="bande_texte" style="left:-45px">Massacre de Meel</span>
		</span>
		
		<span class="bande_trait" style="left:19.67%">| <span class="bande_date">236</span> 
			<span class="bande_texte"></span>
			<span class="bande_texte"><br />|<br />L'exode des Braldûns</span>
		</span>
	</p>
	<p class="bande bande_5">
	</p>
	<br/>
	<p class="bande bande_0 bande_titre">
	</p>
	<p class="bande bande_1 bande_titre">
		Second  Âge de Braldahim<br /> 404 années à ce jour
	</p>
	<p class="bande bande_2 bande_titre">
		Premier Âge de Braldahim<br />402 années
	</p>
	<p class="bande bande_3 bande_titre">
		Période de troubles<br />114 années
	</p>
	<p class="bande bande_4 bande_titre">
		Quatrième Âge standard<br />236 années
	</p>
	<p class="bande bande_5 bande_titre">
	</p>
</div>