<div class="box_gazette">
<div class="inner">
	<div class="contenu">
	    <ul class="box_contenu3 textalib">
	    	<p class="titre textalic textsizeb center" ><a href="/gazette" title="Voir les Archives" style="text-decoration:none">La Gazette</a></p>
	    		<? if (count($this->histoires) > 0) : ?>
				<?php echo $this->render('gazette/histoires.phtml'); ?> 
				<? endif; ?>
				<br/><a href="/gazette">Archives</a>&nbsp;
	    </ul>
	</div>
</div>
</div>