<div class="box_gazette">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<div class="contenu">
	    <ul class="box_contenu1 textalib">
	    	<ul class="titre textalic textsizeb" ><a href="/gazette" title="Voir les Archives" style="text-decoration:none">La Gazette</a></ul>
	    		<? if (count($this->histoires) > 0) : ?>
				<?php echo $this->render('gazette/histoires.phtml'); ?> 
				<? endif; ?>
				<br><a href="/gazette">Archives</a>&nbsp;
	    </ul>
	</div>
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>