<div id="twtr-widget-1" class="twtr-widget twtr-widget-profile twtr-scroll">
	<div class="twtr-doc" style="width: 100%;">
		<p class="titrea textalic titreasizec" style="margin-top:-15px;">
			Les nouvelles
		</p>

		<a class="twitter-timeline" href="https://twitter.com/Braldahim" data-widget-id="344904381642199043">Tweets</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

	</div>
</div>