<?php echo $this->render('header.phtml'); ?> 
<div id="logo">
<a href="/">Braldahim</a><br>
  <a href="/"> -> Interface</a><br>
  <a href="/encyclopedie"> -> Encyclop&eacute;die</a><br>
  <a href="/"> -> Forums</a>
</div> 
 
<form action="/auth/login" method="post"> 
<div class="box_authentification">
<b class="xb_t1"></b><b class="xb_t2"></b><b class="xb_t3"></b><b class="xb_t4"></b><b class="xb_t5"></b><b class="xb_t6"></b><b class="xb_t7"></b>
<div class="inner">
    <ul class="titre textalia textsizea">Braldahim</ul>
    <ul class="titre textalib textsizeb">Connexion</ul>
	<?php if(!empty($this->message)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php echo $this->escape($this->message);?> 
	</div> 
	<?php endif; ?> 
	
	<div class="contenu">
	    <ul class="box_contenu1 textalib">
	    <br>
	    Adresse email du Joueur : <input type="text" name="email" id='email'/> <br />
	
	    Mot de passe : <input type="password" name="password" /> <br />
	
	    Activation :
	    oui <input type="radio" id="auth_activation" name="auth_activation" value="oui" checked>
	    non <input type="radio" id="auth_activation" name="auth_activation" value="non"> <br />
	
	    Gardiennage :
	    oui <input type="radio" id="auth_gardiennage" name="auth_gardiennage" value="oui">
	    non <input type="radio" id="auth_gardiennage" name="auth_gardiennage" value="non" checked> <br />
	
	    </ul>
	    <ul class="box_contenu1	 center"><br>
	    <input type="submit" class='button1' value="Connexion" />
	    <p><a href="/perdu">Perdu ?</a> ou <a href="/inscription">Pas encore inscrit ?</a></p>
	    <br>
	    </ul>    
	</div>
</div>
<b class="xb_b7"></b><b class="xb_b6"></b><b class="xb_b5"></b><b class="xb_b4"></b><b class="xb_b3"></b><b class="xb_b2"></b><b class="xb_b1"></b>
</div>
</form> 

<script language="javascript">
$('email').focus();
</script>
<?php echo $this->render('footer.phtml'); ?>  
