<?php echo $this->render('header.phtml'); ?> 
<div id="logo">
<a href="/">Braldahim</a><br>
  <a href="/"> -> Interface</a><br>
  <a href="/encyclopedie"> -> Encyclop&eacute;die</a><br>
  <a href="/"> -> Forums</a>
</div> 
 
<form action="<?php echo $this->baseUrl ?>/auth/login" method="post"> 
<div class="box_authentification">
<div class="inner">
	<span class="corners-top"><span></span></span>
    <ul class="titre left">Braldahim</ul>
    <ul class="titre right">Authentification</ul>
	<?php if(!empty($this->message)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php echo $this->escape($this->message);?> 
	</div> 
	<?php endif; ?> 
	
	<div class="contenu">
	    <ul class="box_contenu textalia">
	    <br>
	    Nom ou n° du Joueur : <input type="text" name="nom" /> <br />
	
	    Mot de passe : <input type="password" name="password" /> <br />
	
	    Activation :
	    oui <input type="radio" id="auth_activation" name="auth_activation" value="oui" checked>
	    non <input type="radio" id="auth_activation" name="auth_activation" value="non"> <br />
	
	    Gardiennage :
	    oui <input type="radio" id="auth_gardiennage" name="auth_gardiennage" value="oui">
	    non <input type="radio" id="auth_gardiennage" name="auth_gardiennage" value="non" checked> <br />
	
	    </ul>
	    <ul class="box_contenu center"><br>
	    <input type="submit" class='button1' value="Connexion" />
	    <p><a href="<?php echo $this->baseUrl ?>/perdu">Perdu ?</a> ou <a href="<?php echo $this->baseUrl ?>/inscription">Pas encore inscrit ?</a></p>
	    <br>
	    </ul>    
	</div>
	<span class="corners-bottom"><span></span></span>
</div>
</div>
</form> 
 
<?php echo $this->render('footer.phtml'); ?>  
