<div class="box_palmares">

<div class="contenu">

	<div id="depuisToujours">
		<script type="text/javascript" src="<?php echo $this->config->url->site?>/palmares/palmarestop10"></script>
	</div>
	<div id="dernierMois" style="display:none">
		<script type="text/javascript" src="<?php echo $this->config->url->site?>/palmares/palmarestop10derniermois"></script>
	</div>

	<a href="<?php echo $this->config->url->site?>/palmares">Palmarès Complet</a>&nbsp;
</div>

</div>