<div id='box_blabla'>
<ul id="navigation" style="width:99%;text-align:left">
	
	<li id="pocheBlabla">
		<?php $poches[] = "pocheBlabla-head" ?>
      	<h3 id="pocheBlabla-head" class="head" onclick="maccordion(this);">
			Informations
		</h3>
		<ul id="pocheBlabla-body" style="display:none">
			<li>
				<div class="titre textalic textsizec">Messages publics autour de vous</div>
	
				Les messages affichés ci-dessous sont des messages envoyés jusqu'à <?php echo $this->nb_cases_max?> cases aux alentours de votre position.<br />
				Ils sont automatiquement supprimés au bout de 3 jours et vous pouvez envoyer jusqu'à <?php echo $this->nb_messages_max?> messages par tour de jeu.<br />
				<br />
				Le blabla est destiné à l'échange de messages "Role Play" ou tactiques, merci de <a href="/Parametres/contacter">contacter un enquêteur</a> pour tout abus constaté.<br />
				Toute "insulte gratuite" ou propos discriminants seront censurés sans préavis.<br />
			</li>
		</ul>
	</li>
</ul>

<!-- <span onclick="Javascript:_get_('/interface/load/?box=box_blabla');" class="alabel">Rafraîchir</span> -->

<table class="table_liste" style="width:100%;">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>Message</th>
	  </tr>
	</thead>
	<tr class="table_liste">
		
   		<td colspan="4">
   		<?php if ($this->nouveauPossible) : ?>
		<ul id="navigation" style="width:100%;text-align:center" >
			<li id="pocheBlablaMessage">
			<h3 id="pocheBlablaMessage-head" class="head" onclick="maccordion(this);">
			<input type="button" class='button1' name="nouveau_msg" id="nouveau_msg" value="Nouveau Message"/> 
			</h3>
			<ul id="pocheBlablaMessage-body" style="display:none">
				<li>
					<?php include("nouveau.phtml")?>
				</li>
			</ul>
			</li>
		</ul>
		<?php else: ?>
	   	Vous avez déjà envoyé <?php echo $this->user->nb_tour_blabla_braldun?> messages pendant votre tour.<br />
	   	Vous ne pouvez pas en envoyer d'avantage, il faut attendre votre prochain tour.
	   	<?php endif;?>
		</td>
		
   	</tr>
   

  <?php if (count($this->blablaMessages) > 0): ?>
	<tbody>
  	<?php $i = 0; 
  	foreach($this->blablaMessages as $e): ?>
  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
  			<td class="table_liste" style='text-align:left'><i title='le <?php echo $e["date"]?> en <?php echo $e["x"]?> / <?php echo $e["y"]?>'><?php echo $e["braldun"]?></i><br />
	  		<?php echo Bral_Util_BBParser::bbcodeReplace($e["message"]);?>&nbsp;
	  		<p class="a">~</p>
	  		</td>
  		</tr>
  	<?php endforeach; ?>
  	</tbody>
   <?php else: ?>
   	<tr class="table_liste">
   		<td colspan="4">
   			Aucun message
   		</td>
   	</tr>
<?php endif; ?>
</table>
</div>