<ul id="navigation" style="width:auto;text-align:left">
	
	<li id="pocheBlabla">
		<?php $poches[] = "pocheBlabla-head" ?>
      	<h3 id="pocheBlabla-head" class="head" onclick="maccordion(this);">
			Informations
		</h3>
		<ul id="pocheBlabla-body" style="display:none">
			<li>
				<div class="titre textalic textsizec">Messages publics autour de vous</div>
	
				Les messages affichés ci-dessous sont des messages envoyés depuis une position visible dans votre vue.<br />
				Ils sont automatiquement supprimés au bout de 3 jours et vous pouvez envoyer jusqu'à <?php echo $this->nb_messages_max?> messages par tour de jeu.<br />
				<br />
				Le blabla est destiné à l'échange de messages "Role Play" ou tactiques, merci de <a href="/Parametres/contacter">contacter un enquêteur</a> pour tout abus constaté.<br />
				Toute "insulte gratuite" ou propos discriminants seront censurés sans préavis.<br /><br />
			</li>
		</ul>
	</li>
</ul>

<span onclick="Javascript:_get_('/interface/load/?box=box_blabla');" class="alabel">Rafraîchir</span>

<?php if ($this->nouveauPossible) : ?>
	<button type="button" class='button edit' name="nouveau_msg" id="nouveau_msg" onClick="$('#divBlablaMessage-body').toggle()">Nouveau</button>
	<div id="divBlablaMessage-body" style="display:none">
		<?php include("nouveau.phtml")?>
	</div>
<?php else: ?>
Vous avez déjà envoyé <?php echo $this->user->nb_tour_blabla_braldun?> messages pendant votre tour.<br />
Vous ne pouvez pas en envoyer d'avantage, il faut attendre votre prochain tour.<br /><br />
<?php endif;?>

<div id="blabla_messages"></div>
