<form name="myForm" id="myForm">
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='-1'>
	<input type='hidden' name='valeur_1' id='valeur_1' value='envoi' />

<br /><br />

	<?php echo Bral_Helper_BBBoutons::affiche('valeur_messageblabla', 1000)?>
	
	<span>Message</span><br />
	<textarea name="valeur_messageblabla" id="valeur_messageblabla" class="inputbox" rows="10" cols="40" 
	onkeydown="textCount($('#valeur_messageblabla'), $('#characterstypedblabla'), 1000);" 
	onkeyup="textCount($('#valeur_messageblabla'), $('#characterstypedblabla'), 1000); if ($('#valeur_messageblabla').val().length > 2) {$('#envoyer_msg_blabla').attr('disabled',false)} else {$('#envoyer_msg_blabla').attr('disabled',true)}"></textarea>
	
	<br />
	<input style="background-color: lightgray;" readonly="readonly" name="characterstypedblabla" id="characterstypedblabla" size="4" maxlength="4" value="1000" type="text"> Caract&egrave;res restants<br />
	<input type="button" class='button1' name="envoyer_msg_blabla" id="envoyer_msg_blabla" value="Envoyer" onclick="Javascript:$('#nb_valeurs').val(1);$('#valeur_1').val(encodePlus($('#valeur_messageblabla').val()));_get_('/blabla/doaction?caction=do_blabla_message', true);" disabled/> 
</form>