<form name="myForm" id="myForm">
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='-1'>
	<input type='hidden' name='valeur_1' id='valeur_1' value='envoi' />

<br><br>

	<?=Bral_Helper_BBBoutons::affiche('valeur_messageblabla', 1000)?>
	
	<span>Message</span><br>
	<textarea name="valeur_messageblabla" id="valeur_messageblabla" class="inputbox" rows="10" cols="60" 
	onkeydown="textCount($('valeur_messageblabla'),$('characterstypedblabla'),1000);" 
	onkeyup="textCount($('valeur_messageblabla'),$('characterstypedblabla'),1000);if ($('valeur_messageblabla').value.length > 2) {$('envoyer_msg_blabla').disabled=false} else {$('envoyer_msg_blabla').disabled=true}"></textarea>
	
	<br>
	<input style="background-color: lightgray;" readonly="readonly" name="characterstypedblabla" id="characterstypedblabla" size="4" maxlength="4" value="1000" type="text"> Caract&egrave;res restants<br>
	<input type="button" class='button1' name="envoyer_msg_blabla" id="envoyer_msg_blabla" value="Envoyer" onClick="Javascript:$('nb_valeurs').value=1;$('valeur_1').value=encodePlus($('valeur_messageblabla').value);_get_('/blabla/doaction?caction=do_blabla_message', true);" disabled/> 
</form>
