  	Type : 
  	<select name='valeur_2'  onchange="Javascript:_get_('/voir/doaction?caction=ask_voir_monstre&monstre=<?php echo $this->monstre["id_monstre"]?>&menu=evenements&valeur_1=f&valeur_2='+ this.value + '&valeur_3=0')">
  	<?php foreach ($this->typeEvenements as $t) : ?>
  	<option value='<?php echo $t["id_type_evenement"]?>' <?php if ($this->filtre == $t["id_type_evenement"]){echo "selected";}?>><?php echo $t["nom"]?></option>
  	<?php endforeach; ?>
  	</select>
  	<br /><br />
  	
  	<table class="table_liste" style="width:90%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th>Date</th>
			<th>Type</th>
			<th>Description</th>
		  </tr>
		</thead>
		<tfoot class="table_liste">
		  <tr class="table_liste">
		    <th colspan='5'>
			   <?php if ($this->precedentOk === true) : ?>
			   <input type="button" class='button' onclick="Javascript:_get_('/voir/doaction?caction=ask_voir_monstre&monstre=<?php echo $this->monstre["id_monstre"]?>&menu=evenements&valeur_1=p&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>')" value="Page pr&eacute;c&eacute;dente">
			   <?php endif; ?>
			   <?php if ($this->suivantOk === true) : ?>
			   <input type="button" class='button' onclick="Javascript:_get_('/voir/doaction?caction=ask_voir_monstre&monstre=<?php echo $this->monstre["id_monstre"]?>&menu=evenements&valeur_1=s&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>')" value="Page suivante">
			   <?php endif; ?>
		    </th>
		  </tr>
		</tfoot>
  	<?php if ($this->nbEvenements > 0): ?>
	  	
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->evenements as $e): ?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste"><?php echo $e["date"]?></td>
		  		<td class="table_liste"><?php echo $e["type"]?></td>
		  		<td class="table_liste"><?php echo $e["details"]?>&nbsp;</td>
	  		</tr>
	  	<?php endforeach; ?>
	  	</tbody>
	  	
   <?php else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun &eacute;v&eacute;nement
   	 </td>
   	 </tr>
   <?php endif; ?>
   </table>
   <br /><br />
