<br /><br />
<div class="titre textalic textsizea">Profil Officiel</div>
<br />

<table class="table_liste" style="width:90%;">
	
  <tr class="table_liste">
	<th>Date d'apparition</th>
	<th>Le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->monstre["date_creation_monstre"]); ?></th>
  </tr>
  <tr class="table_liste">
	<th>Nombre de Bralduns mis KO</th>
	<td class="table_liste"><?php echo $this->monstre["nb_kill_monstre"] ?></td>
  </tr>
  <tr class="table_liste">
	<th colspan="2"><br /><hr><div class="titre textalic textsizeb">Description</div></th>
  </tr>
  <tr class="table_liste">
  	<td class="table_liste">
		<img src='<?php echo $this->config->static->url?>/images/type_monstre/<?php echo $this->monstre["id_type_monstre"]?>.png'/>
  	</td>
	<td class="table_liste">
		<?php if ($this->monstre["description_type_monstre"] != null) : ?>
			<?php echo $this->monstre["description_type_monstre"] ?>
		<?php else:?>
			Aucune description
		<?php endif;?>
	</td>
  </tr>
</table>


<br /><br />