
<br /><br />
<ul class="titre textalic textsizea">Profil Officiel</ul>
<br />

<table class="table_liste" style="width:90%;">
	
  <tr class="table_liste">
	<th>Date d'apparition</th>
	<th>Le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->monstre["date_creation_monstre"]); ?></th>
  </tr>
  <tr class="table_liste">
	<th>Nombre de Hobbits mis KO</th>
	<td class="table_liste"><?=$this->monstre["nb_kill_monstre"] ?></td>
  </tr>
</table>


<br /><br />