<div class="box_contenu textalic">
	<table width="100%">
		<tr valign="top">
			<td  width="50%">
				<div class="titre textalic textsizeb">
				Sources 
				</div>
				
				<div class="titre textalic textsizee"></div>
				<br/>
				Braldahim est développé sous licence <br/>
				<a href="http://jeu.braldahim.com/licence.txt" class="aWhite">GNU GENERAL PUBLIC LICENSE Version 3.</a><br/>
				<br/>
				Le code source est disponible sur le dépôt GIT : 
				<a href="http://github.com/braldahim/braldahim" class="aWhite">http://github.com/braldahim/braldahim</a>
					<br/><br/>		
				Copyright &copy; 2005-2010, Yvonnick Esnault, Pierre Giraudeau, Maxime Lemonnier.
				
				<br/><br/><br/><br/><br/><br/>
				
				<div class="titre textalic textsizeb">
				Association JeuxWeb.org 
				</div>
				
				<p align="center"><a href="http://www.jeuxweb.org" target="_blank"  class="aWhite">Braldahim est un jeu géré par l'association sans but lucratif JeuxWeb.org </a><br/>
					<a href="http://www.jeuxweb.org" target="_blank"><img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="JeuxWeb" border="0" width="60%"/></a>
				</p>
				<br/><br/>
			</td>
			<td style="border-left: 1px solid #000000;" width="50%">
				<div class="titre textalic textsizeb">
				Images
				</div>
				<br/>
				
				<div class="titre textalic textsizee">Quentin</div>
				Pour les dessins originaux de Braldahim.<br/>
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/fr/" class="aWhite"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/2.0/fr/88x31.png" /></a><br />
				La librairie d'images pour Braldahim par Quentin Ruyant est mise &#224; disposition selon les termes de la 
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/fr/" class="aWhite">licence Creative Commons Paternit&#233;-Partage des Conditions Initiales &#224; l'Identique 2.0 France</a>.
				<br/><br/>
				Cette librairie d'images est accessible sur le <a href="http://github.com/braldahim/braldahim/tree/master/braldahim/public/images/sources/qru/" class="aWhite">dépôt GIT</a>.
				<br/>
			</td>
		</tr>
	</table>
</div>