<ul class="box_contenu1 textalic">

	<table width="100%">
		<tr valign="top">
			<td  width="50%">
				<ul class="titre textalic textsizeb">
				Sources 
				</ul>
				
				<ul class="titre textalic textsizee"></ul>
				<br>
				Braldahim est développé sous licence <br>
				<a href="http://jeu.braldahim.com/licence.txt">GNU GENERAL PUBLIC LICENSE Version 3.</a><br>
				<br>
				Le code source est disponible sur le dépôt SVN : <a href="http://code.google.com/p/braldahim/source">http://code.google.com/p/braldahim/source</a>
					<br><br>		
				Copyright &copy; 2005-2010, Yvonnick Esnault, Pierre Giraudeau, Maxime Lemonnier.
				
				<br><br><br><br><br><br>
				
				<ul class="titre textalic textsizeb">
				Association JeuxWeb.org 
				</ul>
				
				<p align="center"><a href="http://www.jeuxweb.org" target="_blank" class="AllLinks">Braldahim est un jeu géré par l'association sans but lucratif JeuxWeb.org </a><br>
					<a href="http://www.jeuxweb.org" target="_blank"><img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="JeuxWeb" border="0" width="60%"></a>
				</p>
				<br><br>
			</td>
			<td style="border-left: 1px solid #791E1E;" width="50%">
				<ul class="titre textalic textsizeb">
				Images
				</ul>
				<br>
				
				<ul class="titre textalic textsizee">Quentin</ul>
				Pour les dessins originaux de Braldahim.<br>
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/fr/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/2.0/fr/88x31.png" /></a><br /><span xmlns c="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/StillImage" property="dc:title" rel="dc:type">
				La librairie d'image pour Braldahim</span> par Quentin Ruyant est mis &#224; disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/fr/">licence Creative Commons Paternit&#233;-Partage des Conditions Initiales &#224; l'Identique 2.0 France</a>.
				<br><br>
				Cette librairie d'image est accessible sur le <a href="http://code.google.com/p/braldahim/source/browse/#svn/trunk/braldahim/public/images/sources/qru">dépôt SVN</a>.
				<br>
			</td>
		</tr>
	</table>
</ul>