<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">Rondins</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td class="table_liste" valign="bottom">
			<?php echo $this->nb_rondins ?>
			<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/elements/rondin.png' alt='rondin'/>
			</td>
		</tr>
	</tbody>
</table>