
Votre laban contient plusieurs poches. Cliquez sur celle(s) que vous souhaitez ouvrir. <br /><br />

   <input type='button' class='button1' value='Fermer Tout' onClick="$('fermer_pocheLaban').click();">
   <input type='button' class='button1' value='Ouvrir Tout' onClick="$('ouvrir_pocheLaban').click();">
   
<?=$pocheLabans = null; ?>
	<ul id="navigation" style="width:99%;text-align:left">
		
		<li id="pocheLabanCastars">
			<? $pocheLabans[] = "pocheLabanCastars-head" ?>
      		<h3 id="pocheLabanCastars-head" class="head" onClick="maccordion(this);" />
				Poche pour les castars
			</h3>
			<ul id="pocheLabanCastars-body" style="display:none">
				<li>
					<? $this->nb_castars = $this->user->castars_hobbit; ?>
					<?=$this->render("/interface/commun/materiaux/castars.phtml") ?>
				</li>
			</ul>
		</li>
		
		<? if (count($this->tabHobbitMetiers) > 0) :?>
			<? foreach ($this->tabHobbitMetiers as $m) : ?>
				<? if ($m["nom_systeme"] == "bucheron" || $m["nom_systeme"] == "guerrier") { continue; }?>
				<li id="pocheLaban<?=$m["nom_systeme"]?>">
					<? $pocheLabans[] = "pocheLaban".$m["nom_systeme"]."-head" ?>
		      		<h3 id="pocheLaban<?=$m["nom_systeme"]?>-head" class="head" onClick="maccordion(this);" />
						Poche <?=$m["nom"]?>
					</h3>
					<ul id="pocheLaban<?=$m["nom_systeme"]?>-body" style="display:none">
						<li>
							<? include("poche_".$m["nom_systeme"].".phtml") ?>
						</li>
					</ul>
				</li>
			<? endforeach; ?>
		<? endif; ?>
		
		<? if (count($this->tabMetiers) > 0) :?>
			<? foreach ($this->tabMetiers as $m) : ?>
				<? if ($m["a_afficher"] == true) : ?>
					<? if ($m["nom_systeme"] == "bucheron" || $m["nom_systeme"] == "guerrier") { continue; }?>
					<li id="pocheLaban<?=$m["nom_systeme"]?>">
						<? $pocheLabans[] = "pocheLaban".$m["nom_systeme"]."-head" ?>
			      		<h3 id="pocheLaban<?=$m["nom_systeme"]?>-head" class="head" onClick="maccordion(this);" />
							Poche mat&eacute;riaux 
							<? if ($m["nom_systeme"] == "mineur" || $m["nom_systeme"] == "chasseur" || $m["nom_systeme"] == "herboriste") : ?>
							r&eacute;colt&eacute;s
							<? else: ?>
							transform&eacute;s 
							<? endif; ?>
							par un <?=$m["nom"]?>
						</h3>
						<ul id="pocheLaban<?=$m["nom_systeme"]?>-body" style="display:none">
							<li>
								<? include("poche_".$m["nom_systeme"].".phtml") ?>
							</li>
						</ul>
					</li>
				<? endif; ?>
			<? endforeach; ?>
		<? endif; ?>
		
		<li id="pocheLabanRune">
			<? $pocheLabans[] = "pocheLabanRune-head" ?>
      		<h3 id="pocheLabanRune-head" class="head" onClick="maccordion(this);" />
				Poche pour les runes
			</h3>
			<ul id="pocheLabanRune-body" style="display:none">
				<li>
					<? include("poche_rune.phtml") ?>
				</li>
			</ul>
		</li>
		<li id="pocheLabanEquipement">
			<? $pocheLabans[] = "pocheLabanEquipement-head" ?>
      		<h3 id="pocheLabanEquipement-head" class="head" onClick="maccordion(this);" />
				Poche pour les pi&egrave;ces d'&eacute;quipements
			</h3>
			<ul id="pocheLabanEquipement-body" style="display:none">
				<li>
					<? include("poche_equipement.phtml") ?>
				</li>
			</ul>
		</li>
		<li id="pocheLabanMunition">
			<? $pocheLabans[] = "pocheLabanMunition-head" ?>
      		<h3 id="pocheLabanMunition-head" class="head" onClick="maccordion(this);" />
				Poche pour les munitions
			</h3>
			<ul id="pocheLabanMunition-body" style="display:none">
				<li>
					<? include("poche_munition.phtml") ?>
				</li>
			</ul>
		</li>
		<li id="pocheLabanPotion">
			<? $pocheLabans[] = "pocheLabanPotion-head" ?>
      		<h3 id="pocheLabanPotion-head" class="head" onClick="maccordion(this);" />
				Poche pour les potions
			</h3>
			<ul id="pocheLabanPotion-body" style="display:none">
				<li>
					<? include("poche_potion.phtml") ?>
				</li>
			</ul>
		</li>
		<li id="pocheLabanAliment">
			<? $pocheLabans[] = "pocheLabanAliment-head" ?>
      		<h3 id="pocheLabanAliment-head" class="head" onClick="maccordion(this);" />
				Poche pour les aliments
			</h3>
			<ul id="pocheLabanAliment-body" style="display:none">
				<li>
					<? include("poche_aliment.phtml") ?>
				</li>
			</ul>
		</li>
		<li id="pocheLabanTabac">
			<? $pocheLabans[] = "pocheLabanTabac-head" ?>
      		<h3 id="pocheLabanTabac-head" class="head" onClick="maccordion(this);" />
				Poche pour les feuilles de tabac
			</h3>
			<ul id="pocheLabanTabac-body" style="display:none">
				<li>
					<? include("poche_tabac.phtml") ?>
				</li>
			</ul>
		</li>
	</ul>
   <? 
   $jsFermer = "";
   $jsOuvrir = "";
   foreach ($pocheLabans as $p) :
   	$jsFermer .= "maccordion_fermer($('$p'));";
    $jsOuvrir .= "maccordion_ouvrir($('$p'));";
   endforeach; ?>
   
   <input type='button' class='button1' id="fermer_pocheLaban" name="fermer_pocheLaban" value='Fermer Tout' onClick="<?=$jsFermer ?>">
   <input type='button' class='button1' id="ouvrir_pocheLaban" name="ouvrir_pocheLaban"  value='Ouvrir Tout' onClick="<?=$jsOuvrir ?>">
  