<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">&nbsp;</th>
			<th style="width:auto; padding:5px;">Viande pr&eacute;par&eacute;e</th>
			<th style="width:auto; padding:5px;">Rations</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Quantit&eacute;</td>
			<td class="table_liste">
				<?=$this->laban["nb_viande_preparee"] ?>
			</td>
			<td class="table_liste">
				<?=$this->laban["nb_ration"] ?>
			</td>
		</tr>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Poids</td>
			<td class="table_liste" style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_VIANDE_PREPAREE?> Kg">
				<?=($this->laban["nb_viande_preparee"]*Bral_Util_Poids::POIDS_VIANDE_PREPAREE) ?> Kg
			</td>
			<td class="table_liste" style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_RATION?> Kg">
				<?=($this->laban["nb_ration"]*Bral_Util_Poids::POIDS_RATION) ?> Kg
			</td>
		</tr>
	</tbody>
</table>