<? if ($this->nb_runes == 0) : ?>
   <center><i>Vide</i></center>
<? else : ?>
	<? if (count($this->runesNonIdentifiees) > 0) : ?>
		<ul class="titre textalic textsized">Runes non identifi&eacute;es</ul><br />
		<table class="table_liste" style="width:auto; padding:5px;" >
			<tbody>
			  <? $i = 0;
		      foreach ($this->runesNonIdentifiees as $r) : 
		     	 if ($i % 3 == 0) echo "<tr class='table_liste'>"; 
		    	?>
		    	<td class="table_liste table_liste_border" align="center">
		    		<ul style="position:absolute; text-align:center;"><br /> n&deg;<?=$r["id_rune"]?></ul>
		    		<img src="/public/images/runes/rune_transparente.png"  class="rune" title="Rune non identifi&eacute;e n&deg;<?=$r["id_rune"]?>" alt="Rune non identifi&eacute;e n&deg;<?=$r["id_rune"]?>" />
		    	</td>
		    	<? if ($i % 3 == 2) echo "</tr>";
		    	$i++; 
		     endforeach;
		     if  ($i % 3 != 0) echo "</tr>"; 
		     ?>
			</tbody>
		</table>
		<br />
	<? endif ?>

	<? if (count($this->runesIdentifiees) > 0) : ?>
		<ul class="titre textalic textsized">Runes identifi&eacute;es</ul><br />
		<table class="table_liste" style="width:auto; padding:5px;" >
			<tbody>
			  <? $i = 0;
		      foreach ($this->runesIdentifiees as $r) : 
		     	 if ($i % 3 == 0) echo "<tr class='table_liste'>"; 
		    	?>
		    	<td class="table_liste table_liste_border">
		    		<? if ($r["image"] != ""): ?>
		    			<img src="/public/images/runes/<?=$r["image"]?>"  class="rune" title="<?=$r["type"]?> n&deg;<?=$r["id_rune"]?> : <?=htmlentities(addslashes($r["effet_type_rune"])) ?>" alt="<?=$r["type"]?> n&deg;<?=$r["id_rune"]?>"  />
	    			<? else: ?>
		    			<?=$r["type"]?> (<?=$r["id_rune"]?>)
		    		<? endif; ?>
		    	</td>
		    	<? if ($i % 3 == 2) echo "</tr>";
		    	$i++; 
		     endforeach;
		     if  ($i % 3 != 0) echo "</tr>"; 
		     ?>
			</tbody>
		</table>
	<? endif; ?>
<? endif; ?>