<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">Viande pr&eacute;par&eacute;e</th>
			<th style="width:auto; padding:5px;">Rations</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td class="table_liste">
				<?=$this->laban["nb_viande_preparee"] ?>
			</td>
			<td class="table_liste">
				<?=$this->laban["nb_ration"] ?>
			</td>
		</tr>
	</tbody>
</table>