<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">&nbsp;</th>
			<th style="width:auto; padding:5px;">Peaux</th>
			<th style="width:auto; padding:5px;">Viande fra&icirc;che</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Quantit&eacute;</td>
			<td class="table_liste">
			<?=$this->laban["nb_peau"] ?>
			</td>
			<td class="table_liste">
			<?=$this->laban["nb_viande"] ?>
			</td>
		</tr>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Poids</td>
			<td class="table_liste" style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_PEAU?> Kg">
			<?=($this->laban["nb_peau"]*Bral_Util_Poids::POIDS_PEAU) ?> Kg
			</td>
			<td class="table_liste" style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_VIANDE?> Kg">
			<?=($this->laban["nb_viande"]*Bral_Util_Poids::POIDS_VIANDE) ?> Kg
			</td>
		</tr>
	</tbody>
</table>