  <? if ($this->nb_partieplantes > 0) : ?>
    <? if ($this->nb_partieplantes==1):$s=''; else:$s='s';endif; ?>
    &eacute;l&eacute;ment<?=$s?> (brut<?=$s?>) de plantes : <br />
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->partieplantes as $p) : 
    	 
    	if ($i % 3 == 0) echo "<tr>"; 
    	 
    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br />"; 
    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br />"; 
    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite"])."<br />";
    	$titre = htmlentities($p["nom_plante"])." : ".htmlentities($p["nom_type"]);
    	?>
    	<td <?=Bral_Helper_Tip::jsTip($textPlante, $titre) ?>>
    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite"]?> <?=htmlentities($p["nom_type"])?><?if ($p["quantite"]>0) echo "s"; ?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table>
   <? endif; ?>