<div class='comp_titre'><?php echo $this->nomAction ?></div>

 <div class='comp_contenu'>
	 <div id='<?php echo $this->nomSysteme?>_text' style="display:block">
	<?php echo $this->texte ?>
		<br />
	 </div>
	 
	 <div id='<?php echo $this->nomSysteme?>_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=35><?php echo Bral_Helper_Affiche::copie($this->texte); ?></textarea>
	</div>
 </div>

<?php if ($this->reloadInterface == true): ?>
	<input type='button' class='button' value='Fermer' onclick='_get_("/interface/reload");fermeBralBox();'>
<?php else: ?>
	<?php echo Bral_Helper_Fermer::affiche(); ?>
<?php endif; ?>

<input type='button' class='button' value='Copier' onclick="javascript:switch2div('<?php echo $this->nomSysteme?>_text','<?php echo $this->nomSysteme?>_copie');">