 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<? if ($this->match != null) : ?>
	Pour <?=$this->nb_pa?> PA et <?=$this->nb_castars?> castars, vous pouvez vous d&eacute;sinscrire du match de soule
	sur le <?=$this->match["nom_soule_terrain"]?>.
	<? else: ?>
		Vous ne pouvez pas vous désinscrire, le match débute bientôt.
	<? endif;?>
 </div>
 <br />

<? if ($this->assezDePa === false) :?>
	Vous n'avez pas assez de PA.
<? elseif ($this->assezDeCastars === false) : ?>
	Vous n'avez pas assez de castars.
<? endif; ?>
 
</form>
<br />
<? if ($this->desinscriptionPossible === true): ?>
<input type='button' class='button1' id='bouton_desinscription' value='D&eacute;sinscription' onClick='this.disabled=true;_get_("/soule/doaction?caction=do_soule_desinscription");'>
<? endif;?>