 <input type='hidden' id='nb_valeurs-soule_desinscription' name='nb_valeurs-soule_desinscription' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<?php if ($this->match != null) : ?>
	Pour <?php echo $this->nb_pa?> PA et <?php echo $this->nb_castars?> castars, vous pouvez vous d&eacute;sinscrire du match de soule
	sur le <?php echo $this->match["nom_soule_terrain"]?>.
	<?php else: ?>
		Vous ne pouvez pas vous désinscrire, le match débute bientôt.
	<?php endif;?>
 </div>
 <br />

<?php if ($this->assezDePa === false) :?>
	Vous n'avez pas assez de PA.
<?php elseif ($this->assezDeCastars === false) : ?>
	Vous n'avez pas assez de castars.
<?php endif; ?>
 
</form>
<br />
<?php if ($this->desinscriptionPossible === true): ?>
<input type='button' class='button' id='bouton_desinscription' value='D&eacute;sinscription' onclick='this.disabled=true;_get_("/soule/doaction?caction=do_soule_desinscription", "soule_desinscription");'>
<?php endif;?>