 <input type='hidden' id='nb_valeurs-soule_inscription' name='nb_valeurs-soule_inscription' value='2'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	<?php if ($this->hibernationPrevue === true) : ?>
 	Vous ne pouvez pas vous inscrire &agrave; un match de soule avec une hibernation de pr&eacute;vue.<br />
 	
 	<?php elseif ($this->donjonEnCours === true) : ?>
 	Vous ne pouvez pas vous inscrire &agrave; un match de soule en étant dans un Donjon ou inscrit à un Donjon.<br />
 	
 	<?php else: ?>
		Pour <?php echo $this->nb_pa?> PA et <?php echo $this->nb_castars?> castar<?php if ($this->nb_castars > 1): echo 's'; endif?>, vous pouvez vous inscrire pour le prochain match de soule
		sur le <?php echo $this->terrainCourant["nom_soule_terrain"]?>.
	 </div>
	 <br />
	
		<?php if ($this->assezDePa === false) :?>
			Vous n'avez pas assez de PA.
		<?php elseif ($this->assezDeCastars === false) : ?>
			Vous n'avez pas assez de castars.
		<?php //elseif ($this->user->est_engage_braldun == "oui") : ?>
			<!-- Vous &ecirc;tes engag&eacute;. -->
		<?php else: ?>
	 	&Eacute;quipe :<br />
	 
		<select name='valeur_1-soule_inscription' id="valeur_1-soule_inscription" onchange="javascript:if ($('#valeur_1-soule_inscription').val() ==-1 || $('#valeur_2-soule_inscription').val() ==-1){$('#bouton_inscription').attr('disabled', true) } else {$('#bouton_inscription').attr('disabled',false) }">
			<option value='-1'>(Choisissez une &eacute;quipe)</option>
			<?php foreach ($this->tabEquipes as $k => $e) : ?>
			<option value="<?php echo $k?>" <?php if ($e["inscription_possible"] !=  true): echo "disabled"; endif;?>>
				<?php echo $e["nom_equipe"]?> (<?php echo $e["nb_inscrits"]?> inscrit<?php if ($e["nb_inscrits"] > 1): echo "s"; endif;?>)
				<?php if ($e["inscription_possible"] !=  true): echo " : nombre max de joueurs atteint"; endif;?>
			</option>
			<?php endforeach; ?>
		</select><br /><br />
		<br />
		
		Où voulez-vous que la roulotte vous dépose après le match ?<br />
		<select name='valeur_2-soule_inscription' id="valeur_2-soule_inscription" onchange="javascript:if ($('#valeur_1-soule_inscription').val() ==-1 || $('#valeur_2-soule_inscription').val() ==-1){$('#bouton_inscription').attr('disabled', true) } else {$('#bouton_inscription').attr('disabled',false) }">
			<option value='-1'>(Choisissez le retour)</option>
			<option value="1">&Agrave; la position X,Y d'avant match</option>
			<option value="2">&Agrave; la ville la plus proche du terrain</option>
		</select>
		<br /><br />
		
		<?php endif; ?>
	<?php endif;?>
 
</form>
<br />
<?php if ($this->inscriptionPossible === true): ?>
<input type='button' class='button' id='bouton_inscription' value='Inscription' onclick='this.disabled=true;_get_("/soule/doaction?caction=do_soule_inscription", "soule_inscription");' disabled>
<?php endif;?>