 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
	Pour 1 PA et 20 castars, vous pouvez vous inscrire pour le prochain match de soule
	sur le <?=$this->terrainCourant["nom_soule_terrain"]?>.
 </div>
 <br>

	<? if ($this->assezDePa === false) :?>
		Vous n'avez pas assez de PA.
	<? elseif ($this->assezDeCastars === false) : ?>
		Vous n'avez pas assez de castars.
	<? elseif ($this->user->est_engage_hobbit == "oui") : ?>
		Vous &ecirc;tes engag&eacute;.
	<? else: ?>
 	&Eacute;quipe :<br>
 
	<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_inscription').disabled=true } else {$('bouton_inscription').disabled=false }">
		<option value='-1'>(Choisis une &eacute;quipe)</option>
		<? foreach ($this->tabEquipes as $k => $e) : ?>
		<option value="<?=$k?>" <? if ($e["inscription_possible"] !=  true): echo "disabled"; endif;?>>
			<?=$e["nom_equipe"]?> (<?=$e["nb_inscrits"]?> inscrit<? if ($e["nb_inscrits"] > 1): echo "s"; endif;?>)
			<? if ($e["inscription_possible"] !=  true): echo " : nombre max de joueurs atteint"; endif;?>
		</option>
		<? endforeach; ?>
	</select><br /><br />
	
	<? endif; ?>
 
</form>
<br />
<? if ($this->inscriptionPossible === true): ?>
<input type='button' class='button1' id='bouton_inscription' value='Inscription' onClick='this.disabled=true;_get_("/soule/doaction?caction=do_soule_inscription");' disabled>
<? endif;?>