
<br>
<ul class="titre textalic textsizec">

	<?=$this->terrainCourant["nom_soule_terrain"]?>

</ul>

<br>
Développement en cours.<br><br>


<? if ($this->inscriptionPossible === true): ?>
	
	
	<? if ($this->user->activation == true) :?>
	Vous pouvez vous inscrire.
		<input type="button" class='button1' value="1 PA - Inscription"
	  onClick="Javascript:_get_('/soule/doaction?caction=ask_soule_inscription');"/>
	<? else: ?>
	Tour non activ&eacute; &agrave; la connexion, activez-le pour vous inscrire.
	<? endif;?>
 
<? else:?>
	<?=$this->inscriptionNonPossibleInfo?>
<? endif; ?>

<?php include("voir/equipes.phtml")?>