
<br>
<ul class="titre textalic textsizec">
	<?=$this->terrainCourant["nom_soule_terrain"]?>
</ul>
<br>

<? if ($this->matchEnCours != null) : ?>
	Il y a actuellement un match en cours sur ce terrain. <br>
	<? if ($this->matchEnCours["x_ballon_soule_match"] != null && $this->matchEnCours["y_ballon_soule_match"]) :?>
		Le ballon est actuellement libre et se trouve en x:<?=$this->matchEnCours["x_ballon_soule_match"]?>,
		y:<?=$this->matchEnCours["y_ballon_soule_match"]?>
	<? elseif ($this->matchEnCours["id_fk_joueur_ballon_soule_match"] != null && $this->porteur != null): ?>
		Le ballon est actuellement port&eacute; par <?=Bral_Util_Lien::getJsBraldun($this->matchEnCours["id_fk_joueur_ballon_soule_match"], $this->porteur["prenom_braldun"]." ".$this->porteur["nom_braldun"]." (".$this->porteur["id_braldun"].")")?>
		qui est en x:<?=$this->porteur["x_braldun"]?> y:<?=$this->porteur["y_braldun"]?>
	<? else: ?>
	Erreur. Merci de le signaler sur le forum.
	<? endif;?>
<? else: ?>
	Il n'y a actuellement aucun match en cours sur ce terrrain.
<? endif;?>

<table width="100%">
	<tr>
		<td valign="top"><? if ($this->matchEnCours != null) : include("voir/carte.phtml"); endif;?></td>
		<td valign="top"><? if ($this->matchEnCours != null) : include("voir/evenements.phtml"); endif;?></td>
	</tr>
</table>
<br><br>

<? if ($this->inscriptionPossible === true): ?>
	<? if ($this->user->activation == true) :?>
		Vous pouvez vous inscrire.
		<? if ($this->user->pa_braldun >= 1) : 
	      $attr = "onClick=\"Javascript:_get_('/soule/doaction?caction=ask_soule_inscription');\"";
	    else:
	      $attr = "disabled";
	    endif;?>
		<input type="button" class='button1' value="0 PA - Inscription" <?=$attr?>/>
	<? else: ?>
	Tour non activ&eacute; &agrave; la connexion, activez-le pour vous inscrire.
	<? endif;?>
<? else:?>
	<?=$this->inscriptionNonPossibleInfo?>
	<br>
	<? if ($this->desinscriptionPossible === true): ?>
		Vous pouvez vous désinscrire.
		<? if ($this->user->pa_braldun >=2) : 
	      $attr = "onClick=\"Javascript:_get_('/soule/doaction?caction=ask_soule_desinscription');\"";
	    else:
	      $attr = "disabled";
	    endif;?>
		<input type="button" class='button1' value="2 PA - Désinscription" <?=$attr?>/>
	<? endif; ?>
	<? if ($this->deinscriptionNonPossibleInfo != "") : ?>
		<br><?=$this->deinscriptionNonPossibleInfo ?><br>
	<? endif;?>
<? endif; ?>

<?php include("voir/equipes.phtml")?>