
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th colspan="4">
			Qu&ecirc;te de la <?php echo $this->quete["nom_lieu"]?>,
		  	<?php if ($this->quete["date_fin_quete"] != null): ?> 
		  		terminée le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->quete["date_fin_quete"]) ?>
		  	<?php else: ?>
		  		en cours
		  	<?php endif;?>
			</th>
		  </tr>
		  <tr class="table_liste">
			<th>N&deg;</th>
			<th>D&eacute;tails</th>
			<th>&Eacute;tat</th>
			<th>Objectifs remplis</th>
		  </tr>
		</thead>
		<tbody>
		<?php if ($this->etapes != null): ?>
		  <?php $i = 0; 
		  foreach($this->etapes as $e): ?>
		  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste">&Eacute;tape n&deg; <?php echo $e["ordre_etape"]?></td>
		  		<td class="table_liste">
		  		<?php if ($e["date_debut_etape"] != null) : ?>
			  		<?php echo $e["libelle_etape"]?>
		  		<?php else: ?>
		  			non r&eacute;v&eacute;l&eacute;e
		  		<?php endif;?>
		  		</td>
		  		<td class="table_liste">
		  		<?php if ($e["est_terminee_etape"] == "oui") : ?>
			  		Termin&eacute;, le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$e["date_fin_etape"]) ?>
		  		<?php elseif ($e["date_debut_etape"] != null) : ?>
		  			En Cours
		  		<?php else: ?>
		  			Non d&eacute;but&eacute;
		  		<?php endif;?>
		  		</td>
		  		<td class="table_liste">
		  		<?php echo $e["objectif_etape"]?>
		  		</td>
		  	</tr>
		  <?php endforeach; ?>
		  
		 
		  <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			  <td class="table_liste">
			  Gains
			  </td>
			  <td class="table_liste" colspan="3">
			   <?php if ($this->quete["date_fin_quete"] != null): ?>
			 	 <?php echo nl2br($this->quete["gain_quete"])?>
			   <?php else: ?>
			  		Les gains seront indiqu&eacute;s ici &agrave; la fin de la qu&ecirc;te.
			   <?php endif;?>
			  </td>
		  </tr>
		 
		<?php else: ?>
		   <tr class="table_liste">
		   	<td colspan="5">
		   		Aucune &eacute;tape
		   	</td>
		   </tr>
		<?php endif; ?>
	   </tbody>
	</table>
					