
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th colspan="3">
			Qu&ecirc;te de la <?=$this->quete["nom_lieu"]?>,
		  	<? if ($this->quete["date_fin_quete"] != null): ?> 
		  		terminée
		  	<? else: ?>
		  		en cours
		  	<? endif;?>
			</th>
		  </tr>
		  <tr class="table_liste">
			<th>N&deg;</th>
			<th>D&eacute;tails</th>
			<th>&Eacute;tat</th>
		  </tr>
		</thead>
		<tbody>
		<? if ($this->etapes != null): ?>
		  <? $i = 0; 
		  foreach($this->etapes as $e): ?>
		  	<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">&Eacute;tape n&deg; <?=$e["ordre_etape"]?></td>
		  		<td class="table_liste">
		  		<? if ($e["date_debut_etape"] != null) : ?>
			  		<?=$e["libelle_etape"]?>
		  		<? else: ?>
		  			non r&eacute;v&eacute;l&eacute;e
		  		<? endif;?>
		  		</td>
		  		<td class="table_liste">
		  		<? if ($e["est_terminee_etape"] == "oui") : ?>
			  		Termin&eacute;, le <?=$e["date_fin_etape"]?>
		  		<? elseif ($e["date_debut_etape"] != null) : ?>
		  			En Cours
		  		<? else: ?>
		  			Non d&eacute;but&eacute;
		  		<? endif;?>
		  		</td>
		  	</tr>
		  <? endforeach; ?>
		<? else: ?>
		   <tr class="table_liste">
		   	<td colspan="5">
		   		Aucune &eacute;tape
		   	</td>
		   </tr>
		<? endif; ?>
	   </tbody>
	</table>
					