
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th colspan="4">
			Qu&ecirc;te de la <?=$this->quete["nom_lieu"]?>,
		  	<? if ($this->quete["date_fin_quete"] != null): ?> 
		  		terminée le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->quete["date_fin_quete"]) ?>
		  	<? else: ?>
		  		en cours
		  	<? endif;?>
			</th>
		  </tr>
		  <tr class="table_liste">
			<th>N&deg;</th>
			<th>D&eacute;tails</th>
			<th>&Eacute;tat</th>
			<th>Objectifs remplis</th>
		  </tr>
		</thead>
		<tbody>
		<? if ($this->etapes != null): ?>
		  <? $i = 0; 
		  foreach($this->etapes as $e): ?>
		  	<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">&Eacute;tape n&deg; <?=$e["ordre_etape"]?></td>
		  		<td class="table_liste">
		  		<? if ($e["date_debut_etape"] != null) : ?>
			  		<?=$e["libelle_etape"]?>
		  		<? else: ?>
		  			non r&eacute;v&eacute;l&eacute;e
		  		<? endif;?>
		  		</td>
		  		<td class="table_liste">
		  		<? if ($e["est_terminee_etape"] == "oui") : ?>
			  		Termin&eacute;, le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$e["date_fin_etape"]) ?>
		  		<? elseif ($e["date_debut_etape"] != null) : ?>
		  			En Cours
		  		<? else: ?>
		  			Non d&eacute;but&eacute;
		  		<? endif;?>
		  		</td>
		  		<td class="table_liste">
		  		<?=$e["objectif_etape"]?>
		  		</td>
		  	</tr>
		  <? endforeach; ?>
		  
		 
		  <tr class="table_liste<?=($i % 2);$i++; ?>">
			  <td class="table_liste">
			  Gains
			  </td>
			  <td class="table_liste" colspan="3">
			   <? if ($this->quete["date_fin_quete"] != null): ?>
			 	 <?=nl2br($this->quete["gain_quete"])?>
			   <? else: ?>
			  		Les gains seront indiqu&eacute;s ici &agrave; la fin de la qu&ecirc;te.
			   <? endif;?>
			  </td>
		  </tr>
		 
		<? else: ?>
		   <tr class="table_liste">
		   	<td colspan="5">
		   		Aucune &eacute;tape
		   	</td>
		   </tr>
		<? endif; ?>
	   </tbody>
	</table>
					