<?php Zend_Loader::loadClass('Bral_Helper_Contenu'); ?>
<?php if (count($this->minerais) == 0) : ?>
   <center><i>vide</i></center>
<?php else : ?>
    <table class="table_liste" style="width:auto; padding:5px;" >
		<thead class="table_liste">
		  <tr class="table_liste">
		  	<?php foreach ($this->minerais as $m) :  ?>
			<th style="width:auto; padding:5px;" ><?php echo htmlspecialchars($m["type"])?></th>
			<?php endforeach; ?>
		  </tr>
		</thead>
		<tbody>
			<tr class="table_liste">
			<?php foreach ($this->minerais as $m) : ?>
			 	<td class="table_liste">
			 		<?php echo Bral_Helper_Contenu::afficheMinerai($m)?>
			 	</td>
			<?php endforeach; ?>
			</tr>
		</tbody>
	</table>
<?php endif; ?>
<br />