<?php echo $this->render('/commun/menu_bourg.phtml')?>
<br />
<div class="box_contenu textalic">
	<div class="titrea textalic textsizea">Étals</div><br />
	
<table width='100%'>
<tr>
	<td>
		Filtre par comté: 
		<br />
		<select id="region" name="region" onchange="document.location.href = '/etals/?regionselect='+this.value">
		<?php foreach($this->regions as $k => $e): ?>
			<option value="<?php echo $k?>" <?php if ($this->regionSelect == $k): echo "selected" ; endif;?>><?php echo $e?></option>
		<?php endforeach;?>
		</select>
	</td>
</tr>
</table>

<br /><br />


<?php echo $this->render("/interface/commun/lots.phtml"); ?>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />



</div>