<?php 
	$i = 0; 
	foreach ($this->histoires as $info) : ?>
		<table class="table_liste" style="width:90%">
    
		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			<td class="table_liste" style="height:250px;text-align: justify; vertical-align:top">
			
			Parution le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$info["date_info_jeu"]) ?>
			<br/>
			<?php if ($info["titre_info_jeu"] != null && $info["titre_info_jeu"] != "") :?>
				<br/>
				<p class="titre textalic textsized center"><?php echo stripslashes($info["titre_info_jeu"])?></p>
			<?php endif;?>
			
			<?php if (Bral_Util_ConvertDate::get_date_add_time_to_date($info["date_info_jeu"], "36:00:00") > date("Y-m-d H:i:s")): ?>
				<img src="<?php echo $this->config->static->url?>/images/new.gif" alt="New" title="information de moins de 36 heures" style="cursor:pointer" />
			<?php else:?>
				&nbsp;
			<?php endif;?>
			
			<div class="gazette_histoire">
				<?php echo Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
				<?php if ($info["lien_wiki_info_jeu"] != null) :?>
					<a href="<?php echo htmlspecialchars($info["lien_wiki_info_jeu"])?>">...Lire la suite.</a>
				<?php endif;?>
			</div>
			
			<?php if ($info["lien_info_jeu"] != null && substr($info["lien_info_jeu"], 0, 26) == "http://forum.braldahim.com") :?>
				<br/>Les Braldûns en discutent
				<a href="<?php echo htmlspecialchars($info["lien_info_jeu"])?>">sur le forum.</a>
			<?php endif;?>
			<br/><br/>
			<iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo htmlspecialchars($info["lien_wiki_info_jeu"])?>&amp;layout=button_count&amp;show_faces=false&amp;width=100&amp;action=like&amp;font=verdana&amp;colorscheme=dark&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:21px;" allowTransparency="true"></iframe>
			<a href="http://twitter.com/share" class="twitter-share-button" data-url="<?php echo htmlspecialchars($info["lien_wiki_info_jeu"])?>" data-text="<?php echo stripslashes($info["titre_info_jeu"])?>" data-count="horizontal" data-via="Braldahim" data-lang="fr">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
			</td>
		</tr>
	</table>
<?php endforeach; ?>
