<?php echo $this->render('header.phtml'); ?>  
<?php echo $this->render('headerNonAuth.phtml'); ?> 
<div id="wrapper">
<?php echo $this->render('headerArchives.phtml'); ?> 

<table width="100%">
	<tr>
		<td width="40%" valign="top" align="right">
			<div style="width:200px">
			<div class="inner">
				<div class="contenu">
						Filtre par année: <select id="annee" name="annee" onchange="document.location.href = '/gazette/?anneeselect='+this.value+'&uid='+(new Date()).valueOf()">
						<?php foreach($this->annees as $a): ?>
							<option value="<?php echo $a?>" <?php if ($this->anneeSelect == $a): echo "selected='true'" ; endif;?>><?php echo $a?></option>
						<?php endforeach;?>
						</select>
						
						<br/><br/>
						
						<?php echo count($this->histoires)?> article<?php if (count($this->histoires) > 0) : echo "s"; endif; ?>
						 dans la gazette pour l'année <?php echo $this->anneeSelect?> 
				</div>
			</div>
			</div>
			</td>
			
			<td width="60%" valign="top" align="left">
			<?php include("gazette.phtml") ?>	
			<br/>
		</td>
	</tr>
</table>
</div>
<?php echo $this->render('footer.phtml'); ?>  