<input type='hidden' id='menuAncienEchoppes' />
<ul id="navigation">
	<li id="menuVisibleEchoppes">
		<h3 id="" class="head">Construction d'&eacute;choppes</h3>
	</li>	
	<? foreach($this->tabMetiers as $m) : ?>	
	<li id="menuEchoppes<?=$m["nom_systeme_metier"]?>">
		<h3 id="menuEchoppes<?=$m["nom_systeme_metier"]?>-head" class="head" onClick="accordion(this, 'menuAncienEchoppes', 'menuVisibleEchoppes')">Vos &eacute;choppes 
			<? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>
			<?=htmlentities($m["nom_metier"])?>
		</h3>
		<ul  id="menuEchoppes<?=$m["nom_systeme_metier"]?>-body" style="display:none">
			<? foreach($m["regions"] as $r) : ?>
			<li <? if (isset($r["echoppe"])) : ?> style="cursor:pointer" onClick="_get_('/echoppes/DoAction?caction=ask_echoppes_voir&valeur_1=<?=$r["echoppe"]["id_echoppe"]?>')"<?endif;?>>
				<?=htmlentities($r["nom_region"])?> 
				<? if (isset($r["echoppe"])) : ?>
					x:<?=$r["echoppe"]["x_echoppe"]?> y:<?=$r["echoppe"]["y_echoppe"]?>
				<? else: ?>
					: aucune
				<? endif; ?>
			</li>
			<? endforeach; ?>
		</ul>
	</li>
	<? endforeach; ?>
</ul>
