
<div id="menu_echoppes_metier">
  <? $liste =""; $sep = "";  ?>
   <span id='onglet_echoppes_constructions' class='onglet actif' onClick='Javascript:my_switch("echoppes_constructions", "menu_echoppes_metier");_get_("/echoppes/DoAction?caction=ask_echoppes_liste");'>
      &nbsp;Mes constructions&nbsp;
   </span>
  <? foreach($this->tabMetiers as $m) : ?>
      <span id='onglet_echoppes_<?=$m["nom_systeme_metier"] ?>' class='onglet inactif' onClick='Javascript:my_switch("echoppes_<?=$m["nom_systeme_metier"]?>", "menu_echoppes_metier");'>
      &nbsp;<?=htmlentities($m["nom_metier"]) ?>&nbsp;
      </span>
    <? $liste = $liste.$sep."echoppes_".$m["nom_systeme_metier"]; $sep = ",";?>
  <? endforeach; ?>
  <input type='hidden' id='switch_menu_echoppes_metier' value='<?=$liste ?>'>
</div>

<div id="menu_echoppes">
  <? $liste =""; $sep = ""; ?>
  <? foreach($this->tabMetiers as $m) : ?>
  	<div id="echoppes_<?=$m["nom_systeme_metier"] ?>" style="display:none;">
  	<? foreach($m["regions"] as $r) : ?>
  		<? if (isset($r["echoppe"])) : ?>
  			<span id='onglet_echoppe_<?=$m["nom_systeme_metier"]."_".$r["nom_systeme_region"]?>' class='onglet inactif' onClick="Javascript:my_switch('echoppe_<?=$m["nom_systeme_metier"] ?>_<?= $r["nom_systeme_region"]?>', 'menu_echoppes');_get_('/echoppes/DoAction?caction=ask_echoppes_voir&valeur_1=<?=$r["echoppe"]["id_echoppe"]?>')"'>
     		 &nbsp;<?=htmlentities($r["nom_region"])?>&nbsp;
			x:<?=$r["echoppe"]["x_echoppe"]?> y:<?=$r["echoppe"]["y_echoppe"]?>
			</span>
		<? else: ?>
			<span id='onglet_echoppe_<?=$m["nom_systeme_metier"]."_".$r["nom_systeme_region"]?>' class='onglet inactif' style="cursor:default;">
     		 &nbsp;<?=htmlentities($r["nom_region"])?>&nbsp;
			: aucune
			</span>
		<? endif; ?>
    	<? $liste = $liste.$sep."echoppe_".$m["nom_systeme_metier"]."_".$r["nom_systeme_region"]; $sep = ","; ?>
    <? endforeach; ?>
    </div>
  <? endforeach; ?>
  <input type='hidden' id='switch_menu_echoppes' value='<?=$liste ?>'>
</div>
<hr>