<?php echo $this->render("/interface/box_header.phtml") ?>
 <br />
 <?php if ($this->user->rangCommunaute == Bral_Util_Communaute::ID_RANG_NOUVEAU) : ?>
 	<div class="box_contenu1 textalic">
 	En tant que nouveau membre, vous n'avez pas encore accès à toutes les informations de la communauté.
 	</div>
 <?php elseif ($this->affichageInterne == true) : ?>
	 <?php 
	 $this->estCommunaute = true;
	 echo $this->render("/interface/evenements/publiques.phtml") ?>
	<br />
	 <?php echo $this->render("/interface/evenements/bot.phtml") ?>
<?php else: ?>
	<div class="box_contenu1 textalic">
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
	</div>
<?php endif; ?>

<?php echo $this->render("/interface/box_bottom.phtml") ?>