<?php echo $this->render("/interface/box_header.phtml") ?>
<br />
<?php if ($this->affichageInterne == true) : ?>

	<div class="titre textalic textsizec">Gestion</div>
	
	<?php if ($this->user->rangCommunaute <= Bral_Util_Communaute::ID_RANG_ADJOINT) : ?>
  		Vous avez des droits de gestion : <br />
  		<input type='button' class='button' value='G&eacute;rer les membres' onclick='_get_("/communaute/doaction?caction=ask_communaute_gerermembres");'>
  		<input type='button' class='button' value='G&eacute;rer les rangs' onclick='_get_("/communaute/doaction?caction=ask_communaute_rangs");'>
  		<input type='button' class='button' value='Modifier la description / site web' onclick='_get_("/communaute/doaction?caction=ask_communaute_description");'>
  		<?php if ($this->user->rangCommunaute == Bral_Util_Communaute::ID_RANG_GESTIONNAIRE) : ?>
  			<br />
  			Vous &ecirc;tes le gestionnaire  de cette communaut&eacute;, vous avez accès aux actions suivantes : <br />
			<input type='button' class='button' value='Modifier le Gestionnaire' onclick='_get_("/communaute/doaction?caction=ask_communaute_gestionnaire");'>
  		<?php endif; ?>
  		
  		<br /><br />
  		<div class="titre textalic textsizec">Tribune</div>
  		
  		<?php if ($this->niveauTribune != null && ($this->niveauTribune == Bral_Util_Communaute::NIVEAU_EN_CONSTRUCTION || $this->niveauTribune >= 0)) : ?>
			<?php echo Bral_Helper_Communaute::afficheNiveauTribune($this->niveauTribune);?>
				<?php if ($this->niveauTribune >= Bral_Util_Communaute::NIVEAU_TRIBUNE_CSS) : ?>
					<input type='button' class='button' value='Modifier la CSS de la Communauté' onclick='_get_("/communaute/doaction?caction=ask_communaute_modifiercss");'>
		  		<?php endif;?>
		<?php else:?>
			Votre communauté ne possède pas de <?php echo Bral_Helper_Communaute::afficheNiveauTribune(null, "tribune")?>.
		<?php endif;?>
  		
  		<div id="box_communaute_gestion_interne">
  		</div>
  	
  	<?php else: ?>
  		Vous n'avez aucun droit de gestion.
	<?php endif; ?>
  		
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
<?php endif; ?>


<?php echo $this->render("/interface/box_bottom.phtml") ?>