<?php echo $this->render("/interface/box_header.phtml") ?>
<br />
<?php if ($this->affichageInterne == true) : ?>

	Vous faites partie de la communauté depuis le
  		
  	<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->user->date_entree_communaute_braldun); ?>
  		
  	<hr />
  		
	<?php Zend_Loader::loadClass("Bral_Helper_Tri"); ?>
	<div class="titre textalic textsizec">Liste des Membres</div><br />
	
	Filtrer par rang : 
	<select name='valeur_2'  onchange="Javascript:_get_('/interface/load/?box=box_communaute_membres&valeur_1=f&valeur_2='+ this.value + '&valeur_3=0&valeur_4=-1&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')">
	    <option value="-1">Tous les rangs</option>
	<?php foreach ($this->tabRangs as $r) : ?>
	  	<option value='<?php echo $r["id_type_rang"]?>' <?php if ($this->filtre == $r["id_type_rang"]){echo "selected";}?>><?php echo htmlspecialchars($r["nom"])?></option>
	  	<?php endforeach; ?>
	  	</select>
	  	<br /><br />
	  	
	<table class="table_liste" style="width:100%">
	<thead class="table_liste">
	  <tr class="table_liste" title="Cliquer pour Trier">
		<th>
		<span style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=1&valeur_6=<?php echo $this->sensOrdre ?>");'>Pr&eacute;nom <?php echo Bral_Helper_Tri::sens(1, $this->ordre, $this->sensOrdre); ?></span>
		<span style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=2&valeur_6=<?php echo $this->sensOrdre ?>");'>Nom <?php echo Bral_Helper_Tri::sens(2, $this->ordre, $this->sensOrdre); ?></span>
		<span style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=3&valeur_6=<?php echo $this->sensOrdre ?>");'>N&deg; <?php echo Bral_Helper_Tri::sens(3, $this->ordre, $this->sensOrdre); ?></span>
		</th>
		<th style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=5&valeur_6=<?php echo $this->sensOrdre ?>");'>Entr&eacute;e <?php echo Bral_Helper_Tri::sens(5, $this->ordre, $this->sensOrdre); ?></th>
		<th style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=6&valeur_6=<?php echo $this->sensOrdre ?>");'>Rang <?php echo Bral_Helper_Tri::sens(6, $this->ordre, $this->sensOrdre); ?></th>
		<th style="cursor:pointer" onclick='_get_("/interface/load/?box=box_communaute_membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=4&valeur_6=<?php echo $this->sensOrdre ?>");'>Niveau <?php echo Bral_Helper_Tri::sens(4, $this->ordre, $this->sensOrdre); ?></th>
		<th>Position<br />x, y, z</th>
		<th>PV</th>
		<th>DLA</th>
		<th>PA</th>
		<th>FOR</th>
		<th>AGI</th>
		<th>VIG</th>
		<th>SAG</th>
		<th>VUE<br />BM</th>
	  </tr>
	</thead>
	<tfoot class="table_liste">
	  <tr class="table_liste">
	    <th colspan='13'>
	    	Affichage de <?php echo count($this->tabMembres) ?> Braldûn<?php if (count($this->tabMembres) > 1) : echo 's'; endif; ?> sur un total de <?php echo $this->nbMembresTotal ?> dans la communaut&eacute;<br />
	       <?php if ($this->precedentOk === true) : ?>
		   <input type="button" class='button1' onclick="Javascript:_get_('/interface/load/?box=box_communaute_membres&valeur_1=p&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')" value="Page pr&eacute;c&eacute;dente">
		   <?php endif; ?>
		   <?php if ($this->suivantOk === true) : ?>
		   <input type="button" class='button1' onclick="Javascript:_get_('/interface/load/?box=box_communaute_membres&valeur_1=s&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')" value="Page suivante">
		   <?php endif; ?>
	    </th>
	  </tr>
	</tfoot>
	<tbody>
	<?php if (count($this->tabMembres) > 0): ?>
	<?php $i = 0;
	   foreach($this->tabMembres as $m) :?>
		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  <td class="table_liste">
		  <a onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $m["id_braldun"] ?>');" title="Cliquez pour voir le profil">
	   		<?php echo htmlspecialchars($m["prenom_braldun"]) ?> <?php echo htmlspecialchars($m["nom_braldun"]) ?> (<?php echo htmlspecialchars($m["id_braldun"]) ?>)
	   		</a>
	   		</td>	
		  <td class="table_liste"><span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$m["date_entree"]); ?>"><?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('Y',$m["date_entree"]); ?></span></td>
		  <td class="table_liste">Rang n&deg;<?php echo $m["ordre_rang_communaute"] ?> : <br /><?php echo htmlspecialchars($m["nom_rang_communaute"]) ?></td>
		  
		  <td class="table_liste"><?php echo htmlspecialchars($m["niveau_braldun"]) ?></td>
		  <td class="table_liste">
		  	<span style="cursor:pointer" title="Position X"><?php echo $m["x_braldun"] ?></span><br />
		  	<span style="cursor:pointer" title="Position Y"><?php echo $m["y_braldun"] ?></span><br />
		  	<span style="cursor:pointer" title="Position Z"><?php echo $m["z_braldun"] ?></span>
		  </td>
		  
		  <td class="table_liste">
		  <?php echo Bral_Helper_Profil::afficheBarreVie($m["pv_restant_braldun"], $this->config->game->pv_base, $m["vigueur_base_braldun"], $this->config->game->pv_max_coef, $m["pv_max_bm_braldun"], $m["duree_prochain_tour_braldun"], true)?>
		  </td>
		  <td class="table_liste"><?php echo Bral_Helper_Profil::afficheBarreTour($m)?><?php //echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('<b>H:i:s</b> \l\e d/m/y',$m["date_fin_tour_braldun"]);?></td>
		  
		  <td class="table_liste"><?php echo $m["pa_braldun"] ?></td>
		  <td class="table_liste" nowrap>
		  	Niv.<span title="Niveau de la caract&eacute;ristique" style="cursor:pointer"><?php echo $m["force_base_braldun"]; ?></span><br />
		  	<?php echo $this->config->game->base_force + $this->user->force_base_braldun ?> 
	    	D<?php echo $this->config->game->de_force ?> <br />
	    	<span title="Bonus / Malus" style="cursor:pointer"><?php if ($this->user->force_bm_braldun >= 0): echo "+"; endif;?><?php echo $this->user->force_bm_braldun ?></span>
	    	<span title="Bonus / Malus Balance de faim" style="cursor:pointer"><?php if ($this->user->force_bbdf_braldun >= 0): echo "+"; endif;?><?php echo $this->user->force_bbdf_braldun ?></span> <br/>
		  </td>
		  <td class="table_liste" nowrap>
		  	Niv.<span title="Niveau de la caract&eacute;ristique" style="cursor:pointer"><?php echo $m["agilite_base_braldun"]; ?></span><br />
		  	<?php echo $this->config->game->base_agilite + $this->user->agilite_base_braldun ?> 
		    D<?php echo $this->config->game->de_agilite ?> <br />
		    <span title="Bonus / Malus" style="cursor:pointer"><?php if ($this->user->agilite_bm_braldun >= 0): echo "+"; endif;?><?php echo $this->user->agilite_bm_braldun ?></span>
		    <span title="Bonus / Malus Balance de faim" style="cursor:pointer"><?php if ($this->user->agilite_bbdf_braldun >= 0): echo "+"; endif;?><?php echo $this->user->agilite_bbdf_braldun ?></span> <br />
		  </td>
		  <td class="table_liste" nowrap>
		  	Niv.<span title="Niveau de la caract&eacute;ristique" style="cursor:pointer"><?php echo $m["vigueur_base_braldun"]; ?></span><br />
		  	<?php echo $this->config->game->base_vigueur + $this->user->vigueur_base_braldun ?> 
	    	D<?php echo $this->config->game->de_vigueur ?> <br />
	    	<span title="Bonus / Malus" style="cursor:pointer"><?php if ($this->user->vigueur_bm_braldun >= 0): echo "+"; endif;?><?php echo $this->user->vigueur_bm_braldun ?></span>
	    	<span title="Bonus / Malus Balance de faim" style="cursor:pointer"><?php if ($this->user->vigueur_bbdf_braldun >= 0): echo "+"; endif;?><?php echo $this->user->vigueur_bbdf_braldun ?></span>
		  </td>
		  <td class="table_liste" nowrap>
		  	Niv.<span title="Niveau de la caract&eacute;ristique" style="cursor:pointer"><?php echo $m["sagesse_base_braldun"]; ?></span><br />
		  	<?php echo $this->config->game->base_sagesse + $this->user->sagesse_base_braldun ?> 
	    	D<?php echo $this->config->game->de_sagesse ?> <br />
	    	<span title="Bonus / Malus" style="cursor:pointer"><?php if ($this->user->sagesse_bm_braldun >= 0): echo "+"; endif;?><?php echo $this->user->sagesse_bm_braldun ?></span>
	    	<span title="Bonus / Malus Balance de faim" style="cursor:pointer"><?php if ($this->user->sagesse_bbdf_braldun >= 0): echo "+"; endif;?><?php echo $this->user->sagesse_bbdf_braldun ?></span>
		  </td>
		  <td class="table_liste" nowrap>
		  	<?php if ($m["vue_bm_braldun"] >= 0): echo "+"; endif;?> <?php echo $m["vue_bm_braldun"] ?>
		  </td>
		</tr>
	<?php endforeach; ?>
	<?php else: ?>
		<tr class="table_liste0">
		  <td class="table_liste" colspan="13">Pas d'autre membre</td>
		</tr>
	<?php endif; ?>
	</tbody>
	</table>

<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
<?php endif; ?>


<?php echo $this->render("/interface/box_bottom.phtml") ?>