<br />

<? if ($this->isUpdateDescription == true) :?>
	Description mise &agrave; jour.
<? elseif ($this->isUpdateSiteWeb == true) : ?>
	Site web mis &agrave; jour.
<? else : ?>

<center>
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
	<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
	
	<ul class="titre textalic textsizec">Site Web</ul><br />
	<div id="label_site">
		<a href="<?=htmlentities($this->communaute["site_web"]) ?>"><?=htmlentities($this->communaute["site_web"]) ?></a>
	</div>
	<input type="text" id="valeur_2" size="50" maxlength="250" style="display:none" value="<?=htmlentities($this->communaute["site_web"]) ?>" />
	
	<input type="button" class='button1' name="bouton_editer_site" id="bouton_editer_site" value="Editer le site web" 
		onClick="$('label_site').style.display='none'; 
		$('valeur_2').style.display='block' ; 
		$('bouton_site').style.display='block'; 
		this.style.display='none'"/>
	
	<input type="button" class='button1' id="bouton_site" name="bouton_site" 
 	 onClick="
	  $('label_site').style.display='block'; 
	  $('valeur_2').style.display='none'; 
	  this.style.display='none' ;
	  $('valeur_1').value=1;
	   _get_('/communaute/doaction?caction=do_communaute_description')" value="Valider" style="display:none" />
	
	<br /><br /><br />
	
	<ul class="titre textalic textsizec">Description</ul><br />
	<input type="button" class='button1' id="bouton_editer" value="Editer la description" 
	onClick="$('label_description').style.display='none'; 
		$('valeur_3').style.display='block' ; 
		$('bouton_description').style.display='block'; 
		 this.style.display='none' ;
		tinyMCE.execCommand('mceAddControl', false, 'valeur_3');
		"/>
  <div id="label_description">
  <?=stripslashes($this->communaute["description"]) ?><? if (strlen(trim($this->communaute["description"])) == 0 || $this->communaute["description"] == null) :?> [vide]<? endif; ?>
  </div>
  <textarea rows='10' cols='80' name="valeur_3"  id="valeur_3"  style="display:none" ><?=stripslashes($this->communaute["description"]) ?></textarea>
  <input type="button" class='button1' id="bouton_description" 
  onClick="
	  $('valeur_3').value = escape(tinyMCE.get('valeur_3').getContent());
	  $('label_description').style.display='block'; 
	  $('valeur_3').style.display='none'; 
	  this.style.display='none' ;
	  $('valeur_1').value=2;
	   _get_('/communaute/doaction?caction=do_communaute_description', false)" value="Valider" style="display:none" />
</center>
<? endif; ?>