<br />

<?php if ($this->isUpdateDescription == true) :?>
	Description mise &agrave; jour.
<?php elseif ($this->isUpdateSiteWeb == true) : ?>
	Site web mis &agrave; jour.
<?php else : ?>

<center>
	<input type='hidden' id='nb_valeurs-communaute_description' name='nb_valeurs-communaute_description' value='3'>
	<input type='hidden' id='valeur_1-communaute_description' name='valeur_1-communaute_description' value='-1'>
	<input type='hidden' id='valeur_3-communaute_description' name='valeur_3-communaute_description' value=''>
	
	<div class="titre textalic textsizec">Site Web</div><br />
	<div id="label_site">
		<a href="<?php echo htmlspecialchars($this->communaute["site_web"]) ?>"><?php echo htmlspecialchars($this->communaute["site_web"]) ?></a>
	</div>
	<input type="text" id="valeur_2-communaute_description" size="50" maxlength="250" style="display:none" value="<?php echo htmlspecialchars($this->communaute["site_web"]) ?>" />
	
	<input type="button" class='button1' name="bouton_editer_site" id="bouton_editer_site" value="Editer le site web" 
		onclick="$('#label_site').hide(); 
		$('#valeur_2-communaute_description').show(); 
		$('#bouton_site').show();  
		this.style.display='none'"/>
	
	<input type="button" class='button1' id="bouton_site" name="bouton_site" 
 	 onclick="
	  $('#label_site').show();  
	  $('#valeur_2-communaute_description').hide(); 
	  this.style.display='none' ;
	  $('#valeur_1-communaute_description').val(1);
	   _get_('/communaute/doaction?caction=do_communaute_description', 'communaute_description')" value="Valider" style="display:none" />
	
	<br /><br /><br />
	
	<div class="titre textalic textsizec">Description</div><br />
	<input type="button" class='button1' id="bouton_editer" value="Editer la description" 
	onclick="$('#label_description').hide();
		$('#edition').show(); 
		$('#bouton_description').show();  
		 this.style.display='none' ;
		"/>
	</center>
		
  <div id="label_description" style="text-align:left; padding-left:30px">
<br /><br />  
  
  <?php echo Bral_Util_BBParser::bbcodeReplace($this->communaute["description"]) ?><?php if (mb_strlen(trim($this->communaute["description"])) == 0 || $this->communaute["description"] == null) :?> [vide]<?php endif; ?>
  </div>
  
  <div id="edition" style="display:none">
	 <?php echo Bral_Helper_BBBoutons::affiche('valeur_description')?>
	
	  <textarea rows='10' cols='80' name="valeur_description"  id="valeur_description"><?php echo stripslashes($this->communaute["description"]) ?></textarea>
	  <input type="button" class='button1' id="bouton_description" 
	  onclick="
		  $('#label_description').show();  
		  $('#edition').hide();
		  this.style.display='none' ;
		  $('#valeur_1-communaute_description').val(2);
		  $('#valeur_3-communaute_description').val(encodePlus($('#valeur_description').val()));
		   _get_('/communaute/doaction?caction=do_communaute_description', 'communaute_description', false)" value="Valider" style="display:none" />
	</div>

<?php endif; ?>