<br />
<div class="titre textalic textsizec">Liste des Rangs</div><br />

<br />
Pour modifier un nom ou une description, cliquez dessus.<br />
<table class="table_liste">
<thead class="table_liste">
  <tr class="table_liste">
	<th>N&deg;</th>
	<th>Nom</th>
	<th>Description</th>
  </tr>
</thead>
<tbody>
<?php $i = 0;
   foreach($this->tabRangs as $r) :?>
	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	  <td class="table_liste"><?php echo htmlspecialchars($r["ordre_rang_communaute"]) ?></td>
	  <td class="table_liste" > 
	  	<label id="label_nom<?php echo $r["id_rang"] ?>" onclick="this.style.display='none'; $('#value_nom<?php echo $r["id_rang"] ?>').show() ; $('#bouton_nom<?php echo $r["id_rang"] ?>').show()">
	  		<?php echo htmlspecialchars($r["nom"]) ?><?php if (mb_strlen(trim($r["nom"])) == 0 || $r["nom"] == null) :?> [vide]<?php endif; ?>
	  	</label>
	  	<input type="text" value="<?php echo htmlspecialchars($r["nom"]) ?>" id="value_nom<?php echo $r["id_rang"] ?>" style="display:none" maxlength="40" size="41"/>
	  	<input type="button" class='button1' id="bouton_nom<?php echo $r["id_rang"] ?>" onclick="$('#label_nom<?php echo $r["id_rang"] ?>').show(); $('#value_nom<?php echo $r["id_rang"] ?>').hide(); this.style.display='none' ; _get_('/communaute/doaction?caction=ask_communaute_rangs&valeur_1=1&valeur_2=<?php echo $r["id_rang"] ?>&valeur_3='+$('#value_nom<?php echo $r["id_rang"] ?>').val())" value="Valider" style="display:none">
	  </td>
	  <td class="table_liste">
	  <label id="label_desc<?php echo $r["id_rang"] ?>" onclick="this.style.display='none'; $('#value_desc<?php echo $r["id_rang"] ?>').show() ; $('#bouton_desc<?php echo $r["id_rang"] ?>').show(); $('#max_desc<?php echo $r["id_rang"] ?>').show()";>
	  		<?php echo $r["description"] ?><?php if (mb_strlen(trim($r["description"])) == 0 || $r["description"] == null) :?> [vide]<?php endif; ?>
 		</label>
	  	<textarea onkeyup="limiteTailleTextarea(this, 200, 'max_desc<?php echo $r["id_rang"]?>')"  onkeydown="limiteTailleTextarea(this, 200, 'max_desc<?php echo $r["id_rang"]?>')" id="value_desc<?php echo $r["id_rang"] ?>" style="display:none" cols="40" rows="2"><?php echo $r["description"] ?></textarea>
	  	<label id="max_desc<?php echo $r["id_rang"] ?>"></label>
	  	<input type="button" class='button1' id="bouton_desc<?php echo $r["id_rang"] ?>" onclick="$('#label_nom<?php echo $r["id_rang"] ?>').show(); $('#value_desc<?php echo $r["id_rang"] ?>').hide(); this.style.display='none' ; $('#max_desc<?php echo $r["id_rang"] ?>').hide(); _get_('/communaute/doaction?caction=ask_communaute_rangs&valeur_1=2&valeur_2=<?php echo $r["id_rang"] ?>&valeur_3='+$('#value_desc<?php echo $r["id_rang"] ?>').val())" value="Valider" style="display:none">
	 </td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>
