<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	<?php if ($this->possedeCharrette === false) : ?>
	 	Vous n'avez pas de butin...
	 <?php else: ?>
		Pour 0 PA, vous pouvez partager vos butins avec d'autres Braldûns. <br />
		
		Partage avec les Braldûns de votre communauté : 
		<select name='valeur_1' id="valeur_1">
			<option value="oui" <?php if ($this->user->est_partage_communaute_butin_braldun == "oui") : echo "selected"; endif;?>>Oui</option>
			<option value="non" <?php if ($this->user->est_partage_communaute_butin_braldun == "non") : echo "selected"; endif;?>>Non</option>
		</select><br /><br />
		
		Partage avec les Braldûns suivants : 
		
		<input type="hidden" name="valeur_2" id="valeur_2" value="" />
		
		<div id='aff_valeur_2_partage_dest'><?php echo $this->tabBralduns["aff_js_destinataires"]?></div>
		<input type="hidden" name="valeur_2_partage_dest" id="valeur_2_partage_dest" value="<?php echo $this->tabBralduns["destinataires"]?>"/>
		<input type="hidden" name="cpt_valeur_2_partage_dest" id="cpt_valeur_2_partage_dest" value=""/>
		<input type="hidden" name="onchange_valeur_2_partage_dest" id="onchange_valeur_2_partage_dest"/>
		
		<input type="text" name="recherche_valeur_2_partage_dest" size='40' id="recherche_valeur_2_partage_dest" value="Entrez un nom" onFocus='this.value=""; activerRechercheBraldun("valeur_2_partage_dest");' />
		<input type="hidden" name="recherche_valeur_2_partage_dest_actif" id="recherche_valeur_2_partage_dest_actif" value="0" />
	    <span id="indicateur_recherche_valeur_2_partage_dest" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" alt="Recherche..." /></span>
		    
	 <?php endif; ?>
	 <br />
</div>

<br />
<input type='button' class='button1' id='bouton_partagebutin' value='Valider les partages' onclick='this.disabled=true;$("#valeur_2").val($("#valeur_2_partage_dest").val());_get_("/butin/doaction?caction=do_butin_partage");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>