<?php
Zend_Loader::loadClass('Bral_Helper_Contenu');
$vide = true; ?>
<?php if ($this->typePlantes["Arbre"]["a_afficher"] == true) : ?>
<?php $vide = false; ?>
<table class="table_liste" style="width:auto; padding:5px;">
	<thead class="table_liste">
	<tr class="table_liste">
		<th width="20px;">
			<ul class="titre textsized">Arbres</ul>
		</th>
		<th style="width:auto; padding:5px;">Feuilles</th>
		<th style="width:auto; padding:5px;">Fleurs</th>
		<th style="width:auto; padding:5px;">Fruits</th>
		<th style="width:auto; padding:5px;">&Eacute;corce</th>
	</tr>
	</thead>
	<tbody>
		<?php include("contenu_arbre.phtml") ?>
	</tbody>
</table>
<br/>
<?php endif; ?>

<?php if ($this->typePlantes["Buisson"]["a_afficher"] == true) : ?>
<?php $vide = false; ?>
<table class="table_liste" style="width:auto; padding:5px;">
	<thead class="table_liste">
	<tr class="table_liste">
		<th width="20px;">
			<ul class="titre textsized">Buissons</ul>
		</th>
		<th style="width:auto; padding:5px;">Feuilles</th>
		<th style="width:auto; padding:5px;">Fleurs</th>
		<th style="width:auto; padding:5px;">&Eacute;pines</th>
	</tr>
	</thead>
	<tbody>
		<?php include("contenu_buisson.phtml") ?>
	</tbody>
</table>
<br/>
<?php endif; ?>

<?php if ($this->typePlantes["Fleur"]["a_afficher"] == true) : ?>
<?php $vide = false; ?>
<table class="table_liste" style="width:auto; padding:5px;">
	<thead class="table_liste">
	<tr class="table_liste">
		<th width="20px;">
			<ul class="titre textsized">Fleurs</ul>
		</th>
		<th style="width:auto; padding:5px;">Fleurs</th>
	</tr>
	</thead>
	<tbody>
		<?php include("contenu_fleur.phtml") ?>
	</tbody>
</table>
<br/>
<?php endif; ?>
<?php if ($vide == true) : ?>
<center><i>Vide</i></center>
<?php endif; ?>
