 <? foreach ($this->typePlantes["Buisson"]["type_plante"] as $k => $v) : ?>
 	<? if ($v["a_afficher"] == true) : ?>
 	<tr class="table_liste">
	 	<td class="table_liste" style="text-align: left;">
	 		<?=htmlspecialchars($k); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?=Bral_Helper_ContenuPlante::affiche($v["parties"]["feuille"]); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?=Bral_Helper_ContenuPlante::affiche($v["parties"]["fleur"]); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?=Bral_Helper_ContenuPlante::affiche($v["parties"]["epine"]); ?>
	 	</td>
 	</tr>
 	<? endif; ?>
 <? endforeach; ?>