 <?php foreach ($this->typePlantes["Arbre"]["type_plante"] as $k => $v) : ?>
 	<?php if ($v["a_afficher"] == true) : ?>
 	<tr class="table_liste">
	 	<td class="table_liste" style="text-align: left;">
	 		<?php echo htmlspecialchars($k); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?php echo Bral_Helper_Contenu::affichePlante($v["parties"]["feuille"]); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?php echo Bral_Helper_Contenu::affichePlante($v["parties"]["fleur"]); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?php echo Bral_Helper_Contenu::affichePlante($v["parties"]["fruit"]); ?>
	 	</td>
	 	<td class="table_liste">
	 		<?php echo Bral_Helper_Contenu::affichePlante($v["parties"]["ecorce"]); ?>
	 	</td>
 	</tr>
 	<?php endif; ?>
 <?php endforeach; ?>