<?php echo $this->render('header.phtml'); ?>
<form action="/gardiennage/" method="post">
<div class="box_gardiennage">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<ul class="titre textalia textsizea">Gardiennage</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />
   		<? if (!empty($this->message)) : ?>
   			<?=$this->message?>
   		<? endif; ?>
		<? if ($this->user->gardeEnCours) : ?>
			Hobbit en cours : <?=htmlentities($this->user->prenom_hobbit) ?> <?=htmlentities($this->user->nom_hobbit) ?> (<?=$this->user->id_hobbit?>)<br /><br />
			<div id="formbutton">
				<input type="button" name="retour" value="Aller &agrave; l'interface" onClick="javascript:document.location.href='/interface'"/>
			</div>
			&nbsp;
		<? else: ?>
		<br />
			Vous devez s&eacute;lectionner un hobbit en garde
			<div id="formbutton">
				<input type="button" name="retour" value="Retour Gardiennage" onClick="javascript:document.location.href='/gardiennage'"/>
			</div>
		<? endif; ?>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

