<?php echo $this->render('header.phtml'); ?>
<form action="/Gardiennage/garde" method="post">

<div class="box_gardiennage">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<ul class="titre textalia textsizea">Gardiennage</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />
      	<? if (!empty($this->message)) : ?>
   			<?=$this->message?>
   		<? else: ?>
			<? if (empty($this->tabHobbitGarde)) : ?>
				Vous n'avez aucun Hobbit en garde actuellement.
			<? else: ?>
				<ul class="titre textalic textsized">Gardes à effectuer</ul><br>
				<table class="table_liste">
				<thead class="table_liste">
					<tr class="table_liste">
					<th>S&eacute;lectionner</th>
					<th>Hobbit</th>
					<th>Date de d&eacute;but</th>
					<th>Nombre de jour(s)</th>
					<th>Commentaire</th>
				</thead>
				<? foreach($this->tabHobbitGarde as $g): ?>
					<tr>
						<td>
							<? if($g["date_ok"] === true): ?>
							<input type="radio" name="id_gardiennage" value="<?=$g["id_gardiennage"]?>" />
							<? else:?>
							-
							<? endif; ?>
						</td>
						<td nowrap>
							<a onClick="javascript:ouvrirWin('/voir/hobbit/?hobbit=<?=$g["id_hobbit"] ?>');" title="Cliquez pour voir le profil">
						  		<?=htmlspecialchars(stripslashes($g["prenom_hobbit"])). " ". htmlspecialchars(stripslashes($g["nom_hobbit"])). ' ('.$g["id_hobbit"].')';?>
						  	</a>
						</td>
						<td nowrap>Le <?=Bral_Util_ConvertDate::get_date_mysql_datetime('d/m/y',$g["date_debut"]); ?></td>
						<td nowrap><?=$g["nb_jours"] ?></td>
						<td nowrap><?=htmlspecialchars(stripslashes($g["commentaire"])) ?></td>
					</tr>
				<? endforeach; ?>
				</table>
			    Activation du tour :
			    oui <input type="radio" id="activation_tour_gardiennage" name="activation_tour_gardiennage" value="oui" checked>
			    non <input type="radio" id="activation_tour_gardiennage" name="activation_tour_gardiennage" value="non"> <br />
			<? endif; ?>
		<? endif; ?>
<br />
<div id="formbutton">
<? if (!empty($this->tabHobbitGarde) && $this->uneGardePossible) : ?>
<input type="submit" name="add" class='button1' value="Jouer !" />
<? elseif (!empty($this->tabHobbitGarde)): ?>
Aucune des gardes débute aujourd'hui.<br><br>
<? endif; ?>
<input type="button" name="retour" class='button1' value="Retour Interface" onClick="javascript:document.location.href='/interface/'"/>
<? if (!empty($this->message)) : ?>
<input type="button" name="deconnexion" class='button1' value="D&eacute;connexion" onClick="javascript:document.location.href='/auth/logout'"/>
<? endif; ?>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

