<?php echo $this->render('header.phtml'); ?>
<form action="/gardiennage/garde" method="post">

<div class="box_gardiennage">
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
<div class="inner">
	<ul class="titre textalia textsizea">Gardiennage</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu2Clair textalic">
	    <br />
      	<? if (!empty($this->message)) : ?>
   			<?=$this->message?>
   		<? else: ?>
			<? if (empty($this->tabHobbitGarde)) : ?>
				Vous n'avez aucun Hobbit en garde actuellement.
			<? else: ?>
				Vos gardes en cours : 
				<table align="center">
				<th class='comp_titre'>Sélectionner</th>
				<th class='comp_titre'>Hobbit</th>
				<th class='comp_titre'>Date de d&eacute;but</th>
				<th class='comp_titre'>Nombre de jour(s)</th>
				<th class='comp_titre'>Commentaire</th>
				<? foreach($this->tabHobbitGarde as $g): ?>
					<tr>
						<td>
							<? if($g["date_ok"] === true): ?>
							<input type="radio" name="id_gardiennage" value="<?=$g["id_gardiennage"]?>" />
							<? endif; ?>
						</td>
						<td nowrap><?=htmlentities(stripslashes($g["prenom_hobbit"])). " ". htmlentities(stripslashes($g["nom_hobbit"])). ' ('.$g["id_hobbit"].')';?></td>
						<td nowrap><?=$g["date_debut"] ?></td>
						<td nowrap><?=$g["nb_jours"] ?></td>
						<td nowrap><?=htmlentities(stripslashes($g["commentaire"])) ?></td>
					</tr>
				<? endforeach; ?>
				</table>
			    Activation du tour :
			    oui <input type="radio" id="activation_tour_gardiennage" name="activation_tour_gardiennage" value="oui" checked>
			    non <input type="radio" id="activation_tour_gardiennage" name="activation_tour_gardiennage" value="non"> <br />
			<? endif; ?>
		<? endif; ?>
<br />
<div id="formbutton">
<? if (!empty($this->tabHobbitGarde)) : ?>
<input type="submit" name="add" value="Jouer !" />
<? endif; ?>
<input type="button" name="retour" value="Retour Interface" onClick="javascript:document.location.href='/interface/'"/>
<? if (!empty($this->message)) : ?>
<input type="button" name="deconnexion" value="D&eacute;connexion" onClick="javascript:document.location.href='/auth/logout'"/>
<? endif; ?>
		</ul>
	</div>
	&nbsp;
</div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

