<div>
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=hg&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_haut_gauche.gif" border="0" alt="haut-gauche" title="haut-gauche" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=h&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_haut.gif" border="0" alt="haut" title="haut" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=hd&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_haut_droit.gif" border="0" alt="haut-droit" title="haut-droit"><br />
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=g&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_gauche.gif" border="0" alt="gauche" title="gauche" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue');" src="<?php echo $this->config->static->url?>/images/vue/puce_centre.gif" border="0" alt="centrer" title="centrer" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=d&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_droite.gif" border="0" alt="droite" title="droite" style="cursor:pointer"><br />
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=bg&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_bas_gauche.gif" border="0" alt="bas-gauche" title="bas-gauche" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=b&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_bas.gif" border="0" alt="bas" title="bas" style="cursor:pointer">
    <img onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=bd&valeur_2=<?php echo $this->centre_x ?>&valeur_3=<?php echo $this->centre_y ?>')"
     src="<?php echo $this->config->static->url?>/images/vue/puce_bas_droit.gif" border="0" alt="bas-droit" title="bas-droit" style="cursor:pointer"><br />
     <a class="titre textalia textsizef"  onclick="javascript:ouvrirWin('/voir/vue/')";>Vue &eacute;tendue</a>
</div>