<?php 

$textBraldun = "";
$textMonstre = "";
$textNid = "";

if ($case["n_bralduns"] > 0) :
	$sexe_braldun = "";
	$soule_braldun = "";
	$s = "";
	if ($case["n_bralduns"] > 1) {
		$s .= "s";
	}
	$textBraldun = "<br /><div class='titre textalia textsizef'>Braldûn$s</div>";
	$textEquipe["a"] = "";
	$textEquipe["b"] = "";
	
	foreach($case["bralduns"] as $h) {
		
		$intangible = "";
		$textIntangible = "";
		if ($h["est_intangible_braldun"] == 'oui') {
			$intangible = "Intangible";
			$textIntangible = "(Braldûn intangible) -";
		}
		
		$textTmp = "";
		$textTmp .= '<label class=\'alabel profil'.$intangible.'\' onclick=ouvrirProfilH('.$h["id_braldun"].'); title=\''.$textIntangible.' Voir le profil\' >';
		$textTmp .= htmlspecialchars($h["prenom_braldun"])." ".htmlspecialchars($h["nom_braldun"]);
		$textTmp .= " (n&deg;".$h["id_braldun"].")</label>, niv.".$h["niveau_braldun"];
		
		$textTmp .= ' <img src=\''.$this->config->url->static.'/images/vue/puce_event.gif\' title=\'Voir les événements\' border=\'0\' onclick=ouvrirEvenementsH('.$h["id_braldun"].'); style=\'cursor:pointer\'/> ';
		if ($this->estVueEtendue == false) {
			$textTmp .= ' <img src=\''.$this->config->url->static.'/images/uddeim/env.gif\' title=\'Envoyer un message\' alt=\'Ecrire\' border=\'0\' onclick=ecrireMessage('.$h["id_braldun"].'); style=\'cursor:pointer\'/> ';
		}
		if ($h["id_communaute"] != null) {
			$textTmp .= '- <label class=alabel onclick=ouvrirCommunaute('.$h["id_communaute"].');>'.htmlspecialchars($h["nom_communaute"]).'</label>';
		}
		$textTmp .= "<br />";
		
		if ($sexe_braldun != "masculin_feminin"  &&
		    ($sexe_braldun == "masculin" && $h["sexe_braldun"] == "feminin") ||
		    ($sexe_braldun == "feminin" && $h["sexe_braldun"] == "masculin")) {
			$sexe_braldun = "masculin_feminin";
		} elseif ($sexe_braldun != "masculin_feminin" && $h["sexe_braldun"] == "masculin") {
			$sexe_braldun = "masculin";
		} elseif ($sexe_braldun != "masculin_feminin" && $h["sexe_braldun"] == "feminin") {
			$sexe_braldun = "feminin";
		} elseif ($sexe_braldun == "masculin_feminin") {
			$sexe_braldun = "masculin_feminin";
		} else {
			$sexe_braldun = "feminin";
		}
		
		if ($h["est_soule_braldun"] == 'oui' && $h["soule_camp_braldun"] != "") {
			$textEquipe[$h["soule_camp_braldun"]] .= $textTmp;
			if ($soule_braldun == "") {
				$soule_braldun = $h["soule_camp_braldun"];
			} elseif ($soule_braldun != $h["soule_camp_braldun"]) {
				$soule_braldun = "combat";
			}
		} else {
			$textBraldun .= $textTmp;
		}
	} 
	$s = "";
	if ($case["n_bralduns"] > 1) {
		$s = "s";
	}
	if ($soule_braldun != "") {
		$soule_braldun = "-".$soule_braldun;
		
		if ($textEquipe["a"] != "") {
			$textEquipe["a"] = "<br />Equipe A:<br />".$textEquipe["a"];	
		}
		
		if ($textEquipe["b"] != "") {
			$textEquipe["b"] = "<br />Equipe B:<br />".$textEquipe["b"];	
		}
		$textBraldun = $textEquipe["a"] .$textEquipe["b"] ;
	}
	if ($textBraldun != "") {
		$textBraldun = $textBraldun.'<br /><hr/><br />';
	}
endif; 

$idTypeMonstre = "";
if ($case["n_monstres"] > 0) :
	$s = "";
	if ($case["n_monstres"] > 1) {
		$s = "s";
	}
	
	$textMonstre = "<br /><div class='titre textalia textsizef'>Monstre$s ou Gibier$s</div>";
	$textMonstre .= "<br />";
	foreach($case["monstres"] as $m) {
		$textMonstre .= '<label class=\'alabel\' onclick=ouvrirMonstre('.$m["id_monstre"].'); title=\'Voir le profil\' >';
		if ($m["est_gibier"]) {
			$textMonstre .= "Gibier : ";
		}
		$textMonstre .= htmlspecialchars($m["nom_monstre"]) ." ".htmlspecialchars($m["taille_monstre"])." (n&deg;".$m["id_monstre"].")</label> ";
		$textMonstre .= ' <img src=\''.$this->config->url->static.'/images/vue/puce_event.gif\' title=\'Voir les événements\' border=\'0\' onclick=ouvrirEvenementsM('.$m["id_monstre"].'); style=\'cursor:pointer\'/> ';
		$textMonstre .= "<br />";
		
		if ($idTypeMonstre == "") {
			$idTypeMonstre = $m["id_type_monstre"];
		} elseif ($idTypeMonstre != $m["id_type_monstre"]) {
			$idTypeMonstre = -1;
		}
		
	} 
	$s = "";
	if ($case["n_monstres"] > 1) {
		$s = "s";
	}
	if ($textMonstre != "") {
		$textMonstre = $textMonstre.'<br /><hr/><br />';
	}
endif;

if ($case["n_nids"] > 0) :
	$textNid = "<br />";
	foreach($case["nids"] as $n) {
		$textNid .= '1 '.$n["nom_nid"].' ('.$n["id_nid"].') ';
		$textNid .= "<br />";
	} 
	if ($textNid != "") {
		$textNid = $textNid.'<br /><hr/><br />';
	}
endif;

?>

<div class="braltip">

<div id="vuedetails_bralduns-<?php echo $case["x"]?>_<?php echo $case["y"]?>" style='display:none'>
<?php echo $textBraldun.$textMonstre.$textNid;?>
</div>

<?php if ($case["n_nids"] > 0) : ?>
    <img src='<?php echo $this->config->url->static?>/images/vue/nid.png' style="position: absolute; top:-8px; left:0px;"/>
<?php endif;?>

<?php if ($case["n_monstres"] > 0) : 
	if ($case["n_monstres"] == 1) {
		$suffixe = "a";
	} else {
		$suffixe = "b";
	}
	if ($idTypeMonstre == 1 || $idTypeMonstre == 4 || $idTypeMonstre == 5 || 
        $idTypeMonstre == 6 || $idTypeMonstre == 7 || 
        $idTypeMonstre == 8 || $idTypeMonstre == 11 ||
        $idTypeMonstre == 13 || $idTypeMonstre == 14 ||
        $idTypeMonstre == 15 || $idTypeMonstre == 16 ||
        $idTypeMonstre == 17 || 
        $idTypeMonstre == 9 || $idTypeMonstre == 10 ||
        $idTypeMonstre == 23 || $idTypeMonstre == 24 ||
        $idTypeMonstre == 25 || $idTypeMonstre == 26 ||
        $idTypeMonstre == 27 || $idTypeMonstre == 28 ||
        $idTypeMonstre == 21 || $idTypeMonstre == 37 || 
        $idTypeMonstre == 38) {
    	?> <img src='<?php echo $this->config->url->static?>/images/type_monstre/<?php echo $idTypeMonstre.$suffixe?>.png' style="position: absolute;top:-20px;left:0px;"/> <?php
    } else if ($idTypeMonstre == -1) {
        ?> <img src='<?php echo $this->config->url->static?>/images/vue/monstres.png' style="position: absolute;"/> <?php
    } else {
    	?> <img src='<?php echo $this->config->url->static?>/images/vue/monstre.png' style="position: absolute;"/> <?php
    }
   endif;
?>

<?php if ($case["n_bralduns"] > 1) : ?>
    <img src='<?php echo $this->config->url->static?>/images/vue/bralduns_<?php echo $sexe_braldun?><?php echo $soule_braldun?>.png' style="position: absolute;top:-6px;left:0px;" />
<?php elseif ($case["n_bralduns"] > 0) : ?>
    <img src='<?php echo $this->config->url->static?>/images/vue/braldun_<?php echo $sexe_braldun?><?php echo $soule_braldun?>.png' style="position: absolute;left:5px;top:-6px"/>
<?php endif; ?>
    
</div> 