<?php 

$textBraldun = "";
$textMonstre = "";
$textNid = "";

if ($case["n_bralduns"] > 0) :
	$sexe_braldun = "";
	$soule_braldun = "";
	$textBraldun = "<br>Braldun";
	$textEquipe["a"] = "";
	$textEquipe["b"] = "";
	
	if ($case["n_bralduns"] > 1) {
		$textBraldun .= "s";
	}
	$textBraldun .= ":<br>";
	foreach($case["bralduns"] as $h) {
		
		$intangible = "";
		$textIntangible = "";
		if ($h["est_intangible_braldun"] == 'oui') {
			$intangible = "Intangible";
			$textIntangible = "(Braldûn intangible) -";
		}
		
		$textTmp = "";
		$textTmp .= '<label class=\\\'alabel profil'.$intangible.'\\\' onClick=ouvrirProfilH('.$h["id_braldun"].'); title=\\\''.$textIntangible.' Voir le profil\\\' >';
		$textTmp .= addslashes(htmlspecialchars($h["prenom_braldun"]))." ".addslashes(htmlspecialchars($h["nom_braldun"]));
		$textTmp .= " (n&deg;".$h["id_braldun"].")</label>, niv.".$h["niveau_braldun"];
		
		$textTmp .= ' <img src=\\\'/public/images/puce_event.gif\\\' title=\\\'Voir les événements\\\' border=\\\'0\\\' onClick=ouvrirEvenementsH('.$h["id_braldun"].'); style=\\\'cursor:pointer\\\'/> ';
		if ($this->estVueEtendue == false) {
			$textTmp .= ' <img src=\\\'/public/images/uddeim/env.gif\\\' title=\\\'Envoyer un message\\\' alt=\\\'Ecrire\\\' border=\\\'0\\\' onClick=ecrireMessage('.$h["id_braldun"].'); style=\\\'cursor:pointer\\\'/> ';
		}
		if ($h["id_communaute"] != null) {
			$textTmp .= ' - <label class=alabel onClick=ouvrirCommunaute('.$h["id_communaute"].');>'.addslashes(htmlspecialchars($h["nom_communaute"])).'</label>';
		}
		$textTmp .= "<br>";
		
		if ($sexe_braldun != "masculin_feminin"  &&
		    ($sexe_braldun == "masculin" && $h["sexe_braldun"] == "feminin") ||
		    ($sexe_braldun == "feminin" && $h["sexe_braldun"] == "masculin")) {
			$sexe_braldun = "masculin_feminin";
		} elseif ($sexe_braldun != "masculin_feminin" && $h["sexe_braldun"] == "masculin") {
			$sexe_braldun = "masculin";
		} elseif ($sexe_braldun != "masculin_feminin" && $h["sexe_braldun"] == "feminin") {
			$sexe_braldun = "feminin";
		} elseif ($sexe_braldun == "masculin_feminin") {
			$sexe_braldun = "masculin_feminin";
		} else {
			$sexe_braldun = "feminin";
		}
		
		if ($h["soule_camp_braldun"] != "") {
			$textEquipe[$h["soule_camp_braldun"]] .= $textTmp;
			if ($soule_braldun == "") {
				$soule_braldun = $h["soule_camp_braldun"];
			} elseif ($soule_braldun != $h["soule_camp_braldun"]) {
				$soule_braldun = "combat";
			}
		} else {
			$textBraldun .= $textTmp;
		}
	} 
	$s = "";
	if ($case["n_bralduns"] > 1) {
		$s = "s";
	}
	if ($soule_braldun != "") {
		$soule_braldun = "-".$soule_braldun;
		
		if ($textEquipe["a"] != "") {
			$textEquipe["a"] = "<br>Equipe A:<br>".$textEquipe["a"];	
		}
		
		if ($textEquipe["b"] != "") {
			$textEquipe["b"] = "<br>Equipe B:<br>".$textEquipe["b"];	
		}
		$textBraldun = $textEquipe["a"] .$textEquipe["b"] ;
	}
endif; 

$idTypeMonstre = "";
if ($case["n_monstres"] > 0) :
	$textMonstre = "<br>Monstre";
	if ($case["n_monstres"] > 1) {
		$textMonstre .= "s";
	}
	$textMonstre .= ":<br>";
	foreach($case["monstres"] as $m) {
		$textMonstre .= '<label class=\\\'alabel\\\' onClick=ouvrirMonstre('.$m["id_monstre"].'); title=\\\'Voir le profil\\\' >';
		if ($m["est_gibier"]) {
			$textMonstre .= "Gibier : ";
		}
		$textMonstre .= htmlspecialchars($m["nom_monstre"]) ." ".htmlspecialchars($m["taille_monstre"])." (n&deg;".$m["id_monstre"].")</label> ";
		$textMonstre .= ' <img src=\\\'/public/images/puce_event.gif\\\' title=\\\'Voir les événements\\\' border=\\\'0\\\' onClick=ouvrirEvenementsM('.$m["id_monstre"].'); style=\\\'cursor:pointer\\\'/> ';
		$textMonstre .= "<br />";
		
		if ($idTypeMonstre == "") {
			$idTypeMonstre = $m["id_type_monstre"];
		} elseif ($idTypeMonstre != $m["id_type_monstre"]) {
			$idTypeMonstre = -1;
		}
	} 
	$s = "";
	if ($case["n_monstres"] > 1) {
		$s = "s";
	}
endif;

if ($case["n_nids"] > 0) :
	$textNid = "<br>";
	foreach($case["nids"] as $n) {
		$textNid .= '1 '.$n["nom_nid"].' ('.$n["id_nid"].') ';
		$textNid .= "<br />";
	} 
endif;

?>

<div style="position: absolute;" <?=Bral_Helper_Tooltip::jsTip($textBraldun.$textMonstre.$textNid, $titre) ?>>

<? if ($case["n_nids"] > 0) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/nid.png' style="position: absolute;top:-8px"/>
<? endif;?>

<? if ($case["n_monstres"] > 0) : 
	if ($case["n_monstres"] == 1) {
		$suffixe = "a";
	} else {
		$suffixe = "b";
	}
	if ($idTypeMonstre == 1 || $idTypeMonstre == 5 || 
        $idTypeMonstre == 6 || $idTypeMonstre == 7 || 
        $idTypeMonstre == 8 || $idTypeMonstre == 11 ||
        $idTypeMonstre == 9 || $idTypeMonstre == 10 ||
        $idTypeMonstre == 23 || $idTypeMonstre == 24) {
    	?> <img src='/public/styles/braldahim_defaut/images/type_monstre/<?=$idTypeMonstre.$suffixe?>.png' style="position: absolute;top:-20px"/> <?
    } else if ($idTypeMonstre == -1) {
        ?> <img src='/public/styles/braldahim_defaut/images/vue/monstres.png' style="position: absolute;top:-17px"/> <?
    } else {
    	?> <img src='/public/styles/braldahim_defaut/images/vue/monstre.png' style="position: absolute;top:-17px"/> <?
    }
   endif;
?>

<? if ($case["n_bralduns"] > 1) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/bralduns_<?=$sexe_braldun?><?=$soule_braldun?>.png' style="position: absolute;top:-3px;left:5px;" />
<? elseif ($case["n_bralduns"] > 0) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/braldun_<?=$sexe_braldun?><?=$soule_braldun?>.png' style="position: absolute;left:5px;top:-3px"/>
<? endif; ?>
    
</div>