<?php if ($case["n_cadavres"] > 0) : ?>
      <div>
      <?php 
      	$textCadavre = "";
      	foreach($case["cadavres"] as $c) {
      		$textCadavre .= htmlentities($c["nom_cadavre"]) .", n&deg; ".$c["id_cadavre"]." - ".htmlentities($c["taille_cadavre"])."<br />";
		} 
		$s = "";
		if ($case["n_cadavres"] > 1) {
			$s = "s";
		}
		$titre = "X:".$case["x"]." Y:".$case["y"]." - ".$case["n_cadavres"] ." Cadavre".$s;
	  ?>
      <span <?=Bral_Helper_Tip::jsTip($textCadavre, $titre) ?>>
      	<?=$case["n_cadavres"] ?> cadavre<?=$s?>
      </span>
      </div>
<?php endif; ?>	