<?
$textCadavre = "";
$textCastar = "";
$textRune = "";
$titre = "Position X:".$case["x"]." Y:".$case["y"];
?>
<? if ($case["n_cadavres"] > 0) : 
      	$textCadavre = "Cadavre";
      	if ($case["n_cadavres"] > 0) {
      		$textCadavre .= "s";
      	}
      	$textCadavre .= ": 	<br>";
      	foreach($case["cadavres"] as $c) {
      		$textCadavre .= htmlspecialchars($c["nom_cadavre"]) ." (n&deg; ".$c["id_cadavre"].") - ".htmlspecialchars($c["taille_cadavre"])."<br />";
		} 
		$s = "";
		if ($case["n_cadavres"] > 1) {
			$s = "s";
		}
 ?>	
<? if ($case["n_castars"] > 0) : 
	$textCastar = "<br>";
	foreach($case["castars"] as $c) {
		$s = "";
		if ($c["nb_castar"] > 1) {
			$s = "s";
		}
		$textCastar .= $c["nb_castar"]. " castar".$s;
	} 
endif; ?>	
<? if ($case["n_elements_runes"] > 0) :
	$textRune = "<br>";
	foreach($case["elements_runes"] as $r) {
		$textRune .= "1 rune (n&deg; ".$r["id_element_rune"].")<br />";
	} 
	$s = "";
	if ($case["n_elements_runes"] > 1) {
		$s = "s";
	}
endif; ?>
 
<?php if ($case["n_cadavres"] > 0 || $case["n_castars"] > 0 || $case["n_elements_runes"] > 0) : ?>
	<span <?=Bral_Helper_Tooltip::jsTip($textCadavre.$textCastar.$textRune, $titre) ?>>
		<img src='/public/styles/braldahim_defaut/images/layout/vue/castars_runes_cadavres.png' />
	</span>
<? else :?>
	<br>
<? endif; ?>