<div class="vue2d_case_num braltip">
<?php if ($case["marcher"] != null && $case["marcher"]["case"] != null && $case["marcher"]["case"]["valid"] === true):
	$texte = "Environnement : ".$case["marcher"]["general"]["environnement"].", ";
	if ($case["marcher"]["general"]["nb_pa"] > 1) {
		$s = 's';
	} else {
		$s = '';
	}
	$texte .= "Nombre PA nécessaire".$s.": ".$case["marcher"]["general"]["nb_pa"]." ";
	if ($case["n_crevasses"] > 0) :
		$texte .= "Attention ! Il y a une crevasse découverte, quelqu'un est tombé ici.<br />";
	endif;?>
	
<?//=Bral_Helper_Tooltip::render($texte, "Marcher", true); ?> 	
<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/pas.png' 
	<?php if (!Zend_Registry::get("estMobile")) : ?>
		alt='Cliquez pour Marcher' title="Cliquez pour Marcher : <?php echo $texte?>"
		onclick="Javascript:_get_('/competences/doaction?caction=do_competence_marcher&valeur_1=<?php echo $case["marcher"]["case"]["offset"]?>')" style="cursor:pointer;"
	<?php else:?>/>
	<?php endif; ?>
<?php endif; ?>
</div>