<?php if ($case["n_charrettes"] > 0) : ?>
      		<div>
      		<?php 
      			$textCharrette = "";

      			foreach($case["charrettes"] as $c) {
      				$textCharrette .= "Charrette n&deg; ".$c["id_charrette"]. "<br />";
      			} 
				$s = "";
				if ($case["n_charrettes"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_charrettes"]." Charrette".$s;
			?>
      		<span <?=Bral_Helper_Tooltip::jsTip($textCharrette, $titre) ?>>
	      		<?=$case["n_charrettes"] ?> charrette<?=$s?>
	      	</span>
	      	</div>
<?php endif; ?>	