<table class='vue2d' align='center'>
     <?php 
     $col="";
     
     echo "<tr><td>&nbsp;</td>";
     foreach($this->tableau as $k => $case) :
     
    if ($case["change_level"] == 1 && $col == "ok") :
    	break;
    endif;
    echo "<td>".$case["x"]."</td>";
    if ($case["change_level"] == true) : 
          $col="ok";
        endif;
 endforeach;
 echo "</tr>";
	 
$col="";
foreach($this->tableau as $k => $case) :
	$textVille = "";
	if (!empty($case["ville"])) :
		$textVille = " - Ville : ".htmlspecialchars($case["ville"]["nom_ville"]);
		if ($case["ville"]["est_capitale"] === true) {
			$textVille .= " - Capitale";
		}
		$textVille .= ", R&eacute;gion : ".htmlspecialchars($case["ville"]["nom_region"]);
	endif;
	$titre = "Position : ".$case["x"].", ".$case["y"];
      	
	if ($case["change_level"] == 1 && $col == "ok") :
		echo "</tr>";
	endif; 
	
	if ($this->user->administrationvue == true) {
		$adminDoubleClickLieu = "OnDblClick=\"Javascript:_get_('/administrationajax/doaction?caction=ask_administrationajax_insererlieu&xyz_lieu=".$case["x"]."h".$case["y"]."h".$case["z"]."');\" title='Double-Cliquez pour insérer un nouveau lieu'";
		$adminDoubleClickRoute = "OnDblClick=\"Javascript:_get_('/administrationajax/doaction?caction=ask_administrationajax_insererroute&xyz_route=".$case["x"]."h".$case["y"]."h".$case["z"]."');\" title='Double-Cliquez pour insérer une nouvelle route'";
		$adminDoubleClickEau = "OnDblClick=\"Javascript:_get_('/administrationajax/doaction?caction=ask_administrationajax_inserereau&xyz_eau=".$case["x"]."h".$case["y"]."h".$case["z"]."');\" title='Double-Cliquez pour insérer une nouvelle eau'";
		$adminDoubleClickPalissade = "OnDblClick=\"Javascript:_get_('/administrationajax/doaction?caction=ask_administrationajax_insererpalissade&xyz_palissade=".$case["x"]."h".$case["y"]."h".$case["z"]."');\" title='Double-Cliquez pour insérer une nouvelle palissade'";
	} else {
		$adminDoubleClickLieu = "";
		$adminDoubleClickRoute = "";
		$adminDoubleClickEau = "";
		$adminDoubleClickPalissade = "";
	}
	
	?>
	<?php if ($case["change_level"] == true) : 
		$col="ok"; ?>
		<tr><td><?php echo $case["y"]?></td>
    <?php endif; ?>
	<td class='vue2d <?php echo $case["css"] ?> <?php echo $case["css_actuelle"]?>' nowrap title="<?php echo $case["x"]. "," . $case["y"]." ".$textVille?>" onclick="affDetails('<?php echo $case["x"]?>_<?php echo $case["y"]?>');">
	
	<div class="cases <?php echo $case["css_actuelle"]?>">
		<table class="cases <?php echo $case["css_actuelle"]?>">
		<tr>
		<td class="cases <?php echo $case["css_actuelle"]?>" <?php echo $adminDoubleClickEau?>><?php include('bralduns_monstres.phtml');ob_flush();?></td>
		<td class="cases <?php echo $case["css_actuelle"]?>" <?php echo $adminDoubleClickLieu?>><?php include('lieux_palissades_echoppes.phtml');ob_flush();?></td>
		</tr>
		<tr>
		<td class="cases <?php echo $case["css_actuelle"]?>" <?php echo $adminDoubleClickRoute?>><?php include('cadavres_castars_runes.phtml'); ob_flush(); ?></td>
		<td class="cases <?php echo $case["css_actuelle"]?>" <?php echo $adminDoubleClickPalissade?>><?php include('elements_charrettes.phtml'); ob_flush();?><?php include('cases.phtml');?></td>
		</tr>
		</table>
	</div>
	<?php
	$case = null;
	unset($this->tableau[$k]);
	ob_flush();
	?>
	</td>
<?php endforeach; ?>
</tr>
</table>


<?php if (Zend_Registry::get("estMobile")) : ?>
	Version Mobile : pour marcher, choisissez Marcher dans vos compétences basiques.<br /><br />
<?php 	else : ?>
	Compétence Marcher accessible depuis la vue : 
	Cliquez sur <img src='<?php echo $this->config->url->static?>/images/vue/pas2.png'> pour Marcher<br />
	Laissez votre souris sur les pas pour avoir plus d'informations sur le nombre de PA nécessaires.<br />
<?php endif ?>

&nbsp;