<table class='vue2d' align='center'>
     <?php 
     $col="";
     
     echo "<tr><td>&nbsp;</td>";
     foreach($this->tableau as $k => $case) :
     
    if ($case["change_level"] == 1 && $col == "ok") :
    	break;
    endif;
    echo "<td>".$case["x"]."</td>";
    if ($case["change_level"] == true) : 
          $col="ok";
        endif;
 endforeach;
 echo "</tr>";
	 
$col="";
foreach($this->tableau as $k => $case) :
	$textVille = "";
	if (!empty($case["ville"])) :
		$textVille = " - Ville : ".htmlspecialchars($case["ville"]["nom_ville"]);
		if ($case["ville"]["est_capitale"] === true) {
			$textVille .= " - Capitale";
		}
		$textVille .= ", R&eacute;gion : ".htmlspecialchars($case["ville"]["nom_region"]);
	endif;
	$titre = "Position : ".$case["x"].", ".$case["y"];
      	
	if ($case["change_level"] == 1 && $col == "ok") :
		echo "</tr>";
	endif; 
	
	if ($this->user->administrationvue == true) {
		$adminDoubleClick = "OnDblClick=\"Javascript:_get_('/administrationajax/doaction?caction=ask_administrationajax_insererlieu&xy_lieu=".$case["x"]."h".$case["y"]."');\" title='Double-Cliquez pour insérer un nouveau lieu'";
	} else {
		$adminDoubleClick = "";
	}
	
	?>
	<?php if ($case["change_level"] == true) : 
		$col="ok"; ?>
		<tr nowrap><td><?=$case["y"]?></td>
    <?php endif; ?>
	<td class='vue2d <?=$case["css"] ?> <?=$case["css_actuelle"]?>' nowrap title="<?=$case["x"]. "," . $case["y"]." ".$textVille?>">
	
	<div class="cases <?=$case["css_actuelle"]?>">
		<table class="cases <?=$case["css_actuelle"]?>">
		<tr>
		<td class="cases <?=$case["css_actuelle"]?>"><? include('hobbits_monstres.phtml');ob_flush();?></td>
		<td class="cases <?=$case["css_actuelle"]?>" <?=$adminDoubleClick?>><? include('lieux_palissades_echoppes.phtml');ob_flush();?></td>
		</tr>
		<tr>
		<td class="cases <?=$case["css_actuelle"]?>"><? include('cadavres_castars_runes.phtml'); ob_flush(); ?></td>
		<td class="cases <?=$case["css_actuelle"]?>"><? include('elements_charrettes.phtml'); ob_flush();?><? include('cases.phtml');?></td>
		</tr>
	</table>
	</div>
	<?
	$case = null;
	unset($this->tableau[$k]);
	ob_flush();
	?>
	</td>
<?php endforeach; ?>
</tr>
</table>
&nbsp;