<?php if ($case['n_elements_tabac'] > 0) : 
	$textElementsTabac = '<br>Tabac:<br>';
	$nbFeuilles = 0;
	foreach($case['elements_tabc'] as $m) {
		$s = '';
		if ($m['quantite'] > 1) {
			$s = 's';
		}
		$textElementsTabac .= $m['quantite'] . ' feuille'.$s.' '.addslashes($m['type']).'<br />';
		$nbFeuilles = $nbFeuilles + $m['quantite'] ;
	} 
	$s = '';
	if ($nbFeuilles > 1) {
		$s = 's';
	}
endif; ?>