     <?php if ($case["n_elements"] > 0) : ?>
      	<div>
      	<?php 
      		$textElements = "";
      		$nb = 0;
      		foreach($case["elements"] as $e) {
      			$textElements .= $e["nb"]." ".$e["nom"]."<br />";
      			$nb = $nb + $e["nb"];
			} 
			$s = "";
			if ($nb > 1) {
				$s = "s";
			}
			$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$nb."  &eacute;l&eacute;ment".$s;
		?>
      	<span <?=Bral_Helper_Tooltip::jsTip($textElements, $titre) ?>>
      		<?=$nb ?> &eacute;l&eacute;ment<?=$s?>
      	</span>
      	</div>
    <?php endif; ?>