     <?php if ($case["n_elements_equipements"] > 0) : ?>
      	<div>
      	<?php 
      		$textElementsEquipements = "";
      		foreach($case["elements_equipements"] as $e) {
      			$textElementsEquipements .= "n&deg;".$e["id_equipement"] ." ".htmlspecialchars($e["nom"])." ".htmlspecialchars(addslashes($e["suffixe"]))." de qualit&eacute; ".htmlspecialchars($e["qualite"]) ." niv.".$e["niveau"] ." <br />";
			} 
			$s = "";
			if ($case["n_elements_equipements"] > 1) {
				$s = "s";
			}
			$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_elements_equipements"]."  &eacute;quipement".$s;
		?>
      	<span <?=Bral_Helper_Tooltip::jsTip($textElementsEquipements, $titre) ?>>
      		<?=$case["n_elements_equipements"] ?> &eacute;quipement<?=$s?>
      	</span>
      	</div>
    <?php endif; ?>