<?php if ($case["n_elements_minerais_bruts"] > 0) : ?>
      <?php 
      	$textElementsMineraisBruts = "";
      	$nbMinerais = 0;
     	foreach($case["elements_minerais_bruts"] as $m) {
      		$textElementsMineraisBruts .= $m["quantite"] . " ".htmlspecialchars($m["type"])."<br />";
      		$nbMinerais = $nbMinerais + $m["quantite"] ;
		} 
		$s = "";
		if ($nbMinerais > 1) {
			$s = "s";
		}
	?>
<?php endif; ?>
<?php if ($case["n_elements_lingots"] > 0) : ?>
      <?php
      	$nbLingots = 0;
      	$textElementsLingots = "";
     	foreach($case["elements_lingots"] as $m) {
      		$textElementsLingots .= $m["quantite"] . " ".htmlspecialchars($m["type"])."<br />";
      		$nbLingots = $nbLingots + $m["quantite"] ;
		} 
		$s = "";
		if ($nbLingots > 1) {
			$s = "s";
		}
	?>
<?php endif; ?>