<?
$textCharrette = "";
$textElementsMateriels = "";
$textElementsEquipements = "";
$textElementsMineraisBruts = "";
$textElementsMunitions = "";
$textElementsLingots = "";
$textElementsPartiesPlantesBrutes = "";
$textElementsPartiesPlantesPreparees = "";
$textElements = "";
$textElementsPotions = "";
$textElementsTabac = "";
$textElementsAliments = "";

include('charrettes.phtml');
include('elements_materiels.phtml');
include('elements_aliments.phtml');
include('elements_potions.phtml');
include('elements_equipements.phtml');
include('elements_munitions.phtml');
include('elements_minerais.phtml');
include('elements_partieplantes.phtml');
include('elements_tabac.phtml');
include('elements.phtml'); 


if ($textCharrette != "" || $textElementsMateriels != "" || $textElementsEquipements != "" || $textElementsMunitions != "" || $textElementsMineraisBruts != "" 
	|| $textElementsLingots != "" || $textElementsPartiesPlantesBrutes != "" || $textElementsPartiesPlantesPreparees != "" 
	|| $textElements != "" || $textElementsPotions != "" || $textElementsTabac != "" || $textElementsAliments != "") : ?>
	<span <?=Bral_Helper_Tooltip::jsTip($textCharrette.$textElementsMateriels.$textElementsEquipements.$textElementsMunitions.$textElementsMineraisBruts.$textElementsLingots.$textElementsPartiesPlantesBrutes.$textElementsPartiesPlantesPreparees.$textElementsPotions.$textElementsTabac.$textElementsAliments.$textElements, $titre) ?>>
		<img src='/public/styles/braldahim_defaut/images/vue/elements.png' />
	</span>
<? else: ?>
	&nbsp;
<? endif; ?>