<?php if ($case["n_filons"] > 0) : ?>
      		<div>
      		<?php 
      			$textFilon = "";
      			foreach($case["filons"] as $f) {
      				$textFilon .= " 1 filon de ".htmlentities($f["type"])."<br />";
				}
				$s = "";
				if ($case["n_filons"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_filons"]." Filon".$s;
			?>
      		<span <?=Bral_Helper_Tip::jsTip($textFilon, $titre) ?>>
	      		<?=$case["n_filons"] ?> filon<?=$s?>
	      	</span>
	      	</div>
<?php endif; ?>