<?php 

$textHobbit = "";
$textMonstre = "";
$textNid = "";

if ($case["n_hobbits"] > 0) :
	$sexe_hobbit = "feminin";
	$textHobbit = "<br>Hobbit";
	if ($case["n_hobbits"] > 1) {
		$textHobbit .= "s";
	}
	$textHobbit .= ":<br>";
	foreach($case["hobbits"] as $h) {
		$textHobbit .= '<label class=\\\'alabel profil\\\' onClick=ouvrirProfilH('.$h["id_hobbit"].'); title=\\\'Voir le profil\\\' >';
		$textHobbit .= addslashes(htmlspecialchars($h["prenom_hobbit"]))." ".addslashes(htmlspecialchars($h["nom_hobbit"]));
		$textHobbit .= " (n&deg;".$h["id_hobbit"].")</label>, niv.".$h["niveau_hobbit"];
		
		$textHobbit .= ' <img src=\\\'/public/images/puce_event.gif\\\' title=\\\'Voir les événements\\\' border=\\\'0\\\' onClick=ouvrirEvenementsH('.$h["id_hobbit"].'); style=\\\'cursor:pointer\\\'/> ';
		if ($this->estVueEtendue == false) {
			$textHobbit .= ' <img src=\\\'/public/images/uddeim/env.gif\\\' title=\\\'Envoyer un message\\\' alt=\\\'Ecrire\\\' border=\\\'0\\\' onClick=ecrireMessage('.$h["id_hobbit"].'); style=\\\'cursor:pointer\\\'/> ';
		}
		if ($h["id_communaute"] != null) {
			$textHobbit .= ' - <label class=alabel onClick=ouvrirCommunaute('.$h["id_communaute"].');>'.addslashes(htmlspecialchars($h["nom_communaute"])).'</label>';
		}
		$textHobbit .= "<br>";
		if ($h["sexe_hobbit"] == "masculin") {
			$sexe_hobbit = "masculin";
		}
	} 
	$s = "";
	if ($case["n_hobbits"] > 1) {
		$s = "s";
	}
endif; 

$idTypeMonstre = "";
if ($case["n_monstres"] > 0) :
	$textMonstre = "<br>Monstre";
	if ($case["n_monstres"] > 1) {
		$textMonstre .= "s";
	}
	$textMonstre .= ":<br>";
	foreach($case["monstres"] as $m) {
		$textMonstre .= '<label class=\\\'alabel\\\' onClick=ouvrirMonstre('.$m["id_monstre"].'); title=\\\'Voir le profil\\\' >';
		if ($m["est_gibier"]) {
			$textMonstre .= "Gibier : ";
		}
		$textMonstre .= htmlspecialchars($m["nom_monstre"]) ." ".htmlspecialchars($m["taille_monstre"])." (n&deg;".$m["id_monstre"].")</label> ";
		$textMonstre .= ' <img src=\\\'/public/images/puce_event.gif\\\' title=\\\'Voir les événements\\\' border=\\\'0\\\' onClick=ouvrirEvenementsM('.$m["id_monstre"].'); style=\\\'cursor:pointer\\\'/> ';
		$textMonstre .= "<br />";
		
		if ($idTypeMonstre == "") {
			$idTypeMonstre = $m["id_type_monstre"];
		} elseif ($idTypeMonstre != $m["id_type_monstre"]) {
			$idTypeMonstre = -1;
		}
	} 
	$s = "";
	if ($case["n_monstres"] > 1) {
		$s = "s";
	}
endif;

if ($case["n_nids"] > 0) :
	$textNid = "<br>";
	foreach($case["nids"] as $n) {
		$textNid .= '1 '.$n["nom_nid"].' ('.$n["id_nid"].') ';
		$textNid .= "<br />";
	} 
endif;

?>

<div style="position: absolute;" <?=Bral_Helper_Tooltip::jsTip($textHobbit.$textMonstre.$textNid, $titre) ?>>

<? if ($case["n_nids"] > 0) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/nid.png' style="position: absolute;top:-8px"/>
<?endif;?>

<? if ($case["n_monstres"] > 0) : 
	if ($case["n_monstres"] == 1) {
		$suffixe = "a";
	} else {
		$suffixe = "b";
	}
	if ($idTypeMonstre == 1 || $idTypeMonstre == 5 || 
        $idTypeMonstre == 6 || $idTypeMonstre == 7 || 
        $idTypeMonstre == 8 || $idTypeMonstre == 11) {
    	?> <img src='/public/styles/braldahim_defaut/images/type_monstre/<?=$idTypeMonstre.$suffixe?>.png' style="position: absolute;top:-20px"/> <?
    } else {
    	?> <img src='/public/styles/braldahim_defaut/images/vue/monstre.png' style="position: absolute;top:-17px"/> <?
    }
   endif;
?>

<? if ($case["n_hobbits"] > 1) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/hobbits.png' style="position: absolute;top:-8px" />
<? elseif ($case["n_hobbits"] > 0) : ?>
    <img src='/public/styles/braldahim_defaut/images/vue/hobbit_<?=$sexe_hobbit?>.png' style="position: absolute;top:-8px"/>
<? endif; ?>

 

    
</div>