      	<?php if ($case["n_hobbits"] > 0) : ?>
      		<div>
      		<?php 
      			$textHobbit = "";
      			foreach($case["hobbits"] as $h) {
      				$textHobbit .= htmlentities($h["prenom_hobbit"])." ".htmlentities($h["nom_hobbit"]) .", n&deg; ".$h["id_hobbit"].", niveau ".$h["niveau_hobbit"]."<br>";
				} 
				$s = "";
				if ($case["n_hobbits"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_hobbits"]." Hobbit".$s;
			?>
      		<span <?=Bral_Helper_Tip::jsTip($textHobbit, $titre) ?>>
	      		<?=$case["n_hobbits"] ?> hobbit<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>