      	<?php if ($case["n_hobbits"] > 0) : ?>
      		<div>
      		<?php 
      			$textHobbit = "";
      			foreach($case["hobbits"] as $h) {
      				$textHobbit .= htmlspecialchars($h["prenom_hobbit"])." ".htmlspecialchars($h["nom_hobbit"]);
      				$textHobbit .= " (n&deg; ".$h["id_hobbit"]."), niv.".$h["niveau_hobbit"];
      				$textHobbit .= ' <label class=alabel onClick=ouvrirWin(\\\'\/voir\/hobbit\/?hobbit='.$h["id_hobbit"].'\\\');>[profil]</label>';
      				
      				if ($h["id_fk_jos_users_hobbit"] != null) {
      					$textHobbit .= ' <img src=\\\'/public/images/uddeim/env.gif\\\' title=\\\'Envoyer un message\\\' alt=\\\'Ecrire\\\' border=\\\'0\\\' onClick=ecrireMessage('.$h["id_fk_jos_users_hobbit"].'); style=\\\'cursor:pointer\\\'/> ';
      				} else {
      					$textHobbit .= ' <img src=\\\'/public/images/uddeim/env.gif\\\' alt=\\\'Ecrire impossible\\\' title=\\\'Ce hobbit ne peut pas recevoir de message, il doit se connecter au site avant\\\' border=\\\'0\\\' /> ';
      				}
      				if ($h["id_communaute"] != null) {
      					$textHobbit .= ' - <label class=alabel onClick=ouvrirWin(\\\'\/voir\/communaute\/?communaute='.$h["id_communaute"].'\\\');>'.htmlspecialchars($h["nom_communaute"]).'</label>';
      				}
      				$textHobbit .= "<br />";
				} 
				$s = "";
				if ($case["n_hobbits"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_hobbits"]." Hobbit".$s;
			?>
      		<span <?=Bral_Helper_Tooltip::jsTip($textHobbit, $titre) ?>>
	      		<?=$case["n_hobbits"] ?> hobbit<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>