<?php
$textLieu = '';
$textEchoppe = '';
$textChamp = '';
$type_lieu = '';
$textBallon = '';

$textPalissade = "";
	if ($case["n_palissades"] > 0) :
      	$textPalissade = "<br />Palissade / Portail : <br />";
      	foreach($case["palissades"] as $p) {
		  	if ($p["est_portail_palissade"] == "oui") {
				$textPalissade .= "un portail (n&deg; ".htmlspecialchars($p["id_palissade"]).")";
			} else {
				$textPalissade .= "une palissade (n&deg; ".htmlspecialchars($p["id_palissade"]).")";
			}
      		if ($p["est_destructible_palissade"] == "oui") {
      			$textPalissade .= " destructible";
      		} else {
      			$textPalissade .= " indestructible";
      		}
      		$textPalissade .= "<br />";
		} 
		$s = "";
		if ($case["n_palissades"] > 1) {
			$s = "s";
		}
	endif;
	
if ($case['n_lieux'] > 0) :
	$textLieu = 'Lieu : <br />';
    foreach($case['lieux'] as $l) {
      	$textLieu .= htmlspecialchars($l['nom_lieu']);
      	$type_lieu = $l['nom_systeme_type_lieu'];
      	if ($this->user->administrationvue == true) {
       		$textLieu .= ' <label class=\'alabel\' onclick=_get_(\'\/administrationajax\/doaction?caction=ask_administrationajax_deplacerlieu&id_lieu='.$l['id_lieu'].'\')>[Admin:deplacer]</label>';
      	}
      	
	    if ($this->user->x_braldun == $case['x'] && $this->user->y_braldun == $case['y'] && $this->estVueEtendue == false) {
			$textLieu .= ' <span title="Cliquer pour acc&eacute;der directement au lieu"';
			$textLieu .= ' onclick="Javascript:my_switch(\'box_lieu\',\'boite_c\');" class="alabel">[Entrer dans le lieu]</span>';
		}
	}
	 
endif;

if ($case['n_ballons'] > 0) :
	$textBallon = 'Ballon &agrave terre !<br />';
endif; 

if ($case['n_echoppes'] > 0) :
	$textEchoppe = '';
	$nomSystemeEchoppe = '';
	foreach($case['echoppes'] as $c) {
		if ($c['nom_metier']{0} == 'A') : $d='d\''; else: $d='de '; endif;
		if ($c['nom_echoppe'] != null && $c['nom_echoppe'] != '') :
			$textEchoppe .= htmlspecialchars($c['nom_echoppe']). ', ';
		endif; 
		$textEchoppe .= '&Eacute;choppe '.$d.htmlspecialchars($c['nom_metier']).' appartenant &agrave; <br />';
		$textEchoppe .= '<label class=\'alabel\' onclick=ouvrirWin(\'\/voir\/braldun\/?braldun='.$c['id_braldun'].'\'); title=\'Voir le profil\' >';
		$textEchoppe .= htmlspecialchars($c['prenom_braldun']).' '.htmlspecialchars($c['nom_braldun']).', n&deg; '.$c['id_braldun'];
		$textEchoppe .= '</label>';
		if ($this->estVueEtendue == false) {
			$textEchoppe .= ' <img src=\''.$this->config->static->url.'/images/uddeim/env.gif\' title=\'Envoyer un message\' alt=\'Ecrire\' border=\'0\' onclick=ecrireMessage('.$c['id_braldun'].'); style=\'cursor:pointer\'/> ';
		}
		
		if ($this->user->x_braldun == $case['x'] && $this->user->y_braldun == $case['y'] && $this->estVueEtendue == false) {
			$textEchoppe .= ' <span title="Cliquer pour acc&eacute;der directement &agrave; l\'&eacute;choppe"';
			$textEchoppe .= ' onclick="Javascript:my_switch(\'box_lieu\',\'boite_c\');" style="alabel">[Enter dans l\'échoppe]</span>';
		}
		
      	$textEchoppe .= '<br />';
      	$nomSystemeEchoppe = $c['nom_systeme_metier'];
	}
	$s = '';
	if ($case['n_echoppes'] > 1) {
		$s = 's';
	}
	
endif; 

if ($case['n_champs'] > 0) :
	$textChamp = '<br />Champ : <br />';
	$nomSystemeChamp = '';
	foreach($case['champs'] as $c) {
		if ($c['nom_champ'] != null && $c['nom_champ'] != '') :
			$textChamp .= htmlspecialchars($c['nom_champ']). ', ';
		endif; 
		$textChamp .= 'Champ appartenant &agrave; <br />';
		$textChamp .= '<label class=\'alabel\' onclick=ouvrirWin(\'\/voir\/braldun\/?braldun='.$c['id_braldun'].'\'); title=\'Voir le profil\' >';
		$textChamp .= htmlspecialchars($c['prenom_braldun']).' '.htmlspecialchars($c['nom_braldun']).', n&deg; '.$c['id_braldun'];
		$textChamp .= '</label>';
		if ($this->estVueEtendue == false) {
			$textChamp .= ' <img src=\''.$this->config->static->url.'/images/uddeim/env.gif\' title=\'Envoyer un message\' alt=\'Ecrire\' border=\'0\' onclick=ecrireMessage('.$c['id_braldun'].'); style=\'cursor:pointer\'/> ';
		}
		
		if ($this->user->x_braldun == $case['x'] && $this->user->y_braldun == $case['y'] && $this->estVueEtendue == false) {
			$textChamp .= ' <span title="Cliquer pour acc&eacute;der directement au champ"';
			$textChamp .= ' onclick="Javascript:my_switch(\'box_lieu\',\'boite_c\');" style="alabel">[Enter dans le lieu]</span>';
		}
	
      	$textChamp .= '<br />';
	}
	
endif; ?>

<div class='braltip'>

<?php if ($textPalissade != "") : 
	echo Bral_Helper_Tooltip::render($textPalissade, $titre); endif; ?>
<?php if ($textLieu != '' ) :?>
	<?php echo Bral_Helper_Tooltip::render($textLieu.$textEchoppe.$textChamp.$textBallon, $titre); ?>
	<?php if ($type_lieu != '') : ?>
		<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/batiments/<?php echo $type_lieu?>.png' />
	<?php else: ?>
		<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/batiment.png' />
	<?php endif; ?>
<?php elseif ($textChamp != '') : ?>
	<?php echo Bral_Helper_Tooltip::render($textLieu.$textEchoppe.$textChamp.$textBallon, $titre); ?>
	<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/champ.png' />
<?php elseif ($textEchoppe != '') : ?>
	<?php echo Bral_Helper_Tooltip::render($textLieu.$textEchoppe.$textChamp.$textBallon, $titre); ?>
	<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/echoppes/<?php echo $nomSystemeEchoppe?>.png' />
<?php else: ?>
	<br />
<?php endif;?>  

<?php if ($textBallon != '') : ?>
<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/ballon.png'/>
<?php endif;?>
</div>