<?php if ($case["n_lieux"] > 0) : ?>
	<div>
      <?php 
      $textLieu = "";
      foreach($case["lieux"] as $l) {
      	$textLieu .= addslashes(htmlspecialchars($l["nom_lieu"])) ." : ".addslashes(htmlspecialchars($l["nom_type_lieu"]));
	}
	 
	$titre = "Position X:".$case["x"]." Y:".$case["y"]." Lieux.";
	$doubleClick = "";
	if ($this->user->x_hobbit == $case["x"] && $this->user->y_hobbit == $case["y"]) {
		$doubleClick = "title=\"Double Cliquer pour acc&eacute;der directement au lieu\"";
		$doubleClick .= "OnDblClick=\"Javascript:my_switch('box_lieu','boite_c'); return cClick(); \"";
	}
	?>
      <span <?=$doubleClick ?> <?=Bral_Helper_Tooltip::jsTip($textLieu, $titre) ?>>
      <?php if ($case["n_lieux"] == 1) : ?>
      	<?=htmlspecialchars($l["nom_type_lieu"]);?>
      <?php elseif ($case["n_lieux"] > 1) : ?>
      	<?=$case["n_lieux"] ?> lieux
      <?php endif; ?>
      </span>
      <br />
      </div>
<?php endif; ?>