      	<?php if ($case["n_monstres"] > 0) : ?>
      		<div>
      		<?php 
      			$textMonstre = "";
      			foreach($case["monstres"] as $m) {
      				$textMonstre .= htmlspecialchars($m["nom_monstre"]) ." (n&deg; ".$m["id_monstre"].") - ".htmlspecialchars($m["taille_monstre"])."  ";
      				$textMonstre .= ' <img src=\\\'/public/images/profil.gif\\\' title=\\\'Voir le profil\\\' alt=\\\'Profil\\\' border=\\\'0\\\' onClick=ouvrirWin(\\\'\/voir\/monstre\/?monstre='.$m["id_monstre"].'\\\'); style=\\\'cursor:pointer\\\'/> ';
      				$textMonstre .= "<br />";
				} 
				$s = "";
				if ($case["n_monstres"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_monstres"]." Monstre".$s;
			?>
      		<span <?=Bral_Helper_Tooltip::jsTip($textMonstre, $titre) ?>>
	      		<?=$case["n_monstres"] ?> monstre<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>	    