      	<?php if ($case["n_palissades"] > 0) : ?>
      		<div>
      		<?php 
      			$textPalissade = "";
      			foreach($case["palissades"] as $p) {
      				$textPalissade .= "1 palissade (n&deg; ".htmlentities($p["id_palissade"]).")<br />";
				} 
				$s = "";
				if ($case["n_palissades"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_palissades"]." Palissade".$s;
			?>
      		<span <?=Bral_Helper_Tooltip::jsTip($textPalissade, $titre) ?>>
	      		<?=$case["n_palissades"] ?> palissade<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>