     	<?php if ($case["n_plantes"] > 0) : ?>
      		<div>
      		<?php 
      			$textPlante = "";
      			foreach($case["plantes"] as $p) {
      				$textPlante .= htmlentities($p["type"])." - ". htmlentities($p["categorie"]) .", n&deg; ".$p["id_plante"]."<br />";
				}
				$s = "";
				if ($case["n_plantes"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_plantes"]." Plante".$s;
			?>
      		<span <?=Bral_Helper_Tip::jsTip($textPlante, $titre) ?>>
	      		<?=$case["n_plantes"] ?> plante<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>