      	<?php if ($case["n_routes"] > 0) : ?>
      		<div>
      		<?php 
      			$textRoute = "";
      			foreach($case["routes"] as $p) {
      				if ($p["est_route"] == "oui") {
      					$textRoute .= " 1 Route";
      				} else {
      					$textRoute .= " 1 Terrain terrass&eacute;";
      				}
				}
				$s = "";
				if ($case["n_routes"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_routes"]." Route".$s;
			?>
      		<span <?=Bral_Helper_Tooltip::jsTip($textRoute, $titre) ?>>
	      		<?=$textRoute?> 
	      	</span>
	      	</div>
	    <?php endif; ?>