     	<?php if ($case["n_runes"] > 0) : ?>
      		<div>
      		<?php 
      			$textRune = "";
      			foreach($case["runes"] as $r) {
      				$textRune .= "1 rune, n&deg; ".$r["id_rune"]."<br />";
				} 
				$s = "";
				if ($case["n_runes"] > 1) {
					$s = "s";
				}
				$titre = "Position X:".$case["x"]." Y:".$case["y"]." - ".$case["n_runes"]."  Rune".$s;
			?>
      		<span <?=Bral_Helper_Tip::jsTip($textRune, $titre) ?>>
	      		<?=$case["n_runes"] ?> rune<?=$s?>
	      	</span>
	      	</div>
	    <?php endif; ?>