  <div class="titre textalia textsizec"> Ma Vue</div>
  <table width="100%">
  <tr>
  	<td width="25%">
	  	<div class="box_contenu1 textalia braltip" style="float:left">
	  	<?php if ($this->centre_nom_region != null) : ?><?php echo Bral_Helper_Tooltip::render($this->centre_description_region)?><?php endif;?>
	  	
	    <?php if ($this->est_pvp_region == true) :?>
	    	<img src='<?php echo $this->config->url->static?>/images/type_region/region_pvp.png' alt='region_pvp' title="R&eacute;gion PVP"/>
	    <?php else: ?>
	    	<img src='<?php echo $this->config->url->static?>/images/type_region/region_pve.png' alt='region_pve' title="R&eacute;gion PVE"/>
	    <?php endif; ?>
	     <?php echo $this->centre_nom_region ?>&nbsp;
	    
	    <?php if (!empty($this->centre_nom_ville)):?>
	     <a class="titre textalia textsized" title="Cliquez pour voir <?php echo $this->centre_nom_ville ?> dans les règles" style="text-decoration: none" onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/<?php echo $this->centre_nom_ville ?>')";><?php echo $this->centre_nom_ville ?></a>
	    <?php endif; ?>
	    <?php if ($this->centre_est_capitale) : ?>
	    	- Capitale
	    <?php endif; ?>
	    </div>
		   Ma Position : <b><?php echo $this->user->x_braldun ?>, <?php echo $this->user->y_braldun ?></b> <br /><br />

	  	</td>
  	<td width="10%" sytle="text-align:right">
  		<?php include('boussole.phtml'); ?>
  	</td>
  </tr>
  </table>
  
  <?php if ($this->user->administrationvue == true) :?>
  <b>Administration par la vue activée.</b><br />
  Double-Cliquez sur le coin supérieur gauche d'une case pour ajouter une eau.<br />
  Double-Cliquez sur le coin supérieur droit d'une case pour ajouter un lieu.<br />
  Double-Cliquez sur le coin inférieur gauche d'une case pour ajouter / supprimer une route.<br />
  Double-Cliquez sur le coin inférieur gauche d'une case pour ajouter / supprimer une palissade.<br /><br />

	Ville : 
 	<select name='administrationvue_ville' id="administrationvue_ville" onchange="_get_('/administrationajax/doaction?caction=do_administrationajax_positionnervue&id_ville=' + this.value);">
 	<option value="-1" selected>Choisissez une ville</option>
 	<?php foreach ($this->administrationVilles as $v) : ?>
		<option value="<?php echo $v["id_ville"]?>"><?php echo $v["id_ville"]?> : <?php echo $v["nom_ville"]?></option>
	<?php endforeach; ?>
	</select>
	
	Lieux : 
 	<select name='administrationvue_lieu' id="administrationvue_lieu" onchange="_get_('/administrationajax/doaction?caction=do_administrationajax_positionnervue&id_lieu=' + this.value);">
 	<option value="-1" selected>Choisissez un lieu</option>
 	<?php foreach ($this->administrationLieux as $l) : ?>
		<option value="<?php echo $l["id_lieu"]?>"><?php echo $l["id_lieu"]?> : <?php echo $l["nom_lieu"]?> (<?php echo $l["x_lieu"]?>,<?php echo $l["y_lieu"]?>)</option>
	<?php endforeach; ?>
	</select>
	<br />
	
	X:<input type="text" id="administrationvue_x" name="administrationvue_x" size="3" value="<?php echo $this->centre_x ?>" required>
	Y:<input type="text" id="administrationvue_y" name="administrationvue_y" size="3" value="<?php echo $this->centre_y ?>" required>
	Z:<input type="text" id="administrationvue_z" name="administrationvue_z" size="3" value="<?php echo $this->z_position ?>" required>
	<input type="button" class='button1' value="Se Positionner" onclick="_get_('/administrationajax/doaction?caction=do_administrationajax_positionnervue&xyz_position=' + $('#administrationvue_x').val() + 'h' + $('#administrationvue_y').val() + 'h' + $('#administrationvue_z').val());"/>

  <?php endif;?>