  <div style=" float: left;">
  	<ul class="titre textalia textsizec"> Ma Vue</ul>
  	<? if ($this->centre_nom_region != null) : ?>
  		<? $js=Bral_Helper_Tooltip::jsTip(str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlspecialchars(addslashes($this->centre_description_region)))), "Description de la ".htmlspecialchars($this->centre_nom_region), true) ?>
  	<? else: $js=""; ?>
  	<? endif; ?>
  	<ul class="titre textalia textsized" <?=$js ?>>
    <?=$this->centre_nom_region ?>&nbsp;
    </ul>
    <ul class="titre textalia textsized" >
    <? if (!empty($this->centre_nom_ville)):?>
     <?=$this->centre_nom_ville ?>
    <? endif; ?>
    <? if ($this->centre_est_capitale) : ?>
    	- Capitale
    <? endif; ?>
    &nbsp;<br /> &nbsp;
  </ul>
  </div>
  <div style=" float: right;">
  <ul class="titre textalia textsized">
    Ma Position : X=  <?=$this->user->x_hobbit ?> , Y= <?=$this->user->y_hobbit ?> Vue=<?=$this->vue_nb_cases ?> <?=$this->environnement ?> <br />
    Centrage : X= <?=$this->centre_x ?> , Y= <?=$this->centre_y ?> <?=$this->centre_environnement ?> <br />
  	</ul>	<br /><br />
  </div>
  <? include('boussole.phtml'); ?>
