  <div style=" float: left;">
  	<ul class="titre textalia textsizec"> Ma Vue</ul>
  	<ul class="titre textalia textsized" 
  		<?=Bral_Helper_Tooltip::jsTip(str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlentities(addslashes($this->centre_description_region)))), "Description de la ".htmlentities($this->centre_nom_region), true) ?>>
    <?=htmlentities($this->centre_nom_region) ?>
    </ul>
    <ul class="titre textalia textsized" >
    <? if (!empty($this->centre_nom_ville)):?>
     <?=htmlentities($this->centre_nom_ville) ?> 
    <? endif; ?>
    <? if ($this->centre_est_capitale) : ?>
    	- Capitale
    <? endif; ?><br />
  </ul>
  </div>
  <div style=" float: right;">
  <ul class="titre textalia textsized">
    X=  <?=$this->user->x_hobbit ?> , Y= <?=$this->user->y_hobbit ?> Vue : <?=$this->vue_nb_cases ?> <?=$this->environnement ?> <br />
    Centrage : X= <?=$this->centre_x ?> , Y= <?=$this->centre_y ?> <?=$this->centre_environnement ?> <br />
  	</ul>	<br />
  </div>
  <div>
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=hg&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_haut_gauche.gif" border="0">
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=h&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_haut.gif" border="0">
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=hd&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_haut_droit.gif" border="0"><br />
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=g&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_gauche.gif" border="0">
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=d&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_droite.gif" border="0"><br />
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=bg&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_bas_gauche.gif" border="0">
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=b&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_bas.gif" border="0">
    <img onClick="Javascript:_get_('/interface/vue?caction=box_vue&valeur_1=bd&valeur_2=<?=$this->centre_x ?>&valeur_3=<?=$this->centre_y ?>')"
     src="/public/images/puce_bas_droit.gif" border="0">
  </div>
  &nbsp;