<br />
  <center>
  
  <div class="titrea textalic titreasizec">Réputation</div>
  Points de Gredin : <?php echo $this->braldun["points_gredin_braldun"];?><br />
  Points de Redresseur de Torts : <?php echo $this->braldun["points_redresseur_braldun"];?><br /><br />
  
  <div class="titre textalic textsizec">Distinctions</div>
  <?php $s=""; if ($this->braldun["points_distinctions_braldun"] > 1): $s='s'; endif; ?>
   <?php echo $this->braldun["points_distinctions_braldun"] ?> point<?php echo $s?> de distinction (total actualisé une fois par jour)
   <br />
   </center>
   	
  <table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Date</th>
		<th>Distinction</th>
		<th>Points</th>
	  </tr>
	</thead>
  <?php if (count($this->tabDistinctions) >= 1): ?>
	<tbody>
	
	<?php foreach($this->tabDistinctions as $d): ?>
		 <tr class="table_liste">
		 	<td class="table_liste_th" colspan="3">Catégorie : <?php echo $d["nom"]?></td>
		 </tr>
	  	<?php $i = 0; 
	  	foreach($d["distinctions"] as $t): ?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste"><?php echo $t["date_hdistinction"]?></td>
		  		<td class="table_liste"><?php echo $t["nom"]?></td>
		  		<td class="table_liste"><?php echo $t["points"]?></td>
	  		</tr>
	  	<?php endforeach; ?>
  	<?php endforeach; ?>
  	</tbody>
   <?php else: ?>
   <tr class="table_liste">
    <td colspan='5'>
   	Aucune distinction
    </td>
    </tr>
   <?php endif; ?>
   </table>
