<center>  	
<?php if ($this->pereMereOk === true) :?>
	  	Suite &agrave; l'heureuse rencontre entre sa m&egrave;re 
  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->braldun["id_fk_mere_braldun"] ?>');">
  		<?php if ($this->mere == null): ?>
  			Braldun inconnue (n&deg;<?php echo $this->braldun["id_fk_mere_braldun"] ?>)
  		<?php else : ?>
  			<?php if ($this->mereAncienne) : ?>
  				<?php echo $this->mere->prenom_ancien_braldun ?> <?php echo $this->mere->nom_ancien_braldun ?>
  			<?php else: ?>
  				<?php echo $this->mere->prenom_braldun ?> <?php echo $this->mere->nom_braldun ?>
  			<?php endif;?>
  			(n&deg;<?php echo $this->braldun["id_fk_mere_braldun"] ?>)
  		<?php endif;?>
  		</a>
	  	et son p&egrave;re
  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->braldun["id_fk_pere_braldun"] ?>');">
  		<?php if ($this->pere == null): ?>
  			Braldun inconnu (n&deg;<?php echo $this->braldun["id_fk_pere_braldun"] ?>)
  		<?php else : ?>
  			<?php if ($this->pereAncien) : ?>
  				<?php echo $this->pere->prenom_ancien_braldun ?> <?php echo $this->pere->nom_ancien_braldun ?>
  			<?php else: ?>
  				<?php echo $this->pere->prenom_braldun ?> <?php echo $this->pere->nom_braldun ?>
  			<?php endif;?>
  			(n&deg;<?php echo $this->braldun["id_fk_pere_braldun"] ?>)
  		<?php endif;?>
  		</a>
	    <br />
	    <?php echo $this->braldun["prenom_braldun"] ?> <?php echo $this->braldun["nom_braldun"] ?>  (n&deg;<?php echo $this->braldun["id_braldun"] ?>)
	  	 est n&eacute;<?php if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?>
	  	 <span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->braldun["date_creation_braldun"] );?>">
		<?php echo Bral_Helper_Calendrier::affiche(false, $this->braldun["date_creation_braldun"] );?>.
		</span>
  	
  	<?php else: ?>
	  	<?php if ($this->braldun["sexe_braldun"] == 'feminin') : echo "Elle"; else : echo "Il"; endif;?>
	  	 est n&eacute;<?php if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?> orphelin<?php if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?> 
	  	 le  <span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->braldun["date_creation_braldun"] );?>">
		<?php echo Bral_Helper_Calendrier::affiche(false, $this->braldun["date_creation_braldun"] );?>.
		</span>
  	<?php endif; ?>
    <br /><br />
    
    <?php if ($this->nbEnfants == 0 && $this->conjoint == null) :?>
    	<?php if ($this->braldun["sexe_braldun"] == 'feminin') : echo "Elle"; else : echo "Il"; endif;?>
    	 n'a ni enfant, ni conjoint<?php if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>.
    <?php else : ?>
    	Avec <?php if ($this->braldun["sexe_braldun"] != 'feminin'): echo "sa"; else: echo "son"; endif;?> 
    	conjoint<?php if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>
    	
    	<?php if ($this->conjoint != null) : ?>
	    	<a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->conjoint["id_braldun"] ?>');">
	    		<?php echo $this->conjoint["prenom"] ?> <?php echo $this->conjoint["nom"] ?> (n&deg;<?php echo $this->conjoint["id_braldun"] ?>)</a>,
	    <?php else: ?>
	    	disparu<?php if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>
	    <?php endif; ?>
    	 <?php if ($this->braldun["sexe_braldun"] == 'feminin') : echo "elle"; else : echo "il"; endif;?>
    	  a eu <?php echo $this->nbEnfants ?> enfant<?php if ($this->nbEnfants > 1) echo 's' ?>.<br />
    	
    	<?php if ($this->nbEnfants > 0) : ?>
	    	<table class="table_liste" style="width:80%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>Braldun</th>
					<th>Naissance</th>
				  </tr>
				</thead>
				<tbody>
					<?php foreach($this->enfants as $e) :?>
					<tr class="table_liste">
						<td><a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $e["id_braldun"] ?>');"><?php echo $e["prenom"] ?> <?php echo $e["nom"] ?> (n&deg;<?php echo $e["id_braldun"]?>)</a></td>
						<td nowrap>n&eacute;<?php if ($e["sexe_braldun"] == 'feminin') echo "e"?> 
						le 
						<span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$e["date_naissance"] );?>">
						<?php echo Bral_Helper_Calendrier::affiche(false, $e["date_naissance"] );?>
						</span></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php endif; ?>
    <?php endif; ?>
   <br /><br />
</center>