<center>  	
<? if ($this->pereMereOk === true) :?>
	  	Suite &agrave; l'heureuse rencontre entre sa m&egrave;re 
  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?=$this->braldun["id_fk_mere_braldun"] ?>');">
  		<? if ($this->mere == null): ?>
  			Braldun inconnue (n&deg;<?=$this->braldun["id_fk_mere_braldun"] ?>)
  		<? else : ?>
  			<? if ($this->mereAncienne) : ?>
  				<?=$this->mere->prenom_ancien_braldun ?> <?=$this->mere->nom_ancien_braldun ?>
  			<? else: ?>
  				<?=$this->mere->prenom_braldun ?> <?=$this->mere->nom_braldun ?>
  			<? endif;?>
  			(n&deg;<?=$this->braldun["id_fk_mere_braldun"] ?>)
  		<? endif;?>
  		</a>
	  	et son p&egrave;re
  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?=$this->braldun["id_fk_pere_braldun"] ?>');">
  		<? if ($this->pere == null): ?>
  			Braldun inconnu (n&deg;<?=$this->braldun["id_fk_pere_braldun"] ?>)
  		<? else : ?>
  			<? if ($this->pereAncien) : ?>
  				<?=$this->pere->prenom_ancien_braldun ?> <?=$this->pere->nom_ancien_braldun ?>
  			<? else: ?>
  				<?=$this->pere->prenom_braldun ?> <?=$this->pere->nom_braldun ?>
  			<? endif;?>
  			(n&deg;<?=$this->braldun["id_fk_pere_braldun"] ?>)
  		<? endif;?>
  		</a>
	    <br />
	    <?=$this->braldun["prenom_braldun"] ?> <?=$this->braldun["nom_braldun"] ?>  (n&deg;<?=$this->braldun["id_braldun"] ?>)
	  	 est n&eacute;<? if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?>
	  	 <span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->braldun["date_creation_braldun"] );?>">
		<?=Bral_Helper_Calendrier::affiche(false, $this->braldun["date_creation_braldun"] );?>.
		</span>
  	
  	<? else: ?>
	  	<? if ($this->braldun["sexe_braldun"] == 'feminin') : echo "Elle"; else : echo "Il"; endif;?>
	  	 est n&eacute;<? if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?> orphelin<? if ($this->braldun["sexe_braldun"] == 'feminin') echo "e"?> 
	  	 le  <span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->braldun["date_creation_braldun"] );?>">
		<?=Bral_Helper_Calendrier::affiche(false, $this->braldun["date_creation_braldun"] );?>.
		</span>
  	<? endif; ?>
    <br /><br />
    
    <? if ($this->nbEnfants == 0 && $this->conjoint == null) :?>
    	<? if ($this->braldun["sexe_braldun"] == 'feminin') : echo "Elle"; else : echo "Il"; endif;?>
    	 n'a ni enfant, ni conjoint<? if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>.
    <? else : ?>
    	Avec <? if ($this->braldun["sexe_braldun"] != 'feminin'): echo "sa"; else: echo "son"; endif;?> 
    	conjoint<? if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>
    	
    	<? if ($this->conjoint != null) : ?>
	    	<a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?=$this->conjoint["id_braldun"] ?>');">
	    		<?=$this->conjoint["prenom"] ?> <?=$this->conjoint["nom"] ?> (n&deg;<?=$this->conjoint["id_braldun"] ?>)</a>,
	    <? else: ?>
	    	disparu<? if ($this->braldun["sexe_braldun"] != 'feminin') echo "e"?>
	    <? endif; ?>
    	 <? if ($this->braldun["sexe_braldun"] == 'feminin') : echo "elle"; else : echo "il"; endif;?>
    	  a eu <?=$this->nbEnfants ?> enfant<? if ($this->nbEnfants > 1) echo 's' ?>.<br />
    	
    	<? if ($this->nbEnfants > 0) : ?>
	    	<table class="table_liste" style="width:80%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>Braldun</th>
					<th>Naissance</th>
				  </tr>
				</thead>
				<tbody>
					<? foreach($this->enfants as $e) :?>
					<tr class="table_liste">
						<td><a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?=$e["id_braldun"] ?>');"><?=$e["prenom"] ?> <?=$e["nom"] ?> (n&deg;<?=$e["id_braldun"]?>)</a></td>
						<td nowrap>n&eacute;<? if ($e["sexe_braldun"] == 'feminin') echo "e"?> 
						le 
						<span style="cursor:pointer" title="<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$e["date_naissance"] );?>">
						<?=Bral_Helper_Calendrier::affiche(false, $e["date_naissance"] );?>
						</span></td>
					</tr>
					<? endforeach; ?>
				</tbody>
			</table>
		<? endif; ?>
    <? endif; ?>
   <br /><br />
</center>