<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Stock Tabacs</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<?php if ($this->creation === true) : ?>
				<b>Cr&eacute;ation du nouveau stock effectu&eacute;e</b> <br />
			<?php endif; ?>
			<form action="/Administrationstocktabac/tabac" method="post">
				
				Ajouter un nouveau stock, qui sera actif le : 
				<?php echo $this->dateCreationStock ?>
				<br /><br />
					<span class="titre textalia textsizeb">PV : Prix de Vente en castars, par la boutique</span><br />
					<span class="titre textalia textsizeb">PR : Prix de Reprise en castars, par la boutique</span><br />
					<span class="titre textalia textsizeb">NB : Quantité initiale</span><br />
				<br /><br />
				
				<table width="100%">
				<?php 
				$i = -1;
				foreach ($this->regions as $r) : ?>
					<?php 
					$i++;
					if ($i % 4 == 0): ?><tr><?php endif;?>
						<td style="text-align:right">
							<span class="titre textalia textsizec"><?php echo $r["nom_region"]?></span> <br />
							<?php foreach ($r["type_tabac"] as $t) : ?>
							
								<span class="titre textalia textsized"><?php echo $t["nom"]?></span><br />
							
								 <?php echo $t["nom"]?>
								 <span title='Prix Vente en castars' style="cursor:pointer">PV</span> <input type="text" name="<?php echo $t["id_form"]."_vente"?>" size='3' value="<?php echo $t["prix_unitaire_vente"]?>" />
								 <span title='Prix Reprise en castars' style="cursor:pointer">PR</span> <input type="text" name="<?php echo $t["id_form"]."_reprise"?>" size='3' value="<?php echo $t["prix_unitaire_reprise"]?>"/>
								 <span title='Prix Reprise en castars' style="cursor:pointer">NB</span> <input type="text" name="<?php echo $t["id_form"]."_nbinitial"?>" size='3' value="<?php echo $t["nb_feuille"]?>"/> <br />
								<br />
							<?php endforeach; ?>
							<br /><br />
						
						</td>
					<?php if ($i % 4 == 3): echo "</tr>"; endif;?>
				<?php endforeach; ?>
				</table>
				
			<input type="submit" class="button" name="add" value="Ajouter le nouveau stock" />
			</form>
			
			<br /><br />
			<form action="/Administrationstocktabac/tabac" method="post">
				Date Stock (AAAA-MM-JJ 00:00:00) 
				
				<select name="dateStock">
					<?php foreach($this->listeDates as $k=>$v) : ?>
						<option value="<?php echo $v?>" <?php if ($this->dateStock == $v) : echo "selected"; endif;?>><?php echo substr($v, 0, 10)?></option>
					<?php endforeach;?>
				</select>
				
				<input type="submit" class="button" name="add" value="Voir stock" />
			</form>
			
		<br /><br />
			
			<?php if (count($this->stocks) > 0 ) : ?>
				<table align='center'>
				<tr>
				<th class='comp_titre'>N&deg;</th>
				<th class='comp_titre'>Date</th>
				<th class='comp_titre'>Type Tabac</th>
				<th class='comp_titre'>Stock Initial</th>
				<th class='comp_titre'>Stock Restant</th>
				<th class='comp_titre'>Prix de Vente par Boutique</th>
				<th class='comp_titre'>Prix de Reprise</th>
				<th class='comp_titre'>R&eacute;gion</th>
				</tr>
				<?php foreach($this->stocks as $r) :?>
					<tr>
						<td><?php echo $r["id_stock_tabac"]?></td>
						<td><?php echo $r["date_stock_tabac"]?></td>
						<td><?php echo $r["nom_type_tabac"]?></td>
						<td><?php echo $r["nb_feuille_initial_stock_tabac"]?></td>
						<td><?php echo $r["nb_feuille_restant_stock_tabac"]?></td>
						<td><?php echo $r["prix_unitaire_vente_stock_tabac"]?></td>
						<td><?php echo $r["prix_unitaire_reprise_stock_tabac"]?></td>
						<td><?php echo $r["id_fk_region_stock_tabac"]?></td>
					</tr>
				<?php endforeach;?>
				</table>
			<?php else: ?>
			Ancun stock, date <?php echo $this->dateStock?>
			<?php endif;?>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>