<ul class="box_contenu textalic">
	<ul class="titre textalic textsizea">
	Scripts Publics pour développeurs
	</ul>
	<br>
	Les données publiques et les Scripts Publics permettent à tout développeur de pouvoir
	construire une interface de jeu externe.<br>
	
	<br><br>
	
	<table width="100%">
		<tr valign="top">
			<td  width="50%">
				<ul class="titre textalic textsizeb">
				Données Publiques
				</ul>
				<br>
				<ul style="text-align:left">
					<li>
					Fichiers CSV disponibles à l'adresse : <a href='http://public.braldahim.com'>http://public.braldahim.com</a>
					</li>
					<li>
					Les fichiers sont encodés en UTF8
					</li>
				</ul>
				<br><br>
			
			</td>
			<td style="align:left" width="50%">
				<ul class="titre textalic textsizeb">
				Scripts Publics
				</ul>
				<br>
				<ul style="text-align:left">
					<li>
					Les Scripts Publics renvoient les données associées à un Braldûn.
					</li>
					<li>
					Le nombre d'appels autorisés aux Scripts Publics est limité. 
					</li>
					<li>
					 XXX = le NUMERO d'un Braldûn
					</li>
					<li>
					 YYY = le mot de passe restreint correspondant. 
					</li>
					<li>
					Le mot de passe restreint peut-être obtenu ici : <a href='/md5/'>http://sp.braldahim.com/md5/</a>. 
					</li>
					<li>
					Info, anomalies, pour en parler... <a href='http://forum.braldahim.com/viewforum.php?f=30'>Forum Scripts Publics et Interfaces Externes</a>
					</li>
				</ul>
				
				<br>
				
				<br>
			</td>
		</tr>
	</table>
</ul>

<br>

<ul class="box_contenu textalic">
	<ul class="titre textalic textsizeb">
	Détails des Scripts Publics
	</ul>
	<br>
	
	Le nombre d'appels autorisés aux Scripts Publics est limité par <u>jour et par catégorie</u>.<br>
	<br>
	<table style="width:90%" class="table_liste"  valign="top">
		
		<thead class="table_liste">
			<th colspan="2">Catégorie Scripts Dynamiques : 24 appels par jour</th>
		</thead>
		
		<tr>
			<td width="20%">
				Vue
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/vue/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			Détails d'une ligne: TYPE;position_x;position_y;postion_z;autre_element;autre_element...
			
			<div id='details_vue_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_vue_a','details_vue_b');">
			</div>
				
			<div id='details_vue_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_vue_a', 'details_vue_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			POSITION;x;y;z;xMin;xMax;yMin;yMax;idBraldun;vueNbCases;vueBm
			ENVIRONNEMENT;x;y;z;nom_systeme_environnement;nom_environnement
			CADAVRE;x;y;z; id_monstre;nom_type_monstre;$c_taille
			CHARRETTE;x;y;z; id_charrette;nom_type_materiel
			ECHOPPE;x;y;z;id_echoppe;nom_echoppe;nom_systeme_metier;nom_metier;id_braldun
			CHAMP;x;y;z;id_champ;id_braldun
			CREVASSE;x;y;z;id_crevasse
			ELEMENT;x;y;z;Peau;quantite_peau_element
			ELEMENT;x;y;z;Cuir;quantite_cuir_element 
			ELEMENT;x;y;z;Fourrure;quantite_fourrure_element
			ELEMENT;x;y;z;Planche;quantite_planche_element
			ELEMENT;x;y;z;Rondin;quantite_rondin_element
			ELEMENT;x;y;z;Castar;quantite_castar_element
			EQUIPEMENT;x;y;z;id_element_equipement;nom;nom_type_qualite;niveau_recette_equipement;suffixe_mot_runique
			MATERIEL;x;y;z;id_element_materiel;nom_type_materiel
			MUNITION;x;y;z;nom_type_munition;nom_pluriel_type_munition;quantite_element_munition
			POTION;x;y;z;id_element_potion;type;nom_type_potion;nom_type_qualite;niveau_potion
			ALIMENT;x;y;z;id_element_aliment;nom_type_aliment;nom_type_qualite
			GRAINE;x;y;z;quantite_element_graine;nom_type_graine
			INGREDIENT;x;y;z;quantite_element_ingredient;nom_type_ingredient
			MINERAI_BRUT;x;y;z;quantite_brut_element_minerai;nom_type_minerai
			LINGOT;x;y;z;quantite_lingots_element_minerai;nom_type_minerai
			PLANTE_BRUTE;x;y;z;quantite_element_partieplante;nom_type_partieplante;nom_type_plante
			PLANTE_PREPAREE;x;y;z;quantite_preparee_element_partieplante;nom_type_partieplante;nom_type_plante
			RUNE;x;y;z;id_rune_element_rune
			TABAC;x;y;z;quantite_feuille_element_tabac;nom_court_type_tabac
			BRALDUN;x;y;z;id_braldun;est_ko_braldun;est_intangible_braldun;est_soule_braldun;soule_camp_braldun;id_fk_soule_match_braldun
			LIEU;x;y;z;id_lieu;nom_lieu;nom_type_lieu;nom_systeme_type_lieu
			MONSTRE;x;y;z;id_monstre;nom_type_monstre;m_taille;niveau_monstre
			NID;x;y;z;id_nid;nom_nid_type_monstre
			PALISSADE;x;y;z;id_palissade;est_destructible_palissade
			BUISSON;x;y;z;id_buisson;nom_type_buisson
			BOSQUET;x;y;z;id_bosquet;nom_systeme_type_bosquet
			ROUTE;x;y;z;id_route;type_route
			BALLON_SOULE;x;y;z;present
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_vue_a', 'details_vue_b');">
			</div>
			<br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Profil
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/profil/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			<div id='details_profil_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_profil_a','details_profil_b');">
			</div>
				
			<div id='details_profil_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_profil_a', 'details_profil_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			Toutes les valeurs retournées sont sur une même ligne :
			
			idBraldun;prenom;nom;x;y;z;paRestant;DLA;DureeProchainTour;PvRestant;bmPVmax;bbdf;
			nivAgilite;nivForce;nivVigueur;nivSagesse;
			bmAgilite;bmForce;bmVigueur;bmSagesse;
			bmBddfAgilite;bmBddfForce;bmBddfVigueur;bmBddfSagesse;
			bmVue;regeneration;bmRegeneration;
			pxPerso;pxCommun;pi;niveau;poidsTransportable;poidsTransporte;armureNaturelle;
			armureEquipement;bmAttaque;bmDegat;bmDefense;nbKo;nbKill;nbKoBraldun;
			estEngage;estEngageProchainTour;estIntangible;nbPlaquagesSubis;nbPlaquagesEffectues
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_profil_a', 'details_profil_b');">
			</div>
			<br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Événements
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/evenements/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			Détails d'une ligne: idBraldun;idEvenement;type;date;details
			<br><br>
			</td>
		</tr>
		
		<thead class="table_liste">
			<th colspan="2">Catégorie Scripts Statiques : 10 appels par jour</th>
		</thead>
		<tr valign="top">
			<td  width="20%">
				<br>Compétences
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/competences/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			Détails d'une ligne: idBraldun;typeCompetence;idCompetence;nom;nom_systeme;maitrise;idMetier
			<br><br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Contenu du Laban
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/laban/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			Détails d'une ligne: TYPE;autre_element;autre_element...
			
			<div id='details_laban_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_laban_a','details_laban_b');">
			</div>
				
			<div id='details_laban_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_laban_a', 'details_laban_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			ELEMENT;Peau;quantite_peau_element
			ELEMENT;Cuir;quantite_cuir_element 
			ELEMENT;Fourrure;quantite_fourrure_element
			ELEMENT;Planche;quantite_planche_element
			ELEMENT;Rondin;quantite_rondin_element
			ELEMENT;Castar;quantite_castar_element
			EQUIPEMENT;id_element_equipement;nom;nom_type_qualite;niveau_recette_equipement;suffixe_mot_runique
			MATERIEL;id_element_materiel;nom_type_materiel
			MUNITION;nom_type_munition;nom_pluriel_type_munition;quantite_element_munition
			POTION;id_element_potion;type;nom_type_potion;nom_type_qualite;niveau_potion
			ALIMENT;id_element_aliment;nom_type_aliment;nom_type_qualite;bbdf_aliment
			GRAINE;quantite_element_graine;nom_type_graine
			INGREDIENT;quantite_element_ingredient;nom_type_ingredient
			MINERAI_BRUT;quantite_brut_element_minerai;nom_type_minerai
			LINGOT;quantite_lingots_element_minerai;nom_type_minerai
			PLANTE_BRUTE;quantite_element_partieplante;nom_type_partieplante;nom_type_plante
			PLANTE_PREPAREE;quantite_preparee_element_partieplante;nom_type_partieplante;nom_type_plante
			RUNE;id_rune_element_rune
			TABAC;quantite_feuille_element_tabac;nom_court_type_tabac
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_laban_a', 'details_laban_b');">
			</div>
			<br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Contenu du coffre
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/coffre/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			Détails des lignes : similaire au script laban.
			<br><br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Contenu de la charrette
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/charrette/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			<div id='details_charrette_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_charrette_a','details_charrette_b');">
			</div>
				
			<div id='details_charrette_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_charrette_a', 'details_charrette_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			CHARRETTE;idCharrette;durabiliteMax;durabiliteActuelle;poidsTransportable;poidsTransporte
			ou : 
			AUCUNE_CHARRETTE
			
			Le restant des lignes est similaire au script Laban.
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_charrette_a', 'details_charrette_b');">
			</div>
			<br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Liste des équipement équipés par le Braldûn
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/equipements/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			Détails d'une ligne : EQUIPEMENT;idEquipement<br>
			ou :<br>
			AUCUN_EQUIPEMENT
			<br>
			Le détail des équipements est disponible dans les Données Publiques, fichier equipements.csv.
			<br><br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Liste des échoppes
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/echoppes/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			Détails d'une ligne si une échoppe est possédée: voir ci-dessous.<br>
			ou :<br>
			AUCUNE_ECHOPPE
			<br><br>
			
			<div id='details_echoppe_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_echoppe_a','details_echoppe_b');">
			</div>
				
			<div id='details_echoppe_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_echoppe_a', 'details_echoppe_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			ECHOPPE;idEchoppe;x;y;z;idMetier;idRegion
			ELEMENT;CAISSE;Castar;quantite_castar
			ELEMENT;CAISSE;Rondin;quantite_rondin
			ELEMENT;CAISSE;Peau;quantite_peau
			ELEMENT;ARRIERE;Rondin;quantite_rondin
			ELEMENT;ARRIERE;Peau;quantite_peau
			ELEMENT;ARRIERE;Cuir;quantite_cuir
			ELEMENT;ARRIERE;Fourrure;quantite_fourrure
			ELEMENT;ARRIERE;Planche;quantite_planche
			ALIMENT;id_element_aliment;nom_type_aliment;nom_type_qualite;bbdf_aliment;recette;type_vente;prix_1;prix_2;prix_3;unite_1;unite_2;unite_3;commentaire
			ALIMENT_PRIX_MINERAI;id_element_aliment;prix;nom_type_minerai
			ALIMENT_PRIX_PLANTE;id_element_aliment;prix;nom_type_plante;nom_type_partieplante;prefix_type_plante
			EQUIPEMENT;id_equipement;type_vente;prix_1;prix_2;prix_3;unite_1;unite_2;unite_3;commentaire
			EQUIPEMENT_PRIX_MINERAI;id_equipement;prix;nom_type_minerai
			EQUIPEMENT_PRIX_PLANTE;id_equipement;prix;nom_type_plante;nom_type_partieplante;prefix_type_plante
			MATERIEL;id_materiel;id_type_materiel;nom;capacite;durabilite;usure;poids;type_vente;prix_1;prix_2;prix_3;unite_1;unite_2;unite_3;commentaire
			MATERIEL_PRIX_MINERAI;id_materiel;prix;nom_type_minerai
			MATERIEL_PRIX_PLANTE;id_materiel;prix;nom_type_plante;nom_type_partieplante;prefix_type_plante
			POTION;id_potion;type;nom_type_potion;nom_type_qualite;niveau_potion;type_vente;prix_1;prix_2;prix_3;unite_1;unite_2;unite_3;commentaire
			POTION_PRIX_MINERAI;id_potion;prix;nom_type_minerai
			POTION_PRIX_PLANTE;id_potion;prix;nom_type_plante;nom_type_partieplante;prefix_type_plante
			PLANTE;id_type_partieplante;id_type_plante;quantite_caisse;quantite_arriere;quantite_preparee
			MINERAI;nom_type_minerai;id_type_minerai;quantite_brut_arriere;quantite_lingots;quantite_brut_caisse
			INGREDIENT;nom_type_ingredient;id_type_ingredient;quantite_arriere;quantite_caisse
			POTION;id_potion;type;nom_type_potion;nom_type_qualite;niveau_potion;
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_echoppe_a', 'details_echoppe_b');">
			</div>
			
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Liste des champs
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/champs/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			Détails d'une ligne : CHAMP;idChamp;x;y;z;idRegion<br>
			ou :<br>
			AUCUN_CHAMP
			<br><br><br>
			</td>
		</tr>
		<tr valign="top">
			<td  width="20%">
				<br>Liste des quêtes et étapes
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/quetes/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			
			<div id='details_quete_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_quete_a','details_quete_b');">
			</div>
				
			<div id='details_quete_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_quete_a', 'details_quete_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			QUETE;id_quete;date_creation_quete;;date_fin_quete;gain_quete;est_initiatique_quete
			ETAPE;id_quete;libelle_etape;date_debut_etape;date_fin_etape;est_terminee_etape;objectif_etape;ordre_etape
			ou : 
			AUCUNE_QUETE
			AUCUNE_ETAPE
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_quete_a', 'details_quete_b');">
			</div>
			<br>
			</td>
		</tr>
		
		<thead class="table_liste">
			<th colspan="2">Catégorie Scripts Appels : 6 appels par jour</th>
		</thead>
		<tr valign="top">
			<td  width="20%">
				<br>Appels
			</td>
			<td width="80%" style="text-align:left">
			Version : 1<br>
			URL : http://sp.braldahim.com/scripts/appels/?idBraldun=XXX&mdpRestreint=YYYY&version=1<br>
			<div id='details_appels_a' style="display:block" >
			  	<input type='button' class='button1' value='Afficher détails' onClick="javascript:switch2div('details_appels_a','details_appels_b');">
			</div>
				
			<div id='details_appels_b' style="display:none" >
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_appels_a', 'details_appels_b');">
			
			<pre style="background-color:#2a5911; text-align:left" >
			
			Exemple : 
			TYPE:appels;NB_APPELS:0;MAX_AUTORISE:6
			TYPE:dynamique;NB_DYNAMIQUE:0;MAX_AUTORISE:24
			TYPE:statique;NB_STATIQUE:0;MAX_AUTORISE:100
			</pre>
			<input type='button' class='button1' value='Cacher détails' onClick="javascript:switch2div('details_appels_a', 'details_appels_b');">
			</div>
			
			</td>
		</tr>
	</table>
	<br><br>
	
	<table style="width:90%" class="table_liste">
		
		<thead class="table_liste">
			<th colspan="2">Elements Communs</th>
		</thead>
		<tr>
			<td>
			La première ligne renvoyée indique soit une erreur, soit le nombre d'appels en cours.
			<br><br>
			
			Exemple nominal : 
			<pre style="background-color:#2a5911; text-align:left" >
			TYPE:dynamique;NB_APPELS:15;MAX_AUTORISE:24
			[..] (la suite des résultats sur les lignes suivantes)
			</pre>
			
			Exemple avec le code ERREUR-09 : 
			<pre style="background-color:#2a5911; text-align:left">
			ERREUR-09. Depassement Appels;TYPE:dynamique;NB_APPELS:26;MAX_AUTORISE:24 
			</pre>
			
			Exemple avec un autre code erreur : 
			<pre style="background-color:#2a5911; text-align:left">
			ERREUR-03. Braldûn inconnu
			</pre>
			
			</td>
		</tr>
	</table>
	
	<br><br>
	<table style="width:90%" class="table_liste">
		
		<thead class="table_liste">
			<th colspan="2">Code d'erreurs</th>
		</thead>
		<tr>
			<td>
			ERREUR-01. Erreur Technique, l'équipe est informée
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-02. Paramètres incorrects
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-03. Braldûn inconnu
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-04. Mot de passe invalide
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-05. Braldûn désactivé ou pnj
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-06. Service temporairement désactivé
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-07. Service inconnu
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-08. Version incorrecte
			</td>
		</tr>
		<tr>
			<td>
			ERREUR-09. Dépassement appels
			</td>
		</tr>
	</table>
	<br>
</ul>

<br>

<ul class="box_contenu textalia">
	<ul class="titre textalic textsizeb">
	Aide
	</ul>
		<br>
	<ul class="titre textalic textsized">
		Débuter
	</ul>
	<ul class="textalic">
 	Débuter en php : <a href='http://www.phpdebutant.org/'>http://www.phpdebutant.org/</a>, <a href='http://php.developpez.com/cours/'>http://php.developpez.com/cours/</a><br>
 	Pour les plus aguérris : <a href='http://www.z-f.fr/page/comment_debuter'>http://www.z-f.fr/page/comment_debuter</a>, <a href='http://g-rossolini.developpez.com/tutoriels/php/zend-framework/debuter/'>Article Zend Framework</a>
 	</ul>
 	
 	<br><br>
 	
 	<ul class="titre textalic textsized">
		Premier Exemple
	</ul>
	
	<pre style="background-color:#2a5911">
			
			/* lecture du fichier et stockage dans la chaîne de caractères "$buffer" */
			$fichier = "http://public.braldahim.com/bralduns.csv";
			$buffer = "";
			$fd = @fopen($fichier,"r");
			if ($fd) {
				while (!@feof($fd)) { $buffer .= @fgets($fd, 4096); }
				@fclose ($fd);
			
				/* premier découpage en tranches : les lignes sont séparées */
				$lignes = explode("\n", $buffer );
					
				/* chaque ligne est à nouveau découpée en tranches, par champs, et affichée */
				$i=0;
				while ($lignes[$i]) {
					$data = explode(";", $lignes[$i]);
					echo $data[0]." - ".$data[1]." - ". $data[2]." - ". $data[3]." - ". $data[4]." - ". $data[5]." - ". $data[6]."&lt;br&gt;";
					$i++;
				}
			} else { 
				echo "Le fichier "".$fichier."" est inaccessible : "; 
			}
		</pre>

			<ul class="titre textalic textsized">
				Exemple optimisé
			</ul>
			
			Remplacer :
			<pre style="background-color:#2a5911">
			while (!@feof($fd)){ $buffer .= @fgets($fd, 4096); }
			@fclose ($fd);
			$lignes = explode("\n", $buffer );
			</pre>
			par :
			<pre style="background-color:#2a5911">
			while (!@feof($fd)){ $lignes[] = @fgets($fd, 4096); }
			@fclose ($fd);
			</pre>
			<br>
			Remplacer :
			<pre style="background-color:#2a5911">
			echo $data[0]." - ".$data[1]." - ". $data[2]." - ". $data[3]." - ". $data[4]." - ". $data[5]." - ". $data[6]."&lt;br&gt;";
			</pre>
			par :
			<pre style="background-color:#2a5911">
			echo implode(" - ", $data );
			</pre>

			</pre>
	</ul>
	<br>
</ul>
<br>
