<ul class="box_contenu1 textalic">
	<ul class="titre textalic textsizea">
	Braldahim - Scripts Publics
	</ul>
	<br>
</ul>

<br>

<ul class="box_contenu1 textalic">
	<table style="width:100%">
	<tr>
		<td style="width:400px" valign="top">
			<img src="/public/images/description.jpg">
		</td>
		<td style="width:200px; border-left: 1px solid #791E1E;" valign="top">
		</td>
	</tr>
	</table>
	
	<p align="center"><a href="http://www.jeuxweb.org" target="_blank" class="AllLinks">Braldahim est un jeu géré par l'association sans but lucratif JeuxWeb.org </a><br>
		<a href="http://www.jeuxweb.org" target="_blank"><img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="JeuxWeb" border="0" height="60" width="468"></a>
	</p>
</ul>