<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Administration Carte</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    	
	    	<img border='0' src='image<?=$this->parametres?>' title='carte'>
	
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>