<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Carte</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    	
	    	<img border='0' src='image<?php echo $this->parametres?>' title='carte'>
	
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>