	
	<?php if ($this->nb_runes > 0) : ?>
		<?php include("poches/poche_rune.phtml") ?>
	<?php endif;?>
	<?php if (count($lot["materiels"]) > 0) : 
			$this->materiels = $lot["materiels"];
			$this->nb_materiels = count($lot["materiels"]);
		?>
		<?php include("poches/poche_materiel.phtml") ?>
	<?php endif;?>
	<?php if (count($lot["equipements"]) > 0) :
			$this->equipements = $lot["equipements"];
			$this->nb_equipements = count($lot["equipements"]);
		?>
		<?php include("poches/poche_equipement.phtml") ?>
	<?php endif;?>
	<?php if ($this->nb_munitions > 0) : ?>
		<?php include("poches/poche_munition.phtml") ?>
	<?php endif;?>
	<?php if (count($lot["potions"]) > 0) :
			$this->potions = $lot["potions"];
			$this->nb_potions = count($lot["potions"]);
		?>
		<?php include("poches/poche_potion.phtml") ?>
	<?php endif;?>
	<?php if (count($lot["aliments"]) > 0) : 
			$this->aliments = $lot["aliments"];
			$this->nb_aliments = count($lot["aliments"]);
		?>
		<?php include("poches/poche_aliment.phtml") ?>
	<?php endif;?>
	<?php if ($this->nb_graines > 0) : ?>
		<?php include("poches/poche_graine.phtml") ?>
	<?php endif;?>
	<?php if (count($this->tabac) > 0) : ?>
	<?php include("poches/poche_tabac.phtml") ?>
	<?php endif;?>
   	
   	
   	
   	
   	
   	
   	
   	
   	
   	
