
<input type='button' class='button1' value='Fermer Tout' onClick="$('fermer_poche<?=$this->pocheNomSysteme ?>').click();">
<input type='button' class='button1' value='Ouvrir Tout' onClick="$('ouvrir_poche<?=$this->pocheNomSysteme ?>').click();">
   
   
<?=$poches = null; ?>
<ul id="navigation" style="width:99%;text-align:left">
	
	<li id="poche<?=$this->pocheNomSysteme ?>Castars">
		<? $poches[] = "poche".$this->pocheNomSysteme."Castars-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Castars-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les castars
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Castars-body" style="display:none">
			<li>
				<? include("materiaux/castars.phtml") ?>
			</li>
		</ul>
	</li>
	
	<? if (count($this->tabHobbitMetiers) > 0) :?>
		<? foreach ($this->tabHobbitMetiers as $m) : ?>
			<? if ($m["nom_systeme"] == "bucheron" || $m["nom_systeme"] == "guerrier") { continue; }?>
			<li id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>">
				<? $poches[] = "poche".$this->pocheNomSysteme.$m["nom_systeme"]."-head" ?>
	      		<h3 id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>-head" class="head" onClick="maccordion(this);" />
					<?=$this->pocheNom ?> <?=$m["nom"]?>
				</h3>
				<ul id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>-body" style="display:none">
					<li>
						<? include("poches/poche_".$m["nom_systeme"].".phtml") ?>
					</li>
				</ul>
			</li>
		<? endforeach; ?>
	<? endif; ?>
	
	<? if (count($this->tabMetiers) > 0) :?>
		<? foreach ($this->tabMetiers as $m) : ?>
			<? if ($m["a_afficher"] == true) : ?>
				<? if ($m["nom_systeme"] == "bucheron" || $m["nom_systeme"] == "guerrier") { continue; }?>
				<li id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>">
					<? $poches[] = "poche".$this->pocheNomSysteme.$m["nom_systeme"]."-head" ?>
		      		<h3 id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>-head" class="head" onClick="maccordion(this);" />
						<?=$this->pocheNom ?>  mat&eacute;riaux 
						<? if ($m["nom_systeme"] == "mineur" || $m["nom_systeme"] == "chasseur" || $m["nom_systeme"] == "herboriste") : ?>
						r&eacute;colt&eacute;s
						<? else: ?>
						transform&eacute;s 
						<? endif; ?>
						par un <?=$m["nom"]?>
					</h3>
					<ul id="poche<?=$this->pocheNomSysteme ?><?=$m["nom_systeme"]?>-body" style="display:none">
						<li>
							<? include("poches/poche_".$m["nom_systeme"].".phtml") ?>
						</li>
					</ul>
				</li>
			<? endif; ?>
		<? endforeach; ?>
	<? endif; ?>
	
	<li id="poche<?=$this->pocheNomSysteme ?>Rune">
		<? $poches[] = "poche".$this->pocheNomSysteme."Rune-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Rune-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les runes
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Rune-body" style="display:none">
			<li>
				<? include("poches/poche_rune.phtml") ?>
			</li>
		</ul>
	</li>
	<li id="poche<?=$this->pocheNomSysteme ?>Equipement">
		<? $poches[] = "poche".$this->pocheNomSysteme."Equipement-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Equipement-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les pi&egrave;ces d'&eacute;quipements
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Equipement-body" style="display:none">
			<li>
				<? include("poches/poche_equipement.phtml") ?>
			</li>
		</ul>
	</li>
	<li id="poche<?=$this->pocheNomSysteme ?>Munition">
		<? $poches[] = "poche".$this->pocheNomSysteme."Munition-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Munition-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les munitions
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Munition-body" style="display:none">
			<li>
				<? include("poches/poche_munition.phtml") ?>
			</li>
		</ul>
	</li>
	<li id="poche<?=$this->pocheNomSysteme ?>Potion">
		<? $poches[] = "poche".$this->pocheNomSysteme."Potion-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Potion-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?>  pour les potions
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Potion-body" style="display:none">
			<li>
				<? include("poches/poche_potion.phtml") ?>
			</li>
		</ul>
	</li>
	<li id="poche<?=$this->pocheNomSysteme ?>Aliment">
		<? $poches[] = "poche".$this->pocheNomSysteme."Aliment-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Aliment-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les aliments
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Aliment-body" style="display:none">
			<li>
				<? include("poches/poche_aliment.phtml") ?>
			</li>
		</ul>
	</li>
	
	<? if ($this->afficheTabac) : ?>
	<li id="poche<?=$this->pocheNomSysteme ?>Tabac">
		<? $poches[] = "poche".$this->pocheNomSysteme."Tabac-head" ?>
      	<h3 id="poche<?=$this->pocheNomSysteme ?>Tabac-head" class="head" onClick="maccordion(this);" />
			<?=$this->pocheNom ?> pour les feuilles de tabac
		</h3>
		<ul id="poche<?=$this->pocheNomSysteme ?>Tabac-body" style="display:none">
			<li>
				<? include("poches/poche_tabac.phtml") ?>
			</li>
		</ul>
	</li>
	<? endif;?>
</ul>
<? 
$jsFermer = "";
$jsOuvrir = "";
foreach ($poches as $p) :
	$jsFermer .= "maccordion_fermer($('$p'));";
	$jsOuvrir .= "maccordion_ouvrir($('$p'));";
endforeach; ?>
   
<input type='button' class='button1' id="fermer_poche<?=$this->pocheNomSysteme ?>" name="fermer_poche<?=$this->pocheNomSysteme ?>" value='Fermer Tout' onClick="<?=$jsFermer ?>">
<input type='button' class='button1' id="ouvrir_poche<?=$this->pocheNomSysteme ?>" name="ouvrir_poche<?=$this->pocheNomSysteme ?>"  value='Ouvrir Tout' onClick="<?=$jsOuvrir ?>">
   	
