<ul class="box_contenu1 textalic">
	<ul class="titre textalic textsizeb">
	Marché aux Minerais
	</ul><br>
	
<div id="mygrid_container" style="width:770px;height:650px;background-color:#E7C57B; align:center"></div> 
<script>
	gridQString = '/marcheminerai/renderxml?uid='+(new Date()).valueOf();
	
	mygrid = new dhtmlXGridObject('mygrid_container');
	mygrid.setImagePath("/public/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygrid.setHeader("Comté,Date,,Minerai,Prix Vente Unitaire,Prix Reprise Unitaire,Stock Initial,Stock Restant");
	mygrid.setInitWidths("118,95,50,110,85,110,110,90,90");
	mygrid.setColAlign("left,center,center,center,right,right,right,right,right");
	mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setSkin("braldahim");
	mygrid.setColSorting("str,str,str,str,str,str,str,str");
	mygrid.init();
	mygrid.loadXML(gridQString);
	mygrid.setSortImgState(true,3,"des");
</script>

</ul>