
<table class="table_liste" style="width:100%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th><?php echo $nomEquipe?> : <?php echo $equipe["nom_equipe"]?>, <?php echo count($equipe["joueurs"])?> joueur<?php if (count($equipe["joueurs"]) > 1): echo 's'; endif;?><br />
		Plaquages Effectués : <?php echo $equipe["plaquages"]?><br />
		Plaquages Subis : <?php echo $equipe["plaques"]?><br />
		Cagnotte : <?php echo $equipe["px"]?> PX</th>
	  </tr>
	</thead>
	<tbody>
		<?php if ($equipe["joueurs"] != null && count($equipe["joueurs"]) > 0): ?>
		  	<?php 
		  	$i = 0; 
		  	foreach($equipe["joueurs"] as $j): ?>
		  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			  		<td class="table_liste" nowrap>
			  		<a onclick="javascript:ouvrirWin('<?php echo $this->config->url->game?>/voir/braldun/?braldun=<?php echo $j["id_braldun"]?>');" title="Cliquez pour voir le profil">
			  		<?php echo $j["prenom_braldun"]?> <?php echo $j["nom_braldun"]?> (<?php echo $j["id_braldun"]?>)
			  		</a>
			  		<?php if ($this->matchEnCours["date_debut_soule_match"] != null && $this->matchEnCours["date_fin_soule_match"] == null) :?>
			  		en <span title="Position X, Y" style="cursor:pointer"><?php echo $j["x_braldun"]?>, <?php echo $j["y_braldun"]?></span>.
			  		<?php endif;?>
			  		<?php if ($this->matchEnCours["date_debut_soule_match"] != null) : ?>
			  		Plaqué : <?php echo $j["nb_plaque_soule_equipe"]?> fois, Plaqueur : <?php echo $j["nb_braldun_plaquage_soule_equipe"]?> fois.
			  		<?php endif;?>
			  		<?php if ($this->matchEnCours["date_debut_soule_match"] != null && $this->matchEnCours["date_fin_soule_match"] == null) :?>
				  		<?php if ($j["est_ko_braldun"] == "oui") :?>
				  		Actuellement plaqué
				  		<?php endif;?>
			  		<?php endif;?>
			  		<img src='<?php echo $this->config->url->static?>/images/vue/puce_event.gif' title='Voir les événements' border='0' onclick="ouvrirEvenementsH('<?php echo $j["id_braldun"]?>');" style='cursor:pointer'/>
		  		</tr>
		  	<?php endforeach; ?>
		<?php else: ?>
		<tr><td>Aucun joueur</td></tr>
		<?php endif; ?>
  	</tbody>
</table>