<div style="height:350px;overflow: auto; min-height: 60px;">
<br />
	<table class="table_liste">
		<thead class="table_liste">
		  <tr class="table_liste">
		  	<th colspan="3">
		  		&Eacute;v&eacute;nements du match n&deg;<?php echo $this->matchEnCours["id_soule_match"]?>
		  	</th>
		  </tr>
		</thead>
		<tbody>
		<?php if ($this->evenements != null): ?>
		  <?php $i = 0; 
		  foreach($this->evenements as $e): ?>
		  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste"><?php echo $e["date_evenement"]?></td>
		  		<td class="table_liste"><?php echo str_replace("ouvrirWin('", "ouvrirWin('".$this->config->url->game, $e["details_evenement"]);?></td>
		  	</tr>
		  <?php endforeach; ?>
		<?php else: ?>
		   <tr class="table_liste">
		   	<td colspan="5">
		   		Aucun &eacute;v&eacute;nement
		   	</td>
		   </tr>
		<?php endif; ?>
	   </tbody>
	</table>
</div>