<?php echo $this->render('header.phtml'); ?>

<?php include('menu.phtml'); ?>
<div class="box_messagerie">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Archives</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <? if (!empty($this->message)): ?>
			<?=$this->message; ?><br><br>
		<? endif; ?>
	    <br>
	    <form name='myForm'>
 			<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 			<input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->config->messagerie->message->type->archive;?>'>
	    </form>
		<?php include('cadre.phtml'); ?>
		<br><br>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>