
<?php if ($this->information != null): ?>
	<br />
	<?php echo $this->information ?>
	<br />
<?php else: ?>
<br />
<form name="myForm" id="myForm">
	<input type='hidden' id='nb_valeurs-messagerie_contacts' name='nb_valeurs-messagerie_contacts' value='5'>
	<input type='hidden' name='valeur_1-messagerie_contacts' id='valeur_1-messagerie_contacts' value='editer' />
	<input type='hidden' name='valeur_2-messagerie_contacts' id='valeur_2-messagerie_contacts' value='' />
	<input type='hidden' name='valeur_3-messagerie_contacts' id='valeur_3-messagerie_contacts' value='' />
	<input type='hidden' name='valeur_4-messagerie_contacts' id='valeur_4-messagerie_contacts' value='' />
	<input type='hidden' name='valeur_5-messagerie_contacts' id='valeur_5-messagerie_contacts' value='' />
	
	<div class="titre textalic textsizec">Nom de la liste / du Contact</div> <br />
	Ne seront conserv&eacute;s que les chiffres et les 26 lettres de l'alphabet (minuscules et majuscules). 
	<br />
	S'il n'y a qu'un seul Braldûn dans les destinataires de la liste, le nom de la liste sera automatiquement créé tel que : "Prénom Nom" du Braldun.
	<br />
	<?php if(!empty($this->nomErreur)) :?>
		<div class="message_erreur" id="message_erreur"> 
		<?php foreach($this->nomErreur as $message) :?>
			<?php echo $this->escape($message);?><br />
		<?php endforeach; ?>
		</div>
	<?php endif; ?>
	<input type="text" name="nom_liste_contact" size='40' maxlength='40' id="nom_liste_contact" value="<?php echo $this->contactsListe["nom"] ?>">
	<br /><br />
	
	<div class="titre textalic textsizec">Description de la liste</div> <br />
	
	<?php if(!empty($this->descriptionErreur)) :?>
		<div class="message_erreur" id="message_erreur"> 
		<?php foreach($this->descriptionErreur as $message) :?>
			<?php echo $this->escape($message);?><br />
		<?php endforeach; ?>
		</div>
	<?php endif; ?>
	<input type="text" name="description_liste_contact" size='60' maxlength='200' id="description_liste_contact" value="<?php echo $this->contactsListe["description"] ?>">
	<br /><br />
	
	<?php if(!empty($this->destinatairesErreur)) :?>
		<div class="message_erreur" id="message_erreur"> 
		<?php foreach($this->destinatairesErreur as $message) :?>
			<?php echo $this->escape($message);?><br />
		<?php endforeach; ?>
		</div>
	<?php endif; ?>
	<div class="titre textalic textsizec">Destinataires (entrez le pr&eacute;nom)</div><br />
	Le ou les destinataires doivent s'&ecirc;tre d&eacute;j&agrave; connect&eacute;s au site au moins une fois.<br />
	Sinon, ils n'appara&icirc;tront pas dans le r&eacute;sultat de la recherche ci-dessous.<br />
	Vous pouvez faire une liste avec environ 20 bralduns destinataires maximum.<br />
	
	<div id='aff_valeur_3_dest'><?php echo $this->contactsListe["aff_js_destinataires"]?></div>
	<input type="hidden" name="valeur_3_dest" id="valeur_3_dest" value="<?php echo $this->contactsListe["destinataires"]?>" />
	<input type="text" name="recherche_valeur_3_dest" size='40' id="recherche_valeur_3_dest" value="Entrez un prénom" onFocus='this.value=""; activerRechercheBraldun("valeur_3_dest");' />
	<input type="hidden" name="recherche_valeur_3_dest_actif" id="recherche_valeur_3_dest_actif" value="0" />
	<div class="recherche" id="recherche_valeur_3_dest_update" ></div>
    <span id="indicateur_recherche_valeur_3_dest" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" alt="Recherche..." /></span>

<br /><br /><br />
	
	<?php $libelle = "Modifier"; if ($this->contactsListe["id"] == "-1"): $libelle = "Cr&eacute;er"; endif; ?>
	<input type="button" class='button1' name="<?php echo $libelle ?>" value="<?php echo $libelle ?>" onclick="
	Javascript:$('#valeur_1-messagerie_contacts').val('editer');
	$('#valeur_2-messagerie_contacts').val(<?php echo $this->contactsListe["id"] ?>);
	$('#valeur_3-messagerie_contacts').val($('#valeur_3_dest').val());
	$('#valeur_4-messagerie_contacts').val($('#nom_liste_contact').val());
	$('#valeur_5-messagerie_contacts').val($('#description_liste_contact').val());
	 _get_('/messagerie/doaction?caction=do_messagerie_contacts', 'messagerie_contacts');this.disabled=true;" />
	<input type="button" class='button1' name="Annuler" value="Annuler" onclick="Javascript:_get_('/messagerie/doaction?caction=do_messagerie_contacts&valeur_1=liste', 'messagerie_contacts');" /> 
</form>

<?php endif; ?>
