<br />
<div class="titre textalic textsized" >Contacts</div>
<br />

<table class="table_liste">
	<thead class="table_liste">
		<tr class="table_liste">
		<th>Nom</th>
		<th>Description</th>
		<th>Braldun(s) dans la liste</th>
		<th>Écrire</th>
		<th>&nbsp;</th>
	  	</tr>
	</thead>
	<tbody>
	<?php if (!empty($this->listesContacts)): ?>
		<?php $i = 0;
		   foreach($this->listesContacts as $listesContacts): ?>
		   		<?php $js="onclick=\"_get_('/messagerie/doaction?caction=do_messagerie_contacts&valeur_1=editer&valeur_2=".$listesContacts['id']."');\" style='cursor:pointer' title='Lire le message'"; ?>
	  			<tr class="table_liste<?php echo ($i % 2);$i++; ?>" valign="top">
	  				<td class="table_liste">
	  					<?php echo $listesContacts["nom"] ?>
					</td>
					<td class="table_liste">
					<?php echo $listesContacts["description"] ?>
					</td>
					<td class="table_liste">
					<?php echo $listesContacts["bralduns"]["aff_js_destinataires"];?>
					</td>
					<td>
						<label class='alabel' onclick="Javascript:ecrireMessageListeContact(<?php echo $listesContacts["id"] ?>)">Écrire à la liste
	  					<img src='<?php echo $this->config->url->static?>/images/uddeim/env.gif' title='Envoyer un message' alt='Ecrire' border='0' style='cursor:pointer'/></label>
					</td>
	  				<td class="table_liste">
						<img src="<?php echo $this->config->url->static?>/images/uddeim/edit.gif" alt="&Eacute;diter" title="&Eacute;diter" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_contacts&valeur_1=voir&valeur_2=<?php echo $listesContacts["id"];?>");' style="cursor:pointer"> <br />
						<img src="<?php echo $this->config->url->static?>/images/uddeim/trash.gif" alt="Supprimer" title="Supprimer" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_contacts&valeur_1=supprimer&valeur_2=<?php echo $listesContacts["id"];?>");' style="cursor:pointer">
					</td>
	  			</tr>
		  	<?php endforeach; ?>
		<?php else: ?>
   		<tr class="table_liste">
   			<td colspan="5">Aucune liste de contact</td>
   		</tr>
   		<?php endif; ?>
	</tbody>
</table>
<input type="button" class='button1' name="Nouvelle liste" value="Nouvelle liste / nouveau contact" onclick="_get_('/messagerie/doaction?caction=do_messagerie_contacts&valeur_1=nouveau');" /> 
<br />