<?php echo $this->render('header.phtml'); ?>

<?php include('menu.phtml'); ?>
<div class="box_messagerie">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Corbeille</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <? if (!empty($this->message)): ?>
			<?=$this->message; ?><br><br>
		<? endif; ?>
	    <br>
		<?php include('messages.phtml'); ?>
		<br><br>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>