<?php echo $this->render('header.phtml'); ?>
<div class="box_pamaretres">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Ma Messagerie</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br>
		TODO
		
		<br><br>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>