Bonjour,

Votre braldun <?=$this->mailBraldun["prenom_braldun"] ?> <?=$this->mailBraldun["nom_braldun"] ?> (<?=$this->mailBraldun["id_braldun"] ?>)
a reçu le message suivant:

- Debut Message -

<?=$this->mailMessage;?> 
 
- Fin Message -

Vous pouvez regler l'envoi des mails dans vos paramètres.
 
Pour vous connecter, rendez-vous ici :  <?=$this->mailUrlJeu ?>
 
Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : <?=$this->mailAdresseSupport ?> 
 
Bon jeu !

--
Les Maitres du jeu