Bonjour,<br /><br />

Votre hobbit <?=$this->hobbit["prenom_hobbit"] ?> <?=$this->hobbit["nom_hobbit"] ?> (<?=$this->hobbit["id_hobbit"] ?>)
a reçu le message suivant:<br><br>

- Debut Message -<br><br>

<?=$this->message?>

<br><br>
- Fin Message -

<br><br>
Vous pouvez regler l'envoi des mails dans vos paramètres.<br><br>

Pour vous connecter, rendez-vous ici : <br />
<a href="<?=$this->urlJeu ?>"><?=$this->urlJeu ?></a><br /><br />

Si vous rencontrer un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Les Maitres du jeu