Bonjour,<br /><br />

Votre braldun <?=$this->mailBraldun["prenom_braldun"] ?> <?=$this->mailBraldun["nom_braldun"] ?> (<?=$this->mailBraldun["id_braldun"] ?>)
a reçu le message suivant:<br><br>

- Debut Message -<br><br>

<?=nl2br($this->mailMessage);?> 

<br><br>
- Fin Message -

<br><br>
Vous pouvez regler l'envoi des mails dans vos paramètres.<br><br>

Pour vous connecter, rendez-vous ici : <br />
<a href="<?=$this->mailUrlJeu ?>"><?=$this->mailUrlJeu ?></a><br /><br />

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->mailAdresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Les Maitres du jeu