Bonjour,

Votre hobbit <?=$this->mailHobbit["prenom_hobbit"] ?> <?=$this->mailHobbit["nom_hobbit"] ?> (<?=$this->mailHobbit["id_hobbit"] ?>)
a reçu le message suivant:

- Debut Message -

<?=$this->mailMessage?> 
 
- Fin Message -

Vous pouvez regler l'envoi des mails dans vos paramètres.
 
Pour vous connecter, rendez-vous ici :  <?=$this->mailUrlJeu ?>
 
Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : <?=$this->mailAdresseSupport ?> 
 
Bon jeu !

--
Les Maitres du jeu