<div class="box_messagerie_menu">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Messagerie</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br>
		<a href="/messagerie/nouveau">Nouveau message</a>
		<br>
		<a href="/messagerie/reception">Boite r&eacute;ception</a>
		<br>
		<a href="/messagerie/envoyes">Messages envoy&eacute;s</a>
		<br>
		<a href="/messagerie/brouillons">Brouillons</a>
		<br>
		<a href="/messagerie/archives">Archives</a>
		<br>
		<a href="/messagerie/corbeille">Corbeille</a>
		<br>
		<br>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
