	<? if ($this->message != null) : ?>
		Destinataires : <?=$this->escape($this->message["destinataires"]);?>
	    <br>
		Copies : <?=$this->escape($this->message["copies"]);?>
	    <br>
	    Titre : <?=$this->escape($this->message["titre"]);?>
		<br>
	    <?=$this->message["contenu"];?>
	    
	    <br><br>
	    <input type='button' class='button1' value='R&eacute;pondre' onClick='javascript:_get_("/messagerie/AskAction?caction=do_messagerie_message&valeur_5=<?=$this->message["id_message"];?>&valeur_6=repondre");'>
	    <input type='button' class='button1' value='Archiver' onClick='javascript:_get_("/messagerie/AskAction?caction=do_messagerie_message&valeur_1=<?=$this->valeur_1?>&valeur_2=<?=$this->valeur_2?>&valeur_3=<?=$this->valeur_3?>&valeur_4=<?=$this->valeur_4?>&valeur_5=<?=$this->message["id_message"];?>&valeur_6=archiver");'>
	    <input type='button' class='button1' value='Supprimer' onClick='javascript:_get_("/messagerie/AskAction?caction=do_messagerie_message&valeur_5=<?=$this->message["id_message"];?>&valeur_6=supprimer");'>
	<? endif; ?>
