<? if ($this->information != null) :?>
	<br><br><?=$this->information ?><br>
	<?=$this->render("/commun/commun_quete_resultat.phtml") ?>
	<br/>
<? endif; ?>

<? if ($this->message != null) : ?>
	<br><br> 
	<table class="table_liste">
		<thead class="table_liste">
			<tr class="table_liste">
				<th>
				Message de <?=$this->message["expediteur"];?>&nbsp;
				&agrave; <?=$this->message["destinataire"];?>,&nbsp;
				le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y, H:i', $this->message["date"]);?>.
				<br>
				Tous les destinataires : <?=$this->message["destinataires"];?>
			</th>
		</tr>
	</thead>
		<tbody>
			<tr class="table_liste">
				<td class="table_liste">
					<?=Bral_Util_BBParser::bbcodeReplace($this->message["titre"]);?>
				</td>
			</tr>
		</tbody>
	</table>

    <br /><br />
    <input type='button' class='button1' value='R&eacute;pondre' onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondre&valeur_2=<?=$this->message["id_message"];?>");'>
    <input type='button' class='button1' value='R&eacute;pondre &agrave; tous' onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondretous&valeur_2=<?=$this->message["id_message"];?>");'>
	<input type='button' class='button1' value='Transf&eacute;rer' onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=transferer&valeur_2=<?=$this->message["id_message"];?>");'>
    <input type='button' class='button1' value='Supprimer' onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=<?=$this->message["id_message"];?>");'>
    <input type='button' class='button1' value='Archiver' onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiver&valeur_2=<?=$this->message["id_message"];?>");'>
<? endif; ?>
