<?php if ($this->information != null) :?>
	<br /><br /><?php echo $this->information ?><br />
	<?php echo $this->render("/commun/commun_quete_resultat.phtml") ?>
	<br/>
	<input type='button' class='button1' value="Terminer l'action et rafraîchir la liste" onclick='javascript:_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
<?php elseif ($this->estMobile):?>
	<input type='button' class='button1' value='Retour à la liste' onclick='javascript:_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
<?php endif; ?>

<?php if ($this->message != null) : ?>
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
			<tr class="table_liste">
				<th>
				Message de <?php echo $this->message["expediteur"];?>&nbsp;
				&agrave; <?php echo $this->message["destinataire"];?>,&nbsp;
				le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y, H:i', $this->message["date"]);?>.
				<br />
				Tous les destinataires : <?php echo $this->message["destinataires"];?>
			</th>
		</tr>
		<tr>
		<th>
		<hr>
			<?php if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
				<img src="<?php echo $this->config->static->url?>/images/uddeim/answer.gif" alt="Répondre" title="Répondre" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondre&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");' style="cursor:pointer">
				<img src="<?php echo $this->config->static->url?>/images/uddeim/answerall.gif" alt="Répondre à tous" title="Répondre à tous" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondretous&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");' style="cursor:pointer">
				<img src="<?php echo $this->config->static->url?>/images/uddeim/forward.gif" alt="Transf&eacute;rer" title="Transf&eacute;rer" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=transferer&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");' style="cursor:pointer">
			<?php endif;?>
			<?php if ($this->filtre != $this->config->messagerie->message->type->supprime && $this->filtre != $this->config->messagerie->message->type->envoye && $this->filtre != $this->config->messagerie->message->type->archive): ?>
				<img src="<?php echo $this->config->static->url?>/images/uddeim/trash.gif" alt="Effacer" title="Effacer" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");' style="cursor:pointer">
				<img src="<?php echo $this->config->static->url?>/images/uddeim/archive.gif" alt="Archiver" title="Archiver" onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiver&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");' style="cursor:pointer">
			<?php endif; ?>
		</th>
		</tr>
	</thead>
		<tbody>
			<tr class="table_liste">
				<td class="table_liste">
					<?php echo Bral_Util_BBParser::bbcodeReplace($this->message["titre"]);?>
				</td>
			</tr>
		</tbody>
	</table>

    <br /><br />
    <input type='button' class='button1' value='Annuler' onclick='javascript:_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
    <br />
    <input type='button' class='button1' value='R&eacute;pondre' onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondre&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
    <input type='button' class='button1' value='R&eacute;pondre &agrave; tous' onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=repondretous&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
	<input type='button' class='button1' value='Transf&eacute;rer' onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=transferer&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
	<?php if ($this->filtre != $this->config->messagerie->message->type->envoye && $this->filtre != $this->config->messagerie->message->type->supprime): ?>
    <input type='button' class='button1' value='Supprimer' onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
    <input type='button' class='button1' value='Archiver' onclick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiver&valeur_2=<?php echo $this->message["id_message"];?>&valeur_3=<?php echo $this->page?>&valeur_4=<?php echo $this->filtre?>");'>
    <?php endif;?>
<?php endif; ?>
