			
<? if (!empty($this->messages)): ?>
<?php foreach($this->messages as $message) :?>
	<ul class="message" onClick='_get_("/messagerie/DoAction?caction=do_messagerie_message&id=<?=$message["id_message"];?>");'>
	<span class="message date"><?=$message["date_envoi"];?></span>
	<span class="message titre_message"><?=$message["titre"];?></span>
	<span class="message destinataire"><?=$message["destinataires"];?></span>
	</ul>
<?php endforeach; ?>
<? else: ?>
	Aucun message
<? endif; ?>