<div class="titre textalic textsizec">
 R&eacute;partition des &eacute;choppes par Comt&eacute;
</div>
<br />
	
<?php if ($this->echoppes != null): ?>
   <?php foreach($this->echoppes as $k => $v) :?>
   	   <table class="table_liste">
	   <thead class="table_liste">
	   	<tr class="table_liste">
			<th colspan="3" ><?php echo $k?></th>
	  	</tr>
	  	<tr>
	  	<th>Type d'&eacute;choppe</th>
	  	<th>Nombre d'&eacute;choppes construites</th>
	  </tr>
	</thead>
  	<tbody>
  	<?php $i = 0; ?>
  	<?php foreach($v as $e) :?>
  		
	  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	  		<td class="table_liste" width="33%"><?php echo $e["nom_metier"]?></td>
	  		<td class="table_liste" width="33%"><?php echo $e["nombre"]?></td>
	  	</tr>
  	 <?php endforeach; ?>
  	  </tbody>
  	  </table>
  <?php endforeach; ?>
<?php else: ?>
   <tr class="table_liste">
   	<td colspan="5">
   		Aucun m&eacute;tier.
   	</td>
   </tr>
<?php endif; ?>
