<div class="titrea textalic titreasizec">R&eacute;partition des m&eacute;tiers par type</div>
<br />

<table class="table_liste">
	<thead class="table_liste">
	   <tr class="table_liste">
	  	<th>
	  		M&eacute;tier
	  	</th>
	  	<th>
	  		Nombre de Bralduns ayant appris ce m&eacute;tier
	  	</th>
	  </tr>
	</thead>
	<tbody>
	<?php if ($this->metiers != null): ?>
	  <?php $i = 0; 
	   foreach($this->metiers as $m) :?>
	  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	  		<td class="table_liste" width="50%"><?php echo $m["nom_metier"]?></td>
	  		<td class="table_liste" width="50%"><?php echo $m["nombre"]?></td>
	  	</tr>
	  <?php endforeach; ?>
	<?php else: ?>
	   <tr class="table_liste">
	   	<td colspan="5">
	   		Aucun m&eacute;tier.
	   	</td>
	   </tr>
	<?php endif; ?>
   </tbody>
</table>