
<div class="titre textalic textsizec">R&eacute;partition des m&eacute;tiers par type</div>
<br>

<table class="table_liste">
	<thead class="table_liste">
	   <tr class="table_liste">
	  	<th>
	  		M&eacute;tier
	  	</th>
	  	<th>
	  		Nombre de Bralduns ayant appris ce m&eacute;tier
	  	</th>
	  </tr>
	</thead>
	<tbody>
	<? if ($this->metiers != null): ?>
	  <? $i = 0; 
	   foreach($this->metiers as $m) :?>
	  	<tr class="table_liste<?=($i % 2);$i++; ?>">
	  		<td class="table_liste" width="50%"><?=$m["nom_metier"]?></td>
	  		<td class="table_liste" width="50%"><?=$m["nombre"]?></td>
	  	</tr>
	  <? endforeach; ?>
	<? else: ?>
	   <tr class="table_liste">
	   	<td colspan="5">
	   		Aucun m&eacute;tier.
	   	</td>
	   </tr>
	<? endif; ?>
   </tbody>
</table>