<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">&nbsp;</th>
			<th style="width:auto; padding:5px;">Castars</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;" valign="bottom">Quantit&eacute;</td>
			<td class="table_liste" valign="bottom">
			<?=$this->nb_castars ?> 
			<img src='<?=$this->config->static->url?>/styles/braldahim_defaut/images/elements/castars.png' alt='castars'/>
			</td>
		</tr>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;" valign="bottom">Poids</td>
			<td class="table_liste"  valign="bottom" style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_CASTARS?> Kg">
			<?=($this->nb_castars*Bral_Util_Poids::POIDS_CASTARS) ?> Kg
			</td>
		</tr>
	</tbody>
</table>