<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">&nbsp;</th>
			<th style="width:auto; padding:5px;">Cuir</th>
			<th style="width:auto; padding:5px;">Fourrure</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Quantit&eacute;</td>
			<td class="table_liste">
			<?=$this->nb_cuir ?>
			</td>
			<td class="table_liste">
			<?=$this->nb_fourrure ?>
			</td>
		</tr>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Poids</td>
			<td class="table_liste"  style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_CUIR?> Kg">
			<?=($this->nb_cuir*Bral_Util_Poids::POIDS_CUIR) ?> Kg
			</td>
			<td class="table_liste"  style="cursor:pointer" title="Poids unitaire : <?=Bral_Util_Poids::POIDS_FOURRURE?> Kg">
			<?=($this->nb_fourrure*Bral_Util_Poids::POIDS_FOURRURE) ?> Kg
			</td>
		</tr>
	</tbody>
</table>