<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">Cuir</th>
			<th style="width:auto; padding:5px;">Fourrure</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td class="table_liste">
			<?=$this->nb_cuir ?>
			</td>
			<td class="table_liste">
			<?=$this->nb_fourrure ?>
			</td>
		</tr>
	</tbody>
</table>