<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
		<tr class="table_liste">
			<th style="width:auto; padding:5px;">&nbsp;</th>
			<th style="width:auto; padding:5px;">Cuir</th>
			<th style="width:auto; padding:5px;">Fourrure</th>
		</tr>
	</thead>
	<tbody>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;" valign="bottom">Quantit&eacute;</td>
			<td class="table_liste" valign="bottom">
			<?php echo $this->nb_cuir ?>
			<img src='<?php echo $this->config->url->static?>/images/elements/cuir.png' alt='cuir'/>
			</td>
			<td class="table_liste" valign="bottom">
			<?php echo $this->nb_fourrure ?>
			<img src='<?php echo $this->config->url->static?>/images/elements/fourrure.png' alt='fourrure'/>
			</td>
		</tr>
		<tr class="table_liste">
			<td style="width:auto; padding:5px;">Poids</td>
			<td class="table_liste"  valign="bottom" style="cursor:pointer" title="Poids unitaire : <?php echo Bral_Util_Poids::POIDS_CUIR?> Kg">
			<?php echo ($this->nb_cuir*Bral_Util_Poids::POIDS_CUIR) ?> Kg
			</td>
			<td class="table_liste"  valign="bottom" style="cursor:pointer" title="Poids unitaire : <?php echo Bral_Util_Poids::POIDS_FOURRURE?> Kg">
			<?php echo ($this->nb_fourrure*Bral_Util_Poids::POIDS_FOURRURE) ?> Kg
			</td>
		</tr>
	</tbody>
</table>