<? if (count($this->aliments) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_aliments">
			<? $poches[] = "deposer_aliments-head" ?>
			<h3 id="deposer_aliments-head" class="head" onClick="maccordion(this);" />
				Aliments
			</h3>
			<ul id="deposer_aliments-body" style="display:none">
				<li>
					Choississez un aliment (ou plusieurs en appuyant sur ctrl) &agrave; d&eacute;poser.<br />
					<select multiple size="5" name="valeur_13" id="valeur_13" onChange="<?=$jsBtn?>">
						 <? foreach($this->aliments as $a) :?>
						 	<option value="<?=$a["id_aliment"]?>"><?=$a["nom"] ?> de qualit&eacute; <?=$a["qualite"] ?> (n&deg;<?=$a["id_aliment"] ?>), +<?=$a["bbdf"]?> %</option>
						 <? endforeach; ?>
					</select>
			  	</li>
			</ul>
		</li>
	</ul>
<? else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_13' id='valeur_13' value='0' >
	<input type='hidden' maxlength='4' size='4' name='valeur_13_max' id='valeur_13_max' value='0' >
<?endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_13_poids' id='valeur_13_poids' value='<?=Bral_Util_Poids::POIDS_RATION ?>' >