<?php if (count($this->aliments) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_aliments">
			<?php $poches[] = "deposer_aliments-head" ?>
			<h3 id="deposer_aliments-head" class="head" onclick="maccordion(this);">
				Aliments / Boissons
			</h3>
			<ul id="deposer_aliments-body" style="display:none">
				<li>
					Choississez un aliment (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_20" id="valeur_20" onchange="<?php echo $jsBtn?>">
						 <?php 
						 $poids = "";
						 foreach($this->aliments as $a) :?>
						 	<option value="<?php echo $a["id_aliment"]?>"><?php echo $a["nom"] ?> 
						 	<?php if ($a["bbdf"] > 0): ?>
						 		de qualit&eacute; <?php echo $a["qualite"] ?> 
						 	<?php endif;?> 
						 	(n&deg;<?php echo $a["id_aliment"] ?>) <?php if ($a["bbdf"] > 0): ?>, +<?php echo $a["bbdf"]?> %<?php endif;?></option>
						 	<?php $poids .= "<input type='hidden' name='valeur_20_poids_".$a["id_aliment"]."' id='valeur_20_poids_".$a["id_aliment"]."' value='".$a["poids"]."'>";?>
						 <?php endforeach; ?>
					</select>
					<?php echo $poids ?>
					<center><input type="button" class='button' value="Sélectionner tous les aliments" onclick="selectAll(20, 20 );"></input></center>
			  	</li>
			</ul>
		</li>
	</ul>
<?php else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_20' id='valeur_20' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_20_max' id='valeur_20_max' value='0' />
<?php endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_20_poids' id='valeur_20_poids' value='0' />
<input type='hidden' maxlength='4' size='4' name='valeur_20_echoppe' id='valeur_20_echoppe' value='non' />