<?if ($this->autres["nb_peau"] > 0  || $this->autres["nb_cuir"] > 0 || $this->autres["nb_castar"] ||
	  $this->autres["nb_fourrure"] > 0 || $this->autres["nb_planche"] > 0 || $this->autres["nb_viande"] ||
	  $this->autres["nb_viande_preparee"]) :?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_divers">
			<? $poches[] = "deposer_divers-head" ?>
			<h3 id="deposer_divers-head" class="head" onClick="maccordion(this);" />
				Divers
			</h3>
			<ul id="deposer_divers-body" style="display:none">
				<li>
				<? if ($this->autres["nb_castar"] > 0): ?>
					Castar : <?=$this->autres["nb_castar"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_castar"]?>) { alert('Valeur trop grande'); this.value=0};<?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_4_max' id='valeur_4_max' value='<?=$this->autres["nb_castar"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_4_max' id='valeur_4_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_4_poids' id='valeur_4_poids' value='<?=Bral_Util_Poids::POIDS_CASTARS ?>' >
				<? if ($this->autres["nb_peau"] > 0): ?>
					Peau : <?=$this->autres["nb_peau"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_peau"]?>) { alert('Valeur trop grande'); this.value=0};<?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_5_max' id='valeur_5_max' value='<?=$this->autres["nb_peau"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_5_max' id='valeur_5_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_5_poids' id='valeur_5_poids' value='<?=Bral_Util_Poids::POIDS_PEAU ?>' >
				<? if ($this->autres["nb_cuir"] > 0): ?>
					Cuir : <?=$this->autres["nb_cuir"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_cuir"]?>) { alert('Valeur trop grande'); this.value=0};<?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_6_max' id='valeur_6_max' value='<?=$this->autres["nb_cuir"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_6_max' id='valeur_6_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_6_poids' id='valeur_6_poids' value='<?=Bral_Util_Poids::POIDS_CUIR ?>' >
				<? if ($this->autres["nb_fourrure"] > 0): ?>
					Fourrure : <?=$this->autres["nb_fourrure"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_7' id='valeur_7' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_fourrure"]?>) { alert('Valeur trop grande'); this.value=0}; <?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_7_max' id='valeur_7_max' value='<?=$this->autres["nb_fourrure"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_7_max' id='valeur_7_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_7' id='valeur_7' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_7_poids' id='valeur_7_poids' value='<?=Bral_Util_Poids::POIDS_FOURRURE ?>' >
				<? if ($this->autres["nb_viande"] > 0): ?>
					Viande : <?=$this->autres["nb_viande"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_8' id='valeur_8' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_viande"]?>) { alert('Valeur trop grande'); this.value=0}; <?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_8_max' id='valeur_8_max' value='<?=$this->autres["nb_viande"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_8_max' id='valeur_8_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_8' id='valeur_8' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_8_poids' id='valeur_8_poids' value='<?=Bral_Util_Poids::POIDS_VIANDE ?>' >
				<? if ($this->autres["nb_viande_preparee"] > 0): ?>
					Viande pr&eacute;par&eacute;e : <?=$this->autres["nb_viande_preparee"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_9' id='valeur_9' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_viande_preparee"]?>) { alert('Valeur trop grande'); this.value=0}; <?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_9_max' id='valeur_9_max' value='<?=$this->autres["nb_viande_preparee"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_9_max' id='valeur_9_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_9' id='valeur_9' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_9_poids' id='valeur_9_poids' value='<?=Bral_Util_Poids::POIDS_VIANDE_PREPAREE ?>' >
				<? if ($this->autres["nb_planche"] > 0): ?>
					Planche : <?=$this->autres["nb_planche"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_10' id='valeur_10' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_planche"]?>) { alert('Valeur trop grande'); this.value=0}; <?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_10_max' id='valeur_10_max' value='<?=$this->autres["nb_planche"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_10_max' id='valeur_10_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_10' id='valeur_10' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_10_poids' id='valeur_10_poids' value='<?=Bral_Util_Poids::POIDS_PLANCHE ?>' >
				<? if ($this->autres["nb_rondin"] > 0): ?>
					Rondin : <?=$this->autres["nb_rondin"] ?>.
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_11' id='valeur_11' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->autres["nb_rondin"]?>) { alert('Valeur trop grande'); this.value=0}; <?=$jsBtn?>">
					<input type='hidden' maxlength='4' size='4' name='valeur_11_max' id='valeur_11_max' value='<?=$this->autres["nb_rondin"] ?>' >
					<br />
				<? else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_11_max' id='valeur_11_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_11' id='valeur_11' value='0' >
				<? endif; ?>
				<input type='hidden' maxlength='4' size='4' name='valeur_11_poids' id='valeur_11_poids' value='<?=Bral_Util_Poids::POIDS_RONDIN ?>' >
				</li>
			</ul>
		</li>
	</ul>
<? else : ?>
	<? for ($i=4 ; $i <= 11 ; $i++) : ?>
		<input type='hidden' maxlength='4' size='4' name='valeur_<?=$i?>_max' id='valeur_<?=$i?>_max' value='0' >
		<input type='hidden' maxlength='4' size='4' name='valeur_<?=$i?>_poids' id='valeur_<?=$i?>_poids' value='0' >
		<input type='hidden' maxlength='4' size='4' name='valeur_<?=$i?>' id='valeur_<?=$i?>' value='0' >
	<? endfor; ?>
<? endif; ?>