<?php if (count($this->equipements) > 0) : ?>
	 <ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_equipements">
			<?php $poches[] = "deposer_equipements-head" ?>
			<h3 id="deposer_equipements-head" class="head" onclick="maccordion(this);">
				Equipements
			</h3>
			<ul id="deposer_equipements-body" style="display:none">
				<li>
					<?php
					$option = "";
					$poids = "";
					foreach($this->equipements as $e) {
						 $option .= "<option value='".$e["id_equipement"]."'>n&deg;".$e["id_equipement"]." ".$e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"].", niveau ";
						 
						 if ($e["niveau"] == -1) {
						 	$option .= " spécial";
						 } else {
						 	$option .= $e["niveau"];
						 }
						 
						 $option .= ", poids ".$e["poids"]."kg</option>";
						 $poids .= "<input type='hidden' name='valeur_19_poids_".$e["id_equipement"]."' id='valeur_19_poids_".$e["id_equipement"]."' value='".$e["poids"]."'>";
					}
					?>
					Choississez un &eacute;quipement (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_19" id="valeur_19" onchange="<?php echo $jsBtn?>">
						<?php echo $option ?>
					</select>
					<?php echo $poids ?>
					<center><input type="button" class='button' value="S&eacute;lectionner tous les &eacute;quipements" onclick="selectAll(19, 19 );"></input></center>
			  	</li>
			</ul>
		</li>
	</ul>
<?php else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_19' id='valeur_19' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_19_max' id='valeur_19_max' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_19_poids' id='valeur_19_poids' value='0' />
<?php endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_19_echoppe' id='valeur_19_echoppe' value='non' />