<? if (count($this->equipements) > 0) : ?>
	 <ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_equipements">
			<? $poches[] = "deposer_equipements-head" ?>
			<h3 id="deposer_equipements-head" class="head" onClick="maccordion(this);" />
				Equipements
			</h3>
			<ul id="deposer_equipements-body" style="display:none">
				<li>
					Choississez un &eacute;quipement (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_12" id="valeur_12" onChange="<?=$jsBtn?>">
						 <? foreach($this->equipements as $e) :?>
						 	<option value="<?=$e["id_equipement"]?>">n&deg;<?=$e["id_equipement"] ?> <?=$e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?>, niveau <?=$e["niveau"] ?>, poids <?=$e["poids"] ?>kg</option>
						 <? endforeach; ?>
					</select>
					<? foreach($this->equipements as $e) :?>
						<input type="hidden" name="valeur_12_poids_<?=$e["id_equipement"] ?>" id="valeur_12_poids_<?=$e["id_equipement"] ?>" value="<?=$e["poids"]?>">
					<? endforeach; ?>
			  	</li>
			</ul>
		</li>
	</ul>
<? else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_12' id='valeur_12' value='0' >
	<input type='hidden' maxlength='4' size='4' name='valeur_12_max' id='valeur_12_max' value='0' >
	<input type='hidden' maxlength='4' size='4' name='valeur_12_poids' id='valeur_12_poids' value='0' >
<?endif; ?>