<?php if ($this->nb_graine > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_graines">
			<?php $poches[] = "deposer_graines-head" ?>
			<h3 id="deposer_graines-head" class="head" onclick="maccordion(this);">
				Poignées de graines
			</h3>
			<ul id="deposer_graines-body" style="display:none">
				<li>
				<table width='100%'>
				<tr>
					<td>
					<?php if ($this->nb_graine == 1):$s=''; else:$s='s';endif; ?>
					<?php echo $this->nb_graine?> poignée<?php echo $s?> de graine<?php echo $s?>
					</td>
					<td align="center">
					Quantit&eacute; &agrave; transbahuter :
					</td>
				</tr>
				<?php if (count($this->graines) > 0): ?>
					<?php $i = 1;
					foreach ($this->graines as $k => $m) :  
					?>
						<tr>
							<td>
							<?php echo htmlspecialchars($m["type"])?>  : <?php echo $m["quantite_graine"]?> poignée<?php if ($m["quantite_graine"] > 1) echo "s" ?>
							</td>
							<td align="center">
							<input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_graine"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?php echo $jsBtn?>" />
							<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $m["quantite_graine"]?>' />
							<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_poids' id='valeur_<?php echo $k?>_poids' value='<?php echo Bral_Util_Poids::POIDS_POIGNEE_GRAINES ?>' />
							<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_echoppe' id='valeur_<?php echo $k?>_echoppe' value='non' />
							</td>
						</tr>
						<?php
						$i++; 
					endforeach;
						 ?>
				</table> 
				<?php endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?php endif; ?>