<? if ($this->nb_ingredient > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_ingredients">
			<? $poches[] = "deposer_ingredients-head" ?>
			<h3 id="deposer_ingredients-head" class="head" onClick="maccordion(this);" />
				Ingredients
			</h3>
			<ul id="deposer_ingredients-body" style="display:none">
				<li>
				<? if (count($this->ingredients) > 0): ?>
				<table width='100%'>
					<? $i = 0;
					$enter = false;
					foreach ($this->ingredients as $k => $m) : 
						$enter = true;
						if ($i % 3 == 0) echo "<tr>"; 
					?>
						<td>
						<?=htmlspecialchars($m["type"])?>  : <?=$m["quantite_ingredient"]?>
						<br />
						Quantit&eacute; &agrave; transbahuter : <br>
						<input type='text' maxlength='4' size='4' name='valeur_<?=$k ?>' id='valeur_<?=$k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$m["quantite_ingredient"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?=$jsBtn?>" />
						<br>
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_max' id='valeur_<?=$k?>_max' value='<?=$m["quantite_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_poids' id='valeur_<?=$k?>_poids' value='<?=$m["poids_unitaire_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_echoppe' id='valeur_<?=$k?>_echoppe' value='non' />
						</td>
						<? if ($i % 3 == 2) echo "</tr>"; 
						    $i++; 
					endforeach;
					if ($enter == true && $i % 3 != 0) :
						echo "</tr>"; 
					endif;
						 ?>
				</table> 
				<? endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?endif; ?>