<?php if ($this->nb_ingredient > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_ingredients">
			<?php $poches[] = "deposer_ingredients-head" ?>
			<h3 id="deposer_ingredients-head" class="head" onclick="maccordion(this);">
				Ingr&eacute;dients
			</h3>
			<ul id="deposer_ingredients-body" style="display:none">
				<li>
				<table width='100%'>
				<tr>
					<td>
					<?php if ($this->nb_ingredient == 1):$s=''; else:$s='s';endif; ?>
					<?php echo $this->nb_ingredient?> ingr&eacute;dient<?php echo $s?>
					</td>
					<td align="center">
					Quantit&eacute; &agrave; transbahuter :
					</td>
				</tr>
				<?php
				if (count($this->ingredients) > 0):
					$i = 1;
					$nb = count($this->ingredients);
					foreach ($this->ingredients as $k => $m) :
						if ($i == 1) {
							$valmin = $k;
						}
						if ($i == $nb) {
							$valmax = $k;
						}
					?>
					<tr>
						<td>
						<?php echo htmlspecialchars($m["type"])?>  : <?php echo $m["quantite_ingredient"]?>
						</td>
						<td align="center">
						<input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_ingredient"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?php echo $jsBtn?>" />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $m["quantite_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_poids' id='valeur_<?php echo $k?>_poids' value='<?php echo $m["poids_unitaire_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_echoppe' id='valeur_<?php echo $k?>_echoppe' value='oui' />
						</td>
					</tr>
					<?php 
						$i++; 
					endforeach;
						 ?>
					<tr>
						<td colspan="3" align="center">
						<input type="button" class='button' value="S&eacute;lectionner tous les ingr&eacute;dients" onclick="selectAll(<?php echo $valmin;?>, <?php echo $valmax;?> );"></input>
						</td>
					</tr>
				</table> 
				<?php endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?php endif; ?>