<?php if ($this->nb_ingredient > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_ingredients">
			<?php $poches[] = "deposer_ingredients-head" ?>
			<h3 id="deposer_ingredients-head" class="head" onclick="maccordion(this);">
				Ingredients
			</h3>
			<ul id="deposer_ingredients-body" style="display:none">
				<li>
				<?php if (count($this->ingredients) > 0): ?>
				<table width='100%'>
					<?php $i = 0;
					$enter = false;
					foreach ($this->ingredients as $k => $m) : 
						$enter = true;
						if ($i % 3 == 0) echo "<tr>"; 
					?>
						<td>
						<?php echo htmlspecialchars($m["type"])?>  : <?php echo $m["quantite_ingredient"]?>
						<br />
						Quantit&eacute; &agrave; transbahuter : <br />
						<input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_ingredient"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?php echo $jsBtn?>" />
						<br />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $m["quantite_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_poids' id='valeur_<?php echo $k?>_poids' value='<?php echo $m["poids_unitaire_ingredient"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_echoppe' id='valeur_<?php echo $k?>_echoppe' value='oui' />
						</td>
						<?php if ($i % 3 == 2) echo "</tr>"; 
						    $i++; 
					endforeach;
					if ($enter == true && $i % 3 != 0) :
						echo "</tr>"; 
					endif;
						 ?>
				</table> 
				<?php endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?php endif; ?>