<? if ($this->nb_minerai_brut > 0 || $this->nb_minerai_lingot > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_minerais">
			<? $poches[] = "deposer_minerais-head" ?>
			<h3 id="deposer_minerais-head" class="head" onClick="maccordion(this);" />
				Minerais bruts / Lingots
			</h3>
			<ul id="deposer_minerais-body" style="display:none">
				<li>
				<? if ($this->nb_minerai_brut == 1):$s=''; else:$s='s';endif; ?>
				<?=$this->nb_minerai_brut?> minerai<?=$s?> brut<?=$s?>
				 et 
				<? if ($this->nb_minerai_lingot == 1):$s=''; else:$s='s';endif; ?>
				<?=$this->nb_minerai_lingot?> lingot<?=$s?>. <br /> 
				
				<? if (count($this->minerais) > 0): ?>
				<table width='100%'>
					<? $i = 0;
					$enter = false;
					foreach ($this->minerais as $k => $m) : 
						$enter = true;
						if ($i % 3 == 0) echo "<tr>"; 
					?>
						<td>
						<?=htmlspecialchars($m["type"])?> - brut<? if ($m["quantite_brut_minerai"] > 0) echo "s" ?> : <?=$m["quantite_brut_minerai"]?>, lingot<? if ($m["quantite_lingots_minerai"] > 0) echo "s" ?> : <?=$m["quantite_lingots_minerai"]?>
						<br />
						Quantit&eacute; &agrave; transbahuter : <br>
						Brut : <input type='text' maxlength='4' size='4' name='valeur_<?=$k ?>' id='valeur_<?=$k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$m["quantite_brut_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?=$jsBtn?>" />
						<br>
						Lingot : <input type='text' maxlength='4' size='4' name='valeur_<?=($k+1) ?>' id='valeur_<?=($k+1) ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$m["quantite_lingots_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?=$jsBtn?>" />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_max' id='valeur_<?=$k?>_max' value='<?=$m["quantite_brut_minerai"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_poids' id='valeur_<?=$k?>_poids' value='<?=Bral_Util_Poids::POIDS_MINERAI ?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_echoppe' id='valeur_<?=$k?>_echoppe' value='oui' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=($k+1)?>_max' id='valeur_<?=($k+1)?>_max' value='<?=$m["quantite_lingots_minerai"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=($k+1)?>_poids' id='valeur_<?=($k+1)?>_poids' value='<?=Bral_Util_Poids::POIDS_LINGOT ?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?=($k+1)?>_echoppe' id='valeur_<?=($k+1)?>_echoppe' value='oui' />
						</td>
						<? if ($i % 3 == 2) echo "</tr>"; 
						    $i++; 
					endforeach;
					if ($enter == true && $i % 3 != 0) :
						echo "</tr>"; 
					endif;
						 ?>
				</table> 
				<? endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?endif; ?>