<?php if ($this->nb_minerai_brut > 0 || $this->nb_minerai_lingot > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_minerais">
			<?php $poches[] = "deposer_minerais-head" ?>
			<h3 id="deposer_minerais-head" class="head" onclick="maccordion(this);">
				Minerais bruts / Lingots
			</h3>
			<ul id="deposer_minerais-body" style="display:none">
				<li>
				<?php if ($this->nb_minerai_brut == 1):$s=''; else:$s='s';endif; ?>
				<?php echo $this->nb_minerai_brut?> minerai<?php echo $s?> brut<?php echo $s?>
				 et 
				<?php if ($this->nb_minerai_lingot == 1):$s=''; else:$s='s';endif; ?>
				<?php echo $this->nb_minerai_lingot?> lingot<?php echo $s?>. <br /> 
				
				<?php if (count($this->minerais) > 0): ?>
				<table width='100%'>
					<?php $i = 0;
					$enter = false;
					foreach ($this->minerais as $k => $m) : 
						$enter = true;
						if ($i % 3 == 0) echo "<tr>"; 
					?>
						<td>
						<?php echo htmlspecialchars($m["type"])?> - brut<?php if ($m["quantite_brut_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_brut_minerai"]?>, lingot<?php if ($m["quantite_lingots_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_lingots_minerai"]?>
						<br />
						Quantit&eacute; &agrave; transbahuter : <br />
						Brut : <input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_brut_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?php echo $jsBtn?>" />
						<br />
						Lingot : <input type='text' maxlength='4' size='4' name='valeur_<?php echo ($k+1) ?>' id='valeur_<?php echo ($k+1) ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_lingots_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; <?php echo $jsBtn?>" />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $m["quantite_brut_minerai"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_poids' id='valeur_<?php echo $k?>_poids' value='<?php echo Bral_Util_Poids::POIDS_MINERAI ?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_echoppe' id='valeur_<?php echo $k?>_echoppe' value='oui' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>_max' id='valeur_<?php echo ($k+1)?>_max' value='<?php echo $m["quantite_lingots_minerai"]?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>_poids' id='valeur_<?php echo ($k+1)?>_poids' value='<?php echo Bral_Util_Poids::POIDS_LINGOT ?>' />
						<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>_echoppe' id='valeur_<?php echo ($k+1)?>_echoppe' value='oui' />
						</td>
						<?php if ($i % 3 == 2) echo "</tr>"; 
						    $i++; 
					endforeach;
					if ($enter == true && $i % 3 != 0) :
						echo "</tr>"; 
					endif;
						 ?>
				</table> 
				<?php endif;?>
			  	</li>
			</ul>
		</li>
	</ul>
<?php endif; ?>