<?php if (count($this->potions) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_potions">
			<?php $poches[] = "deposer_potions-head" ?>
			<h3 id="deposer_potions-head" class="head" onclick="maccordion(this);">
				Potions / Vernis
			</h3>
			<ul id="deposer_potions-body" style="display:none">
				<li>
					Choississez une potion ou un vernis (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_22" id="valeur_22" onchange="<?php echo $jsBtn?>">
						 <?php foreach($this->potions as $p) :?>
						 	<option value="<?php echo $p["id_potion"]?>"><?php echo $p["nom_type"] ?> <?php echo $p["nom"] ?> de qualit&eacute; <?php echo $p["qualite"] ?> (n&deg;<?php echo $p["id_potion"] ?>, niv:<?php echo $p["niveau"]?>) </option>
						 <?php endforeach; ?>
					</select>	
				</li>
			</ul>
		</li>
	</ul>
<?php else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_22' id='valeur_22' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_22_max' id='valeur_22_max' value='0' />
<?php endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_22_poids' id='valeur_22_poids' value='<?php echo Bral_Util_Poids::POIDS_POTION ?>' />
<input type='hidden' maxlength='4' size='4' name='valeur_22_echoppe' id='valeur_22_echoppe' value='<?php if ($this->idEchoppe != null) : echo "oui"; else : echo "non"; endif;?>' />