<? if (count($this->potions) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_potions">
			<? $poches[] = "deposer_potions-head" ?>
			<h3 id="deposer_potions-head" class="head" onclick="maccordion(this);">
				Potions / Vernis
			</h3>
			<ul id="deposer_potions-body" style="display:none">
				<li>
					Choississez une potion ou un vernis (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_15" id="valeur_15" onChange="<?=$jsBtn?>">
						 <? foreach($this->potions as $p) :?>
						 	<option value="<?=$p["id_potion"]?>"><?=$p["nom_type"] ?> <?=$p["nom"] ?> de qualit&eacute; <?=$p["qualite"] ?> (n&deg;<?=$p["id_potion"] ?>, niv:<?=$p["niveau"]?>) </option>
						 <? endforeach; ?>
					</select>	
				</li>
			</ul>
		</li>
	</ul>
<? else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_15' id='valeur_15' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_15_max' id='valeur_15_max' value='0' />
<?endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_15_poids' id='valeur_15_poids' value='<?=Bral_Util_Poids::POIDS_POTION ?>' />
<input type='hidden' maxlength='4' size='4' name='valeur_15_echoppe' id='valeur_15_echoppe' value='<? if ($this->idEchoppe != null) : echo "oui"; else : echo "non"; endif;?>' />