<?php if (count($this->runes) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_runes">
			<?php $poches[] = "deposer_runes-head" ?>
			<h3 id="deposer_runes-head" class="head" onclick="maccordion(this);">
				Runes
			</h3>
			<ul id="deposer_runes-body" style="display:none">
				<li>
					Choississez une rune (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_21" id="valeur_21" onchange="<?php echo $jsBtn?>">
						 <?php foreach($this->runes as $r) :?>
						 	<option value="<?php echo $r["id_rune"]?>">Rune n&deg;<?php echo $r["id_rune"] ?>, 
						 	<?php if ($r["est_identifiee"] == "oui") : ?>
						 		<?php echo $r["type"] ?>
						 	<?php else: ?>
						 		rune non identifi&eacute;e
						 	<?php endif; ?>
						 	<?php echo $r["info"]?>
						 	</option>
						 <?php endforeach; ?>
					</select>
					<center><input type="button" class='button1' value="Sélectionner toutes les runes" onclick="selectAll(21, 21 );"></input></center>
				</li>
			</ul>
		</li>
	</ul>
<?php else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_21' id='valeur_21' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_21_max' id='valeur_21_max' value='0' />
<?php endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_21_poids' id='valeur_21_poids' value='<?php echo Bral_Util_Poids::POIDS_RUNE ?>' >
<input type='hidden' maxlength='4' size='4' name='valeur_21_echoppe' id='valeur_21_echoppe' value='non' >