<? if (count($this->runes) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_runes">
			<? $poches[] = "deposer_runes-head" ?>
			<h3 id="deposer_runes-head" class="head" onClick="maccordion(this);">
				Runes
			</h3>
			<ul id="deposer_runes-body" style="display:none">
				<li>
					Choississez une rune (ou plusieurs en appuyant sur ctrl) &agrave; transbahuter.<br />
					<select multiple size="5" name="valeur_14" id="valeur_14" onChange="<?=$jsBtn?>">
						 <? foreach($this->runes as $r) :?>
						 	<option value="<?=$r["id_rune"]?>">Rune n&deg;<?=$r["id_rune"] ?>, 
						 	<? if ($r["est_identifiee"] == "oui") : ?>
						 		<?=$r["type"] ?>
						 	<? else: ?>
						 		rune non identifi&eacute;e
						 	<? endif; ?>
						 	</option>
						 <? endforeach; ?>
					</select>
				</li>
			</ul>
		</li>
	</ul>
<? else : ?>
	<input type='hidden' maxlength='4' size='4' name='valeur_14' id='valeur_14' value='0' />
	<input type='hidden' maxlength='4' size='4' name='valeur_14_max' id='valeur_14_max' value='0' />
<?endif; ?>
<input type='hidden' maxlength='4' size='4' name='valeur_14_poids' id='valeur_14_poids' value='<?=Bral_Util_Poids::POIDS_RUNE ?>' >
<input type='hidden' maxlength='4' size='4' name='valeur_14_echoppe' id='valeur_14_echoppe' value='non' >