<?php if (count($this->tabacs) > 0) : ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_tabacs">
			<?php $poches[] = "deposer_tabacs-head" ?>
			<h3 id="deposer_tabacs-head" class="head" onclick="maccordion(this);">
				Tabac
			</h3>
			<ul id="deposer_tabacs-body" style="display:none">
				<li>
				<?php foreach($this->tabacs as $k => $t) :?>
					<?php echo $t["type"]?> : <?php echo $t["quantite"]?>
					Quantit&eacute; &agrave; transbahuter : 
					<input type='text' maxlength='4' size='4' name='valeur_<?php echo $k?>' id='valeur_<?php echo $k?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $t["quantite"] ?>) { alert('Valeur trop grande'); this.value=0}; <?php echo $jsBtn?>"/>
					<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $t["quantite"]?>' />
					<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_poids' id='valeur_<?php echo $k?>_poids' value='<?php echo Bral_Util_Poids::POIDS_TABAC ?>' />
					<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_echoppe' id='valeur_<?php echo $k?>_echoppe' value='non' />
					<br />
				<?php endforeach; ?>
			  	</li>
			</ul>
		</li>
	</ul>
<?php endif; ?>