<br />Votre Prix : 
<input type='text' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='' onkeypress="chiffres(event, false);">
<input type='hidden' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='<?php echo TypeUnite::ID_TYPE_CASTARS?>'>Castars
 
<input type='hidden' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='1'>
<input type='hidden' maxlength='4' size='4' name='valeur_7' id='valeur_7' value='1'>
<input type='hidden' maxlength='4' size='4' name='valeur_8' id='valeur_8' value='1'>
<input type='hidden' maxlength='4' size='4' name='valeur_9' id='valeur_9' value='1'>
<br /><br />

<div class="titre textalic textsized" > Commentaire de mise en vente </div>
<br />
<?php echo Bral_Helper_BBBoutons::affiche('valeur_commentaire', 300)?>
<input type='hidden' id='valeur_10' name='valeur_10' value='' />
<input style="background-color: #31401A;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="300" type="text"> Caract&egrave;res restants<br />
<textarea name="valeur_commentaire" id="valeur_commentaire" class="inputbox" rows="10" cols="60" onkeydown="textCount($('#valeur_commentaire'),$('#characterstyped'),300);" onkeyup="textCount($('#valeur_commentaire'),$('#characterstyped'),300);"><?php echo $this->commentaire?></textarea>
