
<? if ($this->nbEquipementsArriereBoutique > 0): ?>
	<? foreach($this->equipementsArriereBoutique as $e) :?>
		<?=htmlentities($e["nom"]) ?> : qualit&eacute; <?=htmlentities($e["qualite"]) ?>,
		 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?><br>
	<? endforeach; ?>
	<br>
	
	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="Mettre en vente un &eacute;quipement"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendre&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="Transf&eacute;rer un &eacute;quipement"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transfererequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucun &eacute;quipement en r&eacute;serve
<? endif; ?>