	<? if ($this->nb_arriereMinerai == 0 && $this->nb_lingotsMinerai == 0 &&
		   $this->nb_arrierePartiePlantes == 0 && $this->nb_prepareePartiePlantes == 0 &&
		   $this->echoppe["quantite_cuir_arriere_echoppe"] == 0 &&
		   $this->echoppe["quantite_fourrure_arriere_echoppe"] == 0 &&
		   $this->echoppe["quantite_rondin_arriere_echoppe"] == 0 &&
		   $this->echoppe["quantite_peau_arriere_echoppe"] == 0 ) : ?>
		Votre arri&egrave;re-boutique est vide<br>
	<? endif; ?>
	
	<? if ($this->echoppe["quantite_rondin_arriere_echoppe"] > 1) $s = "s" ; else $s = "";?>
	Rondin<?=$s ?> : <?=$this->echoppe["quantite_rondin_arriere_echoppe"] ?>,
	Peau : <?=$this->echoppe["quantite_peau_arriere_echoppe"] ?><br>
	
	Cuir : <?=$this->echoppe["quantite_cuir_arriere_echoppe"] ?>, 
	Fourrure : <?=$this->echoppe["quantite_fourrure_arriere_echoppe"] ?>,
	
	<? if ($this->echoppe["quantite_planche_arriere_echoppe"] > 1) $s = "s" ; else $s = "";?>
	Planche<?=$s ?> : <?=$this->echoppe["quantite_planche_arriere_echoppe"] ?><br>
	
   <? if ($this->nb_arrierePartiePlantes == 0) : ?>
   	Aucune plante brute<br>
   <? else: ?>
    <? if ($this->nb_arrierePartiePlantes<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_arrierePartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plante<?=$s?>  brute<?=$s?>: <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->partieplantes as $p) : 
      	if ($p["quantite_arriere"] > 0) :
      		$enter = true;
	    	if ($i % 3 == 0) echo "<tr>"; 
	    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br>"; 
	    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br>"; 
	    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite_arriere"])."<br>";
	    	?>
	    	<td onmouseover="return overlib('<?=$textPlante?>',CAPTION,'<?=htmlentities($p["nom_plante"])?> : <?=htmlentities($p["nom_type"])?> - D&eacute;tails');"
	      		onclick="return overlib('<?=$textPlante?>', STICKY, CAPTION, 'Plante <?=htmlentities($p["nom_type"])?> - D&eacute;tails', CLOSECLICK, EXCLUSIVE);"
	      		onmouseout="return nd();">
	    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite_arriere"]?> <?=htmlentities($p["nom_type"])?><? if ($p["quantite_arriere"] > 1) echo "s"; ?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table>
   <? endif; ?>
   
   <? if ($this->nb_prepareePartiePlantes == 0) : ?>
   	Aucune plante pr&eacute;par&eacute;e<br>
   <? else: ?>
    <? if ($this->nb_prepareePartiePlantes<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_prepareePartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plante<?=$s?>  pr&eacute;par&eacute;e<?=$s?>: <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->partieplantes as $p) : 
      	if ($p["quantite_preparee"] > 0) :
      		$enter = true;
	    	if ($i % 3 == 0) echo "<tr>"; 
	    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br>"; 
	    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br>"; 
	    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite_preparee"])."<br>";
	    	?>
	    	<td onmouseover="return overlib('<?=$textPlante?>',CAPTION,'<?=htmlentities($p["nom_plante"])?> <?=htmlentities($p["nom_type"])?> - D&eacute;tails');"
	      		onclick="return overlib('<?=$textPlante?>', STICKY, CAPTION, 'Plante <?=htmlentities($p["nom_type"])?> - D&eacute;tails', CLOSECLICK, EXCLUSIVE);"
	      		onmouseout="return nd();">
	    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite_preparee"]?> <?=htmlentities($p["nom_type"])?><? if ($p["quantite_preparee"]>1) echo "s"; ?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table>
   <? endif; ?>
   
   <? if ($this->nb_arriereMinerai == 0) : ?>
   	Aucun minerai brut<br>
   <? else: ?>
   
    <? if ($this->nb_arriereMinerai<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_arriereMinerai?> minerai<?=$s?> brut<?=$s?>: <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->minerais as $m) : 
      	if ($m["quantite_arriere"] > 0) :
      		$enter = true;
	     	if ($i % 3 == 0) echo "<tr>"; 
	    	?>
	    	<td>
	    		<?=htmlentities($m["type"])?> : Quantit&eacute; : <?=$m["quantite_arriere"]?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table> 
    <? endif; ?>
    
   <? if ($this->nb_lingotsMinerai == 0) : ?>
   	Aucun lingot<br>
   <? else: ?>
    <? if ($this->nb_lingotsMinerai<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_lingotsMinerai?> lingot<?=$s?> : <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->minerais as $m) : 
      	if ($m["quantite_lingots"] > 0) :
      		$enter = true;
	     	if ($i % 3 == 0) echo "<tr>"; 
	    	?>
	    	<td>
	    		<?=htmlentities($m["type"])?> : Quantit&eacute; : <?=$m["quantite_lingots"]?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table> 
    <? endif; ?>
    
    <? if ($this->estSurEchoppe === true): 
  		$disabled = "";
  	?>
  	<? else: 
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave; aux actions...<br>
  	<? endif; ?>
    
    
    <input type="button" class='button1' value="Retirer des mati&egrave;res premi&egrave;res"
       	   onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirerressources&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')"  <?=$disabled ?>/>
       		<br>  
    <input type="button" class='button1' value="D&eacute;poser des mati&egrave;res premi&egrave;res"
       	   onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_deposerressources&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')"  <?=$disabled ?> />
    
    