
<? if ($this->nbPotionsArriereBoutique > 0): ?>
	<? foreach($this->potionsArriereBoutique as $p) :?>
		<?=htmlentities($p["nom"]) ?> : qualit&eacute; <?=htmlentities($p["qualite"]) ?>,
		 niveau: <?=$p["niveau"] ?><br>
	<? endforeach; ?>
	<br>
	
	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="Mettre en vente une potion"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendre&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="Transf&eacute;rer une potion"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transfererpotion&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucune potion en r&eacute;serve
<? endif; ?>
<br>