	<? if ($this->nb_caisseMinerai == 0 && $this->nb_caissePartiePlantes == 0 && 
		$this->echoppe["quantite_castar_caisse_echoppe"] == 0 &&
		$this->echoppe["quantite_rondin_caisse_echoppe"] == 0 &&
		$this->echoppe["quantite_peau_caisse_echoppe"] == 0) : ?>
		Votre caisse est vide<br>
	<? endif; ?>
	
	Castars : <?=$this->echoppe["quantite_castar_caisse_echoppe"] ?>, 
	Rondins : <?=$this->echoppe["quantite_rondin_caisse_echoppe"] ?>,
	Peau : <?=$this->echoppe["quantite_peau_caisse_echoppe"] ?><br>

   <? if ($this->nb_caissePartiePlantes == 0) : ?>
   	Aucune plante brute<br>
   <? else: ?>
    <? if ($this->nb_caissePartiePlantes<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_caissePartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plante<?=$s?>  brute<?=$s?>: <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->partieplantes as $p) : 
      	if ($p["quantite_caisse"] > 0) :
      		$enter = true;
	    	if ($i % 3 == 0) echo "<tr>"; 
	    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br>"; 
	    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br>"; 
	    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite_caisse"])."<br>";
	    	?>
	    	<td onmouseover="return overlib('<?=$textPlante?>',CAPTION,'<?=htmlentities($p["nom_type"])?> - D&eacute;tails');"
	      		onclick="return overlib('<?=$textPlante?>', STICKY, CAPTION, 'Plante <?=htmlentities($p["nom_type"])?> - D&eacute;tails', CLOSECLICK, EXCLUSIVE);"
	      		onmouseout="return nd();">
	    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite_caisse"]?> <?=htmlentities($p["nom_type"])?><? if ($p["quantite_caisse"] > 1) echo "s" ?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table>
   <? endif; ?>
   
   <? if ($this->nb_caisseMinerai == 0) : ?>
   	Aucun minerai<br>
   <? else: ?>
    <? if ($this->nb_caisseMinerai<=1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_caisseMinerai?> minerai<?=$s?> brut<?=$s?>: <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->minerais as $m) : 
      	if ($m["quantite_caisse"] > 0) :
      		$enter = true;
	     	if ($i % 3 == 0) echo "<tr>"; 
	    	?>
	    	<td>
	    		<?=htmlentities($m["type"])?> : Quantit&eacute; : <?=$m["quantite_caisse"]?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table> 
    <? endif; ?>
    
    <? if ($this->estSurEchoppe === true): 
  		$disabled = "";
  	?>
  	<? else: 
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave; aux actions...<br>
  	<? endif; ?>
  	
    <input type="button" class='button1' value="Retirer des &eacute;l&eacute;ments"
       	   onClick="Javascript:_get_('/echoppes/DoAction?caction=ask_echoppes_retirercaisse&valeur_1=<?=$this->echoppe["id_echoppe"] ?>') "  <?=$disabled ?> />
    <br>
