	<? if ($this->nb_caisseMinerai == 0 && $this->nb_caissePartiePlantes == 0) : ?>
		Votre caisse est vide<br>
	<? endif; ?>
	
	Castars : <?=$this->echoppe["quantite_castars_caisse_echoppe"] ?>, 
	Bois : <?=$this->echoppe["quantite_bois_caisse_echoppe"] ?>,
	Cuir : <?=$this->echoppe["quantite_cuir_caisse_echoppe"] ?>,
	Fourrure : <?=$this->echoppe["quantite_fourrure_caisse_echoppe"] ?><br>

   <? if ($this->nb_caissePartiePlantes == 0) : ?>
   	Aucune plante<br>
   <? else: ?>
    <? if ($this->nb_caissePartiePlantes==1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_caissePartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plantes : <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->partieplantes as $p) : 
      	if ($p["quantite_caisse"] > 0) :
      		$enter = true;
	    	if ($i % 3 == 0) echo "<tr>"; 
	    	$textPlante = "Type : ".htmlentities($p["nom_type"]). "<br>"; 
	    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite_caisse"])."<br>";
	    	?>
	    	<td onmouseover="return overlib('<?=$textPlante?>',CAPTION,'<?=htmlentities($p["nom_type"])?> - D&eacute;tails');"
	      		onclick="return overlib('<?=$textPlante?>', STICKY, CAPTION, 'Plante <?=htmlentities($p["nom_type"])?> - D&eacute;tails', CLOSECLICK, EXCLUSIVE);"
	      		onmouseout="return nd();">
	    		<?=$p["nom_type"]?> - Quantit&eacute;: <?=$p["quantite_caisse"]?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table>
   <? endif; ?>
   
   <? if ($this->nb_caisseMinerai == 0) : ?>
   	Aucun minerai<br>
   <? else: ?>
    <? if ($this->nb_caisseMinerai==1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_caisseMinerai?> minerai<?=$s?> : <br>
    
    <table width='100%'>
    <? $i = 0;
      $enter = false;
      foreach ($this->minerais as $m) : 
      	if ($m["quantite_caisse"] > 0) :
      		$enter = true;
	     	if ($i % 3 == 0) echo "<tr>"; 
	    	?>
	    	<td>
	    		<?=$m["type"]?> : Quantit&eacute; : <?=$m["quantite_caisse"]?>
	    	</td>
	    	<? if ($i % 3 == 2) echo "</tr>"; 
	    	$i++; 
	    endif;
     endforeach;
     if ($enter == true) :
     	if  ($i % 3 != 0) echo "</tr>"; 
     endif;
     ?>
    </table> 
    <? endif; ?>
    
    