<div class='comp_titre'>Construire une &eacute;choppe</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<? if ($this->construireMetierPossible === true && $this->construireLieuOk === true && $this->aucuneEchoppe === true) : ?>
		Dans cette comt&eacute; (<?=htmlentities($this->tabRegionCourante["nom_region"])?>),
		 vous pouvez construire une &eacute;choppe
		<? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>
		<?=$this->nom_metier_courant ?><br><br>
		Elle se trouvera sur votre case, soit en  x:<?=$this->user->x_hobbit ?> y:<?=$this->user->y_hobbit ?> 
	<? else: ?>
		<? if ($this->construireLieuOk == false) : ?>
			Vous ne pouvez pas construire d'&eacute;choppe sur un lieu...
		<? elseif ($this->aucuneEchoppe == false) : ?>
			Vous poss&eacute;dez d&eacute;j&agrave; une &eacute;choppe pour ce m&eacute;tier dans
			cette r&eacture;gion
		<? else: ?>
			Vous ne pouvez pas construire d'&eacute;choppe avec votre m&eacute;tier courant...
		<? endif; ?>
	<? endif; ?>
 </div> 
</form>
<br> 

<? if ($this->construireMetierPossible === true && $this->construireLieuOk === true && $this->aucuneEchoppe === true) : ?>
<input type='button' class='button1' id="construire_echoppe" value='Construire une echoppe' onClick="this.disabled=true;_get_('/echoppes/DoAction?caction=do_echoppes_construire');">
<? endif; ?>
<br>
<? include("commun_fermer.phtml") ?>