<div class='comp_titre'>Construire une &eacute;choppe</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<? if ($this->construirePossible === true) : ?>
		Vous pouvez construire une &eacute;choppe sur votre case
	<? else: ?>
		Vous ne pouvez pas construire d'&eacute;choppe ici...
	<? endif; ?>
 </div> 
</form>
<br> 

<? if ($this->construirePossible === true) : ?>
<input type='button' class='button1' id="construire_echoppe" value='Construire une echoppe' onClick="this.disabled=true;_get_('/echoppes/DoAction?caction=do_echoppes_construire');">
<? endif; ?>
<br>
<? include("commun_fermer.phtml") ?>