<div class='comp_titre'>D&eacute;poser des &eacute;l&eacute;ments dans la caisse</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<br>
</div>

</form>
<br>
<?php if ($this->deposercaisseOk === true) : ?>
<input type='button' class='button1' id='bouton_deposercaisse' value='D&eacute;poser des &eacute;l&eacute;ments !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_echoppes_deposercaisse");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>