<div class='comp_titre'>D&eacute;poser des mati&egrave;res premi&egrave;res</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo $this->nb_valeurs ?>'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez d&eacute;poser des mati&egrave;res premi&egrave;res pr&eacute;sentes 
 	dans votre laban (ou dans votre charrette pour les rondins) pour les mettre dans
 	l'arri&egrave;re-boutique de cette &eacute;choppe.<br />
 	
	<br />
	<?php echo $poches = null; ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="deposer_divers">
			<?php $poches[] = "deposer_divers-head" ?>
			<h3 id="deposer_divers-head" class="head" onclick="maccordion(this);">
				Divers
			</h3>
			<ul id="deposer_divers-body" style="display:none">
			<li>
				<?php if ($this->charretteOk === true && $this->charrette["nb_rondin"] > 0): ?>
					Rondins : <?php echo $this->charrette["nb_rondin"] ?>
					Quantit&eacute; &agrave; d&eacute;poser : 
					<input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0; if (this.value > <?php echo $this->charrette["nb_rondin"]  ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}" >
					<input type='hidden' maxlength='4' size='4' name='valeur_2_max' id='valeur_2_max' value='<?php echo $this->charrette["nb_rondin"] ?>' >
					<br />
				<?php else : ?>
					<input type='hidden' maxlength='4' size='4' name='valeur_2_max' id='valeur_2_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' >
				<?php endif; ?>
				<?php if ($this->laban["nb_peau"] > 0): ?>
				Peau : <?php echo $this->laban["nb_peau"] ?>.
				Quantit&eacute; &agrave; d&eacute;poser : 
				<input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->laban["nb_peau"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
				<input type='hidden' maxlength='4' size='4' name='valeur_3_max' id='valeur_3_max' value='<?php echo $this->laban["nb_peau"] ?>' >
				<?php else : ?>
					Aucune Peau.
					<input type='hidden' maxlength='4' size='4' name='valeur_3_max' id='valeur_3_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->laban["nb_cuir"] > 0): ?>
					Cuir : <?php echo $this->laban["nb_cuir"] ?>.
					Quantit&eacute; &agrave; d&eacute;poser : 
					<input type='text' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->laban["nb_cuir"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
					<input type='hidden' maxlength='4' size='4' name='valeur_4_max' id='valeur_4_max' value='<?php echo $this->laban["nb_cuir"] ?>' >
				<?php else : ?>
					Aucun cuir.
					<input type='hidden' maxlength='4' size='4' name='valeur_4_max' id='valeur_4_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->laban["nb_fourrure"] > 0): ?>
					Fourrure : <?php echo $this->laban["nb_fourrure"] ?>.
					Quantit&eacute; &agrave; d&eacute;poser : 
					<input type='text' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->laban["nb_fourrure"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
					<input type='hidden' maxlength='4' size='4' name='valeur_5_max' id='valeur_5_max' value='<?php echo $this->laban["nb_fourrure"] ?>' >
				<?php else : ?>
					Aucune fourrure.
					<input type='hidden' maxlength='4' size='4' name='valeur_5_max' id='valeur_5_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->laban["nb_planche"] > 0): ?>
					Planche : <?php echo $this->laban["nb_planche"] ?>.
					Quantit&eacute; &agrave; d&eacute;poser : 
					<input type='text' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->laban["nb_planche"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
					<input type='hidden' maxlength='4' size='4' name='valeur_6_max' id='valeur_6_max' value='<?php echo $this->laban["nb_planche"] ?>' >
				<?php else : ?>
					Aucune planche.
					<input type='hidden' maxlength='4' size='4' name='valeur_6_max' id='valeur_6_max' value='0' >
					<input type='hidden' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' >
				<?php endif; ?>
			</li>
			</ul>
		</li>
	</ul>
	
	<ul id="navigation" style="width:99%;text-align:left">
	<li id="deposer_plantes">
		<?php $poches[] = "deposer_plantes-head" ?>
		<h3 id="deposer_plantes-head" class="head" onclick="maccordion(this);">
			Plantes brutes / pr&eacute;par&eacute;es
		</h3>
		<ul id="deposer_plantes-body" style="display:none">
		<li>
		   <?php if ($this->nb_partiePlantes == 0 && $this->nb_prepareesPartiePlantes == 0) : ?>
		   		Aucune plante brute ou pr&eacute;par&eacute;e<br />
		    <?php else : ?>
			    <?php if ($this->nb_partiePlantes==1):$s=''; else:$s='s';endif; ?>
		  		<?php echo $this->nb_partiePlantes?> &eacute;l&eacute;ment<?php echo $s?> de plantes brute<?php echo $s?>: <br />
			    et 
			    <?php if ($this->nb_prepareesPartiePlantes==1):$s=''; else:$s='s';endif; ?>
			    <?php echo $this->nb_prepareesPartiePlantes?> &eacute;l&eacute;ment<?php echo $s?> de plantes pr&eacute;par&eacute;e<?php echo $s?>. <br />
		    
		    <table width='100%'>
		    <?php $i = 0;
		      $lignes = 0;
		      $enter = false;
		      $nb = count($this->partieplantes);
		      foreach ($this->partieplantes as $k => $p) : 
		      	if ($p["quantite_laban_partieplante"] > 0 || $p["quantite_preparee_laban_partieplante"] > 0) :
		      		$enter = true;
			    	if ($i % 3 == 0) echo "<tr>"; 
			    	?>
			    	<td>
			    		<?php if ($p["quantite_laban_partieplante"] > 1) : $s="s" ; else: $s=""; endif; ?>
				    		<?php if ($p["quantite_preparee_laban_partieplante"] > 1) : $s2="s" ; else: $s2="";endif;?>
				    		
				    		<?php echo htmlspecialchars($p["nom_plante"])?> : <?php echo $p["quantite_laban_partieplante"]?> <?php echo htmlspecialchars($p["nom_type"])?><?php echo $s ?> brute<?php echo $s ?> et <?php echo $p["quantite_preparee_laban_partieplante"]?> <?php echo htmlspecialchars($p["nom_type"])?><?php echo $s2 ?> pr&eacute;par&eacute;<?php echo $s2 ?>.
			    		<br />Quantit&eacute; &agrave; d&eacute;poser : 
			    		<br />Brute : <input type='text' maxlength='4' size='4' name='valeur_<?php echo $k?>' id='valeur_<?php echo $k?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $p["quantite_laban_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
			    		<br />Pr&eacute;par&eacute;e : <input type='text' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>' id='valeur_<?php echo ($k+1)?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $p["quantite_preparee_laban_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}">
			    		<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $p["quantite_laban_partieplante"]?>' >
			    		<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>_max' id='valeur_<?php echo ($k+1)?>_max' value='<?php echo $p["quantite_preparee_laban_partieplante"]?>' >
			    	<br />
			    	</td>
			    	<?php if ($i % 3 == 2) {
				    		echo "</tr>";
				    		$lignes++;
				    		if ($lignes == 2 && $i+1 < $nb) {
				    			$lignes = 0;
				    			echo "
				    				</table>
		    						</li>
									</ul>
									</li>
									</ul>
				    				<ul id='navigation' style='width:99%;text-align:left'>
									<li id='deposer_plantes_suite".$i."'>";
										$poches[] = "deposer_plantes_suite".$i."-head";
								echo "<h3 id='deposer_plantes_suite".$i."-head' class='head' onclick='maccordion(this);' />
											Plantes brutes / pr&eacute;par&eacute;es (suite)
										</h3>
										<ul id='deposer_plantes_suite".$i."-body' style='display:none'>
										<li>
										<table width='100%'>";
				    		}
				    	}
				    	$i++;
			    endif;
		     endforeach;
		     if ($enter == true) :
		     	if  ($i % 3 != 0) echo "</tr>"; 
		     endif;
		     ?>
		    </table>
		   <?php endif; ?>
		  </li>
		 </ul>
		</li>
	</ul>
   
   	<ul id="navigation" style="width:99%;text-align:left">
	<li id="deposer_minerais">
		<?php $poches[] = "deposer_minerais-head" ?>
		<h3 id="deposer_minerais-head" class="head" onclick="maccordion(this);">
			Minerais bruts / Lingots
		</h3>
		<ul id="deposer_minerais-body" style="display:none">
		<li>
		   <?php if ($this->nb_minerai_brut == 0 && $this->nb_minerai_lingot == 0) : ?>
		   	Aucun minerai brut ou lingot<br />
		   <?php else: ?>
		    <?php if ($this->nb_minerai_brut == 1):$s=''; else:$s='s';endif; ?>
		    <?php echo $this->nb_minerai_brut?> minerai<?php echo $s?> brut<?php echo $s?>
		    et 
		    <?php if ($this->nb_minerai_lingot == 1):$s=''; else:$s='s';endif; ?>
		    <?php echo $this->nb_minerai_lingot?> lingot<?php echo $s?>. <br />
		    
		    <table width='100%'>
		    <?php $i = 0;
		      $enter = false;
		      foreach ($this->minerais as $k => $m) : 
		      	$enter = true;
		     	if ($i % 3 == 0) echo "<tr>"; 
		    	?>
		    	<td>
		    		<?php echo htmlspecialchars($m["type"])?> - brut<?php if ($m["quantite_brut_laban_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_brut_laban_minerai"]?>, lingot<?php if ($m["quantite_lingots_laban_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_lingots_laban_minerai"]?>
		    		<br />
		    		Quantit&eacute; &agrave; d&eacute;poser : <br />
		    		Brut : <input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_brut_laban_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}" >
		    		<br />
		    		Lingot : <input type='text' maxlength='4' size='4' name='valeur_<?php echo ($k+1) ?>' id='valeur_<?php echo ($k+1) ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_lingots_laban_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_deposermatierespremieres').disabled=false;}else{$('bouton_deposermatierespremieres').disabled=true;}" >
		    	
		    		<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo $k?>_max' id='valeur_<?php echo $k?>_max' value='<?php echo $m["quantite_brut_laban_minerai"]?>' >
			    	<input type='hidden' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>_max' id='valeur_<?php echo ($k+1)?>_max' value='<?php echo $m["quantite_lingots_laban_minerai"]?>' >
		    	</td>
		    	<?php if ($i % 3 == 2) echo "</tr>"; 
		    	$i++; 
		     endforeach;
		     if ($enter == true) :
		     	if  ($i % 3 != 0) echo "</tr>"; 
		     endif;
		     ?>
		    </table> 
		    <?php endif; ?>
		  </li>
		</ul>
		</li>
	</ul>
 </div>

</form>
<br />

<?php 
$js = "
	cacher = true;
	for (i=2; i<=".$this->nb_valeurs."; i++) {
		$('valeur_' + i).value = $('valeur_' + i + '_max').value;
		if (cacher == true && $('valeur_' + i + '_max').value > 0) {
			cacher = false;
		}
	}
	$('bouton_deposermatierespremieres').disabled=cacher;

";
?>

<?php 
$jsFermer = "";
$jsOuvrir = "";
foreach ($poches as $p) :
	$jsFermer .= "maccordion_fermer($('$p'));";
	$jsOuvrir .= "maccordion_ouvrir($('$p'));";
endforeach; 
?>
   
   <input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onclick="<?php echo $js?>"> 
	<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onclick="<?php echo $jsFermer ?>">
    <input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onclick="<?php echo $jsOuvrir ?>">
	<br />
	
<?php if ($this->deposerRessourcesOk === true) : ?>
	<input type='button' class='button1' id='bouton_deposermatierespremieres' value='D&eacute;poser des &eacute;l&eacute;ments !' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_deposerressources");' disabled>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>