<div class='comp_titre'>Retirer des &eacute;l&eacute;ments dans la caisse</div>

 <div class='comp_contenu'>
	 <div id='deposercaisse_text' style="display:block"  onClick="javascript:switch2div('deposercaisse_text','deposercaisse_copie');">
		Vous avez d&eacute;pos&eacute; les &eacute;l&eacute;ments suivants : <br>
		TODO
		<br>
	 </div>
	 
	 <div id='deposercaisse_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez d&eacute;pos&eacute; les &eacute;l&eacute;ments suivants : ";
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('deposercaisse_text','deposercaisse_copie');">
<? include("commun_fermer.phtml") ?>