<ul class="titre textalic textsizec">Construction d'&eacute;choppes</ul>
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  <br>
  	Vous &ecirc;tes actuellement <?=$this->tabMetierCourant["nom_metier"] ?> et vous vous 
  	situez dans la <?=htmlentities($this->tabRegionCourante["nom_region"]) ?><br><br>
  	Vous ne pouvez construire d'&eacute;choppe que dans la comt&eacute; o&ugrave; vous 
  	&ecirc;tes.<br>
 	
 	<? if ($this->constructionPossible == false): ?>
 		Vous ne pouvez pas contruire d'&eacute;choppe avec votre m&eacute;tier courant<br>
 	<? endif; ?>
 	<br>
	<? if ($this->nEchoppes < 1) : ?>
  		Vous n'avez aucune &eacute;choppe.<br><br>
   	<? endif; ?>
   	
   	<? foreach($this->tabMetiers as $m) : ?>
   		<?=htmlentities($m["nom_metier"]) ?><br>
   		<? foreach($m["regions"] as $r) :?>
   			<? if ($r["echoppe"] != null): ?>
   			Votre &eacute;choppe dans la <?=htmlentities($r["nom_region"]) ?> se trouve en x:<?=$r["echoppe"]["x_echoppe"] ?> y:<?=$r["echoppe"]["y_echoppe"] ?>
   			<? else: ?>
   				<? if ($this->tabRegionCourante["id_region"] != $r["id_region"] || $this->tabMetierCourant["id_metier"] != $m["id_metier"]):$disabled="disabled";else:$disabled="";endif; ?>
   				<input type='button' class='button1' value="Construire une &eacute;choppe de <?=htmlentities($m["nom_metier"]) ?> dans la <?=htmlentities($r["nom_region"]) ?>" onClick="_get_('/echoppes/DoAction?caction=ask_echoppes_construire');" <?=$disabled ?>>
   			<? endif; ?>
   			<br>
   		<? endforeach; ?>
   	<? endforeach; ?>
   </ul>
</div>
