<div class='comp_titre'>Modifier le nom de l'&eacute;choppe</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	<br />
 	Entrez le nom de l'&eacute;choppe : <br>
	<input id="valeur_2" name="valeur_2" type="text" value="<?=htmlspecialchars($this->echoppe["nom_echoppe"])?>" size="22" maxlength="20"/>
	
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_modifiernom' value='Modifier le nom' onClick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_modifiernom");'>
<? echo Bral_Helper_Fermer::affiche(); ?>