<div class='comp_titre'>Modifier le nom de l'&eacute;choppe</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	<br />
 	Entrez le nom de l'&eacute;choppe : <br />
	<input id="valeur_2" name="valeur_2" type="text" value="<?php echo htmlspecialchars($this->echoppe["nom_echoppe"])?>" size="22" maxlength="30"/>
	
 </div>

</form>
<br />
<input type='button' class='button' id='bouton_modifiernom' value='Modifier le nom' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_modifiernom");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>