<div class='comp_titre'>Modifier la description de l'&eacute;choppe</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
	<br />
		<?=Bral_Helper_BBBoutons::affiche('valeur_descriptionechoppe', 300)?>
		<input type='hidden' id='valeur_2' name='valeur_2' value='' />
		<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="300" type="text"> Caract&egrave;res restants<br>
		<textarea name="valeur_descriptionechoppe" id="valeur_descriptionechoppe" class="inputbox" rows="10" cols="60" onkeydown="textCount($('valeur_descriptionechoppe'),$('characterstyped'),300);" onkeyup="textCount($('valeur_descriptionechoppe'),$('characterstyped'),300);"><?=$this->echoppe["commentaire_echoppe"]?></textarea>
		
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_modifierdescription' value='Modifier la description' onClick='this.disabled=true;$("valeur_2").value=encodePlus($("valeur_descriptionechoppe").value);_get_("/echoppes/doaction?caction=do_echoppes_modifierdescription");'>
<? echo Bral_Helper_Fermer::affiche(); ?>