<div class='comp_titre'>Modifier la description de l'&eacute;choppe</div>
 <input type='hidden' id='nb_valeurs-echoppes_modifierdescription' name='nb_valeurs-echoppes_modifierdescription' value='2'>
 <input type='hidden' id='valeur_1-echoppes_modifierdescription' name='valeur_1-echoppes_modifierdescription' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
	<br />
		<?php echo Bral_Helper_BBBoutons::affiche('valeur_descriptionechoppe', 2500)?>
		<input type='hidden' id='valeur_2-echoppes_modifierdescription' name='valeur_2-echoppes_modifierdescription' value='' />
		<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="<?php echo (2500-mb_strlen($this->echoppe["commentaire_echoppe"]))?>" type="text"> Caract&egrave;res restants<br />
		<textarea name="valeur_descriptionechoppe" id="valeur_descriptionechoppe" class="inputbox" rows="10" cols="60" onkeydown="textCount($('#valeur_descriptionechoppe'),$('#characterstyped'),2500);" onkeyup="textCount($('#valeur_descriptionechoppe'),$('#characterstyped'),2500);"><?php echo Bral_Util_BBParser::bbcodeStripPlus($this->echoppe["commentaire_echoppe"])?></textarea>
		
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_modifierdescription' value='Modifier la description' onclick='this.disabled=true;$("#valeur_2-echoppes_modifierdescription").val(encodePlus($("#valeur_descriptionechoppe").val()));_get_("/echoppes/doaction?caction=do_echoppes_modifierdescription", "echoppes_modifierdescription", true);'>
<?php echo Bral_Helper_Fermer::affiche(); ?>