<div class='comp_titre'>Retirer de la vente</div>
 <div class='comp_contenu'>
	 <div id='retirer_text' style="display:block"  onclick="javascript:switch2div('retirer_text','retirer_copie');">
		Vous avez retir&eacute; de l'&eacute;tal le mat&eacute;riel suivant : <br />
		<?php echo htmlspecialchars($this->materiel["nom"]) ?>
		<br />
	 </div>
	 
	 <div id='retirer_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?php
		echo "Vous avez retir&eacute; de l'&eacute;tal le mat&eacute;riel suivant : ";
		echo htmlspecialchars($this->materiel["nom"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('retirer_text','retirer_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>