<div class='comp_titre'>Retirer de la vente un &eacute;quipement</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<br />
	<? if ($this->nbEquipementsEtal > 0): ?>
		Vous pouvez retirer de l'&eacute;tal un &eacute;quipement : <br />
		<select name="valeur_2" id="valeur_2"  onChange="javascript:if ($('valeur_2').value==-1){$('bouton_retirer').disabled=true } else {$('bouton_retirer').disabled=false }">
	 		<option value="-1">(Choisissez un &eacute;quipement)</option>
			<? foreach($this->equipementsEtal as $e) :?>
				<option value="<?=$e["id_echoppe_equipement"] ?>">n&deg; <?=$e["id_echoppe_equipement"] ?> : <?=htmlspecialchars($e["nom"]) ?> de qualit&eacute; <?=htmlspecialchars($e["qualite"]) ?>,
				 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?></option>
			<? endforeach; ?>
		</select>
		<br /><br />
	<? else: ?>
		Vous n'avez aucun &eacute;quipement sur l'&eacute;tal.
	<? endif; ?>
</div>

</form>
<br />
<?php if ($this->retirerequipementOk === true) : ?>
<input type='button' class='button1' id='bouton_retirer' value='Retirer de la vente !' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_retirerequipement");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>