<div class='comp_titre'>Retirer de la vente un &eacute;quipement</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<br />
	<?php if ($this->nbEquipementsEtal > 0): ?>
		Vous pouvez retirer de l'&eacute;tal un &eacute;quipement : <br />
		<select name="valeur_2" id="valeur_2"  onchange="javascript:if ($('valeur_2').value==-1){$('bouton_retirer').disabled=true } else {$('bouton_retirer').disabled=false }">
	 		<option value="-1">(Choisissez un &eacute;quipement)</option>
			<?php foreach($this->equipementsEtal as $e) :?>
				<option value="<?php echo $e["id_echoppe_equipement"] ?>">n&deg; <?php echo $e["id_echoppe_equipement"] ?> : <?php echo htmlspecialchars($e["nom"]) ?> de qualit&eacute; <?php echo htmlspecialchars($e["qualite"]) ?>,
				 niveau: <?php echo $e["niveau"] ?>, nb. emplacements: <?php echo $e["nb_runes"] ?></option>
			<?php endforeach; ?>
		</select>
		<br /><br />
	<?php else: ?>
		Vous n'avez aucun &eacute;quipement sur l'&eacute;tal.
	<?php endif; ?>
</div>

</form>
<br />
<?php if ($this->retirerequipementOk === true) : ?>
<input type='button' class='button1' id='bouton_retirer' value='Retirer de la vente !' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_retirerequipement");' disabled>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>