<div class='comp_titre'>Retirer des mati&egrave;res premi&egrave;res</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=$this->nb_valeurs ?>'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez retirer des mati&egrave;res premi&egrave;res pr&eacute;sentes de cette &eacute;choppe 
 	pour les mettre dans votre laban (ou dans votre charrette pour les rondins).<br />
 	
	<br />
	<?=$poches = null; ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="retirer_divers">
			<? $poches[] = "retirer_divers-head" ?>
			<h3 id="retirer_divers-head" class="head" onClick="maccordion(this);" />
				Divers
			</h3>
			<ul id="retirer_divers-body" style="display:none">
			<li>
				<? if ($this->echoppe["quantite_rondin_arriere_echoppe"] > 0): ?>
					Rondins : <?=$this->echoppe["quantite_rondin_arriere_echoppe"] ?>.
					<? if ($this->charretteOk === true): ?>
						Quantit&eacute; &agrave; retirer : 
						<input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0; if (this.value > <?=$this->echoppe["quantite_rondin_arriere_echoppe"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
					<? else : ?>
						<input type='hidden' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' >
						Vous n'avez pas de charette pour les retirer.
					<? endif; ?>
				<? else : ?>
					Aucun rondin.
					<input type='hidden' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' >
				<? endif; ?>
				<br />
				<? if ($this->echoppe["quantite_peau_arriere_echoppe"] > 0): ?>
					Peau : <?=$this->echoppe["quantite_peau_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->echoppe["quantite_peau_arriere_echoppe"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<? else : ?>
					Aucune peau.
					<input type='hidden' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' >
				<? endif; ?>
				<br />
				<? if ($this->echoppe["quantite_cuir_arriere_echoppe"] > 0): ?>
					Cuir : <?=$this->echoppe["quantite_cuir_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->echoppe["quantite_cuir_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<? else : ?>
					Aucun cuir.
					<input type='hidden' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' >
				<? endif; ?>
				<br />
				<? if ($this->echoppe["quantite_fourrure_arriere_echoppe"] > 0): ?>
					Fourrure : <?=$this->echoppe["quantite_fourrure_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->echoppe["quantite_fourrure_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<? else : ?>
					Aucune fourrure.
					<input type='hidden' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' >
				<? endif; ?>
				<br />
				<? if ($this->echoppe["quantite_planche_arriere_echoppe"] > 0): ?>
					Planche : <?=$this->echoppe["quantite_planche_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$this->echoppe["quantite_planche_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<? else : ?>
					Aucune planche.
					<input type='hidden' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' >
				<? endif; ?>
			</li>
			</ul>
		</li>
	</ul>
	
	<ul id="navigation" style="width:99%;text-align:left">
	<li id="retirer_plantes">
		<? $poches[] = "retirer_plantes-head" ?>
		<h3 id="retirer_plantes-head" class="head" onClick="maccordion(this);" />
			Plantes brutes / pr&eacute;par&eacute;es
		</h3>
		<ul id="retirer_plantes-body" style="display:none">
		<li>
		    <? if ($this->nb_arrierePartiePlantes == 0 && $this->nb_prepareesPartiePlantes == 0) : ?>
		   		Aucune plante brute ou pr&eacute;par&eacute;e<br />
		    <? else : ?>
			    <? if ($this->nb_arrierePartiePlantes==1):$s=''; else:$s='s';endif; ?>
			    <?=$this->nb_arrierePartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plantes brute<?=$s?>: <br />
			    et 
			    <? if ($this->nb_prepareesPartiePlantes==1):$s=''; else:$s='s';endif; ?>
			    <?=$this->nb_prepareesPartiePlantes?> &eacute;l&eacute;ment<?=$s?> de plantes pr&eacute;par&eacute;e<?=$s?>. <br />
			    
			    <table width='100%'>
			    <? $i = 0;
			      $enter = false;
			      foreach ($this->partieplantes as $k => $p) : 
			      		$enter = true;
				    	if ($i % 3 == 0) echo "<tr>"; 
				    	?>
				    	<td>
				    		<? if ($p["quantite_arriere_echoppe_partieplante"] > 1) : $s="s" ; else: $s=""; endif;?>
				    		<? if ($p["quantite_arriere_echoppe_partieplante"] > 1) : $s2="s" ; else: $s2="";endif; ?>
				    		
				    		<?=htmlspecialchars($p["nom_plante"])?> : <?=$p["quantite_arriere_echoppe_partieplante"]?> <?=htmlspecialchars($p["nom_type"])?><?=$s ?> brute<?=$s ?> et <?=$p["quantite_preparees_echoppe_partieplante"]?> <?=htmlspecialchars($p["nom_type"])?><?=$s2 ?> pr&eacute;par&eacute;<?=$s2 ?>.
				    		Quantit&eacute; &agrave; retirer :<br>
				    		<br>Brute <input type='text' maxlength='4' size='4' name='valeur_<?=$k?>' id='valeur_<?=$k?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$p["quantite_arriere_echoppe_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				    		<br>Pr&eacute;par&eacute;e <input type='text' maxlength='4' size='4' name='valeur_<?=($k+1)?>' id='valeur_<?=($k+1)?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$p["quantite_preparees_echoppe_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				    	</td>
				    	<? if ($i % 3 == 2) echo "</tr>"; 
				    	$i++; 
			     endforeach;
			     if ($enter == true) :
			     	if  ($i % 3 != 0) echo "</tr>"; 
			     endif;
			     ?>
			    </table>
		   <? endif; ?>
		  </li>
		 </ul>
		</li>
	</ul>
   
   	<ul id="navigation" style="width:99%;text-align:left">
	<li id="retirer_minerais">
		<? $poches[] = "retirer_minerais-head" ?>
		<h3 id="retirer_minerais-head" class="head" onClick="maccordion(this);" />
			Minerais bruts / Lingots
		</h3>
		<ul id="retirer_minerais-body" style="display:none">
		<li>
		   <? if ($this->nb_arriereMinerai == 0 && $this->nb_arriereLingot == 0) : ?>
		   	Aucun minerai brut ou lingot<br />
		   <? else: ?>
		    <? if ($this->nb_arriereMinerai == 1):$s=''; else:$s='s';endif; ?>
		    <?=$this->nb_arriereMinerai?> minerai<?=$s?> brut<?=$s?>
		    et 
		    <? if ($this->nb_arriereLingot==1):$s=''; else:$s='s';endif; ?>
		    <?=$this->nb_arriereLingot?> lingot<?=$s?>. <br />
		    
		    <table width='100%'>
		    <? $i = 0;
		      $enter = false;
		      foreach ($this->minerais as $k => $m) : 
		      	$enter = true;
		     	if ($i % 3 == 0) echo "<tr>"; 
		    	?>
		    	<td>
		    		<?=htmlspecialchars($m["type"])?> - brut<? if ($m["quantite_arriere_echoppe_minerai"] > 0) echo "s" ?> : <?=$m["quantite_arriere_echoppe_minerai"]?>, lingot<? if ($m["quantite_lingots_echoppe_minerai"] > 0) echo "s" ?> : <?=$m["quantite_lingots_echoppe_minerai"]?>
		    		<br>Quantit&eacute; &agrave; retirer -<br>
		    		<br>Brut : <input type='text' maxlength='4' size='4' name='valeur_<?=$k ?>' id='valeur_<?=$k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$m["quantite_arriere_echoppe_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
		    		Lingot : <input type='text' maxlength='4' size='4' name='valeur_<?=($k+1) ?>' id='valeur_<?=($k+1) ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$m["quantite_lingots_echoppe_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
		    	</td>
		    	<? if ($i % 3 == 2) echo "</tr>"; 
		    	$i++; 
		     endforeach;
		     if ($enter == true) :
		     	if  ($i % 3 != 0) echo "</tr>"; 
		     endif;
		     ?>
		    </table> 
		    <? endif; ?>
		   </li>
		 </ul>
		</li>
	</ul>
 </div>

</form>
<br />

<? 
$jsFermer = "";
$jsOuvrir = "";
foreach ($poches as $p) :
	$jsFermer .= "maccordion_fermer($('$p'));";
	$jsOuvrir .= "maccordion_ouvrir($('$p'));";
endforeach; 
?>

<?php if ($this->retirerRessourcesOk === true) : ?>
	<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onClick="<?=$jsFermer ?>">
    <input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onClick="<?=$jsOuvrir ?>">
    <br>
<input type='button' class='button1' id='bouton_retirermatierespremieres' value='Retirer des &eacute;l&eacute;ments !' onClick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_retirerressources");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>