<div class='comp_titre'>Retirer des mati&egrave;res premi&egrave;res</div>
 <div class='comp_contenu'>
	 <div id='retirercaisse_text' style="display:block"  onClick="javascript:switch2div('retirercaisse_text','retirercaisse_copie');">
		Vous avez retir&eacute; les &eacute;l&eacute;ments suivants : <br />
		<?=htmlspecialchars($this->elementsRetires) ?>
		<br />
	 </div>
	 
	 <div id='retirercaisse_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez retir&eacute; les &eacute;l&eacute;ments suivants : ";
		echo htmlspecialchars($this->elementsRetires);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('retirercaisse_text','retirercaisse_copie');">
<? include("commun_fermer.phtml") ?>