<div class='comp_titre'>Retirer des mati&egrave;res premi&egrave;res</div>
 <div class='comp_contenu'>
 	<br />	
	 <div id='retirercaisse_text' style="display:block"  onclick="javascript:switch2div('retirercaisse_text','retirercaisse_copie');">
	 	<?php if (trim($this->elementsRetires) != "") :?>
			Vous avez retir&eacute; les &eacute;l&eacute;ments suivants : <br />
			<?php echo htmlspecialchars($this->elementsRetires) ?>
		<?php else: ?>
			Vous n'avez rien retir&eacute;, vous n'avez plus de place disponible !
		<?php endif;?>
		<br /><br />
	 </div>
	 
	 <div id='retirercaisse_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?php
		if (trim($this->elementsRetires) != "")  {
			echo "Vous avez retir&eacute; les &eacute;l&eacute;ments suivants : ";
			echo htmlspecialchars($this->elementsRetires);
		} else {
			echo "Vous n'avez rien retir&eacute;, vous n'avez plus de place disponible !";
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('retirercaisse_text','retirercaisse_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>