<div class='comp_titre'>Retirer de la vente</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

</div>

</form>
<br>
<?php if ($this->retirerOk === true) : ?>
<input type='button' class='button1' id='bouton_retirer' value='Retirer de la vente !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_competence_retirer");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>