<div class='comp_titre'>Retirer de la vente un mat&eacute;riel</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<br />
	<? if ($this->nbMaterielsEtal > 0): ?>
		Vous pouvez retirer de l'&eacute;tal un mat&eacute;riel : <br />
		<select name="valeur_2" id="valeur_2"  onChange="javascript:if ($('valeur_2').value==-1){$('bouton_retirer').disabled=true } else {$('bouton_retirer').disabled=false }">
	 		<option value="-1">(Choisis un mat&eacute;riel)</option>
			<? foreach($this->materielsEtal as $e) :?>
				<option value="<?=$e["id_echoppe_materiel"] ?>">n&deg; <?=$e["id_echoppe_materiel"] ?> : <?=htmlspecialchars($e["nom"]) ?></option>
			<? endforeach; ?>
		</select>
		<br /><br />
	<? else: ?>
		Vous n'avez aucun mat&eacute;riel sur l'&eacute;tal.
	<? endif; ?>
</div>

</form>
<br />
<?php if ($this->retirermaterielOk === true) : ?>
<input type='button' class='button1' id='bouton_retirer' value='Retirer de la vente !' onClick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_retirermateriel");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>