<div class='comp_titre'>Retirer de la vente</div>
 <div class='comp_contenu'>
	 <div id='retirer_text' style="display:block"  onClick="javascript:switch2div('retirer_text','retirer_copie');">
		Vous avez retir&eacute; de l'&eacute;tal le aliment suivant : <br />
		<?=htmlspecialchars($this->aliment["nom"]) ?>
		<br />
	 </div>
	 
	 <div id='retirer_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez retir&eacute; de l'&eacute;tal le aliment suivant : ";
		echo htmlspecialchars($this->aliment["nom"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('retirer_text','retirer_copie');">
<? echo Bral_Helper_Fermer::affiche(); ?>