<div class='comp_titre'>Retirer des mati&egrave;res premi&egrave;res</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo $this->nb_valeurs ?>'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez retirer des mati&egrave;res premi&egrave;res pr&eacute;sentes de cette &eacute;choppe 
 	pour les mettre dans votre laban (ou dans votre charrette pour les rondins).<br />
 	
	<br />
	<?php echo $poches = null; ?>
	<ul id="navigation" style="width:99%;text-align:left">
		<li id="retirer_divers">
			<?php $poches[] = "retirer_divers-head" ?>
			<h3 id="retirer_divers-head" class="head" onclick="maccordion(this);">
				Divers
			</h3>
			<ul id="retirer_divers-body" style="display:none">
			<li>
				<?php if ($this->echoppe["quantite_rondin_arriere_echoppe"] > 0): ?>
					Rondins : <?php echo $this->echoppe["quantite_rondin_arriere_echoppe"] ?>.
					<?php if ($this->charretteOk === true): ?>
						Quantit&eacute; &agrave; retirer : 
						<input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0; if (this.value > <?php echo $this->echoppe["quantite_rondin_arriere_echoppe"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
					<?php else : ?>
						<input type='hidden' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' >
						Vous n'avez pas de charette pour les retirer.
					<?php endif; ?>
				<?php else : ?>
					Aucun rondin.
					<input type='hidden' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->echoppe["quantite_peau_arriere_echoppe"] > 0): ?>
					Peau : <?php echo $this->echoppe["quantite_peau_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->echoppe["quantite_peau_arriere_echoppe"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<?php else : ?>
					Aucune peau.
					<input type='hidden' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->echoppe["quantite_cuir_arriere_echoppe"] > 0): ?>
					Cuir : <?php echo $this->echoppe["quantite_cuir_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->echoppe["quantite_cuir_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<?php else : ?>
					Aucun cuir.
					<input type='hidden' maxlength='4' size='4' name='valeur_4' id='valeur_4' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->echoppe["quantite_fourrure_arriere_echoppe"] > 0): ?>
					Fourrure : <?php echo $this->echoppe["quantite_fourrure_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->echoppe["quantite_fourrure_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<?php else : ?>
					Aucune fourrure.
					<input type='hidden' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='0' >
				<?php endif; ?>
				<br />
				<?php if ($this->echoppe["quantite_planche_arriere_echoppe"] > 0): ?>
					Planche : <?php echo $this->echoppe["quantite_planche_arriere_echoppe"] ?>.
					Quantit&eacute; &agrave; retirer : 
					<input type='text' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $this->echoppe["quantite_planche_arriere_echoppe"]?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				<?php else : ?>
					Aucune planche.
					<input type='hidden' maxlength='4' size='4' name='valeur_6' id='valeur_6' value='0' >
				<?php endif; ?>
			</li>
			</ul>
		</li>
	</ul>
	
	<ul id="navigation" style="width:99%;text-align:left">
	<li id="retirer_plantes">
		<?php $poches[] = "retirer_plantes-head" ?>
		<h3 id="retirer_plantes-head" class="head" onclick="maccordion(this);">
			Plantes brutes / pr&eacute;par&eacute;es
		</h3>
		<ul id="retirer_plantes-body" style="display:none">
		<li>
		    <?php if ($this->nb_arrierePartiePlantes == 0 && $this->nb_prepareesPartiePlantes == 0) : ?>
		   		Aucune plante brute ou pr&eacute;par&eacute;e<br />
		    <?php else : ?>
			    <?php if ($this->nb_arrierePartiePlantes==1):$s=''; else:$s='s';endif; ?>
			    <?php echo $this->nb_arrierePartiePlantes?> &eacute;l&eacute;ment<?php echo $s?> de plantes brute<?php echo $s?>: <br />
			    et 
			    <?php if ($this->nb_prepareesPartiePlantes==1):$s=''; else:$s='s';endif; ?>
			    <?php echo $this->nb_prepareesPartiePlantes?> &eacute;l&eacute;ment<?php echo $s?> de plantes pr&eacute;par&eacute;e<?php echo $s?>. <br />
			    
			    <table width='100%'>
			    <?php $i = 0;
			      $lignes = 0;
			      $enter = false;
			      $nb = count($this->partieplantes);
			      foreach ($this->partieplantes as $k => $p) : 
			      		$enter = true;
				    	if ($i % 3 == 0) echo "<tr>"; 
				    	?>
				    	<td>
				    		<?php if ($p["quantite_arriere_echoppe_partieplante"] > 1) : $s="s" ; else: $s=""; endif;?>
				    		<?php if ($p["quantite_arriere_echoppe_partieplante"] > 1) : $s2="s" ; else: $s2="";endif; ?>
				    		
				    		<?php echo htmlspecialchars($p["nom_plante"])?> : <?php echo $p["quantite_arriere_echoppe_partieplante"]?> <?php echo htmlspecialchars($p["nom_type"])?><?php echo $s ?> brute<?php echo $s ?> et <?php echo $p["quantite_preparee_echoppe_partieplante"]?> <?php echo htmlspecialchars($p["nom_type"])?><?php echo $s2 ?> pr&eacute;par&eacute;<?php echo $s2 ?>.
				    		Quantit&eacute; &agrave; retirer :<br />
				    		<br />Brute <input type='text' maxlength='4' size='4' name='valeur_<?php echo $k?>' id='valeur_<?php echo $k?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $p["quantite_arriere_echoppe_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				    		<br />Pr&eacute;par&eacute;e <input type='text' maxlength='4' size='4' name='valeur_<?php echo ($k+1)?>' id='valeur_<?php echo ($k+1)?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $p["quantite_preparee_echoppe_partieplante"] ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}">
				    	</td>
				    	<?php if ($i % 3 == 2) {
				    		echo "</tr>";
				    		$lignes++;
				    		if ($lignes == 2 && $i+1 < $nb) {
				    			$lignes = 0;
				    			echo "
				    				</table>
		    						</li>
									</ul>
									</li>
									</ul>
				    				<ul id='navigation' style='width:99%;text-align:left'>
									<li id='retirer_plantes_suite".$i."'>";
										$poches[] = "retirer_plantes_suite".$i."-head";
								echo "<h3 id='retirer_plantes_suite".$i."-head' class='head' onclick='maccordion(this);' />
											Plantes brutes / pr&eacute;par&eacute;es (suite)
										</h3>
										<ul id='retirer_plantes_suite".$i."-body' style='display:none'>
										<li>
										<table width='100%'>";
				    		}
				    	}
				    	$i++;
				    	
			     endforeach;
			     if ($enter == true) :
			     	if  ($i % 3 != 0) echo "</tr>"; 
			     endif;
			     ?>
			    </table>
		   <?php endif; ?>
		  </li>
		 </ul>
		</li>
	</ul>
   
   	<ul id="navigation" style="width:99%;text-align:left">
	<li id="retirer_minerais">
		<?php $poches[] = "retirer_minerais-head" ?>
		<h3 id="retirer_minerais-head" class="head" onclick="maccordion(this);">
			Minerais bruts / Lingots
		</h3>
		<ul id="retirer_minerais-body" style="display:none">
		<li>
		   <?php if ($this->nb_arriereMinerai == 0 && $this->nb_arriereLingot == 0) : ?>
		   	Aucun minerai brut ou lingot<br />
		   <?php else: ?>
		    <?php if ($this->nb_arriereMinerai == 1):$s=''; else:$s='s';endif; ?>
		    <?php echo $this->nb_arriereMinerai?> minerai<?php echo $s?> brut<?php echo $s?>
		    et 
		    <?php if ($this->nb_arriereLingot==1):$s=''; else:$s='s';endif; ?>
		    <?php echo $this->nb_arriereLingot?> lingot<?php echo $s?>. <br />
		    
		    <table width='100%'>
		    <?php $i = 0;
		      $enter = false;
		      foreach ($this->minerais as $k => $m) : 
		      	$enter = true;
		     	if ($i % 3 == 0) echo "<tr>"; 
		    	?>
		    	<td>
		    		<?php echo htmlspecialchars($m["type"])?> - brut<?php if ($m["quantite_brut_arriere_echoppe_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_brut_arriere_echoppe_minerai"]?>, lingot<?php if ($m["quantite_lingots_echoppe_minerai"] > 0) echo "s" ?> : <?php echo $m["quantite_lingots_echoppe_minerai"]?>
		    		<br />Quantit&eacute; &agrave; retirer -<br />
		    		<br />Brut : <input type='text' maxlength='4' size='4' name='valeur_<?php echo $k ?>' id='valeur_<?php echo $k ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_brut_arriere_echoppe_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
		    		Lingot : <input type='text' maxlength='4' size='4' name='valeur_<?php echo ($k+1) ?>' id='valeur_<?php echo ($k+1) ?>' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0;if (this.value > <?php echo $m["quantite_lingots_echoppe_minerai"] ?>) { alert('Valeur trop grande'); this.value = 0 }; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_retirermatierespremieres').disabled=false;}else{$('bouton_retirermatierespremieres').disabled=true;}" >
		    	</td>
		    	<?php if ($i % 3 == 2) echo "</tr>"; 
		    	$i++; 
		     endforeach;
		     if ($enter == true) :
		     	if  ($i % 3 != 0) echo "</tr>"; 
		     endif;
		     ?>
		    </table> 
		    <?php endif; ?>
		   </li>
		 </ul>
		</li>
	</ul>
 </div>

</form>
<br />

<?php 
$jsFermer = "";
$jsOuvrir = "";
foreach ($poches as $p) :
	$jsFermer .= "maccordion_fermer($('$p'));";
	$jsOuvrir .= "maccordion_ouvrir($('$p'));";
endforeach; 
?>
	<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onclick="<?php echo $jsFermer ?>">
    <input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onclick="<?php echo $jsOuvrir ?>">
    <br />
<?php if ($this->retirerRessourcesOk === true) : ?>

<input type='button' class='button1' id='bouton_retirermatierespremieres' value='Retirer des &eacute;l&eacute;ments !' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_retirerressources");' disabled>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>