<div class='comp_titre'>Retirer des mati&egrave;res premi&egrave;res</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<br>
</div>

</form>
<br>
<?php if ($this->retirerressourcesOk === true) : ?>
<input type='button' class='button1' id='bouton_retirerressources' value='Retirer des mati&egrave;res premi&egrave;res !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_echoppes_retirerressources");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>