<div class='comp_titre'>Transf&eacute;rer une potion ou un vernis</div>

 <div class='comp_contenu'>
	 <div id='transferpotion_text' style="display:block"  onclick="javascript:switch2div('transferpotion_text','transferpotion_copie');">
		Vous avez transf&eacute;r&eacute; dans <?php echo htmlspecialchars($this->destination["texte"])?> l'élément suivant : <br />
		<?php echo $this->potion["nom_type"]?> <?php echo htmlspecialchars($this->potion["nom"]) ?> n&deg; <?php echo $this->potion["id_echoppe_potion"] ?>
		<br />
	 </div>
	 
	 <div id='transferpotion_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez transf&eacute;r&eacute; ";
		echo " dans ".htmlspecialchars($this->destination["texte"]);
		echo " l'élément suivant : ";
		echo $this->potion["nom_type"]. " ";
		echo htmlspecialchars($this->potion["nom"]);
		echo " n&deg;".$this->potion["id_echoppe_potion"]; 
		
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('transferpotion_text','transferpotion_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>