<div class='comp_titre'>Transf&eacute;rer une potion</div>

 <div class='comp_contenu'>
	 <div id='transfererpotion_text' style="display:block"  onClick="javascript:switch2div('transfererpotion_text','transfererpotion_copie');">
		Vous avez transf&eacute;r&eacute; dans <?=htmlentities($this->destination["texte"])?> la potion <br />
		<?=htmlentities($this->potion["nom"]) ?> n&deg; <?=$this->potion["id_echoppe_potion"] ?>
		<br />
	 </div>
	 
	 <div id='transfererpotion_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez transf&eacute;r&eacute; ";
		echo " dans ".htmlentities($this->destination["texte"]);
		echo " la potion ";
		echo htmlentities($this->potion["nom"]);
		echo " n&deg;".$this->potion["id_echoppe_potion"]; 
		
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('transfererpotion_text','transfererpotion_copie');">
<? include("commun_fermer.phtml") ?>