<div class='comp_titre'>Transf&eacute;rer un &eacute;quipement</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='8'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>

 </div>

</form>
<br>
<?php if ($this->transfererOk > 0) : ?>
<input type='button' class='button1' id='bouton_transfererequipement' value='Transf&eacute;rer !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_echoppes_transfererequipement");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>