<div class='comp_titre'>Transf&eacute;rer un aliment</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 <br />
	
		Vous pouvez transf&eacute;rer un aliment pr&eacute;sent
		soit dans votre laban, soit votre charrette.<br /><br />

		<select name="valeur_3" id="valeur_3" onchange="_get_('/echoppes/doaction?caction=ask_echoppes_transferaliment&valeur_1=<?php echo $this->idEchoppe ?>&id_destination_courante='+this.value);">
	 		<option value="-1">(Choisissez une destination)</option>
			<?php foreach($this->destinationTransfert as $d) :?>
				<option value="<?php echo $d["id_destination"] ?>" <?php echo $d["selected"]?>><?php echo $d["texte"] ?></option>
			<?php endforeach; ?>
		</select>
		
		
	<?php if (count($this->alimentsArriereBoutique) > 0): ?>
		<br /><br />
		<?php if ($this->destinationTransfertCourante != null) : ?>
		<select name="valeur_2" id="valeur_2"  onchange="javascript:if ($('valeur_2').value==-1 || $('valeur_3').value==-1){$('bouton_transferaliment').disabled=true } else {$('bouton_transferaliment').disabled=false }">
	 		<option value="-1">(Choisissez un aliment)</option>
			<?php foreach($this->alimentsArriereBoutique as $e) :?>
				<option value="<?php echo $e["id_echoppe_aliment"] ?>" <?php if ($e["place_dispo"] == false):echo "disabled"; endif;?>>N&deg; <?php echo $e["id_echoppe_aliment"] ?>, <?php echo htmlspecialchars($e["nom"]) ?> <?php if ($e["place_dispo"] == false):echo "Trop Lourd !"; endif;?></option>
			<?php endforeach; ?>
		</select>
		<br /><br />
		<?php else: ?>
			<input type="hidden" name="valeur_2" id="valeur_2" value="-1">
		<?php endif; ?>
	<?php endif; ?>
	<br />
	
 </div>

</form>
<br />
<?php if ($this->transfererOk > 0 && $this->destinationTransfertCourante != null) : ?>
<input type='button' class='button1' id='bouton_transferaliment' value='Transf&eacute;rer !' onclick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_transferaliment&id_destination_courante=<?php echo $this->destinationTransfertCourante?>");' disabled>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>