<div class='comp_titre'>Transf&eacute;rer un &eacute;quipement</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 <br>
	<? if ($this->nbEquipementsArriereBoutique > 0): ?>
		Vous pouvez transf&eacute;rer un &eacute;quipement pr&eacute;sent dans la r&eacute;serve, 
		soit dans votre laban, soit un autre de vos &eacute;choppe.<br>
		<select name="valeur_2" id="valeur_2"  onChange="javascript:if ($('valeur_2').value==-1 || $('valeur_3').value==-1){$('bouton_transfererequipement').disabled=true } else {$('bouton_transfererequipement').disabled=false }">
	 		<option value="-1">(Choisis un &eacute;quipement)</option>
			<? foreach($this->equipementsArriereBoutique as $e) :?>
				<option value="<?=$e["id_echoppe_equipement"] ?>"><?=htmlentities($e["nom"]) ?> : qualit&eacute; <?=htmlentities($e["qualite"]) ?>,
				 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?></option>
			<? endforeach; ?>
		</select>
		<br><br>
		
		<select name="valeur_3" id="valeur_3"  onChange="javascript:if ($('valeur_2').value==-1 || $('valeur_3').value==-1){$('bouton_transfererequipement').disabled=true } else {$('bouton_transfererequipement').disabled=false }">
	 		<option value="-1">(Choisis une destination)</option>
			<? foreach($this->destinationTransfert as $d) :?>
				<option value="<?=$d["id_destination"] ?>"><?=$d["texte"] ?></option>
			<? endforeach; ?>
		</select>
		
	<? endif; ?>
 </div>

</form>
<br>
<?php if ($this->transfererOk > 0) : ?>
<input type='button' class='button1' id='bouton_transfererequipement' value='Transf&eacute;rer !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_echoppes_transfererequipement");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>