<div class='comp_titre'>Transf&eacute;rer une potion</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 <br />
	<? if (count($this->potionsArriereBoutique) > 0): ?>
		Vous pouvez transf&eacute;rer une potion pr&eacute;sente soit dans la r&eacute;serve, 
		soit dans votre laban, soit une autre de vos &eacute;choppes.<br />
		<select name="valeur_2" id="valeur_2"  onChange="javascript:if ($('valeur_2').value==-1 || $('valeur_3').value==-1){$('bouton_transferpotion').disabled=true } else {$('bouton_transferpotion').disabled=false }">
	 		<option value="-1">(Choisis une potion)</option>
			<? foreach($this->potionsArriereBoutique as $e) :?>
				<option value="<?=$e["id_echoppe_potion"] ?>">N&deg;<?=$e["id_echoppe_potion"] ?> <?=htmlspecialchars($e["nom"]) ?> : qualit&eacute; <?=htmlspecialchars($e["qualite"]) ?>,
				 niveau: <?=$e["niveau"] ?></option>
			<? endforeach; ?>
		</select>
		<br /><br />
		
		Vers : <br />
		<select name="valeur_3" id="valeur_3"  onChange="javascript:if ($('valeur_2').value==-1 || $('valeur_3').value==-1){$('bouton_transferpotion').disabled=true } else {$('bouton_transferpotion').disabled=false }">
	 		<option value="-1">(Choisis une destination)</option>
			<? foreach($this->destinationTransfert as $d) :?>
				<option value="<?=$d["id_destination"] ?>"><?=$d["texte"] ?></option>
			<? endforeach; ?>
		</select>
		
	<? endif; ?>
	<br>
	<? if ($this->placeDispo == false) :?>
		Vous n'avez pas assez de place dans votre laban.<br>
	<? endif; ?>
 </div>

</form>
<br />
<?php if ($this->transfererOk > 0 && $this->placeDispo === true) : ?>
<input type='button' class='button1' id='bouton_transferpotion' value='Transf&eacute;rer !' onClick='this.disabled=true;_get_("/echoppes/doaction?caction=do_echoppes_transferpotion");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>