<div class='comp_titre'>Transf&eacute;rer un &eacute;quipement</div>

 <div class='comp_contenu'>
	 <div id='transfermateriel_text' style="display:block"  onclick="javascript:switch2div('transfermateriel_text','transfermateriel_copie');">
		Vous avez transf&eacute;r&eacute; l'&eacute;quipement suivant : <br />
		<?php echo htmlspecialchars($this->equipement["nom"]) ?> dans <?php echo htmlspecialchars($this->destination["texte"]) ?>
		<br />
	 </div>
	 
	 <div id='transferequipement_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?php
		echo "Vous avez transf&eacute;r&eacute; l'&eacute;quipement suivant : ";
		echo htmlspecialchars($this->equipement["nom"]); 
		echo " dans ".htmlspecialchars($this->destination["texte"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('transferequipement_text','transferequipement_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>