<div class='comp_titre'>Transf&eacute;rer un aliment</div>
 <div class='comp_contenu'>
	 <div id='transferaliment_text' style="display:block"  onclick="javascript:switch2div('transferaliment_text','transferaliment_copie');">
		Vous avez transf&eacute;r&eacute; l'aliment suivant : <br />
		<?php echo htmlspecialchars($this->aliment["nom"]) ?> dans <?php echo htmlspecialchars($this->destination["texte"]) ?>
		<br />
	 </div>
	 
	 <div id='transferaliment_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez transf&eacute;r&eacute; l'aliment suivant : ";
		echo htmlspecialchars($this->aliment["nom"]); 
		echo " dans ".htmlspecialchars($this->destination["texte"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('transferaliment_text','transferaliment_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>