<div class='comp_titre'>Transf&eacute;rer un mat&eacute;riel</div>
 <div class='comp_contenu'>
	 <div id='transfermateriel_text' style="display:block"  onClick="javascript:switch2div('transfermateriel_text','transfermateriel_copie');">
		Vous avez transf&eacute;r&eacute; le mat&eacute;riel suivant : <br />
		<?=htmlspecialchars($this->materiel["nom"]) ?> dans <?=htmlspecialchars($this->destination["texte"]) ?>
		<br />
	 </div>
	 
	 <div id='transfermateriel_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez transf&eacute;r&eacute; le mat&eacute;riel suivant : ";
		echo htmlspecialchars($this->materiel["nom"]); 
		echo " dans ".htmlspecialchars($this->destination["texte"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('transfermateriel_text','transfermateriel_copie');">
<? echo Bral_Helper_Fermer::affiche(); ?>