<div class='comp_titre'>Mettre en vente</div>

 <div class='comp_contenu'>
	 <div id='vendre_text' style="display:block"  onClick="javascript:switch2div('vendre_text','vendre_copie');">
		

		<br>
	 </div>
	 
	 <div id='vendre_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?

	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('vendre_text','vendre_copie');">
<? include("commun_fermer.phtml") ?>