<div class='comp_titre'>Mettre en vente un aliment</div>
 <div class='comp_contenu'>
	 <div id='vendre_text' style="display:block"  onClick="javascript:switch2div('vendre_text','vendre_copie');">
		Vous avez mis en vente l'aliment suivant : <br />
		<?=htmlspecialchars($this->aliment["nom"]) ?>
		<br />
	 </div>
	 
	 <div id='vendre_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez mis en vente l'aliment suivant : ";
		echo htmlspecialchars($this->aliment["nom"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('vendre_text','vendre_copie');">
<? echo Bral_Helper_Fermer::affiche(); ?>