<div class='comp_titre'>Mettre en vente un &eacute;quipement</div>

 <div class='comp_contenu'>
	 <div id='vendre_text' style="display:block"  onclick="javascript:switch2div('vendre_text','vendre_copie');">
		Vous avez mis en vente l'&eacute;quipement suivant : <br />
		<?php echo htmlspecialchars($this->equipement["nom"]) ?>
		<br />
	 </div>
	 
	 <div id='vendre_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?
		echo "Vous avez mis en vente l'&eacute;quipement suivant : ";
		echo htmlspecialchars($this->equipement["nom"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('vendre_text','vendre_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>