<div class='comp_titre'>Mettre en vente un aliment</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='9'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idEchoppe ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	<? if (count($this->alimentsArriereBoutique) > 0): ?>
		Vous pouvez mettre en vente un aliment pr&eacute;sent dans la r&eacute;serve : <br />
		<select name="valeur_2" id="valeur_2"  onChange="javascript:$('valeur_commentaire').value=$('commentaire_' + this.value).value; if ($('valeur_2').value==-1 || $('valeur_3').value=='' || $('valeur_4').value==-1 ){$('bouton_vendrealiment').disabled=true } else {$('bouton_vendrealiment').disabled=false }">
	 		<option value="-1">(Choisissez un aliment)</option>
			<? foreach($this->alimentsArriereBoutique as $e) :?>
				<option value="<?=$e["id_echoppe_aliment"] ?>">n&deg; <?=$e["id_echoppe_aliment"] ?> : <?=htmlspecialchars($e["nom"]) ?></option>
			<? endforeach; ?>
		</select>
		<br /><br />
		
		<input type='hidden' id='commentaire_-1' name='commentaire_-1' value=''>
		<? foreach($this->alimentsArriereBoutique as $e) :?>
			<input type='hidden' id='commentaire_<?=$e["id_echoppe_aliment"] ?>' name='commentaire_<?=$e["id_echoppe_aliment"] ?>' value='<?=htmlspecialchars($e["commentaire"], ENT_QUOTES);?>'>
		<? endforeach;?>
		
		Vous pouvez vendre le aliment &agrave; l'aide de trois unit&eacute;s diff&eacute;rentes : <br />
		
		<? $js = "
			if ($('valeur_2').value !=-1 && $('valeur_3').value >= 0 && $('valeur_3').value != '' && $('valeur_4').value !=-1 ) {
				$('bouton_vendrealiment').disabled=false;
			} else {
				$('bouton_vendrealiment').disabled=true;
			}
		";
		?>
		
		<table class="table_liste" style="width:98%; border:0" >
		<tbody>
			<tr class="table_liste" valign="top">
				<td align="right">
					<input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
					unit&eacute;(s) de 
				</td>
				<td align="left">&nbsp;
					<select name="valeur_4" id="valeur_4" onChange="<?=$js ?>">
				 		<option value="-1">(Choisissez une unit&eacute;)</option>
						<? foreach($this->unites as $k => $u) :?>
							<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
						<? endforeach; ?>
					</select> OU
				</td>
			</tr>
			<tr>
				<td align="right">
					<input type='text' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
					unit&eacute;(s) de 
				</td>
				<td align="left">&nbsp;
					<select name="valeur_6" id="valeur_6">
				 		<option value="-1">(Choisissez une unit&eacute;)</option>
						<? foreach($this->unites as $k => $u) :?>
							<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
						<? endforeach; ?>
					</select> OU
				</td>
			</tr>
			<tr>
				<td align="right">
					<input type='text' maxlength='4' size='4' name='valeur_7' id='valeur_7' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
					unit&eacute;(s) de 
				</td>
				<td align="left">&nbsp;
					<select name="valeur_8" id="valeur_8">
				 		<option value="-1">(Choisissez une unit&eacute;)</option>
						<? foreach($this->unites as $k => $u) :?>
							<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
						<? endforeach; ?>
					</select>
				</td>
			</tr>
		</tbody>
		</table>
		 
		<br /><br />
	
		<div class="titre textalic textsized" > Commentaire de mise en vente </div>
		<br />
		<?=Bral_Helper_BBBoutons::affiche('valeur_commentaire', 300)?>
		<input type='hidden' id='valeur_9' name='valeur_9' value='' />
		<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="300" type="text"> Caract&egrave;res restants<br />
		<textarea name="valeur_commentaire" id="valeur_commentaire" class="inputbox" rows="10" cols="60" onkeydown="textCount($('valeur_commentaire'),$('characterstyped'),300);" onkeyup="textCount($('valeur_commentaire'),$('characterstyped'),300);"><?=$this->commentaire?></textarea>
		
	<? else: ?>
		Vous n'avez aucun aliment en r&eacute;serve
	<? endif; ?>
 </div>

</form>
<br />
<?php if ($this->vendreOk > 0) : ?>
<input type='button' class='button1' id='bouton_vendrealiment' value='Mettre en vente !' onclick='this.disabled=true;$("valeur_9").value=encodePlus($("valeur_commentaire").value);_get_("/echoppes/doaction?caction=do_echoppes_vendrealiment");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>