<div class='comp_titre'>Mettre en vente un potion</div>

 <div class='comp_contenu'>
	 <div id='vendre_text' style="display:block"  onclick="javascript:switch2div('vendre_text','vendre_copie');">
		Vous avez mis en vente l'élément suivant : <br />
		<?php echo $this->potion["nom_type"]?> <?php echo htmlspecialchars($this->potion["nom"]) ?> n&deg;<?php echo htmlspecialchars($this->potion["id_echoppe_potion"]) ?>
		<br />
	 </div>
	 
	 <div id='vendre_copie' style="display:none">
		<textarea onclick="javascript:this.select();" rows=4 cols=40><?php
		echo "Vous avez mis en vente l'élément suivant: ";
		echo $this->potion["nom_type"]. " ";
		echo htmlspecialchars($this->potion["nom"]);
		echo " n&deg;". htmlspecialchars($this->potion["id_echoppe_potion"]);
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onclick="javascript:switch2div('vendre_text','vendre_copie');">
<?php echo Bral_Helper_Fermer::affiche(); ?>