<div class='comp_titre'>Mettre en vente un &eacute;quipement</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br>
	<? if ($this->nbEquipementsArriereBoutique > 0): ?>
		Vous pouvez mettre en vente en &eacute;quipement pr&eacute;sent dans la r&eacute;serve : <br>
		<select name="valeur_1" id="valeur_1"  onChange="javascript:if ($('valeur_1').value==-1){$('bouton_cueillir').disabled=true } else {$('bouton_cueillir').disabled=false }">
	 		<option value="-1">(Choisis un &eacute;quipement)</option>
			<? foreach($this->equipementsArriereBoutique as $e) :?>
				<option value="<?=$e["id_echoppe_equipement"] ?>"><?=htmlentities($e["nom"]) ?> : qualit&eacute; <?=htmlentities($e["qualite"]) ?>,
				 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?></option>
			<? endforeach; ?>
		</select>
		<br>
		
		Vous pouvez vendre votre &eacute;quipement &agrave; l'aide de trois unit&eacute;s diff&eacute;rentes : 
		
		
	<? else: ?>
		Vous n'avez aucun &eacute;quipement en r&eacut;serve
	<? endif; ?>
 </div>

</form>
<br>
<?php if ($this->nbEquipementsArriereBoutique > 0) : ?>
<input type='button' class='button1' id='bouton_vendre' value='Mettre en vente !' onClick='this.disabled=true;_get_("/echoppes/DoAction?caction=do_competence_vendre");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>