<ul class="titre textalic textsizec">&Eacute;choppe <? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?> 
<?=htmlentities($this->echoppe["nom_metier"])?>, <?=htmlentities($this->echoppe["nom_region"])?> </ul>
<ul class="titre textalic textsizec">x:<?=$this->echoppe["x_echoppe"]?>, y:<?=$this->echoppe["y_echoppe"]?></ul>

<br><hr>
<ul class="titre textalic textsizec">La caisse</ul>
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  <br>
 	<? include("caisse.phtml") ?>
   </ul>
</div>

<br><hr>
<ul class="titre textalic textsizec">L'arri&egrave;rre boutique</ul>
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  <br>
 	<? include("arriere_boutique.phtml") ?>
   </ul>
</div>

<br><hr>
<ul class="titre textalic textsizec">L'atelier</ul>
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  <br>
  	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
  	?>
  		Vous &ecirc;tes dans votre &eacute;choppe, vous pouvez travailler...<br>
  	<? else: 
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous ne pouvez pas y travailler...<br>
  	<? endif; ?>
		<? foreach($this->competences as $c) : ?>
				<input type="button" class='button1' value="<?=$c["pa_utilisation"]?> PA - <?=htmlentities($c["nom"])?> : <?=$c["pourcentage"]?> % "
       		  onClick="Javascript:_get_('/competences/DoAction?caction=ask_competence_<?=$c["nom_systeme"] ?>')" <?=$disabled ?>>
		<? endforeach; ?>
   </ul>
</div>

<br><hr>
<ul class="titre textalic textsizec">l'&eacute;tal</ul>
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  <br>
 	Etal ICI
   </ul>
</div>


