<ul style="text-align:left; position:Absolute; padding: 0px; ">
<input type="button" class='button1' onClick='_get_("/echoppes/doaction?caction=ask_echoppes_liste");' value="Retour &agrave; la liste">
</ul>

<ul class="titre textalic textsizec">&Eacute;choppe <? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?> 
<?=htmlspecialchars($this->echoppe["nom_metier"])?>, <?=htmlspecialchars($this->echoppe["nom_region"])?> </ul>
<ul class="titre textalic textsizec">x:<?=$this->echoppe["x_echoppe"]?>, y:<?=$this->echoppe["y_echoppe"]?></ul>
<br />

<hr> <br />

<? include("voir/arriere_boutique.phtml") ?>

<hr> <br />
  	
<? include("voir/atelier.phtml") ?>
  	
<hr><br />

<? include("voir/etal.phtml") ?>

