<ul style="text-align:left; position:Absolute; padding: 0px; ">
<input type="button" class='button1' onClick='_get_("/echoppes/doaction?caction=ask_echoppes_liste");' value="Retour &agrave; la liste">
</ul>

<ul class="titre textalic textsizec">
<?if ($this->echoppe["nom_echoppe"] != null && $this->echoppe["nom_echoppe"] != "") : ?>
	<?=htmlspecialchars($this->echoppe["nom_echoppe"])?>,
<? endif; ?>
&Eacute;choppe <? if ($this->echoppe["nom_metier"]{0} == 'A') : echo 'd\''; else: echo "de"; endif; ?> <?=htmlspecialchars($this->echoppe["nom_metier"])?><br></ul>
<ul class="titre textalic textsizec"><?=htmlspecialchars($this->echoppe["nom_region"])?>, x:<?=$this->echoppe["x_echoppe"]?>, y:<?=$this->echoppe["y_echoppe"]?></ul>
<br />

    <? if ($this->estSurEchoppe === true && $this->user->activation == true): 
  		$disabled = "";
  	   else:
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
  	<? endif; ?>

 <input type="button" class='button1' value="0 PA - Modifier le nom" 
 onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_modifiernom&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled?> />
 <input type="button" class='button1' value="0 PA - Modifier la description"
  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_modifierdescription&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled?>/>
 
<hr> <br />

<? include("voir/arriere_boutique.phtml") ?>

<hr> <br />
  	
<? include("voir/atelier.phtml") ?>
  	
<hr><br />

<? include("voir/etal.phtml") ?>

