<?php Zend_Loader::loadClass("Bral_Helper_DetailPrix");?>
<?php if (count($this->lots["lots"]) > 0) : ?>
Afficher : 
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('',1)">Tout</span>-
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('équipement',1)">Equipements</span>-
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('potion',1)">Potions</span> -
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('aliment',1)">Aliments</span> -
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('rune',1)">Runes</span> -
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('plante',1)">Plantes</span> -
<span class="alabel" onClick="Javascript:$('#idLotsTable').dataTable().fnFilter('minerai',1)">Minerais</span><br/><br/>
<div id="cadre_lots">
    <table class="table_liste" style="width:100%" id="idLotsTable">
		<thead class="table_liste">
			<tr class="table_liste">
				<th>N° du lot</th>
                <th>Type</th>
                <th>Description du lot</th>
                <th>Prix</th>
				<th>Vendeur</th>
                <th>Commentaire</th>
			</tr>
		</thead>
		<tbody>
		<?php $i=0; ?>
        <?php foreach ($this->lots["lots"] as $numero => $lot) : ?>
		    <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
                <td class="table_liste"><?php echo $numero?></td>
                <td><?php echo $lot["resume"]; ?></td>
                <td class="table_liste">
                    <?php include("lot.phtml") ?>
                </td>
                <td class="table_liste"><?php echo Bral_Helper_DetailPrix::afficherPrix($lot, ""); ?></td>
                <td class="table_liste">
                    <a onclick="javascript:ouvrirWin('<?php echo $this->config->url->game?>/voir/braldun/?braldun=<?php echo $lot['id_fk_vendeur_braldun_lot']  ?>');"
                               title="Cliquez pour voir le profil"><?php echo $lot['prenom_braldun_vendeur'] ?> <?php echo $lot['nom_braldun_vendeur'] ?>
                                (<?php echo $lot['id_fk_vendeur_braldun_lot'] ?>)</a>
                    <?php if ($lot['echoppe'] != null) : ?>
                        <?php //Échoppe en x:<?php echo $lot['echoppe']['x_echoppe'] , y:<?php echo $lot['echoppe']['y_echoppe']<br />?>
                    <?php endif;?>
                </td>
                <td class="table_liste">
                    <?php echo Bral_Util_BBParser::bbcodeReplace($lot['commentaire_lot']);?>
                </td>
			</tr>
		<?php endforeach;?>
        </tbody>
	</table>
</div>
<script type="text/javascript">
    tableauTriable("idLotsTable");
</script>
<?php else: ?>
	<i>Rien en vente</i>
<?php endif;?>
