<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>

 <div class='comp_contenu'>
	 <div id='<?=$this->nom_systeme?>_text' style="display:block">
	<?=$this->texte ?>
		<br />
	 </div>
	 
	 <div id='<?=$this->nom_systeme?>_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?=Bral_Helper_Affiche::copie($this->texte); ?></textarea>
	</div>
 </div>
<br /><br />
<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('<?=$this->nom_systeme?>_text','<?=$this->nom_systeme?>_copie');">
<? if ($this->reloadInterface == true): ?>
	<input type='button' class='button1' value='Fermer' onClick='_get_("/interface/reload");Modalbox.hide();'>
<? else: ?>
	<? echo Bral_Helper_Fermer::affiche(); ?>
<? endif; ?>