<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la banque">
	</ul>
		<?=$this->nomLieu ?><br/><br/>
	</ul>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
		
	<br /><br />

	<input type="button" class='button1' onClick='_get_("/lieux/doaction?caction=ask_lieu_banqueretirer");' value="<?=$this->paUtilisationBanque ?> PA - Retirer des &eacute;l&eacute;ments">
	<br>
	Les dépots sont actuellement suspendus, ils seront de nouveau possible d'ici quelques jours.<br>
	<br>
	<input type="button" class='button1' onClick='_get_("/lieux/doaction?caction=ask_lieu_banquedeposer");' value="<?=$this->paUtilisationBanque ?> PA - D&eacute;poser des &eacute;l&eacute;ments" disabled>
	<br /><br />
	Votre coffre contient plusieurs tiroirs. Cliquez sur celui ou ceux que vous souhaitez ouvrir. <br /><br />

	<br />
	<? include("commun/poches.phtml") ?>
	</ul>
 	</div>
</div>
<? include("box_bottom.phtml") ?>