<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la boutique">
	</ul>
		<?=$this->nomLieu ?><br/><br/>
	</ul>
	<? if ($this->tabStockPrix == null) : ?>
		Les prix du marché sont inconnus, la boutique est fermée.
	<? else: ?>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
			<br />
			<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_acheterbois");' value="<?=$this->paUtilisationBoutique ?> PA - Acheter">
			<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_vendrebois");' value="<?=$this->paUtilisationBoutique ?> PA - Vendre">
			<br /><br />
			
			 <table class="table_liste" style="width:80%; padding:5px;" >
				<thead class="table_liste">
				  <tr class="table_liste">
				  <th style="width:auto; padding:5px;" >&nbsp;</th>
				  <th style="width:auto; padding:5px;" >Article</th>
				  <th style="width:auto; padding:5px;" >Prix Unitaire de vente par la boutique</th>
				  <th style="width:auto; padding:5px;" >Prix Unitaire d'achat par la boutique</th>
				  <th style="width:auto; padding:5px;" >Stock initial</th>
				  <th style="width:auto; padding:5px;" >Stock restant</th>
				  </tr>
				</thead>
				<tbody>
					<? $i = 0;
					foreach ($this->tabStockPrix as $a) :  ?>
						<tr class="table_liste<?=($i % 2);$i++; ?>">
							<td style="width:auto; padding:5px;" >
								<img src='/public/styles/braldahim_defaut/images/elements/rondin.png' alt='rondin'/>
							</td>
							<td style="width:auto; padding:5px;" >Rondin</td>
							<td style="width:auto; padding:5px;" ><?=htmlspecialchars($a["prix_unitaire_vente_stock_bois"])?></td>
							<td style="width:auto; padding:5px;" ><?=htmlspecialchars($a["prix_unitaire_reprise_stock_bois"])?></td>
							<td style="width:auto; padding:5px;" ><?=htmlspecialchars($a["nb_rondin_initial_stock_bois"])?></td>
							<td style="width:auto; padding:5px;" ><?=htmlspecialchars($a["nb_rondin_restant_stock_bois"])?></td>
						</tr>
					<? endforeach; ?>
				</tbody>
			</table>
			<br />
 		</ul>
 	</div>
 	<? endif ?>
</div>
<? include("box_bottom.phtml") ?>