<?php include("box_header.phtml") ?>
<div class="inner">
  <span class="titre textalia textsizec">Le Bla bla...</span>
  <div class="contenuA">
	  <div class="box_contenu1 textalic">
	<?php if ($this->affichageInterne == true) : ?>
			<?php include("blabla/messages.phtml") ?>
	<br /><br />
	<?php else: ?>
		Chargement en cours
		<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
	<?php endif; ?>
	  </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>