<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul style="text-align:left; position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la boutique">
	</ul>
		<?=$this->nomLieu ?><br/><br/>
	</ul>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
			<br />
			
			<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_acheterminerais");' value="<?=$this->paUtilisationBoutique ?> PA - Acheter">
			<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_vendreminerais");' value="<?=$this->paUtilisationBoutique ?> PA - Vendre">
			
			<br /><br />
			Prix de vente des minerais bruts
			<br /><br />
			<?=$this->render("/interface/commun/minerais/minerais.phtml"); ?>
				
			<br />
 		</ul>
 	</div>
</div>
<? include("box_bottom.phtml") ?>