<input type='hidden' id='switch_<?=$this->conteneur; ?>' value='<?=$this->liste ?>'>
<div class="<?=$this->conteneur; ?>" id="<?=$this->conteneur; ?>">
<?php foreach($this->onglets as $onglet) : ?>
	<input type='hidden' id='loaded_<?=$onglet["nom"] ?>' value='<?=$onglet["chargementInBoxes"] ?>'>
	<li id='onglet_<?=$onglet["nom"] ?>' class='onglet <?=$onglet["css"] ?>' onClick='Javascript:$("<?=$this->conteneur?>").style.display="none";my_switch("<?=$onglet["nom"] ?>","<?=$this->conteneur ?>"); '>
	&nbsp;<?=$onglet["titre"] ?>&nbsp;
	</li>
<?php endforeach; ?>
</div>
<?php echo $this->data ?>