<?php if ($this->affichageInterne == false) :
	echo '<div class="'.$this->nom_interne.'" id="'.$this->nom_interne.'" style="display:'.$this->display.'">';
endif; ?>

<?php if ($this->estMobile) : ?>
<div id='onglet_menu' class='onglet actif' onclick='Javascript:switch2div("boite_m","<?=$this->nom_interne ?>"); '>
Menu
</div>
<div id='onglet_menu' class='onglet actif' onclick="Javascript:_get_('/interface/load/?box=<?=$this->nom_interne ?>'); ">
Rafraîchir
</div>
<?php endif; ?>
