<input type='hidden' id='switch_<?php echo $this->conteneur; ?>' value='<?php echo $this->liste ?>'>
<div class="<?php echo $this->conteneur; ?>" id="<?php echo $this->conteneur; ?>">
<?php foreach($this->onglets as $onglet) : ?>
	<input type='hidden' id='loaded_<?php echo $onglet["nom"] ?>' value='<?php echo $onglet["chargementInBoxes"] ?>'>
	<div id='onglet_<?php echo $onglet["nom"] ?>' class='onglet <?php echo $onglet["css"] ?>' onclick='Javascript:$("<?php echo $this->conteneur?>").style.display="none";my_switch("<?php echo $onglet["nom"] ?>","<?php echo $this->conteneur ?>"); '>
	&nbsp;<?php echo $onglet["titre"] ?>&nbsp;
	</div>
<?php endforeach; ?>
</div>
<?php echo $this->data ?>