<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la boutique">
	</ul>
		<?=$this->nomLieu ?><br/><br/>
	</ul>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
			<br />
			<? if ($this->typePlantesBruts == null) : ?>
				Les prix du marché sont inconnus, la boutique est fermée.<br />
			<? else: ?>
			
				<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_acheterpartieplantes");' value="<?=$this->paUtilisationBoutique ?> PA - Acheter">
				<input type="button" class='button1' onClick='_get_("/boutique/doaction?caction=ask_boutique_vendrepartieplantes");' value="<?=$this->paUtilisationBoutique ?> PA - Vendre">
				<br /><br />
				
				<? $this->typePlantes = $this->typePlantesBruts; ?>
				<?=$this->render("/interface/commun/plantes/plantes.phtml"); ?>
			<? endif; ?>
			<br />
 		</ul>
 	</div>
</div>
<? include("box_bottom.phtml") ?>