<?php include("box_header.phtml") ?>
<div class="inner">

<div class="titre textalic textsizeb">
	<div class="titre textalia" style="position:Absolute">
	</div>
		<?php echo $this->nomLieu ?><br/><br/>
	</div>
	<input type="button" class='button' onclick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la boutique">
 	<div class="contenuC">
 		<div class="box_contenu1 textalic">
			<br />
			
			<?php if ($this->tabac == null) : ?>
				Les prix du marché sont inconnus, la boutique est fermée.<br />
			<?php else: ?>
				<input type="button" class='button' onclick='_get_("/boutique/doaction?caction=ask_boutique_achetertabac");' value="<?php echo $this->paUtilisationBoutique ?> PA - Acheter">
				
				<br /><br />
				Prix de vente des feuilles de tabac
				<br /><br />
				<?php echo $this->render("/interface/commun/tabac/tabac.phtml"); ?>
			<?php endif; ?>
			<br />
 		</div>
 	</div>
</div>
<?php include("box_bottom.phtml") ?>