<? include("box_header.phtml") ?>
<div class="inner">

<div class="titre textalic textsizeb">
	<div class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onclick='_get_("/interface/load/?box=box_lieu");' value="Sortir de la boutique">
	</div>
		<?=$this->nomLieu ?><br/><br/>
	</div>
 	<div class="contenuC">
 		<div class="box_contenu1 textalic">
			<br />
			
			<? if ($this->tabac == null) : ?>
				Les prix du marché sont inconnus, la boutique est fermée.<br />
			<? else: ?>
				<input type="button" class='button1' onclick='_get_("/boutique/doaction?caction=ask_boutique_achetertabac");' value="<?=$this->paUtilisationBoutique ?> PA - Acheter">
				
				<br /><br />
				Prix de vente des feuilles de tabac
				<br /><br />
				<?=$this->render("/interface/commun/tabac/tabac.phtml"); ?>
			<? endif; ?>
			<br />
 		</div>
 	</div>
</div>
<? include("box_bottom.phtml") ?>