<?php include("box_header.phtml") ?>
<div class="inner">
<?php if (Zend_Registry::get("estMobile")) : ?>
	 <div class="titre textalia textsizec">Mon Carnet</div>
<?php else: ?>
	<div id="<?php echo $this->nom_interne ?>Titre" style="display:none"><span class="titrea textalia titreasizee">Mon Carnet</span></div>
<?php endif;?>

  <div class="contenuA">
	  <div class="box_contenu1 textalic">
	  
	<?php if ($this->affichageInterne == true) : ?>
			<br />
			
			<div id='carnet_html'>
			<?php if ($this->carnets != null && count($this->carnets) > 0): ?>
			<br /><br />
			Cliquez sur une note pour l'éditer.<br />
			
				<table class="table_liste" style="width:80%;" >
				<?php 	$i = 0;
					foreach($this->carnets as $c) : ?>
					<tr class="table_liste<?php echo ($i % 2);$i++; ?> hhover"  onclick='_get_("/carnet/doaction?caction=do_carnet_voir&carnet=<?php echo $c["id_carnet"]?>");'>
					<td class="table_liste" style="padding:0px;">
					Note <?php echo $c["id_carnet"]?>
					</td>
	  				<td class="table_liste" style="padding:0px;">
	  				<?php if (mb_strlen($c["texte_carnet"]) > 25) :
	  					echo mb_substr($c["texte_carnet"], 0, 25)."...";
	  					else : 
	  					echo $c["texte_carnet"];
	  					endif;
					?>
	  				</td>
	  				</tr>
				<?php endforeach;?>
				</table>
			<?php else:?>
				Vos n'avez pas encore saisi de note.
			<?php endif;?>
			
			</div>
<br /><br />
	<?php else: ?>
		Chargement en cours
		<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
	<?php endif; ?>
	  </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>