<? include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Ma Charrette</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">
  
    <? if ($this->affichageInterne == true) : ?>
    
    	<? if ($this->user->pa_braldun >=1) : 
	      $attrA = "onClick=\"Javascript:_get_('/charrette/doaction?caction=ask_charrette_attraper');\"";
	      $attrB = "onClick=\"Javascript:_get_('/charrette/doaction?caction=ask_charrette_lacher');\"";
	    else:
	      $attrA = "disabled";
	      $attrB = "disabled";
	    endif;?>
	    
		<input type="button" class='button1' value="1 PA - Attraper une charrette" <?=$attrA?> />
		<input type="button" class='button1' value="1 PA - Lâcher une charrette" <?=$attrB?> />
	   
	    <br /> <br />
	    
	     <? if ($this->possedeCharrette) : ?>
	     
		   <table align="center" width="80%">
		   	<tr>
		   		<td align="center" valign="top">
		   			<div class="titre textalic textsized">Caract&eacute;ristiques</div>
		   			
		   			<?=$this->charrette["nom_charrette"]?> n&deg;<?=$this->charrette["id_charrette"]?>, voir <label class='alabel' onclick='ouvHistoMa("<?=$this->charrette["id_charrette"]?>")'>l'historique</label><br><br>
				   <? Zend_Loader::loadClass("Bral_Helper_Charrette")?>
				   <?=Bral_Helper_Charrette::afficheBarrePoids($this->charrette)?>
				   <?=$this->tabPoidsCharrette["transporte"]?> Kg / <?=$this->tabPoidsCharrette["transportable"]?> Kg transportable.
				   <br><br>
				   <?=Bral_Helper_Charrette::afficheBarreDurabilite($this->charrette)?>
				   Durabilit&eacute; : <?=$this->charrette["durabilite_actuelle"]?> / <?=$this->charrette["durabilite_max"]?>.
		   		</td>
		   		<td align="center" valign="top">
		   			<div class="titre textalic textsized braltip">Partage
		   				<?=Bral_Helper_Tooltip::render("Tous les Braldûns peuvent déposer des éléments dans n'importe quelle  charrette présente sur leur case.<br> Par contre, pour autoriser des Braldûns à piocher dans votre charrette, il vous faut configurer les partages ci-dessous", "Gestion du partage de la Charrette");?>
		   			</div>
		   			Partage avec les Braldûns de la communauté : <?=$this->charrette["est_partage_communaute"]?><br>
		   			Partage avec tous les Braldûns : <?=$this->charrette["est_partage_bralduns"]?><br>
		   			<? if ($this->partageBralduns == null) : ?>
		   				Partage avec aucun autre Braldûn<br><br>
		   			<? else: ?>
		   				Partage avec : <?=$this->partageBralduns?><br><br>
		   			<? endif;?>
		   			
		   			<input type="button" class='button1' value="0 PA - Configurer les partages" onClick="Javascript:_get_('/charrette/doaction?caction=ask_charrette_partage');" />
		   			<? if ($this->possedeSabot) : ?>
		   			<input type="button" class='button1' value="0 PA - Configurer le sabot" onClick="Javascript:_get_('/charrette/doaction?caction=ask_charrette_sabot');" />
		   			<? endif;?>
		   		</td>
		   		<td align="left" valign="top">
		   			<div class="titre textalic textsized">Am&eacute;liorations</div>
		   			
		   			<table class="table_liste" style="width:90%">
					<thead class="table_liste">
					  <tr class="table_liste">
					  	<th>N&deg;</th>
					  	<th>&nbsp;</th>
						<th>Nom</th>
						<th>Caract&eacute;ristiques</th>
					  </tr>
					</thead>
					<tbody>
		   			<? if ($this->materielsAssembles != null && count($this->materielsAssembles) > 0): ?>
		   			<? $i = 0;
		   				Zend_Loader::loadClass("Bral_Helper_DetailMateriel");
				   		foreach($this->materielsAssembles as $e) :?>
						<tr class="table_liste<?=($i % 2);$i++; ?>">
					  		<td class="table_liste"><?=$e["id_materiel"] ?></td>
					  		<td class="table_liste"><img src='/public/styles/braldahim_defaut/images/type_materiel/type_materiel_<?=$e["id_type_materiel"]?>.png' alt="<?=htmlspecialchars($e["nom"]) ?>"/></td>
					  		<td class="table_liste"><?=$e["nom"] ?></td>
					  		<td class="table_liste">
					  			<div class='braltip'>
					  			<?=Bral_Helper_DetailMateriel::afficherTooltip($e);?>
					  			<img src="/public/images/info_icon.gif" />
					  			</div>
					  		</td>
					  	</tr>
						<? endforeach; ?>
					<? else: ?>
						<tr class="table_liste0">
							<td colspan="4">Aucun mat&eacute;riel assembl&eacute;</td>
						</tr>
		   			<? endif;?>
		   			</tbody>
					</table>
		   		</td>
		   	</tr>
		   </table>
		   
		   <br />
			<div class="titre textalic textsized">Contenu de la charrette</div>	   
	   		<? include("commun/poches.phtml") ?>
	
	   <? else: ?>
	   Vous n'avez pas de charrette.
	   <? endif;?>
  <? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
  <? endif; ?>
  
   <br />
   </div>
</div>
</div>
<? include("box_bottom.phtml") ?>