<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Ma Charrette</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">
  
    <?php if ($this->affichageInterne == true) : ?>
    
    	<?php if ($this->user->pa_braldun >=1) : 
	      $attrA = "onclick=\"Javascript:_get_('/charrette/doaction?caction=ask_charrette_attraper');\"";
	      $attrB = "onclick=\"Javascript:_get_('/charrette/doaction?caction=ask_charrette_lacher');\"";
	    else:
	      $attrA = "disabled";
	      $attrB = "disabled";
	    endif;?>
	    
		<input type="button" class='button1' value="1 PA - Attraper une charrette" <?php echo $attrA?> />
		<input type="button" class='button1' value="1 PA - Lâcher une charrette" <?php echo $attrB?> />
	   
	    <br /> <br />
	    
	     <?php if ($this->possedeCharrette) : ?>
	     
		   			<div class="titre textalic textsized">Caract&eacute;ristiques</div>
		   			
		   			<?php echo $this->charrette["nom_charrette"]?> n&deg;<?php echo $this->charrette["id_charrette"]?>, voir <label class='alabel' onclick='ouvHistoMa("<?php echo $this->charrette["id_charrette"]?>")'>l'historique</label><br /><br />
				   <?php Zend_Loader::loadClass("Bral_Helper_Charrette")?>
				   <?php echo Bral_Helper_Charrette::afficheBarrePoids($this->charrette)?>
				   <?php echo $this->tabPoidsCharrette["transporte"]?> Kg / <?php echo $this->tabPoidsCharrette["transportable"]?> Kg transportable.
				   <br /><br />
				   <?php echo Bral_Helper_Charrette::afficheBarreDurabilite($this->charrette)?>
				   Durabilit&eacute; : <?php echo $this->charrette["durabilite_actuelle"]?> / <?php echo $this->charrette["durabilite_max"]?>.
				   
				   <br />
		   			<ul id="navigation" style="width:99%;text-align:left">
	
						<li id="pocheAmelioCharette">
							<?php $poches[] = "pocheAmelioCharette-head" ?>
					      	<h3 id="pocheAmelioCharette-head" class="head" onclick="maccordion(this);">
								Améliorations
							</h3>
							<ul id="pocheAmelioCharette-body" style="display:none">
								<li>
									<table class="table_liste" style="width:90%">
										<thead class="table_liste">
										  <tr class="table_liste">
										  	<th>N&deg;</th>
										  	<th>&nbsp;</th>
											<th>Nom</th>
										  </tr>
										</thead>
										<tbody>
							   			<?php if ($this->materielsAssembles != null && count($this->materielsAssembles) > 0): ?>
							   			<?php $i = 0;
							   				Zend_Loader::loadClass("Bral_Helper_DetailMateriel");
									   		foreach($this->materielsAssembles as $e) :?>
											<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
										  		<td class="table_liste"><?php echo $e["id_materiel"] ?></td>
										  		<td class="table_liste"><img src='<?php echo $this->config->url->static?>/images/type_materiel/type_materiel_<?php echo $e["id_type_materiel"]?>.png' alt="<?php echo htmlspecialchars($e["nom"]) ?>"/></td>
										  		<td class="table_liste">
										  			<div class='braltip'>
										  			<?php echo Bral_Helper_DetailMateriel::afficherTooltip($e);?>
										  			<?php echo $e["nom"] ?>
										  			</div>
										  		</td>
										  	</tr>
											<?php endforeach; ?>
										<?php else: ?>
											<tr class="table_liste0">
												<td colspan="4">Aucun mat&eacute;riel assembl&eacute;</td>
											</tr>
							   			<?php endif;?>
							   			</tbody>
									</table>
								</li>
							</ul>
						</li>
						
						<li id="pochePartageCharette">
							<?php $poches[] = "pochePartageCharette-head" ?>
					      	<h3 id="pochePartageCharette-head" class="head" onclick="maccordion(this);">
								Configurer Partage
							</h3>
							<ul id="pochePartageCharette-body" style="display:none">
								<li>
								
							<div class="titre textalic textsized braltip">Partage
				   				<?php echo Bral_Helper_Tooltip::render("Tous les Braldûns peuvent déposer des éléments dans n'importe quelle  charrette présente sur leur case.<br /> Par contre, pour autoriser des Braldûns à piocher dans votre charrette, il vous faut configurer les partages ci-dessous", "Gestion du partage de la Charrette");?>
				   			</div>
				   			Partage avec les Braldûns de la communauté : <?php echo $this->charrette["est_partage_communaute"]?><br />
				   			Partage avec tous les Braldûns : <?php echo $this->charrette["est_partage_bralduns"]?><br />
				   			<?php if ($this->partageBralduns == null) : ?>
				   				Partage avec aucun autre Braldûn<br /><br />
				   			<?php else: ?>
				   				Partage avec : <?php echo $this->partageBralduns?><br /><br />
				   			<?php endif;?>
				   			
				   			<input type="button" class='button1' value="0 PA - Configurer les partages" onclick="Javascript:_get_('/charrette/doaction?caction=ask_charrette_partage');" />
				   			<?php if ($this->possedeSabot) : ?>
				   			<input type="button" class='button1' value="0 PA - Configurer le sabot" onclick="Javascript:_get_('/charrette/doaction?caction=ask_charrette_sabot');" />
				   			<?php endif;?>
				   			</li>
				   		</ul>
				   		</li>
					</ul>
		   
		   <br />
			<div class="titre textalic textsized">Contenu de la charrette</div>	   
	   		<?php include("commun/poches.phtml") ?>
	
	   <?php else: ?>
	   Vous n'avez pas de charrette.
	   <?php endif;?>
  <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" />
  <?php endif; ?>
  
   <br />
   </div>
</div>
</div>
<?php include("box_bottom.phtml") ?>