<?php Zend_Loader::loadClass('Bral_Helper_Profil'); ?>

<button class="butPersonnage " title="Personnage" onclick='Javascript:boutonCockpit("box_personnage");'
		title="Personnage">
	<?php if (Zend_Registry::get("estWork")) : ?>

	<?php else: ?>
	<img src='<?php echo $this->config->url->static?>/images/vue/braldun_<?php echo $this->user->sexe_braldun ?>_grand.png'/>
	<?php endif;?>

	<table cellspacing="0px" cellpadding="0px">
		<tr>
			<td nowrap>
				<?php echo Bral_Helper_Profil::afficheBarreVie($this->user->pv_restant_braldun, $this->config->game->pv_base, $this->user->vigueur_base_braldun, $this->config->game->pv_max_coef, $this->user->pv_max_bm_braldun, $this->user->duree_prochain_tour_braldun, false, true)?>
			</td>
			<td nowrap>&nbsp;
				<?php echo $this->user->pv_restant_braldun ?>
				/<?php echo ($this->config->game->pv_base + ($this->user->vigueur_base_braldun * $this->config->game->pv_max_coef) + $this->user->pv_max_bm_braldun) ?>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo Bral_Helper_Profil::afficheBarreFaim($this->user->balance_faim_braldun, $this->user->force_bbdf_braldun, true)?>
			</td>
			<td>&nbsp;
				<?php echo $this->user->balance_faim_braldun?> %
			</td>
		</tr>
	</table>
</button>

<button class="butEffets" title="Effets" onclick='Javascript:boutonCockpit("box_effets");' title="Effets">
	Effets
</button>
<button class="butCarnet" title="Carnet" onclick='Javascript:boutonCockpit("box_carnet");' title="Carnet">
	Carnet
</button>
<button class="butMessagerie" title="Messagerie" onclick='Javascript:boutonCockpit("box_messagerie");'
		title="Carnet">&nbsp;</button>
<br/><br/>

<div id="tourCockpit">
	<?php $s = ''; if ($this->user->pa_braldun > 1): $s = 's'; endif;?>	<?php echo $this->user->pa_braldun?>
	Point<?php echo $s?> d'Action restant<?php echo $s?>
	<?php echo Bral_Helper_Profil::afficheBarreTour($this->user, true) ?>
</div>

<?php //echo $this->render("/annonces/speciale.phtml") ?>

<div id=menu_actions>les actions</div>
<input type='hidden' id='nb_valeurs-competencefavorite' name='nb_valeurs-competencefavorite' value='1'>
<input type='hidden' id='valeur_1-competencefavorite' name='valeur_1-competencefavorite' value='-1'><br/>
