<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mon coffre</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
	Vous ne pouvez déposer ou retirer des éléments de votre coffre qu'en étant dans une banque.	
	<br /><br />
	Votre coffre contient plusieurs tiroirs. Cliquez sur celui ou ceux que vous souhaitez ouvrir. 
	<br /><br />
   <? include("commun/poches.phtml") ?>
</div>
<? include("box_bottom.phtml") ?>