<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mon coffre</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">
  <?php if ($this->affichageInterne == true) : ?>
	Vous ne pouvez déposer ou retirer des éléments de votre coffre qu'en étant dans une banque.	
	<br /><br />
	Votre coffre contient plusieurs tiroirs. Cliquez sur celui ou ceux que vous souhaitez ouvrir. 
	<br /><br />
   <?php include("commun/poches.phtml") ?>
  <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
  <?php endif; ?>
</div>
</div>
</div>
<?php include("box_bottom.phtml") ?>