<?php include("box_header.phtml") ?>
<div class="inner">

<?php if ($this->affichageInterne == true) : ?>
 
	 <div class="titre textalia textsizeb">Ma Communaut&eacute;
		<?php if ($this->communaute != null) : ?>
			: <?php echo $this->communaute["nom_communaute"] ?>, 
			n&deg; <?php echo $this->communaute["id_communaute"] ?>
		<?php endif; ?>
	 </div>
	 
	 <div class="contenuC">
     <div class="box_contenu1 textalic">
  	<?php if ($this->communaute != null) : ?>
  		Vous faites partie de la communaut&eacute; <?php echo $this->communaute["nom_communaute"] ?>,
  		 n&deg; <?php echo $this->communaute["id_communaute"] ?> depuis le
  		
  		<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->user->date_entree_communaute_braldun); ?>
  		
  		<br /><br />
  		<input type='button' class='button1' value='Voir le profil public' onclick='ouvrirWin("/voir/communaute/?communaute=<?php echo $this->communaute["id_communaute"] ?>", "Description de la communaut&eacute; n&deg;<?php echo $this->communaute["id_communaute"] ?>");'>
  		<input type='button' class='button1' value='Voir les membres' onclick='_get_("/communaute/doaction?caction=ask_communaute_membres");'>
  		<hr />
  		
  		<?php if ($this->user->rangCommunaute < Bral_Util_Communaute::ID_RANG_NOUVEAU) : ?>
  			<?php include("communaute/batiments.phtml") ?>
  			<hr />
  			<input type='button' class='button1' value='Coffre et Réservations' onclick='_get_("/communaute/doaction?caction=ask_communaute_coffre");'>
  		<?php else: ?>
  			En tant que nouveau membre, vous n'avez pas encore accès à toutes les informations de la communauté.
  		<?php endif; ?>
  		<?php if ($this->user->rangCommunaute <= Bral_Util_Communaute::ID_RANG_ADJOINT) : ?>
  			<br /><br />
  			Vous avez des droits de gestion : <br />
  			<input type='button' class='button1' value='G&eacute;rer les membres' onclick='_get_("/communaute/doaction?caction=ask_communaute_gerermembres");'>
  			<input type='button' class='button1' value='G&eacute;rer les rangs' onclick='_get_("/communaute/doaction?caction=ask_communaute_rangs");'>
  			<input type='button' class='button1' value='Modifier la description / site web' onclick='_get_("/communaute/doaction?caction=ask_communaute_description");'>
  		<?php endif; ?>
  		<?php if ($this->user->rangCommunaute == Bral_Util_Communaute::ID_RANG_GESTIONNAIRE) : ?>
  			<br />
  			Vous &ecirc;tes le gestionnaire  de cette communaut&eacute;, vous avez accès aux actions suivantes : <br />
			<input type='button' class='button1' value='Modifier le Gestionnaire' onclick='_get_("/communaute/doaction?caction=ask_communaute_gestionnaire");'>
  		<?php endif; ?>
  	<?php else : ?>
  		Vous ne faites pas partie d'une communaut&eacute;. <br /><br />
  		Vous pouvez vous rendre dans une mairie pour rentrer dans une communaut&eacute;.
  	<?php endif; ?>
  	
  	<div id="box_communaute_action">
  	</div>

  	<br />
  </div>
   </div>
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
<?php endif; ?>

</div>
<?php include("box_bottom.phtml") ?>