<? include("box_header.phtml") ?>
<div class="inner">

<? if ($this->affichageInterne == true) : ?>
 
	 <div class="titre textalia textsizeb">Ma Communaut&eacute;
		<? if ($this->communaute != null) : ?>
			: <?=$this->communaute["nom_communaute"] ?>, 
			n&deg; <?=$this->communaute["id_communaute"] ?>
		<? endif; ?>
	 </div>
	 <div class="contenuC">
     <div class="box_contenu1 textalic">
  	<? if ($this->communaute != null) : ?>
  		Vous faites partie de la communaut&eacute; <?=$this->communaute["nom_communaute"] ?>,
  		 n&deg; <?=$this->communaute["id_communaute"] ?> depuis le
  		
  		<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->user->date_entree_communaute_braldun); ?>
  		
  		<br /><br />
  		<input type='button' class='button1' value='Voir le profil public' onclick='ouvrirWin("/voir/communaute/?communaute=<?=$this->communaute["id_communaute"] ?>", "Description de la communaut&eacute; n&deg;<?=$this->communaute["id_communaute"] ?>");'>
  		<input type='button' class='button1' value='Voir les membres' onclick='_get_("/communaute/doaction?caction=ask_communaute_membres");'>
  		
  		<? if ($this->estGestionnaire == true) : ?>
  			<br /><br />
  			Vous &ecirc;tes le gestionnaire de cette communaut&eacute;. Vous avez acc&egrave;s aux actions suivantes : <br />
  			<input type='button' class='button1' value='G&eacute;rer les membres' onclick='_get_("/communaute/doaction?caction=ask_communaute_gerermembres");'>
  			<input type='button' class='button1' value='G&eacute;rer les rangs' onclick='_get_("/communaute/doaction?caction=ask_communaute_rangs");'>
  			<input type='button' class='button1' value='Modifier la description / site web' onclick='_get_("/communaute/doaction?caction=ask_communaute_description");'>
			<input type='button' class='button1' value='Modifier le Gestionnaire' onclick='_get_("/communaute/doaction?caction=ask_communaute_gestionnaire");'>
  		<? endif; ?>
  	<? else : ?>
  		Vous ne faites pas partie d'une communaut&eacute;. <br /><br />
  		
  		Vous pouvez vous rendre dans une mairie pour rentrer dans une communaut&eacute;.
  	<? endif; ?>
  	
  	<div id="box_communaute_action">
  	</div>

  	<br />
  </div>
   </div>
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>

</div>
<? include("box_bottom.phtml") ?>