<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizeb">Ma Communaute
	<? if ($this->communaute != null) : ?>
		: <?=htmlentities($this->communaute["nom_communaute"]) ?> 
		n&deg; <?=$this->communaute["id_communaute"] ?>
	<? endif; ?>
</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
  	<? if ($this->communaute != null) : ?>
  		Vous faites partie de la communaut&eacute; <?=htmlentities($this->communaute["nom_communaute"]) ?>,
  		 n&deg; <?=$this->communaute["id_communaute"] ?> depuis le
  		
  		<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->communaute["date_entree_hobbit_communaute"]); ?>
  		
  		<br /><br />
  		<input type='button' class='button1' value='Voir les membres' onClick='_get_("/communaute/doaction?caction=ask_communaute_membres");'>
  		
  		<? if ($this->estCreateur == true) : ?>
  			<br />
  			Vous &ecirc;tes le cr&eacute;ateur de cette communaut&eacute;.<br />
  			<input type='button' class='button1' value='G&eacute;rer les rangs' onClick='_get_("/communaute/doaction?caction=ask_communaute_rangs");'>
  			<input type='button' class='button1' value='Modifier la description' onClick='_get_("/communaute/doaction?caction=ask_communaute_description");'>
  		<? endif; ?>
  	<? else : ?>
  		Vous ne faites pas partie d'une communaut&eacute;. <br /><br />
  		
  		Vous pouvez vous rendre dans une mairie pour rentrer dans une communaut&eacute;.
  	<? endif; ?>
  	
  	<div id="box_communaute_action">
  	
  	</div>
  	<br />
  </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>