<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Comp&eacute;tences de base</ul>
 <div class="contenu">
 <ul class="box_contenu1 textalic">
 <?php 
 if (count($this->competences) > 0) {
 	foreach($this->competences as $c) : ?>
  <ul class="ligne_espace">
      <input type="button" class='button1' value="0 PA - <?=$c["nom"]?>"
        onClick="Javascript:_get_('/competences/DoAction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
  </ul>
 <?php endforeach ;
  } else {	
 	echo "Aucune comp&eacute;tence basique";
  }
 ?>
 </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>