<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Comp&eacute;tences communes</ul>
 <div class="contenuB">
  <ul class="box_contenu1 textalic">
  
<? if ($this->affichageInterne == true) : ?>
	 <?php 
	 if (count($this->competences) > 0) {
	 	foreach($this->competences as $c) : ?>
	  <ul class="ligne_espace">
	      <input type="button" class='button1' value="<?=$c["pa_utilisation"]?> PA - <?=$c["nom"]?><? if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>"
	         onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
	  </ul>
	 <?php endforeach ;
	  } else {	
	 	echo "Aucune comp&eacute;tence commune";
	  }
	 ?>
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
 
 </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>