<? include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mes Comp&eacute;tences de Soule</div>
 <div class="contenuB">
 <div class="box_contenu1 textalic">
 
 <?php 
 if ($this->user->activation == false) {
 	echo "Tour non activé à la connexion";
 } else if ($this->user->est_soule_braldun == "non") {
 	echo "Pas de compétence de soule, aucun match en cours";
 } else if (count($this->competences) > 0) {
 	foreach($this->competences as $c) : ?>
  <div class="ligne_espace">
      <? if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
      		$attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
	    else:
	      $attr = "disabled alt=\"Vous n'avez pas assez de PA\"";
	    endif;?>
	    <input type="button" class='button1' value="<?=$c["pa_texte"]?> PA - <?=$c["nom"]?>" <?=$attr?>>
  </div>
 <?php endforeach ;
  } else {	
 	echo "Aucune comp&eacute;tence de soule";
  }
 ?>
 </div>
 </div>
</div>
<? include("box_bottom.phtml") ?>