<?php if ($this->affichageInterne == false) : ?>
<div class="<?=$this->nom_interne ?>" id="<?=$this->nom_interne ?>" style="display:<?=$this->display; ?>"> 
<?php endif; ?>
 <div class="box_titre1">
  Comp&eacute;tences basiques</div>
 <div class="box_contenu2">
 
 <?php 
 if (count($this->competences) > 0) {
 	foreach($this->competences as $c) : ?>
  <div>
       0 PA -
      <input type="button" value="<?=$c["nom"]?>"
        onClick="Javascript:_get_('/competences/DoAction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
  </div>
 <?php endforeach ;
  } else {	
 	echo "Aucune comp&eacute;tence basique";
  }
 ?>
 </div>
 <?php if ($this->affichageInterne == false) : ?>
</div>
<?php endif; ?>