<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Comp&eacute;tences de Soule</ul>
 <div class="contenuB">
 <ul class="box_contenu1 textalic">
 
 <?php 
 if ($this->user->activation == false) {
 	echo "Tour non activé à la connexion";
 } else if ($this->user->est_soule_hobbit == "non") {
 	echo "Pas de compétence de soule, aucun match en cours";
 } else if (count($this->competences) > 0) {
 	foreach($this->competences as $c) : ?>
  <ul class="ligne_espace">
      <input type="button" class='button1' value="<?=$c["pa_utilisation"]?> PA - <?=$c["nom"]?>"
        onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
  </ul>
 <?php endforeach ;
  } else {	
 	echo "Aucune comp&eacute;tence de soule";
  }
 ?>
 </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>