<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Comp&eacute;tences m&eacute;tiers</ul>
 <div class="contenuB">
  <ul class="box_contenu1 textalic">
 
 <? 
 
if ($this->user->activation == false) :
 	echo "Tour non activé à la connexion";
elseif ($this->affichageInterne == true) : ?>
	 <?php if (count($this->competences) > 0) : ?>
	 
		<ul id="navigation" style="width:100%;">
		<? foreach($this->competences as $m) : ?>
			<li id="menuCompetencesMetier<?=$m["nom_systeme_metier"]?>">
				<h3 id="menuCompetencesMetier<?=$m["nom_systeme_metier"]?>-head" class="head" onClick="maccordion(this);" /><?=$m["nom_metier"]?></h3>
				<ul id="menuCompetencesMetier<?=$m["nom_systeme_metier"]?>-body" style="display:none">
				<? foreach($m["competences"] as $c) : ?>
					<li>
					<input type="button" class='button1' value="<?=$c["pa_utilisation"]?> PA - <?=$c["nom"]?><? if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>"
	       		  onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
					</li>
				<? endforeach; ?>
				</ul>
			</li>
		<? endforeach; ?>
		</ul>
	 
	 <?php 
	  else :	
	 	echo "Aucune comp&eacute;tence m&eacute;tier";
	  endif;
	 ?>
 
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>

 </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>