<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mes Comp&eacute;tences de base</div>
 <div class="contenuB">
 <div class="box_contenu1 textalic">
 
 <?php 
 if ($this->user->activation == false) :
 	echo "Tour non activé à la connexion"; ?>
 <?php elseif ($this->affichageInterne == true) : ?>
	 <?php  if (count($this->competences) > 0) {
 	foreach($this->competences as $c) : ?>
  <div class="ligne_espace">
  <?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
    else:
      $attr = "disabled";
    endif;?>
    <input type="button" class='button1' value="<?php echo $c["pa_texte"]?> PA - <?php echo $c["nom"]?>" <?php echo $attr?>>
  </div>
 <?php endforeach ;
  } else {	
 	echo "Aucune comp&eacute;tence basique";
  }
 ?>
 
 <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/wait.gif" />
<?php endif; ?>

 </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>