<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mes Comp&eacute;tences</div>
 <div class="contenuB">
 <div class="box_contenu1 textalic">
 
 <span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('Favorite')">Favorites</span>  -
 <span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('Basique')">Basiques</span> - 
 <span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('Commune')">Communes</span> - 
 <span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('Soule')">Soule</span><br /><br />
 
 <?php
	if ($this->metiers != null && count($this->metiers) > 0) :
		?>
		 <span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('Métier')">Métier<?php if (count($this->metiers) > 1) : echo 's'; endif;?> : </span>
		<?php 
	 	foreach($this->metiers as $m) : 
	 	if ($this->user->sexe_braldun == 'feminin') :
			$nom_metier = $m["nom_feminin_metier"];
		else:
			$nom_metier = $m["nom_masculin_metier"];
		endif;
 ?>
 	<span class="alabel" onClick="Javascript:$('#idCompetencesTable').dataTable().fnFilter('<?php echo $nom_metier?>')"><?php echo $nom_metier?></span> 
 <?php 
 endforeach;
 endif;
 ?>
 
  <input type='hidden' id='init-competencefavorite' name='init-competencefavorite' value='<?php if ($this->favorites == null || count($this->favorites) <= 0) : echo "false"; else: echo "true"; endif;?>'>
  <input type='hidden' id='filtre-competenceCourant' name='filtre-competenceCourant' value=''>
  <input type='hidden' id='nb_valeurs-competencefavorite' name='nb_valeurs-competencefavorite' value='1'>
  <input type='hidden' id='valeur_1-competencefavorite' name='valeur_1-competencefavorite' value='-1'><br />
	 
  <br /> <br />
 	
 <?php if ($this->user->activation == false) :
 	echo "Tour non activé à la connexion"; ?>
 <?php elseif ($this->affichageInterne == true) : ?>
 
 	
 	<table class="table_liste" style="width:100%" id="idCompetencesTable">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>&nbsp;</th>
		<th>&nbsp;</th>
	  </tr>
	</thead>
	<tbody>
		<?php if (count($this->competences) > 0) :?>
			<?php $i = 0;
			   foreach($this->competences as $m) :?>
			   	<?php foreach($m["competences"] as $c) : ?>
			   		<?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
				      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
				      $css = "alabel";
				    else:
				      $attr = "  ";
				      $css = "";
				    endif;?>
							    
					<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
						<td class="table_liste" onClick="$('#valeur_1-competencefavorite').val('<?php echo $c["id_competence"]?>');_get_('/interfaceaction/doaction?caction=do_interfaceaction_competencefavorite','competencefavorite')">
						
							<?php if (in_array($c["id_competence"], $this->favorites)) : ?>
								<img src="<?php echo $this->config->url->static?>/images/layout/etoile_pleine.png"/>
								<span style="display:none">favorite</span>
							<?php else: ?>
								<img src="<?php echo $this->config->url->static?>/images/layout/etoile_vide.png"/>
							<?php endif;?>
							<span style="display:none"><?php echo $m["nom_onglet"]?></span>
							<span style="display:none"><?php echo $c["pa_texte"]?> PA</span>
							<span style="display:none"><?php echo $m["nom_onglet"]?></span>
						</td>
					  		<td class="table_liste">
				  			<span style="display:none"><?php echo $c["nom"]?></span>
			  				<?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
						      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
						    else:
						      $attr = " disabled ";
						    endif;?>
						    <input type="button" class='button1' value="<?php echo $c["pa_texte"]?> PA - <?php echo $c["nom"]?><?php if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?php echo $attr?>>
				  		</td>
				  	</tr>
				 <?php endforeach; ?>
			<?php endforeach; ?>
		<?php else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune compétence</i></td></tr>
		<?php endif; ?>
	</tbody>
</table>

 <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
<?php endif; ?>

 </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>