<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mes Comp&eacute;tences</div>
 <div class="contenuB">
 <div class="box_contenu1 textalic">
 
 <?php if ($this->user->activation == false) :
 	echo "Tour non activé à la connexion"; ?>
 <?php elseif ($this->affichageInterne == true) : ?>
	 <?php  if (count($this->competences) > 0) :
	 			foreach($this->competences as $m) : ?>
				  <ul id="navigation" style="width:100%;">
						<li id="menuCompetences<?php echo $m["nom_systeme_onglet"]?>">
							<?php if (count($this->competences) > 2): $display = "none"; $css = "head"; else: $display = "block"; $css = "head selected"; endif;?>
							<h3 id="menuCompetences<?php echo $m["nom_systeme_onglet"]?>-head" class="<?php echo $css?>" onclick="maccordion(this);"><?php echo $m["nom_onglet"]?></h3>
							<?php if (count($this->competences) > 2): $display = "none"; else: $display = "block"; endif;?>
							<ul id="menuCompetences<?php echo $m["nom_systeme_onglet"]?>-body" style="display:<?php echo $display?>">
							<?php foreach($m["competences"] as $c) : ?>
								<li>
								<?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
							      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
							    else:
							      $attr = " disabled ";
							    endif;?>
							    <input type="button" class='button1' value="<?php echo $c["pa_texte"]?> PA - <?php echo $c["nom"]?><?php if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?php echo $attr?>>
								</li>
							<?php endforeach; ?>
							</ul>
						</li>
					</ul>
					<?php endforeach; ?>
				 <?php 
			else :	
				echo "Aucune comp&eacute;tence";
			endif;
 	?>
 <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/wait.gif" />
<?php endif; ?>

 </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>