<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Comp&eacute;tences m&eacute;tiers</ul>
 <div class="contenuB">
  <ul class="box_contenu1 textalic">
  
 <?php if (count($this->competences) > 0) : ?>
 
	<input type='hidden' id='menuAncienCompetencesMetier' />
	<ul id="navigation" style="width:100%;">
	<? foreach($this->competences as $m) : ?>
		<li id="menuCompetencesMetier<?=htmlentities($m["nom_systeme_metier"])?>">
			<h3 id="menuCompetencesMetier<?=htmlentities($m["nom_systeme_metier"])?>-head" class="head" onClick="accordion(this, 'menuAncienCompetencesMetier', 'menuVisibleCompetencesMetier')"><?=htmlentities($m["nom_metier"])?></h3>
			<ul id="menuCompetencesMetier<?=$m["nom_systeme_metier"]?>-body" style="display:none">
			<? foreach($m["competences"] as $c) : ?>
				<li>
				<input type="button" class='button1' value="<?=$c["pa_utilisation"]?> PA - <?=htmlentities($c["nom"])?> : <?=$c["pourcentage"]?> % "
       		  onClick="Javascript:_get_('/competences/DoAction?caction=ask_competence_<?=$c["nom_systeme"] ?>')">
				</li>
			<? endforeach; ?>
			</ul>
		</li>
	<? endforeach; ?>
	</ul>
 
 <?php 
  else :	
 	echo "Aucune comp&eacute;tence m&eacute;tier";
  endif;
 ?>
 </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>