<?php if ($this->affichageInterne == false) : ?>
<div class="box_<?=$this->nom_interne ?>" id="box_<?=$this->nom_interne ?>" style="display:<?=$this->display; ?>"> 
<?php endif; ?>
 <div class="box_titre1">
  Comp&eacute;tences communes</div>
 <div class="box_contenu2">
 {foreach name=outer item=competence from=$contenu}
   {* foreach key=key item=item from=$competence *}
  <div>
         {$competence.pa_utilisation} PA -
      <input type="button" value="{$competence.nom}"
         onClick="Javascript:_get_('ask_competence_{$competence.nom_systeme}')">
       - {$competence.pourcentage}%
  </div>
   {/foreach}
 </div>
 <?php if ($this->affichageInterne == false) : ?>
</div>
<?php endif; ?>