<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Gestion des &Eacute;choppes</div>
 <div class="contenuc">
  <div class="box_contenu1 textalic">
  <div id="box_echoppe">
 
<?php if ($this->affichageInterne == true) : ?>
    <?php echo $this->htmlContenu ?>
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" />
<?php endif; ?>

</div>
</div>
</div>
</div>
<?php include("box_bottom.phtml") ?>