<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir de l'&eacute;choppe">
	</ul>
		<?=$this->nomEchoppe ?><br/><br/>
	</ul>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
			<br /><br /><br />
			<? $this->materiels = $this->materielsEtal; ?>
				<?=$this->render("/interface/commun/materiels/materiels.phtml"); ?>
				<br /><br />
			<? if ($this->afficheType == "equipements") :?>
				<? $this->equipements = $this->equipementsEtal; ?>
				<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
			<? else: ?>
				<? $this->potions = $this->potionsEtal; ?>
				<?=$this->render("/interface/commun/potions/potions.phtml"); ?>
			<? endif; ?>
			
			<br />
 		</ul>
 	</div>
</div>
<? include("box_bottom.phtml") ?>