<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul style="text-align:left; position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/lieu");' value="Sortir de l'&eacute;choppe">
	</ul>

&Eacute;choppe de TODO<br/><br/>
</ul>
 <div class="contenuC">
 	<ul class="box_contenu1 textalic">
<br /><br /><br />

TODO ETAL
 	</ul>
<br />
 </div>
</div>
<? include("box_bottom.phtml") ?>