<?php include("box_header.phtml") ?>
<div class="inner">

<?php if (Zend_Registry::get("estMobile")) : ?>
	<div class="titre textalia textsizec">Effets</div>
<?php else: ?>
	<div id="<?php echo $this->nom_interne ?>Titre" style="display:none"><span class="titrea textalia titreasizee">Effets</span></div>
<?php endif;?>

 <div class="contenuC">
  <div class="box_contenu1 textalic">
  
 <?php if ($this->affichageInterne == true) : ?>
 
 	<div class="titre textalic textsized">Potions</div>
 
		<?php $nb = count($this->potions);
		if ($nb > 1) { $s = 's'; $verb = 'ont'; } else { $s =''; $verb = 'a'; }
		?>
		
		<?php if ($nb > 0) :?>
		<?php echo $nb ?> potion<?php echo $s ?> <?php echo $verb?> actuellement de l'effet sur vous.<br />
		
			<table class="table_liste" style="width:90%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>N°</th>
					<th>Potion</th>
					<th>Effet</th>
				  </tr>
				</thead>
				<tbody>
					<?php foreach($this->potions as $e) : ?>
					<tr class="table_liste">
						<td class='alabel' onclick='ouvHistoP("<?php echo $e["potion"]["id_potion"]?>")'>
						n°<?php echo $e["potion"]["id_potion"]?>
						</td>
						<td><?php echo htmlspecialchars($e["potion"]["nom"]) ?> de qualit&eacute; <?php echo htmlspecialchars($e["potion"]["qualite"]) ?>, 
						niveau <?php echo $e["potion"]["niveau"] ?>
						</td>
						<td>
						<?php echo $e["potion"]["bm_effet_potion"] ?> point<?php if ($e["potion"]["bm_effet_potion"]): echo 's'; endif; ?> de <?php echo $e["potion"]["bm_type"] ?> sur <?php echo $e["potion"]["caracteristique"]?>
						et <?php echo $e["potion"]["nb_tour_restant"] ?> tour<?php $s = ''; if ($e["potion"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?php echo $s ?>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php else: ?>
		Aucun effet de potion n'est appliqu&eacute; sur vous actuellement.<br />
		<?php endif;?>
   <br />
   
   <div class="titre textalic textsized">Autres Effets</div>
   
	  	<?php $nb = count($this->effets);?>
		<?php if ($nb > 0) :?>
			<table class="table_liste" style="width:90%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>Effet</th>
				  </tr>
				</thead>
				<tbody>
					<?php foreach($this->effets as $e) : ?>
					<tr class="table_liste">
						<td>
						<?php if ($e["effet"]["caracteristique"] == "PAMARCHER" ||
						       $e["effet"]["caracteristique"] == "STOUT" || 
						       $e["effet"]["caracteristique"] == "TOUR") : ?>
							<?php echo $e["effet"]["texte_calcule_effet_braldun"]?>
						<?php else: ?>
							<?php echo $e["effet"]["bm_effet_braldun"] ?> point<?php if ($e["effet"]["bm_effet_braldun"]): echo 's'; endif; ?> de <?php echo $e["effet"]["bm_type"] ?> sur 
							<?php if ($e["effet"]["caracteristique"] == "ATTDEGDEF") : ?>
								ATT / DEG / DEF
							<?php else: ?>
								<?php echo $e["effet"]["caracteristique"]?>
							<?php endif;?>
						<?php endif;?>
						<?php if ($e["effet"]["caracteristique"] != "TOUR") : ?>
							et <?php echo $e["effet"]["nb_tour_restant"] ?> tour<?php $s = ''; if ($e["effet"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?php echo $s ?>
						<?php endif;?>
						<?php if ($e["effet"]["texte_effet_braldun"]) : ?>
							<br /><i><?php echo $e["effet"]["texte_effet_braldun"]?></i>
						<?php endif;?>
						<?php if ($e["effet"]["actif"] == false):?>
							   Effet non cumulable donc non actif.
						<?php endif;?>
						<hr>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php else: ?>
		Aucun autre effet n'est appliqu&eacute; sur vous actuellement.
		<?php endif;?>
		<br /><br />
   
 <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
<?php endif; ?>
   </div>
</div>
</div>
<?php include("box_bottom.phtml") ?>