<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Effets</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
  
 <? if ($this->affichageInterne == true) : ?>
 
 	<ul class="titre textalic textsized">Potions</ul>
 
		<? $nb = count($this->potions);
		if ($nb > 1) { $s = 's'; $verb = 'ont'; } else { $s =''; $verb = 'a'; }
		?>
		
		<? if ($nb > 0) :?>
		<?=$nb ?> potion<?=$s ?> <?=$verb?> actuellement de l'effet sur vous.<br />
		
			<table class="table_liste" style="width:90%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>N°</th>
					<th>Potion</th>
					<th>Effet</th>
				  </tr>
				</thead>
				<tbody>
					<? foreach($this->potions as $e) : ?>
					<tr class="table_liste">
						<td class='alabel' onclick='ouvHistoP("<?=$e["potion"]["id_potion"]?>")'>
						n°<?=$e["potion"]["id_potion"]?>
						</td>
						<td><?=htmlspecialchars($e["potion"]["nom"]) ?> de qualit&eacute; <?=htmlspecialchars($e["potion"]["qualite"]) ?>, 
						niveau <?=$e["potion"]["niveau"] ?>
						</td>
						<td>
						<?=$e["potion"]["bm_effet_potion"] ?> point<? if ($e["potion"]["bm_effet_potion"]): echo 's'; endif; ?> de <?=$e["potion"]["bm_type"] ?> sur <?=$e["potion"]["caracteristique"]?>
						et <?=$e["potion"]["nb_tour_restant"] ?> tour<? $s = ''; if ($e["potion"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?=$s ?>
						</td>
					</tr>
					<? endforeach; ?>
				</tbody>
			</table>
		<? else: ?>
		Aucun effet de potion n'est appliqu&eacute; sur vous actuellement.<br>
		<? endif;?>
   <br>
   
   <ul class="titre textalic textsized">Autres Effets</ul>
   
	  	<? $nb = count($this->effets);?>
		<? if ($nb > 0) :?>
			<table class="table_liste" style="width:90%">
				<thead class="table_liste">
				  <tr class="table_liste" title="Cliquer pour Trier">
					<th>Effet</th>
				  </tr>
				</thead>
				<tbody>
					<? foreach($this->effets as $e) : ?>
					<tr class="table_liste">
						<td>
						<? if ($e["effet"]["caracteristique"] == "PAMARCHER" ||
						       $e["effet"]["caracteristique"] == "STOUT" || 
						       $e["effet"]["caracteristique"] == "TOUR") : ?>
							<?=$e["effet"]["texte_calcule_effet_braldun"]?>
						<? else: ?>
							<?=$e["effet"]["bm_effet_braldun"] ?> point<? if ($e["effet"]["bm_effet_braldun"]): echo 's'; endif; ?> de <?=$e["effet"]["bm_type"] ?> sur 
							<? if ($e["effet"]["caracteristique"] == "ATTDEGDEF") : ?>
								ATT / DEG / DEF
							<? else: ?>
								<?=$e["effet"]["caracteristique"]?>
							<? endif;?>
						<? endif;?>
						<? if ($e["effet"]["caracteristique"] != "TOUR") : ?>
							et <?=$e["effet"]["nb_tour_restant"] ?> tour<? $s = ''; if ($e["effet"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?=$s ?>
						<? endif;?>
						<? if ($e["effet"]["texte_effet_braldun"]) : ?>
							<br></i><?=$e["effet"]["texte_effet_braldun"]?></i>
						<? endif;?>
						<? if ($e["effet"]["actif"] == false):?>
							   Effet non cumulable donc non actif.
						<? endif;?>
						<hr>
						</td>
					</tr>
					<? endforeach; ?>
				</tbody>
			</table>
		<? else: ?>
		Aucun autre effet n'est appliqu&eacute; sur vous actuellement.
		<? endif;?>
		<br><br>
   
 <? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
   </ul>
</div>
</div>
<? include("box_bottom.phtml") ?>