<? include("box_header.phtml");
Zend_Loader::loadClass("Bral_Helper_DetailEquipement");
?>
<div class="inner">
<ul class="titre textalia textsizeb">Mon Equipement</ul>
 <div class="contenuA">
  <ul class="box_contenu1 textalic">
 
 <? if ($this->affichageInterne == true) : ?>
 
   &Eacute;quipement pr&eacute;sent sur vous : <br />

	<table align="center" border="0">
	  <tr>
	    <td>
	 	<table align="center" border='1'>
	 	
	 	<? foreach($this->typesEmplacement as $k => $e) : ?>
	 		<? if ($e["position"] == "gauche" && $e["affiche"] == "oui") : ?>
	 		<tr>
	 			<td class="equipement">
	 			<?=htmlentities($e["nom_type_emplacement"]) ?><br />
	 			<? if (count($e["equipementPorte"]) > 0): ?>
					<? foreach($e["equipementPorte"] as $p) : ?>
						<? echo Bral_Helper_DetailEquipement::afficher($p); ?>
 					<? endforeach; ?>
 				<? else : ?>
 					Libre
	 			<? endif;  ?>
	 			</td>
	 		</tr>
	 		<? endif; ?>
	 	<?  endforeach; ?>
	 	</table>
	  </td>
	  <td>
	 	<table align="center" border="1">
	 		<tr>
	 	<? 	$i = 0;
	 		foreach($this->typesEmplacement as $k => $e) : ?>
	 		<? if ($e["position"] == "droite" && $e["affiche"] == "oui") : 
	 			$i++;
	 			if ($e["position"] == "deuxmains") {
	 				$i++;
	 			}
	 			?>
	 			<td class="equipement">
	 			<?=htmlentities($e["nom_type_emplacement"]) ?><br />
	 			<? if (count($e["equipementPorte"]) > 0): ?>
					<? foreach($e["equipementPorte"] as $p) : ?>
 						<? echo Bral_Helper_DetailEquipement::afficher($p); ?>
 					<? endforeach; ?>
	 			<? endif;  ?>
	 			</td>
	 		<? endif; ?>
	 	<?  endforeach; ?>
	 		<? if ($i == 1) : ?>
	 			<td class="equipement">1 main de libre</td>
	 		<? else : ?>
	 			<td class="equipement">2 mains de libres</td>
	 		<? endif;?>
	 	  </tr>
	 	</table>
	  </td>
	 </tr>
    </table>
  	
 <? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>

   </ul>
</div>
</div>
<? include("box_bottom.phtml") ?>