<? include("box_header.phtml");
Zend_Loader::loadClass("Bral_Helper_ProfilEquipement");
?>
<div class="inner">
<ul class="titre textalia textsizec">Mon &Eacute;quipement</ul>
 <div class="contenuA">
  <ul class="box_contenu1 textalic">
 
 <? if ($this->affichageInterne == true) : ?>
 
   &Eacute;quipement pr&eacute;sent sur vous : <br />

	<table>
	<tr>
	<td><img src='/public/styles/braldahim_defaut/images/vue/braldun_<?=$this->user->sexe_braldun?>_grand.png'"/></td>
	
	<td><?=Bral_Helper_ProfilEquipement::afficher($this->typesEmplacement); ?></td>
	</tr>
	</table>
	
  	
 <? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>

   </ul>
</div>
</div>
<? include("box_bottom.phtml") ?>