Une erreur est survenue : <br />


<div id="erreur_message_static" style="display:block" onClick="javascript:switch2div('erreur_message_static','erreur_message_form');">
<?=$this->messageErreur ?>
</div>
<div id="erreur_message_form" style="display:none">
<textarea id="message_erreur" rows=15 cols=60><?=$this->messageErreur ?>
</textarea>
</div>


<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('erreur_message_static','erreur_message_form');">
<input type='button' class='button1' value='Fermer' onClick='_get_("/interface/clear");Modalbox.hide();'>
