Une erreur est survenue : <br />


<div id="erreur_message_static" style="display:block" onclick="javascript:switch2div('erreur_message_static','erreur_message_form');">
<?php echo $this->messageErreur ?>
</div>
<div id="erreur_message_form" style="display:none">
<textarea id="message_erreur" rows=15 cols=60><?php echo $this->messageErreur ?>
</textarea>
</div>


<input type='button' class='button' value='Copier' onclick="javascript:switch2div('erreur_message_static','erreur_message_form');">
<input type='button' class='button' value='Fermer' onclick='document.location.href="/interface/";'>
