<?php include("box_header.phtml") ?>
<div class="inner">

<div class="titre textalia textsizeb">Mes &Eacute;v&eacute;nements</div>
 
 <?php if ($this->affichageInterne == true) : ?>
	 <?php 
	 $this->estCommunaute = false;
	 ?>
	 
	 <div class="contenuC">
	 
	<table style="padding:0px;border-spacing:0px;width:100%">
		<tr>
		<td width="50%" valign="top"> 
			<?php include("evenements/publiques.phtml") ?>
		</td>
		<td width="50%" valign="top">
			<?php include("evenements/bot.phtml") ?>
		</td>
		</tr>
		</table>
	</div>
<?php else: ?>
	<div class="box_contenu1 textalic">
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" />
	</div>
<?php endif; ?>

</div>
<?php include("box_bottom.phtml") ?>