<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizeb">Mes &Eacute;v&egrave;nements</ul>
 <div class="contenu">
  <ul class="box_contenu1 textalic">
  	Type:
  	<select name='valeur_2'  onChange="Javascript:_get_('<?=$this->baseUrl ?>/interface/evenements?caction=box_evenements&valeur_1=f&valeur_2='+ this.value + '&valeur_3=0')">
  	<? foreach ($this->typeEvenements as $t) : ?>
  	<option value='<?=$t["id_type_evenement"]?>' <?if ($this->filtre == $t["id_type_evenement"]){echo "selected";}?>><?=htmlentities($t["nom"])?></option>
  	<? endforeach; ?>
  	</select>
  	<br>
  	<? if ($this->nbEvenements > 0): ?>
	  	<ul class="mtable">
	  	<? foreach($this->evenements as $e): ?>
	  		<li class="row">
	  			<dl>
	  				<dd class="date_evenement"><?=$e["date"]?></dd>
	  				<dd class="type_evenement"><?=htmlentities($e["type"])?></dd>
	  				<dd class="detail_evenement"><?=htmlentities($e["details"])?>&nbsp;</dd>
	  			</dl>
	  		</li>
	  	<? endforeach; ?>
	  	</ul>
   <? else: ?>
   		Aucun &eacute;v&egrave;nement
   <? endif; ?>
   <br><br>
   <? if ($this->precedentOk === true) : ?>
   <input type="button" class='button1' onClick="Javascript:_get_('<?=$this->baseUrl ?>/interface/evenements?caction=box_evenements&valeur_1=p&valeur_2=<?=$this->filtre ?>&valeur_3=<?=$this->page ?>&valeur_4=<?=$this->filtre?>')" value="Page pr&eacute;c&eacute;dente">
   <? endif; ?>
   <? if ($this->suivantOk === true) : ?>
   <input type="button" class='button1' onClick="Javascript:_get_('<?=$this->baseUrl ?>/interface/evenements?caction=box_evenements&valeur_1=s&valeur_2=<?=$this->filtre ?>&valeur_3=<?=$this->page ?>&valeur_4=<?=$this->filtre?>')" value="Page suivante">
   <? endif; ?>
   
  </ul>
 </div>
</ul>
</div>
<? include("box_bottom.phtml") ?>