<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Ma Famille</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">
  
 <?php if ($this->affichageInterne == true) : ?>
 
 <table>
	<tr>
	<td><img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/famille.png'"/></td>
	
	<td>
		<?php if ($this->pereMereOk === true) :?>
	  		Suite &agrave; l'heureuse rencontre entre votre m&egrave;re 
	  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->user->id_fk_mere_braldun ?>');">
	  		<?php if ($this->mere == null): ?>
	  			Braldun inconnue (n&deg;<?php echo $this->user->id_fk_mere_braldun ?>)
	  		<?php else : ?>
	  			<?php if ($this->mereAncienne) : ?>
	  				<?php echo $this->mere->prenom_ancien_braldun ?> <?php echo $this->mere->nom_ancien_braldun ?>
	  			<?php else: ?>
	  				<?php echo $this->mere->prenom_braldun ?> <?php echo $this->mere->nom_braldun ?>
	  			<?php endif;?>
	  			(n&deg;<?php echo $this->user->id_fk_mere_braldun ?>)
	  		<?php endif;?>
	  		</a>
		  	et votre p&egrave;re
	  		<a title="Voir le profil" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->user->id_fk_pere_braldun ?>');">
	  		<?php if ($this->pere == null): ?>
	  			Braldun inconnu (n&deg;<?php echo $this->user->id_fk_pere_braldun ?>)
	  		<?php else : ?>
	  			<?php if ($this->pereAncien) : ?>
	  				<?php echo $this->pere->prenom_ancien_braldun ?> <?php echo $this->pere->nom_ancien_braldun ?>
	  			<?php else: ?>
	  				<?php echo $this->pere->prenom_braldun ?> <?php echo $this->pere->nom_braldun ?>
	  			<?php endif;?>
	  			(n&deg;<?php echo $this->user->id_fk_pere_braldun ?>)
	  		<?php endif;?>
	  		</a>
		    		
	  	vous &ecirc;tes n&eacute;<?php if ($this->user->sexe_braldun == 'feminin') echo "e"?> le <?php echo $this->dateNaissance ?>.
	  	
	  	<?php else: ?>
	  	Vous &ecirc;tes n&eacute;<?php if ($this->user->sexe_braldun == 'feminin') echo "e"?> orphelin<?php if ($this->user->sexe_braldun == 'feminin') echo "e"?> le <?php echo $this->dateNaissance ?>
	  	<?php endif; ?>
	    <br /><br />
	
		<?php if ($this->nbEnfants == 0 && $this->conjoint == null) :?>
	    	Vous n'avez ni enfant, ni conjoint<?php if ($this->user->sexe_braldun != 'feminin') echo "e"?>.
	    <?php else : ?>
	    	Avec votre conjoint<?php if ($this->user->sexe_braldun != 'feminin') echo "e"?>
	    	<?php if ($this->conjoint != null) : ?>
		    	<a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->conjoint["id_braldun"] ?>');">
		    		<?php echo $this->conjoint["prenom"] ?> <?php echo $this->conjoint["nom"] ?> (n&deg;<?php echo $this->conjoint["id_braldun"] ?>)</a>,
		    <?php else: ?>
		    	disparu<?php if ($this->user->sexe_braldun != 'feminin') echo "e"?>
		    <?php endif; ?>
	    	 vous avez eu <?php echo $this->nbEnfants ?> enfant<?php if ($this->nbEnfants > 1) echo 's' ?>.<br />
	    <?php endif; ?>
	</td>
	</tr>
	</table>
	
	<?php if ($this->nbEnfants > 0) : ?>
    	<table class="table_liste" style="width:80%">
			<thead class="table_liste">
			  <tr class="table_liste" title="Cliquer pour Trier">
				<th>Braldun</th>
				<th>Naissance</th>
			  </tr>
			</thead>
			<tbody>
				<?php foreach($this->enfants as $e) :?>
				<tr class="table_liste">
					<td><a title="Voir le profil" href="#" onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $e["id_braldun"] ?>');"><?php echo $e["prenom"] ?> <?php echo $e["nom"] ?> (n&deg;<?php echo $e["id_braldun"]?>)</a></td>
					<td nowrap>n&eacute;<?php if ($e["sexe_braldun"] == 'feminin') echo "e"?> le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$e["date_naissance"] );?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php endif; ?>
	
    
    
    
   <br />
   
 <?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
<?php endif; ?>
   </div>
</div>
</div>
<?php include("box_bottom.phtml") ?>