<?php include("box_header.phtml") ?>
<div class="inner">

<div class="titre textalic textsizeb">
		<?php echo $this->nomLieu ?><br/><br/>
	</div>
	
 	<div class="contenuC">
 		<div class="box_contenu1 textalic">
 		<input type="button" class='button1' onclick='_get_("/interface/load/?box=box_lieu");' value="Sortir de l'Hôtel des Ventes">
			<br /><br /><br />
			<?php echo $this->htmlContenu?>
			<br />
 		</div>
 	</div>
</div>
<?php include("box_bottom.phtml") ?>