<?php include("box_header.phtml") ?>
<div class="inner">

	<?php if ($this->affichageInterne == true) : ?>

		<?php if ($this->estMobile) : ?>
			<div id="box_vue"></div>
		<?php else : ?>
			<div id="box_vue"></div>
		<?php endif; ?>

	<?php else: ?>
	Chargement en cours
	<br/><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif"/>
	<?php endif; ?>

</div>
<?php include("box_bottom.phtml") ?>