<?php include("box_header.phtml") ?>
<div class="inner">


	Intégration de la vue Braldop en cours. Ce que vous voyez n'est pas votre vue.
	<br />

	<div id=layer_list>
		<input type=checkbox id="layer_satellite"><label for=layer_satellite>Photo Satellite</label>
		<br><input type=checkbox id="layer_nomsLieux"><label for=layer_nomsLieux>Noms des lieux</label>
		<br><input type=checkbox id="layer_régions"><label for=layer_régions>Régions</label>
	</div>
	<div id=map>
		<canvas id=map_canvas></canvas>
	</div>
	<div id=posmark>-</div>


</div>
<?php include("box_bottom.phtml") ?>