<?php include("box_header.phtml") ?>
<div class="inner">


	Intégration de la vue Braldop en cours.
	<br/>Attention, sur cette vue, il n'y a pas tous les éléments présents dans votre
	vue.
	<br/>
	Ce n'est pas pas défaut centré sur votre vue.<br/>
	<br/>
	Développement en cours. Pour toutes remarques / questions, c'est ici : <a
		href="http://forum.braldahim.com/viewtopic.php?f=30&t=1236">http://forum.braldahim.com/viewtopic.php?f=30&t=1236</a>.
	<br/><br/>

	<div id=layer_list>
		<input type=checkbox id="layer_satellite"><label for=layer_satellite>Photo Satellite</label>
		<br><input type=checkbox id="layer_régions"><label for=layer_régions>Régions</label>
	</div>
	<div id=map>
		<canvas id=map_canvas></canvas>
        <div id=map_dialog></div>
	</div>
	<div id=posmark>-</div>


</div>
<?php include("box_bottom.phtml") ?>