<?php include("box_header.phtml") ?>
<div class="inner">

<?php if ($this->affichageInterne == true) : ?>

	<?php if ($this->estMobile) : ?>
		<div id="box_vue"></div>
		<?php include("box_onglets.phtml") ?>
	<?php else : ?>
	<table>
		<tr>
			<td valign='top'>
				<div id="box_vue"></div>
			</td>
			<td valign='top'>
				<?php include("box_onglets.phtml") ?>		
			</td>
		</tr>
	</table>
	<?php endif;?>
	
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" />
<?php endif; ?>

</div>
<?php include("box_bottom.phtml") ?>