<?php include("box_header.phtml") ?>
<div class="inner">

	<input type="hidden" id="positionX" value="<?php echo $this->user->x_braldun ?>"/>
	<input type="hidden" id="positionY" value="<?php echo $this->user->y_braldun ?>"/>

	<div class="verte" style="position: relative;">

		<div id=layer_list>
			<input type=checkbox id="layer_satellite"><label for=layer_satellite>Photo Satellite</label><br/>
			<input type=checkbox id="layer_régions"><label for=layer_régions>Régions</label><br/>
			<input type=checkbox id="layer_fog"><label for=layer_fog>Brouillard de guerre</label><br/>
			<input type=checkbox id=layer_grid><label for=layer_grid>Grille</label><br>
			<span id=choix_profondeur></span><br/>
			<button id="btnCentrer" class="button">Centrer</button>
			<br/>

			<br/><br/>
			Développement en cours.
			<br/>
			<a href="http://forum.braldahim.com/viewtopic.php?f=30&t=1236">Remarques / questions</a>.
			<br/><br/>

		</div>

		<div id=map>
			<canvas id=map_canvas></canvas>
			<div id=map_dialog></div>
			<span id=posmark>-</span>
		</div>


	</div>

</div>
<?php include("box_bottom.phtml") ?>