<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mon Laban, besace du hobbit</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
  
<? if ($this->affichageInterne == true) : ?>
	Votre laban contient plusieurs poches. Cliquez sur celle(s) que vous souhaitez ouvrir. <br /><br />
    <? include("commun/poches.phtml"); ?>
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>

  </ul>
</div>
</div>
<? include("box_bottom.phtml") ?>