
   <div class="laban">
   <? if ($this->nb_runes == 0) : ?>
   	Aucun &eacute;quipement
   <? else : ?>
    <? if ($this->nb_equipements==1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_equipements?> &eacute;quipement<?=$s?> : <br>
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->equipements as $e) : 
     	 if ($i % 3 == 0) echo "<tr>"; 
    	?>
    	<td>
    		<?=htmlentities($e["nom"]) ?> : qualit&eacute; <?=htmlentities($e["qualite"]) ?>,
			 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table> 
    <? endif; ?>
   </div>
   <br/>
