<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mon Laban</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
   Castars : <?=$this->user->castars_hobbit ?><br />
   <hr>
   <div class="laban_plante">
   <? if ($this->nb_partieplantes > 0) : ?>
    <? if ($this->nb_partieplantes==1):$s=''; else:$s='s';endif; ?>
    &eacute;l&eacute;ment<?=$s?> (brut<?=$s?>) de plantes : <br />
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->partieplantes as $p) : 
    	 
    	if ($i % 3 == 0) echo "<tr>"; 
    	 
    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br />"; 
    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br />"; 
    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite"])."<br />";
    	$titre = htmlentities($p["nom_plante"])." : ".htmlentities($p["nom_type"]);
    	?>
    	<td <?=Bral_Helper_Tip::jsTip($textPlante, $titre) ?>>
    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite"]?> <?=htmlentities($p["nom_type"])?><?if ($p["quantite"]>0) echo "s"; ?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table>
   <? endif; ?>
   
    <? if ($this->nb_partieplantesPreparees > 0) : ?>
    <? if ($this->nb_partieplantesPreparees==1):$s=''; else:$s='s';endif; ?>
    &eacute;l&eacute;ment<?=$s?> (pr&eacute;par&eacute;<?=$s?>) de plantes : <br />
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->partieplantesPreparees as $p) : 
    	 
    	if ($i % 3 == 0) echo "<tr>"; 
    	 
    	$textPlante = "Plante : ".htmlentities($p["nom_plante"]). "<br />"; 
    	$textPlante = "Partie : ".htmlentities($p["nom_type"]). "<br />"; 
    	$textPlante .= "Quantit&eacute; : ".htmlentities($p["quantite"])."<br />";
    	$titre = htmlentities($p["nom_plante"])." : ".htmlentities($p["nom_type"]);
    	?>
    	<td <?=Bral_Helper_Tip::jsTip($textPlante, $titre) ?>>
    		<?=htmlentities($p["nom_plante"])?> : <?=$p["quantite"]?> <?=htmlentities($p["nom_type"])?><?if ($p["quantite"]>0) echo "s"; ?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table>
   <? endif; ?>
   </div>
   
   <div class="laban_minerai">
   <? if ($this->nb_minerais == 0) : ?>
   	Aucun minerai
   <? else : ?>
    <? if ($this->nb_minerais==1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_minerais?> minerai<?=$s?> : <br />
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->minerais as $m) : 
     	 if ($i % 3 == 0) echo "<tr>"; 
    	?>
    	<td>
    		<?=htmlentities($m["type"])?> - Brut : <?=$m["quantiteBrut"]?>, Lingot : <?=$m["quantiteLingot"]?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table> 
    <? endif; ?>
   </div>
   <br />
   <div class="laban">
   	Peau : <?=$this->laban["nb_peau"] ?>
   	<br />
   	Viande fra&icirc;che: <?=$this->laban["nb_viande"] ?>, Viande pr&eacute;par&eacute;e <?=$this->laban["nb_viande_preparee"] ?> 
    <br />
    Ration : <?=$this->laban["nb_ration"] ?>
    <br />
    Cuir : <?=$this->laban["nb_cuir"] ?>
    <br />
    Fourrure : <?=$this->laban["nb_fourrure"] ?>
    <br />
    Planche : <?=$this->laban["nb_planche"] ?>
   </div>
   <br />
   
   <div class="laban">
   <? if ($this->nb_runes == 0) : ?>
   	Aucune rune
   <? else : ?>
    <? if ($this->nb_runes==1):$s=''; else:$s='s';endif; ?>
    <?=$this->nb_runes?> rune<?=$s?> : <br />
    
    <table width='100%'>
    <? $i = 0;
      foreach ($this->runes as $r) : 
     	 if ($i % 3 == 0) echo "<tr>"; 
    	?>
    	<td>
    		<? if ($r["est_identifiee"] == 'oui'): ?>
    			<? if ($r["image"] != ""): ?>
    				<img src="/public/images/runes/<?=$r["image"]?>"  class="rune" title="<?=$r["type"]?> n&deg;<?=$r["id_rune"]?> : <?=htmlentities(addslashes($r["effet_type_rune"])) ?>" alt="<?=$r["type"]?> n&deg;<?=$r["id_rune"]?>"  />
    			<? else: ?>
	    			<?=$r["type"]?> (<?=$r["id_rune"]?>)
	    		<? endif; ?>
    		<? else: ?>
    			rune n&deg;<?=$r["id_rune"]?> non identifi&eacute;e
    		<? endif; ?>
    	</td>
    	<? if ($i % 3 == 2) echo "</tr>"; 
    	$i++; 
     endforeach;
     if  ($i % 3 != 0) echo "</tr>"; 
     ?>
    </table> 
    <? endif; ?>
   </div>
   <br/>
   
   <? include("laban_equipement.phtml") ?>
   <br/>
   <? include("laban_potion.phtml") ?>
   </ul>
</div>
</div>
<? include("box_bottom.phtml") ?>