<?php include("box_header.phtml") ?>
<div class="inner">
  <div class="titre textalia textsizec">Lieu actuel</div>
  <div class="titre textalib textsizeb"><?php echo $this->nomTypeLieu; ?></div>
  <div class="contenuC">
    <div class="box_contenu1 textalic">
    
<?php if ($this->affichageInterne == true) : ?>
    
 	<?php if ($this->estLieuCourant === true) : ?>
 		Vous vous trouvez sur un lieu particulier !
 		
 		<?php if ($this->estFranchissableLieu === true && $this->estAlterableLieu === true) : ?>
 			Ce lieu est franchissable et alt&eacute;rable
 		<?php elseif ($this->estFranchissableLieu === true && $this->estAlterableLieu === false) : ?>
 			Ce lieu est franchissable mais n'est pas alt&eacute;rable
		<?php elseif ($this->estFranchissableLieu === false && $this->estAlterableLieu === true) : ?>
 			Ce lieu n'est pas franchissable et il est alt&eacute;rable
 		<?php else: ?>
 			Ce lieu n'est ni franchissable, ni alt&eacute;rable
 		<?php endif; ?>
 		
 		 <br /><br />
 		<div class="titre textalic textsizec"><?php echo $this->nomLieu ?></div>
 		<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/<?php echo $this->nomImageLieu?>.png' />
 		<br /><br />
 		<table width='80%' align='center'>
 		<tr><td style='text-align:justify'><?php echo nl2br($this->descriptionLieu); ?>
 		</td></tr>
 		</table>
 		
 		<?php if ($this->user->activation == true) :?>
 			<?php echo $this->htmlLieu?>
 		<?php else: ?>
 			Détails non affichés, Tour non activé à la connexion
 		<?php endif;?>
 	<?php else: ?>
 	Le lieu o&ugrave; vous vous trouvez n'a rien de particulier
 	<?php endif; ?>
 
 	<br /><br />
 	<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
<?php endif; ?>
 	</div>
   </div>
 </div>
<?php include("box_bottom.phtml") ?>