<? include("box_header.phtml") ?>
<div class="inner">
  <div class="titre textalia textsizec">Lieu actuel</div>
  <div class="titre textalib textsizeb"><?=$this->nomTypeLieu; ?></div>
  <div class="contenuC">
    <div class="box_contenu1 textalic">
    
<? if ($this->affichageInterne == true) : ?>
    
 	<? if ($this->estLieuCourant === true) : ?>
 		Vous vous trouvez sur un lieu particulier !
 		
 		<? if ($this->estFranchissableLieu === true && $this->estAlterableLieu === true) : ?>
 			Ce lieu est franchissable et alt&eacute;rable
 		<? elseif ($this->estFranchissableLieu === true && $this->estAlterableLieu === false) : ?>
 			Ce lieu est franchissable mais n'est pas alt&eacute;rable
		<? elseif ($this->estFranchissableLieu === false && $this->estAlterableLieu === true) : ?>
 			Ce lieu n'est pas franchissable et il est alt&eacute;rable
 		<? else: ?>
 			Ce lieu n'est ni franchissable, ni alt&eacute;rable
 		<? endif; ?>
 		
 		 <br /><br />
 		<div class="titre textalic textsizec"><?=$this->nomLieu ?></div>
 		<img src='<?=$this->config->static->url?>/styles/braldahim_defaut/images/vue/<?=$this->nomImageLieu?>.png' />
 		<br /><br />
 		<table width='80%' align='center'>
 		<tr><td style='text-align:justify'><?=nl2br($this->descriptionLieu); ?>
 		</td></tr>
 		</table>
 		
 		<? if ($this->user->activation == true) :?>
 			<?=$this->htmlLieu?>
 		<? else: ?>
 			Détails non affichés, Tour non activé à la connexion
 		<? endif;?>
 	<? else: ?>
 	Le lieu o&ugrave; vous vous trouvez n'a rien de particulier
 	<? endif; ?>
 
 	<br /><br />
 	<? else: ?>
	Chargement en cours
	<br /><img src="<?=$this->config->static->url?>/images/wait.gif" />
<? endif; ?>
 	</div>
   </div>
 </div>
<? include("box_bottom.phtml") ?>