<div id=menu_actions>

		<br /><center><b>Mes Actions</b></center>
			<div id=titre_resultats_recherche>
			<input type="checkbox" id="actions_onoff" checked="checked" /><label id="actions_onoff_label" for="actions_onoff">Toutes</label>
			<input id=actionneur placeholder="Recherche" size=15><img id=clear_action src="<?php echo $this->config->url->static?>/images/layout/clear-left-icone.png"></div><div id=resultats_recherche></div>
		<div id=liste_actions></div>
	</div>