<div id=menu_actions>
	<br />
	<span id="actions_onoff" for="actions_onoff" title="Cliquez pour afficher que vos actions actives en fonction de vos PA, ou toutes vos actions">Toutes mes actions</span>
			<div id=titre_resultats_recherche>Recherche

			<input id=actionneur placeholder="Nb PA ou libellé" size=15><img id=clear_action src="<?php echo $this->config->url->static?>/images/layout/clear-left-icone.png"></div><div id=resultats_recherche></div>
		<div id=liste_actions></div>
	</div>