<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizeb">Mes messages</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">

<span style="cursor:pointer;" title="Nouveau Message" onClick='Javascript:_get_("/interface/load/?box=box_messagerie");'>
<img src="/public/images/uddeim/menu_inbox.gif" alt="Reçus"> Reçus
</span> - 

<span style="cursor:pointer;" title="Nouveau Message" onClick='Javascript:_get_("/interface/load/?box=box_messagerie&valeur_4=<?=$this->config->messagerie->message->type->envoye ?>");'>
<img src="/public/images/uddeim/menu_outbox.gif" alt="Envoy&eacute;s" border="0"> Envoy&eacute;s
</span> - 

<span style="cursor:pointer;" title="Nouveau Message" onClick='Javascript:_get_("/interface/load/?box=box_messagerie&valeur_4=<?=$this->config->messagerie->message->type->supprime ?>");'>
<img src="/public/images/uddeim/menu_trashcan.gif" alt="Corbeille" border="0"> Corbeille
</span> - 

<span style="cursor:pointer;" title="Nouveau Message" onClick='Javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=nouveau");'>
<img src="/public/images/uddeim/menu_new.gif" alt="Nouveau" border="0"> 
Nouveau</span>

<br />
<div id='messagerie_message'>
	<? if ($this->affichageInterne == true) : ?>
	   	<? include("messagerie/messages.phtml") ?>
	<? else: ?>
		Chargement en cours
		<br /><img src="/public/images/wait.gif" />
	<? endif; ?>
</div>

  </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>