<? include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizeb">Mes messages</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">

<span style="cursor:pointer;" title="Messages reçus" onclick='Javascript:_get_("/interface/load/?box=box_messagerie");'>
<img src="/public/images/uddeim/menu_inbox.gif" alt="Reçus"> Reçus
</span> &nbsp;&nbsp;

<span style="cursor:pointer;" title="Messages envoy&eacute;s" onclick='Javascript:_get_("/interface/load/?box=box_messagerie&valeur_4=<?=$this->config->messagerie->message->type->envoye ?>");'>
<img src="/public/images/uddeim/menu_outbox.gif" alt="Envoy&eacute;s" border="0"> Envoy&eacute;s
</span> &nbsp;&nbsp;

<span style="cursor:pointer;" title="Messages archivés" onclick='Javascript:_get_("/interface/load/?box=box_messagerie&valeur_4=<?=$this->config->messagerie->message->type->archive ?>");'>
<img src="/public/images/uddeim/menu_archive.gif" alt="Reçus"> Archivés
</span> &nbsp;&nbsp;

<span style="cursor:pointer;" title="Corbeille" onclick='Javascript:_get_("/interface/load/?box=box_messagerie&valeur_4=<?=$this->config->messagerie->message->type->supprime ?>");'>
<img src="/public/images/uddeim/menu_trashcan.gif" alt="Corbeille" border="0"> Corbeille
</span> &nbsp;&nbsp;

<span style="cursor:pointer;" title="Contacts" onclick='Javascript:_get_("/messagerie/askaction?caction=do_messagerie_contacts&valeur_1=liste");'>
<img src="/public/images/uddeim/menu_book.gif" alt="Contacts" border="0"> 
Contacts</span> &nbsp;&nbsp;

<span style="cursor:pointer;" title="Nouveau Message" onclick='Javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=nouveau");'>
<img src="/public/images/uddeim/menu_new.gif" alt="Nouveau" border="0"> 
Nouveau</span>

<br />
<div id='messagerie_contenu'>
	<? if ($this->affichageInterne == true) : ?>
	   	<? include("messagerie/messages.phtml") ?>
	<? else: ?>
		Chargement en cours
		<br /><img src="/public/images/wait.gif" />
	<? endif; ?>
</div>

  </div>
 </div>
</div>
<? include("box_bottom.phtml") ?>