<? include("box_header.phtml") ?>
<div class="inner">
  <ul class="titre textalia textsizeb">Mes M&eacute;tiers</ul>
  <div class="contenu">
	  <ul class="box_contenu1 textalic">

 <? if ($this->affichageInterne == true) : ?>
	   <? if (!$this->possedeMetier): ?>
	   	Vous ne pratiquez aucun m&eacute;tier <br /><br />
	   	
	   	Vous pouvez aller vous renseigner dans un Ahenne Peheux
	   <? else : ?>
		   	Vous &ecirc;tes actuellement :
		   	<? $contenu = str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlspecialchars(addslashes($this->tabMetierCourant["description"])))); ?>
		   	<? $titre = "Description du m&eacute;tier ";
		   	 if ($this->tabMetierCourant["nom"]{0} == 'A') : $titre .= "d\'"; else: $titre .=  "de "; endif; 
		   	 $titre .= $this->tabMetierCourant["nom"];
		   	?>
		   	<span <?=Bral_Helper_Tooltip::jsTip($contenu, $titre, true) ?>>
		  	 	<?=$this->tabMetierCourant["nom"] ?>, appris le <?=$this->tabMetierCourant["date_apprentissage"] ?>
		    </span>
			<br /><br />
		   	<? if (count($this->tabMetiers) == 1): ?>
		   		Vous pratiquez &eacute;galement le m&eacute;tier suivant : <br />
		   	<? elseif (count($this->tabMetiers) > 1): ?>
		   		Vous pratiquez &eacute;galement les m&eacute;tiers suivants : <br />
		   	<? endif; ?>	
		   	<? if (count($this->tabMetiers) >= 1): ?>
		   		<table class="table_liste">
					<thead class="table_liste">
					  <tr class="table_liste" title="Cliquer pour Trier">
						<th>M&eacute;tier </th>
						<th>Appris le</th>
					  </tr>
					</thead>
					<tbody>
						<? foreach ($this->tabMetiers as $m) : ?>
							<? $contenu = str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlspecialchars(addslashes($m["description"]))));?>
					   		<? $titre = "Description du m&eacute;tier ";
			   	 			if ($m["nom"]{0} == 'A') : $titre .= "d\'"; else: $titre .=  "de "; endif; 
			   	 			$titre .= $m["nom"]?>
							<tr class="table_liste">
								<td class="" <?=Bral_Helper_Tooltip::jsTip($contenu, $titre, true) ?>><?=$m["nom"];?></td>
								<td class=""><?=$m["date_apprentissage"];?></td>
							</tr>
						<? endforeach; ?>
					</tbody>
				</table>
		    <? endif; ?>
	   <? endif; ?>
	   
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
	</ul> 
  </div>
</div>
<? include("box_bottom.phtml") ?>