<? include("box_header.phtml") ?>
<div class="inner">
  <ul class="titre textalia textsizeb">Mes M&eacute;tiers</ul>
  <div class="contenu">
	  <ul class="box_contenu1 textalic">
	   <? if (!$this->possedeMetier): ?>
	   	Vous ne pratiquez aucun m&eacute;tier <br><br>
	   	
	   	Vous pouvez aller vous renseigner dans un Ahenne Peheux
	   <? else : ?>
	   	Vous &ecirc;tes actuellement :
	   	
	   	 <span
	   	onmouseover="return overlib('<div style=\'width:300px\'><p style=\'text-align:justify\'><?=str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlentities(addslashes($this->tabMetierCourant["description"]))))?></p></div>',CAPTION,'Description du m&eacute;tier <? if ($this->tabMetierCourant["nom"]{0} == 'A') : echo 'd'; else: echo "de"; endif; ?> <?=htmlentities($this->tabMetierCourant["nom"]) ?>');"
      	onclick="return overlib('<div style=\'width:300px\'><p style=\'text-align:justify\'><?=str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlentities(addslashes($this->tabMetierCourant["description"]))));?></p></div>', STICKY, CAPTION, 'Description du m&eacute;tier <? if ($this->tabMetierCourant["nom"]{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>  <?=htmlentities($this->tabMetierCourant["nom"]) ?>', CLOSECLICK, EXCLUSIVE);"
      	onmouseout="return nd();" style="cursor:pointer">	
	   <?=htmlentities($this->tabMetierCourant["nom"]) ?> </span><br>
	   	Vous avez appris ce m&eacute;tier le <?=$this->tabMetierCourant["date_apprentissage"] ?>
		<br><br>
	   	<? if (count($this->tabMetiers) == 1): ?>
	   		Vous pratiquez &eacute;galement le m&eacute;tier suivant : <br>
	   	<? elseif (count($this->tabMetiers) > 1): ?>
	   		Vous pratiquez &eacute;galement les m&eacute;tiers suivants : <br>
	   	<? endif; ?>	
	   	<? if (count($this->tabMetiers) >= 1): ?>
			<? foreach ($this->tabMetiers as $m) : ?>
				 <span
			   	onmouseover="return overlib('<div style=\'width:300px\'><p style=\'text-align:justify\'><?=str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlentities(addslashes($m["description"]))));?></p></div>',CAPTION,'Description  du m&eacute;tier <? if ($m["nom"]{0} == 'A') : echo 'd'; else: echo "de"; endif; ?> <?=htmlentities($m["nom"]) ?>');"
		      	onclick="return overlib('<div style=\'width:300px\'><p style=\'text-align:justify\'><?=str_replace(array("\r\n", "\r", "\n"),'',nl2br(htmlentities(addslashes($m["description"]))));?></p></div>', STICKY, CAPTION, 'Description du m&eacute;tier <? if ($m["nom"]{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>  <?=htmlentities($m["nom"]) ?>', CLOSECLICK, EXCLUSIVE);"
      			onmouseout="return nd();" style="cursor:pointer">
				<?=htmlentities($m["nom"]);?>, appris le <?=htmlentities($m["date_apprentissage"]);?><br>
				</span>
			<? endforeach; ?>
	    <? endif; ?>
	   <? endif; ?>
	</ul> 
  </div>
</div>
<? include("box_bottom.phtml") ?>