<?php include("box_header.phtml") ?>
<div class="inner">

 <div class="titre">
	  <a onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $this->user->id_braldun ?>');" title="Cliquez pour voir votre profil">
	  <span class="titrea textalia textsizea"><?php echo $this->escape($this->user->prenom_braldun);?> 
	  <?php echo $this->escape($this->user->nom_braldun);?></span>
	  <br />
	  <span class="textalia textsized"><?php if ($this->user->titre_courant_braldun != null) :?>
	  <?php echo $this->user->titre_courant_braldun?>,
	  <?php endif;?> n&deg;<?php echo $this->user->id_braldun;?></span>
	  </a>
 </div>
  
<?php if ($this->affichageInterne == true) : ?>
	<?php include("box_onglets.phtml") ?>
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" />
<?php endif; ?>

</div>
<?php include("box_bottom.phtml") ?>