<? include("box_header.phtml") ?>
<div class="inner">
  <ul class="titre textalia textsizec"><a class="titre textalia textsizec"  onClick="javascript:ouvrirWin('/voir/hobbit/?hobbit=<?=$this->user->id_hobbit ?>');" title="Cliquez pour voir votre profil">Mon Profil</a>, n&deg;<?=$this->user->id_hobbit;?></span></ul>
  <ul class="titre textalib textsizeb"><?=$this->escape($this->user->prenom_hobbit);?> <?=$this->escape($this->user->nom_hobbit);?></ul>
  <div class="contenuA">
	  <ul class="box_contenu1 textalic">
	    Tour de base : <?php echo $this->escape($this->user->duree_base_tour_hobbit) ?><br />
	    DLA : <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('H:i:s \l\e d/m/y',$this->user->date_fin_tour_hobbit);?><br />
	    Position Tour Courant : <?=$this->user->nom_tour ?><br />
	    <? if ($this->user->info_prochaine_position != "") : ?>
	    	<?=$this->user->info_prochaine_position ?><br />
	    <? endif; ?>
	    Dur&eacute;e de ce tour : <?php echo $this->escape($this->user->duree_courant_tour_hobbit) ?><br />
	    Dur&eacute;e du prochain tour : <?php echo $this->escape($this->user->duree_prochain_tour_hobbit) ?><br />
		
	    Points de Vie : <?=$this->user->pv_restant_hobbit ?> / <?=($this->config->game->pv_base + $this->user->vigueur_base_hobbit * $this->config->game->pv_max_coef) ?> + <?= $this->user->pv_max_bm_hobbit ?>
	    <div class="barre_faim"><img src="/public/images/barre_vie.gif" height="10px" width="<?=floor($this->user->pv_restant_hobbit*100)/($this->config->game->pv_base + ($this->user->vigueur_base_hobbit * $this->config->game->pv_max_coef) + $this->user->pv_max_bm_hobbit)?>px"></div>
	    PA restants : <?=$this->user->pa_hobbit ?><br />
	    PX Perso: <?=$this->user->px_perso_hobbit ?> - PX Commun : <?=$this->user->px_commun_hobbit ?><br />
	    PI : <?=$this->user->pi_hobbit ?> - Niveau : <?=$this->user->niveau_hobbit ?><br />
	    Nb. Morts : <?=$this->user->nb_mort_hobbit ?> - 
	    Nb. Kill Monstre : <?=$this->user->nb_monstre_kill_hobbit ?> - 
	    Nb. Kill Hobbit : <?=$this->user->nb_hobbit_kill_hobbit ?>
	    <hr>
	    Vue BM : <?=$this->user->vue_bm_hobbit ?> <br />
	    R&eacute;g&eacute;n&eacute;ration : <?=$this->user->regeneration_hobbit ?> D<?=$this->config->game->de_regeneration ?> | Malus R&eacute;g&eacute;n&eacute;ration prochain tour : <?=$this->user->regeneration_malus_hobbit ?><br />
	    Force : <?=$this->config->game->base_force + $this->user->force_base_hobbit ?> 
	    	D<?=$this->config->game->de_force ?> 
	    	<? if ($this->user->force_bm_hobbit >= 0): echo "+"; endif;?><?=$this->user->force_bm_hobbit ?> 
	    	<? if ($this->user->force_bbdf_hobbit >= 0): echo "+"; endif;?><?=$this->user->force_bbdf_hobbit ?> | 
	    Agilit&eacute; : <?=$this->config->game->base_agilite + $this->user->agilite_base_hobbit ?> 
		    D<?=$this->config->game->de_agilite ?> 
		    <? if ($this->user->agilite_bm_hobbit >= 0): echo "+"; endif;?><?=$this->user->agilite_bm_hobbit ?>
		    <? if ($this->user->agilite_bbdf_hobbit >= 0): echo "+"; endif;?><?=$this->user->agilite_bbdf_hobbit ?> <br />
	    Sagesse : <?=$this->config->game->base_sagesse + $this->user->sagesse_base_hobbit ?> 
	    	D<?=$this->config->game->de_sagesse ?> 
	    	<? if ($this->user->sagesse_bm_hobbit >= 0): echo "+"; endif;?><?=$this->user->sagesse_bm_hobbit ?>
	    	<? if ($this->user->sagesse_bbdf_hobbit >= 0): echo "+"; endif;?><?=$this->user->sagesse_bbdf_hobbit ?> | 
	    Vigueur : <?=$this->config->game->base_vigueur + $this->user->vigueur_base_hobbit ?> 
	    	D<?=$this->config->game->de_vigueur ?> 
	    	<? if ($this->user->vigueur_bm_hobbit >= 0): echo "+"; endif;?><?=$this->user->vigueur_bm_hobbit ?>
	    	<? if ($this->user->vigueur_bbdf_hobbit >= 0): echo "+"; endif;?><?=$this->user->vigueur_bbdf_hobbit ?><br />
	    Attaque BM : <?=$this->user->bm_attaque_hobbit ?> | D&eacute;fense BM : <?=$this->user->bm_defense_hobbit ?> | D&eacute;g&acirc;ts BM : <?=$this->user->bm_degat_hobbit ?><br />
	    Balance faim : <?=$this->user->balance_faim_hobbit ?> %
	    <div class="barre_faim"><img src="/public/images/barre_faim.gif" height="10px" width="<?=$this->user->balance_faim_hobbit ?>px"></div>
	    <br />
	    Poids transportable : <?=$this->user->poids_transportable_hobbit ?> Kg - transport&eacute; : <?=$this->user->poids_transporte_hobbit ?> Kg<br /><br />
	    Armure naturelle : <?=$this->user->armure_naturelle_hobbit ?>, &eacute;quipement : <?=$this->user->armure_equipement_hobbit ?><br />
	  </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>