<? include("box_header.phtml") ?>
<div class="inner">
<ul class="titre textalia textsizec">Mes Quêtes / Contrats et Filatures</ul>
 <div class="contenuC">
  <ul class="box_contenu1 textalic">
  
<? if ($this->affichageInterne == true) : ?>
    
    <input type='button' class='button1' value='Mes Quêtes' onClick="_get_('/quetes/doaction?caction=ask_quetes_liste');">
    <input type='button' class='button1' value='Mes Contrats' onClick="_get_('/contrats/doaction?caction=ask_contrats_liste');">
    <input type='button' class='button1' value='Mes Filatures' onClick="_get_('/filatures/doaction?caction=ask_filatures_liste');">
    <div id="box_quete_interne">
    <?=$this->htmlContenu ?>
    </div>
    
			   				
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
  
  </ul>
 </div>
</div>
<? include("box_bottom.phtml") ?>