<?php include("box_header.phtml") ?>
<div class="inner">
<div class="titre textalia textsizec">Mes Quêtes / Contrats et Filatures</div>
 <div class="contenuC">
  <div class="box_contenu1 textalic">
  
<?php if ($this->affichageInterne == true) : ?>
    <input type='button' class='button1' value='Mes Quêtes' onclick="_get_('/quetes/doaction?caction=ask_quetes_liste');">
    <input type='button' class='button1' value='Mes Contrats' onclick="_get_('/contrats/doaction?caction=ask_contrats_liste');">
    <input type='button' class='button1' value='Mes Filatures' onclick="_get_('/filatures/doaction?caction=ask_filatures_liste');">
    <div id="box_quete_interne">
    <?php echo $this->htmlContenu ?>
    </div>
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/wait.gif" />
<?php endif; ?>
  
  </div>
 </div>
</div>
<?php include("box_bottom.phtml") ?>