<? include("box_header.phtml") ?>
<div class="inner">
  <ul class="titre textalia textsizeb">Jeu de Soule</ul>
  <div class="contenu">
	  <ul class="box_contenu1 textalic">

 <? if ($this->affichageInterne == true) : ?>
   <? if ($this->terrainHobbit != null) : ?>
   Avec votre niveau, le terrain vous correspondant est le <?=$this->terrainHobbit["nom_soule_terrain"]?>.<br>
   <? endif;?>
   <br>
   
   Choissisez le terrain : 
	<select name='id_terrain' onChange="Javascript:_get_('/soule/doaction?caction=ask_soule_voir&id_terrain='+this.value);">
		<? if ($this->terrains != null) : ?>
		   	<? foreach ($this->terrains as $t) : ?>
			<option value='<?=$t["id_soule_terrain"]?>' <?if ($t["selected"] == true){echo "selected";}?>><?=$t["nom_soule_terrain"]?> (<?=$t["info_soule_terrain"]?>)</option>
			<? endforeach; ?>
		<? endif;?>
	</select>
	   
	<div id="box_soule_interne">
	<?=$this->htmlTerrain?>
	</div>
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
	</ul> 
  </div>
</div>
<? include("box_bottom.phtml") ?>