<?php include("box_header.phtml") ?>
<div class="inner">
  <div class="titre textalia textsizec"><a class="titre textalia textsizec" title="Cliquez pour voir les règles complètes" style="text-decoration: none" onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/Soule');">Jeu de Soule</a></div>
  <div class="contenu">
  <div class="box_contenu1 textalic">
  <div class="titre textalic textsized">Règle : prendre le ballon et l'emmener dans le fond du camp adverse</div>
	  
 <?php if ($this->affichageInterne == true) : ?>
   <?php if ($this->terrainBraldun != null) : ?>
   Avec votre niveau, le terrain vous correspondant est le <?php echo $this->terrainBraldun["nom_soule_terrain"]?>.<br />
   <?php endif;?>
   <br />
   
   Choissisez le terrain : 
	<select name='id_terrain' onchange="Javascript:_get_('/soule/doaction?caction=ask_soule_voir&id_terrain='+this.value);">
	<?php if ($this->terrains != null) : ?>
	   	<?php foreach ($this->terrains as $t) : ?>
		<option value='<?php echo $t["id_soule_terrain"]?>' <?php if ($t["selected"] == true) { echo "selected"; }?>><?php echo $t["nom_soule_terrain"]?> (<?php echo $t["info_soule_terrain"]?>)</option>
		<?php endforeach; ?>
	<?php endif;?>
	</select>
	   
	<div id="box_soule_interne">
	<?php echo $this->htmlTerrain?>
	</div>
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->url->static?>/images/wait.gif" />
<?php endif; ?>
	</div> 
  </div>
</div>
<?php include("box_bottom.phtml") ?>