<?php include("box_header.phtml") ?>
<div class="inner">
  <div class="titre textalia textsizec">Ma Réputation</div>
  <div class="contenu">
	  <div class="box_contenu1 textalic">

<div class="titre textalic textsized">Mes Titres</div>
 <?php if ($this->affichageInterne == true) : ?>
	   <?php if (!$this->possedeTitre): ?>
	   	Vous n'avez aucun titre <br /><br />
	   	
	   <?php else : ?>
		   	<?php if (count($this->tabTitres) >= 1): ?>
		   		<table class="table_liste">
					<thead class="table_liste">
					  <tr class="table_liste" title="Cliquer pour Trier">
						<th>Titre </th>
						<th nowrap>Acquis au niveau</th>
						<th nowrap>Appris le</th>
						<th>Niveau</th>
					  </tr>
					</thead>
					<tbody>
						<?php foreach ($this->tabTitres as $t) : ?>
							<tr class="table_liste">
								<td class="" nowrap><?php echo $t["nom"];?></td>
								<td class="" nowrap><?php echo $t["niveau_acquis_htitre"];?></td>
								<td class="" nowrap><?php echo $t["date_acquis_htitre"];?></td>
								<td class="" nowrap>&nbsp;&nbsp;<?php echo $t["description"];?></td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
		    <?php endif; ?>
	   <?php endif; ?>
	   <br />
	   
	<div class="titre textalic textsized">Ma Réputation Gredin / Redresseur de Torts</div>
		Vos points de Gredin : <?php echo $this->user->points_gredin_braldun?><br />
		Vos points de Redresseur de Torts : <?php echo $this->user->points_redresseur_braldun?><br /><br />
		
	<div class="titre textalic textsized">Mes Distinctions</div>
	   <?php if ($this->tabDistinctions != null && count($this->tabDistinctions) >= 1): ?>
	   	<?php $s=""; if ($this->user->points_distinctions_braldun > 1): $s='s'; endif; ?>
	   	<span title='points actualisés une fois par jour' style='cursor:pointer'>Vous avez <?php echo $this->user->points_distinctions_braldun ?> point<?php echo $s?> de distinction. (?)</span>
	   	<br />
	   	<?php foreach($this->tabDistinctions as $d): ?>
	   		<br />
			 Catégorie : <?php echo $d["nom"]?>
			 <br />
		  	<?php $i = 0; 
		  	foreach($d["distinctions"] as $t): ?>
			  	<?php echo $t["date_hdistinction"]?> : 
			  	<?php echo $t["nom"]?> (<?php echo $t["points"]?> pt<?php if ($t["points"] > 1): echo "s"; endif;?>) <br />
		  	<?php endforeach; ?>
	  	<?php endforeach; ?>
	  <?php else: ?>
	  	Aucune distinction
	  <?php endif;?>
	   <br />
<?php else: ?>
	Chargement en cours
	<br /><img src="<?php echo $this->config->static->url?>/images/wait.gif" />
<?php endif; ?>
	</div> 
  </div>
</div>
<?php include("box_bottom.phtml") ?>