<? include("box_header.phtml") ?>
<div class="inner">
  <ul class="titre textalia textsizeb">Mes Titres et Distinctions</ul>
  <div class="contenu">
	  <ul class="box_contenu1 textalic">
	  <br>

 <? if ($this->affichageInterne == true) : ?>
	   <? if (!$this->possedeTitre): ?>
	   	Vous n'avez aucun titre <br /><br />
	   	
	   <? else : ?>
		   	<? if (count($this->tabTitres) >= 1): ?>
		   		<table class="table_liste">
					<thead class="table_liste">
					  <tr class="table_liste" title="Cliquer pour Trier">
						<th>Titre </th>
						<th nowrap>Acquis au niveau</th>
						<th nowrap>Appris le</th>
						<th>Niveau</th>
					  </tr>
					</thead>
					<tbody>
						<? foreach ($this->tabTitres as $t) : ?>
							<tr class="table_liste">
								<td class="" nowrap><?=$t["nom"];?></td>
								<td class="" nowrap><?=$t["niveau_acquis_htitre"];?></td>
								<td class="" nowrap><?=$t["date_acquis_htitre"];?></td>
								<td class="" nowrap>&nbsp;&nbsp;<?=$t["description"];?></td>
							</tr>
						<? endforeach; ?>
					</tbody>
				</table>
		    <? endif; ?>
	   <? endif; ?>
	   <br>
	   <? if ($this->tabDistinctions != null && count($this->tabDistinctions) >= 1): ?>
	   	<? $s=""; if ($this->user->points_distinctions_hobbit > 1): $s='s'; endif; ?>
	   	<span title='points actualisés une fois par jour' style='cursor:pointer'>Vous avez <?=$this->user->points_distinctions_hobbit ?> point<?=$s?> de distinction. (?)</span>
	   	<br>
	   	<? foreach($this->tabDistinctions as $d): ?>
	   		<br>
			 Catégorie : <?=$d["nom"]?>
			 <br>
		  	<? $i = 0; 
		  	foreach($d["distinctions"] as $t): ?>
			  	<?=$t["date_hdistinction"]?> : 
			  	<?=$t["nom"]?> (<?=$t["points"]?> pts) <br>
		  	<? endforeach; ?>
	  	<? endforeach; ?>
	  <? else: ?>
	  	Aucune distinction
	  <? endif;?>
	   <br>
<? else: ?>
	Chargement en cours
	<br /><img src="/public/images/wait.gif" />
<? endif; ?>
	</ul> 
  </div>
</div>
<? include("box_bottom.phtml") ?>