<?		 
if (isset($this->ciblesEffet["hobbitTouches"]) || isset($this->ciblesEffet["monstreTouches"]) &&
	($this->ciblesEffet["hobbitTouches"] != null || $this->ciblesEffet["monstreTouches"] != null)) {
	echo "Vous avez touch&eacute; : ";
	echo "
";
}
if (isset($this->ciblesEffet["hobbitTouches"]) && $this->ciblesEffet["hobbitTouches"] != null) {
	foreach($this->ciblesEffet["hobbitTouches"] as $val) {
		$h = $val["hobbit"];
		echo htmlentities($h["prenom_hobbit"]). " ". htmlentities($h["nom_hobbit"]). " (".$h["id_hobbit"].") N".$h["niveau_hobbit"];
		echo "
";
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_copie_effets.phtml");
	}
}
if (isset($this->ciblesEffet["monstreTouches"]) && $this->ciblesEffet["monstreTouches"] != null) {
	foreach($this->ciblesEffet["monstreTouches"] as $val) {
		$m = $val["monstre"];
		echo htmlentities($m["nom_type_monstre"]). " (".$m["id_monstre"].") N".$m["niveau_monstre"];
		echo "
";
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_copie_effets.phtml");
	}
}
if ((isset($this->ciblesEffet["hobbitMorts"])|| isset($this->ciblesEffet["monstreMorts"])) && 
    ($this->ciblesEffet["hobbitMorts"] != null || $this->ciblesEffet["monstreMorts"] != null)) {
	echo "Vous avez tu&eacute; : ";
	echo "
";
}
if (isset($this->ciblesEffet["hobbitMorts"]) && $this->ciblesEffet["hobbitMorts"] != null) {
	foreach($this->ciblesEffet["hobbitMorts"] as $val) {
		$h = $val["hobbit"];
		echo htmlentities($h["prenom_hobbit"]). " ". htmlentities($h["nom_hobbit"]). " (".$h["id_hobbit"].") N".$h["niveau_hobbit"];
		echo "
";
	}
}
if (isset($this->ciblesEffet["monstreMorts"]) && $this->ciblesEffet["monstreMorts"] != null) {
	foreach($this->ciblesEffet["monstreMorts"] as $val) {
		$m = $val["monstre"];
		echo htmlentities($m["nom_type_monstre"]). " (".$m["id_monstre"].") N".$m["niveau_monstre"];
		echo "
";
	}
}
?>