<div id='tour_text' style="display:block"  onClick="javascript:switch2div('tour_text','tour_copie');">
	
	<?php if ($this->is_mort): ?>
		<? if ($this->user->sexe_hobbit == "feminin"):$e='e';else:$e='';endif;?>
		Vous avez &eacute;t&eacute; tu&eacute;<?=$e?><br>
		Vous r&eacute;apparaissez dans un C&eacute;ache Hu<br><br>
	<? endif; ?>

	<?php if ($this->is_nouveau_tour): ?>
		Activation d'un nouveau tour : <br>
	<?php elseif ($this->is_update_tour) : ?>
		Information tour : <br>
	<?php endif; ?>
	<?php if ($this->is_tour_manque) : ?>
		<b>Vous avez manqué un (ou plusieurs) tours de jeu.</b>  <br>
	<?php endif; ?>
	Date limite d'action : <?=$this->user->date_fin_tour_hobbit ?> <br>
	Durée du tour : <?=$this->user->duree_courant_tour_hobbit ?> <br>
	Position dans le tour : <?=$this->user->nom_tour ?> <br>
	Nombre de Points d'Action : <?=$this->user->pa_hobbit ?>
</div>
	 
<div id='tour_copie' style="display:none">
	<textarea onClick="javascript:this.select();" rows=5 cols=40><?php if ($this->is_nouveau_tour): ?>
Activation d'un nouveau tour <?php endif; ?>
<?php if ($this->is_tour_manque) : ?>Vous avez manqué un (ou plusieurs) tour de jeu<?php endif; ?> 
Date limite d'action : <?=$this->user->date_fin_tour_hobbit ?> 
Durée du tour : <?=$this->user->duree_courant_tour_hobbit ?> 
Position dans le tour : <?=$this->user->nom_tour  ?> 
Nombre de Points d'Action : <?=$this->user->pa_hobbit ?></textarea>
</div>

<input type='button' value='Copier' onClick="javascript:switch2div('tour_text','tour_copie');">
<input type='button' value='Fermer' onClick='_get_("/interface/clear");'>