<?php include("box_header.phtml") ?>

<?php if ($this->estVueEtendue == false): 
		include('vue/titre_vue.phtml'); 
	else :
		?><div class="titre textalic textsizea">Ma Vue &Eacute;tendue</div>
		<div class="titre textalic textsizef">
		<?php echo $this->vue_nb_cases ?> case<?php if ($this->vue_nb_cases > 1): echo "s"; endif; ?>
		aux alentours
		</div><?php
	endif;
?>
<div class="box_contenu1 textalic">
<?php if (Zend_Registry::get("estWork")) : ?>
	<input type='button' class='button1' value='Afficher / Cacher la vue et ses images' onclick="switch2div('vueFoo', 'vueTableWrapper');">
	<div id='vueFoo'>Vue Cachée</div>
<?php endif;?>
  <table align="center" id="vueTableWrapper" class="vueTableWrapper" width='100%'>
  	<tr>
  		<td valign="top">
		<?php if ($this->user->z_braldun != 0) : ?>
			<div class="textalic textsizee">
				<b>Vous êtes au niveau z:<?php echo $this->user->z_braldun?></b>
			</div>
		<?php endif;?>  		
		<?php include('vue/damier.phtml'); ?>
		</td>
  	</tr>
  </table>
</div>

<?php include("box_bottom.phtml") ?>