<?php include("box_header.phtml") ?>
  <div class="contenuA">
	  <div class="box_contenu1 textalia">
	  
	  	<table width='100%'>
	  	<tr>
	  	<td>
		  	<div id='boussole'>
		  		<table>
		  		<tr>
			  		<td>
				  		<div class="ui-state-default ui-corner-all" title="Déplacement en haut à gauche" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=hg&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-nw"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en haut" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=h&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-n"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en haut à droite" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=hd&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-ne"></span>
						</div>
					</td>
					</tr>
					<tr>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement à gauche" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=g&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-w"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Recentrage sur la position actuelle" onclick="Javascript:_get_('/interface/load/?box=box_vue');">
						<span class="ui-icon ui-icon-radio-on"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en haut à droite" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=d&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-e"></span>
						</div>
					</td>
					</tr>
					<tr>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en bas à gauche" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=bg&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-sw"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en bas" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=b&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-s"></span>
						</div>
					</td>
					<td>
						<div class="ui-state-default ui-corner-all" title="Déplacement en bas à droite" onclick="Javascript:_get_('/interface/load/?box=box_vue&caction=box_vue&valeur_1=bd&valeur_2=' + $('#boussole_centre_x').val() +'&valeur_3=' + $('#boussole_centre_y').val())">
						<span class="ui-icon ui-icon-triangle-1-se"></span>
						</div>
					</td>
				</tr>
				</table>
			</div>
	  	</td>
	  	<td>
		  	<a class="titre textalia textsizef"  onclick="javascript:ouvrirWin('/voir/vue/')";>Vue &eacute;tendue</a><br />
		    Ma Position : <b><?php echo $this->user->x_braldun ?>, <?php echo $this->user->y_braldun ?></b> <br /><br />
	    </td>
		</table>
		
	    <p class="a">❧</p>
	    
 		<div class="titre textalia textsized" >Détails vue</div>
 		<button id="vueFixeeButton" onclick="Javascript:vueFixeeButton();" title="Débloquer" style="display:none;float:right;">Débloquer</button>
 		
 		<div id='vuedetails_interne'>Cliquer sur une case pour avoir le détails</div>
 		
 		<p class="a">❧</p>
 		
 		<?php echo $this->blabla?>

	  </div>
</div>
<?php include("box_bottom.phtml") ?>