<?php include("box_header.phtml") ?>
  <div class="inner">
	  <div class="box_contenu1 textalia">
	  	
	    <p class="a">❧</p>
	    
 		<div class="titre textalia textsized" >Détails vue</div>
 		<button id="vueFixeeButton" onclick="Javascript:vueFixeeButton();" title="Débloquer" style="display:none;float:right;">Débloquer</button>
 		
 		<div id='vuedetails_interne'>Cliquer sur une case pour avoir le détails</div>
 		
 		<p class="a">❧</p>
 		
 		<?php echo $this->blabla?>

	  </div>
</div>
<?php include("box_bottom.phtml") ?>