  <br />
  <div class="titre textalic textsized">Filatures</div>
  <br /><br />
  
  <div class="titre textalic textsized">Vous pouvez filer un Braldûn avec la compétence Filer</div>
  <br /> 
  
  <?php if ($this->filatures == null) : ?>
  	Vous n'avez aucune filature.
  <?php else: ?>
  
  <?php if ($this->idFilatureEnCours != null) : ?>
	  <input type='button' class='button' value='Annuler la filature en cours - 0 PA' onclick="_get_('/filature/doaction?caction=ask_filature_annuler&id_filature=<?php echo $this->idFilatureEnCours?>');">
	  <br /><br />
  <?php endif;?>
    
    
 	<table width="100%">
 		<tr>
 			<td width="40%" valign="top">
 				<table class="table_liste" style="width:90%">
					<thead class="table_liste">
					  <tr class="table_liste">
						<th colspan="2"> Filatures r&eacute;alis&eacute;es ou en cours<br /></th>
					  </tr>
					</thead>
					
					<tbody>
					 <?php foreach($this->filatures as $f) :
					 	$i = 0; 
					 	?>
				  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>" title="Cliquer pour voir le détail" style="cursor:pointer" onclick="Javascript:_get_('/filature/doaction?caction=ask_filature_voir&id_filature=<?php echo $f["id_filature"]?>');">
				  		<td class="table_liste">
				  			<?php echo $f["cible"]?>
				  		</td>
						<td class="table_liste" nowrap>
						  	<?php if ($f["date_fin_filature"] != null): ?> 
						  		Terminée le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$f["date_fin_filature"]);?>
						  	<?php else: ?>
						  		En Cours, depuis le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$f["date_creation_filature"]);?>
						  	<?php endif;?>
						 </td>
					  	 </tr>
					  <?php endforeach;?>
					</tbody>
				</table>
 			</td>
 			<td width="60%" valign="top">
 				<div id="box_filature_voir">
				<?php echo $this->htmlFilature?>
				</div>
 			</td>
 		</tr>
 	</table>
 <?php endif; ?>
 	