<?php Zend_Loader::loadClass("Bral_Helper_DetailEquipement"); ?>

<table class="table_liste" style="width:90%" <?php if ($this->idEquipementsTable != false) : ?> id="<?php echo $this->idEquipementsTable?>"<?php endif; ?>>
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
	  	<th>&nbsp;</th>
		<th>Nom</th>
		<th>Caract&eacute;ristiques</th>
		<th>Niveau</th>
	  </tr>
	</thead>
	<tbody>
		<?php if (count($this->equipements) > 0) :?>
			<?php foreach($this->equipements as $em) : ?>
			   	 <tr class="table_liste">
				  	<th colspan="8" class="table_liste_th">Position : <?php echo $em["nom_type_emplacement"] ?></th>
			  	</tr>
			   	<?php 
			   	  $i = 0;
			      foreach($em["equipements"] as $e) :?>
					<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
				  		<td class="table_liste"><?php echo $e["id_equipement"] ?></td>
				  		<td class="table_liste"><img src='<?php echo $this->config->url->static?>/images/type_equipement/type_equipement_<?php echo $e["id_type_equipement"]?>.png' alt="<?php echo htmlspecialchars($e["nom"]) ?>"/></td>
				  		<td class="table_liste"><?php echo $e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?></td>
				  		<td class="table_liste">
				  			<div class='braltip'>
				  			<?php echo Bral_Helper_DetailEquipement::afficherTooltip($e, true);?>
				  			<img src="<?php echo $this->config->url->static?>/images/divers/info_icon.gif"/>
				  			</div>
				  		</td>
				  		<td class="table_liste"><?php echo $e["niveau"] ?></td>
				  	</tr>
				  <?php endforeach; ?>
			<?php endforeach; ?>
		<?php else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune pi&egrave;ce d'&eacute;quipement</i></td></tr>
		<?php endif; ?>
	</tbody>
</table>