<br>
<? if ($this->filtre == $this->config->messagerie->message->type->envoye): 
	$titre = "Messages envoyés";
?>
	<ul class="titre textalic textsized" ><?=$titre?></ul>
	Les messages envoyés sont supprimés au bout de 30 jours.
<? elseif ($this->filtre == $this->config->messagerie->message->type->supprime): 
	$titre = "Messages supprimés";
?>
	<ul class="titre textalic textsized" ><?=$titre?></ul>
	Les messages supprimés sont définitivement supprimés dans la nuit.
<? elseif ($this->filtre == $this->config->messagerie->message->type->reception): 
	$titre = "Boite de réception";
?>
	<ul class="titre textalic textsized" ><?=$titre?></ul>
	Les messages présents dans la boite de réception sont supprimés au bout de 30 jours.
<? elseif ($this->filtre == $this->config->messagerie->message->type->archive): 
	$titre = "Messages archivés";
?>
	<ul class="titre textalic textsized" ><?=$titre?></ul>
	Vous ne pouvez pas avoir plus de 200 messages archivés
<? endif; ?>
		
<br><br>

<table  width="100%" style="padding:0px;border-spacing:0px;">
<tr>
<td  width="40%" valign="top">
<table class="table_liste" style="width:100%;" >
	<tbody>
	<? if (!empty($this->messages)): ?>
		<? $i = 0;
		   $listeIdMessage = "";
		   foreach($this->messages as $message):
		   		$jsLu = "";
		   		if ($this->filtre == $this->config->messagerie->message->type->reception):
			   		if ($message["toread"] == "0") :
			   			$jsLu = "$('imgMsgLu".$message["id_message"]."').style.display='block';$('imgMsgALire".$message["id_message"]."').style.display='none';";
			   		endif;
		   		endif;
		   		$js="onClick=\"".$jsLu."_get_('/messagerie/doaction?caction=do_messagerie_message&valeur_1=message&valeur_2=".$message['id_message']."&valeur_3=".$this->page."&valeur_4=".$this->filtre."');\"  title='Lire le message'"; ?>
	  			<tr class="table_liste<?=($i % 2);$i++; ?> hhover">
	  				<td class="table_liste" style="padding:0px;" <?=$js ?>>
	  					<? if ($message["toread"] == "0") :
	  						$displayAlire = 'display:block;';
	  						$displayLu = 'display:none;';
	  					   else:
	  						$displayAlire = 'display:none;';
	  						$displayLu = 'display:block;';
	  					   endif;
	  					 ?>
						
						<img id='imgMsgALire<?=$message["id_message"]?>' alt="&Agrave; lire" title="&Agrave; lire" src="/public/images/uddeim/new_im.gif" border="0" style='<?=$displayAlire?>'/>
						<img id='imgMsgLu<?=$message["id_message"]?>'alt="D&eacute;j&agrave; lu" title="D&eacute;j&agrave; lu" src="/public/images/uddeim/nonew_im.gif" border="0" style='<?=$displayLu?>' />
					</td>
	  				<td class="table_liste" style="padding:2px;" nowrap>
	  					<? if ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
		  					De <?=$message["expediteur"];?>&nbsp;
		  					&agrave;<br/>
		  					<?=$message["destinataire"];?>&nbsp;
	  					<? elseif ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
	  						<?=$message["destinataire"];?>&nbsp;
	  					<? else: ?>
	  						<?=$message["expediteur"];?>&nbsp;
	  					<? endif; ?>
	  				</td>
	  				<td class="table_liste" style="padding:2px;" <?=$js ?> nowrap> <?if (mb_strlen($message["titre"]) > 25) echo Bral_Util_BBParser::bbcodeStrip(mb_substr($message["titre"], 0, 25))."..."; else echo Bral_Util_BBParser::bbcodeStrip($message["titre"]);?></td>
	  				<td class="table_liste" style="padding:2px;" <?=$js ?>>
	  					<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y\<\b\r\> H:i', $message["date"]);?></td>
					<td class="table_liste" style="padding:0px;">
						<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
							<input type="checkbox" id="msgId_<?=$message["id_message"];?>" value="<?=$message["id_message"];?>"/>
							<? $listeIdMessage .= "msgId_".$message["id_message"].",";?>
						<? endif; ?>
					</td>
	  			</tr>
		  	<? endforeach; ?>
		  	<? if ($listeIdMessage != "") :?>
		  		<input type="hidden" id="listeIdMessage" value="<?=substr($listeIdMessage, 0, strlen($listeIdMessage) - 1);?>"/>
		  	<? endif;?>
		<? else: ?>
   		<tr class="table_liste">
   			<td colspan="6">Aucun message</td>
   		</tr>
   		<? endif; ?>
	</tbody>
		<thead class="table_liste">
		<tr class="table_liste">
		<th>&nbsp;</th>
		<th>
		<? if ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
			&Agrave;
		<? elseif ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
			De / &Agrave;
		<? else: ?>
			De
		<? endif; ?>
		</th>
		<th>Message</th>
		<th>Date</th>
		<th>
			<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
				<span id="messages_tous" style="cursor:pointer" onClick='javascript:checkboxCocher($("listeIdMessage").value, true, this, $("messages_aucun"))'>Tous</span>
				<span id="messages_aucun" style="cursor:pointer; display:none" onClick='javascript:checkboxCocher($("listeIdMessage").value, false, this, $("messages_tous"))'>Aucun</span>
			<? endif; ?>
		</th>
	  	</tr>
	</thead>
	<tfoot class="table_liste">
	 <tr class="table_liste">
		    <th colspan='5'>
		    
		    	<br>
		    	<input type="hidden" id="messagerie_filtre" name="messagerie_filtre" value="<?=$this->filtre?>" />
		      	<?php echo $this->paginator; ?>
             	<br>
			   
			   <? if (!empty($this->messages)) : ?>
				   <? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
			       	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimerselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Supprimer les messages sélectionnés" />
			       <? endif; ?>
				   <? if ($this->filtre == $this->config->messagerie->message->type->reception): ?>
				   	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiverselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Archiver les messages sélectionnés" />
				   <? endif; ?>
				   <? if ($this->filtre != $this->config->messagerie->message->type->supprime && $this->filtre != $this->config->messagerie->message->type->envoye): ?>
			       	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=marquerlueselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Marquer les messages sélectionnés comme lus" />
			       <? endif; ?>
			       <br>
			       <? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
			       	<input type="button" class='button1'  onClick='javascript:if (confirm("Confirmez-vous la suppression de tous les messages ?")) {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=all&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="<?=$titre?> : Supprimer TOUS les messages" />
			       <? endif; ?>
			   <? endif;?>
		    </th>
		  </tr>
	</tfoot>
</table>

</td>
<td width="50%"  valign="top">
<div id="messagerie_message"></div>
</td>
</tr>
</table>
<br>