
<br>
<? if ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
	<ul class="titre textalic textsized" >Messages envoyés</ul>
	Les messages envoyés sont supprimés au bout de 30 jours.
<? elseif ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
	<ul class="titre textalic textsized" >Messages supprimés</ul>
	Les messages supprimés sont définitivement supprimés dans la nuit.
<? elseif ($this->filtre == $this->config->messagerie->message->type->reception): ?>
	<ul class="titre textalic textsized" >Boite de réception</ul>
	Les messages présents dans la boite de réception sont supprimés au bout de 30 jours.
<? elseif ($this->filtre == $this->config->messagerie->message->type->archive): ?>
	<ul class="titre textalic textsized" >Messages archivés</ul>
	Vous ne pouvez pas avoir plus de 200 messages archivés
<? endif; ?>
		
<br><br>

<table class="table_liste">
	<tbody>
	<? if (!empty($this->messages)): ?>
		<? $i = 0;
		   $listeIdMessage = "";
		   foreach($this->messages as $message): ?>
		   		<? $js="onClick=\"_get_('/messagerie/doaction?caction=do_messagerie_message&valeur_1=message&valeur_2=".$message['id_message']."&valeur_3=".$this->page."&valeur_4=".$this->filtre."');\"  title='Lire le message'"; ?>
	  			<tr class="table_liste<?=($i % 2);$i++; ?> hhover">
	  				<td class="table_liste">
	  					<? if ($message["toread"] == "0") :?>
		  					<img alt="&Agrave; lire" title="&Agrave; lire" src="/public/images/uddeim/new_im.gif" border="0" 
							<?=$js ?>>
	  					<? else: ?>
							<img alt="D&eacute;j&agrave; lu" title="D&eacute;j&agrave; lu" src="/public/images/uddeim/nonew_im.gif" border="0" 
							<?=$js ?>>
						<? endif; ?>
					</td>
	  				<td class="table_liste">
	  					<? if ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
		  					De <?=$message["expediteur"];?>&nbsp;
		  					&agrave;<br/>
		  					<?=$message["destinataire"];?>&nbsp;
	  					<? elseif ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
	  						<?=$message["destinataire"];?>&nbsp;
	  					<? else: ?>
	  						<?=$message["expediteur"];?>&nbsp;
	  					<? endif; ?>
	  				</td>
	  				<td class="table_liste" <?=$js ?>> <?if (mb_strlen($message["titre"]) > 25) echo Bral_Util_BBParser::bbcodeStrip(mb_substr($message["titre"], 0, 25))."..."; else echo Bral_Util_BBParser::bbcodeStrip($message["titre"]);?></td>
	  				<td class="table_liste" <?=$js ?>> le 
	  					<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y, H:i', $message["date"]);?></td>
	  				<td class="table_liste" nowrap>
						<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
							<img src="/public/images/uddeim/forward.gif" alt="Transf&eacute;rer" title="Transf&eacute;rer"onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=transferer&valeur_2=<?=$message["id_message"];?>");' style="cursor:pointer">
							<img src="/public/images/uddeim/trash.gif" alt="Effacer" title="Effacer" onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=<?=$message["id_message"];?>");' style="cursor:pointer">
						<? endif;?>
						<? if ($this->filtre != $this->config->messagerie->message->type->supprime && $this->filtre != $this->config->messagerie->message->type->envoye): ?>
							<img src="/public/images/uddeim/archive.gif" alt="Archiver" title="Archiver" onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiver&valeur_2=<?=$message["id_message"];?>");' style="cursor:pointer">
						<? endif; ?>
					</td>
					<td class="table_liste">
						<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
							<input type="checkbox" id="msgId_<?=$message["id_message"];?>" value="<?=$message["id_message"];?>"/>
							<? $listeIdMessage .= "msgId_".$message["id_message"].",";?>
						<? endif; ?>
					</td>
	  			</tr>
		  	<? endforeach; ?>
		  	<? if ($listeIdMessage != "") :?>
		  		<input type="hidden" id="listeIdMessage" value="<?=substr($listeIdMessage, 0, strlen($listeIdMessage) - 1);?>"/>
		  	<? endif;?>
		<? else: ?>
   		<tr class="table_liste">
   			<td colspan="5">Aucun message</td>
   		</tr>
   		<? endif; ?>
	</tbody>
		<thead class="table_liste">
		<tr class="table_liste">
		<th>&nbsp;</th>
		<th>
		<? if ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
			&Agrave;
		<? elseif ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
			De / &Agrave;
		<? else: ?>
			De
		<? endif; ?>
		</th>
		<th>Message</th>
		<th>Date</th>
		<th>&nbsp;</th>
		<th>
			<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
				<span id="messages_tous" style="cursor:pointer" onClick='javascript:checkboxCocher($("listeIdMessage").value, true, this, $("messages_aucun"))'>Tous</span>
				<span id="messages_aucun" style="cursor:pointer; display:none" onClick='javascript:checkboxCocher($("listeIdMessage").value, false, this, $("messages_tous"))'>Aucun</span>
			<? endif; ?>
		</th>
	  	</tr>
	</thead>
	<tfoot class="table_liste">
	 <tr class="table_liste">
		    <th colspan='6'>
		    
		    	<br>
		    	<input type="hidden" id="messagerie_filtre" name="messagerie_filtre" value="<?=$this->filtre?>" />
		      	<?php echo $this->paginator; ?>
             	<br>
			   
			   <? if (!empty($this->messages)) : ?>
				   <? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
			       	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimerselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Supprimer les messages sélectionnés" />
			       <? endif; ?>
				   <? if ($this->filtre == $this->config->messagerie->message->type->reception): ?>
				   	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=archiverselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Archiver les messages sélectionnés" />
				   <? endif; ?>
				   <? if ($this->filtre != $this->config->messagerie->message->type->supprime && $this->filtre != $this->config->messagerie->message->type->envoye): ?>
			       	<input type="button" class='button1'  onClick='javascript:listeMessages=chaineCheckbox($("listeIdMessage").value);if (listeMessages == "") {alert("Aucun message sélectionné");} else {_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=marquerlueselection&valeur_2="+listeMessages+"&valeur_3=<?=$this->page?>&valeur_4=<?=$this->filtre?>");}'  value="Marquer les messages sélectionnés comme lus" />
			       <? endif; ?>
			   <? endif;?>
		    </th>
		  </tr>
	</tfoot>
</table>
<br>