
<br>
<? if ($this->inscriptionSiteOk == false) :?>
	Vous devez vous connecter au <a href="http://www.braldahim.com">site</a> avant de voir les messages ici.
<? else: ?>

<table class="table_liste">
	<thead class="table_liste">
		<tr class="table_liste">
		<th>&nbsp;</th>
		<th>
		<? if ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
			&Agrave;
		<? elseif ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
			De / &Agrave;
		<? else: ?>
			De
		<? endif; ?>
		</th>
		<th>Message</th>
		<th>Date</th>
		<th>&nbsp;</th>
	  	</tr>
	</thead>
	<tfoot class="table_liste">
	 <tr class="table_liste">
		    <th colspan='5'>
			   <? if ($this->precedentOk === true) : ?>
			   <input type="button" class='button1' onClick="Javascript:_get_('/interface/load/?box=box_messagerie&valeur_1=p&valeur_2=<?=$this->filtre ?>&valeur_3=<?=$this->page ?>&valeur_4=<?=$this->filtre?>')" value="Page pr&eacute;c&eacute;dente">
			   <? endif; ?>
			   <? if ($this->suivantOk === true) : ?>
			   <input type="button" class='button1' onClick="Javascript:_get_('/interface/load/?box=box_messagerie&valeur_1=s&valeur_2=<?=$this->filtre ?>&valeur_3=<?=$this->page ?>&valeur_4=<?=$this->filtre?>')" value="Page suivante">
			   <? endif; ?>
		    </th>
		  </tr>
	</tfoot>
	<tbody>
	<? if (!empty($this->messages)): ?>
		<? $i = 0;
		   foreach($this->messages as $message): ?>
		   		<? $js="onClick=\"_get_('/messagerie/doaction?caction=do_messagerie_message&valeur_1=message&valeur_2=".$message['id_message']."');\" style='cursor:pointer' title='Lire le message'"; ?>
	  			<tr class="table_liste<?=($i % 2);$i++; ?>">
	  				<td class="table_liste">
	  					<? if ($message["toread"] == "0") :?>
		  					<img alt="&Agrave; lire" title="&Agrave; lire" src="/public/images/uddeim/new_im.gif" border="0" 
							<?=$js ?>>
	  					<? else: ?>
							<img alt="D&eacute;j&agrave; lu" title="D&eacute;j&agrave; lu" src="/public/images/uddeim/nonew_im.gif" border="0" 
							<?=$js ?>>
						<? endif; ?>
					</td>
	  				<td class="table_liste" <?=$js ?>">
	  					<? if ($this->filtre == $this->config->messagerie->message->type->supprime): ?>
		  					De <? if (mb_strlen($message["expediteur"]) > 25) echo mb_substr(htmlspecialchars($message["expediteur"]), 0, 25)."..."; else echo htmlspecialchars($message["expediteur"]);?>&nbsp;
		  					&agrave;<br/>
		  					<? if (mb_strlen($message["destinataire"]) > 25) echo mb_substr(htmlspecialchars($message["destinataire"]), 0, 25)."..."; else echo htmlspecialchars($message["destinataire"]);?>&nbsp;
	  					<? elseif ($this->filtre == $this->config->messagerie->message->type->envoye): ?>
	  						<? if (mb_strlen($message["destinataire"]) > 25) echo mb_substr(htmlspecialchars($message["destinataire"]), 0, 25)."..."; else echo htmlspecialchars($message["destinataire"]);?>&nbsp;
	  					<? else: ?>
	  						<? if (mb_strlen($message["expediteur"]) > 25) echo mb_substr(htmlspecialchars($message["expediteur"]), 0, 25)."..."; else echo htmlspecialchars($message["expediteur"]);?>&nbsp;
	  					<? endif; ?>
	  				</td>
	  				<td class="table_liste" <?=$js ?>"> <?if (mb_strlen($message["titre"]) > 25) echo Bral_Util_BBParser::bbcodeStrip(mb_substr($message["titre"], 0, 25))."..."; else echo Bral_Util_BBParser::bbcodeStrip($message["titre"]);?></td>
	  				<td class="table_liste" <?=$js ?>"> le <?=date('d/m/y, H:i', $message["date"]);?></td>
	  				<td class="table_liste">
						<? if ($this->filtre != $this->config->messagerie->message->type->supprime): ?>
							<img src="/public/images/uddeim/forward.gif" alt="Transf&eacute;rer" title="Transf&eacute;rer"onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=transferer&valeur_2=<?=$message["id_message"];?>");' style="cursor:pointer"><br>
							<img src="/public/images/uddeim/trash.gif" alt="Effacer" title="Effacer" onClick='javascript:_get_("/messagerie/askaction?caction=do_messagerie_message&valeur_1=supprimer&valeur_2=<?=$message["id_message"];?>");' style="cursor:pointer">
						<? endif; ?>
					</td>
	  			</tr>
		  	<? endforeach; ?>
		<? else: ?>
   		<tr class="table_liste">
   			<td colspan="5">Aucun message</td>
   		</tr>
   		<? endif; ?>
	</tbody>
</table>
<? endif; ?>
<br>