
<? if ($this->pageCount): ?>
<div id="paginationControl">

<!-- Previous page link --> 
<? if (isset($this->previous)): ?> 
  <label class="alabel" onClick='Javascript:filtre=$("messagerie_filtre").value;_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_2="+filtre+"&valeur_3=<?=$this->previous ?>&valeur_4="+filtre)'>
  &lt; <? echo "précédent"; ?></label> | 
<? else: ?> 
  <span class="disabled">&lt; <? echo "précédent"; ?></span> | 
<? endif; ?> 

<!-- Numbered page links -->
<? foreach ($this->pagesInRange as $page): ?> 
  <? if ($page != $this->current): ?>
    <label class="alabel" onClick='Javascript:filtre=$("messagerie_filtre").value;_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_2="+filtre+"&valeur_3=<?=$page ?>&valeur_4="+filtre)'>
    <? echo $page; ?></label> |  
  <? else: ?>
    <span class="current"><? echo $page; ?></span> | 
  <? endif; ?>
<? endforeach; ?>

<!-- Next page link --> 
<? if (isset($this->next)): ?>
  <label class="alabel" onClick='Javascript:filtre=$("messagerie_filtre").value;_get_("/interface/load/?box=box_messagerie&valeur_1=page&valeur_2="+filtre+"&valeur_3=<?=$this->next ?>&valeur_4="+filtre)'>
  	suivant &gt;</label>
<? else: ?> 
  <span class="disabled"><? echo "suivant" ?> &gt;</span>
<? endif; ?> 
</div> 
<? endif; ?>
