<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Hobbits</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
		<br /><br />
			<table  align='center'>
			<? foreach ($this->hobbits as $h) : ?>
			<? foreach ($h as $key => $value) : ?>
			<th class='comp_titre'><?=$key?></th>
			<? endforeach; ?>
			<? break;endforeach; ?>
			
			<? foreach ($this->hobbits as $h) : ?>
			<tr>
			<? foreach ($h as $key => $value) : ?>
			<? if ($key=="id_hobbit"):
				$id_hobbit = $value;
			   endif; ?>
					<td style='cursor:pointer' onClick='document.location.href="/administrationHobbits/Hobbit/mode/simple/idhobbit/<?=$id_hobbit ?>"'>
					<?=$value ?></td>
			<? endforeach; ?>
			</tr>
			<? endforeach; ?>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>