<div class='comp_titre'>Acad&eacute;mie</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
  Pour <?=$this->paUtilisationLieu ?> PA, le professeur <br />
  vous propose d'am&eacute;liorer une caract&eacute;ristique.<br /><br />
 
 <? if ($this->user->pi_academie_hobbit > 0) : ?>
 Pour information, vous avez déjà dépensé <?=$this->user->pi_academie_hobbit?> PI à l'académie.<br><br>
 <? endif;?>
 
 <? if ($this->user->niveau_hobbit > 20 && $this->user->niveau_hobbit < Bral_Util_Niveau::NIVEAU_MAX) : ?>
 	Une fois que vous aurez atteint le niveau <?=Bral_Util_Niveau::NIVEAU_MAX?>, vous ne pourrez plus obtenir de nouveaux PI.
 	Vous aurez à ce moment là, en comptant les PI déjà dépensés, la possibilité de dépenser <?=Bral_Util_Niveau::NB_PI_NIVEAU_MAX?> en tout à l'académie.
 	<br><br>
 <? elseif ($this->user->niveau_hobbit >= Bral_Util_Niveau::NIVEAU_MAX) : ?>
 	Vous avez atteint le niveau <?=Bral_Util_Niveau::NIVEAU_MAX?>, vous ne pouvez plus gagner de nouveau PI.<br>
 	Il vous reste <?=$this->user->pi_hobbit?> PI à dépenser à l'académie.<br><br>
 <? endif;?>
 
 Vous avez actuellement <?=$this->user->pi_hobbit?> PI à dépenser.<br><br>
 
 <? if ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PA<br /><br />
 <? elseif ($this->achatPossibleCumul == false) : ?>
 	Vous ne pouvez déjà dépensé <?=$this->user->pi_academie_hobbit?> PI, vous ne pouvez plus vous améliorer<br /><br />
 <? elseif ($this->achatPossible == false): ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PI ou de castars<br /><br />
 <? endif; ?>
 
  <? if ($this->utilisationPaPossible === true && $this->achatPossible === true): ?>
  Choisissez une caract&eacute;ristique ci-dessous :<input style='display:none' type='radio' name='valeur_1' id='valeur_1' value='-1' onChange="$('bouton_academie').disabled=true;" checked>
  <? endif ?>
  
   <ul class="ligne_espace">
   Agilit&eacute; (AGI): <?=$this->coutPIAgilite?> PI et <?=$this->coutCastarsAgilite?> castar<? if ($this->coutCastarsAgilite > 1): echo "s"; endif; ?>
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleAgilite === true): ?>
     <? if ($this->coutAgilite <= $this->user->pi_hobbit): ?>
      <input type="radio" name="valeur_1" id="valeur_1" value="AGI" onChange="$('bouton_academie').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif; ?>
    </ul>
    <ul class="ligne_espace">
    Force (FOR) : <?=$this->coutPIForce?> PI et <?=$this->coutCastarsForce?> castar<? if ($this->coutCastarsForce > 1): echo "s"; endif; ?>
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleForce === true): ?>
     <? if ($this->coutForce <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="FOR" onChange="$('bouton_academie').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
    </ul>
    <ul class="ligne_espace">
	Vigueur (VIG) : <?=$this->coutPIVigueur?> PI et <?=$this->coutCastarsVigueur?> castar<? if ($this->coutCastarsVigueur > 1): echo "s"; endif; ?>
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleVigueur === true): ?>
     <? if ($this->coutVigueur <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="VIG" onChange="$('bouton_academie').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
       </ul>
    <ul class="ligne_espace">
    Sagesse (SAG) :  <?=$this->coutPISagesse?> PI et <?=$this->coutCastarsSagesse?> castar<? if ($this->coutCastarsSagesse > 1): echo "s"; endif; ?>
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleSagesse === true): ?>
     <? if ($this->coutSagesse <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="SAG" onChange="$('bouton_academie').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
 </div> 
</form>

<? if ($this->utilisationPaPossible === true && ($this->achatPossible === true)): ?>
<input type='button' class='button1' id="bouton_academie" value="S'am&eacute;liorer !" onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_academie');"  disabled>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>