<div class='comp_titre'>Acad&eacute;mie</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
  Pour <?php echo $this->paUtilisationLieu ?> PA, le professeur <br />
  vous propose d'am&eacute;liorer une caract&eacute;ristique.<br /><br />
 
 <?php if ($this->user->pi_academie_braldun > 0) : ?>
 Pour information, vous avez déjà dépensé <?php echo $this->user->pi_academie_braldun?> PI à l'académie.<br /><br />
 <?php endif;?>
 
 <?php if ($this->user->niveau_braldun < Bral_Util_Niveau::NIVEAU_MAX) : ?>
 	Une fois que vous aurez atteint le niveau <?php echo Bral_Util_Niveau::NIVEAU_MAX?>, vous ne pourrez plus obtenir de nouveaux PI.
 	Vous aurez à ce moment là, en comptant les PI déjà dépensés, la possibilité de dépenser <?php echo Bral_Util_Niveau::NB_PI_NIVEAU_MAX?> en tout à l'académie.
 	<br /><br />
 <?php elseif ($this->user->niveau_braldun >= Bral_Util_Niveau::NIVEAU_MAX) : ?>
 	Vous avez atteint le niveau <?php echo Bral_Util_Niveau::NIVEAU_MAX?>, vous ne pouvez plus gagner de nouveau PI.<br />
 	Il vous reste <?php echo $this->user->pi_braldun?> PI à dépenser à l'académie.<br /><br />
 <?php endif;?>
 
 Connaissez-vous la spécialisation ? <br /><br />
 
 L'idée est la suivante : un Braldûn qui privilégie les améliorations dans une caractéristique 
 en particulier s'oriente vers un profil. Plus il investit et plus il devient bon dans cette caractéristique.
 
 <table align="center" class="table_liste" style="width:90%">
 	<thead class="table_liste">
 	<tr class="table_liste">
 		<td>Niveaux / Caracs</td>
 		<td>FOR</td>
 		<td>AGI</td>
 		<td>VIG</td>
 		<td>SAG</td>
 	</tr>
 	</thead>
 	<?php $i = 0;?>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">13</td>
	 	<td class="table_liste">+2 FOR</td>
	 	<td class="table_liste">+2 AGI</td>
	 	<td class="table_liste">+2 VIG</td>
	 	<td class="table_liste">+2 SAG</td>
 	</tr>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">16</td>
	 	<td class="table_liste">+3 FOR <br />+3 DEG</td>
	 	<td class="table_liste">+3 AGI <br />+3 DEF</td>
	 	<td class="table_liste">+3 VIG <br />+3 REG</td>
	 	<td class="table_liste">+3 SAG <br />Tour : -20min</td>
 	</tr>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">20</td>
	 	<td class="table_liste">+10 DEG</td>
	 	<td class="table_liste">+10 DEF</td>
	 	<td class="table_liste">+10 REG</td>
	 	<td class="table_liste">Tour : -100min</td>
 	</tr>
 </table>
 
 <br />
 Par exemple, si vous avez un niveau 16 en force, vous aurez un bonus de +5 en Force et de +3 en dégâts. 
 Les bonus sont cumulatifs.
 <br /><br />
 Vous avez actuellement <?php echo $this->user->pi_braldun?> PI à dépenser.<br /><br />
 
 <?php if ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PA<br /><br />
 <?php elseif ($this->achatPossibleCumul == false) : ?>
 	Vous ne pouvez déjà dépensé <?php echo $this->user->pi_academie_braldun?> PI, vous ne pouvez plus vous améliorer<br /><br />
 <?php elseif ($this->achatPossible == false): ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PI ou de castars<br /><br />
 <?php endif; ?>
 
  <?php if ($this->utilisationPaPossible === true && $this->achatPossible === true): ?>
  Choisissez une caract&eacute;ristique ci-dessous :<input style='display:none' type='radio' name='valeur_1' id='valeur_1' value='-1' onchange="$('#bouton_academie').attr('disabled', true);" checked>
  <?php endif ?>
  <hr style="width:20%"/>
   <div class="ligne_espace">
   Agilit&eacute; (AGI) : Actuellement niveau <?php echo $this->user->agilite_base_braldun?>. <br />
   Achat d'un niveau : <?php echo $this->coutPIAgilite?> PI et <?php echo $this->coutCastarsAgilite?> castar<?php if ($this->coutCastarsAgilite > 1): echo "s"; endif; ?>
   <?php if ($this->utilisationPaPossible === true && $this->achatPossibleAgilite === true): ?>
     <?php if ($this->coutAgilite <= $this->user->pi_braldun): ?>
      <input type="radio" name="valeur_1" id="valeur_1" value="AGI" onchange="$('#bouton_academie').attr('disabled',false);">
     <?php else :?>
       Trop cher !
     <?php endif;?>
   <?php endif; ?>
    </div>
    <hr style="width:20%"/>
    <div class="ligne_espace">
    Force (FOR) : Actuellement niveau <?php echo $this->user->force_base_braldun?>. <br />
   Achat d'un niveau : <?php echo $this->coutPIForce?> PI et <?php echo $this->coutCastarsForce?> castar<?php if ($this->coutCastarsForce > 1): echo "s"; endif; ?>
   <?php if ($this->utilisationPaPossible === true && $this->achatPossibleForce === true): ?>
     <?php if ($this->coutForce <= $this->user->pi_braldun): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="FOR" onchange="$('#bouton_academie').attr('disabled',false);">
     <?php else :?>
       Trop cher !
     <?php endif;?>
   <?php endif;?>
    </div>
    <hr style="width:20%"/>
    <div class="ligne_espace">
	Vigueur (VIG) : Actuellement niveau <?php echo $this->user->vigueur_base_braldun?>. <br />
   Achat d'un niveau : <?php echo $this->coutPIVigueur?> PI et <?php echo $this->coutCastarsVigueur?> castar<?php if ($this->coutCastarsVigueur > 1): echo "s"; endif; ?>
   <?php if ($this->utilisationPaPossible === true && $this->achatPossibleVigueur === true): ?>
     <?php if ($this->coutVigueur <= $this->user->pi_braldun): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="VIG" onchange="$('#bouton_academie').attr('disabled',false);">
     <?php else :?>
       Trop cher !
     <?php endif;?>
   <?php endif;?>
       </div>
       <hr style="width:20%"/>
    <div class="ligne_espace">
    Sagesse (SAG) : Actuellement niveau <?php echo $this->user->sagesse_base_braldun?>. <br />
    Achat d'un niveau : <?php echo $this->coutPISagesse?> PI et <?php echo $this->coutCastarsSagesse?> castar<?php if ($this->coutCastarsSagesse > 1): echo "s"; endif; ?>
   <?php if ($this->utilisationPaPossible === true && $this->achatPossibleSagesse === true): ?>
     <?php if ($this->coutSagesse <= $this->user->pi_braldun): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="SAG" onchange="$('#bouton_academie').attr('disabled',false);">
     <?php else :?>
       Trop cher !
     <?php endif;?>
   <?php endif;?><br /><br />
   Informations : <br />
   A partir du niveau 13 en sagesse, des compétences deviennent disponibles gratuitement à la bibliothèque.<br />
   <a href='http://regles.braldahim.com/wiki/Dissuader'>Compétence Dissuader</a>.<br />
   <a href='http://regles.braldahim.com/wiki/Psychologie'>Compétence Psychologie</a>.<br />
   <a href='http://regles.braldahim.com/wiki/R%C3%A9animer'>Compétence Réanimer</a>.<br />
 </div>
 </div> 
</form>

<?php if ($this->utilisationPaPossible === true && ($this->achatPossible === true)): ?>
<input type='button' class='button1' id="bouton_academie" value="S'am&eacute;liorer !" onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_academie');"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>