<div class='comp_titre'>Ahenne Peheux</div>
 <form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='voir'>
 <div class='comp_contenu'>
 </div> 
</form>
<br> 
<input type='button' value='Action TODO' onClick='_get_("/lieux/DoAction?caction=do_lieu_ahennepeheux");'>
<input type='button' value='Annuler' onClick='_get_("/interface/clear");'>