<div class='comp_titre'>Ahenne Peheux</div>

 <div class='comp_contenu'>
	 <div id='lieu_text' style="display:block"  onClick="javascript:switch2div('lieu_text','lieu_copie');">
		<? if($this->apprentissageMetier === true) : ?>
			Vous avez appris le m&eacute;tier suivant :<br>
			<?=htmlentities($this->nomMetier) ?>
			<br><br>
			C'est &eacute;galement votre m&eacute;tier courant<br>
			Il vous reste <?=$this->user->castars_hobbit; ?>
			<? if ($this->user->castars_hobbit == 0): ?>
			castar
			<? else: ?>
			castars
			<? endif; ?>
			<br>
			<? if ($this->constructionCharrette === true): ?>
				De plus, vous avez r&eacute;cup&eacute;r&eacute; une charrette !
			<? endif; ?>
			<? if ($this->constructionEchoppe === true): ?>
				De plus, vous pouvez construire une &eacute;choppe !
			<? endif; ?>
		<? elseif ($this->changementMetier === true) : ?>
			Votre m&eacute;tier courant est maintenant :<br>
			<?=htmlentities($this->nomMetier) ?>
		<? endif; ?>
	 </div>
	 
	 <div id='lieu_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><? 
			if($this->apprentissageMetier === true) {
				echo "Vous avez appris le m&eacute;tier suivant : ";
				echo htmlentities($this->nomMetier);
				echo " 
";
				echo "C'est &eacute;galement votre m&eacute;tier courant";
				echo " 
";
				echo "Il vous reste ".$this->user->castars_hobbit;
				if ($this->user->castars_hobbit == 0) {
					echo " castar";
				} else {
					echo " castars";
				}
				
				if ($this->constructionCharrette === true) {
					echo "
";
					echo "De plus, vous avez r&eacute;cup&eacute;r&eacute; une charrette !";
				}
				if ($this->constructionEchoppe === true) {
					echo "
";
					echo "De plus, vous avez pouvez construire une &eacute;choppe !";
				}
			}elseif ($this->changementMetier === true) {
				echo "Votre m&eacute;tier courant est maintenant :";
				echo htmlentities($this->nomMetier);
			}
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('lieu_text','lieu_copie');">
<? if ($this->constructionCharrette === true || $this->constructionEchoppe): ?>
	<input type='button' class='button1' value='Fermer' onClick='_get_("/interface/reloadInterface");Modalbox.hide();'>
<? else: ?>
	<? include("commun_fermer.phtml") ?>
<? endif; ?>

