<? if($this->apprentissageMetier === true) : ?>
	Vous avez appris le m&eacute;tier suivant :<br />
	<?=$this->nomMetier ?>
	<br /><br />
	C'est &eacute;galement votre m&eacute;tier courant<br />
	Il vous reste <?=$this->user->castars_hobbit; ?>
	<? if ($this->user->castars_hobbit == 0): ?>
	castar
	<? else: ?>
	castars
	<? endif; ?>
	<br />
	<? if ($this->constructionCharrette === true): ?>
		De plus, vous avez r&eacute;cup&eacute;r&eacute; une charrette !
	<? endif; ?>
	<? if ($this->constructionEchoppe === true): ?>
		De plus, vous pouvez construire une &eacute;choppe !
	<? endif; ?>
<? elseif ($this->changementMetier === true) : ?>
	Votre m&eacute;tier courant est maintenant :<br />
	<?=$this->nomMetier ?>
<? endif; ?>