<div class='comp_titre'>L'Assembleur</div>
<br />
Pour <?php echo $this->coutCastars?> castars, vous avez assembl&eacute; <br />
le matériel n°<?php echo $this->materielAAssembler["id_materiel"]?>, <?php echo $this->materielAAssembler["nom_type_materiel"]?> sur le mat&eacute;riel n°
<?php echo $this->materielBase["id_materiel"]?>, <?php echo $this->materielBase["nom_type_materiel"]?>.<br /><br />
 
Faites-en bon usage...