<div class='comp_titre'>Auberge</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?php echo $this->coutCastars?> castars et <?php echo $this->paUtilisationLieu ?> PA, vous pouvez vous restaurer
 	et, si vous le souhaitez, acheter des ragoûts (&agrave; <?php echo $this->coutCastars?> castars l'unit&eacute;). <br /><br />

   	Vous avez <?php echo $this->user->castars_braldun ?> castar<?php if ($this->user->castars_braldun > 1): echo "s"; endif; ?> et <?php echo $this->poidsRestant?> Kg de poids transportable disponible.<br />
   	
	<br /><br />
	<?php if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars !<br />
   	<?php elseif ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<?php else: ?> 

   		<?php if ($this->nbPossible > 0) :?>
   		Vous pouvez acheter au maximum <?php echo $this->nbPossible ?> ragoût<?php if ($this->nbPossible > 1): echo "s"; endif; ?> 
   			<?php if ($this->nbDeduction > 0) :?>
   				(<?php echo $this->nbPossible - $this->nbDeduction?> si vous prenez un repas sur place).
   			<?php endif; ?>
   		<br /><br />
 	 	<?php else: ?>
	    	Vous ne pouvez pas acheter de ragoût &agrave; emporter<br /><br />
	    	<input type='hidden' name='valeur_2' id='valeur_2' value='0'>
	   	<?php endif; ?>
		
		<input type='hidden' value='Faites un choix' id='bouton_-1'>
		<?php foreach ($this->tabChoix as $k => $t) : ?>
			<input type='hidden' value='<?php echo $t["bouton"]?>' id='bouton_<?php echo $k?>'>
		<?php endforeach; ?>
		
		<?php
		$max = $this->nbPossible - $this->nbDeduction;
		$js = "var type=$('#valeur_3').val();";
		$js .= "if (type != -1 && $('#valeur_2').val() > $('#nb_max_' + type).val() || $('#valeur_2').val() == 0){ $('#bouton_auberge').attr('disabled', true) };";
		$js .= "if ($('#valeur_1').val() == 3 && $('#valeur_2').val() == ".$this->nbPossible."){ $('#valeur_2').val(".$max.") };";
		?>
	   	Choix : <br />
	   	<select name='valeur_1' id="valeur_1" onchange="javascript:$('#bouton_auberge').val($('#bouton_'+this.value).val());if ($('#valeur_1').val() ==-1 && $('#valeur_2').val() ==0 || ($('#valeur_3').val() ==-1 && $('#valeur_1').val() !=1 )){$('#bouton_auberge').attr('disabled', true) } else {$('#bouton_auberge').attr('disabled',false) };if ($('#valeur_1').val() ==2 || $('#valeur_1').val() ==3) {$('#nbAliment').show()} else { $('#nbAliment').hide()};<?php echo $js;?>">
		<option value='-1'>(Choix &agrave; faire)</option>
			<?php foreach ($this->tabChoix as $k => $t) : ?>
				<option value="<?php echo $k?>" <?php if ($t["valid"] === false): echo "disabled"; endif;?>><?php echo $t["nom"]?> <?php if ($t["valid"] === false): echo " (impossible)"; endif;?></option>
			<?php endforeach; ?>
		</select>
		<br /><br />

	   	<div id="nbAliment" style="display:none">
	   	Nombre de ragoûts &agrave; acheter  :
	 	 <br />
		 <input type='text' maxlength='7' size='7' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event);"  onkeyup="if ((this.value >= 0 && this.value <=<?php echo $this->nbPossible  ?> && ($('#valeur_1').val() ==2) || ($('#valeur_1').val() ==3) && this.value >= 0 && this.value <=<?php echo $this->nbPossible - $this->nbDeduction ?> ) && $('#valeur_3').val() !=-1) {$('#bouton_auberge').attr('disabled',false)} else {$('#bouton_auberge').attr('disabled', true)};<?php echo $js;?> ">
		 <br />
		 <br />
		 	Destination : <br />
		 	<?php 
		 	$options = "";
		 	$input = "";
		 	foreach($this->destinationTransfert as $d) {
				$options .= "<option value='".$d["id_destination"]."'";
				if ($d["possible"] == false) {
					$options .= " disabled='true' ";
				}
				if (count($this->destinationTransfert) == 1){
					$options .= " selected='true' ";
				}
				$options .= ">";
				$options .= $d["texte"]." ".$d["poids_restant"]." Kg dispo ";
				if ($d["possible"] == false) {
					$options .= " : pas assez de place";
				}
				else {
					$options .= " (".$d["nb_possible"]." rations possible max)"; 
				}
				$options .= "</option>";
				
				$input .= "<input type='hidden' id='nb_max_".$d["id_destination"]."' value='".$d["nb_possible"]."'/>";
			}
			?>
			<select name="valeur_3" id="valeur_3" onchange="if (this.value != -1) {$('#bouton_auberge').attr('disabled', false)} else { $('#bouton_auberge').attr('disabled', 'disabled')};<?php echo $js;?>">
		 		<option value="-1">(Choisissez une destination)</option>
		 		<?php echo $options;?>
			</select>
			<?php echo $input;?>		
	    </div>

	<?php endif;?>
	<br />
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_auberge" value='Faites un choix' onclick="if ($('#valeur_2').val() <= 0 && ($('#valeur_1').val() == 2 || $('#valeur_1').val() == 3)) { alert('Entrez un nombre de ragoût > 0 ou sélectionnez \'Se restaurer uniquement\'')} else {this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_auberge');}"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>