<div class='comp_titre'>Auberge</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?=$this->coutCastars?> castars et <?=$this->paUtilisationLieu ?> PA, vous pouvez vous restaurer
 	et, si vous le soutaitez, acheter des rations (&agrave; <?=$this->coutCastars?> castars l'unit&eacute;) <br /><br />
   	
   	Vous avez <?=$this->user->castars_hobbit ?> castar<? if ($this->user->castars_hobbit > 1): echo "s"; endif; ?> et <?=$this->poidsRestant?> Kg de poids transportable disponible.<br>
   		
	<? if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars <br />
   	<? elseif ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA <br />
   	<? elseif ($this->nbPossible > 0) :?>
   		Vous pouvez acheter au maximum <?=$this->nbPossible ?> ration<? if ($this->nbPossible > 1): echo "s"; endif; ?>.<br><br>
   	
 	 	Nombre de rations &agrave; acheter (<?=$this->nbPossible ?> maximum) :
	 	 <br>
		 <input type='text' maxlength='7' size='7' name='valeur_1' id='valeur_1' value='0' onkeypress="chiffres(event);"  onkeyup="if (this.value >= 0 && this.value <=<?=$this->nbPossible  ?>) {$('bouton_auberge').disabled=false} else {$('bouton_auberge').disabled=true} ">   		
    <? else: ?>
    	Vous ne pouvez pas acheter de ration... <br>
   	<? endif; ?>
 </div> 
</form>
<br /> 

<? if ($this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_auberge" value='Se restaurer !' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_auberge');"  <? if ($this->utilisationPossible == false) echo "disabled"?>>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>