	<? if ($this->idChoix == 1 || $this->idChoix == 3) :?>
		Vous vous &ecirc;tes restaur&eacute;<br /> <br />
		Votre balance de faim est maintenant de <?=$this->user->balance_faim_hobbit ?> %<br /><br>
	<? endif;?>
	
	<? if ($this->idChoix == 2 || $this->idChoix == 3) : ?>
		Vous avez achet&eacute; <?=$this->nbAcheter ?>  ration<? if ($this->nbAcheter > 1): echo "s"; endif; ?> <br><br>
	<? endif;?>
	Vous avez d&eacute;pens&eacute; <?=$this->coutCastars ?> castars.