<div class='comp_titre'>Auberge</div>

 <div class='comp_contenu'>
	 <div id='lieu_text' style="display:block"  onClick="javascript:switch2div('lieu_text','lieu_copie');">
	Vous vous &ecirc;tes restaur&eacute;<br> <br>
	Votre balance de faim est maintenant de <?=$this->user->balance_faim_hobbit ?> %<br>
	 </div>
	 
	 <div id='lieu_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><? 
			echo "Vous vous &ecirc;tes restaur&eacute;";
			echo "
";
			echo " Votre balance de faim est maintenant de ".$this->user->balance_faim_hobbit ." %";
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('lieu_text','lieu_copie');">
<? include("commun_fermer.phtml") ?>