 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='5'>
 <div class='comp_contenu'>
	 
	 <ul class="titre textalic textsizec">Retirer des &eacute;l&eacute;ments du coffre</ul>
	 <br>
	 Pour <?=$this->paUtilisationLieu ?> PA, vous pouvez retirer des objets de votre coffre pour les
	 mettre dans votre laban. <br /><br />
	 
	 <?php if ($this->utilisationPaPossible == true) : ?>
		 <select name="valeur_1" id="valeur_1"  onChange="if ($('bouton_ramasser')) {$('bouton_ramasser').disabled=true} ;_get_('/lieux/doaction?caction=ask_lieu_banqueretirer&valeur_1='+this.value);">
		 	<option value="-1">(Choisis un &eacute;l&eacute;ment)</option>
		 	<? foreach($this->typeElements as $t) : ?>
		 		<option value="<?=$t["id_type_element"]?>" <? if ($t["selected"] == $t["id_type_element"]): echo "selected"; endif;?>><?=htmlspecialchars($t["nom_element"])?></option>
		 	<? endforeach; ?>
		 </select>
		 <br /><br />
		 
		 <? if ($this->type != null) : ?>
		 	<?=$this->render("/competences/ramasser/" . $this->type . ".phtml"); ?>
		 	 <br /> <br />
			<? if ($this->ramasserOk === false) : ?>
				Il n'y a rien &agrave; retirer
			<? elseif ($this->poidsPlaceDisponible === false) : ?>
				Vous n'avez pas assez de place dans votre laban
			<? endif; ?>
		 <? endif ?>
	<? endif; ?>
	 
</div>

<br />
<?php if ($this->utilisationPaPossible == true && $this->ramasserOk === true && $this->poidsPlaceDisponible === true) : ?>
<input type='button' class='button1' id='bouton_ramasser' value='Retirer !' onClick='this.disabled=true;_get_("/lieux/doaction?caction=do_lieu_banqueretirer");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>