<div class='comp_titre'>B&eacute;hennep&eacute;e</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value=''>
 <div class='comp_contenu'>

 	<ul class="titre textalic textsizec">Construction d'&eacute;choppes</ul>
 	<br />
 	
 	<? if ($this->construireMetierPossible !== true) :?>
		Vous ne pouvez pas construire d'&eacute;choppe avec votre m&eacute;tier courant...
 	<? elseif ($this->nEchoppes < 1) : ?>
 		Vous ne poss&eacute;dez pas encore d'&eacute;choppe. La premi&egrave;re est gratuite (<?=$this->coutCastars?> castar).<br /><br />
 	<? else: ?>
 		Pour <?=$this->paUtilisationLieu?> PA et <?=$this->coutCastars?> castars, vous pouvez constuire une nouvelle &eacute;choppe.<br /><br />
 	<? endif; ?>

	<? if ($this->construireMetierPossible !== true) :?>
		<!-- rien ici -->
   	<? elseif ($this->achatPossible === false || $this->utilisationPaPossible === false): ?>
   		<? if ($this->achatPossible === false) : ?>
   		Vous n'avez pas assez de castars. <br />
   		<? endif;?>
   		<? if ($this->utilisationPaPossible === false) : ?>
   		Vous n'avez pas assez de PA. <br />
   		<? endif; ?>
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<? else : ?>
	 	<? if ($this->construireMetierPossible === true && $this->aucuneEchoppe === true) : ?>
			 Dans cette comt&eacute; (<?=$this->tabRegionCourante["nom_region"]?>),
			 vous pouvez construire une &eacute;choppe
			<? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>
			<?=$this->nom_metier_courant ?>.<br /><br />

			Indiquez la position de l'&eacute;choppe : <br />
			X = <input type='textbox' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='' onkeypress="chiffres(event, true);if($('valeur_2').value=='' || $('valeur_3').value=='') {$('construire_echoppe').disabled=true} else {$('construire_echoppe').disabled=false};">
			<br />
			Y = <input type='textbox' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='' onkeypress="chiffres(event, true);if($('valeur_2').value=='' || $('valeur_3').value=='') {$('construire_echoppe').disabled=true} else {$('construire_echoppe').disabled=false};">
			<br />
		<? else: ?>
			<? if ($this->aucuneEchoppe == false) : ?>
				Vous poss&eacute;dez d&eacute;j&agrave; une &eacute;choppe pour ce m&eacute;tier dans
				cette r&eacute;gion.
			<? else: // doit jamais arriver, mais a cas où... ?>
				Vous ne pouvez pas construire d'&eacute;choppe avec votre m&eacute;tier courant...
			<? endif; ?>
		<? endif; ?>
	<? endif; ?>
 </div>
</form>
<br />

<? if ($this->construireMetierPossible === true && $this->aucuneEchoppe === true && $this->utilisationPaPossible === true && $this->achatPossible === true) : ?>
<input type='button' class='button1' id="construire_echoppe" value='Construire une &eacute;choppe' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_behennepee');" disabled>
<? endif; ?>
<br />
<? echo Bral_Helper_Fermer::affiche(); ?>