<div class='comp_titre'>B&eacute;hennep&eacute;e</div>

 <div class='comp_contenu'>
	 <div id='behennepee_text' style="display:block"  onClick="javascript:switch2div('behennepee_text','behennepee_copie');">
		
		<? if ($this->constructionEchoppeOk === true): ?>
		Vous avez construit une &eacute;choppe avec succ&egrave;s ! <br><br>
		
		Elle se trouve en x:<?=$this->user->x_hobbit ?> y:<?=$this->user->y_hobbit ?> 
		dans la <?=htmlentities($this->tabRegionCourante["nom_region"]) ?> .<br><br>
		
		C'est une &eacute;choppe <? if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>
		<?=$this->nom_metier_courant ?>
		
		<? elseif ($this->construireLieuOk == false) : ?>
		Un lieu existe en x:, y:, vous ne pouvez pas construire une &eacute;choppe 
		&agrave; cet endroit
		<? elseif ($this->construireRegionOk == false) : ?>
		Vous ne pouvez pas construire d'&eacute;choppe dans une autre comt&eacute; que
		la comt&eacute; <?=$this->regionCourante["nom_region"] ?>
		<? endif; ?>
		
		<br><br>
	 </div>
	 
	 <div id='behennepee_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><? 
			echo "Vous avez construit une &eacute;choppe avec succ&egrave;s !";
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('behennepee_text','behennepee_copie');">
<? include("commun_fermer.phtml") ?>