<div class='comp_titre'>Biblioth&egrave;que</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?=$this->paUtilisationLieu ?> PA et <?=$this->coutCastars?> castars, la Biblioth&egrave;que <br />
  vous propose d'apprendre une nouvelle comp&eacute;tence.<br /><br />
  
  <? if ($this->possedeCompetenceCommune === false): ?>
	  C'est votre première visite, la première compétence est gratuite en PI et en castars!<br><br>
  <? endif; ?>
 
 <? if ($this->nCompetences == 0): ?>
	Il n'y a aucune comp&eacute;tence pour vous...
 <? elseif ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PA<br /><br />
 <? elseif ($this->achatPiPossible == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PI<br /><br />
 <? elseif ($this->achatPossibleCastars == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de Castars<br /><br />
 <? endif; ?>
 
<? if ($this->nCompetences > 0): ?>
 <? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
  Choisissez une comp&eacute;tence ci-dessous <input type='radio' name='valeur_1' id='valeur_1' value='-1' onChange="$('bouton_bibliotheque').disabled=true;" checked style="display:none">
 <? endif; ?>
 <table>
 <? foreach ($this->tabCompetences as $c):?>
   <tr>
     <td><?=$c["nom"]?></td>
     <td nowrap> co&ucirc;t : <?=$c["pi_cout"]?> PI </td>
     <td align='left'>
     <? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $c["trop_cher"] === false && $this->achatPossibleCastars === true): ?>
     	<? if ($c["nom_systeme"] != "pister" || $this->pisterPossible == true) : ?>
       		<input type="radio" name="valeur_1" id="valeur_1" value="<?=$c["id_competence"]?>" onChange="$('bouton_bibliotheque').disabled=false;">
       	<? else :?>
       		(N&eacute;cessite Connaissances des monstres !)
       	<?endif; ?>
     <? endif;?>
     </td>
   </tr>
 <? endforeach; ?>
 </table>
 <? endif; ?>
 
 </div> 
</form>
<br />

<? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
<input type='button' class='button1' id="bouton_bibliotheque" value='Apprendre cette comp&eacute;tence !' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_bibliotheque');"  disabled>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>