<div class='comp_titre'>Biblioth&egrave;que</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?php echo $this->paUtilisationLieu ?> PA et <?php echo $this->coutCastars?> castars, la Biblioth&egrave;que <br />
  vous propose d'apprendre une nouvelle comp&eacute;tence.<br /><br />
  
  <?php if ($this->possedeCompetenceCommune === false): ?>
	  C'est votre première visite, la première compétence est gratuite en castars!<br /><br />
  <?php endif; ?>
  
  <?php if ($this->user->niveau_braldun >= Bral_Util_Niveau::NIVEAU_MAX) : ?>
 	Vous avez atteint le niveau <?php echo Bral_Util_Niveau::NIVEAU_MAX?>, vous devez
 	acheter les nouvelles compétences à l'aide de PX et non de PI.<br /><br />
 <?php endif;?>
 
 <?php if ($this->nCompetences == 0): ?>
	Il n'y a aucune comp&eacute;tence pour vous...
 <?php elseif ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PA<br /><br />
 <?php elseif ($this->achatPiPossible == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de <?php if ($this->user->niveau_braldun >= Bral_Util_Niveau::NIVEAU_MAX) : echo "PX"; else : echo "PI"; endif;?><br /><br />
 <?php elseif ($this->achatPossibleCastars == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de Castars<br /><br />
 <?php endif; ?>
 
<?php if ($this->nCompetences > 0): ?>
 <?php if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
  Choisissez une comp&eacute;tence ci-dessous <input type='radio' name='valeur_1' id='valeur_1' value='-1' onchange="$('#bouton_bibliotheque').attr('disabled', true);" checked style="display:none">
 <?php endif; ?>
 <table>
 <?php foreach ($this->tabCompetences as $c):?>
   <tr>
     <td><a href='http://regles.braldahim.com/wiki/<?php echo $c["nom"]?>'><?php echo $c["nom"]?></a></td>
     <td nowrap> co&ucirc;t : <?php echo $c["pi_cout"]?> <?php if ($this->user->niveau_braldun >= Bral_Util_Niveau::NIVEAU_MAX) : echo "PX"; else : echo "PI"; endif;?> </td>
     <td align='left'>
     <?php if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $c["trop_cher"] === false && $this->achatPossibleCastars === true): ?>
     	<?php if ($c["nom_systeme"] != "pister" || $this->pisterPossible == true) : ?>
       		<input type="radio" name="valeur_1" id="valeur_1" value="<?php echo $c["id_competence"]?>" onchange="$('#bouton_bibliotheque').attr('disabled',false);">
       	<?php else :?>
       		(N&eacute;cessite Connaissances des monstres !)
       	<?php endif; ?>
     <?php endif;?>
     </td>
   </tr>
 <?php endforeach; ?>
 </table>
 <?php endif; ?>
 
 </div> 
</form>
<br />

<?php if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
<input type='button' class='button' id="bouton_bibliotheque" value='Apprendre cette comp&eacute;tence !' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_bibliotheque');"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>