<?php echo $this->render("/commun/commun_quete_resultat.phtml") ?>

<?php if($this->apprentissageMetier === true) : ?>
	Vous avez appris le m&eacute;tier suivant :<br />
	<?php echo $this->nomMetier ?>
	<br /><br />
	C'est &eacute;galement votre m&eacute;tier courant<br />
	Il vous reste <?php echo $this->user->castars_braldun; ?>
	<?php if ($this->user->castars_braldun == 0): ?>
	castar.
	<?php else: ?>
	castars.
	<?php endif; ?>
	<br /><br />
	<?php if ($this->constructionCharrette === true): ?>
		De plus, vous avez r&eacute;cup&eacute;r&eacute; une charrette !
	<?php endif; ?>
	<?php if ($this->constructionEchoppe === true): ?>
		De plus, vous pouvez construire une &eacute;choppe, rendez-vous &agrave; l'Office Notarial !
	<?php endif; ?>
<?php endif; ?>
<?php if ($this->changementMetier === true) : ?>
	<?php if ($this->apprentissageMetier === false) : ?>
		Votre m&eacute;tier courant est maintenant :<br />
		<?php echo $this->nomMetier ?>
	<?php endif; ?>
	<br />Vous avez &eacute;galement perdu 10% sur les comp&eacute;tences de votre ancien m&eacute;tier.
<?php endif; ?>