<? if($this->apprentissageMetier === true) : ?>
	Vous avez appris le m&eacute;tier suivant :<br />
	<?=$this->nomMetier ?>
	<br /><br />
	C'est &eacute;galement votre m&eacute;tier courant<br />
	Il vous reste <?=$this->user->castars_hobbit; ?>
	<? if ($this->user->castars_hobbit == 0): ?>
	castar
	<? else: ?>
	castars
	<? endif; ?>
	<br />
	<? if ($this->constructionCharrette === true): ?>
		De plus, vous avez r&eacute;cup&eacute;r&eacute; une charrette !
	<? endif; ?>
	<? if ($this->constructionEchoppe === true): ?>
		De plus, vous pouvez construire une &eacute;choppe (rendez-vous &agrave; l'Office Notarial)!
	<? endif; ?>
<? endif; ?>
<? if ($this->changementMetier === true) : ?>
	<? if ($this->apprentissageMetier === false) : ?>
		Votre m&eacute;tier courant est maintenant :<br />
		<?=$this->nomMetier ?>
	<? endif; ?>
	<br />Vous avez &eacute;galement perdu 10% sur les comp&eacute;tences de votre ancien m&eacute;tier.
<? endif; ?>