<div class='comp_titre'>Centre de Formation</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value=''>
 <div class='comp_contenu'>
 
 	<br />
 	<b>Information pratique</b> : <br />
 	Vous trouverez dans le 
 	<span class='alabel' onclick="javascript:ouvrirWin('http://www.braldahim.com/bourg');" title="Cliquez pour voir le bourg">Bourg</span>, 
 	la <span class='alabel' onclick="javascript:ouvrirWin('http://www.braldahim.com/chambre');" title="Cliquez pour voir la chambre des m&ecute;tiers">Chambre de Métiers</span>
 	 qui vous permettra de voir
 	la r&eacute;partition des m&eacute;tiers pratiqu&eacute;s dans Braldahim.
 
 	<br /><br />
    <?php if (!$this->possedeMetier): ?>
   		Vous ne pratiquez aucun m&eacute;tier <br /><br />
   		<input type='hidden' id='valeur_defaut' name='valeur_defaut' value=''>
   		<input type="hidden" id="valeur_2" name="valeur_2" value="-1">
   		<input type="hidden" id="changer_metier" name="changer_metier" value="-1">
   		
   	<?php else :?>
   		<?php if (count($this->tabMetiers) == 1) : ?>
   			Le m&eacute;tier que vous avez appris <br />
   			<input type="hidden" id="valeur_2" name="valeur_2" value="-1">
   			<input type="hidden" id="changer_metier" name="changer_metier" value="-1">
   		<?php else : ?>
   			Les m&eacute;tiers que vous avez appris <br />
   		<?php endif; ?>
   		<table width='300px' align='center'>
   			<tr>
   			<th class='titre textalic textsized'>Nom</th>
			<th class='titre textalic textsized'>Date d'apprentissage</th>
			<th class='titre textalic textsized'>Changement</th>
			</tr>
	   		<?php foreach ($this->tabMetiers as $m) : ?>
	   		<tr>
				<td><?php echo $m["nom"];?></td>
				<td><?php echo $m["date_apprentissage"];?></td>
				<td>
				<?php if ($m["est_actif"]): ?>
					m&eacute;tier courant <br />
					<input type="radio" id="valeur_defaut" name="valeur_2" value="-1" checked onclick="javascript:$('changer_metier').attr('disabled', true);if ($('apprendre_metier')) $('apprendre_metier').attr('disabled', true);">
				<?php else: ?>
					<input type="radio" id="valeur_2" name="valeur_2" value="<?php echo $m["id_metier"]?>" onclick="javascript:if ($('apprendre_metier')) $('apprendre_metier').attr('disabled', true);$('changer_metier').attr('disabled',false);$('#valeur_3').val('-1')"/>
				<?php endif; ?>
	   			</td>
			</tr>
			<?php endforeach; ?>
		</table>
   	<?php endif; ?>
    <br /><br />

    	<?php if ($this->achatPossible === false): ?>
    		Vous n'avez pas assez de castars <br />
    		Il vous faut <?php echo $this->coutCastars?> castars et <?php echo $this->paUtilisationLieu?> PA pour apprendre un nouveau m&eacute;tier
    		 <input type='hidden' id='valeur_3' name='valeur_3' value='-1'>
    	<?php else : ?>
    	    <?php if (count($this->tabNouveauMetiers) >= 1) : ?>
	    	Pour <?php echo $this->coutCastars?> castars et <?php echo $this->paUtilisationLieu?> PA, <br />
	    	vous pouvez apprendre un nouveau m&eacute;tier : <br />
		    	<select id='valeur_3' name='valeur_3' onchange="javascript:$('changer_metier').attr('disabled', true);$('#valeur_defaut').checked=true;if(this.value!=-1){$('apprendre_metier').attr('disabled',false);} else { $('apprendre_metier.attr('disabled', true)}">
		    		<option value='-1'>(Choisissez un m&eacute;tier)</option>
		    		<?php foreach ($this->tabNouveauMetiers as $t) : ?>
		    			<option value='<?php echo $t["id_metier"]?>' <?php if ($this->user->niveau_braldun < $t["niveau_min_metier"]) :echo 'disabled'; endif;?>><?php echo $t["nom"]?> <?php if ($this->user->niveau_braldun < $t["niveau_min_metier"]) : echo "Niveau minimum requis pour apprendre ce métier: ".$t["niveau_min_metier"]; endif;?> </option>
		    		<?php endforeach; ?>
		    	</select>
		    <?php else : ?>
		    	Vous ne pouvez pas apprendre de m&eacute;tier suppl&eacute;mentaire
		    	<input type='hidden' id='valeur_3' name='valeur_3' value='-1'>
		    <?php endif; ?>
    	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if (count($this->tabMetiers) > 1) : ?>
<input type='button' class='button1' id="changer_metier" value='Changer de m&eacute;tier' onclick="javascript:this.disabled=true;$('#valeur_1').val('changer'); _get_('/lieux/doaction?caction=do_lieu_centreformation');" disabled>
<?php endif; ?>
<?php if ($this->achatPossible === true && count($this->tabNouveauMetiers) >= 1): ?>
<input type='button' class='button1' id="apprendre_metier" value='Apprendre un m&eacute;tier' onclick="this.disabled=true;$('#valeur_1').val('apprendre'); _get_('/lieux/doaction?caction=do_lieu_centreformation');"  disabled>
<?php endif; ?>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>