<div class='comp_titre'>Maison de Contrat</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs-lieu_contrat' value='0'>
 <div class='comp_contenu'>
 
 <br />
 Coût : <?php echo $this->paUtilisationLieu?> PA.<br /><br />
 
 <?php if ($this->utilisationPaPossible == false) : ?>
 	Vous n'avez pas assez de PA.
 <?php elseif ($this->contratEnCours != null) : ?>
 	Vous avez déjà un contrat en cours, vous ne pouvez pas en prendre un autre.
 <?php else: ?>
 	Vos points de Gredin : <?php echo $this->user->points_gredin_braldun?><br />
	Vos points de Redresseur de Torts : <?php echo $this->user->points_redresseur_braldun?><br />
	
	<?php if ($this->type == "gredin") : ?>
		Vous êtes dans une maison pour obtenir un contrat de Gredin.
	<?php else: ?>
		Vous êtes dans une maison pour obtenir un contrat de Redresseur de Torts.
	<?php endif; ?>
	
	<br /><br />
	
	<?php if ($this->utilisationPossible == false) : ?>
		<?php if ($this->type == "gredin") : ?>
			Vous n'avez pas assez de point de Gredin pour obtenir ce type de contrat.
		<?php else: ?>
			Vous n'avez pas assez de point de Redresseur de Torts pour obtenir ce type de contrat.
		<?php endif;?>
		
	<?php elseif ($this->contratDisponible == false) : ?>
		La maison n'a actuellement aucun contrat à vous proposer.
	<?php else: ?>
		Souhaitez-vous prendre un contrat 
		<?php if ($this->type == "gredin") : ?>
			de Gredin
		<?php else: ?>
			de Redresseur de Torts
		<?php endif;?>
		?
	<?php endif;?>
 <?php endif; ?>
  
 </div> 
</form>
<br /> 
<br />
<?php if ($this->utilisationPossible === true && $this->utilisationPaPossible === true && $this->contratDisponible == true) : ?>
	<input type='button' class='button1' id="bouton_contrat" value='Obtenir le contrat' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_contrat', 'lieu_contrat', true);">
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>