<div class='comp_titre'>Glourte Pieds Visqueux</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?=$this->paUtilisationLieu ?> PA et quelques castars, Glourte Pieds Visqueux vous propose d'échanger
 trois runes identiques contre une rune d'un niveau supérieur. Attention, seules des runes de certaines raret&eacute;s sont &eacute;changeables.<br /><br />
 
 <? if ($this->utilisationPaPossible === true) : ?>
	 Vous avez actuellement <?=$this->user->castars_braldun?> castar<? if ($this->user->castars_braldun > 1): echo "s"; endif;?>.<br /><br />
	 
		<? if (count($this->labanRunes) > 0 && $this->tabAAfficher === true) : ?>
			<table>
			 <? foreach ($this->labanRunes as $r): ?>
			 	<? if ($r["a_afficher"] == true): ?>
				   <tr>
				     <td valign="top">
				     <img class="rune" src="/public/images/runes/<?=$r["image_type_rune"]?>" title="<?=$r["nom_type_rune"]?>" alt="<?=$r["nom_type_rune"] ?>"/>
				     <br />
				     3 runes <?=$r["nom_type_rune"]?>
				     <br />
				     co&ucirc;t : <?=$r["cout_castars"]?> castars.
				     <? if ($r["achat_possible"] !== true): ?>
				     	(trop cher)
				     <? endif;?>
				     </td>
				     <td align='left' valign="top">
				     <? if ($this->utilisationPaPossible === true && $r["achat_possible"] === true && $this->achatPossibleCastars === true): ?>
				       		<input type="radio" name="valeur_1" id="valeur_1" value="<?=$r["id_type_rune"]?>" onChange="$('bouton_echangeurrune').disabled=false;">
				     <? endif;?>
				     </td>
				   </tr>
				  <? endif;?>
				<? endforeach; ?>
			 </table>
		<? else: ?>
			Vous n'avez de runes &eacute;changeables dans votre laban.
		<? endif; ?>
	 </div> 
	</form>

<? else :?>
Vous n'avez pas assez de PA.<br />
<? endif; ?>


<? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true && $this->tabAAfficher === true): ?>
<input type='button' class='button1' id="bouton_echangeurrune" value='&Eacute;changer !' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_echangeurrune');"  disabled>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>