<div class='comp_titre'>Glourte Pieds Visqueux</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?php echo $this->paUtilisationLieu ?> PA et quelques castars, Glourte Pieds Visqueux vous propose d'échanger
 trois runes identiques contre une rune d'un niveau supérieur. Attention, seules des runes de certaines raret&eacute;s sont &eacute;changeables.<br /><br />
 
 <?php if ($this->utilisationPaPossible === true) : ?>
	 Vous avez actuellement <?php echo $this->user->castars_braldun?> castar<?php if ($this->user->castars_braldun > 1): echo "s"; endif;?>.<br /><br />
	 
		<?php if (count($this->labanRunes) > 0 && $this->tabAAfficher === true) : ?>
			<table>
			 <?php foreach ($this->labanRunes as $r): ?>
			 	<?php if ($r["a_afficher"] == true): ?>
				   <tr>
				     <td valign="top">
				     <img class="rune" src="<?php echo $this->config->url->static?>/images/runes/<?php echo $r["image_type_rune"]?>" title="<?php echo $r["nom_type_rune"]?>" alt="<?php echo $r["nom_type_rune"] ?>"/>
				     <br />
				     3 runes <?php echo $r["nom_type_rune"]?>
				     <br />
				     co&ucirc;t : <?php echo $r["cout_castars"]?> castars.
				     <?php if ($r["achat_possible"] !== true): ?>
				     	(trop cher)
				     <?php endif;?>
				     </td>
				     <td align='left' valign="top">
				     <?php if ($this->utilisationPaPossible === true && $r["achat_possible"] === true && $this->achatPossibleCastars === true): ?>
				       		<input type="radio" name="valeur_1" id="valeur_1" value="<?php echo $r["id_type_rune"]?>" onchange="$('#bouton_echangeurrune').attr('disabled',false);">
				     <?php endif;?>
				     </td>
				   </tr>
				  <?php endif;?>
				<?php endforeach; ?>
			 </table>
		<?php else: ?>
			Vous n'avez de runes &eacute;changeables dans votre laban.
		<?php endif; ?>
	 </div> 
	</form>

<?php else :?>
Vous n'avez pas assez de PA.<br />
<?php endif; ?>


<?php if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true && $this->tabAAfficher === true): ?>
<input type='button' class='button' id="bouton_echangeurrune" value='&Eacute;changer !' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_echangeurrune');"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>