<div class='comp_titre'>Escaliers</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?php echo $this->paUtilisationLieu ?> PA, 
 	vous pouvez prendre les escaliers et monter d'un étage.<br />
   	
   	<?php if ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPaPossible === true): ?>
<input type='button' class='button' id="bouton_hopital" value='Prendre les escaliers' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_escaliers');">
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>