<div class='comp_titre'>Escaliers</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?=$this->paUtilisationLieu ?> PA, 
 	vous pouvez prendre les escaliers et monter d'un étage.<br />
   	
   	<? if ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<? endif; ?>
 </div> 
</form>
<br /> 

<? if ($this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_hopital" value='Prendre les escaliers' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_escaliers');">
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>