<div class='comp_titre'>Essene Cehef</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<br>
 	Pour utiliser la charette, il faut <?=$this->coutCastars?> castars<br><br>
   	<? if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars <br>
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<? else : ?>
   	   Choisir une destination : <br>
   	   <select id='valeur_1' name='valeur_1' onChange="javascript:if($('valeur_1').value==-1){$('bouton_essenecehef').disabled=true} else {$('bouton_essenecehef').disabled=false}">
   	     <option value='-1'>(Choisis une destination)</option>
   	     <? foreach($this->tabDestinations as $d) :?>
   	     <option value='<?=$d["id_lieu"]?>'><?=htmlentities($d["nom"])?> (<?=$d["x"]?>,<?=$d["y"]?>) 
   	     <? if ($d["est_capitale"]): ?>
   	     - Capitale
   	     <? else: ?>
   	     - Ville
   	     <? endif; ?>
   	     </option>
   	     <? endforeach; ?>
   	   </select>
   	<? endif; ?>
 </div> 
</form>
<br> 

<? if ($this->utilisationPossible === true): ?>
<input type='button' class='button1' id="bouton_essenecehef" value='Utiliser la charrette !' onClick="_get_('/lieux/DoAction?caction=do_lieu_essenecehef');"  disabled>
<? endif; ?>
<? include("commun_fermer.phtml") ?>