<div class='comp_titre'>Eujime Nasiumme</div>
 <form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
  Pour <?=$this->paUtilisationLieu ?> PA et <?=$this->coutCastars?> castars, l'entra&icirc;neur <br>
  vous propose d'am&eacute;liorer une caract&eacute;ristique<br><br>
 
 <? if ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PA<br><br>
 <? elseif ($this->achatPiPossible == false): ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de PI<br><br>
 <? elseif ($this->achatPossibleCastars == false): ?>
 	Vous ne pouvez rien am&eacute;liorer, vous n'avez pas assez de Castars<br><br>
 <? endif; ?>
 
  <? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true): ?>
  Choisissez une caract&eacute;ristique ci-dessous <input type='radio' name='valeur_1' id='valeur_1' value='-1' onChange="$('bouton_eujimenasiumme').disabled=true;" checked>
  <? endif ?>
  
   <ul class="ligne_espace">
   Agilit&eacute; (AGI): <?=$this->coutAgilite?> PI
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
     <? if ($this->coutAgilite <= $this->user->pi_hobbit): ?>
      <input type="radio" name="valeur_1" id="valeur_1" value="AGI" onChange="$('bouton_eujimenasiumme').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif; ?>
    </ul>
    <ul class="ligne_espace">
    Force (FOR) : <?=$this->coutForce?> PI
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
     <? if ($this->coutForce <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="FOR" onChange="$('bouton_eujimenasiumme').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
    </ul>
    <ul class="ligne_espace">
	Vigueur (VIG) : <?=$this->coutVigueur?> PI
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
     <? if ($this->coutVigueur <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="VIG" onChange="$('bouton_eujimenasiumme').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
       </ul>
    <ul class="ligne_espace">
    Sagesse (SAG) :  <?=$this->coutSagesse?> PI
   <? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
     <? if ($this->coutSagesse <= $this->user->pi_hobbit): ?>
     <input type="radio" name="valeur_1" id="valeur_1" value="SAG" onChange="$('bouton_eujimenasiumme').disabled=false;">
     <? else :?>
       Trop cher !
     <? endif;?>
   <? endif;?>
 </div> 
</form>

<? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true): ?>
<input type='button' class='button1' id="bouton_eujimenasiumme" value="S'am&eacute;liorer !" onClick="_get_('/lieux/DoAction?caction=do_lieu_eujimenasiumme');"  disabled>
<? endif; ?>
<input type='button' class='button1' value='Annuler' onClick='javascript:_get_("/interface/clear");'>