<div class='comp_titre'>Gare</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<br />
 	Pour utiliser la diligence, il faut <?php echo $this->coutCastars?> castars et <?php echo $this->paUtilisationLieu?> PA.<br /><br />
   	<?php if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars <br />
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<?php elseif ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA <br />
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<?php else : ?>
   	   Choisir une destination : <br />
   	   <select id='valeur_1' name='valeur_1' onchange="javascript:if($('#valeur_1').val() ==-1){$('#bouton_gare').attr('disabled', true)} else {$('#bouton_gare').attr('disabled',false)}">
   	     <option value='-1'>(Choisissez une destination)</option>
   	     <?php foreach($this->tabDestinations as $d) :?>
   	     <option value='<?php echo $d["id_lieu"]?>'><?php echo $d["nom"]?> (<?php echo $d["x"]?>,<?php echo $d["y"]?>) 
   	     <?php if ($d["est_capitale"]): ?>
   	     - Capitale
   	     <?php else: ?>
   	     - Ville
   	     <?php endif; ?>
   	     </option>
   	     <?php endforeach; ?>
   	   </select>
   	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_gare" value='Utiliser la diligence !' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_gare');"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>