<div class='comp_titre'>Gare</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<br />
 	Pour utiliser la diligence, il faut <?=$this->coutCastars?> castars et <?=$this->paUtilisationLieu?> PA.<br /><br />
   	<? if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars <br />
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<? elseif ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA <br />
   		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
   	<? else : ?>
   	   Choisir une destination : <br />
   	   <select id='valeur_1' name='valeur_1' onChange="javascript:if($('valeur_1').value==-1){$('bouton_gare').disabled=true} else {$('bouton_gare').disabled=false}">
   	     <option value='-1'>(Choisis une destination)</option>
   	     <? foreach($this->tabDestinations as $d) :?>
   	     <option value='<?=$d["id_lieu"]?>'><?=$d["nom"]?> (<?=$d["x"]?>,<?=$d["y"]?>) 
   	     <? if ($d["est_capitale"]): ?>
   	     - Capitale
   	     <? else: ?>
   	     - Ville
   	     <? endif; ?>
   	     </option>
   	     <? endforeach; ?>
   	   </select>
   	<? endif; ?>
 </div> 
</form>
<br /> 

<? if ($this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_gare" value='Utiliser la diligence !' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_gare');"  disabled>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>