<div class='comp_titre'><?php echo $this->nomLieu ?></div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?php echo $this->coutCastars?> castars et <?php echo $this->paUtilisationLieu ?> PA, 
 	le docteur peut vous activer votre reg&eacute;n&eacute;ration.<br />
   	
   	Vous avez <?php echo $this->user->castars_braldun ?> castar<?php if ($this->user->castars_braldun > 1): echo "s"; endif; ?>.<br />
   		
	<?php if ($this->utilisationPossible === false): ?>
   		Vous n'avez pas assez de castars !<br />
   	<?php elseif ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<?php elseif ($this->recupPossible) :?>
   		<br /><br />
    <?php else: ?>
    	Vous &ecirc;tes d&eacute;j&agrave; en pleine forme !<br />
   	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPossible === true && $this->utilisationPaPossible === true && $this->recupPossible): ?>
<input type='button' class='button' id="bouton_hopital" value='Se faire soigner !' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_<?php echo $this->nomSystemeLieu?>');">
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>