<div class='comp_titre'>Joaillier</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
 Pour <?=$this->paUtilisationLieu ?> PA et <?=$this->coutCastars?> castars, le joaillier <br />
  vous propose de sertir une pi&egrave;ce d'&eacute;quipement, pr&eacute;sente dans votre laban.<br /><br />
 
 	<? if ($this->nbEquipementsLaban > 0): ?>
 		&Eacute;quipement:<br />
		<select name="valeur_1" id="valeur_1" onChange="_get_('/lieux/doaction?caction=ask_lieu_joaillier&id_equipement='+this.value);">
	 		<option value="-1">(Choisis un &eacute;quipement)</option>
			<? foreach($this->equipementsLaban as $e) :?>
				<option value="<?=$e["id_laban_equipement"] ?>" <?=$e["selected"]?>><?=$e["nom"] ?> : n&deg;<?=$e["id_laban_equipement"] ?>, qualit&eacute; <?=$e["qualite"] ?>,
				 niveau: <?=$e["niveau"] ?>, nb. emplacements: <?=$e["nb_runes"] ?></option>
			<? endforeach; ?>
		</select>
		<br /><br />
	<? endif; ?>
	
	<? if (isset($this->equipementCourant) ) : ?>
		<? if ($this->equipementCourant["nb_runes"] < 1) : ?>
			Cet &eacute;quipement ne peut pas &ecirc;tre serti de rune.
		<? else : ?>
			<? if ($this->nbEquipementRune > 0) :
			
				if ($this->nbEquipementRune > 1) $s="s"; else $s=""; ?>
			Il y a d&eacute;j&agrave; <?=$this->nbEquipementRune ?> rune<?=$s ?> de sertie<?=$s ?> sur cet &eacute;quipement. <br />
			
			Vous ne pouvez pas sertir de rune sur un &eacute;quipement d&eacute;j&agrave; serti.
			
			<? else : ?>
			
				Glissez une rune sur l'&eacute;quipement ci-dessous. L'ordre des runes ayant une importance,
				vous pouvez les r&eacute;organiser avant que le joaillier les sertisse.<br /><br />
				Tous les emplacements runiques doivent &ecirc;tre utilis&eacute;s.<br />
				Tout objet serti, ne pourra pas faire l'objet d'un nouveau sertissage dans le futur.<br />
				<br />
				<? $js="sections = ['group1','group2'];
					function calculNbRune(total){ 
						liste=Sortable.serialize('group2'); 
						if (liste.length > 0) {
							tliste=liste.split('&'); 
							nbPlacees=tliste.length;
						} else { 
							nbPlacees=0; 
						} 
						$('valeur_2').value=nbPlacees; 
						nb = total - nbPlacees;
						$('valeur_3').value=Sortable.sequence($('group2')); 
						if (nb != 0) { 
							$('bouton_joaillier').disabled=true; 
						} else { 
							$('bouton_joaillier').disabled=false; 
						}
						text = '';
						s = '';
						for (i=0; i<nbPlacees; i++) {
							text = text + ' ' + $('item_'+tliste[i].substr(9,tliste[i].length-8)).alt;
							if (i > 0) {
								s = 's';
							}
						}
						text = 'Rune' + s + ' : ' + text;
						$('rune_text').innerHTML = text;
						return nb;
					};
					function upd() {
						$('dispo').innerHTML=calculNbRune(".$this->equipementCourant["nb_runes"].");
						
					}
					Sortable.create('group1',{tag:'img',dropOnEmpty: true, overlap:'horizontal', containment: sections, only:'rune'});
					Sortable.create('group2',{tag:'img',dropOnEmpty: true, overlap:'horizontal', containment: sections, only:'rune', onUpdate:upd});" ?>
				
				<? if (count($this->labanRunes) > 0) : ?>
					<input type="button" class='button1' value="Choisir les runes" onClick="<?=$js ?>; $('choix_runes').style.display='block';this.style.display='none';">
				
					<div id="choix_runes" style="display:none">
						<h3 class="handle">Vos runes disponibles</h3>
						
						<div id="group1" class="joaillier_runes" style="height:130px ;overflow:auto">
							<? 
							$i = 0;
								foreach($this->labanRunes as $k => $v) : ?>
									<img id="item_<?=$k ?>" class="rune" src="/public/images/runes/<?=$v["image_type_rune"]?>" title="<?=$v["nom_type_rune"]?> : <?=$v["effet_type_rune"]?>" alt="<?=$v["nom_type_rune"] ?>" style="cursor:pointer;"/>
								<? endforeach; ?>
						</div>
							
						<br />
						<input type="hidden" id="valeur_2" name="valeur_2">
						<input type="hidden" id="valeur_3" name="valeur_3">
						<br />
						<? if ($this->equipementCourant["nb_runes"] > 1): $s="s"; else:$s=""; endif; ?>Sur <?=$this->equipementCourant["nb_runes"]?> emplacement<?=$s?> au total, il en reste <label id="dispo"><?=$this->equipementCourant["nb_runes"]?></label>.
						<br />
						<label id='rune_text'></label>
						<div id="group2" class="joaillier_runes" style="height:40px">
						</div>
					</div>
				<? else: ?>
					Vous n'avez aucun rune dans votre laban
				<? endif; ?>
			<? endif; ?>
		<? endif; ?>
	<? endif; ?>
	
 </div> 
</form>
<br />

<? if ($this->achatPossibleCastars !== true) :?>
Vous n'avez pas assez de castars.<br>
<? endif; ?>

<? if ($this->utilisationPaPossible !== true) :?>
Vous n'avez pas assez de PA.<br>
<? endif; ?>


<? if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
<input type='button' class='button1' id="bouton_joaillier" value='Sertir !' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_joaillier&id_equipement='+$('valeur_1').value);"  disabled>
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>