<div class='comp_titre'>Joaillier</div>
 <form name='myForm'  id='myForm'>
 <input type='hidden' id='nb_valeurs-joaillier' name='nb_valeurs-joaillier' value='3'>
 <div class='comp_contenu'>
 Pour <?php echo $this->paUtilisationLieu ?> PA et <?php echo $this->coutCastars?> castars, le joaillier <br />
  vous propose de sertir une pi&egrave;ce d'&eacute;quipement, pr&eacute;sente dans votre laban.<br /><br />
 
 <?php if ($this->achatPossibleCastars == true) :?>
 	<?php if ($this->nbEquipementsLaban > 0): ?>
 		&Eacute;quipement:<br />
		<select name="valeur_1-joaillier" id="valeur_1-joaillier" onchange="_get_('/lieux/doaction?caction=ask_lieu_joaillier&id_equipement='+this.value);">
	 		<option value="-1">(Choisissez un &eacute;quipement)</option>
			<?php foreach($this->equipementsLaban as $e) :?>
				<option value="<?php echo $e["id_laban_equipement"] ?>" <?php echo $e["selected"]?>><?php echo $e["nom"] ?> : n&deg;<?php echo $e["id_laban_equipement"] ?>,
				 nb. emplacements: <?php echo $e["nb_runes"] ?></option>
			<?php endforeach; ?>
		</select>
		<br /><br />
	<?php else: ?>
	Vous n'avez aucun équipement à sertir.
	<?php endif; ?>
	
	<?php if (isset($this->equipementCourant) ) : ?>
		<?php if ($this->equipementCourant["nb_runes"] < 1) : ?>
			Cet &eacute;quipement ne peut pas &ecirc;tre serti de rune.
		<?php else : ?>
			<?php if ($this->nbEquipementRune > 0) :
			
				if ($this->nbEquipementRune > 1) $s="s"; else $s=""; ?>
			Il y a d&eacute;j&agrave; <?php echo $this->nbEquipementRune ?> rune<?php echo $s ?> de sertie<?php echo $s ?> sur cet &eacute;quipement. <br />
			
			Vous ne pouvez pas sertir de rune sur un &eacute;quipement d&eacute;j&agrave; serti.
			
			<?php else : ?>
			
				Glissez une rune sur l'&eacute;quipement ci-dessous. L'ordre des runes ayant une importance,
				vous pouvez les r&eacute;organiser avant que le joaillier les sertisse.<br /><br />
				Tous les emplacements runiques doivent &ecirc;tre utilis&eacute;s.<br />
				Tout objet serti, ne pourra pas faire l'objet d'un nouveau sertissage dans le futur.<br />
			<br />
			<?php $js="
				function calculNbRuneRecherche(total) { 
					$( '#group1, #group2' ).sortable({
							connectWith: '.liste_runes',
							placeholder: 'ui-state-highlight-bral',
							update: function(event, ui) { 
							
								liste = $('#group2').sortable('serialize');  
								if (liste.length > 0) {
									tliste = liste.split('&'); 
									nbPlacees = tliste.length;
								} else { 
									nbPlacees = 0; 
								}
								$('#valeur_2-joaillier').val(nbPlacees); 
								nb = total - nbPlacees;
								$('#dispo').html(nb);
								
								if (nb != 0) { 
									$('#bouton_joaillier').attr('disabled', true); 
								} else { 
									$('#bouton_joaillier').attr('disabled', false); 
								}
								text = '';
								val3 = '';
								s = '';
								for (i = 0; i < nbPlacees; i++) {
									text = text + ' ' + $('#item_'+tliste[i].substr(7, tliste[i].length-7))[0].alt;
									if (i > 0) {
										s = 's';
									}
									val3 = val3 + tliste[i].substr(7, tliste[i].length-7) + ',';
								}
								
								$('#valeur_3-joaillier').val(val3);
								text = 'Rune' + s + ' : ' + text;
								$('#rune_text').html(text);
							}
						}).disableSelection();
					}
					calculNbRuneRecherche(".$this->equipementCourant["nb_runes"].");
				" ?>
			
			<?php if (count($this->labanRunes) > 0) : ?>
				<input type="button" class='button' value="Choisir les runes" onclick="<?php echo $js ?>; $('#choix_runes_joaillier').show();this.style.display='none';">
			
				<div id="choix_runes_joaillier" style="display:none">
					
					<br />
						<?php if ($this->equipementCourant["nb_runes"] > 1): $s="s"; else:$s=""; endif; ?>Sur <?php echo $this->equipementCourant["nb_runes"]?> emplacement<?php echo $s?> au total, il en reste <label id="dispo"><?php echo $this->equipementCourant["nb_runes"]?></label>.
						<br />
						<label id='rune_text'></label>
						<div id="group2" class="liste_runes" style="height:40px">
						</div>
						
						
						<h3 class="handle">Vos runes disponibles</h3>
						
						<div id="group1" class="liste_runes" style="height:130px ;overflow:auto">
							<?php 
							$i = 0;
								foreach($this->labanRunes as $k => $v) : ?>
									<img id="item_<?php echo $k ?>" class="rune" src="<?php echo $this->config->url->static?>/images/runes/<?php echo $v["image_type_rune"]?>" title="<?php echo $v["nom_type_rune"]?> : <?php echo $v["effet_type_rune"]?>" alt="<?php echo $v["nom_type_rune"] ?>" style="cursor:pointer;"/>
								<?php endforeach; ?>
						</div>
							
						<br />
						<input type="hidden" id="valeur_2-joaillier" name="valeur_2-joaillier">
						<input type="hidden" id="valeur_3-joaillier" name="valeur_3-joaillier">
						
					</div>
				<?php else: ?>
					Vous n'avez aucune rune dans votre laban
				<?php endif; ?>
			<?php endif; ?>
		<?php endif; ?>
	<?php endif; ?>
	
 </div> 
</form>
<?php endif;?>
<br />

<?php if ($this->achatPossibleCastars !== true) :?>
Vous n'avez pas assez de castars.<br /><br />
<?php endif; ?>

<?php if ($this->utilisationPaPossible !== true) :?>
Vous n'avez pas assez de PA.<br />
<?php endif; ?>


<?php if ($this->utilisationPaPossible === true && $this->achatPossibleCastars === true): ?>
<input type='button' class='button' id="bouton_joaillier" value='Sertir !' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_joaillier&id_equipement='+$('#valeur_1-joaillier').val(), 'joaillier');"  disabled>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>