<div class='comp_titre'>Laffaque</div>
 <form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?=$this->paUtilisationLieu ?> PA et <?=$this->coutCastars?> castars, le pr&eacute;sident de Laffaque <br>
  vous propose d'apprendre une nouvelle comp&eacute;tence<br><br>
 
 <? if ($this->nCompetences == 0): ?>
	Il n'y a aucune comp&eacute;tence pour vous...
 <? elseif ($this->utilisationPaPossible == false) : ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PA<br><br>
 <? elseif ($this->achatPiPossible == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PI<br><br>
 <? elseif ($this->achatPossibleCastars == false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de Castars<br><br>
 <? endif; ?>
 
<? if ($this->nCompetences > 0): ?>
 <? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
  Choisissez une comp&eacute;tence ci-dessous <input type='radio' name='valeur_1' id='valeur_1' value='-1' onChange="$('bouton_laffaque').disabled=true;" checked>
 <? endif; ?>
 <table>
 <? foreach ($this->tabCompetences as $c):?>
   <tr>
     <td><?=$c["nom"]?></td>
     <td> co&ucirc;t : <?=$c["pi_cout"]?> PI </td>
     <td>
     <? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $c["trop_cher"] === false): ?>
       <input type="radio" name="valeur_1" id="valeur_1" value="<?=$c["id_competence"]?>" onChange="$('bouton_laffaque').disabled=false;">
     <? endif;?>
     </td>
   </tr>
 <? endforeach; ?>
 </table>
 <? endif; ?>
 
 </div> 
</form>
<br>

<? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->achatPossibleCastars === true && $this->nCompetences > 0): ?>
<input type='button' class='button1' id="bouton_laffaque" value='Apprendre cette comp&eacute;tence !' onClick="_get_('/lieux/DoAction?caction=do_lieu_laffaque');"  disabled>
<? endif; ?>
<? include("commun_fermer.phtml") ?>