<div class='comp_titre'>Laffaque</div>

 <div class='comp_contenu'>
	 <div id='lieu_text' style="display:block"  onClick="javascript:switch2div('lieu_text','lieu_copie');">
	 Pour <?=$this->coutCastars?> castars et <?=$this->coutPi?> PI, vous avez appris <br />
	 la comp&eacute;tence : <?=htmlentities($this->nomCompetence) ?> <br /><br />
	 
	 Faites-en bon usage...<br /><br />
	 </div>
	 <div id='lieu_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><? 
		echo "Pour ".$this->coutCastars." castars et ".$this->coutPi." PI, vous avez appris";
	 	echo " la comp&eacute;tence : ".htmlentities($this->nomCompetence);
	 	echo "
";
	 	echo "Faites-en bon usage...";
		?></textarea>
	</div>
 </div>

<input type='button' value='Copier' class='button1' onClick="javascript:switch2div('lieu_text','lieu_copie');">
<? include("commun_fermer.phtml") ?>