<div class='comp_titre'>Laffaque</div>
 <form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 Pour <?=$this->paUtilisationLieu ?> PA, le pr&eacute;sident de Laffaque <br>
  vous propose d'apprendre une nouvelle comp&eacute;tence<br><br>
 
 <? if ($this->nCompetences == 0): ?>
	Il n'y a aucune comp&eacute;tence pour vous...
 <? elseif ($this->utilisationPaPossible === false) : ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PA<br><br>
 <? elseif ($this->achatPossiblePi === false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PI<br><br>
 <? elseif ($this->achatPossibleCastars === false): ?>
 	Vous ne pouvez rien apprendre, vous n'avez pas assez de PI<br><br>
 <? else: ?>
  Choisissez une comp&eacute;tence : <br>
 <? endif; ?>
 
 <? if ($this->nCompetences > 0): ?>
 <table>
 <? foreach ($this->tabCompetences as $c):?>
   <tr>
     <td><?=$c["nom"]?></td>
     <td> co&ucirc;t : <?=$c["pi_cout"]?> PI </td>
     <td>
     <? if ($this->utilisationPaPossible === true && $this->achatPossiblePi === true && $c["trop_cher"] === false): ?>
       <input type="radio" name="valeur_1" id="valeur_1" value="<?=$c["id_competence"]?>" onChange="$('bouton_essenecehef').disabled=false;">
     <? endif;?>
     </td>
   </tr>
 <? endforeach; ?>
 </table>
 <? endif; ?>
 
 </div> 
</form>
<br> 

<? if ($this->utilisationPaPossible === true && $this->achatPiPossible === true && $this->nCompetences > 0): ?>
<input type='button' id="bouton_laffaque" value='Apprendre cette comp&eacute;tence !' onClick="_get_('/lieux/DoAction?caction=do_lieu_laffaque');"  disabled>
<? endif; ?>
<input type='button' value='Annuler' onClick='javascript:_get_("/interface/clear");'>