<div class='comp_titre'>Lieu Mythique</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 
 <? if ($this->utilisationPossible === true) : ?>
 	C'est la première fois que vous passez ici... <br />
 	Vous pouvez obtenir la  distinction suivante :
 	<br /><br />
 	<i><?=$this->nom_distinction?></i>
 <? else: ?>
 	Vous êtes déjà passé par ici, vous ne pouvez avoir une nouvelle fois cette distinction.
 <? endif;?>
 </div> 
</form>
<br /> 
<br />
<? if ($this->utilisationPaPossible === true && $this->utilisationPossible === true) : ?>
	<input type='button' class='button1' id="bouton_obtenir" value='Obtenir la distinction' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_lieumythique');" >
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>