<div class='comp_titre'>Lieu Mythique</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 
 <?php if ($this->utilisationPossible === true) : ?>
 	C'est la première fois que vous passez ici... <br />
 	Vous pouvez obtenir la  distinction suivante :
 	<br /><br />
 	<i><?php echo $this->nom_distinction?></i>
 <?php else: ?>
 	Vous êtes déjà passé par ici, vous ne pouvez avoir une nouvelle fois cette distinction.
 <?php endif;?>
 </div> 
</form>
<br /> 
<br />
<?php if ($this->utilisationPaPossible === true && $this->utilisationPossible === true) : ?>
	<input type='button' class='button' id="bouton_obtenir" value='Obtenir la distinction' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_lieumythique');" >
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>