<div class='comp_titre'>Mairie</div>
 <div class='comp_contenu'>
	 <div id='lieu_text' style="display:block"  onClick="javascript:switch2div('lieu_text','lieu_copie');">
	 </div>
	 <? if ($this->creerCommunaute === true) : ?>
	 	F&eacute;licitations ! Vous avez cr&eacute;&eacute; la communaut&eacute; <?=htmlentities($this->communaute["nom_communaute"]) ?>, n&deg; <?=$this->communaute["id_communaute"] ?>.
	 <? elseif ($this->entrerCommunaute === true) : ?>
	 	F&eacute;licitations ! Vous &ecirc;tes entr&eacute; dans la communaut&eacute; <?=htmlentities($this->communaute["nom_communaute"]) ?>, n&deg; <?=$this->communaute["id_communaute"] ?>.
	 <? else : // sortie, suppression ?>
	 	Vous est sorti de la communaut&eacute; <?=htmlentities($this->communaute["nom_communaute"]) ?>, n&deg; <?=$this->communaute["id_communaute"] ?>.
	 	<br>
	 	<? if ($this->supprimerCommunaute === true) : ?>
	 		Vous avez supprim&eacute; cette communaut&eacute;.
	 	<? endif; ?>
	 	
	 <? endif; ?>
	 <div id='lieu_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><? 
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('lieu_text','lieu_copie');">
<? include("commun_fermer.phtml") ?>