<div class='comp_titre'>Entrée de Mine</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?php echo $this->paUtilisationLieu ?> PA, 
 	vous pouvez descendre dans la mine.<br />
   	
   	<?php if ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_mine" value='Descendre dans la mine' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_mine');">
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>