<?php if ($this->idTypeCourant == "acheterchamp") : ?>
 	
	<?php if ($this->constructionChampOk === true): ?>
		Vous avez acheté un champ avec succ&egrave;s ! <br /><br />
		
		Il se trouve en x:<?php echo $this->x_construction ?> y:<?php echo $this->y_construction ?> 
		dans la <?php echo $this->tabRegionCourante["nom_region"] ?>.<br /><br />
		
	<?php elseif ($this->construireLieuOk == false) : ?>
		Un lieu particulier existe en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter de champ
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuEchoppeOk == false) : ?>
		Une échoppe existe en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter de champ
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuPalissadeOk == false) : ?>
		Une palissade existe d&eacute;j&agrave; en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter de champ
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuChampOk == false) : ?>
		Un champ existe d&eacute;j&agrave; en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter de champ
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuRouteOk == false) : ?>
		Vous ne pouvez pas acheter de champ &agrave; cet endroit.
		
	<?php elseif ($this->construireLieuEauOk == false) : ?>
		De l'eau est présente en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter de champ
		&agrave; cet endroit.
		
	<?php elseif ($this->construireRegionOk == false) : ?>
		&Eacute;tant dans la <?php echo $this->regionCourante["nom_region"] ?>, vous ne pouvez pas 
		acheter de champ dans une autre Comt&eacute;.
	<?php endif; ?>
<?php elseif ($this->idTypeCourant == "acheterechoppe" || $this->idTypeCourant == "deplacerechoppe") : ?>

	<?php if ($this->constructionEchoppeOk === true): ?>
		Vous avez construit une &eacute;choppe avec succ&egrave;s ! <br /><br />
		
		Elle se trouve en x:<?php echo $this->x_construction ?> y:<?php echo $this->y_construction ?> 
		dans la <?php echo $this->tabRegionCourante["nom_region"] ?>.<br /><br />
		
		C'est une &eacute;choppe <?php if ($this->nom_metier_courant{0} == 'A') : echo 'd\''; else: echo "de "; endif; ?><?php echo $this->nom_metier_courant ?>.
	
	<?php elseif ($this->deplacerEchoppeOk === true): ?>
		Vous avez déplacé une &eacute;choppe avec succ&egrave;s ! <br /><br />
		
		Elle se trouve en x:<?php echo $this->x_construction ?> y:<?php echo $this->y_construction ?> 
		dans la <?php echo $this->tabRegionCourante["nom_region"] ?>.<br /><br />
	<?php elseif ($this->construireLieuOk == false) : ?>
		Un lieu particulier existe en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas construire ou déplacer une &eacute;choppe 
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuEchoppeOk == false) : ?>
		Une &eacute;choppe existe d&eacute;j&agrave; en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas construire ou déplacer une &eacute;choppe 
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuPalissadeOk == false) : ?>
		Une palissade existe d&eacute;j&agrave; en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas construire ou déplacer une &eacute;choppe 
		&agrave; cet endroit.
		
	<?php elseif ($this->construireLieuChampOk == false) : ?>
		Un champ existe d&eacute;j&agrave; en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas construire ou déplacer une &eacute;choppe 
		&agrave; cet endroit.
	
	<?php elseif ($this->construireLieuRouteOk == false) : ?>
		Vous ne pouvez pas acheter ou déplacer une échoppe &agrave; cet endroit.
	
	<?php elseif ($this->construireLieuEauOk == false) : ?>
		De l'eau est présente en x:<?php echo $this->x_construction ?>, y:<?php echo $this->y_construction ?>, vous ne pouvez pas acheter d'échoppe
		&agrave; cet endroit.
	
	<?php elseif ($this->construireRegionOk == false) : ?>
		&Eacute;tant dans la <?php echo $this->regionCourante["nom_region"] ?>, vous ne pouvez pas 
		construire d'&eacute;choppe dans une autre Comt&eacute;.
	<?php endif; ?>
<?php elseif ($this->idTypeCourant == "supprimerechoppe") : ?>
	Vous avez supprimé une &eacute;choppe avec succ&egrave;s ! <br /><br />
<?php endif; ?>