<div class='comp_titre'>Office Notarial</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
	
	Nombre de PA : <?php echo $this->paUtilisationLieu?>.<br /><br />	
	
	Que voulez-vous faire ?
	<br /> (les champs sont disponibles à partir du niveau 5) : 
	<br />
	<select name="valeur_1" id="valeur_1" onchange="_get_('/lieux/doaction?caction=ask_lieu_notaire&valeur_1='+this.value);">
 		<option value="-1">(Choisissez une action)</option>
		<?php foreach($this->typeAction as $t) :?>
			<option value="<?php echo $t["id_type_action"] ?>" <?php echo $t["selected"]?>><?php echo $t["texte"] ?></option>
		<?php endforeach; ?>
	</select>
	
	<br /><br />
	<?php if ($this->coutCastars != null) : ?>
		Coût en castars : <?php echo $this->coutCastars?>.<br /><br />
	<?php endif;?>
 	
 	<?php if ($this->idTypeCourant == "acheterchamp") : ?>
 	
 		<div class="titre textalic textsizec">Construction de champs</div>
 		<br />
 		
 		Vous possédez actuellement <?php echo $this->nChamps?> champ<?php if ($this->nChamps > 1): echo "s"; endif;?> 
 		et vous pouvez en avoir au maximum <?php echo $this->nChampsPossibleMax?>.<br />
	 	Pour <?php echo $this->paUtilisationLieu?> PA et <?php echo $this->coutCastars?> castars, vous pouvez acheter un champ.<br /><br />
 	
 		<?php if ($this->nChampsPossible < 1) : ?>
 			Vous ne pouvez pas avoir de champ supplémentaire.
 		<?php elseif ($this->achatPossible === false || $this->utilisationPaPossible === false): ?>
	   		<?php if ($this->achatPossible === false) : ?>
	   		Vous n'avez pas assez de castars. <br />
	   		<?php endif;?>
	   		<?php if ($this->utilisationPaPossible === false) : ?>
	   		Vous n'avez pas assez de PA. <br />
	   		<?php endif; ?>
	   	<?php else : ?>
	   		Dans cette Comt&eacute; (<?php echo $this->tabRegionCourante["nom_region"]?>),
			 vous pouvez acheter un champ.<br /><br />

			Indiquez la position du champ : <br />
			X = <input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#acheter_champ').attr('disabled', true)} else {$('#acheter_champ').attr('disabled',false)};">
			<br />
			Y = <input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#acheter_champ').attr('disabled', true)} else {$('#acheter_champ').attr('disabled',false)};">
			<br />
	   	<?php endif; ?>
	   	
 	<?php elseif ($this->idTypeCourant == "acheterechoppe") : ?>
 	
 	 	<div class="titre textalic textsizec">Construction d'&eacute;choppes</div>
 		<br />
 	
	 	<?php if ($this->construireMetierPossible !== true) :?>
			Vous ne pouvez pas construire d'&eacute;choppe avec votre m&eacute;tier courant...
	 	<?php elseif ($this->nEchoppes < 1) : ?>
	 		Vous ne poss&eacute;dez pas encore d'&eacute;choppe. La premi&egrave;re est gratuite (<?php echo $this->coutCastars?> castar, mais <?php echo $this->paUtilisationLieu?> PA tout de m&ecirc;me).<br /><br />
	 	<?php else: ?>
	 		Pour <?php echo $this->paUtilisationLieu?> PA et <?php echo $this->coutCastars?> castars, vous pouvez constuire une nouvelle &eacute;choppe.<br /><br />
	 	<?php endif; ?>
	
		<?php if ($this->construireMetierPossible !== true) :?>
			<!-- rien ici -->
	   	<?php elseif ($this->achatPossible === false || $this->utilisationPaPossible === false): ?>
	   		<?php if ($this->achatPossible === false) : ?>
	   		Vous n'avez pas assez de castars. <br />
	   		<?php endif;?>
	   		<?php if ($this->utilisationPaPossible === false) : ?>
	   		Vous n'avez pas assez de PA. <br />
	   		<?php endif; ?>
	   	<?php else : ?>
		 	<?php if ($this->construireMetierPossible === true && $this->aucuneEchoppe === true) : ?>
				 Dans cette Comt&eacute; (<?php echo $this->tabRegionCourante["nom_region"]?>),
				 vous pouvez construire une &eacute;choppe
				<?php if ($this->nom_metier_courant{0} == 'A') : echo 'd'; else: echo "de"; endif; ?>
				<?php echo $this->nom_metier_courant ?>.<br /><br />
	
				Indiquez la position de l'&eacute;choppe : <br />
				X = <input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#construire_echoppe').attr('disabled', true)} else {$('#construire_echoppe').attr('disabled',false)};">
				<br />
				Y = <input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#construire_echoppe').attr('disabled', true)} else {$('#construire_echoppe').attr('disabled',false)};">
				<br />
			<?php else: ?>
				<?php if ($this->aucuneEchoppe == false) : ?>
					Vous poss&eacute;dez d&eacute;j&agrave; une &eacute;choppe pour ce m&eacute;tier dans
					cette r&eacute;gion.
				<?php else: // doit jamais arriver, mais a cas où... ?>
					Vous ne pouvez pas construire d'&eacute;choppe avec votre m&eacute;tier courant...
				<?php endif; ?>
			<?php endif; ?>
		<?php endif; ?>
	
	<?php elseif ($this->idTypeCourant == "deplacerechoppe") : ?>
		Indiquez la nouvelle position de l'&eacute;choppe : <br />
		X = <input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#construire_echoppe').attr('disabled', true)} else {$('#construire_echoppe').attr('disabled',false)};">
		<br />
		Y = <input type='text' maxlength='4' size='4' name='valeur_3' id='valeur_3' value='' onkeyup="chiffres(event, true);if($('#valeur_2').val() =='' || $('#valeur_3').val() =='') {$('#construire_echoppe').attr('disabled', true)} else {$('#construire_echoppe').attr('disabled',false)};">
		<br />
	<?php elseif ($this->idTypeCourant == "supprimerechoppe") : ?>
		Confirmer la suppression de cette échoppe ?<br /><br />
		
		Attention, tout le contenu de l'échoppe sera définitivement détruit.<br /><br />
	<?php endif;?>
 </div>
</form>
<br />

<?php if ($this->utilisationPaPossible === true && $this->achatPossible === true) : ?>
	<?php if ($this->idTypeCourant == "acheterchamp") : ?>
		<?php if ($this->nChampsPossible > 0) : ?>
		<input type='button' class='button' id="acheter_champ" value='Acheter un champ' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_notaire');" disabled>
		<?php endif; ?>
	<?php elseif ($this->idTypeCourant == "acheterechoppe") : ?>
		<?php if ($this->construireMetierPossible === true && $this->aucuneEchoppe === true) : ?>
		<input type='button' class='button' id="construire_echoppe" value='Construire une &eacute;choppe' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_notaire');" disabled>
		<?php endif; ?>
	<?php elseif ($this->idTypeCourant == "deplacerechoppe") : ?>
		<input type='button' class='button' id="construire_echoppe" value='Déplacer une &eacute;choppe' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_notaire');" disabled>
	<?php elseif ($this->idTypeCourant == "supprimerechoppe") : ?>
		<input type='button' class='button' id="construire_echoppe" value='Supprimer une &eacute;choppe' onclick="$('#nb_valeurs').val(1);this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_notaire');">
	<?php endif;?>
<?php endif;?>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>