<div class='comp_titre'>Poste de Garde</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	
 	<br>
 	Pour utiliser les services du poste, il vous faut <?=$this->paUtilisationLieu?> PA.<br /><br />
 	
 	<? if ($this->utilisationPaPossible !== true): ?>
 		Vous n'avez pas assez de PA.
 	<? elseif ($this->soulePossible !== true): ?>
 		Vous ne pouvez pas entrer dans le Donjon en étant inscrit à un match de Soule.
 	<? elseif ($this->nouvelleEquipePossible === true) : ?>
 		
 		<? if ($this->inscriptionParHobbitNouvelleEquipePossible === true):?>
	 		Vous êtes Bourlingueur de cette Comté. Félicitations !<br>
	 		Vous pouvez inscrire une équipe pour entrer dans ce Donjon. <br><br>
	 		Vous devez choisir 8 coéquipiers, également Bourlingueurs de cette Comté.<br><br>
	 		Saisissez un prénom de hobbit ci-dessous. Attention, les hobbits qui ne sont pas 
	 		Bourlingueurs de cette Comté ne seront pas retournés par la recherche, ainsi que
	 		les hobbits inscrits à un match de soule.<br>
	 		De plus, vous êtes directement inclus dans l'équipe, ne prenez donc pas la peine
	 		de vous rechercher, vous n'apparaitrez pas dans la recherche également.<br><br>
 		<? else:?>
 			Pour rentrer dans ce Donjon, vous devez être Bourlingueur de cette Comté (avoir
 			terminé toutes les quêtes de cette Comté, consultez votre onglet Quêtes).<br>
 		<? endif;?>
 		
 	<? else : ?>
	 	<? if ($this->inscriptionDemandee === true): ?>
	 		Vous êtes demandé pour vous inscrire dans ce Donjon. Si vous n'acceptez pas, le meneur 
	 		ne pourra pas ouvrir la porte et l'inscription
	 		de toute l'équipe sera annulée le <?=$this->dateLimiteInscription?>.
	 	<? elseif ($this->inscriptionRealisee === true): ?>
	 		
	 		<? if ($this->estMeneur) : ?>
		 		<? if ($this->descentePossible) : ?>
		 			Vous êtes inscrit pour participer à ce Donjon dont vous êtes le meneur.<br>
		 			Tous vos coéquipiers ont validé leur inscription, 
			 		vous pouvez maintenant ouvrir la porte du Donjon.
			 	<? else: ?>
			 		Vous êtes déjà inscrit pour participer à ce Donjon dont vous êtes le meneur.<br>
			 		Dès que tous vos coéquipiers auront validé leur inscription, 
			 		vous pourrez revenir ici-même ouvrir la porte du Donjon et faire
			 		rentrer toute votre équipe à l'intérieur.
			 		<br><br>
		 			Toute l'équipe doit être sur le Poste de Garde pour pouvoir descendre.
			 	<? endif;?>
	 		<? else : ?>
		 		Vous êtes déjà inscrit pour participer à ce Donjon.<br>
	 		
		 		Dès lors que tous vos coéquipiers auront validé leur inscription, 
		 		le meneur pourra ouvrir la porte du Donjon et vous
		 		rentrerez automatiquement à l'intérieur.<br><br>
		 		Toute l'équipe doit être sur le Poste de Garde pour pouvoir descendre.
	 		<? endif;?>
	 		
	 	<? else: ?>
	 		Il y déjà une équipe dans ce Donjon ou en cours d'inscription, sans que vous 
	 		soyez demandé pour en faire partie. Attendez leur sortie pour inscrire une 
	 		nouvelle équipe.
	 	<? endif;?>
	 	<br><br>
	 <? endif;?>
	 
	 
	<? if ($this->utilisationPaPossible === true): ?> 
		
		<input type="hidden" name="valeur_1" id="valeur_1" value="" />
		
		<? if ($this->nouvelleEquipePossible === true && 
		   	   $this->inscriptionParHobbitNouvelleEquipePossible === true) : ?>
 		
 			<div id='aff_valeur_1_coequiper' name='aff_valeur_1_coequiper'></div>
			<input type="hidden" name="valeur_1_coequiper" id="valeur_1_coequiper" value=""/>
			<input type="hidden" name="cpt_valeur_1_coequiper" id="cpt_valeur_1_coequiper" value=""/>
			<input type="hidden" name="onChange_valeur_1_coequiper" id="onChange_valeur_1_coequiper" value="if ($('cpt_valeur_1_coequiper').value == 8) {$('bouton_poste_nouveau').disabled = false;} else {$('bouton_poste_nouveau').disabled = true;}"/>
			
			<input type="text" name="recherche_valeur_1_coequiper" size='40' id="recherche_valeur_1_coequiper" value="Entrez un nom" onFocus='this.value=""; activerRechercheBourlingueur("valeur_1_coequiper", "<?=$this->idTypeDistinctionCourante?>");' />
			<input type="hidden" name="recherche_valeur_1_coequiper_actif" id="recherche_valeur_1_coequiper_actif" value="0" />
			<div class="recherche" id="recherche_valeur_1_coequiper_update" ></div> <img src="/public/images/loupe.gif" />
		    <span id="indicateur_recherche_valeur_1_coequiper" style="display: none"><img src="/public/images/wait.gif" alt="Recherche..." /></span>
		    
		    <br><br>
		    <input type='button' class='button1' id="bouton_poste_nouveau" value="Inscrire l'équipe" onClick="this.disabled=true;$('valeur_1').value=$('valeur_1_coequiper').value;_get_('/lieux/doaction?caction=do_lieu_postedegarde');" disabled/>
	
		<? elseif ($this->inscriptionDemandee === true): ?>
			 <input type='button' class='button1' id="bouton_poste_nouveau" value="Valider l'inscription" onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_postedegarde');" />
		<? elseif ($this->estMeneur && $this->descentePossible) : ?>
		 	 <input type='button' class='button1' id="bouton_poste_nouveau" value="Ouvrir la porte du Donjon" onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_postedegarde');" />
		<? endif;?>
 	<? endif;?>
 	
 </div> 
</form>
<? echo Bral_Helper_Fermer::affiche(); ?>