<div class='comp_titre'><?=$this->nomLieu?></div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	<? if ($this->queteObtenue === false):?>
 	Vous êtes en recherche de quête à <?=$this->nomVille?> ? 
 	<br><br>
 	Bien, vous êtes au bon endroit, mais vous devez payer <?=$this->coutCastars?> castars 
 	(et <?=$this->paUtilisationLieu ?> PA) pour rencontrer la personne occupant ce lieu et
 	recevoir quelque chose de sa part...<br>
 	<? else: ?>
 	Vous êtes déjà rentré dans ce lieu, vous n'avez plus rien à faire ici...
 	<? endif;?>
 </div> 
</form>
<br /> 

<? if ($this->queteObtenue === false && $this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_quete" value='Payer et Rentrer' onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_quete');">
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>