<div class='comp_titre'><?=$this->nomLieu?></div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	
 	Bonjour à toi <?=$this->user->prenom_hobbit ?> <?=$this->user->nom_hobbit ?>.<br>
 	<br>
 	<? if ($this->queteEnCours === true):?>
 	Tu as d&eacute;j&agrave; une quête en cours... Termine-là et viens me revoir ensuite.
 	<? elseif ($this->queteObtenue === false):?>
 	
 	Tu es en recherche de quête à <?=$this->nomVille?> ? 
 	<br><br>
 	Bien, j'ai une mission pour toi qui me semble adapter.<br> Tu dois payer <?=$this->coutCastars?> castars 
 	(et <?=$this->paUtilisationLieu ?> PA).<br><br>
 	Es-tu prêt &agrave; accepter ?
 	<? else: ?>
 	Vous êtes déjà rentré dans ce lieu, vous n'avez plus rien à faire ici...
 	<? endif;?>
 </div> 
</form>
<br /> 

<? if ($this->queteEnCours === false && $this->queteObtenue === false && $this->utilisationPossible === true && $this->utilisationPaPossible === true): ?>
<input type='button' class='button1' id="bouton_quete" value="Oui, J'accepte !" onClick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_quete');">
<? endif; ?>
<? echo Bral_Helper_Fermer::affiche(); ?>