<div class='comp_titre'>Ruine</div>
 <form name='myForm' id='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	<br />
 	Pour <?php echo $this->paUtilisationLieu ?> PA, 
 	vous pouvez transformer cette ruine en hall de Communauté.<br />
   	
   	<?php if ($this->utilisationPaPossible === false) :?>
   		Vous n'avez pas assez de PA !<br />
   	<?php elseif ($this->transformerOk == false): ?>
   	<br />
   		Il faut être Gestionnaire de communauté pour transformer ce lieu en Hall de Communauté
   	<?php endif; ?>
 </div> 
</form>
<br /> 

<?php if ($this->utilisationPaPossible === true && $this->transformerOk === true): ?>
<input type='button' class='button1' id="bouton_hopital" value='Prendre les escaliers' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_escaliers');">
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>