<div class='comp_titre'>Tribunal</div>

<?php if ($this->type == "gredin"): ?>
	<?php if ($this->choix == 1) : ?>
		Vous avez réalisé avec succès les travaux d'intérêts généraux. 
	<?php else : ?>
		Vous avez payé avec succès votre caution.
	<?php endif;?>
	<br /><br />
	Vous avez 1 point de gredin en moins.<br />
	Vous avez maintenant <?php echo $this->user->points_gredin_braldun;?>
	 point<?php if ($this->user->points_gredin_braldun > 1) : echo "s"; endif;?> de gredin.

<?php else: ?>
	Vous avez maintenant <?php echo $this->user->points_redresseur_braldun;?> point de Redresseur de Torts.
<?php endif;?>
<br />
