<div class='comp_titre'>Tribunal</div>
 <form name='myForm' id='myForm'>
 <?php if ($this->type == "gredin"): ?>
 	<input type='hidden' id='nb_valeurs-lieu_tribunal' name='nb_valeurs-lieu_tribunal' value='1'>
 <?php else: ?>
 	<input type='hidden' id='nb_valeurs-lieu_tribunal' name='nb_valeurs-lieu_tribunal' value='0'>
 <?php endif;?>
 <div class='comp_contenu'>
 
 <br />
   	
  <?php if ($this->type == "gredin"): ?>
  Vous avez actuellement <?php echo $this->user->points_gredin_braldun;?>
 point<?php if ($this->user->points_gredin_braldun > 1) : echo "s"; endif;?> de Gredin.<br /><br />
 
	  <?php if ($this->contratEnCours == true) : ?>
	 	Vous ne pouvez pas vous racheter, il y a actuellement un contrat en cours sur votre tête...
	 <?php elseif ($this->user->pa_braldun <1) : ?>
	 	Vous n'avez pas assez de PA (1 minimum).
	  <?php elseif ($this->utilisationPointPossible === true) : ?>
	  
	  	<?php if ($this->travauxOk != true && $this->cautionOk !== true) : ?>
		  	Vous n'avez pas assez de PA (4 minimum) ou de castars (100 minimum).
		  <?php else: ?>
		  
	 	  Vous pouvez vous racheter et perdre un point de gredin en effectuant une action ci-dessous :<br /> 
	 	
		  <?php if ($this->travauxOk === true) : ?>
		  Réalisation de travaux d'intérêts généraux : 4 PA pour 1 point de gredin en moins: 
		  <input type="radio" name="valeur_1-lieu_tribunal" id="valeur_1-lieu_tribunal" value="1" onchange="$('#bouton_tribunal').attr('disabled',false);"> 
		  <?php endif;?>
		  
		  <?php if ($this->cautionOk === true) : ?>
		  Achat d'une caution : 100 castars et 1 PA pour 1 point de gredin en moins : 
		  <input type="radio" name="valeur_1-lieu_tribunal" id="valeur_1-lieu_tribunal" value="2" onchange="$('#bouton_tribunal').attr('disabled',false);">
		  <?php endif;?>
		  
		  <?php endif;?>
	  
	  <?php else: ?>
	  	Vous n'avez donc rien à faire au tribunal...
	  <?php endif;?>
  <?php else: ?>
  Vous avez actuellement <?php echo $this->user->points_redresseur_braldun;?>
 point<?php if ($this->user->points_redresseur_braldun > 1) : echo "s"; endif;?> de Redresseur de Torts.<br /><br />
 
	  <?php if ($this->contratEnCours == true) : ?>
	 	Vous ne pouvez pas vous racheter, il y a actuellement un contrat en cours sur votre tête...
	  <?php elseif ($this->utilisationPointPossible === true) : ?>
		 Souhaitez-vous soudoyer un employé du tribunal pour effacer l'historique de vos actes de redresseur (perdre tous les points de Redresseur) ? <br />
		  Coût: <?php echo $this->coutCastarsSoudoyer?> castars et 4 PA.<br /><br />
		  
		  <?php if (!$this->soudoyerOk) : ?>
		  	Vous n'avez pas assez de castars dans votre laban.
		  <?php endif;?>
		  <?php else: ?>
	  	Vous n'avez donc rien à faire au tribunal...
	  <?php endif;?>
 
  <?php endif;?>
  
 </div> 
</form>
<br /> 
<br />
<?php if ($this->utilisationPointPossible === true && $this->utilisationPossible === true) : ?>
	<input type='button' class='button1' id="bouton_tribunal" value='Valider' onclick="this.disabled=true;_get_('/lieux/doaction?caction=do_lieu_tribunal', 'lieu_tribunal', true);"    <?php if ($this->type == "gredin"): ?>disabled<?php endif;?>>
<?php endif; ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>