<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<? if ($this->contratEnCours != null) : ?>
		Voulez-vous vraiment annuler le contrat en cours ?<br /><br />
		
		Attention, si vous acceptez, vous allez perdre <?=$this->perte?>.
	<? else: ?>
		Vous n'avez aucun contrat à annuler.
	<? endif;?>
 </div>

</form>
<br />
<? if ($this->contratEnCours != null) : ?>
<input type='button' class='button1' id='bouton_annuler' value='Annuler le contrat' onclick='this.disabled=true;_get_("/contrat/doaction?caction=do_contrat_annuler");'/>
<? endif;?>

<? echo Bral_Helper_Fermer::affiche(); ?>