<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<?php if ($this->contratEnCours != null) : ?>
		Voulez-vous vraiment annuler le contrat en cours ?<br /><br />
		
		Attention, si vous acceptez, vous allez perdre <?php echo $this->perte?>.
	<?php else: ?>
		Vous n'avez aucun contrat à annuler.
	<?php endif;?>
 </div>

</form>
<br />
<?php if ($this->contratEnCours != null) : ?>
<input type='button' class='button1' id='bouton_annuler' value='Annuler le contrat' onclick='this.disabled=true;_get_("/contrat/doaction?caction=do_contrat_annuler");'/>
<?php endif;?>

<?php echo Bral_Helper_Fermer::affiche(); ?>