
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th colspan="4">
		  	
		  	Contrat n°<?php echo $this->contrat["id_contrat"]?>			
			</th>
		  </tr>
		</thead>
		<tbody>
		<?php $i = 0;?>
		   <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		    <td class="table_liste">
		   	Type du contrat
		   </td>
		   <td class="table_liste">
		   <?php if ($this->contrat["etat_contrat"] == "gredin") : ?>
		  		Gredin.<br />
		  		Vous devez mettre KO un Redresseur de Torts.
		  	<?php else :  ?>
		  		Redresseur de Torts.<br />
		  		Vous devez mettre KO un Gredin.
		  	<?php endif; ?>
		   </td>
		   </tr>
		   
		   <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		    <td class="table_liste">
		   	Objectif
		   </td>
		   <td class="table_liste">
		   	Vous devez mettre KO <?php echo Bral_Util_Lien::remplaceBaliseParNomEtJs("[b".$this->contrat["id_fk_cible_braldun_contrat"]."]");?>
		   </td>
		   </tr>
		   
		   <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		    <td class="table_liste">
		   	État
		    </td>
		   <td class="table_liste">
		   	<br />
			<?php if ($this->contrat["etat_contrat"] == "terminé"): ?>
		  		Terminé le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->contrat["date_fin_contrat"]);?>
		  	<?php elseif ($this->contrat["etat_contrat"] == "annulé"): ?> 
		  		Annulé le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->contrat["date_fin_contrat"]);?>
		  	<?php else: ?>
		  		En cours, depuis le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->contrat["date_creation_contrat"]);?>
		  	<?php endif;?>
		   </td>
		   </tr>
		   
		   <tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		    <td class="table_liste">
		   Gains
		   </td>
		   	<td class="table_liste">
		   	<?php if ($this->contrat["etat_contrat"] == "terminé"): ?>
		  		<?php echo $this->contrat["gain_contrat"]?>
		  	<?php elseif ($this->contrat["etat_contrat"] == "annulé"): ?> 
		  		Aucun.
		  	<?php else: ?>
		  		En attente.
		  	<?php endif;?>
		   	</td>
		   	</tr>
	   </tbody>
	</table>
					