<?php echo $this->render('/commun/menu_bourg.phtml')?>
<br/>
<div class="titre textalic textsizea">L'Office des Palmarès</div>
<table style="width:100%">
<tr>
	<td style="width:30px" valign="top" nowrap="nowrap">
		<div class="box_contenu textalic">
			<div class="titre textalic textsizec">
			Général
			</div>
			<?php foreach($this->selection as $s) : ?>
				<a href="/palmares/<?php echo $s["url"]?>" class="aWhite"><?php echo $s["nom"]?></a><br/>
			<?php endforeach;?>
			<br/>
			
			<div class="titre textalic textsizec">
			Réputation
			</div>
			<?php if (count($this->selectionReputation) > 0): ?>
				<?php foreach($this->selectionReputation as $s) : ?>
					<a href="/palmares/<?php echo $s["url"]?>" class="aWhite"><?php echo $s["nom"]?></a><br/>
				<?php endforeach;?>
			<?php endif; ?>
			<br/>
			
			<div class="titre textalic textsizec">
			Récolteurs
			</div>
			<?php if (count($this->selectionRecolteurs) > 0): ?>
				<?php foreach($this->selectionRecolteurs as $s) : ?>
					<a href="/palmares/<?php echo $s["url"]?>" class="aWhite"><?php echo $s["nom"]?></a><br/>
				<?php endforeach;?>
			<?php endif; ?>
			<br/>
			<div class="titre textalic textsizec">
			Fabricants
			</div>
			<?php if (count($this->selectionFabricants) > 0): ?>
				<?php foreach($this->selectionFabricants as $s) : ?>
					<a href="/palmares/<?php echo $s["url"]?>" class="aWhite"><?php echo $s["nom"]?></a><br/>
				<?php endforeach;?>
			<?php endif; ?>
			<br/>
			<div class="titre textalic textsizec">
			Runes
			</div>
			<?php if (count($this->selectionRunes) > 0): ?>
				<?php foreach($this->selectionRunes as $s) : ?>
					<a href="/palmares/<?php echo $s["url"]?>" class="aWhite"><?php echo $s["nom"]?></a><br/>
				<?php endforeach;?>
			<?php endif; ?>
			<br/>
		</div>
	</td>
	<td style="width:400px; border: 0px solid #791E1E;" valign="top">
		<div class="titre textalic textsizec">
			<?php echo $this->titre?><br/><br/>
		</div>
		<?php echo $this->render("commun/box_onglets.phtml"); ?>
	</td>
</tr>
</table>
