<? include("box_header.phtml") ?>
<div class="inner">
<ul class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Hobbit</th>
		<th><?=$this->titreColonne2?></th>
	  </tr>
	</thead>
  	<? if (count($this->evenements) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->evenements as $e): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste" >
		  			<a href="#" onClick="javascript:ouvrirWin('<?=$this->config->url->game?>/voir/hobbit/?hobbit=<?=$e["id_hobbit"]?>');" title="Cliquez pour voir votre profil">
		  				<?=$e["prenom_hobbit"]?> <?=$e["nom_hobbit"]?> (<?=$e["id_hobbit"]?>)
		  			</a>
		  		</td>
		  		<td class="table_liste">
		  			<?=$e["nombre"]?>
		  		</td>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
	<? else: ?>
	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
	</tr>
	<? endif; ?>
	</table>
	<br>
</ul>
</div>
<? include("box_bottom.phtml") ?>