<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Niveau</th>
		<th><?=$this->titreColonne2?></th>
		<? if ($this->afficheMoyenne === true) : ?>
			<th><?=$this->titreColonne3?></th>
		<? endif;?>
	  </tr>
	</thead>
  	<? if (count($this->sexes) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->sexes as $f): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<? if ($f["sexe_braldun"] == "masculin") :?>
		  				Masculin
		  			<? else: ?>
		  				Féminin
		  			<? endif;?>
		  		</td>
		  		<td class="table_liste">
		  			<?=$f["nombre"]?>
		  		</td>
		  		<? if ($this->afficheMoyenne === true) : ?>
	  				<td><?=floor($f["moyenne"])?></td>
	  			<? endif;?>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <? endif; ?>
   </table>
	<br>
</div>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>