<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu textalic">
	<?include("filtre.phtml")?>
	
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Braldûn</th>
		<th><?php echo $this->titreColonne2?></th>
		<?php if ($this->afficheMoyenne === true) : ?>
			<th><?php echo $this->titreColonne3?></th>
		<?php endif;?>
	  </tr>
	</thead>
  	<?php if (count($this->top10) > 0): ?>
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->top10 as $e): 
	  		if ($e["nombre"] > 0) :
	  		?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste" >
		  			<a href="#" onclick="javascript:ouvrirWin('<?php echo $this->config->url->game?>/voir/braldun/?braldun=<?php echo $e["id_braldun"]?>');" title="Cliquez pour voir le profil">
		  				<?php echo $e["prenom_braldun"]?> <?php echo $e["nom_braldun"]?> (<?php echo $e["id_braldun"]?>)
		  			</a>
		  		</td>
		  		<td class="table_liste">
		  			<?php echo $e["nombre"]?>
		  		</td>
		  		<?php if ($this->afficheMoyenne === true) : ?>
	  				<td><?php echo floor($e["moyenne"])?></td>
	  			<?php endif;?>
	  		</tr>
			<?php endif;?>
	  	<?php endforeach; ?>
	  	</tbody>
	<?php else: ?>
	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
	</tr>
	<?php endif; ?>
	</table>
	<br />
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>