<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu textalic">
	<?include("filtre.phtml")?>
	
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Tranche de Niveaux<br />
		0: 0 à 9<br />
		1: 10 à 19,<br />2: 20 à 29...</th>
		<th><?php echo $this->titreColonne2?></th>
		<?php if ($this->afficheMoyenne === true) : ?>
			<th><?php echo $this->titreColonne3?></th>
		<?php endif;?>
	  </tr>
	</thead>
  	<?php if (count($this->niveaux) > 0): ?>
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->niveaux as $f): ?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<?php echo $f["niveau"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?php echo $f["nombre"]?>
		  		</td>
		  		<?php if ($this->afficheMoyenne === true) : ?>
	  				<td><?php echo floor($f["moyenne"])?></td>
	  			<?php endif;?>
	  		</tr>
	  	<?php endforeach; ?>
	  	</tbody>
   <?php else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <?php endif; ?>
   </table>
	<br />
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>