<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<ul class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Tranche de Niveaux<br>
		0: 0 à 9<br>
		1: 10 à 19,<br>2: 20 à 29...</th>
		<th><?=$this->titreColonne2?></th>
		<? if ($this->afficheMoyenne === true) : ?>
			<th><?=$this->titreColonne3?></th>
		<? endif;?>
	  </tr>
	</thead>
  	<? if (count($this->niveaux) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->niveaux as $f): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<?=$f["niveau"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?=$f["nombre"]?>
		  		</td>
		  		<? if ($this->afficheMoyenne === true) : ?>
	  				<td><?=floor($f["moyenne"])?></td>
	  			<? endif;?>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <? endif; ?>
   </table>
	<br>
</ul>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>