<? include("box_header.phtml") ?>
<div class="inner">
<ul class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Famille</th>
		<th><?=$this->titreColonne2?></th>
		<? if ($this->afficheMoyenne === true) : ?>
			<th>Niveau moyen des pièces créées</th>
		<? endif;?>
	  </tr>
	</thead>
  	<? if (count($this->familles) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->familles as $f): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<?=$f["nom"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?=$f["nombre"]?>
		  		</td>
		  		<? if ($this->afficheMoyenne === true) : ?>
	  				<td><?=floor($f["moyenne"])?></td>
	  			<? endif;?>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <? endif; ?>
   </table>
	<br>
</ul>
</div>
<? include("box_bottom.phtml") ?>