<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu textalic">
	<?php include("filtre.phtml")?>
	
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Famille</th>
		<th><?php echo $this->titreColonne2?></th>
		<?php if ($this->afficheMoyenne === true) : ?>
			<th><?php echo $this->titreColonne3?></th>
		<?php endif;?>
	  </tr>
	</thead>
  	<?php if (count($this->familles) > 0): ?>
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->familles as $f): ?>
	  		<?php if ($f["nombre"] > 0) : ?>
		  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			  		<td class="table_liste">
			  			<?php echo $f["nom"]?>
			  		</td>
			  		<td class="table_liste">
			  			<?php echo $f["nombre"]?>
			  		</td>
			  		<?php if ($this->afficheMoyenne === true) : ?>
		  				<td><?php echo floor($f["moyenne"])?></td>
		  			<?php endif;?>
		  		</tr>
		  	<?php endif; ?>
	  	<?php endforeach; ?>
	  	</tbody>
   <?php else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <?php endif; ?>
   </table>
	<br />
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>