<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<ul class="box_contenu textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Hobbit</th>
		<th><?=$this->titreColonne2?></th>
		<? if ($this->afficheMoyenne === true) : ?>
			<th><?=$this->titreColonne3?></th>
		<? endif;?>
	  </tr>
	</thead>
  	<? if (count($this->top10) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->top10 as $e): 
	  		if ($e["nombre"] > 0) :
	  		?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste" >
		  			<a href="#" onClick="javascript:ouvrirWin('<?=$this->config->url->game?>/voir/hobbit/?hobbit=<?=$e["id_hobbit"]?>');" title="Cliquez pour voir le profil">
		  				<?=$e["prenom_hobbit"]?> <?=$e["nom_hobbit"]?> (<?=$e["id_hobbit"]?>)
		  			</a>
		  		</td>
		  		<td class="table_liste">
		  			<?=$e["nombre"]?>
		  		</td>
		  		<? if ($this->afficheMoyenne === true) : ?>
	  				<td><?=floor($e["moyenne"])?></td>
	  			<? endif;?>
	  		</tr>
			<? endif;?>
	  	<? endforeach; ?>
	  	</tbody>
	<? else: ?>
	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
	</tr>
	<? endif; ?>
	</table>
	<br>
</ul>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>