<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Type de monstre</th>
		<th>Nombre de kills de bralduns</th>
	  </tr>
	</thead>
  	<?php if (count($this->type) > 0): ?>
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->type as $e): ?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste" >
	  				<?php echo $e["nom_type_monstre"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?php echo $e["nombre"]?>
		  		</td>
	  		</tr>
	  	<?php endforeach; ?>
	  	</tbody>
	<?php else: ?>
	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
	</tr>
	<?php endif; ?>
	</table>
	<br />
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>