<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Monstre</th>
		<th>Nombre de kills de bralduns</th>
	  </tr>
	</thead>
  	<? if (count($this->top10) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->top10 as $e): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste" >
		  			<a href="#" onClick="javascript:ouvrirWin('<?=$this->config->url->game?>/voir/monstre/?monstre=<?=$e["id_monstre"]?>');" title="Cliquez pour voir le profil">
		  				<?=$e["nom_type_monstre"]?>, n&deg;<?=$e["id_monstre"]?>
		  			</a>
		  		</td>
		  		<td class="table_liste">
		  			<?=$e["nombre"]?>
		  		</td>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
	<? else: ?>
	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
	</tr>
	<? endif; ?>
	</table>
	<br>
</div>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>