<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	<?php include("filtre.phtml") ?>
	
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Mot</th>
		<th>Type de pièce</th>
		<th>Nombre</th>
	  </tr>
	</thead>
  	<?php if (count($this->mots) > 0): ?>
		<tbody>
	  	<?php $i = 0; 
	  	foreach($this->mots as $f): ?>
	  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<?php echo $f["suffixe"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?php echo $f["nomPiece"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?php echo $f["nombre"]?>
		  		</td>
	  		</tr>
	  	<?php endforeach; ?>
	  	</tbody>
   <?php else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <?php endif; ?>
   </table>
	<br />
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>