<?php echo $this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	<?php include("filtre.phtml")?>
	
	<br/>
	
	Total: <?php echo $this->total?>
	<br/>
		<table class="table_liste" style="width:90%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th>Famille</th>
			<th>Nombre</th>
		  </tr>
		</thead>
	  	<?php if (count($this->familles) > 0): ?>
			<tbody>
		  	<?php $i = 0; 
		  	foreach($this->familles as $f): ?>
		  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			  		<td class="table_liste">
			  			<?php echo $f["nom"]?>
			  		</td>
			  		<td class="table_liste">
			  			<?php echo $f["nombre"]?>
			  		</td>
		  		</tr>
		  	<?php endforeach; ?>
		  	</tbody>
	   <?php else: ?>
	   	<tr class="table_liste">
	   	 <td colspan='5'>
	   		Aucun résultat
	   	 </td>
	   	</tr>
	   <?php endif; ?>
	   </table>
	<br/>
</div>
</div>
<?php echo $this->render("commun/box_bottom.phtml") ?>