<? include("box_header.phtml") ?>
<div class="inner">
<ul class="box_contenu1 textalic">
	<?include("filtre.phtml")?>
	
	<br>
	
	Total: <?=$this->total?>
	<br>
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Comté</th>
		<th>Nombre</th>
	  </tr>
	</thead>
  	<? if (count($this->regions) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->regions as $r): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<?=$r["nom_region"]?>
		  		</td>
		  		<td class="table_liste">
		  			<?=$r["nombre"]?>
		  		</td>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <? endif; ?>
   </table>
	<br>
</ul>
</div>
<? include("box_bottom.phtml") ?>