<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	<? include("filtre.phtml") ?>
	
	<br />
	Les runes découvertes ce mois-ci ne sont pas prises en compte.<br />
	<br />
	<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th>Catégorie</th>
		<th>Nombre</th>
	  </tr>
	</thead>
  	<? if (count($this->categories) > 0): ?>
		<tbody>
	  	<? $i = 0; 
	  	foreach($this->categories as $f): ?>
	  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  		<td class="table_liste">
		  			<? if ($f["niveau"] == "d"): ?>
		  				Runes communes 
		  			<? elseif ($f["niveau"] == "c"): ?>
		  				Runes peu communes
		  			<? elseif ($f["niveau"] == "b"): ?>
		  				Runes rares 
		  			<? elseif ($f["niveau"] == "a"): ?>
		  				Runes très rares 
		  			<? endif;?>
		  		</td>
		  		<td class="table_liste">
		  			<?=$f["nombre"]?>
		  		</td>
	  		</tr>
	  	<? endforeach; ?>
	  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   	 <td colspan='5'>
   		Aucun résultat
   	 </td>
   	</tr>
   <? endif; ?>
   </table>
	<br />
</div>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>