<?=$this->render("commun/box_header.phtml") ?>
<div class="inner">
<div class="box_contenu1 textalic">
	
	Filtre par Niveau : <select id="filtre" name="filtre" onchange="_get_('/palmares/load?caction=do_palmares_<?=$this->nom_systeme?>_'+this.value+'_supersbralduns', false)">
	<? foreach($this->niveaux as $f): ?>
			<option value="<?=$f["niveau"]?>"<?if ($this->filtre == $f["niveau"]): echo " selected='selected'" ; endif;?>>Niveau <?=$f["niveau"]?></option>
	<? endforeach;?>
	</select>
	<br /><br />
	Pour un niveau choisi, la valeur maximum de chaque caractéristique (possédée par un braldun) est indiquée.<br />
	Les Bonus et les Malus ne sont pas pris en compte.
	<br /><br />
	
	<? if ($this->bralduns == null) : ?>
		Il n'y a pas assez de Braldûns de niveau <?=$this->filtre?> pour afficher les caractéristiques "Super Braldûns".
		<br /><br />
	<? else: ?>
		<table class="table_liste" style="width:90%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th>Caractéristique</th>
			<th>Valeur Maximum</th>
		  </tr>
		</thead>
			<tbody>
		  	<? $i = 0; 
		  	foreach($this->bralduns as $k => $v): ?>
		  		<tr class="table_liste<?=($i % 2);$i++; ?>">
		  			<td class="table_liste" >
		  			<?=$k?>
		  			</td>
			  		<td class="table_liste">
			  			<? if ($v["base"] != ""): ?>
			  				<?=($v["nombre"] + $v["base"]) ?>
			  			<? else: ?>
			  				<?=$v["nombre"] ?>
			  			<? endif;?>
			  			<?=$v["libelle"]?>
			  		</td>
		  		</tr>
		  	<? endforeach; ?>
		  	</tbody>
		</table>
	<? endif; ?>
	<br />
</div>
</div>
<?=$this->render("commun/box_bottom.phtml") ?>