<? if ($this->nb_runes == 0) : ?>
   <center><i>Vide</i></center>
<? else : ?>
	<div class="textalic textsizee">Poids d'une rune : <?=Bral_Util_Poids:: POIDS_RUNE?> Kg, 
	Poids total de la poche : <?=($this->nb_runes*Bral_Util_Poids::POIDS_RUNE) ?> Kg</div><br />
	
	<? if (count($this->runesNonIdentifiees) > 0) : ?>
		<div class="titre textalic textsized">Runes non identifi&eacute;es</div><br />
		<table class="table_liste" style="width:auto; padding:5px;" >
			<tbody>
			  <? $i = 0;
		      foreach ($this->runesNonIdentifiees as $r) : 
		     	 if ($i == 0) echo "<tr class='table_liste'>"; 
		    	?>
		    	<td class="table_liste table_liste_border">
		    		<div class="braltip">
		    		<span class="tip">Rune non identifi&eacute;e n&deg;<?=$r["id_rune"]?></span>
		    		<img src="/public/images/runes/rune_inconnue.png"  class="rune"  alt="Rune non identifi&eacute;e n&deg;<?=$r["id_rune"]?>" />
		    		</div>
		    	</td>
		    	<? 
		    	if ($i == 9) :
		    		echo "</tr>";
		    		$i = 0;
		    	else : 
		    		$i++;
		    	endif; 
		     endforeach;
		     if ($i > 0) {
			     for ($j = $i; $j <= 9; $j++) {
			     	echo "<td class='table_liste table_liste_border'>&nbsp;</td>";
			     }
			     echo "</tr>"; 
		     }
		     ?>
			</tbody>
		</table>
		<br />
	<? endif ?>

	<? if (count($this->runesIdentifiees) > 0) : ?>
		<div class="titre textalic textsized">Runes identifi&eacute;es</div><br />
		<table class="table_liste" style="width:auto; padding:5px;" >
			<tbody>
			  <? $i = 0;
		      foreach ($this->runesIdentifiees as $r) : 
		     	 if ($i == 0) echo "<tr class='table_liste'>"; 
		    	?>
		    	<td class="table_liste table_liste_border">
		    		<? if ($r["image"] != ""): ?>
		    		<div class="braltip">
		    		<span class="tip"><?=Bral_Helper_DetailRune::afficherTexte($r, true);?></span>
		    		<img src="/public/images/runes/<?=$r["image"]?>"  class="rune" alt="<?=$r["type"]?> n&deg;<?=$r["id_rune"]?>"  />
		    		</div>
	    			<? else: ?>
		    			<?=$r["type"]?> (<?=$r["id_rune"]?>)
		    		<? endif; ?>
		    	</td>
		    	<? 
		    	if ($i == 9) :
		    		echo "</tr>";
		    		$i = 0;
		    	else : 
		    		$i++;
		    	endif; 
		     endforeach;
		     if ($i > 0) {
			     for ($j = $i; $j <= 9; $j++) {
			     	echo "<td class='table_liste table_liste_border'>&nbsp;</td>";
			     }
			     echo "</tr>"; 
		     }
		     ?>
			</tbody>
		</table>
	<? endif; ?>
<? endif; ?>