<?php if ($this->ameliorationCompetence) : ?>
	<b>Vous avez r&eacute;ussi &agrave; am&eacute;liorer une de vos comp&eacute;tences de fabrication :</b>
	<br />
	<?php foreach($this->tabCompetencesAmeliorees as $c) : ?>
		<b><?php echo $c["nom_competence"]?> : + <?php echo $this->deCompetence?> % </b><br />
	<?php endforeach;?>
<?php else: ?>
	Vous n'avez pas r&eacute;ussi &agrave; am&eacute;liorer une de vos comp&eacute;tence de fabrication.
	<?php if ($this->boutiquerMetierCourant == false) :?>
		<br />Vous ne boutiquez pas dans l'échoppe de votre métier courant...
	<?php endif;?>
<?php endif;?>
<br /><br />

Vous avez boutiqu&eacute; <?php echo $this->petitEquipement["nom_petit_equipement"]?>.<br /><br />

Un fonctionnaire de la ville regarde votre objet : <br />
"<?php echo $this->message?>"<br /><br />

Il vous &eacute;change votre objet contre <?php echo $this->nbCastarsGagnes?> 
castar<?php if ($this->nbCastarsGagnes > 1): echo "s"; endif;?> (plac&eacute;<?php if ($this->nbCastarsGagnes > 1): echo "s"; endif;?> dans votre échoppe).
<br /><br /> 