 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->boutiquerEchoppeOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez boutiquer<br />
	<? elseif ($this->boutiquerEchoppeOk == false) : ?>
		Vous ne pouvez boutiquer que dans une de vos &eacute;choppes.
	<? else: ?>
		Vous n'avez pas assez de PA pour boutiquer...
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->boutiquerEchoppeOk === true) : ?>
<input type='button' class='button1' id='bouton_boutiquerforgeron' value='Boutiquer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_<?=$this->nomCompetenceBoutiquer?>");'>
<? endif ?>
