<div class="box_speciale" style="margin-top:15px;">
	<div class="inner textalid">
		<p class="titrea textalic titreasizec" style="margin-top:-15px;">
			<img src='<?php echo $this->config->url->static?>/images/vue/ballon.png'/> Saison 404 - 405 !
		<img src='<?php echo $this->config->url->static?>/images/vue/ballon.png'/> </p>

		A l'occasion d'une refonte des conditions de jeu de la Soule, dont l'attrait faisait jusqu'alors
		débat, la gazette de Crissbrouque est allée recueillir l'avis d'expert du très populaire Pierre
		Albalablabla.


		<p id='suitetexte'
		   onClick='$( "#suite" ).show("slow");$( "#suitetexte" ).hide();$( "#cachertexte" ).hide();'
		   style="cursor:pointer">[Afficher la
			suite]</p>

		<div id="suite" style="display:none">

			Grand artisan de cette réforme et membre honoraire de la FBICS (Fédération
		Braldûne Inter Comtés de Soule), ce dernier se félicite que des moyens supplémentaires aient été
		débloqués pour permettre à notre sport emblématique de retrouver son aura d'antan.


			En habile
			commentateur et fin harangueur des foules, il entend bien rendre de sa superbe à ce sport et
			à
			ses pratiquants. D'ailleurs, insistant sur les valeurs véhiculées par les athlètes, ainsi
			que
			sur les vertus collectives de la Soule, il souligne qu'une place est d'ores et déjà réservée
			à
			tous les participants au tableau d'honneur. Concluant notre brève entrevue par une envolée
			fiévreuse promettant gloire et distinction pour tous les joueurs... Vivement le début de la
			saison !!!

			<br/><br/>
			La saison 404 / 405 des matchs de Soule débute le 1er Halimath.
			Tous les participants recevront une distinction (5 pts) pour le premier match de la saison
			sur
			chaque terrain.
			<br/><br/>

			Rappel : la durée des tours de jeu est divisée par deux pendant un match de soule.
			Une fois connecté, allez dans l'onglet soule pour vous inscrire.
			L'inscription est gratuite !
			<br/>
			Tout match donnera lieu à 1 pt de distinction à chaque participant.

			<br/><br/>
			<a href="http://forum.braldahim.com/viewtopic.php?f=9&t=1158">Toutes les infos sur le
				forum</a>

			<p id='suitetexte'
			   onClick='$( "#suite" ).hide("slow");$( "#suitetexte" ).show();$( "#cachertexte" ).hide();'
			   style="cursor:pointer">[Cacher]</p>
			<br/>

		</div>

	</div>

</div>