<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>

 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=count($this->tabac) ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	<? if ($this->assezDePa == false) :?>
		Vous n'avez pas assez de PA.
	<? elseif ($this->acheterPossible === true) : ?>
		Vous avez <?=$this->user->castars_braldun?> castar<? if ($this->user->castars_braldun > 1): echo 's'; endif; ?>.<br />
		
		<br />Indiquez la quantit&eacute; souhait&eacute;e pour chaque type.
		
		<?=$this->render("/interface/commun/tabac/tabac.phtml"); ?>

	<? else : ?>
		Vous n'avez pas assez de castars.
	<? endif;?>
	
 </div>
<br />
</form>
<? if ($this->acheterPossible === true && $this->assezDePa === true) : ?>
	<input type='button' class='button1' id='bouton_achetertabac' value='Acheter !' onclick='for (i=1; i<=$("nb_valeurs").value; i++) { if ($("valeur_" + i).value == "") { $("valeur_" + i).value="0" }}; this.disabled=true; _get_("/boutique/doaction?caction=do_boutique_achetertabac");' disabled>
<? endif;?>
<? echo Bral_Helper_Fermer::affiche(); ?>