<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	<? if ($this->nomType == "bois"): ?>
		Acheter du Bois <br />
	<? endif;?>
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br /><br />
	
	Prix unitaire : <?=$this->tabStockPrix["prix_unitaire_vente_stock_bois"] ?> Castars.
	
	<? if ($this->possedeCharrette === true) : ?>
		<? if ($this->tabPoidsRondinsCharrette["nb_rondins_presents"] > 1) : $s = 's'; else: $s = ''; endif; ?>
		<br><br>
		Votre charrette contient actuellement <?=$this->tabPoidsRondinsCharrette["nb_rondins_presents"]?> rondin<?=$s?>. <br>
		Elle peut en contenir au maximum <?=$this->tabPoidsRondinsCharrette["nb_rondins_transportables"]?>.
	<? endif;?>
	<br /><br />
	
	<? if ($this->acheterPossible === true) : ?>
		Vous avez <?=$this->user->castars_hobbit?> castar<? if ($this->user->castars_hobbit > 1): echo 's'; endif; ?>.<br>
		Vous pouvez donc acheter <?=$this->nombreMaximum ?> article<? if ($this->nombreMaximum > 1): echo 's'; endif; ?>.
	<? elseif ($this->assezDePa === false) :?>
		Vous n'avez pas assez de PA.
	<? elseif ($this->possedeCharrette === false) :?>
		Vous n'avez pas de charrette pour stocker les rondins !
	<? elseif ($this->placeDisponible === false) :?>
		Vous n'avez pas assez de place dans votre charrette.
	<? else : ?>
		Vous n'avez pas assez de castars.
	<? endif;?>
	<br /><br />
	
	<? if ($this->acheterPossible === true && $this->assezDePa === true && $this->possedeCharrette === true) : ?>
	 Quantit&eacute; &agrave; acheter :
	 <input type='text' maxlength='7' size='7' name='valeur_1' id='valeur_1' value='0' onkeypress="chiffres(event);"  onkeyup="if (this.value > 0 && $('valeur_1').value > 0 && $('valeur_1').value <=<?=$this->nombreMaximum  ?>) {$('bouton_acheterbois').disabled=false} else {$('bouton_acheterbois').disabled=true} ">
 	<? endif; ?>
 </div>

</form>
<br />
<? if ($this->acheterPossible === true && $this->assezDePa === true && $this->possedeCharrette === true) : ?>
	<input type='button' class='button1' id='bouton_acheterbois' value='Acheter !' onClick='this.disabled=true; _get_("/boutique/doaction?caction=do_boutique_acheterbois");' disabled="true">
<? endif;?>
<? echo Bral_Helper_Fermer::affiche(); ?>