<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>

 <input type='hidden' id='nb_valeurs-achetertabac' name='nb_valeurs-achetertabac' value='<?php echo count($this->tabac) ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	<?php if ($this->assezDePa == false) :?>
		Vous n'avez pas assez de PA.
	<?php elseif ($this->acheterPossible === true) : ?>
		Vous avez <?php echo $this->user->castars_braldun?> castar<?php if ($this->user->castars_braldun > 1): echo 's'; endif; ?>.<br />
		
		<br />Indiquez la quantit&eacute; souhait&eacute;e pour chaque type.
		
		<?php echo $this->render("/interface/commun/tabac/tabac.phtml"); ?>

	<?php else : ?>
		Vous n'avez pas assez de castars.
	<?php endif;?>
	
 </div>
<br />
</form>
<?php if ($this->acheterPossible === true && $this->assezDePa === true) : ?>
	<input type='button' class='button1' id='bouton_achetertabac' value='Acheter !' onclick='for (i=1; i<=$("#nb_valeurs-achetertabac").val(); i++) { if ($("#valeur_" + i + "-achetertabac").val() == "") { $("#valeur_" + i).val("0")}}; this.disabled=true; _get_("/boutique/doaction?caction=do_boutique_achetertabac", "achetertabac");' disabled>
<?php endif;?>
<?php echo Bral_Helper_Fermer::affiche(); ?>