<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>

 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=($this->typePlantes["nb_valeurs"] + 1) ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	Destination : <br>
	<select name="valeur_1" id="valeur_1" onChange="_get_('/boutique/doaction?caction=ask_boutique_acheterpartieplantes&id_destination_courante='+this.value);">
 		<option value="-1">(Choisissez une destination)</option>
		<? foreach($this->destinationTransfert as $d) :?>
			<option value="<?=$d["id_destination"] ?>" <?=$d["selected"]?>><?=$d["texte"] ?></option>
		<? endforeach; ?>
	</select>
	<br><br>
	
	<? if ($this->assezDePa === false) :?>
		Vous n'avez pas assez de PA.
	<? elseif ($this->acheterPossible === true && $this->destinationTransfertCourante != null) : ?>
		Vous avez <?=$this->user->castars_hobbit?> castar<? if ($this->user->castars_hobbit > 1): echo 's'; endif; ?>.<br>
		<ul id="navigation" style="width:99%;text-align:left">
		<li id="acheter_info">
			<h3 id="acheter_info-head" class="head" onClick="maccordion(this);" />
				Attention, informations
			</h3>
			<ul id="acheter_info-body" style="display:block">
			<li>
				Attention, si vous demandez plus que ce que vous ne pouvez acheter (avec vos castars)
				 et avoir dans votre <?=$this->destinationTransfertCourante ?> (avec la place disponible restante),<br> 
				la boutique vous remplit votre conteneur (suivant la place et castars restants) sans vous demander votre avis ! <br>
				Poids actuellement disponible dans votre <?=$this->destinationTransfertCourante ?> : <?=$this->poidsRestant?> Kg<br>
				Poids d'une partie de plante : <?=Bral_Util_Poids:: POIDS_PARTIE_PLANTE_BRUTE?> Kg<br><br>
			</li>
			</ul>
		</li>
		<li id="acheter_detail">
			<h3 id="acheter_detail-head" class="head" onClick="maccordion(this);" />
				Quantit&eacute; &agrave; acheter.
			</h3>
			<ul id="acheter_detail-body" style="display:none">
			<li align='center'>
			Indiquez la quantit&eacute; souhait&eacute;e pour chaque type.<br>
		
			<?=$this->render("/interface/commun/plantes/plantes.phtml"); ?>
			</li>
			</ul>
		</li>
		</ul>
		
		</div>
	<? elseif ($this->destinationTransfertCourante != null) : ?>
		Vous n'avez pas assez de castars.
	<? endif;?>
	
 </div>
</form>
<? if ($this->acheterPossible === true && $this->assezDePa === true && $this->destinationTransfertCourante != null) : ?>
	<input type='button' class='button1' id='bouton_acheterpartieplantes' value='Acheter !' onClick='for (i=2; i<=$("nb_valeurs").value; i++) { if ($("valeur_" + i).value == "") { $("valeur_" + i).value="0" }}; this.disabled=true; _get_("/boutique/doaction?caction=do_boutique_acheterpartieplantes&id_destination_courante=<?=$this->destinationTransfertCourante?>");' disabled="true">
<? endif;?>
<? echo Bral_Helper_Fermer::affiche(); ?>