
<?php if ($this->elementsAchetes != "") :?>
	Vous avez achet&eacute; : <?php echo $this->elementsAchetes?>.<br />
	
	Au total, vous avez d&eacute;pens&eacute; <?php echo $this->coutCastars ?> castar<?php if ($this->coutCastars > 1): echo 's'; endif;?>
<?php else: ?>
	Vous n'avez rien achet&eacute;. <br /><br />
	
	Aucun PA n'a été dépensé.
<?php endif;?>

<?php if ($this->manqueCastars) : ?>
	<br />
	Certains &eacute;l&eacute;ments n'ont pas pu &ecirc;tes achet&eacute;s 
	<?php if ($this->manqueCastars) : ?>
		par manque de castars
	<?php endif;?> 
<?php endif;?> 
