<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	<br />
	
 </div>

</form>
<br />
<? echo Bral_Helper_Fermer::affiche(); ?>