
<? if ($this->elementsAchetes != "") :?>
	Vous avez achet&eacute; : <?=$this->elementsAchetes?>.<br>
	
	Au total, vous avez d&eacute;pens&eacute; <?=$this->coutCastars ?> castar<? if ($this->coutCastars > 1): echo 's'; endif;?>
<? else: ?>
	Vous n'avez rien achet&eacute;. <br><br>
	
	Aucun PA n'a été dépensé.
<? endif;?>

<? if ($this->manquePlace || $this->manqueCastars) : ?>
<br>
Certains &eacute;l&eacute;ments n'ont pas pu &ecirc;tes achet&eacute;s 
	<? if ($this->manquePlace) : ?>
		par manque de place
	<? endif;?> 
	<? if ($this->manqueCastars) : ?>
		<? if ($this->manquePlace) : ?>
		et
		<? endif;?>
		par manque de castars
	<? endif;?> 
<? endif;?> 
