<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idTypePlante ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='<?=$this->idTypePartiePlante ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Acheter des parties de plantes <br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br /><br />
	
	Prix unitaire : <?=$this->prixUnitaire ?> Castars.
	<br /><br />
	
	<? if ($this->acheterPossible === true) : ?>
		Vous avez <?=$this->user->castars_hobbit?> castar<? if ($this->user->castars_hobbit > 1): echo 's'; endif; ?>.<br>
		Vous pouvez donc acheter <?=$this->nombreMaximum ?> article<? if ($this->nombreMaximum > 1): echo 's'; endif; ?>.
	<? elseif ($this->assezDePa === false) :?>
		Vous n'avez pas assez de PA.
	<? else : ?>
		Vous n'avez pas assez de castars.
	<? endif;?>
	<br /><br />
	
	 Quantit&eacute; &agrave; acheter :
	 <input type='text' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);"  onkeyup="if (this.value > 0 && $('valeur_3').value > 0 && $('valeur_3').value <=<?=$this->nombreMaximum  ?>) {$('bouton_acheterpartieplantes').disabled=false} else {$('bouton_acheterpartieplantes').disabled=true} ">
 </div>

</form>
<br />
<? if ($this->acheterPossible === true && $this->assezDePa === true) : ?>
	<input type='button' class='button1' id='bouton_acheterpartieplantes' value='Acheter !' onClick='this.disabled=true; _get_("/boutique/doaction?caction=do_boutique_acheterpartieplantes");' disabled="true">
<? endif;?>
<? echo Bral_Helper_Fermer::affiche(); ?>