<? if ($this->elementsVendus != "") :?>
	Vous avez vendu les &eacute;l&eacute;ments suivants : <br />
	<?=htmlspecialchars($this->elementsVendus) ?>
<? else: ?>
	Vous n'avez rien vendu.
<? endif; ?>
<br><br>
<? if ($this->limitePoidsCastars === true) : ?>
Certains &eacute;l&eacute;ments n'ont pas pu &ecirc;tre vendus.<br>
Vous n'aviez pas assez de place dans votre laban pour recevoir les castars (m&ecirc;me en comptant la place r&eacute;cup&eacute;r&eacute;e par votre vente).
<? endif;?>