<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=$this->nb_valeurs ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez vendre des &eacute;l&eacute;ments de plantes pr&eacute;sents dans votre laban <br>
 	ou dans votre charrette (si vous en avez une).<br />
 	<br>
  	Source : <br>
	<select name="valeur_1" id="valeur_1" onChange="_get_('/boutique/doaction?caction=ask_boutique_vendrepartieplantes&id_source_courante='+this.value);">
 		<option value="-1">(Choisissez une source)</option>
		<? foreach($this->sourceTransfert as $d) :?>
			<option value="<?=$d["id_source"] ?>" <?=$d["selected"]?>><?=$d["texte"] ?></option>
		<? endforeach; ?>
	</select><br>
	Les gains en castars li&eacute;s &agrave; la vente iront dans la source choisie.
	<br><br>
	
	<? if ($this->sourceTransfertCourante != null) : ?>
	
	    <? if ($this->assezDePa === false) :?>
			Vous n'avez pas assez de PA
		<? elseif ($this->nb_partiePlantes == 0) : ?>
	   		Aucune plante brute &agrave; vendre<br />
	    <? else : ?>
		    <? if ($this->nb_partiePlantes==1):$s=''; else:$s='s';endif; ?>
	  		<?=$this->nb_partiePlantes?> &eacute;l&eacute;ment<?=$s?> de plantes brute<?=$s?>: <br />
	    
	    <table width='100%'>
	    <? $i = 0;
	      $enter = false;
	      foreach ($this->partieplantes as $k => $p) : 
	      	if ($p["quantite_".$this->sourceTransfertCourante."_partieplante"] > 0) :
	      		$enter = true;
		    	if ($i % 3 == 0) echo "<tr>"; 
		    	?>
		    	<td>
		    		<? if ($p["quantite_".$this->sourceTransfertCourante."_partieplante"] > 1) : $s="s" ; else: $s=""; endif; ?>
			    	<?=htmlspecialchars($p["nom_plante"])?> : <?=$p["quantite_".$this->sourceTransfertCourante."_partieplante"]?> <?=htmlspecialchars($p["nom_type"])?><?=$s ?> brute<?=$s ?>.
		    		<br />
		    		<? if ($p["prixUnitaireReprise"] > 1): $s='s'; else: $s=''; endif; ?>
	    			Prix Reprise : <?=$p["prixUnitaireReprise"] ?> castar<?=$s?><br>
		    		Quantit&eacute; &agrave; vendre : 
		    		<br>
		    		<input type='text' maxlength='4' size='4' name='valeur_<?=$k?>' id='valeur_<?=$k?>' value='0' onkeypress="chiffres(event, false);" 
		    		onkeyup="if (this.value=='')this.value = 0;if (this.value > <?=$p["quantite_".$this->sourceTransfertCourante."_partieplante"] ?>) { this.value= <?=$p["quantite_".$this->sourceTransfertCourante."_partieplante"] ?>}; v=false;for (i=1;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_vendrepartieplantes').disabled=false;}else{$('bouton_vendrepartieplantes').disabled=true;}">
		    		<input type='hidden' maxlength='4' size='4' name='valeur_<?=$k?>_max' id='valeur_<?=$k?>_max' value='<?=$p["quantite_".$this->sourceTransfertCourante."_partieplante"]?>' >
		    	<br>
		    	</td>
		    	<? if ($i % 3 == 2) echo "</tr>"; 
		    	$i++; 
		    endif;
	     endforeach;
	     if ($enter == true) :
	     	if  ($i % 3 != 0) echo "</tr>"; 
	     endif;
	     ?>
	    </table>
	   <? endif; ?>
	  <? endif;?>
 </div>

</form>
<br />

<?php 
$js = "
	cacher = true;
	for (i=1; i<=".$this->nb_valeurs."; i++) {
		$('valeur_' + i).value = $('valeur_' + i + '_max').value;
		if (cacher == true && $('valeur_' + i + '_max').value > 0) {
			cacher = false;
		}
	}
	$('bouton_vendrepartieplantes').disabled=cacher;

";
?>
<?php if ($this->vendrePartieplantesOk === true && $this->sourceTransfertCourante != null && $this->assezDePa === true) : ?>
	<input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onClick="<?=$js?>"> <br>
	<input type='button' class='button1' id='bouton_vendrepartieplantes' value='Vendre !' onClick='this.disabled=true;_get_("/boutique/doaction?caction=do_boutique_vendrepartieplantes&id_source_courante=<?=$this->sourceTransfertCourante?>");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>