<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez vendre des rondins pr&eacute;sents dans votre charrette.<br />
	<br />
	<? if ($this->charretteOk === true && $this->charrette["nb_rondin"] > 0): ?>
		Rondins : <?=$this->charrette["nb_rondin"] ?>
		Quantit&eacute; &agrave; d&eacute;poser : 
		<input type='text' maxlength='4' size='4' name='valeur_1' id='valeur_1' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0; if (this.value > <?=$this->charrette["nb_rondin"]  ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=2;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_vendrebois').disabled=false;}else{$('bouton_vendrebois').disabled=true;}" >
		<input type='hidden' maxlength='4' size='4' name='valeur_1_max' id='valeur_1_max' value='<?=$this->charrette["nb_rondin"] ?>' >
		<br />
	<? else : ?>
	Vous n'avez pas pas de rondin &agrave; vendre.
		<input type='hidden' maxlength='4' size='4' name='valeur_1_max' id='valeur_1_max' value='0' >
		<input type='hidden' maxlength='4' size='4' name='valeur_1' id='valeur_1' value='0' >
	<? endif; ?>
 </div>

</form>
<br />

<?php 
$js = "
	cacher = true;
	$('valeur_1').value = $('valeur_1' + '_max').value;
	if (cacher == true && $('valeur_1' + '_max').value > 0) {
		cacher = false;
	}
	$('bouton_vendrebois').disabled=cacher;

";
?>
<?php if ($this->vendreBoisOk === true) : ?>
	<input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onClick="<?=$js?>"> <br>
	<input type='button' class='button1' id='bouton_vendrebois' value='Vendre !' onClick='this.disabled=true;_get_("/boutique/doaction?caction=do_boutique_vendrebois");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>