<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	Vous pouvez vendre des peaux pr&eacute;sentes dans votre laban <br />
 	ou dans votre charrette (si vous en avez une).<br />
 	<br />
 	Source : <br />
	<select name="valeur_1" id="valeur_1" onChange="_get_('/boutique/doaction?caction=ask_boutique_vendrepeaux&id_source_courante='+this.value);">
 		<option value="-1">(Choisissez une source)</option>
		<? foreach($this->sourceTransfert as $d) :?>
			<option value="<?=$d["id_source"] ?>" <?=$d["selected"]?>><?=$d["texte"] ?></option>
		<? endforeach; ?>
	</select><br />
	Les gains en castars li&eacute;s &agrave; la vente iront dans la source choisie.
	<br />
	
	<? if ($this->sourceTransfertCourante != null) : ?>
	
	<br />
		<? if ($this->assezDePa === false) :?>
			Vous n'avez pas assez de PA
		<? elseif ($this->nb_peaux == 0 ) : ?>
			Aucune peau &agrave; vendre<br />
		<? else: ?>
	    <? if ($this->nb_peaux == 1):$s=''; else:$s='x';endif; ?>
	    	Vous avez <?=$this->nb_peaux?> peau<?=$s?> dans <?=$this->sourceTransfertCourante?>.<br />
	    
	   		<? if ($this->prixRepriseUnitaire > 1) : $s='s'; else: $s=""; endif; ?>
			 La boutique vous donne <?=$this->prixRepriseUnitaire?> castar<?=$s?> par peau.
			 <br /><br />
			Quantit&eacute; &agrave; vendre : 
			<input type='text' maxlength='4' size='4' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event, false);" onkeyup="if (this.value=='')this.value = 0; if (this.value > <?=$this->nb_peaux  ?>) { alert('Valeur trop grande'); this.value=0}; v=false;for (i=1;i<=$('nb_valeurs').value;i++){if ($('valeur_'+i).value>0)v=true;};if (v==true){$('bouton_vendrepeaux').disabled=false;}else{$('bouton_vendrepeaux').disabled=true;}" >
			<input type='hidden' maxlength='4' size='4' name='valeur_2_max' id='valeur_2_max' value='<?=$this->nb_peaux ?>' >
			<br />
			
	    <? endif; ?>
    <? endif;?>
 </div>

</form>
<br />

<?php if ($this->vendrePeauxOk === true && $this->sourceTransfertCourante != null && $this->assezDePa === true) : ?>
	<input type='button' class='button1' id='bouton_vendrepeaux' value='Vendre !' onclick='this.disabled=true;_get_("/boutique/doaction?caction=do_boutique_vendrepeaux&id_source_courante=<?=$this->sourceTransfertCourante?>");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>