
<ul class="titre textalic textsizee">
Recherche par Équipement
</ul>

<select name="hotel_menu_recherche_equipements" id="hotel_menu_recherche_equipements" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheEquipement as $m) : ?>
	<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
	<? foreach($m["elements"] as $e) : ?>
		<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
	<? endforeach; ?>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Matériel
</ul>
<select name="hotel_menu_recherche_materiels" id="hotel_menu_recherche_materiels" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheMateriel as $m) : ?>
	<? foreach($m["elements"] as $e) : ?>
		<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
	<? endforeach; ?>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Matière Première
</ul>
<select name="hotel_menu_recherche_matieres_premieres" id="hotel_menu_recherche_matieres_premieres" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheMatieresPremieres as $m) : ?>
	<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
	<? foreach($m["elements"] as $e) : ?>
		<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
	<? endforeach; ?>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Matière Transformée
</ul>
<select name="hotel_menu_recherche_matieres_transformees" id="hotel_menu_recherche_matieres_transformees" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheMatieresTransformees as $m) : ?>
	<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
	<? foreach($m["elements"] as $e) : ?>
		<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
	<? endforeach; ?>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Aliment
</ul>
<select name="hotel_menu_recherche_aliments" id="hotel_menu_recherche_aliments" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheAliment as $e) : ?>
	<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Potion
</ul>
<select name="hotel_menu_recherche_potions" id="hotel_menu_recherche_potions" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRecherchePotion as $e) : ?>
	<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
<? endforeach;?>
</select>

<br><br>
<ul class="titre textalic textsizee">
Recherche par Rune
</ul>
<select name="hotel_menu_recherche_runes" id="hotel_menu_recherche_runes" onChange="jsMenuHotel(this.id, this.value)">
<option value="-1">Choisissez un type de recherche</option>
<? foreach($this->menuRechercheRune as $e) : ?>
	<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
<? endforeach;?>
</select>

