
<table class="table_liste" style="width:95%">
<thead class="table_liste">
<tr class="table_liste">
	<th colspan="4">Recherche dans l'Hôtel des Ventes</th>
</tr>
</thead>
<tr>
<td colspan='4'>
		<select name="hotel_menu_recherche_pratique" id="hotel_menu_recherche_pratique" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Recherches pratiques</option>
		<? foreach($this->menuRecherchePratique as $m) : ?>
			<option value="<?=$m["numero_element"]?>" <?=$m["selected"]?>><?=$m["nom"]?></option>
		<? endforeach;?>
		</select>
</td>
</tr>
<tr>
	<td>
		<select name="hotel_menu_recherche_equipements" id="hotel_menu_recherche_equipements" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Équipements</option>
		<? foreach($this->menuRechercheEquipement as $m) : ?>
			<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
			<? foreach($m["elements"] as $e) : ?>
				<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
			<? endforeach; ?>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_potions" id="hotel_menu_recherche_potions" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Potions et Vernis</option>
		<? foreach($this->menuRecherchePotion as $e) : ?>
			<option value="<?=$e["numero_element"]?>"><?=$e["nom_type"]?> <?=$e["nom"]?></option>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_materiels" id="hotel_menu_recherche_materiels" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matériels</option>
		<? foreach($this->menuRechercheMateriel as $m) : ?>
			<option value="<?=$m["numero_element"]?>"><?=$m["nom"]?></option>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_munitions" id="hotel_menu_recherche_munitions" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Munitions</option>
		<? foreach($this->menuRechercheMunition as $m) : ?>
			<option value="<?=$m["numero_element"]?>"><?=$m["nom"]?></option>
		<? endforeach;?>
		</select>
	</td>
</tr>
<tr>
	<td>
		<select name="hotel_menu_recherche_matieres_premieres" id="hotel_menu_recherche_matieres_premieres" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matières Premières</option>
		<? foreach($this->menuRechercheMatieresPremieres as $m) : ?>
			<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
			<? foreach($m["elements"] as $e) : ?>
				<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
			<? endforeach; ?>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_matieres_transformees" id="hotel_menu_recherche_matieres_transformees" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matières Transformées</option>
		<? foreach($this->menuRechercheMatieresTransformees as $m) : ?>
			<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
			<? foreach($m["elements"] as $e) : ?>
				<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
			<? endforeach; ?>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_runes" id="hotel_menu_recherche_runes" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Runes</option>
		<? foreach($this->menuRechercheRune as $e) : ?>
			<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
		<? endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_aliments_ingredients" id="hotel_menu_recherche_aliments_ingredients" onChange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Aliments / Ingrédients</option>
		<? foreach($this->menuRechercheAlimentsIngredients as $m) : ?>
			<optgroup label="<?=$m["titre"]?>" style="font-weight:bold"></optgroup>
			<? foreach($m["elements"] as $e) : ?>
				<option value="<?=$e["numero_element"]?>"><?=$e["nom"]?></option>
			<? endforeach; ?>
		<? endforeach;?>
		</select>
	</td>
</tr>
</table>

