<? foreach($e["objet"] as $a) : ?>
<img src='<?=$this->config->static->url?>/styles/braldahim_defaut/images/type_aliment/type_aliment_<?=$a["id_type_aliment"]?>.png'>
<br />
n°<?=$a["id_vente_aliment"] ?> <?=$a["nom"] ?> 
	<? if ($a["bbdf"] > 0): ?>
 		de qualit&eacute; <?=$a["qualite"] ?> 
 	<? endif;?> 
 	<? if ($a["bbdf"] > 0): ?> +<?=$a["bbdf"]?> % (recette <?=htmlspecialchars($a["recette"]) ?>)<? endif;?> <br />
<? endforeach;?>