
<?php if ($this->venteDefaut == true) : ?>
	<div class="titre textalic">
	Affichage des 50 dernières ventes inscrites
	</div>
	Vous pouvez affiner votre recherche avec les listes à choix présentes ci-dessus.
	<br /><br />
<?php endif;?>
 <br />
 <table class="table_liste" style="width:95%">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg; Vente <br />Date fin</th>
		<th>Nom</th>
		<th>Vendeur</th>
		<th>Prix</th>
		<th>Commentaire</th>
		<th>Acheter</th>
	  </tr>
	</thead>
  <?php if (count($this->resultats) > 0): ?>
	<tbody>
	
	<?php if ($this->user->pa_braldun >= $this->paUtilisationHotel): 
		$disabled = "";
	else:
		$disabled = "disabled" ;
	endif;
	?>

  	<?php $i = 0; 
  	foreach($this->resultats as $e): ?>
  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
  			<td class="table_liste">N&deg;<?php echo $e["vente"]["id_vente"]?>
  			<br /><?php echo $e["vente"]["date_fin_vente"]?>
  			</td>
	  		<td class="table_liste">
	  		<?php
	  		if ($e["type"] == "equipement") :
	  			include("resultats_equipements.phtml");
	  		elseif ($e["type"] == "munition") :
	  			include("resultats_munitions.phtml");
	  		elseif ($e["type"] == "element") :
	  			include("resultats_elements.phtml");
	  		elseif ($e["type"] == "minerai") :
	  			include("resultats_minerais.phtml");
	  		elseif ($e["type"] == "partieplante") :
	  			include("resultats_plantes.phtml");
	  		elseif ($e["type"] == "graine") :
	  			include("resultats_graines.phtml");
	  		elseif ($e["type"] == "ingredient") :
	  			include("resultats_ingredients.phtml");
	  		elseif ($e["type"] == "aliment") :
	  			include("resultats_aliments.phtml");
	  		elseif ($e["type"] == "potion") :
	  			include("resultats_potions.phtml");
	  		elseif ($e["type"] == "rune") :
	  			include("resultats_runes.phtml");
	  		elseif ($e["type"] == "materiel") :
	  			include("resultats_materiels.phtml");
	  		endif;
	  		?>
	  		</td>
	  		<td class="table_liste">
	  			<a onclick="javascript:ouvrirWin('/voir/braldun/?braldun=<?php echo $e["vente"]["id_braldun"]?>');" title="Cliquez pour voir le profil">
		  		<?php echo $e["vente"]["prenom_braldun"]?> <?php echo $e["vente"]["nom_braldun"]?> (<?php echo $e["vente"]["id_braldun"]?>)
		  		</a>
		  		<img src='<?php echo $this->config->static->url?>/images/uddeim/env.gif' title='Envoyer un message' alt='Ecrire' border='0' onclick="ecrireMessage('<?php echo $e["vente"]["id_braldun"]?>');" style='cursor:pointer'/>
	  		</td>
	  		<td class="table_liste">
	  		<?php echo Bral_Helper_DetailHotel::afficherPrix($e["vente"]);?>
	  		</td>
	  		<td class="table_liste"><?php echo Bral_Util_BBParser::bbcodeReplace($e["vente"]["commentaire_vente"])?></td>
	  		<td class="table_liste">
	  			<input type="button" class='button1' onclick='_get_("/hotel/doaction?caction=ask_hotel_acheter&valeur_1=<?php echo $e["vente"]["id_vente"]?>");' value="<?php echo $this->paUtilisationHotel ?> PA - Acheter" <?php echo $disabled?>>
		  	</td>
  		</tr>
  	<?php endforeach; ?>
  	</tbody>
   <?php else: ?>
   	<tr class="table_liste">
   		<td colspan="5">
   			Aucun r&eacute;sultat
   		</td>
   	</tr>
   <?php endif; ?>
</table>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

