Vous avez achet&eacute; l'&eacute;quipement suivant : <br />
<?=htmlspecialchars($this->equipement["nom"])." ".htmlspecialchars(addslashes($this->equipement["suffixe"]))." de qualit&eacute; ".htmlspecialchars($this->equipement["qualite"]) ?>,
 n&deg; <?=$this->equipement["id_equipement"]; ?>
 pour <?=$this->detailPrix?>.<br><br>
La pi&egrave; est plac&eacute;e dans <?=$this->destination["texte"]?>.