<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->equipement["id_equipement"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	<?php if (floor($this->user->niveau_braldun / 10) < $this->vente["objet"]["niveau"]) : ?>
		<br /><br />Attention ! Vous n'avez pas le niveau requis pour équiper cette pièce.
	<?php endif;?>
	<br /><br />
	
	<?php echo $this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
	<br />
	
	<?php if ($this->equipement["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br />
	<?php endif; ?>
	
	<?php if (count($this->prix) > 0) : ?>
		
		<?php foreach($this->destinationTransfert as $d) :?>
			<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>" value="<?php if ($d["possible"] == true): echo 1; endif;?>"/>
			<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>_force" value="<?php if ($d["possible_force"] == true): echo 1; endif;?>"/>
		<?php endforeach; ?>
		
		<?php
		$jsTrue = "";
		$jsFalse = "";
		$js = "";
		foreach($this->prix as $k => $p) {
			if ($p["possible"] === true) {
				$jsTrue .= "$('bouton_achetereequipement".$k."').disabled = true;";
				$jsFalse .= "if ($('possible_'+this.value+'_force').value == 1 && ('".$p["id_destination"]."' != this.value)) {  $('bouton_achetereequipement".$k."').disabled = true } else { $('bouton_achetereequipement".$k."').disabled = false};";
			}
		}
		if ($jsTrue != "" && $jsFalse != "") {
			$jsTrue = substr($jsTrue, 0, strlen($jsTrue)-1);
			$jsFalse = substr($jsFalse, 0, strlen($jsFalse)-1);
			$js = " if (this.value == -1) {".$jsTrue."} else {".$jsFalse."}";
		}
		?>
		
		Destination de la pi&egrave;ce : <br />
		<select name="valeur_3" id="valeur_3" onchange="<?php if ($js!= ""): echo $js; endif;?>">
	 		<option value="-1">(Choisissez une destination)</option>
			<?php foreach($this->destinationTransfert as $d) :?>
				<option value="<?php echo $d["id_destination"] ?>" <?php if ($d["possible"] == false && $d["possible_force"] == false): echo "disabled"; endif;?>><?php echo $d["texte"] ?> <?php if ($d["possible"] == false && $d["possible_force"] == false): echo " : pas assez de place"; endif;?></option>
			<?php endforeach; ?>
		</select>
		
		<br /><br />
		<div class="titre textalic textsizec">Prix</div>
		<br />
			
		<?php foreach($this->prix as $k => $p) : ?>
			<?php echo $p["id_destination"] ?> : <?php echo $p["prix"] ?> <?php echo $p["nom"] ?>
			<?php if ($this->assezDePa !== true): ?>
			: Pas assez de PA
			<?php elseif ($p["possible"] === true && $this->equipement["place_dispo"] === true) : ?>
				<input type='button' class='button1' id='bouton_achetereequipement<?php echo $k?>' value='Acheter !' onclick='this.disabled=true;$("valeur_2").value=<?php echo $k ?>; _get_("/echoppe/doaction?caction=do_echoppe_acheterequipement&idEquipement=<?php echo $this->equipement["id_equipement"] ?>");' disabled>
			<?php elseif ($this->equipement["place_dispo"] !== true): ?>
			: Pas assez de place disponible
			<?php else: ?>
			: Pas assez de ressources
			<?php endif; ?>
			<br />
		<?php endforeach; ?>
		
	<?php endif; ?>
	
 </div>

</form>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>