<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->potion["id_potion"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	<br />
	
	<?php $this->potions = array($this->potion); ?>
	<?php $this->idPotionsTable = false ?>
	<?php echo $this->render("/interface/commun/potions/potions.phtml"); ?>
	
	<br />
	
	<?php if ($this->potion["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban <br />
	<?php endif; ?>
	
	<div class="titre textalic textsizec">Prix</div>
	
	<?php if (count($this->prix) > 0) : ?>
		<?php foreach($this->prix as $k => $p) : ?>
			<?php echo $p["prix"] ?> <?php echo $p["nom"] ?>
			<?php if ($this->assezDePa !== true): ?>
			: Pas assez de PA
			<?php elseif ($p["possible"] === true && $this->potion["place_dispo"] === true) : ?>
				<input type='button' class='button1' id='bouton_acheterepotion' value='Acheter !' onclick='this.disabled=true;$("valeur_2").value=<?php echo $k ?>; _get_("/echoppe/doaction?caction=do_echoppe_acheterpotion&idPotion=<?php echo $this->potion["id_potion"] ?>");'>
			<?php elseif ($this->potion["place_dispo"] !== true): ?>
			: Pas assez de place disponible
			<?php else: ?>
			: Pas assez de ressources
			<?php endif; ?>
			<br />
		<?php endforeach; ?>
	<?php endif; ?>
	
 </div>

</form>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>