<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->equipement["id_equipement"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	<br />
	
	<? $this->equipements = array($this->equipement); ?>
	<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
	<br />
	
	<? if ($this->equipement["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br>
	<? endif; ?>
	
	<? if (count($this->prix) > 0) : ?>
		
		<?
		$jsTrue = "";
		$jsFalse = "";
		$js = "";
		foreach($this->prix as $k => $p) {
			if ($p["possible"] === true) {
				$jsTrue .= "$('bouton_achetereequipement".$k."').disabled = true,";
				$jsFalse .= "$('bouton_achetereequipement".$k."').disabled = false,";
			}
		}
		if ($jsTrue != "" && $jsFalse != "") {
			$jsTrue = substr($jsTrue, 0, strlen($jsTrue)-1);
			$jsFalse = substr($jsFalse, 0, strlen($jsFalse)-1);
			$js = " if (this.value == -1) {".$jsTrue."} else {".$jsFalse."}";
		}
		?>
		Destination de la pi&egrave;ce : <br>
		<select name="valeur_3" id="valeur_3" onChange="<? if ($js!= ""): echo $js; endif;?>">
	 		<option value="-1">(Choisissez une destination)</option>
			<? foreach($this->destinationTransfert as $d) :?>
				<option value="<?=$d["id_destination"] ?>" <? if ($d["possible"] == false): echo "disabled"; endif;?>><?=$d["texte"] ?> <? if ($d["possible"] == false): echo " : pas assez de place"; endif;?></option>
			<? endforeach; ?>
		</select>
		
		<br><br>
		<ul class="titre textalic textsizec">Prix</ul>
		<br>
			
		<? foreach($this->prix as $k => $p) : ?>
			<?=$p["id_destination"] ?> : <?=$p["prix"] ?> <?=$p["nom"] ?>
			<? if ($this->assezDePa !== true): ?>
			: Pas assez de PA
			<? elseif ($p["possible"] === true && $this->equipement["place_dispo"] === true) : ?>
				<input type='button' class='button1' id='bouton_achetereequipement<?=$k?>' value='Acheter !' onClick='this.disabled=true;$("valeur_2").value=<?=$k ?>; _get_("/echoppe/doaction?caction=do_echoppe_acheterequipement&idEquipement=<?=$this->equipement["id_equipement"] ?>");' disabled>
			<? elseif ($this->equipement["place_dispo"] !== true): ?>
			: Pas assez de place disponible
			<? else: ?>
			: Pas assez de ressources
			<? endif; ?>
			<br />
		<? endforeach; ?>
		
	<? endif; ?>
	
 </div>

</form>
<br />
<? echo Bral_Helper_Fermer::affiche(); ?>