<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->potion["id_potion"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	<br />
	
	<? $this->potions = array($this->potion); ?>
	<?=$this->render("/interface/commun/potions/potions.phtml"); ?>
	
	<br />
	<ul class="titre textalic textsizec">Prix</ul>
	
	<? if (count($this->prix) > 0) : ?>
		<? foreach($this->prix as $k => $p) : ?>
			<?=$p["prix"] ?> <?=$p["nom"] ?>
			<? if ($this->assezDePa !== true): ?>
			: Pas assez de PA
			<? elseif ($p["possible"] === true) : ?>
				<input type='button' class='button1' id='bouton_acheterepotion' value='Acheter !' onClick='this.disabled=true;$("valeur_2").value=<?=$k ?>; _get_("/echoppe/doaction?caction=do_echoppe_acheterpotion");'>
			<? else: ?>
			: Pas assez de ressources
			<? endif; ?>
			<br />
		<? endforeach; ?>
	<? endif; ?>
	
 </div>

</form>
<br />
<? include("commun_fermer.phtml") ?>