<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->materiel["id_materiel"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	<br />
	<? if ($this->materiel["est_charrette"] == true) : ?>
	<b>Si vous achetez une charrette, celle-ci sera d&eacute;pos&eacute;e au sol.</b><br>
	Vous devrez utiliser ensuite l'action "Attraper Charrette" de l'onglet Charrette pour attraper la charrette.<br>
	Attention aux caract&eacute;ristiques n&eacute;cessaires pour l'attraper et pensez &agrave; garder un PA pour le faire juste après l'achat.<br>
	<? endif;?>
	
	<br><br>
	<? $this->materiels = array($this->materiel); ?>
	<?=$this->render("/interface/commun/materiels/materiels.phtml"); ?>
	<br />
	
	<? if ($this->materiel["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban <br>
	<? endif; ?>
	
	<ul class="titre textalic textsizec">Prix</ul>
	
	<? if (count($this->prix) > 0) : ?>
		<? foreach($this->prix as $k => $p) : ?>
			<?=$p["prix"] ?> <?=$p["nom"] ?>
			<? if ($this->assezDePa !== true): ?>
			: Pas assez de PA
			<? elseif ($p["possible"] === true && $this->materiel["place_dispo"] === true) : ?>
				<input type='button' class='button1' id='bouton_acheteremateriel' value='Acheter !' onClick='this.disabled=true;$("valeur_2").value=<?=$k ?>; _get_("/echoppe/doaction?caction=do_echoppe_achetermateriel");'>
			<? elseif ($this->materiel["place_dispo"] !== true): ?>
			: Pas assez de place disponible
			<? else: ?>
			: Pas assez de ressources
			<? endif; ?>
			<br />
		<? endforeach; ?>
	<? endif; ?>
	
 </div>

</form>
<br />
<? echo Bral_Helper_Fermer::affiche(); ?>