<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->aliment["id_aliment"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	<br />
	<?php $this->aliments = array($this->aliment); ?>
	<?php echo $this->render("/interface/commun/aliments/aliments.phtml"); ?>
	<br />
	
	<?php if ($this->aliment["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br />
	<?php endif; ?>
	
	<?php if (count($this->prix) > 0) : ?>
		
		<?php foreach($this->destinationTransfert as $d) :?>
			<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>" value="<?php if ($d["possible"] == true): echo 1; endif;?>"/>
			<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>_force" value="<?php if ($d["possible_force"] == true): echo 1; endif;?>"/>
		<?php endforeach; ?>
		
		<?php if ($this->aliment["est_charrette"] === false) : ?>
			<?
			$jsTrue = "";
			$jsFalse = "";
			$js = "";
			foreach($this->prix as $k => $p) {
				if ($p["possible"] === true) {
					$jsTrue .= "$('bouton_acheterealiment".$k."').disabled = true;";
					$jsFalse .= "if ($('possible_'+this.value+'_force').value == 1 && ('".$p["id_destination"]."' != this.value)) {  $('bouton_acheterealiment".$k."').disabled = true } else { $('bouton_acheterealiment".$k."').disabled = false};";
				}
			}
			if ($jsTrue != "" && $jsFalse != "") {
				$jsTrue = substr($jsTrue, 0, strlen($jsTrue)-1);
				$jsFalse = substr($jsFalse, 0, strlen($jsFalse)-1);
				$js = " if (this.value == -1) {".$jsTrue."} else {".$jsFalse."}";
			}
			?>
			Destination de la pi&egrave;ce : <br />
			<select name="valeur_3" id="valeur_3" onchange="<?php if ($js!= ""): echo $js; endif;?>">
		 		<option value="-1">(Choisissez une destination)</option>
				<?php foreach($this->destinationTransfert as $d) :?>
					<option value="<?php echo $d["id_destination"] ?>" <?php if ($d["possible"] == false && $d["possible_force"] == false): echo "disabled"; endif;?>><?php echo $d["texte"] ?> <?php if ($d["possible"] == false && $d["possible_force"] == false): echo " : pas assez de place"; endif;?></option>
				<?php endforeach; ?>
			</select>
		<?php else :?>
			 <input type='hidden' id='valeur_3' name='valeur_3' value='laban'>
		<?php endif;?>
		
		<br />
		
		<?php if ($this->aliment["charrette_possible"] === false) : ?>
				Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?php echo $this->aliment["charrette_detail"]?>
		<?php else: ?>	
			<div class="titre textalic textsizec">Prix</div>
			<br />
			<?php foreach($this->prix as $k => $p) : ?>
				<?php echo $p["id_destination"] ?> : <?php echo $p["prix"] ?> <?php echo $p["nom"] ?>
				<?php if ($this->assezDePa !== true): ?>
				: Pas assez de PA
				<?php elseif ($this->aliment["charrette_possible"] === false) : ?>
					<br />
					Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?php echo $this->aliment["charrette_detail"]?>
				<?php elseif ($p["possible"] === true && $this->aliment["place_dispo"] === true) : ?>
					<input type='button' class='button1' id='bouton_acheterealiment<?php echo $k?>' value='Acheter !' onclick='this.disabled=true;$("valeur_2").value=<?php echo $k ?>; _get_("/echoppe/doaction?caction=do_echoppe_acheteraliment");' <?php if ($this->aliment["est_charrette"] == false) : echo "disabled"; endif;?>></input>
				<?php elseif ($this->aliment["place_dispo"] !== true): ?>
				: Pas assez de place disponible
				<?php else: ?>
				: Pas assez de ressources
				<?php endif; ?>
				<br />
			<?php endforeach; ?>
		<?php endif;?>
	<?php endif; ?>
	
 </div>

</form>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>