<?php if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; produire un mat&eacute;riel : 
	<br />
	<?php echo htmlspecialchars($this->typeMaterielCourant["nom_type_materiel"]) ?> n°<?php echo $this->id_materiel_cree ?>.
	<br /><br />
<?php else: ?>
	Vous avez manqu&eacute; votre production.<br/>
	La moiti&eacute; des mati&egrave;res premi&egrave;res est d&eacute;truite.<br />
<?php endif; ?>