 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <? if ($this->produireEchoppeOk === true) : ?>
		 Pour <?=$this->nb_pa ?> PA, vous pouvez produire un mat&eacute;riel.<br /><br />
	     
	     Type de mat&eacute;riel :<br />
	     <select name="valeur_1" id="valeur_1"  onChange="_get_('/competences/doaction?caction=ask_competence_<?=$this->nom_systeme?>&type_materiel='+this.value);">
		 	<option value="-1">(Choisissez un mat&eacute;riel)</option>
		 	<? foreach($this->typeMateriel as $t) : ?>
		 		<option value="<?=$t["id_type_materiel"]?>" <?=$t["selected"]?>><?=htmlspecialchars($t["nom_type_materiel"])?></option>
		 	<? endforeach; ?>
		 </select>
		 
		 <br /><br />
		 
		<? if (isset($this->typeMaterielCourant)) : ?>
		<?=Bral_Helper_DetailMateriel::afficheRecette($this->typeMaterielCourant);?>
		<? endif;?>
			
		<? if (isset($this->cout)): ?>
		<br />Co&ucirc;t 
			<? if ($this->ressourcesOk === false) : ?>
		 		(Pas assez de ressource dans l'&eacute;choppe)
			<? endif; ?> : 
		 	<? foreach($this->cout as $key1 => $c) :?>
	 			<br /><?=htmlspecialchars($c["nom"]) ?> : <?=$c["cout"] ?> <? if (isset($c["unite"]) && $c["unite"] != "") :?><?=$c["unite"] ?><? if ($c["cout"] > 1) : echo 's'; endif;?> <? if ($c["ressourcesOk"] == "non") : echo ' ressources Ko'; else:  echo ' ressources Ok'; endif;?><? endif; ?>
		 	<? endforeach; ?>
		<? endif; ?>
	
	 <? elseif ($this->produireEchoppeOk == false) : ?>
		Vous ne pouvez produire que dans une de vos &eacute;choppes.
	<? else: ?>
		Vous n'avez pas assez de mati&egrave;res premi&egrave; pour produire...
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->produireEchoppeOk === true && $this->etape1 === true && $this->ressourcesOk === true) : ?>
<input type='button' class='button1' id='bouton_produire' value='Produire !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_<?=$this->nom_systeme?>&type_materiel="+$("valeur_1").value);'>
<? endif ?>
