<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Bosquets</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
			<?php if ($this->creation === true) : ?>
			<b>Cr&eacute;ation de <?php echo $this->nb_creation ?> bosquets</b> <br />
			<b>Les bosquets créés en villes ont été ensuite supprimés</b>.<br />
			<?php endif; ?>
			<form action="/Administrationbosquet/bosquets" method="post">
			<table align='center'>
			<tr>
			<th class='comp_titre'>Zone</th>
			<th class='comp_titre'>Bosquet</th>
			<th class='comp_titre'>Couverture</th>
			</tr>
			<tr valign='top'>
				<td>
					<select name="id_zone">
					<?php foreach ($this->zones as $z) : ?>
					<option value="<?php echo $z["id_zone"]?>"><?php echo $z["id_zone"]?></option>
					<?php endforeach; ?>
					</select>
				</td>
				<td>
					<select name="id_type_bosquet_bosquet">
					<?php foreach ($this->typeBosquets as $p) : ?>
					<option value="<?php echo $p["id_type_bosquet"]?>"><?php echo $p["nom"]?></option>
					<?php endforeach; ?>
					</select>
					<br />
					Quantit&eacute; min <input type="text" name="quantite_min" onkeypress="chiffres(event);" />
					 max : <input type="text" name="quantite_max" onkeypress="chiffres(event);" /> <br />
				</td>
				<td>
					<select name="couverture">
					<?php for ($i=1; $i<100; $i++) : ?>
						<option value="<?php echo $i?>"><?php echo $i?> %</option>
					<?php endfor; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td colspan='3'> <input type="submit"  class='button' name="Ajouter" value="Ajouter la couverture de bosquet" /></td>
			</tr>
			</table>
			</form>
		<br /><br />
			<table  align='center'>
			<tr>
			<th class='comp_titre'>N&deg;</th>
			<th class='comp_titre'>Environnement</th>
			<th class='comp_titre'>x_min</th>
			<th class='comp_titre'>x_max</th>
			<th class='comp_titre'>y_min</th>
			<th class='comp_titre'>y_max</th>
			<th class='comp_titre'>Nombre Cases</th>
			<th class='comp_titre'>Nombre Bosquets</th>
			<th class='comp_titre'>Couverture</th>
			</tr>
			<?php foreach ($this->zones as $zone) : ?>
				<tr>
					<td><?php echo $zone["id_zone"] ?></td>
					<td><?php echo $zone["environnement"] ?></td>
					<td><?php echo $zone["x_min"] ?></td>
					<td><?php echo $zone["x_max"] ?></td>
					<td><?php echo $zone["y_min"] ?></td>
					<td><?php echo $zone["y_max"] ?></td>
					<td><?php echo $zone["nombre_cases"] ?></td>
					<td><?php echo $zone["nombre_bosquets"] ?></td>
					<td><?php echo $zone["couverture"] ?> % </td>
					<td>
					
					</td>
				</tr>
			<?php endforeach; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>