Bonjour ! <br /><br />

Votre braldun <?=$this->braldun["prenom_braldun"] ?> <?=$this->braldun["nom_braldun"] ?> (N°<?=$this->braldun["id_braldun"] ?>) a été supprimé. <br /><br />

Soit vous n'avez jamais activé votre compte, soit vous ne l'avez pas joué depuis plus de <?=$this->nbJours?> jours.

Pour créer un nouveau braldun, rendez-vous ici : <br />
<a href="<?=$this->urlJeu ?>"><?=$this->urlJeu ?></a><br /><br />

A bientôt ! <br /><br />

--<br />
Les Maitres du jeu