Bonjour ! 

Votre hobbit vous réclame, corps et âme.

Il sera supprimé le <?=$this->dateSuppression?> si vous ne le jouez pas avant. 
Si toutefois vous ne pouvez pas le jouer pendant plusieurs jours, nous vous conseillons de le mettre en hibernation.
En hibernation, votre hobbit ne sera pas supprimé et n'apparaîtra pas dans le monde de Braldahim.

Email : <?=$this->hobbit["email_hobbit"] ?> 

Hobbit : <?=$this->hobbit["prenom_hobbit"] ?> <?=$this->hobbit["nom_hobbit"] ?>.

Numero du Hobbit :<?=$this->hobbit["id_hobbit"] ?>.

Pour vous connecter, rendez-vous ici : <?=$this->urlJeu ?>

Si vous rencontrer un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante :  <?=$this->adresseSupport ?>

Bon jeu ! 

--
Les Maitres du jeu