Bonjour ! <br /><br />

Votre hobbit <?=$this->hobbit["prenom_hobbit"] ?> <?=$this->hobbit["nom_hobbit"] ?> (N°<?=$this->hobbit["id_hobbit"] ?>) a été supprimé. <br /><br />

Soit vous n'avez jamais activé votre compte, soit vous ne l'avez pas joué depuis plus de <?=$this->nbJours?> jours.

Pour créer un nouveau hobbit, rendez-vous ici : <br />
<a href="<?=$this->urlJeu ?>"><?=$this->urlJeu ?></a><br /><br />

A bientôt ! <br /><br />

--<br />
Les Maitres du jeu