<div class="textalic">
<table width="100%" cellspacing="30px">
	<tr valign="top">
		<td style="width:25%">
			<div class="titrea textalic textsizeb">
			Actuellement
			</div>
			Sujet : 
			<script language="Javascript" src="http://ircube.org/webmasters/stats/?op=topic&channel=braldahim"></script>
			
			<p class="a">❧</p>
			
			Nombre de Braldûns présents dans le salon : 
			<script language="Javascript" src="http://ircube.org/webmasters/stats/?op=users&channel=braldahim"></script>
			
		</td>
		<td  style="width:60%; text-align:center;">
			<div class="titrea textalic titreasize0">
			Le Chat
			</div>
			<br/>
			
			<script type="text/javascript" src="http://ircube.org/js/box.js"></script><input type="hidden" id="ircube_chan" value="braldahim" /><input type="hidden" id="ircube_version" value="1" /><form name='chat' method='post' action='javascript:Chat2();'>
			 <div id='chat' name='chat'>
				Votre pseudo : <input type='text' name='nickname' class='chat_edit' required>
				<input type=submit value='Chatter !' class='chat_bouton'>
			</div>
			</form>

			
			<p class="a">❧</p>
			
			Vous pouvez également rejoindre le salon en utilisant un client IRC (exemples : Win : <a href="http://www.mirc.com/">Mirc</a>, OSX: <a href="http://colloquy.info/">Colloquy</a>).<br />
			<br />
			Paramètres : <br />
			serveur IRC : irc.ircube.org<br />
			Salon : #Braldahim<br />


		</td>
	</tr>
</table>

</div>