<?php Zend_Loader::loadClass("Bral_Helper_Tri"); ?>
<br />
<div class="titre textalic textsizea">Liste des Membres</div><br />

Filtrer par rang : 
<select name='valeur_2'  onchange="Javascript:_get_('/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=f&valeur_2='+ this.value + '&valeur_3=0&valeur_4=-1&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')">
    <option value="-1">Tous les rangs</option>
<?php foreach ($this->tabRangs as $r) : ?>
  	<option value='<?php echo $r["id_type_rang"]?>' <?if ($this->filtre == $r["id_type_rang"]){echo "selected";}?>><?php echo $r["nom"]?></option>
  	<?php endforeach; ?>
  	</select>
  	<br /><br />
  	
<table class="table_liste" style="width:90%">
<thead class="table_liste">
  <tr class="table_liste" title="Cliquer pour Trier">
	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=1&valeur_6=<?php echo $this->sensOrdre ?>");'>Pr&eacute;nom <?php echo Bral_Helper_Tri::sens(1, $this->ordre, $this->sensOrdre); ?></th>
	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=2&valeur_6=<?php echo $this->sensOrdre ?>");'>Nom <?php echo Bral_Helper_Tri::sens(2, $this->ordre, $this->sensOrdre); ?></th>
	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=3&valeur_6=<?php echo $this->sensOrdre ?>");'>N&deg; <?php echo Bral_Helper_Tri::sens(3, $this->ordre, $this->sensOrdre); ?></th>
	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=4&valeur_6=<?php echo $this->sensOrdre ?>");'>Niveau <?php echo Bral_Helper_Tri::sens(4, $this->ordre, $this->sensOrdre); ?></th>
	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=5&valeur_6=<?php echo $this->sensOrdre ?>");'>Date d'entr&eacute;e <?php echo Bral_Helper_Tri::sens(5, $this->ordre, $this->sensOrdre); ?></th>
 	<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=o&valeur_2=<?php echo $this->filtre ?>&valeur_5=6&valeur_6=<?php echo $this->sensOrdre ?>");'>Rang <?php echo Bral_Helper_Tri::sens(6, $this->ordre, $this->sensOrdre); ?></th>
 	<th style="cursor:pointer" nowrap>Profil Public</th>
  </tr>
</thead>
<tfoot class="table_liste">
  <tr class="table_liste">
    <th colspan='10'>
    	Affichage de <?php echo count($this->tabMembres) ?> braldun<?php if (count($this->tabMembres) > 1) : echo 's'; endif; ?> sur un total de <?php echo $this->nbMembresTotal ?> dans la communaut&eacute;<br />
       <?php if ($this->precedentOk === true) : ?>
	   <input type="button" class='button1' onclick="Javascript:_get_('/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=p&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')" value="Page pr&eacute;c&eacute;dente">
	   <?php endif; ?>
	   <?php if ($this->suivantOk === true) : ?>
	   <input type="button" class='button1' onclick="Javascript:_get_('/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres&valeur_1=s&valeur_2=<?php echo $this->filtre ?>&valeur_3=<?php echo $this->page ?>&valeur_4=<?php echo $this->filtre?>&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>')" value="Page suivante">
	   <?php endif; ?>
    </th>
  </tr>
</tfoot>
<tbody>
<?php if (count($this->tabMembres) > 0): ?>
<?php $i = 0;
   foreach($this->tabMembres as $m) :?>
	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	  <td class="table_liste"><?php echo $m["prenom_braldun"] ?></td>	
	  <td class="table_liste"><?php echo $m["nom_braldun"] ?></td>
	  <td class="table_liste"><?php echo $m["id_braldun"] ?></td>
	  <td class="table_liste"><?php echo $m["niveau_braldun"] ?></td>
	  <td class="table_liste"><?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$m["date_entree"]); ?></td>
	  <td class="table_liste">Rang n&deg;<?php echo $m["ordre_rang_communaute"] ?> : <?php echo $m["nom_rang_communaute"] ?></td>
	  <td class="table_liste"><input type="button" class='button1' onclick="Javascript:document.location.href='/voir/braldun/?braldun=<?php echo $m["id_braldun"] ?>';" value="Voir"></td>
	</tr>
<?php endforeach; ?>
<?php else: ?>
	<tr class="table_liste0">
	  <td class="table_liste" colspan="10">Pas d'autre membre</td>
	</tr>
<?php endif; ?>
</tbody>
</table>