<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
<div class="inner">
    <ul class="titre textalic textsizea">Administration</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
	    <a href='<?$this->baseUrl?>/AdministrationFilons/filons'>Administration Filons</a> 
	    
	     <br> <br> <br>
	    Administration Hobbit 
	    <a href='<?$this->baseUrl?>/AdministrationHobbits/Hobbits'>[ Liste ]</a>
	    Hobbit Id <input type='text' name='id_hobbit' id='id_hobbit' value='' size='5'> <input type='button' name='goFiche' value='Ouvrir Fiche'   class='button1'  onClick='document.location.href="<?=$this->baseUrl ?>/administrationHobbits/Hobbit/mode/simple/idhobbit/"+$("id_hobbit").value;'> 
	    <br><br>
	    Administration Monstres 
	    <a href='<?$this->baseUrl?>/AdministrationMonstres/creation'>[ Cr&eacute;ation ]</a> 
	    <a href='<?$this->baseUrl?>/AdministrationMonstres/referentiel'>[ R&eacute;f&eacute;rentiel ]</a>
	    <a href='<?$this->baseUrl?>/viemonstres/vie'>[ Jouer Vie Monstre ]</a>
	    <br> <br> <br>
	    
	    <a href='<?$this->baseUrl?>/AdministrationPlantes/plantes'>Administration Plantes</a><br>
		
		</ul>
	</div>
	&nbsp;
</div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
</div>
<?php echo $this->render('footer.phtml'); ?>