<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="box_titre1">Administration Plantes</div><br />
	
	<form action="<?=$this->baseUrl ?>/administration/plantes" method="post">
	<table>
	<th class='comp_titre'>Zone</th>
	<th class='comp_titre'>Plante</th>
	<th class='comp_titre'>Couverture</th>
	<tr valign='top'>
		<td>
			<select name="id_zone">
			<? foreach ($this->zones as $z) : ?>
			<option value="<?=$z["id"]?>"><?=$z["id"]?></option>
			<? endforeach; ?>
			</select>
		</td>
		<td>
			<select name="id_plante">
			<? foreach ($this->typePlantes as $p) : ?>
			<option value="<?=$z["id"]?>"><?=htmlentities($p["nom"])?> - <?=htmlentities($p["categorie"]) ?> - <?=htmlentities($p["environnement"])?> - A:<?=htmlentities($p["nom_partie_1"])?> - B:<?=htmlentities($p["nom_partie_2"])?> - C:<?=htmlentities($p["nom_partie_3"])?> - D:<?=htmlentities($p["nom_partie_4"]) ?></option>
			<? endforeach; ?>
			</select>
			<br>
			Quantité partie A : <input type="textbox" name="partie_1"><br>
			Quantité partie B : <input type="textbox" name="partie_2"><br>
			Quantité partie C : <input type="textbox" name="partie_3"><br>
			Quantité partie D : <input type="textbox" name="partie_4"><br>
		</td>
		<td>
			<select name="couverture">
			<? for ($i=1; $i<100; $i++) : ?>
				<option value="<?=$i?>"><?=$i?> %</option>
			<? endfor; ?>
			</select>
		</td>
	</tr>
	<tr>
		<td colspan='3'> <input type="submit" name="add" value="ajouter la couverture de plante" /></td>
	</tr>
	</table>
	</form>
<br><br>
 <div class="box_contenu2">
	<table>
	<th class='comp_titre'>N°</th>
	<th class='comp_titre'>Environnement</th>
	<th class='comp_titre'>x_min</th>
	<th class='comp_titre'>x_max</th>
	<th class='comp_titre'>y_min</th>
	<th class='comp_titre'>y_max</th>
	<th class='comp_titre'>Nombre Cases</th>
	<th class='comp_titre'>Nombre Plantes</th>
	<th class='comp_titre'>Couverture</th>
	<? foreach ($this->zones as $zone) : ?>
		<tr>
			<td><?=$zone["id"] ?></td>
			<td><?=htmlentities($zone["environnement"]) ?></td>
			<td><?=$zone["x_min"] ?></td>
			<td><?=$zone["x_max"] ?></td>
			<td><?=$zone["y_min"] ?></td>
			<td><?=$zone["y_max"] ?></td>
			<td><?=$zone["nombre_cases"] ?></td>
			<td><?=$zone["nombre_plantes"] ?></td>
			<td><?=$zone["couverture"] ?> % </td>
			<td>
			
			</td>
		</tr>
	<? endforeach; ?>
	</table>
 </div>
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>