<div class="inner">
<ul class="box_contenu1 textalic"><br>
	
	<ul class="titre textalic textsizec">
		Match n°<?=$this->matchEnCours["id_soule_match"]?>
		- <?=$this->matchEnCours["nom_soule_terrain"]?> 
		<br> 
		<? if ($this->matchEnCours["date_debut_soule_match"] == null && $this->matchEnCours["date_fin_soule_match"] == null) : ?>
		Non d&eacute;but&eacute;  - Inscriptions en cours
		<? elseif ($this->matchEnCours["date_debut_soule_match"] != null && $this->matchEnCours["date_fin_soule_match"] == null) : ?>
		En Cours
		<? else: ?>
		Terminé
		<? endif;?>
	</ul>
	<br>
	Adresse directe pour vos marques-pages : <a href='http://www.braldahim.com/brasserie/?match=<?=$this->matchEnCours["id_soule_match"]?>'>http://www.braldahim.com/brasserie/?match=<?=$this->matchEnCours["id_soule_match"]?></a>
	<br><br>
	<? if ($this->matchEnCours["date_debut_soule_match"] != null && $this->matchEnCours["date_fin_soule_match"] == null) :?>
		<? if ($this->matchEnCours["x_ballon_soule_match"] != null && $this->matchEnCours["y_ballon_soule_match"]) :?>
			Le ballon est actuellement libre et se trouve en x:<?=$this->matchEnCours["x_ballon_soule_match"]?>,
			y:<?=$this->matchEnCours["y_ballon_soule_match"]?>
		<? elseif ($this->matchEnCours["id_fk_joueur_ballon_soule_match"] != null && $this->porteur != null): ?>
			Le ballon est actuellement port&eacute; par <?=Bral_Util_Lien::getJsHobbit($this->matchEnCours["id_fk_joueur_ballon_soule_match"], $this->porteur["prenom_hobbit"]." ".$this->porteur["nom_hobbit"]." (".$this->porteur["id_hobbit"].")")?>
			qui est en x:<?=$this->porteur["x_hobbit"]?> y:<?=$this->porteur["y_hobbit"]?>
		<? endif;?>
	<? endif;?>

<table width="100%">
	<tr>
		<td valign="top"><? include("voir/carte.phtml");?></td>
		<td valign="top"><? include("voir/evenements.phtml");?></td>
	</tr>
</table>
<?php include("voir/equipes.phtml")?>
</ul>
</div>
