<table width="80%" align="center">
	<tr>
		<td width="100%" valign="top">
			<ul id="navigation" style="width:99%;text-align:left">
				<?php foreach($this->arBoutiqueTransformes as $k => $v) : ?>
					<?php if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueTransformes<?php echo $k?>">
				      	<h3 id="arboutiqueTransformes<?php echo $k?>-head" class="head" onclick="maccordion(this);">
							<?php echo htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueTransformes<?php echo $k?>-body" style="display:none">
							<li>
								<?php include("poche_arr_bout_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</td>
	</tr>
</table>
