<div class="titre textalic textsizec">L'arri&egrave;re-boutique</div><br />
C'est dans l'arri&egrave;re-boutique que l'artisan entrepose les mati&egrave;res premi&egrave;res
n&eacute;cessaires &agrave; l'exercice de son art. <br />
C'est aussi ici que sa caisse est en 
s&eacute;curit&eacute;. Il y stocke les diff&eacute;rentes monnaies d'&eacute;change utilis&eacute;es.
<br /><br />

<div class="titre textalid textsizec">Mati&egrave;res premi&egrave;res</div><br />
<?php if ($this->afficheType == "aliments") :?>
	<?php include("arriere_boutique_ressources_ingredients.phtml") ?>
<?php else: ?>
	<?php include("arriere_boutique_ressources.phtml") ?>
<?php endif;?>
	
<?php if ($this->estSurEchoppe === true && $this->user->activation == true && $this->user->pa_braldun >= 1): 
	$disabled = "";
else:
	$disabled = "disabled" ;
?>
	<?php if ($this->estSurEchoppe == false) : ?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
  	<?php elseif ($this->user->activation == false) :?>
  		Tour non activé à la connexion, vous n'avez pas acc&egrave;s aux actions...<br />
  	<?php elseif ($this->user->pa_braldun < 1) :?>
  		Vous n'avez pas assez de PA, vous n'avez pas acc&egrave;s aux actions...<br />
  	<?php endif; ?>
<?php endif; ?>
    
<input type="button" class='button1' value="1 PA - Retirer des mati&egrave;res premi&egrave;res"
       onclick="Javascript:_get_('/competences/doaction?caction=ask_competence_transbahuter&valeur_1=5')"  <?php echo $disabled ?>/>
<input type="button" class='button1' value="1 PA - D&eacute;poser des mati&egrave;res premi&egrave;res"
       onclick="Javascript:_get_('/competences/doaction?caction=ask_competence_transbahuter')"  <?php echo $disabled ?> />
	
<br /><br /><br />

<div class="titre textalic textsizec">La caisse</div>
<?php include("caisse.phtml") ?>