<ul class="titre textalic textsizec">L'arri&egrave;re-boutique</ul><br />
C'est dans l'arri&egrave;re-boutique que l'artisan entrepose les mati&egrave;res premi&egrave;res
n&eacute;cessaires &agrave; l'exercice de son art. <br>
C'est aussi ici que sa caisse est en 
s&eacute;curit&eacute;. Il y stocke les diff&eacute;rentes monnaies d'&eacute;change utilis&eacute;es.
<br /><br />

<ul class="titre textalid textsizec">Mati&egrave;res premi&egrave;res</ul><br />
<? if ($this->afficheType == "aliments") :?>
	<? include("arriere_boutique_ressources_ingredients.phtml") ?>
<? else: ?>
	<? include("arriere_boutique_ressources.phtml") ?>
<? endif;?>
	
<? if ($this->estSurEchoppe === true && $this->user->activation == true && $this->user->pa_braldun >= 1): 
	$disabled = "";
else:
	$disabled = "disabled" ;
?>
	<? if ($this->estSurEchoppe == false) : ?>
  		Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
  	<? elseif ($this->user->activation == false) :?>
  		Tour non activé à la connexion, vous n'avez pas acc&egrave;s aux actions...<br />
  	<? elseif ($this->user->pa_braldun < 1) :?>
  		Vous n'avez pas assez de PA, vous n'avez pas acc&egrave;s aux actions...<br />
  	<? endif; ?>
<? endif; ?>
    
<input type="button" class='button1' value="1 PA - Retirer des mati&egrave;res premi&egrave;res"
       onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_transbahuter&valeur_1=5')"  <?=$disabled ?>/>
<input type="button" class='button1' value="1 PA - D&eacute;poser des mati&egrave;res premi&egrave;res"
       onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_transbahuter')"  <?=$disabled ?> />
	
<br /><br /><br />

<ul class="titre textalic textsizec">La caisse</ul>
<? include("caisse.phtml") ?>