<table width="80%" align="center">
	<tr>
		<td width="50%" valign="top">
			<ul class="titre textalic textsizee">Mat&eacute;riaux Bruts</ul>
			<ul id="navigation" style="width:99%;text-align:left">
				<? foreach($this->arBoutiqueBruts as $k => $v) : ?>
					<? if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueBruts<?=$k?>">
				      	<h3 id="arboutiqueBruts<?=$k?>-head" class="head" onClick="maccordion(this);" />
							<?=htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueBruts<?=$k?>-body" style="display:none">
							<li>
								<? include("poche_arr_bout_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<? endif; ?>
				<? endforeach; ?>
			</ul>
		</td>
		<td width="50%" valign="top">
			<ul class="titre textalic textsizee">Mat&eacute;riaux Transform&eacute;s</ul>
			<ul id="navigation" style="width:99%;text-align:left">
				<? foreach($this->arBoutiqueTransformes as $k => $v) : ?>
					<? if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueTransformes<?=$k?>">
				      	<h3 id="arboutiqueTransformes<?=$k?>-head" class="head" onClick="maccordion(this);" />
							<?=htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueTransformes<?=$k?>-body" style="display:none">
							<li>
								<? include("poche_arr_bout_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<? endif; ?>
				<? endforeach; ?>
			</ul>
		</td>
	</tr>
</table>

<? if ($this->estSurEchoppe === true): 
	$disabled = "";
else:
	$disabled = "disabled" ;
?>
	Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
<? endif; ?>
    
<input type="button" class='button1' value="0 PA - Retirer des mati&egrave;res premi&egrave;res"
       onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirerressources&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')"  <?=$disabled ?>/>
<input type="button" class='button1' value="0 PA - D&eacute;poser des mati&egrave;res premi&egrave;res"
       onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_deposerressources&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')"  <?=$disabled ?> />
