<ul class="titre textalic textsizec">L'arri&egrave;re-boutique</ul><br />
C'est dans l'arri&egrave;re-boutique que l'artisan entrepose les mati&egrave;res premi&egrave;res
n&eacute;cessaires &agrave; l'exercice de son art. <br>
C'est aussi ici que sa caisse est en 
s&eacute;curit&eacute;. Il y stocke les diff&eacute;rentes monnaies d'&eacute;change utilis&eacute;es.
<br /><br />

	<ul class="titre textalid textsizec">Mati&egrave;res premi&egrave;res</ul><br />
	<? include("arriere_boutique_ressources.phtml") ?>
	
	<br /><br /><br />
	
	<ul class="titre textalic textsizec">La caisse</ul>
  	<? include("caisse.phtml") ?>