<?php Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
<?php if (count($this->potionsArriereBoutique) > 0): ?>

	<?php $this->potions = $this->potionsArriereBoutique; ?>
	<?php $this->idPotionsTable = $this->idPotionsArriereBoutiqueTable; ?>
	<?php echo $this->render("/interface/commun/potions/potions.phtml"); ?>

	<?php if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="0 PA - Mettre en vente à l'échoppe"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendrepotion&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="0 PA - Transf&eacute;rer une potion ou un vernis"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transferpotion&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" <?php echo $disabled ?>/>

<?php else: ?>
	Vous n'avez aucune potion / vernis en r&eacute;serve
<?php endif; ?>
<br />