<? if (count($this->equipementsArriereBoutique) > 0): ?>

	<? $this->equipements = $this->equipementsArriereBoutique; ?>
	<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="0 PA - Mettre en vente à l'échoppe"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendreequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="0 PA - Transf&eacute;rer un &eacute;quipement"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transferequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucun &eacute;quipement en r&eacute;serve
<? endif; ?>