<?php Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
<?php if (count($this->potionsArriereBoutique) > 0): ?>
	<?php $this->potions = $this->potionsArriereBoutique; ?>
	<?php $this->idPotionsTable = $this->idPotionsArriereBoutiqueTable; ?>
	<?php echo $this->render("/interface/commun/potions/potions.phtml"); ?>
<?php else: ?>
	Vous n'avez aucune potion / vernis en r&eacute;serve
<?php endif; ?>
<br />