<div class="titre textalic textsizec">L'atelier</div>
L'atelier est le c&oelig;ur de l'&eacute;choppe. C'est ici que l'artisan exerce son art.<br /><br />

<? if ($this->estSurEchoppe === true && $this->user->activation == true): 
$disabled = "";
?>
Vous &ecirc;tes dans votre &eacute;choppe, vous pouvez travailler...<br />
<? else: 
$disabled = "disabled" ;
?>
<? if ($this->user->activation == true) : ?>
	Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous ne pouvez pas y travailler...<br />
<? else :?>
	Tour non activé à la connexion, vous ne pouvez pas y travailler...<br />
<? endif; ?>
<? endif; ?>
<? foreach($this->competences as $c) : ?>
	<? if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
    else:
      $attr = " disabled ";
    endif;?>
    <input type="button" class='button1' value="<?=$c["pa_texte"]?> PA - <?=$c["nom"]?><? if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?=$attr?>>
<? endforeach; ?>

<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
<? if ($this->user->pa_braldun >= 1) : 
  $attr = "onclick='_get_(\"/hotel/doaction?caction=ask_hotel_vendre&valeur_1=1\");'";
else:
  $attr = " disabled ";
endif;?>

<input type="button" class='button1' value="1 PA - Mettre en vente à l'Hôtel des Ventes" <?=$attr?> <?=$disabled?>>

<br /><br />

<? if ($this->afficheType == "equipements" || $this->afficheType == "potions") :?>
  <div class="titre textalic textsized">Mat&eacute;riels cr&eacute;&eacute;s</div>
  <? include("atelier_materiels.phtml") ?>
  <br /><br />
<? endif?>
  	
<? if ($this->afficheType == "equipements") :?>
	<div class="titre textalic textsized">&Eacute;quipements cr&eacute;&eacute;s</div>
	<? include("atelier_equipements.phtml") ?>
<? elseif ($this->afficheType == "potions") :?>
	<div class="titre textalic textsizec">Potions et vernis cr&eacute;&eacute;s</div>
	<? include("atelier_potions.phtml") ?>
<? elseif ($this->afficheType == "aliments") :?>
	<div class="titre textalic textsizec">Aliments cr&eacute;&eacute;s</div>
	<? include("atelier_aliments.phtml") ?>
<? endif; ?>
