<?php if (count($this->materielsArriereBoutique) > 0): ?>

	<?php $this->materiels = $this->materielsArriereBoutique; ?>
	<?php $this->idMaterielsTable = $this->idMaterielsArriereBoutiqueTable; ?>
	<?php echo $this->render("/interface/commun/materiels/materiels.phtml"); ?>
	
	<?php if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="0 PA - Mettre en vente à l'échoppe"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendremateriel&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="0 PA - Transf&eacute;rer un mat&eacute;riel"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transfermateriel&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" <?php echo $disabled ?>/>

<?php else: ?>
	Vous n'avez aucun mat&eacute;riel en r&eacute;serve
<?php endif; ?>