<? if (count($this->materielsArriereBoutique) > 0): ?>

	<? $this->materiels = $this->materielsArriereBoutique; ?>
	<?=$this->render("/interface/commun/materiels/materiels.phtml"); ?>
	
	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="0 PA - Mettre en vente à l'échoppe"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendremateriel&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="0 PA - Transf&eacute;rer un mat&eacute;riel"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transfermateriel&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucun mat&eacute;riel en r&eacute;serve
<? endif; ?>