
<? if ($this->nbEquipementsArriereBoutique > 0): ?>

	<? $this->equipements = $this->equipementsArriereBoutique; ?>
	<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="Mettre en vente un &eacute;quipement"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendreequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="Transf&eacute;rer un &eacute;quipement"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transfererequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucun &eacute;quipement en r&eacute;serve
<? endif; ?>