<? Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
<? if (count($this->potionsArriereBoutique) > 0): ?>

	<? $this->potions = $this->potionsArriereBoutique; ?>
	<?=$this->render("/interface/commun/potions/potions.phtml"); ?>

	<? if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="Mettre en vente une potion"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendrepotion&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="Transf&eacute;rer une potion"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transferpotion&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" <?=$disabled ?>/>

<? else: ?>
	Vous n'avez aucune potion en r&eacute;serve
<? endif; ?>
<br />