<?php if (count($this->alimentsArriereBoutique) > 0): ?>

	<?php $this->aliments = $this->alimentsArriereBoutique; ?>
	<?php $this->idAlimentsTable = $this->idAlimentsArriereBoutiqueTable; ?>
	<?php echo $this->render("/interface/commun/aliments/aliments.phtml"); ?>
	
	<?php if ($this->estSurEchoppe === true): 
  		$disabled = "";
	   else: 
  		$disabled = "disabled" ;
  	   endif;
  	?>
  	
	<input type="button" class='button1' value="0 PA - Mettre en vente un aliment"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_vendrealiment&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
	<input type="button" class='button1' value="0 PA - Transf&eacute;rer un aliment"
       		onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_transferaliment&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" <?php echo $disabled ?>/>

<?php else: ?>
	Vous n'avez aucun aliment en r&eacute;serve
<?php endif; ?>