 <ul class="titre textalic textsizec">L'atelier</ul>
L'atelier est le coeur de l'&eacute;choppe. C'est ici que l'artisan exerce sont art.<br /><br />

<? if ($this->estSurEchoppe === true && $this->user->activation == true): 
$disabled = "";
?>
Vous &ecirc;tes dans votre &eacute;choppe, vous pouvez travailler...<br />
<? else: 
$disabled = "disabled" ;
?>
<? if ($this->user->activation == true) : ?>
	Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous ne pouvez pas y travailler...<br />
<? else :?>
	Tour non activé à la connexion, vous ne pouvez pas y travailler...<br />
<? endif; ?>
<? endif; ?>
<? foreach($this->competences as $c) : ?>
	<? if ($this->user->pa_hobbit >=$c["pa_utilisation"]) : 
      $attr = "onClick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
    else:
      $attr = " disabled ";
    endif;?>
    <input type="button" class='button1' value="<?=$c["pa_texte"]?> PA - <?=$c["nom"]?><? if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?=$attr?>>
<? endforeach; ?>

<br /><br />

<? if ($this->afficheType == "equipements" || $this->afficheType == "potions") :?>
  <ul class="titre textalic textsized">Mat&eacute;riels cr&eacute;&eacute;s</ul>
  <? include("atelier_materiels.phtml") ?>
  <br /><br />
<? endif?>
  	
<? if ($this->afficheType == "equipements") :?>
	<ul class="titre textalic textsized">&Eacute;quipements cr&eacute;&eacute;s</ul>
	<? include("atelier_equipements.phtml") ?>
<? elseif ($this->afficheType == "potions") :?>
	<ul class="titre textalic textsizec">Potions et vernis cr&eacute;&eacute;s</ul>
	<? include("atelier_potions.phtml") ?>
<? elseif ($this->afficheType == "aliments") :?>
	<ul class="titre textalic textsizec">Aliments cr&eacute;&eacute;s</ul>
	<? include("atelier_aliments.phtml") ?>
<? endif; ?>
