<table width="40%" align="center">
	<tr>
		<td>
			<ul id="navigation" style="width:99%;text-align:left">
				<?php foreach($this->arBoutiqueCaisse as $k => $v) : ?>
					<?php if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueCaisse<?php echo $k?>">
				      	<h3 id="arboutiqueCaisse<?php echo $k?>-head" class="head" onclick="maccordion(this);">
							<?php echo htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueCaisse<?php echo $k?>-body" style="display:none">
							<li>
								<?php include("poche_caisse_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</td>
	</tr>
</table>
    
<?php if ($this->estSurEchoppe === true && $this->user->activation == true): 
  $disabled = "";
  ?>
  <?php else: 
  $disabled = "disabled" ;
  ?>
  <?php if ($this->user->activation == true) : ?>
  	Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
  <?php else :?>
  	Tour non activé à la connexion, vous n'avez pas acc&egrave;s aux actions...<br />
  <?php endif; ?>
  <?php endif; ?>
  
<input type="button" class='button1' value="0 PA - Retirer des &eacute;l&eacute;ments"
       onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirercaisse&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>') "  <?php echo $disabled ?> />
<br />
