<table width="40%" align="center">
	<tr>
		<td>
			<ul id="navigation" style="width:99%;text-align:left">
				<? foreach($this->arBoutiqueCaisse as $k => $v) : ?>
					<? if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueCaisse<?=$k?>">
				      	<h3 id="arboutiqueCaisse<?=$k?>-head" class="head" onClick="maccordion(this);" />
							<?=htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueCaisse<?=$k?>-body" style="display:none">
							<li>
								<? include("poche_caisse_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<? endif; ?>
				<? endforeach; ?>
			</ul>
		</td>
	</tr>
</table>
    
<? if ($this->estSurEchoppe === true && $this->user->activation == true): 
  $disabled = "";
  ?>
  <? else: 
  $disabled = "disabled" ;
  ?>
  <? if ($this->user->activation == true) : ?>
  	Vous n'&ecirc;tes pas dans votre &eacute;choppe, vous n'avez pas acc&egrave;s aux actions...<br />
  <? else :?>
  	Tour non activé à la connexion, vous n'avez pas acc&egrave;s aux actions...<br />
  <? endif; ?>
  <? endif; ?>
  
<input type="button" class='button1' value="0 PA - Retirer des &eacute;l&eacute;ments"
       onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirercaisse&valeur_1=<?=$this->echoppe["id_echoppe"] ?>') "  <?=$disabled ?> />
<br />
