<table width="40%" align="center">
	<tr>
		<td>
			<ul id="navigation" style="width:99%;text-align:left">
				<?php foreach($this->arBoutiqueCaisse as $k => $v) : ?>
					<?php if ($v["a_afficher"] == true) :?>
					<li id="arboutiqueCaisse<?php echo $k?>">
				      	<h3 id="arboutiqueCaisse<?php echo $k?>-head" class="head" onclick="maccordion(this);">
							<?php echo htmlspecialchars($v["nom"]) ?>
						</h3>
						<ul id="arboutiqueCaisse<?php echo $k?>-body" style="display:none">
							<li>
								<?php include("poche_caisse_".$k.".phtml") ?>
							</li>
						</ul>
					</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</td>
	</tr>
</table>
<br />
