<?php if (count($this->alimentsEtal) > 0) : ?>

	<?php $this->aliments = $this->alimentsEtal; ?>
	<?php $this->idAlimentsTable = $this->idAlimentsEtalTable; ?>
	<?php echo $this->render("/interface/commun/aliments/aliments.phtml"); ?>
	
		<input type="button" class='button1' value="0 PA - Retirer de la vente"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retireraliment&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
<?php else: ?>
	Vous n'avez aucun aliment en vente
<?php endif; ?>