<?php if (count($this->equipementsEtal) > 0) : ?>

	<?php $this->equipements = $this->equipementsEtal; ?>
	<?php $this->idEquipementsTable = $this->idEquipementsEtalTable; ?>
	<?php echo $this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
		<input type="button" class='button1' value="0 PA - Retirer de la vente"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirerequipement&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
<?php else: ?>
	Vous n'avez aucun &eacute;quipement en vente
<?php endif; ?>