<? if (count($this->alimentsEtal) > 0) : ?>

	<? $this->aliments = $this->alimentsEtal; ?>
	<? $this->idAlimentsTable = $this->idAlimentsEtalTable; ?>
	<?=$this->render("/interface/commun/aliments/aliments.phtml"); ?>
	
		<input type="button" class='button1' value="0 PA - Retirer de la vente"
       		  onClick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retireraliment&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
<? else: ?>
	Vous n'avez aucun aliment en vente
<? endif; ?>