<ul class="titre textalic textsizec">L'etal</ul>
L'&eacute;tal permet &agrave; l'artisan d'exposer ses ouvrages pour les mettre en vente.<br /><br />
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  	<? if ($this->afficheType == "equipements") :?>
  		<ul class="titre textalic textsized">Equipements en vente</ul>
  		<? include("etal_equipements.phtml") ?>
  	<? else: ?>
  		<ul class="titre textalic textsized">Potions en vente</ul>
  		<? include("etal_potions.phtml") ?>
  	<? endif; ?>
   </ul>
</div>