<?php Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
<?php if (count($this->potionsEtal) > 0) : ?>

	<?php $this->potions = $this->potionsEtal; ?>
	<?php $this->idPotionsTable = $this->idPotionsEtalTable ?>
	<?php echo $this->render("/interface/commun/potions/potions.phtml"); ?>
	
		<input type="button" class='button1' value="0 PA - Retirer de la vente"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirerpotion&valeur_1=<?php echo $this->echoppe["id_echoppe"] ?>')" />
<?php else: ?>
	Vous n'avez aucune potion / vernis en vente
<?php endif; ?>