<ul class="titre textalic textsizec">L'etal</ul>
L'&eacute;tal permet &agrave; l'artisan d'exposer ses ouvrages pour les mettre en vente.<br /><br />
 <div class="contenuc">
  <ul class="box_contenu1 textalic">
  
  	<? if ($this->afficheType == "equipements" || $this->afficheType == "potions") :?>
  		<ul class="titre textalic textsized">Mat&eacute;riels en vente</ul>
  		<? include("etal_materiels.phtml") ?>
  		<br /><br />
  	<? endif?>
  	<? if ($this->afficheType == "equipements") :?>
  		<ul class="titre textalic textsized">&Eacute;quipements en vente</ul>
  		<? include("etal_equipements.phtml") ?>
  	<? elseif ($this->afficheType == "potions") :?>
  		<ul class="titre textalic textsized">Potions / Vernis en vente</ul>
  		<? include("etal_potions.phtml") ?>
  	<? elseif ($this->afficheType == "aliments") :?>
  		<ul class="titre textalic textsized">Aliments en vente</ul>
  		<? include("etal_aliments.phtml") ?>
  	<? endif; ?>
   </ul>
</div>