<? if (count($this->equipementsEtal) > 0) : ?>

	<? $this->equipements = $this->equipementsEtal; ?>
	<? $this->idEquipementsTable = $this->idEquipementsEtalTable; ?>
	<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
	
		<input type="button" class='button1' value="0 PA - Retirer de la vente"
       		  onclick="Javascript:_get_('/echoppes/doaction?caction=ask_echoppes_retirerequipement&valeur_1=<?=$this->echoppe["id_echoppe"] ?>')" />
<? else: ?>
	Vous n'avez aucun &eacute;quipement en vente
<? endif; ?>