<? if ($this->ramasserOk === true) : ?>
	
	<? $tab = "var tabPossible = new Array();tabPossible[-1]=0;";
		foreach($this->autres as $k => $v) :
			$tab .= "tabPossible[$k]=".$v["nbPossible"].";";
		endforeach;
	?>
 	Choississez un &eacute;l&eacute;ment &agrave; ramasser &agrave; terre.<br />
	<select name="valeur_2" id="valeur_2" onChange="<?=$tab?>$('valeur_3').value = 0;  $('nbPossibleText').innerHTML = tabPossible[this.value]; $('nbPossible').value = tabPossible[this.value]; if (this.value > 0 && $('valeur_3').value > 0) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisis un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->autres as $k => $v) :?>
 			<option value="<?=$k?>" nbPossible="<?=$v["nbPossible"] ?>"><?=$v["nom"] ?> : <?=$v["nb"] ?></option>
	 	<? endforeach; ?>
	</select>

<br />
<br />

Vous pouvez en mettre  
<label id="nbPossibleText" name="nbPossible">0</label>
dans votre laban.

<input type="hidden" id="nbPossible" name="nbPossible" value="0">
<br>
Quantit&eacute; &agrave; ramasser : <br />
	<input type='text' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);"  
	onkeyup="if (this.value > 0 && $('valeur_2').value > 0 && Number(this.value) <= Number($('nbPossible').value)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">

<? endif; ?>

	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />