Il y a <?=$this->castars ?> castar<? if ($this->castars > 1): echo "s"; endif; ?> sur la case.

<? if ($this->ramasserOk === true && $this->poidsPlaceDisponible === true) : ?>
	<br />
	Il y a de la place pour <?=$this->nbCastarsPossible ?> castar<? if ($this->nbCastarsPossible > 1): echo "s"; endif; ?> dans votre laban. <br/>
	<br>
	Nombre de castars &agrave; ramasser : 
	<input type='textbox' maxlength='7' size='7' name='valeur_2' id='valeur_2' value='' onkeypress="chiffres(event);" onkeyup="if (this.value != '' && this.value > 0 && this.value <= <?=$this->nbCastarsPossible ?> && this.value <= <?=$this->castars ?>) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true}">
<? endif; ?>

	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />