<? if ($this->ramasserOk === true) : ?>

Il vous reste <?=$this->poidsRestant  ?> Kg de disponible dans votre laban.<br><br>
Choississez un &eacute;quipement.<br />
	<select name="valeur_2" id="valeur_2" onChange="if (this.value > 0) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisissez un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->equipements as $e) :?>
	 		<option value="<?=$e["id_equipement"]?>" <? if ($e["poids_ok"] == false): echo "disabled='disabled'"; endif;?>>n&deg;<?=$e["id_equipement"] ?> <?=$e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?>, niveau <?=$e["niveau"] ?>, poids <?=$e["poids"] ?> <? if ($e["poids_ok"] == false): echo " : Trop lourd !"; endif;?></option>
	 	<? endforeach; ?>
	</select>
<? endif; ?>

	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />