
Il vous reste <?=$this->poidsRestant ?> Kg de place disponible dans votre laban.<br>

Vous pouvez y mettre <?=$this->nbMunitionsPossible ?> munition<? if ($this->nbMunitionsPossible > 1): echo "s"; endif; ?>.
<br>
<br>
Si lors de l'action, il ne vous reste plus de place dans votre laban, les &eacute;l&eacute;ments en trop ne seront pas inclus :-) 

<br>
<br>

<? if (count($this->munitions) > 0) :?>
	Munitions :<br/>
	<? if ($this->nbMunitionsPossible < 1) : $disabled="disabled"; else: $disabled=""; endif;?>
	<select name="valeur_2" id="valeur_2" <?=$disabled ?> onChange="if (($('valeur_2').value > 0 && $('valeur_3').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisis un type de munition)</option>
	 	<? foreach($this->munitions as $m) :?>
	 		<option value="<?=$m["id_type_munition"]?>"><?=$m["type"]?> : <?=$m["quantite"]?></option>
	 	<? endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; : <br />
	<input type='text' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);" onkeyup="if (($('valeur_2').value > 0 && $('valeur_3').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true}">
	
<? else: ?>
	Aucune munition.
	<input type='hidden' name='valeur_2' id='valeur_2' value='-1' />
	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
<? endif; ?>
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />
<br>