
Il vous reste <?=$this->poidsRestant ?> Kg de place disponible dans votre laban.<br>

<? if ($this->nbPartiesPlantesBrutesPossible > 1) : $s="s"; else : $s=""; endif; ?>
Vous pouvez ramasser <?=$this->nbPartiesPlantesBrutesPossible ?> &eacute;l&eacute;ment<?=$s ?> de plante<?=$s ?> brute<?=$s ?>
 ou 
 <? if ($this->nbPartiesPlantesPrepareesPossible > 1) : $s="s"; else : $s=""; endif; ?>
<?=$this->nbPartiesPlantesPrepareesPossible ?> &eacute;l&eacute;ment<?=$s ?> de plante<?=$s ?> pr&eacute;par&eacute;e<?=$s ?><br>
<br>
Ceci dit, vous pouvez ramasser des &eacute;l&eacute;ments de plante brute et pr&eacute;par&eacute;e en même temps. <br>
Si lors du ramassage il ne vous reste plus de place dans votre laban, les &eacute;l&eacute;ments en trop ne seront pas ramass&eacute;s :-) 

<br>
<br>

<? if (count($this->partiePlantesBrutes) > 0) :?>
	&Eacute;lements de Plantes Brutes:<br/>
	
	<select name="valeur_2" id="valeur_2" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1 && $('valeur_5').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisis une plante brute)</option>
	 	<? foreach($this->partiePlantesBrutes as $k => $m) :?>
	 		<option value="<?=$k?>"><?=$m["quantite"]?> <?=$m["type"]?><? if ($m["quantite"] > 0): echo "s"; endif; ?> de <?=$m["type_plante"]?></option>
	 	<? endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; &agrave; ramasser : <br />
	<input type='text' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);" onkeyup="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1 && $('valeur_5').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	
<? else: ?>
	Aucun &eacute;l&eacute;ment de plante brute &agrave; ramasser &agrave; terre.
	<input type='hidden' name='valeur_2' id='valeur_2' value='-1' />
	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
<? endif; ?>

<br /><br />
<? if (count($this->partiePlantesPreparees) > 0) :?>
	&Eacute;lements de Plantes Pr&eacute;par&eacute;es : <br/>
	
	<select name="valeur_4" id="valeur_4" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1&& $('valeur_5').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisis une plante pr&eacute;par&eacute;e)</option>
	 	<? foreach($this->partiePlantesPreparees as $k => $m) :?>
	 		<option value="<?=$k?>"><?=$m["quantite"]?> <?=$m["type"]?><? if ($m["quantite"] > 0): echo "s"; endif; ?> de <?=$m["type_plante"]?></option>
	 	<? endforeach; ?>
	</select>
	<br />
	Quantit&eacute; &agrave; ramasser : <br />
	<input type='text' maxlength='7' size='7' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event);" onkeyup="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1&& $('valeur_5').value > 0)) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	
<? else: ?>
	Aucun &eacute;l&eacute;ment de plante pr&eacute;par&eacute;e &agrave; ramasser &agrave; terre.
	<input type='hidden' name='valeur_4' id='valeur_4' value='-1' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />
<? endif; ?>
<br />
