<? if (count($this->partiePlantesBrutes) > 0) :?>
	&Eacute;lements de Plantes Brutes:<br/>
	
	<select name="valeur_2" id="valeur_2" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1 && $('valeur_5').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	 	<option value="-1">(Choisis une plante brute)</option>
	 	<? foreach($this->partiePlantesBrutes as $k => $m) :?>
	 		<option value="<?=$k?>"><?=$m["quantite"]?> <?=$m["type"]?><? if ($m["quantite"] > 0): echo "s"; endif; ?> de <?=$m["type_plante"]?></option>
	 	<? endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; &agrave; d&eacute;poser : <br />
	<input type='textbox' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1 && $('valeur_5').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	
<? else: ?>
	Aucun &eacute;l&eacute;ment de plante brute &agrave; d&eacute;poser &agrave; terre.
	<input type='hidden' name='valeur_2' id='valeur_2' value='-1' />
	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
<? endif; ?>

<br /><br />
<? if (count($this->partiePlantesPreparees) > 0) :?>
	&Eacute;lements de Plantes Pr&eacute;par&eacute;es : <br/>
	
	<select name="valeur_4" id="valeur_4" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1&& $('valeur_5').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	 	<option value="-1">(Choisis une plante pr&eacute;par&eacute;e)</option>
	 	<? foreach($this->partiePlantesPreparees as $k => $m) :?>
	 		<option value="<?=$k?>"><?=$m["quantite"]?> <?=$m["type"]?><? if ($m["quantite"] > 0): echo "s"; endif; ?> de <?=$m["type_plante"]?></option>
	 	<? endforeach; ?>
	</select>
	<br />
	Quantit&eacute; &agrave; d&eacute;poser : <br />
	<input type='textbox' maxlength='7' size='7' name='valeur_5' id='valeur_5' value='0' onkeypress="chiffres(event);" onChange="if (($('valeur_2').value != -1 && $('valeur_3').value > 0) || ( $('valeur_4').value != -1&& $('valeur_5').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	
<? else: ?>
	Aucun &eacute;l&eacute;ment de plante pr&eacute;par&eacute;e &agrave; d&eacute;poser &agrave; terre.
	<input type='hidden' name='valeur_4' id='valeur_4' value='-1' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />
<? endif; ?>
<br />
