<? if ($this->ramasserOk === true) : ?>
	Choississez une rune.<br />
	<select name="valeur_2" id="valeur_2" onChange="if (this.value > 0) {$('bouton_ramasser').disabled=false} else {$('bouton_ramasser').disabled=true} ">
	 	<option value="-1">(Choisis une rune)</option>
	 	<? foreach($this->runes as $r) :?>
	 		<option value="<?=$r["id_rune"]?>">Rune n&deg;<?=$r["id_rune"] ?></option>
	 	<? endforeach; ?>
	</select>
<? endif; ?>

	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />