<div id="footer">
  <div style="height:10px">&nbsp;</div>
	 <div class="inner_footer">
	 	<span id='date_heure' class=''>&nbsp;</span>
	 	<a href="http://www.braldahim.com" class="aWhite">www.braldahim.com</a> |
	 	<? if (isset($this->user) && isset($this->user->email_braldun)) : ?> 
	 		<span id='nb_connectes' class=''>&nbsp;</span><br>
	 	<? endif;?>
		<a href="http://www.jeuxweb.org" class="aWhite">Braldahim est hébergé par l'Association JeuxWeb.org ASBL</a>
		 	
	 	<br/>
 		<a href="http://www.braldahim.com/abus/" class="aWhite">Signaler un abus</a> | 
 		<a href="http://jeu.braldahim.com/Feed/" class="feed">Flux RSS</a>
	 	<br/>
	 	
<!-- Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs  -->
<p style="text-align:center;font-size:9px;">
<a href="http://www.jeux-alternatifs.com/Braldahim-jeu301_hit-parade_1_1.html" target="_blank"><img src="http://www.jeux-alternatifs.com/im/bandeau/hitP_88x31_v2.gif" alt="" border="0" /></a>
<a href="http://www.gamersroom.com/vote.php?num=1615" title="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs"><img src="http://www.gamersroom.com/pub/bouton4.gif" alt="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs" style="border:none" /></a>
<a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>
</p>
  
	 </div>
	
	<? if ($this->config->tracker->enabled == "1") : ?>
	<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script type="text/javascript">
	var pageTracker = _gat._getTracker("<?=$this->config->tracker->id?>");
	pageTracker._initData();
	pageTracker._trackPageview();
	</script>
	<? endif; ?>
</div>