<div id="modalPage">
    <div class="modalBackground"></div>
    <div class="modalContainer">
 		<div id="box_chargement" class="box_chargement">
			 <div class="inner" style='background-color:#CC6666'>
			 Chargement en Cours<br /><img src="/public/images/wait.gif" alt=""/>
		 	</div>
		 </div>
    </div>
</div>

<div id="overDiv" style="position:absolute; visibility:hidden; z-index:100001;"></div>