<?=Bral_Helper_Box::haut(); ?>
<div id="menu">
	<ul>
		<li class="accueil"><a href="/">Accueil</a></li>
		<li class="jouer"><a href="http://beta.braldahim.com">Jouer</a></li>
		<li class="bourg"><a href="/bourg">Palmarès</a></li>
		<li class="forums"><a href="http://forums.braldahim.com">Forums</a></li>
		<li class="regles"><a href="http://wiki.braldahim.com">Règles</a></li>
		<li class="projet"><a href="/projet">Le Projet</a></li>
	</ul>
</div>
<?=Bral_Helper_Box::bas(); ?>