
<div id="menuhead">
	<nav id="nav-main">
	<ul class="menu">
		<li class="leaf first"><a title="" href="http://www.braldahim.com">Accueil</a>
		</li>
		<li class="leaf"><a title=""
			href="http://jeu.braldahim.com/auth/login">Jouer</a>
		</li>
		<li class="expanded"><a title="" href="http://www.braldahim.com/bourg">Le
				Bourg</a>
			<ul class="menu">
				<li class="leaf first"><a title=""
					href="http://www.braldahim.com/palmares">Palmarès</a>
				</li>
				<li class="leaf last"><a title=""
					href="http://www.braldahim.com/hotel">Hôtel des Ventes</a>
				</li>
			</ul>
		</li>

		<li class="leaf"><a title=""
			href="http://forum.braldahim.com">Forum</a>
		</li>
		<li class="leaf last"><a title=""
			href="http://regles.braldahim.com">Règles</a>
		</li>
	</ul>
	</nav>
</div>
