<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta http-equiv="Cache-Control" content="no-cache" />
		<meta http-equiv="Pragma" content="no-cache" />
		<title>Braldahim - Site</title>
		<meta name="description" content="Braldahim - Jeu Web - Hobbits" />
		<meta name="keywords" content="jeu web, hobbits, MMO, rôle" />
		<link href="/public/styles/braldahim-site-004.css" media="screen" rel="Stylesheet" type="text/css" />
		<link href="/public/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		
		<script type="text/javascript" src="/public/scripts/prototype_1602/prototype.js"></script> 
		<script type="text/javascript" src="/public/scripts/scriptaculous_181/scriptaculous.js" ></script>
		<script type="text/javascript" src="/public/scripts/braldahim/m_action-site-001.js"></script>
		<script type="text/javascript" src="/public/scripts/braldahim/m_display-site-001.js"></script>
		<script type="text/javascript" src="/public/scripts/braldahim/uddeimtools-site-001.js"></script>
		
		<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/dhtmlxcommon.js"></script>
		<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/dhtmlxgrid.js"></script>		
		<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/dhtmlxgridcell.js"></script>
		<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/ext/dhtmlxgrid_srnd.js"></script>
		<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/excells/dhtmlxgrid_excell_link.js"></script>
		
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib.js"></script>
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib_exclusive.js"></script>
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib_fade.js"></script>
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib_anchor.js"></script>
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib_positioncap.js"></script>
		<script type="text/javascript" src="/public/scripts/overlib_423/overlib_draggable.js"></script>

		<link rel="Stylesheet" type="text/css" href="/public/scripts/dhtmlxGrid-2.0.0/codebase/dhtmlxgrid.css">
		<link rel="Stylesheet" type="text/css" href="/public/scripts/dhtmlxGrid-2.0.0/codebase/dhtmlxgrid_skins.css">
	</head>

	<body>
	
	<?include("headerDiv.phtml")?>
	
	<div id="page">
		<div id="header">
			<h1><a href="/">Braldahim - Site</a></h1>
		</div>
		
		<?=$this->render("menu.phtml"); ?>
		
		<br>
		
		<?=Bral_Helper_Box::haut(); ?>
		<div class="inner">
			<div class="contenu">
				<?= $this->layout()->contenu ?>
			</div>
		</div>
		<?=Bral_Helper_Box::bas(); ?>

		<?=$this->render("footer.phtml"); ?>
	</div>
</body>
</html>