<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Pragma" content="no-cache" />
	<title>Braldahim - Site</title>
	<meta name="description" content="Braldahim - Jeu Web - Hobbits" />
	<meta name="keywords" content="jeu web, hobbits, MMO, rôle" />
	<link href="/public/styles/braldahim-site-011.css" media="screen" rel="Stylesheet" type="text/css" />
	<link href="/public/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	
	<script type="text/javascript" src="/public/scripts/protoaculous_183/protoaculous.1.8.3.min.js"></script> 
	<script  src="/public/scripts/dhtmlxGrid-2.0.0/codebase/allDhtmlx_001.js"></script>
	
	<link rel="alternate" type="application/rss+xml" title="Braldahim - Chronique" href="http://jeu.braldahim.com/Feed/" />
</head>
<body>
	<?include("headerDiv.phtml")?>
	<div id="header">
	<div id="frisetop">
		<h1><a href="/">Braldahim - Jeu</a></h1>
		</div>
	</div>
	<div id="page">
		<?=$this->render("menu.phtml"); ?>
		<div id="wrapper">
		<div class="contenu">
			<br>
			<?= $this->layout()->contenu ?>
			<br><br>
		</div>
		</div>
		<div id="frisebot" ></div>
		<?=$this->render("footer.phtml"); ?>
	</div>
	<script type="text/javascript" src="/public/scripts/braldahim/m_action-site-003.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/allbraldahim.js"></script>
</body>
</html>