<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('headerNonAuth.phtml'); ?>

<form action="/Perdu/" method="post">
<div class="box_perdu">
<div class="inner">
	<div class="titrea textalic titreasizea">Perte de mot de passe</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
		&nbsp;
		<div>
			<?php if ($this->emailGenerationOk) : ?>
				Pour g&eacute;n&eacute;rer un nouveau mot de passe, 
				suivez les indications que vous venez de recevoir
				 &agrave; l'adresse suivante : <br />
				<?php echo  $this->email_braldun ?>
			<?php else : ?>
				Erreur :  <?php echo $this->message?>
			<?php endif; ?>
				<br /><br />
				Courbettes distingu&eacute;es, <br /><br />
				Les ma&icirc;tres du jeu.<br /><br />
			 <input type="button" value="Accueil" class='button' onclick="javascript:document.location.href='/'"/>
		</div>
		</div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>