<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<div class="box_perdu">
<div class="box_titre1">Perte de mot de passe</div><br />

	<? if ($this->generationOk) : ?>
		Un nouveau mot de passe vient d'&ecirc;tre g&eacute;n&eacute;r&eacute;. 
		Vous venez de le recevoir par mail &agrave; l'adresse suivante : <br>
		<?= $this->email_hobbit ?>

	<? else : ?>
		<b>Une erreur est survenu lors de la g&eacute;n&eacute;ration de votre mot de passe.</b><br><br>
		
		Veuillez contacter le maitre du jeu à l'adresse suivante :
		<?= $this->emailMaitreJeu ?>. <br><br>
		N'oubliez pas d'indiquer : <br>
		=> votre nom et num&eacute;ro de hobbit<br>
		=> votre adresse de validation<br>
		=> le probl&egrave;me rencontr&eacute;.<br>
	<? endif ?>
		<br><br>
		Courbettes distingu&eacute;es, <br><br>
		Les ma&icirc;tres du jeu.<br><br>
	 <input type="button" value="Accueil" onClick="javascript:document.location.href='/'"/>
</div>

<?php echo $this->render('footer.phtml'); ?>