<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<div class="box_perdu">
<div class="box_titre1">Mot de Passe Perdu ?</div><br />

<form action="<?=$this->baseUrl ?>/perdu/" method="post">

<div><br>
	<?php if(!empty($this->messagesEmail)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php foreach($this->messagesEmail as $message) :?>
		<?=$this->escape($message);?><br>
	<?php endforeach; ?>
	</div>
	<?php endif; ?>
    <label for="title">Email</label><br>
    Un email vous parviendra à cette adresse<br>
    <input type="text" name="email_hobbit" value="<?=$this->escape($this->email_hobbit);?>" size="25" maxlength="100"/> 
    <?php if(!empty($this->messagesEmailConfirm)) :?> 
	<div class="message_erreur" id="message_erreur"> 
		<?=$this->escape($this->messagesEmailConfirm);?><br>
	</div>
	<?php endif; ?>
	<br><label for="title">Confirmation Email</label><br>
    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
</div>

<div id="formbutton">
<input type="submit" name="envoyer" value="Envoyer" /> <input type="button" name="add" value="Annuler" onClick="javascript:document.location.href='/'"/>
</div>
</form>
</div>

<?php echo $this->render('footer.phtml'); ?>

