<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Perdu ?</ul>

<form action="<?=$this->baseUrl ?>/perdu/" method="post">
<div class="box_perdu">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Mot de passe perdu ?</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
		&nbsp;
		<div>
			<?php if(!empty($this->messagesEmail)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesEmail as $message) :?>
				<?=$this->escape($message);?><br>
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    <label for="title">Email</label><br>
		    Un email vous parviendra à cette adresse<br>
		    <input type="text" name="email_hobbit" value="<?=$this->escape($this->email_hobbit);?>" size="25" maxlength="100"/> 
		    <?php if(!empty($this->messagesEmailConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesEmailConfirm);?><br>
			</div>
			<?php endif; ?>
			<br><label for="title">Confirmation Email</label><br>
		    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
		</div>

		<div id="formbutton">
		<input type="submit" class='button1' name="envoyer" value="Envoyer" /> 
		<input type="button" class='button1' name="add" value="Annuler" onClick="javascript:document.location.href='/'"/>
		</div>

	</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>

