Bonjour.

Votre nouveau mot de passe : <?php echo $this->password_braldun ?>

Nom du Braldûn : <?php echo $this->nom_braldun ?> 
Prenom du Braldûn : <?php echo $this->prenom_braldun ?> 
Numero du Braldûn :<?php echo $this->id_braldun ?> 

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?php echo $this->adresseSupport ?> 

Bon jeu ! 

--
Boule Hondevice - Maitre du jeu