Bonjour.<br /><br />
Vous avez perdu votre mot de passe sur Braldahim ?<br /><br />
Nom du Braldûn : <?=$this->nom_braldun ?><br />
Prenom du Braldûn : <?=$this->prenom_braldun ?><br />
Numero du Braldûn :<?=$this->id_braldun ?><br /><br />
Pour obtenir un nouveau mot de passe, allez ici : <br />
<a href="<?=$this->urlGeneration ?>"><?=$this->urlGeneration ?></a><br /><br />

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Boule Hondevice - Maitre du jeu