Bonjour.<br /><br />
Votre nouveau mot de passe : <b><?php echo $this->password_braldun ?></b><br /><br />
Nom du Braldûn : <?php echo $this->nom_braldun ?><br />
Prenom du Braldûn : <?php echo $this->prenom_braldun ?><br />
Numero du Braldûn :<?php echo $this->id_braldun ?><br /><br />

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?php echo $this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Boule Hondevice - Maitre du jeu