Bonjour.

Vous avez perdu votre mot de passe sur Braldahim ? 

Nom du braldun : <?=$this->nom_braldun ?> 
Prenom du braldun : <?=$this->prenom_braldun ?> 
Numero du Braldun :<?=$this->id_braldun ?> 

Pour obtenir un nouveau mot de passe, allez ici :  
<?=$this->urlGeneration ?> 

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?> 

Bon jeu ! 

--
Boule Hondevice - Maitre du jeu