Bonjour.<br><br>
Votre nouveau mot de passe : <b><?=$this->password_hobbit ?></b><br><br>
Nom du hobbit : <?=$this->nom_hobbit ?><br>
Prenom du hobbit : <?=$this->prenom_hobbit ?><br>
Numero du Hobbit :<?=$this->id_hobbit ?><br><br>

Si vous rencontrer un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br><br>

Bon jeu ! <br><br>

--<br>
Boule Hondevice - Maitre du jeu