Bonjour.<br><br>
Vous avez perdu votre mot de passe sur Braldahim ?<br><br>
Nom du hobbit : <?=$this->nom_hobbit ?><br>
Numero du Hobbit :<?=$this->id_hobbit ?><br><br>
Pour obtenir un nouveau mot de passe, allez ici : <br>
<a href="<?=$this->urlGeneration ?>"><?=$this->urlGeneration ?></a><br><br>

Si vous rencontrer un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br><br>

Bon jeu ! <br><br>

--<br>
Boule Hondevice - Maitre du jeu