Bonjour.<br /><br />
Votre nouveau mot de passe : <b><?=$this->password_braldun ?></b><br /><br />
Nom du braldun : <?=$this->nom_braldun ?><br />
Prenom du braldun : <?=$this->prenom_braldun ?><br />
Numero du Braldun :<?=$this->id_braldun ?><br /><br />

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Boule Hondevice - Maitre du jeu