Bonjour.

Vous avez perdu votre mot de passe sur Braldahim ? 

Nom du hobbit : <?=$this->nom_hobbit ?> 
Prenom du hobbit : <?=$this->prenom_hobbit ?> 
Numero du Hobbit :<?=$this->id_hobbit ?> 

Pour obtenir un nouveau mot de passe, allez ici :  
<?=$this->urlGeneration ?> 

Si vous rencontrez un soucis, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?> 

Bon jeu ! 

--
Boule Hondevice - Maitre du jeu