<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->idsLots ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	<b>Lot<?php if (count($this->tabIdsLots) > 1): echo 's'; endif;?> <?php echo $this->idsLots?></b> <br />
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	<?php if ($this->lotCharrette == null && $this->detailsLots["place_dispo"] === false) : ?>
		<br /><br />
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br />
	<?php endif; ?>
	
	<br />
		
		<?php if ($this->lotCharrette != null && $this->detailsLots["charrette_possible"] == false) : ?>
				<?php echo $this->detailsLots["charrette_detail"]?><br />
		<?php elseif ($this->lotCharrette != null) : ?>
			<br />Vous êtes sur le point d'acheter une charrette.<br />
			<input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
			
		<?php else : ?>
	
			<?php foreach($this->destinationTransfert as $d) :?>
				<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>" value="<?php if ($d["possible"] == true): echo 1; endif;?>"/>
				<input type="hidden" id="possible_<?php echo $d["id_destination"] ?>_force" value="<?php if ($d["possible_force"] == true): echo 1; endif;?>"/>
			<?php endforeach; ?>
			
			Destination du lot : <br />
			<select name="valeur_3" id="valeur_3" onchange="<?php if ($js!= ""): echo $js; endif;?>">
		 		<option value="-1">(Choisissez une destination)</option>
				<?php foreach($this->destinationTransfert as $d) :?>
					<option value="<?php echo $d["id_destination"] ?>" <?php if ($d["possible"] == false && $d["possible_force"] == false): echo "disabled"; endif;?>><?php echo $d["texte"] ?> <?php if ($d["possible"] == false && $d["possible_force"] == false): echo " : pas assez de place"; endif;?></option>
				<?php endforeach; ?>
			</select>
		
		<?php endif; ?>

		<?php if ($this->lotCharrette == null || $this->detailsLots["charrette_possible"] == true) : ?>		
			<br /><br />
			<?php if ($this->lotCharrette == null) : ?>
			<div class="titre textalic textsizec">Poids : <?php echo $this->detailsLots["poids_total"]?> </div>
			<?php endif;?>
			
			<div class="titre textalic textsizec">Prix en castars : <?php echo $this->detailsLots["prix_total"]?> </div>
			<br />
			
			<?php if ($this->assezDePa !== true): ?>
				Vous n'avez pas assez de PA
				
			<?php elseif ($this->detailsLots["place_dispo"] === true) : ?>
			
				<input type='button' class='button1' id='bouton_acheterelot<?php echo $k?>' value='Acheter !' 
				onclick='this.disabled=true; _get_("/lot/doaction?caction=do_lot_acheterlot&idsLots=<?php echo $this->idsLots ?>&amp;idEchoppe=<?php echo $this->idEchoppe?>");' 
				<?php if ($this->lotCharrette == null) : echo "disabled"; endif;?>>
				
			<?php elseif ($this->detailsLots["place_dispo"] !== true): ?>
				Vous n'avez pas assez de place disponible.
			<?php else: ?>
				Vous n'avez pas assez de castars dans votre laban
			<?php endif; ?>
		<?php endif;?>
		<br />
		
 </div>

</form>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>