<ul class="box_contenu textalic">

	<table style="width:100%" cellspacing=0>
	<tr>
		<td style="width:300px" valign="top">
			<ul class="titre textalic textsizec">
			L'office des Palmarès
			</ul>
			
			<input type="button" class='button1' value="Rentrer dans l'office" onClick='document.location.href="/palmares"'/>
			
			<br><br>
			<ul class="titre textalic textsizec">
			La brasserie des sports
			</ul>
			
			<input type="button" class='button1' value="Rentrer dans la brasserie" onClick='document.location.href="/brasserie"'/>
			
			<br><br>
			<ul class="titre textalic textsizec">
			La chambre des m&eacute;tiers
			</ul>
			
			<input type="button" class='button1' value="Rentrer dans la chambre" onClick='document.location.href="/chambre"'/>
			<br><br>
		</td>
		<td style="width:300px;" valign="top" colspan='2'>
			<ul class="titre textalic textsizec">
			Les Marchés
			</ul>
			
			<table style="width:100%" cellspacing=0>
			<tr>
				<td style="width:300px;" valign="top">
				<input type="button" class='button1' value="Marché aux équipements " onClick='document.location.href="/marcheequipement"'/>
				<br><br>
				<input type="button" class='button1' value="Marché aux potions et vernis " onClick='document.location.href="/marchepotion"'/>
				<br><br>
				<input type="button" class='button1' value="Marché aux matériels " onClick='document.location.href="/marchemateriel"'/>
				<br><br>
			</td>
			<td style="width:300px;" valign="top">
				<input type="button" class='button1' value="Hôtel des Ventes" onClick='document.location.href="/hotel"'/>
				<br><br>
				<input type="button" class='button1' value="Marché aux aliments " onClick='document.location.href="/marchealiment"'/>
				<br><br>
				<input type="button" class='button1' value="Marché au tabac " onClick='document.location.href="/marchetabac"'/>
				<br><br>
			</td>
			</tr>
			</table>
		</td>
	</tr>
	</table>
</ul>
<br>
<ul class="box_contenu textalic">
<i>Pour relater un fait, choisissez la compétence "<a href="http://wiki.braldahim.com/wiki/Relater_un_fait" class="aWhite">Relater un fait</a>" dans le jeu.</i><br>
			<label  class="aWhite" style="text-decoration:underline" onClick="javascript:$('abus_div').style.display='block';">Merci de signaler tout abus constaté</label>.<br>
			<div id='abus_div' style="display:none">
			<?=$this->render('abus/formulaire.phtml')?>
			</div>
			<br><br>
	<table style="width:100%">
	<tr>
		<td style="width:300px" valign="top">
			<ul class="titre textalic textsizec">
			Ils relatent...
			</ul><br>
			
			Filtre par année: <select id="annee" name="annee" onChange="document.location.href = '/bourg/?anneeselect='+this.value+'&typeselect='+$('type').value+'&uid='+(new Date()).valueOf()">
			<? foreach($this->annees as $a): ?>
				<option value="<?=$a?>" <?if ($this->anneeSelect == $a): echo "selected" ; endif;?>><?=$a?></option>
			<? endforeach;?>
			</select>
			
			Filtre par type: <select id="type" name="type" onChange="document.location.href = '/bourg/?anneeselect='+$('annee').value+'&typeselect='+this.value+'&uid='+(new Date()).valueOf()">
			<? foreach($this->types as $t): ?>
				<option value="<?=$t["id_type"]?>" <?if ($this->typeSelect == $t["id_type"]): echo "selected" ; endif;?>><?=$t["nom_type"]?></option>
			<? endforeach;?>
			</select>
			<br><br>
			
		</td>
		
		<td style="width:320px" valign="top">
			<ul class="titre textalic textsizec">
			Ils recherchent...
			</ul><br>
	 		Seules les annonces de 10 jours ou moins sont affichées.<br>
			<br>
		</td>
	</tr>
	<tr>
		<td style="width:320px" valign="top">
		<? include('relate.phtml')?>
		</td>
		
		<td style="width:320px" valign="top">
		<? include('recherche.phtml')?>
		</td>
	</tr>
	</table>
</ul>
