<ul class="box_contenu1 textalic">

	<table style="width:100%">
	<tr>
		<td style="width:300px" valign="top">
			<ul class="titre textalic textsizec">
			L'office des Palmarès
			</ul><br>
			
			<ul style="font: 12px arial, verdana, sans-serif;">
			
			</ul>
			
			<input type="button" class='button1' value="Rentrer dans l'office" onClick='document.location.href="/palmares"'/>
		</td>
		<td style="width:300px; border-left: 1px solid #791E1E;" valign="top">
			<ul class="titre textalic textsizec">
			Le Marché
			</ul><br>
			
			Le marché est actuellement fermé.
		</td>
	</tr>
	</table>
	
</ul>