<div id="mygrid_recherche_container" style="width:380px;height:500px;align:center"></div> 
<script type="text/javascript">
	mygridRecherche = new dhtmlXGridObject('mygrid_recherche_container');
	mygridRecherche.setImagePath("<?=$this->config->static->url?>/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygridRecherche.setHeader("Date,À la recherche de...");
	mygridRecherche.setInitWidths("70,*");
	mygridRecherche.setColAlign("left,left");
	mygridRecherche.setColTypes("ro,txt");
	mygridRecherche.setSkin("braldahim");
	mygridRecherche.setColSorting("server");
	mygridRecherche.attachEvent("onBeforeSorting",sortGridOnServerRecherche);
	mygridRecherche.enableSmartRendering(true,100);
	mygridRecherche.init();
	mygridRecherche.loadXML(getGridQStringRecherche());
	mygridRecherche.setSortImgState(true,0,"des");
</script>