<div id="mygrid_relate_container" style="width:380px;height:500px;align:center"></div> 
<script type="text/javascript">
	mygrid = new dhtmlXGridObject('mygrid_relate_container');
	mygrid.setImagePath("<?php echo $this->config->url->static?>/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygrid.setHeader("Date,Histoire...");
	mygrid.setInitWidths("70,*");
	mygrid.setColAlign("left,left");
	mygrid.setColTypes("ro,txt");
	mygrid.setSkin("braldahim");
	mygrid.setColSorting("server");
	mygrid.attachEvent("onBeforeSorting", sortGridOnServerRelate);
	mygrid.enableSmartRendering(true,100);
	mygrid.init();
	mygrid.loadXML(getGridQStringRelate());
	mygrid.setSortImgState(true,0,"des");
</script>