<div class='comp_titre'>Abattre un arbre</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->abattreArbreOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez abattre un arbre : <br>
	 <? else:?>
		 	Vous ne pouvez pas abattre un arbre en ville.<br>
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->abattreArbreOk === true) : ?>
<input type='button' class='button1' id='bouton_abattrearbre' value='Abattre un arbre !' onClick='_get_("/competences/DoAction?caction=do_competence_abattrearbre");'>
<? endif ?>
<? include("commun_fermer.phtml") ?>