 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <?php if ($this->abattreArbreEnvironnementOk !== true) : ?>
	 	Vous ne pouvez abattre un arbre que dans un bosquet
	 <?php else: ?>
		 Pour <?php echo $this->nb_pa ?> PA, vous pouvez abattre un arbre dans ce bosquet.
		 <br /><br />
		 <?php if ($this->charettePleine == true && $this->possedeCharrette == true) : ?>
	 		Votre charette ne peut plus contenir de rondin.<br />
	 	 <?php endif;?>
	 	 <?php if ($this->labanPlein == true) : ?>
	 		Votre laban ne peut plus contenir de rondin.<br />
	 	 <?php endif;?>
	 	 <br />
	 	 Choisissez la destination :
		 <br />
		 <?$select="";?>
		 <select name="valeur_1" id="valeur_1">
			<?php if ($this->possedeCharrette == true && $this->charettePleine == false ) : ?>
				<?php $select = " selected='selected' ";?>
				<option value="1" <?php echo $select;?>>Votre charrette (<?php echo $this->nbPossibleDansCharretteMax?> rondin(s) maximum)</option>
			<?php endif; ?>
			<?php if ( $this->labanPlein == false ) : ?>
				<?php if ($select == "") $select = " selected='selected' "; else $select="";  ?>
					<option value="2" <?php echo $select;?>>Votre laban (<?php echo $this->nbPossibleDansLabanMax?> rondin(s) maximum)</option>
			<?php endif; ?>
			<option value="3">Le sol</option>
		 </select>
	 <?php endif; ?>
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->abattreArbreEnvironnementOk === true ) : ?>
<input type='button' class='button' id='bouton_abattrearbre' value='Abattre un arbre !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_abattrearbre");'>
<?php endif ?>
