 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->abattreArbreEnvironnementOk !== true) : ?>
	 	Vous pouvez abattre un arbre qu'en for&ecirc;t
	 <? elseif ($this->abattreArbreVilleOk !== true) : ?>
		Vous ne pouvez pas abattre un arbre en ville
	 <? elseif ($this->abattreArbreLieuOk !== true) : ?>
	 	Vous ne pouvez pas abattre un arbre sur un lieu
	 <? elseif ($this->possedeCharrette !== true) :?>
		Vous ne pouvez pas abattre un arbre sans charrette
	 <? else: ?>
		 Pour <?=$this->nb_pa ?> PA, vous pouvez abattre un arbre
	 <? endif; ?>
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->abattreArbreEnvironnementOk === true && $this->abattreArbreLieuOk === true && $this->abattreArbreVilleOk === true && $this->possedeCharrette === true) : ?>
<input type='button' class='button1' id='bouton_abattrearbre' value='Abattre un arbre !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_abattrearbre");'>
<? endif ?>
