 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <? if ($this->assaisonnerNbViandeOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez assaisonner de la viande : <br />
	 	transformer jusqu'&agrave; <?=$this->nbViande ?> unit&eacute;<? if ($this->nbViande > 1) : echo "s"; endif; ?> de 
	 	viande en unit&eacute;(s) de viande pr&eacute;par&eacute;e<br /><br />
	 	
	 	Nombre d'unit&eacute;(s) &agrave; pr&eacute;parer<br />
		 <select name="valeur_1" id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_assaisonner').disabled=true } else {$('bouton_assaisonner').disabled=false }">
		 	<option value="-1">(Choisissez le nombre)</option>
		 	<? for ($i = 1; $i<= $this->nbViande; $i++) : ?>
		 		<option value="<?=$i?>"><?=$i?> unit&eacute;<? if ($i > 1): echo "s"; endif;?> de viande</option>
		 	<? endfor; ?>
		 </select>
	 <? else: ?>
	 Vous n'avez pas assez d'unit&eacute; de viande fra&icirc;che pour assaisonner...
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->assaisonnerNbViandeOk === true) : ?>
<input type='button' class='button1' id='bouton_assaisonner' value='Assaisonner !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_assaisonner");' disabled>
<? endif ?>