 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->assaisonnerNbViandeOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez assaisonner de la viande : <br />
	 	transformer <?=$this->nbViande ?> unit&eacute;<? if ($this->nbViande > 1) : echo "s"; endif; ?> de 
	 	viande en unit&eacute;(s) de viande pr&eacute;par&eacute;e<br /><br />
	 <? else: ?>
	 Vous n'avez pas assez d'unit&eacute; de viande fra&icirc;che pour assaissonner...
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->assaisonnerNbViandeOk === true) : ?>
<input type='button' class='button1' id='bouton_assaisonner' value='Assaisonner !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_assaisonner");'>
<? endif ?>
