<div class='comp_titre'>Attaquer</div>

 <div class='comp_contenu'>
	 <div id='attaquer_text' style="display:block"  onClick="javascript:switch2div('attaquer_text','attaquer_copie');">
	 <? include("commun_text_resultat.phtml") ?>
		 Vous avez attaqu&eacute; <?=htmlentities($this->cible["nom_cible"])?> (<?=$this->cible["id_cible"]?>) :<br><br>
		 Jet d'attaque : <?=$this->jetAttaquant?><br>
		 Jet de r&eacute;sistance de la cible : <?=$this->jetCible?><br>
		 
	 	<? if ($this->attaqueReussie === true) : ?>
	 		<? if ($this->jetDegat>1):$s='s'; else:$s=''; endif;?>
	 		Vous avez inflig&eacute; <?=$this->jetDegat?> point<?=$s?> de d&eacute;gat.
	 		<br><br>
	 		
	 		<? if ($this->mort): ?>
	 			Vous avez tu&eacute; <?=htmlentities($this->cible["nom_cible"])?> (<?=$this->cible["id_cible"]?>) N<?=$this->cible["niveau_cible"] ?><br><br>
	 		<? endif; ?>
	 		Vous avez gagn&eacute; <?=$this->nb_px?> PX<br><br>
	 	<? else: ?>
	 		Votre attaque a &eacute;t&eacute; esquiv&eacute;e<br>
	 		<? if ($this->fragilisee === true) : ?>
	 		 La cible est fragilis&eacute;e pour les prochaines attaques
	 		<? endif; ?>
	 	<? endif; ?>
	 </div>
	 
	 <div id='attaquer_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		 echo "Vous avez attaqu&eacute; ".htmlentities($this->cible["nom_cible"])." (".$this->cible["id_cible"].") N".$this->cible["niveau_cible"]." :";
		 echo "
";
		 echo "Jet d'attaque : ".$this->jetAttaquant;
		 echo "
";
		 echo "Jet de r&eacute;sistance de la cible : ".$this->jetCible;
		 echo "
";
		 
	 	 if ($this->attaqueReussie === true) {
	 		if ($this->jetDegat>1):$s='s'; else:$s=''; endif;
	 		echo "Vous avez inflig&eacute; ".$this->jetDegat." point".$s." de d&eacute;gat.";
	 		echo "
";
	 		
	 		if ($this->mort) {
	 			echo "Vous avez tu&eacute; ".htmlentities($this->cible["nom_cible"])." (". $this->cible["id_cible"].") N".$this->cible["niveau_cible"]." :";
	 			echo "
";
			}
	 		echo "Vous avez gagn&eacute; ".$this->nb_px." PX";
	 	  } else {
	 	  	echo "Votre attaque a &eacute;t&eacute; esquiv&eacute;e";
	 	  	echo "
";
	 	  	 if ($this->fragilisee === true) {
	 		 	echo "La cible est fragilis&eacute;e pour les prochaines attaques";
	 	  	 }
	 	  }
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('attaquer_text','attaquer_copie');">
<? include("commun_fermer.phtml") ?>