<? include("commun_text_resultat.phtml") ?>

Vous avez attaqu&eacute; une palissade !<br />
<? if ($this->degats > 1) : $s='s'; else : $s=''; endif;?>
 Vous avez inflig&eacute; <?=$this->degats?> point<?=$s?> de d&eacute;g&acirc;ts.<br />

<? if ($this->degatsInfliges != $this->degats) : ?>
	<? if ($this->degatsInfliges > 1) : $s='s'; else : $s=''; endif;?>
	Son armure la prot&egrave;ge, elle ne perd que <?=$this->degatsInfliges?> point<?=$s?> de d&eacute;g&acirc;ts.<br />
<? endif; ?>

<? if ($this->detruire) :?>
	La palissade est d&eacute;truite.
<? else: ?>
	La palissade est touch&eacute;e &agrave; <?=100 - ($this->palissade["pv_restant_palissade"]*100 / $this->palissade["pv_max_palissade"]) ?> %
<? endif; ?>
<br /><br />
<? if ($this->nb_px > 0) :?>
	Vous avez gagn&eacute; <?=$this->nb_px?> PX.
<? else : ?>
	Vous n'avez pas gagn&eacute; de PX.
<? endif; ?>
<br /><br />