<div class='comp_titre'>Attaquer</div>

 <div class='comp_contenu'>
	 <div id='attaquer_text' style="display:block"  onClick="javascript:switch2div('attaquer_text','attaquer_copie');">
	 <? include("commun_text_resultat.phtml") ?>
		 Vous avez attaqu&eacute; <?=htmlentities($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) :<br><br>
		 Jet d'attaque : <?=$this->retourAttaque["jetAttaquant"]?><br>
		 Jet de r&eacute;sistance de la cible : <?=$this->retourAttaque["jetCible"]?><br>
		 
	 	<? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
	 		<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
	 		Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;gat
	 		<? if ($this->retourAttaque["critique"]  == true): ?>
	 		en attaque critique
	 		<? endif; ?>
	 		<br><br>
	 		
	 		<? if ($this->retourAttaque["mort"] === true): ?>
	 			Vous avez tu&eacute; <?=htmlentities($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) N<?=$this->retourAttaque["cible"]["niveau_cible"] ?><br><br>
	 		<? endif; ?>
	 		Vous avez gagn&eacute; <?=$this->nb_px?> PX<br><br>
	 	<? else: ?>
	 		Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
	 		<? if ($this->retourAttaque["fragilisee"] === true) : ?>
	 		<br> La cible est fragilis&eacute;e pour les prochaines attaques<br>
	 		<? else: ?>
	 		parfaitement.
	 		<? endif; ?>
	 	<? endif; ?>
	 	<? include("commun_text_effets.phtml") ?>
	 </div>
	 
	 <div id='attaquer_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		 echo "Vous avez attaqu&eacute; ".htmlentities($this->retourAttaque["cible"]["nom_cible"])." (".$this->retourAttaque["cible"]["id_cible"].") N".$this->retourAttaque["cible"]["niveau_cible"]." :";
		 echo "
";
		 echo "Jet d'attaque : ".$this->retourAttaque["jetAttaquant"];
		 echo "
";
		 echo "Jet de r&eacute;sistance de la cible : ".$this->retourAttaque["jetCible"];
		 echo "
";
		 
	 	 if ($this->retourAttaque["attaqueReussie"] === true) {
	 		if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;
	 		echo "Vous avez inflig&eacute; ".$this->retourAttaque["jetDegat"]." point".$s." de d&eacute;gat ";
	 		if ($this->retourAttaque["critique"]  == true) {
	 			echo "en attaque critique";
	 		}
	 		echo "
";
	 		
	 		if ($this->retourAttaque["mort"] === true) {
	 			echo "Vous avez tu&eacute; ".htmlentities($this->retourAttaque["cible"]["nom_cible"])." (". $this->retourAttaque["cible"]["id_cible"].") N".$this->retourAttaque["cible"]["niveau_cible"]." :";
	 			echo "
";
			}
	 		echo "Vous avez gagn&eacute; ".$this->nb_px." PX";
	 	  } else {
	 	  	echo "Votre attaque a &eacute;t&eacute; esquiv&eacute;e";
	 	  	
	 	  	 if ($this->retourAttaque["fragilisee"] === true) {
	 	  	 	echo "
";
	 		 	echo "La cible est fragilis&eacute;e pour les prochaines attaques";
	 		 	echo "
";
	 	  	 } else {
	 	  	 	echo " parfaitement";
;	 	  	 }
	 	  }
	 	  include("commun_copie_effets.phtml");
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('attaquer_text','attaquer_copie');">
<? include("commun_fermer.phtml") ?>