 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	 <? if ($this->armeTirPortee == true) :?>
		Vous ne pouvez pas utiliser cette comp&eacute;tence avec une arme de tir !<br /><br />
	<? else: ?>
		<? include('commun_attaque_formulaire.phtml');?>
			
	 	<? if ($this->nBralduns == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; attaquer ici...<br />
	 	<? else: ?>
	 		Pour <?=$this->nb_pa?> PA, vous pouvez attaquer :<br /><br />
	 		
			<? if ($this->nMonstres > 0): ?>
			Un monstre<br />
				<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_attaquer').disabled=true } else {$('valeur_2').value=-1; $('bouton_attaquer').disabled=false }">
				<option value='-1'>(Choisissez un monstre)</option>
				<? foreach ($this->tabMonstres as $m) : ?>
				<option value="<?=$m["id_monstre"]?>"><? if ($m["est_gibier"]): ?>Gibier : <? endif;?><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>)</option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
			<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<? endif; ?>
			
			
	 		<? if ($this->nBralduns > 0): ?>
	 		 Un Braldûn<br />
	 			<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_attaquer').disabled=true } else {$('valeur_1').value=-1; $('bouton_attaquer').disabled=false }">
				<option value='-1'>(Choisissez un Braldûn)</option>
				<? foreach ($this->tabBralduns as $h) : ?>
				<option value="<?=$h["id_braldun"]?>"><?=$h["prenom_braldun"]?> <?=$h["nom_braldun"]?> (<?=$h["id_braldun"]?>)</option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
			<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<? endif;?>
		<? endif; ?>
	<? endif;?>
 </div>

<br />
<?php if ($this->assezDePa == true) : ?>
<input type='button' class='button1' value='Attaquer !' id='bouton_attaquer' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_attaquer");' disabled>
<? endif ?>
