<? include("commun_text_resultat.phtml") ?>
 Vous avez attaqu&eacute; <?=htmlentities($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) :<br /><br />
 Jet d'attaque : <?=$this->retourAttaque["jetAttaquant"]?><br />
 Jet de r&eacute;sistance de la cible : <?=$this->retourAttaque["jetCible"]?><br />
 
 <? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
 	<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
 	Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;g&acirc;ts
 	<? if ($this->retourAttaque["critique"]  == true): ?>
 	en attaque critique
 	<? endif; ?>
 	<br /><br />
 	
 	<? if ($this->retourAttaque["mort"] === true): ?>
 		Vous avez tu&eacute; <?=htmlentities($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) N<?=$this->retourAttaque["cible"]["niveau_cible"] ?><br /><br />
 	<? endif; ?>
 	Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
 <? else: ?>
 	Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
 	<? if ($this->retourAttaque["fragilisee"] === true) : ?>
 	<br /> La cible est fragilis&eacute;e pour les prochaines attaques<br />
 	<? else: ?>
 	parfaitement.
 	<? endif; ?>
 <? endif; ?>
<? include("commun_text_effets.phtml") ?>