<?php include("commun_text_resultat.phtml") ?>

Vous avez attaqu&eacute; une palissade en x:<?php echo $this->palissade["x_palissade"]?> et y:<?php echo $this->palissade["y_palissade"]?> !<br />
<?php if ($this->degats > 1) : $s='s'; else : $s=''; endif;?>
 Vous avez inflig&eacute; <?php echo $this->degats?> point<?php echo $s?> de d&eacute;g&acirc;ts.<br />

<?php if ($this->degatsInfliges != $this->degats) : ?>
	<?php if ($this->degatsInfliges > 1) : $s='s'; else : $s=''; endif;?>
	Son armure la prot&egrave;ge, elle ne perd que <?php echo $this->degatsInfliges?> point<?php echo $s?> de d&eacute;g&acirc;ts.<br />
<?php endif; ?>

<?php if ($this->detruire) :?>
	La palissade est d&eacute;truite.
<?php else: ?>
	La palissade est touch&eacute;e &agrave; <?php echo floor(100 - ($this->palissade["pv_restant_palissade"]*100 / $this->palissade["pv_max_palissade"])) ?> %
<?php endif; ?>
<br /><br />

<?php if ($this->apparitionMonstre): ?>
<b>Oh oh... quelque chose est apparu.</b>
<br /><br />
<?php endif;?>

<?php if ($this->nb_px > 0) :?>
	Vous avez gagn&eacute; <?php echo $this->nb_px?> PX.
<?php else : ?>
	Vous n'avez pas gagn&eacute; de PX.
<?php endif; ?>
<br /><br />