 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
<? if ($this->armeTirPortee == true) :?>
	Vous ne pouvez pas utiliser cette comp&eacute;tence avec une arme de tir !<br><br>
<? elseif ($this->user->est_intangible_hobbit == "oui") : ?>
	Vous ne pouvez pas attaquer une palissade en étant intangible. <br><br>
<? else: ?>
	<?php if ($this->tableau == null || count($this->tableau) == 0) : ?>
	 Vous ne pouvez attaquer une palissade qu'aux alentours de vous.
	<?php else : ?>
	  <table align='center'>
	   <tr>
	     <th>Position [x;y]</th>
	   </tr>
	   <tr>
	     <td>
	     <table class='comp_marcher_position'>
	     	<?php $col=null ?>
			<?php foreach ($this->tableau as $case) : ?>
	
			<?php if ($case["change_level"] == 1 && $col == "ok") :
	          echo "</tr>";
			 endif; ?>
			<?php if ($case["change_level"] == true) : 
				$col="ok"; ?>
	                  <tr>
			<?php endif; ?>
	          <td class='comp_marcher_position_td' nowrap>
	           <?=$case["display"] ?><br />
	
			<?php if ($case["valid"] == true) : ?>
	            <input type='radio' name='valeur_1' id='valeur_1' value='<?php echo $case["x_offset"]."h".$case["y_offset"] ?>' <?=$case["default"]?>>
			<?php else: ?>
				<? if ($case["est_destructible"] != null) : ?>
					Palissade <br>indestructible
				<? endif; ?>
				&nbsp;
			<?php endif; ?>
	          </td>
	       <?php endforeach; ?>
	       </tr>
	     </table>
	     </td>
	    </tr>
	  </table>
	<? endif ?>
<? endif ?>
</div>

<br />
<?php if ($this->assezDePa === true && $this->attaquerPalissadeOk === true && $this->user->est_intangible_hobbit == 'non') : ?>
<input type='button' class='button1' value='Attaquer la palissade !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_attaquerpalissade");'>
<? endif ?>
