<div class='comp_titre'>Attraper une charrette</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>

	<? if ($this->attraperCharrettePossible === false) : ?>
		Il n'y a pas de charrette &agrave; attraper ici ..	
	 <? elseif ($this->possedeCharrette === true) : ?>
	 	Vous avez d&eacute;j&agrave; une charrette, vous ne pouvez pas en attraper une autre...
	 <? else: ?>
		 Pour <?=$this->nb_pa ?> PA, vous pouvez attraper une charrette. <br /><br />
		 <select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_attrapercharrette').disabled=true } else {$('bouton_attrapercharrette').disabled=false }">
			<option value='-1'>(Choisis une charrette)</option>
			<? foreach ($this->charrettes as $c) : ?>
			<option value="<?=$c["id_charrette"]?>">Charrette n&deg; <?=$c["id_charrette"]?></option>
			<? endforeach; ?>
			</select><br /><br />
	 <? endif; ?>
	 <br />
<? endif ?>
</div>

</form>
<br />
<?php if ($this->assezDePa == true && $this->possedeCharrette === false && $this->attraperCharrettePossible == true) : ?>
<input type='button' class='button1' id='bouton_attrapercharrette' value='Attraper une charrette !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_attrapercharrette");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>