<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	
	<? if ($this->routeTrouvee) : ?>
		Vous avez découvert une ancienne route. Félicitations !
	<? else: ?>
		Vous avez balisé un sentier !<br />
		
		Ce sentier a les caract&eacute;ristiques suivantes : <br />
		Qualit&eacute; : <?=$this->qualite?><br />
		Position : <?=$this->user->x_braldun ?>, <?=$this->user->y_braldun ?><br />
		Date de destruction : le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->route["date_fin_route"]); ?>
		
		<br /><br />
		
		<? if ($this->construireRouteContinueOk == true) : ?>
			<? if ($this->deplacement == true) : ?>
				Vous êtes arrivé en x=<?=$this->user->x_braldun?>, y=<?=$this->user->y_braldun?>.<br /><br />
			<? endif;?>
		Vous avez balisé à côté d'un autre sentier balisé, vous avez donc bénéficié de -10% sur votre jet d'action.
		<? endif;?>
	<? endif;?>
<? endif; ?>