 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

<?php if ($this->construireOk == true) : ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez baliser un sentier &agrave; l'endroit où vous &ecirc;tes.
	
	<?php if ($this->construireRouteContinueOk == true) : ?>
		<br /><br />Il y a d&eacute;j&agrave; un sentier balisé autour de vous. 
		<br />Vous avez donc 10% de chance de plus de r&eacute;ussir la balise.<br />
		
		<br />En cas de réussite, vous devrez quitter la case. <br />
		Dans ce cas, où voulez-vous vous déplacer gratuitement ?<br />
		<?php include('marcher_tableau.phtml'); ?>
	<?php else : ?>
		<input type='hidden' name='valeur_1' id='valeur_1' value='-1'>
	<?php endif;?>
<?php else: ?>
	Vous ne pouvez pas baliser de sentier &agrave; cet endroit
<?php endif;?>
<br /><br />
</div>

<br />
<?php if ($this->assezDePa === true && $this->construireOk === true) : ?>
<input type='button' class='button' value='Baliser !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_baliser");'>
<?php endif ?>
