<?php include("commun_text_resultat.phtml") ?>
		
<?php if ($this->okJet1 === true):
	$s = "";
	if ($this->nbBieres > 1) : $s = "s"; endif;
?>
		Vous avez r&eacute;ussi à brasser.<br /> 
		Vous avez préparé
		<?php echo $this->nbBieres ?> outre<?php if ($this->nbBieres) : echo "s"; endif;?> <?php echo $this->qualite?>.<br /><br />
		<?php if ($this->nbBieresATerre > 0): ?>
			Faute de place, <?php echo $this->nbBieresATerre ?> outre<?php if ($this->nbBieresATerre > 1): echo "s sont tomb&eacute;es à terre"; else: " est tomb&eacute;e à terre"; endif?>.
			<br /><br />
		<?php endif;?>
<?php endif; ?>
<br />