 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
 	Vous devez avoir au minimum 5Kg d'Orge et 26g de Houblon pour brasser.<br>
	 <? if ($this->brasserOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez brasser 
	 	jusqu'&agrave; <?=$this->nbBieres ?> outre<? if ($this->nbBieres > 1) : echo "s"; endif;?> de bière.<br>
	 
		 <br><br>
		 Nombre de d'outre de bière à préparer : <br />
		 <select name="valeur_1" id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_brasser').disabled=true } else {$('bouton_brasser').disabled=false }">
		 	<option value="-1">(Choisissez le nombre)</option>
		 	<? for ($i = 1; $i<= $this->nbBieres; $i++) : ?>
		 		<option value="<?=$i?>"><?=$i?> outre<? if ($i > 1): echo "s"; endif;?></option>
		 	<? endfor; ?>
		 </select>
			 
		<br>
		Source des ingrédients :<br />
	     <select name="valeur_2" id="valeur_2" onChange="if ($('valeur_2').value != -1 && $('valeur_3').value != -1) { $('bouton_cuisiner').disabled=false; } else {$('bouton_cuisiner').disabled=true; }">
		 	<option value="-1">(Choisissez une source)</option>
			 	<? foreach($this->destinations as $k => $t) : ?>
			 		<option value="<?=$k?>" <? if ($t["possible"] != true): echo "disabled"; endif; ?>><?=$t["nom"]?> <? if ($t["possible"] != true): echo "- Ingrédients non disponibles"; endif; ?></option>
			 	<? endforeach; ?>
		 </select>
		 
		 <br> <br>
		Destination :<br />
	     <select name="valeur_3" id="valeur_3" onChange="if ($('valeur_3').value != -1 && $('valeur_2').value != -1) { $('bouton_cuisiner').disabled=false; } else {$('bouton_cuisiner').disabled=true;}">
		 	<option value="-1">(Choisissez une destination)</option>
		 		<option value="<?=$k?>" <? if ($t["possible"] != true): echo "disabled"; endif; ?>><?=$t["nom"]?> <? if ($t["possible"] != true): echo "- Pas assez de place"; endif; ?></option>
		 </select>
		<br>
		Attention, si vous n'avez pas assez de place pour contenir les outres créés, les outres en trop seront laissées au sol.
	
	 <? else: ?>
		 Vous n'avez pas assez d'Orge et de Houblon pour brasser.<br />
	 <? endif; ?>

</div>

<br />
<?php if ($this->assezDePa == true && $this->brasserOk === true) : ?>
<input type='button' class='button1' id='bouton_brasser' value='Brasser !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_brasser");' disabled>
<? endif ?>