 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	<? if ($this->possedeCharrette == true && $this->chargerPossible == false) :?>
 		Vous ne pouvez pas charger avec votre charrette, elle ne poss&egrave;de pas les
 		caract&eacute;ristiques n&eacute;cessaires !<br /><br />
 	<? elseif ($this->armeTirPortee == true) :?>
		Vous ne pouvez pas utiliser cette comp&eacute;tence avec une arme de tir !<br /><br />
	<? else: ?>
	  	<? include('commun_attaque_formulaire.phtml');?>
		
	 	<? if ($this->nBralduns == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; charger dans votre distance de charge de <?=$this->charge_nb_cases ?> case<?if ($this->charge_nb_cases > 1): echo 's'; endif; ?><br />
	 	<? else: ?>
	 		Pour <?=$this->nb_pa?> PA, vous pouvez charger &agrave; <?=$this->charge_nb_cases ?> case<?if ($this->charge_nb_cases > 1): echo 's'; endif; ?>.<br /><br />
	 		 <br /><br />
			<? if ($this->nMonstres > 0): ?>
			Charger un monstre<br />
				<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_charger').disabled=true } else {$('valeur_2').value=-1; $('bouton_charger').disabled=false }">
				<option value='-1'>(Choisissez un monstre)</option>
				<? foreach ($this->tabMonstres as $m) : ?>
				<option value="<?=$m["id_monstre"]?>"><? if ($m["est_gibier"]): ?> Gibier : <? endif;?><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>) x:<?=$m["x_monstre"]?> , y:<?=$m["y_monstre"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
			<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<? endif; ?>
			
	 		<? if ($this->nBralduns > 0): ?>
	 		 Charger un Braldûn<br />
	 			<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_charger').disabled=true } else {$('valeur_1').value=-1; $('bouton_charger').disabled=false }">
				<option value='-1'>(Choisissez un Braldûn)</option>
	 			<? foreach ($this->tabBralduns as $h) : ?>
				<option value="<?=$h["id_braldun"]?>"><?=$h["prenom_braldun"]?> <?=$h["nom_braldun"]?> (<?=$h["id_braldun"]?>) x:<?=$h["x_braldun"]?> , y:<?=$h["y_braldun"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
			<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<? endif;?>
		<? endif; ?>
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->chargerPossible === true) : ?>
<input type='button' class='button1' value='Charger !' id='bouton_charger' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_charger");' disabled>
<? endif ?>
