 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	<?php if ($this->possedeCharrette == true && $this->chargerPossible == false) :?>
 		Vous ne pouvez pas charger avec votre charrette, elle ne poss&egrave;de pas les
 		caract&eacute;ristiques n&eacute;cessaires !<br /><br />
 	<?php elseif ($this->armeTirPortee == true) :?>
		Vous ne pouvez pas utiliser cette comp&eacute;tence avec une arme de tir !<br /><br />
	<?php else: ?>
	  	<?php include('commun_attaque_formulaire.phtml');?>
		
	 	<?php if ($this->nBralduns == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; charger dans votre distance de charge de <?php echo $this->charge_nb_cases ?> case<?php if ($this->charge_nb_cases > 1): echo 's'; endif; ?><br />
	 	<?php else: ?>
	 		Pour <?php echo $this->nb_pa?> PA, vous pouvez charger &agrave; <?php echo $this->charge_nb_cases ?> case<?php if ($this->charge_nb_cases > 1): echo 's'; endif; ?>.<br /><br />
	 		 <br /><br />
			<?php if ($this->nMonstres > 0): ?>
			Charger un monstre<br />
				<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').value==-1 && $('#valeur_2').value==-1){$('#bouton_charger.attr('disabled', true) } else {$('#valeur_2').value=-1; $('#bouton_charger').attr('disabled',false) }">
				<option value='-1'>(Choisissez un monstre)</option>
				<?php foreach ($this->tabMonstres as $m) : ?>
				<option value="<?php echo $m["id_monstre"]?>"><?php if ($m["est_gibier"]): ?> Gibier : <?php endif;?><?php echo $m["nom_monstre"]?> <?php echo $m["taille_monstre"]?>  (<?php echo $m["id_monstre"]?>) x:<?php echo $m["x_monstre"]?> , y:<?php echo $m["y_monstre"]?></option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
			<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<?php endif; ?>
			
	 		<?php if ($this->nBralduns > 0): ?>
	 		 Charger un Braldûn<br />
	 			<select name='valeur_2' id="valeur_2" onchange="javascript:if ($('#valeur_1').value==-1 && $('#valeur_2').value==-1){$('#bouton_charger.attr('disabled', true) } else {$('#valeur_1').value=-1; $('#bouton_charger').attr('disabled',false) }">
				<option value='-1'>(Choisissez un Braldûn)</option>
	 			<?php foreach ($this->tabBralduns as $h) : ?>
				<option value="<?php echo $h["id_braldun"]?>"><?php echo $h["prenom_braldun"]?> <?php echo $h["nom_braldun"]?> (<?php echo $h["id_braldun"]?>) x:<?php echo $h["x_braldun"]?> , y:<?php echo $h["y_braldun"]?></option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
			<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<?php endif;?>
		<?php endif; ?>
	<?php endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->chargerPossible === true) : ?>
<input type='button' class='button1' value='Charger !' id='bouton_charger' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_charger");' disabled>
<?php endif ?>
