<? include("commun_text_resultat.phtml") ?>
	<? if ($this->okJet1 === true): ?>
		 Vous avez charg&eacute; <?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) 
		 <br /> et vous &ecirc;tes arriv&eacute; en x:<?=$this->retourAttaque["cible"]["x_cible"]?> y:<?=$this->retourAttaque["cible"]["y_cible"]?><br /><br />
		 Jet d'attaque : <?=$this->retourAttaque["jetAttaquant"]?><br />
		 Jet de d&eacute;fense de la cible : <?=$this->retourAttaque["jetCible"]?><br />
		 
	 	<? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
	 		<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
	 		Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;g&acirc;ts
	 		<? if ($this->retourAttaque["critique"]  == true): ?>
	 		en attaque critique
	 		<? endif; ?>
	 		<br /><br />
	 		<? if ($this->retourAttaque["arm_nat_cible"] > 0) :?>
	 			L'armure naturelle l'a prot&eacute;g&eacute;e en réduisant les d&eacute;g&acirc;ts de <?= $this->retourAttaque["arm_nat_cible"]?><br />
	 		<? endif; ?>
	 		<? if ($this->retourAttaque["arm_eqpt_cible"] > 0) :?>
	 			L'&eacute;quipement l'a prot&eacute;g&eacute; en r&eacute;duisant les d&eacute;g&acirc;ts de <?= $this->retourAttaque["arm_eqpt_cible"]?><br />
	 		<? endif; ?>
			La cible a donc perdu <?=$this->retourAttaque["jetDegatReel"] ?> point<? if ($this->retourAttaque["jetDegatReel"] > 1) : ?>s<?endif;?> de vie<br />
	 		<br />
	 		<? if ($this->retourAttaque["mort"] === true): ?>
	 			Vous avez 
	 			<? if ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "oui") :?>
		 			plaqu&eacute;
		 		<? elseif ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "non") :?>
		 			mis KO
		 		<? else: ?>	
		 			tu&eacute; 
		 		<? endif;?>
		 		<?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
		 		
		 		<? if ($this->retourAttaque["gains"] != null) :?>
		 			<? if ($this->retourAttaque["gains"]["gainRune"] != false) :?>
		 				Une rune est tomb&eaucte;e &agrave; terre <? if ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
		 				ainsi que <?=$this->retourAttaque["gains"]["gainCastars"]?> castar<? if ($this->retourAttaque["gains"]["gainCastars"] > 1): echo "s"; endif;?>
		 				<? endif;?>.
		 				<br /><br />
		 			<? elseif ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
		 				<?=$this->retourAttaque["gains"]["gainCastars"]?> castar<? if ($this->retourAttaque["gains"]["gainCastars"] > 1) : echo "s"; endif;?>
		 				sont tomb&eacute;s &agrave; terre.<br /><br />
		 			<? endif;?>
		 		<? endif;?>
	 		<? endif; ?>
	 		
	 		<? if ($this->effetRune) :?>
				Une rune que vous portez a fait effet.<br />
			<? endif; ?>
			<? if ($this->retourAttaque["ballonLache"]) : ?>
				<img src='/public/styles/braldahim_defaut/images/vue/ballon.png'/><br>
				Le ballon de soule est tomb&eacute; &agrave; terre !<br>
			<? endif;?>
	 	<? else: ?>
	 		Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
	 		<? if ($this->retourAttaque["fragilisee"] === true) : ?>
	 			<br /> La cible est fragilis&eacute;e pour les prochaines attaques
	 		<? else: ?>
	 			parfaitement.
	 		<? endif; ?>
	 	<? endif; ?>
	 	<br /><br />
	 	Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
	<? else: ?>
		Vous avez manqu&eacute; votre charge.<br />
	<? endif; ?>
<? include("commun_text_effets.phtml") ?>
