<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true):?>
	Jet de Chasse : <?=$this->jetChasse ?> (pour <?=$this->tauxReussite ?> %) <br /><br />
	<? if ($this->jetChasseOk === true) : ?>
		
		<? if ($this->nbViande > 0 || $this->nbPeau > 0) : ?>
			Vous avez r&eacute;ssi votre jet de chasse. <br />
			Vous avez r&eacute;cup&eacute;r&eacute; : <br />
			Viande : <?=$this->nbViande ?><br />
			Peau : <?=$this->nbPeau ?><br />
		
		<? else : ?>
			Vous avez r&eacute;ssi votre jet de chasse, mais vous n'avez rien r&eacute;cup&eacute;r&eacute; 
			&agrave; cause de vos malus importants en Agilit&eacute;.<br>
		<? endif; ?>
		
		
	<? else: ?>
		Vous avez rat&eacute; votre chasse !
	<? endif; ?>			
<? endif; ?>