 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 
	<? if ($this->poidsPlaceDisponible !== true) : ?>
		Vous n'avez pas assez de place dans votre laban ! <br>
	<? else : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez chasser et r&eacute;cup&eacute;rer de la viande
	 	et de la fourrure. <br /><br />
	 	
		Si votre comp&eacute;tence est r&eacute;ussie, vous avez <?=$this->tauxReussite ?> % de chance de bien chasser.
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->poidsPlaceDisponible === true) : ?>
<input type='button' class='button1' id='bouton_chasser' value='Chasser !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_chasser");'>
<? endif ?>
