<div class='comp_titre'>Chasser</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->chasserOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez chasser et r&eacute;cup&eacute;rer de la viande
	 	et de la fourrure. <br><br>
	 	
		Si votre comp&eacute;tence est r&eacute;ussie, vous avez <?=$this->tauxReussite ?> % de chance de bien chasser.
	 <? else: ?>
	 Vous ne pouvez pas chasser ici...
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->chasserOk === true) : ?>
<input type='button' class='button1' id='bouton_chasser' value='Chasser !' onClick='this.disabled=true;_get_("/competences/DoAction?caction=do_competence_chasser");'>
<? endif ?>
<? include("commun_fermer.phtml") ?>