<div class='comp_titre'>Chasser</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->chasserOk === true) : ?>
		
	 <? else: ?>
	 Vous ne pouvez pas chasser ici...
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->chasserOk === true) : ?>
<input type='button' class='button1' id='bouton_chasser' value='Chasser !' onClick='_get_("/competences/DoAction?caction=do_competence_chasser");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>