<div class='comp_titre'>Chasser</div>

 <div class='comp_contenu'>
	 <div id='chasser_text' style="display:block"  onClick="javascript:switch2div('chasser_text','chasser_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true):?>
			
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='cueillir_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
		if ($this->okJet1 === true) {
			
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('chasser_text','chasser_copie');">
<? include("commun_fermer.phtml") ?>