	<? if ($this->jetUtilise === true):?>	
		<? if ($this->okJet1 === true):?>
			<span class="action_ok">Vous avez r&eacute;ussi votre jet d'action <?=$this->jet1 ?> %</span><br />
			<? if ($this->okJet2 === true):?>
				De plus, vous avez r&eacute;ussi votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br />
				et vous am&eacute;liorez votre comp&eacute;tence de <?=$this->jet3?> % !<br /><br />
			<? elseif ($this->jet2Possible === false): ?>
				<? if ($this->estCompetenceMetier === true && $this->ameliorationCompetenceMetierCourant === false): ?>
					Vous ne pouvez pas am&eacute;liorer cette comp&eacute;tence, elle n'appartient pas &agrave; 
					votre m&eacute;tier courant<br /><br />
				<? else: ?>
					Vous ne pouvez plus am&eacute;liorer cette comp&eacute;tence<br /><br />
				<? endif; ?>
			<? else: ?>
					Vous avez rat&eacute; votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br /><br />
			<? endif; ?>
			<? if ($this->calcul_px_generique === true) : ?>
				<? if ($this->nb_px == 0) : ?>
					Vous n'avez gagn&eacute; aucun PX<br /><br /> 
				<? else: ?>
					Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
				<? endif; ?>
			<? endif; ?>
		<? else: ?>
			<span class="action_ko">Vous avez rat&eacute; votre jet d'action <?=$this->jet1 ?> %</span><br />
			<? if ($this->okJet2 === true):?>
				Cependant, vous avez r&eacute;ussi votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br />
				et vous am&eacute;liorez votre comp&eacute;tence de <?=$this->jet3?> % !<br /><br />
			<? elseif ($this->estCompetenceMetier === true && $this->ameliorationCompetenceMetierCourant === false): ?>
				Vous ne pouvez pas am&eacute;liorer cette comp&eacute;tence, elle n'appartient pas &agrave; 
				votre m&eacute;tier courant<br /><br />
			<? elseif ($this->jet2Possible === true): ?>
				Vous avez rat&eacute; votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br /><br />
			<? endif; ?>
		<? endif; ?>
	<? endif; ?>
	
	<? if ($this->balanceFaimUtilisee === true): ?>
		Influence sur la balance de faim : <?=$this->balance_faim ?> %<br /><br />
	<? endif; ?>
		Cela vous a co&ucirc;t&eacute; <?=$this->nb_pa?> PA<br /><br />
		
	<? if ($this->changeNiveau === true):?>
		Vous avez chang&eacute; de niveau ! <br />
		Vous &ecirc;tes maintenant Niveau <?=$this->user->niveau_hobbit ?><br />
		Vous avez  <?=$this->user->pi_hobbit ?> PI<br /><br />
		<? if (($this->user->niveau_hobbit % 10) == 0) : ?>
			<? if ($this->user->niveau_hobbit > 10) :?>
				Vous avez un nouveau titre !
			<? else : ?>
				Vous avez gagn&eacute; un titre !
			<? endif;?>
			<br />
			Vous &ecirc;tes maintenant 
			<?=$this->escape($this->user->prenom_hobbit);?>  <?=$this->escape($this->user->nom_hobbit);?>, <?=$this->user->titre_courant_hobbit?><br>
		<? endif;?>
	<? endif; ?>