<?
	if ($this->jetUtilise === true) {
		if ($this->okJet1 === true) {
			if ($this->okJet2 === true && $this->okJet3 === true) {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1." %";
				echo "
";
				echo "Vous am&eacute;liorez votre comp&eacute;tence de ".$this->jet3." %";
echo "
";
			} elseif ($this->okJet2 === true && $this->okJet3 === false) {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1." %";
				echo "
";
				echo "Vous ne pouvez plus am&eacute;liorer cette comp&eacute;tence";
echo "
";
			} else {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1. " %";
				echo "
";
				echo "Vous avez rat&eacute; votre jet d'am&eacute;lioration : ".$this->jet2. " %";
				echo "
";
			}
			if ($this->calcul_px_generique === true) {
				echo "Vous avez gagn&eacute; ".$this->nb_px." PX";
				echo "
";
			}
			
		} else {
			echo "Vous avez rat&eacute; votre jet d'action ".$this->jet1." %";
			echo "
";
			if ($this->okJet2 === true && $this->okJet3 === true) {
				echo "Mais, vous am&eacute;liorez votre comp&eacute;tence de ".$this->jet3." % !";
				echo "
";
			} elseif ($this->jet2Possible === true) {
				echo "Vous avez rat&eacute; votre jet d'am&eacute;lioration : ".$this->jet2." %";
				echo "
";
			}
		}
	}
	
	if ($this->balanceFaimUtilisee === true) {
		echo "Influence sur la balance de faim : ".$this->balance_faim. " %";	
		echo "
";
	}
	echo "Cela vous a cout&eacute; ".$this->nb_pa." PA";
	echo "
";

	if ($this->changeNiveau === true) {
		echo "Vous avez chang&eacute; de niveau !";
		
		echo " Vous &ecirc;tes maintenant Niveau ".$this->user->niveau_hobbit;
		echo " Vous avez ".$this->user->pi_hobbit." PI";
		echo "
";
	}