<?

	if ($this->retourAttaque["effetMotD"]) {
		echo "
";
		echo "Votre casque de La Mouette a eu de l'effet sur cette action, vos chances de trouver des runes rares ont &eacute;t&eacute; augment&eacute;es.";
		echo "
";
	}
	
	if ($this->retourAttaque["effetMotE"]) {
		echo "
";
		echo "Votre arme des Vampires a eu de l'effet sur cette action :  ";
		echo "Votre arme des Vampires vous permet de gagner ".$this->retourAttaque["effetMotEPoints"]." point";
		if ($this->retourAttaque["effetMotEPoints"] > 1): echo "s"; endif;
		echo " de vie. 
";
	}
	
	if ($this->retourAttaque["effetMotG"]) {
		echo "Votre arme de Massacre a eu de l'effet sur cette action : le bonus de d&eacute;g&acirc;ts de votre ";
		echo "arme a &eacute;t&eacute; doubl&eacute; (ou divis&eacute; par deux s'il est n&eacute;gatif).";
		echo "
";
	}
	
	if ($this->retourAttaque["effetMotH"]) {
		echo "
";
		echo "Votre arme d'Appar&acirc;t a eu de l'effet sur cette action, la quantit&eacute; de castars dropp&eacute;s a &eacute;t&eacute; doubl&eacute;e.";
		echo "
";
	}

	if ($this->retourAttaque["effetMotI"]) {
		echo "
";
		echo "Votre arme de Maladie a eu de l'effet sur cette action : la cible subit un malus de r&eacute;g&eacute;n&eacute;ration &eacute;gal au niveau de l'arme.";
		echo "
";
	}
	
	if ($this->retourAttaque["effetMotL"]) {
		echo "
";
		echo "Votre arme de Finisseur a eu de l'effet sur cette action, vous gagnez 3 Points d'Action.";
		echo "
";
	}
	
	if ($this->retourAttaque["effetMotQ"]) {
		echo "
";
		echo "Votre arme de Glace a eu de l'effet sur cette action : la cible subit un malus d'agilit&eacute; &eacute;gal au niveau de l'arme. ";
		echo "Le malus est appliqu&eacute; pour le tour actuel et le tour suivant de la cible.";
		echo "
";
	}
	
	if ($this->retourAttaque["effetMotS"]) {
		echo "
";
		echo "Votre cible a rispost&eacute; &agrave; votre attaque !";
		echo "
";
		 echo "Jet d'attaque de votre cible : ".$this->retourAttaque["retourAttaqueEffetMotS"]["jetAttaquant"];
		 echo "
";
		 echo "Votre jet de r&eacute;sistance : ".$this->retourAttaque["retourAttaqueEffetMotS"]["jetCible"];
		 echo "
";
		 
	 	 if ($this->retourAttaque["retourAttaqueEffetMotS"]["attaqueReussie"] === true) {
	 		if ($this->retourAttaque["retourAttaqueEffetMotS"]["jetDegat"] > 1) : $s='s'; else : $s=''; endif;
	 		echo "Vous avez eu ".$this->retourAttaque["retourAttaqueEffetMotS"]["jetDegat"]." point".$s." de d&eacute;g&acirc;ts ";
	 		if ($this->retourAttaque["retourAttaqueEffetMotS"]["critique"]  == true) {
	 			echo "en attaque critique";
	 		}
	 		echo "
";
	 		
	 		if ($this->retourAttaque["retourAttaqueEffetMotS"]["mort"] === true) {
	 			echo "Vous avez &eacute;t&eacute; mis KO ";
	 			echo "
";
			}
	 	  } else {
	 	  	echo "Vous avez esquiv&eacute; l'attaque";
	 	  	
	 	  	 if ($this->retourAttaque["retourAttaqueEffetMotS"]["fragilisee"] === true) {
	 	  	 	echo "
";
	 		 	echo "Vous &ecirc;tes fragilis&eacute;e pour les prochaines attaques";
	 		 	echo "
";
	 	  	 } else {
	 	  	 	echo " parfaitement";
;	 	  	 }
	 	  }
	}

?>