<?
	if ($this->jetUtilise === true) {
		if ($this->okJet1 === true) {
			if ($this->okJet2 === true && $this->okJet3 === true) {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1." %";
				echo "
";
				echo "Vous am&eacute;liorez votre comp&eacute;tence de ".$this->jet3." %";
echo "
";
			} elseif ($this->okJet2 === true && $this->okJet3 === false) {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1." %";
				echo "
";
				echo "Vous ne pouvez plus am&eacute;liorer cette comp&eacute;tence";
echo "
";
			} else {
				echo "Vous avez r&eacute;ussi votre jet d'action ".$this->jet1. " %";
				echo "
";
				if ($this->estCompetenceMetier === true && $this->ameliorationCompetenceMetierCourant === false) {
					echo "Vous ne pouvez pas am&eacute;liorer cette comp&eacute;tence, elle n'appartient pas &agrave;";
					echo " votre m&eacute;tier courant";
					echo "
";
				} else {
					echo "Vous avez rat&eacute; votre jet d'am&eacute;lioration : ".$this->jet2. " %";
					echo "
";
				}
			}
			if ($this->calcul_px_generique === true) {
				echo "Vous avez gagn&eacute; ".$this->nb_px." PX";
				echo "
";
			}
			
		} else {
			echo "Vous avez rat&eacute; votre jet d'action ".$this->jet1." %";
			echo "
";
			if ($this->okJet2 === true && $this->okJet3 === true) {
				echo "Cependant, vous am&eacute;liorez votre comp&eacute;tence de ".$this->jet3." % !";
				echo "
";
			} elseif ($this->estCompetenceMetier === true && $this->ameliorationCompetenceMetierCourant === false) {
				echo "Vous ne pouvez pas am&eacute;liorer cette comp&eacute;tence, elle n'appartient pas &agrave;";
				echo " votre m&eacute;tier courant";
				echo "
";
			} elseif ($this->jet2Possible === true) {
				echo "Vous avez rat&eacute; votre jet d'am&eacute;lioration : ".$this->jet2." %";
				echo "
";
			}
		}
	}
	
	if ($this->balanceFaimUtilisee === true) {
		echo "Influence sur la balance de faim : ".$this->balance_faim. " %";	
		echo "
";
	}
	echo "Cela vous a co&ucirc;t&eacute; ".$this->nb_pa." PA";
	echo "
";

	if ($this->changeNiveau === true) {
		echo "Vous avez chang&eacute; de niveau !";
		
		echo " Vous &ecirc;tes maintenant Niveau ".$this->user->niveau_hobbit;
		echo " Vous avez ".$this->user->pi_hobbit." PI";
		echo "
";
		
		if (($this->user->niveau_hobbit % 10) == 0) {
			if ($this->user->niveau_hobbit > 10) {
				echo "Vous avez un nouveau titre !
";
			} else {
				echo "Vous avez gagn&eacute; un titre ! 
";
			}
			
			echo "Vous &ecirc;tes maintenant ";
			echo $this->escape($this->user->prenom_hobbit). " " .$this->escape($this->user->nom_hobbit);." , ".$this->user->titre_courant_hobbit." 
";
		}
	}