		
Points de Gredin : <?php echo $this->user->points_gredin_braldun?>.<br />
Points de Redresseur de Torts : <?php echo $this->user->points_redresseur_braldun?>.<br /><br />

 <?php if ($this->estRegionPvp == false) :?>
 	<?php if ($this->user->points_gredin_braldun > 0 || $this->user->points_redresseur_braldun > 0) : ?>
 		Dans cette région, vous ne pouvez attaquer que des gredins ou des redresseurs de torts.
 	<?php else : ?>
		Vous ne pouvez pas attaquer de Braldûn dans cette r&eacute;gion.
	<?php endif;?>
	<br /><br />
<?php endif;?>

<?php if ($this->user->est_soule_braldun == 'oui') :?>
	Vous ne pouvez attaquer que des adversaires pendant un match de soule.<br /><br />
<?php endif;?>

<?php if ($this->user->est_intangible_braldun == 'oui') :?>
	Vous êtes actuellement intangible, vous ne pouvez pas attaquer.<br /><br />
<?php endif;?>