		<? if ($this->okJet1 === true):?>
			<? if ($this->okJet2 === true && $this->okJet3 === true):?>
				<span class="action_ok">Vous avez r&eacute;ussi votre jet d'action <?=$this->jet1 ?> %</span><br>
				Vous am&eacute;liorez votre comp&eacute;tence de <?=$this->jet3?> % !<br><br>
			<? elseif ($this->okJet2 === true && $this->okJet3 === false): ?>
				<span class="action_ok">Vous avez r&eacute;ussi votre jet d'action <?=$this->jet1 ?> %</span><br>
				Vous ne pouvez plus am&eacute;liorer cette comp&eacute;tence<br><br>
			<? else: ?>
				<span class="action_ok">Vous avez r&eacute;ussi votre jet d'action <?=$this->jet1 ?> %</span><br>
				Vous avez rat&eacute; votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br><br>
			<? endif; ?>
			<? if ($this->calcul_px_generique === true) : ?>
			Vous avez gagn&eacute; <?=$this->nb_px?> PX<br><br>
			<? endif; ?>
		<? else: ?>
			<span class="action_ko">Vous avez rat&eacute; votre jet d'action <?=$this->jet1 ?> %</span><br>
			<? if ($this->okJet2 === true && $this->okJet3 === true):?>
				Mais, vous am&eacute;liorez votre comp&eacute;tence de <?=$this->jet3?> % !<br><br>
			<? elseif ($this->jet2Possible === true): ?>
				Vous avez rat&eacute; votre jet d'am&eacute;lioration : <?=$this->jet2?> %<br><br>
			<? endif; ?>
		<? endif; ?>
		Influence sur la balance de faim : <?=$this->balance_faim ?> %<br><br>
		Cela vous a cout&eacute; <?=$this->nb_pa?> PA<br><br>
		
		<? if ($this->changeNiveau === true):?>
		Vous avez chang&eacute; de niveau ! <br>
		Vous &ecirc;tes maintenant Niveau <?=$this->user->niveau_hobbit ?><br>
		Vous avez  <?=$this->user->pi_hobbit ?> PI<br><br>
		<? endif; ?>