<?php $modif = false;?>
<?php if ($this->retourAttaque["attaquantDeltaPointsGredin"] != null) : $modif = true; ?>
	<br />Influence sur vos points de Gredin : <?php echo $this->retourAttaque["attaquantDeltaPointsGredin"] ?>
<?php endif;?>

<?php if ($this->retourAttaque["attaquantDeltaPointsRedresseur"] != null) : $modif = true; ?>
	<br />Influence sur vos points de Redresseur de Torts : <?php echo $this->retourAttaque["attaquantDeltaPointsRedresseur"] ?>
<?php endif;?>

<?php if ($this->retourAttaque["cibleDeltaPointsGredin"] != null) : $modif = true; ?>
	<br />Influence sur les points de Gredin de la cible : <?php echo $this->retourAttaque["cibleDeltaPointsGredin"] ?>
<?php endif;?>

<?php if ($this->retourAttaque["cibleDeltaPointsRedresseur"] != null) : $modif = true; ?>
	<br />Influence sur les points de Redresseur de Torts de la cible  : <?php echo $this->retourAttaque["cibleDeltaPointsRedresseur"] ?>
<?php endif;?>

<?php if ($modif === true) : ?>
<br /><br />
Vos points de Gredin : <?php echo $this->user->points_gredin_braldun?><br />
Vos points de Redresseur de Torts : <?php echo $this->user->points_redresseur_braldun?><br />
<?php endif;?>

<?php if ($this->retourAttaque["nouvelleDistinction"] != null) : ?>
	<br />
	<?php echo $this->retourAttaque["nouvelleDistinction"]?><br />
<?php endif;?>

<?php if ($this->retourAttaque["contratModifie"] === true) : ?>
	<br />
	<b>Il y a du nouveau sur votre contrat. Consultez l'onglet Quêtes / Contrats.</b>
	<br />
<?php endif;?>
<br />
