<div class='comp_titre'><?=$this->competence["nom"] ?></div>

 <div class='comp_contenu'>
	 <div id='<?=$this->competence["nom_systeme"]?>_text' style="display:block">
	<?=$this->texte ?>
	<br />
	 </div>
	 
	 <div id='<?=$this->competence["nom_systeme"]?>_copie' style="display:none">
		<textarea rows=15 cols=60><?=Bral_Helper_Affiche::copie($this->texte); ?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('<?=$this->competence["nom_systeme"]?>_text','<?=$this->competence["nom_systeme"]?>_copie');">
<? if ($this->reloadInterface == true): ?>
	<input type='button' class='button1' value='Fermer' onClick='_get_("/interface/reload");Modalbox.hide();'>
<? else: ?>
	<? echo Bral_Helper_Fermer::affiche(); ?>
<? endif; ?>