<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; concocter une plante <?=$this->planteNomType ?>.
	Vous avez concoct&eacute; <?=$this->nbPartiesPlantesPreparees ?> <?=$this->planteNomTypePartiePlante?><?if($this->nbPartiesPlantesPreparees > 1):echo 's';endif;?>
	<br />
<? else: ?>
	Vous avez manqu&eacute; votre pr&eacute;paration<br />
<? endif; ?>