<div class='comp_titre'>Concocter</div>

 <div class='comp_contenu'>
	 <div id='concocter_text' style="display:block"  onClick="javascript:switch2div('concocter_text','concocter_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true): ?>
			Vous avez r&eacute;ussi &agrave; concocter une plante <?=htmlentities($this->planteNomType) ?>.
			Vous avez concoct&eacute; <?=$this->nbPartiesPlantesPreparees ?> <?=$this->planteNomTypePartiePlante?><?if($this->nbPartiesPlantesPreparees > 1):echo 's';endif;?>
			<br />
		<? else: ?>
			Vous avez manqu&eacute; votre pr&eacute;paration<br />
		<? endif; ?>
		<br />
	 </div>
	 
	 <div id='concocter_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
			echo "
";
			if ($this->okJet1 === true) {
				echo "Vous avez r&eacute;ussi &agrave; concocter une plante ".htmlentities($this->planteNomType);
				echo "
";
				echo "Vous avez concoct&eacute; ".$this->nbPartiesPlantesPreparees." ".$this->planteNomTypePartiePlante;
				if($this->nbPartiesPlantesPreparees > 1):echo 's';endif;
				echo "
";
			} else {
				echo "Vous avez manqu&eacute; votre pr&eacute;paration";
			}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('concocter_text','concocter_copie');">
<? include("commun_fermer.phtml") ?>