<div class='comp_titre'>Concocter</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->concocterEchoppeOk === true && $this->concocterPlanteOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez concocter du 2 parties de plante en 1D2 partie(s) de plante pr&eacute;par&eacute;e(s) ...<br>
	 <select name="valeur_1" id="valeur_1"  onChange="javascript:if ($('valeur_1').value==-1){$('bouton_concocter').disabled=true } else {$('bouton_concocter').disabled=false }">
	 	<option value="-1">(Choisis une plante)</option>
	 	<? foreach($this->partiesPlantes as $m) :
			if ($m["quantite_arriere"]<=1):$s=''; else:$s='s';endif;
	 	?>
	 		<option value="<?=$m["indicateur"]?>"><?=$m["quantite_arriere"]?> <?=htmlentities($m["nom_type_partieplante"])?><?=$s?> de <?=htmlentities($m["nom_type"])?></option>
	 	<? endforeach; ?>
	 </select>
	<? elseif ($this->concocterEchoppeOk == false) : ?>
		Vous ne pouvez concocter que dans une de vos &eacute;choppes de Forgeron.
	<? else: ?>
		Vous n'avez aucune plante &agrave; concocter...
	<? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->concocterEchoppeOk === true && $this->concocterPlanteOk) : ?>
<input type='button' class='button1' id='bouton_concocter' value='Concocter !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_concocter");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>