 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if ($this->nMonstres == 0) : ?>
 	Il n'y a aucun monstre dans votre vue !<br />
<?php else: ?>
	Pour <?=$this->nb_pa ?> PA, vous pouvez conna&icirc;tre les caract&eacute;ristiques de base d'un monstre &agrave; <?=$this->distance ?> cases.<br />

	Reconna&icirc;tre un monstre<br />
	<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_cdm').disabled=true } else {$('bouton_cdm').disabled=false }">
		<option value='-1'>(Choisis un monstre)</option>
		<? foreach ($this->tabMonstres as $m) : ?>
		<option value="<?=$m["id_monstre"]?>"><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>) x:<?=$m["x_monstre"]?> , y:<?=$m["y_monstre"]?></option>
		<? endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button1' value='Reconna&icirc;tre !' id='bouton_cdm' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_connaissancemonstres");' disabled>
<?php endif; ?>
</div>