 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if ($this->nMonstres == 0) : ?>
 	Il n'y a aucun monstre dans votre vue !<br />
<?php else: ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez conna&icirc;tre les caract&eacute;ristiques de base d'un monstre &agrave; <?php echo $this->distance ?> cases.<br />

	Reconna&icirc;tre un monstre<br />
	<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').val() ==-1){$('#bouton_cdm').attr('disabled', true) } else {$('#bouton_cdm').attr('disabled',false) }">
		<option value='-1'>(Choisissez un monstre)</option>
		<?php $dist=-1; ?>
		<?php foreach ($this->tabMonstres as $m) : ?>
			<?php if ($dist != $m['dist_monstre']) : ?>
				<?php
				$dist = $m['dist_monstre'];
				switch ($dist) {
					case 0:
						$case = "Sur votre case : ";
						break;
					case 1:
						$case = "&agrave; 1 case : ";
						break;
					default:
						$case = "&agrave; $dist cases : ";
				}
				?>
				<optgroup label="<?php echo $case ?>" style="font-weight:bold"></optgroup>
			<?php endif; ?>
		<option value="<?php echo $m["id_monstre"]?>"><?php echo $m["nom_monstre"]?> <?php echo $m["taille_monstre"]?>  (<?php echo $m["id_monstre"]?>) x:<?php echo $m["x_monstre"]?> , y:<?php echo $m["y_monstre"]?></option>
		<?php endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button1' value='Reconna&icirc;tre !' id='bouton_cdm' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_connaissancemonstres");' disabled>
<?php endif; ?>
</div>