<? include("commun_text_resultat.phtml") ?>
<? if ($this->okJet1 === true): ?>
	Le hobbit <?=$this->tabCDM['prenom_hobbit']?> <?=$this->tabCDM['nom_hobbit'] ?> (<?=$this->tabCDM['id_hobbit'] ?>) a les caract&eacute;ristiques suivantes :<br /><br />
	
	Niveau : <?=$this->tabCDM['niveau_hobbit'] ?> <br />
	Point de vie max : entre <?=$this->tabCDM['min_pvmax_hobbit'] ?> et <?=$this->tabCDM['max_pvmax_hobbit'] ?><br />
	Point de vie actuels : entre <?=$this->tabCDM['min_pvact_hobbit'] ?> et <?=$this->tabCDM['max_pvact_hobbit'] ?><br />
	Force : entre <?=$this->tabCDM['min_for_hobbit'] ?> et <?=$this->tabCDM['max_for_hobbit'] ?> D<?=$this->config->game->de_force?><br />
	Agilit&eacute; : entre <?=$this->tabCDM['min_agi_hobbit'] ?> et <?=$this->tabCDM['max_agi_hobbit'] ?> D<?=$this->config->game->de_agilite?><br />
	Sagesse : entre <?=$this->tabCDM['min_sag_hobbit'] ?> et <?=$this->tabCDM['max_sag_hobbit'] ?> D<?=$this->config->game->de_sagesse?><br />
	Vigueur : entre <?=$this->tabCDM['min_vig_hobbit'] ?> et <?=$this->tabCDM['max_vig_hobbit'] ?> D<?=$this->config->game->de_vigueur?><br />
	R&eacute;g&eacute;n&eacute;ration : entre <?=$this->tabCDM['min_reg_hobbit'] ?> et <?=$this->tabCDM['max_reg_hobbit'] ?> D<?=$this->config->game->de_regeneration?><br />
	Armure : entre <?=$this->tabCDM['min_arm_hobbit'] ?> et <?=$this->tabCDM['max_arm_hobbit'] ?><br />
	Dur&eacute;e du tour : entre <?=$this->tabCDM['min_dla_hobbit'] ?> et <?=$this->tabCDM['max_dla_hobbit'] ?><br />
	
<? else: ?>
	Vous avez manqu&eacute; votre reconnaissance.<br />
<? endif; ?>


