 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if ($this->nBralduns == 0) : ?>
 	Il n'y a aucun Braldûn dans votre vue !<br />
 	Si vous en voyez quand m&ecirc;me, c'est qu'ils sont intangibles.<br />
<?php else: ?>
	Pour <?=$this->nb_pa ?> PA, vous pouvez conna&icirc;tre les caract&eacute;ristiques de base d'un Braldûn &agrave; <?=$this->distance ?> cases.<br />

	Reconna&icirc;tre un Braldûn<br />
	<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_cdm').disabled=true } else {$('bouton_cdm').disabled=false }">
		<option value='-1'>(Choisissez un Braldûn)</option>
		<? $dist=-1; ?>
		<? foreach ($this->tabBralduns as $m) : ?>
			<? if ($dist != $m['dist_braldun']) : ?>
				<?
				$dist = $m['dist_braldun'];
				switch ($dist) {
					case 0:
						$case = "Sur votre case : ";
						break;
					case 1:
						$case = "&agrave; 1 case : ";
						break;
					default:
						$case = "&agrave; $dist cases : ";
				}
				?>
				<optgroup label="<?=$case ?>" style="font-weight:bold"></optgroup>
			<? endif; ?>
		<option value="<?=$m["id_braldun"]?>"><?=$m["prenom_braldun"]?> <?=$m["nom_braldun"]?> (<?=$m["id_braldun"]?>) x:<?=$m["x_braldun"]?> , y:<?=$m["y_braldun"]?></option>
		<? endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button1' value='Reconna&icirc;tre !' id='bouton_cdm' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_connaissancebralduns");' disabled>
<?php endif; ?>
</div>