 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if ($this->nBralduns == 0) : ?>
 	Il n'y a aucun Braldûn dans votre vue !<br />
 	Si vous en voyez quand m&ecirc;me, c'est qu'ils sont intangibles.<br />
<?php else: ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez conna&icirc;tre les caract&eacute;ristiques de base d'un Braldûn &agrave; <?php echo $this->distance ?> cases.<br />

	Reconna&icirc;tre un Braldûn<br />
	<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').val() ==-1){$('#bouton_cdm').attr('disabled', true) } else {$('#bouton_cdm').attr('disabled',false) }">
		<option value='-1'>(Choisissez un Braldûn)</option>
		<?php $dist=-1; ?>
		<?php foreach ($this->tabBralduns as $m) : ?>
			<?php if ($dist != $m['dist_braldun']) : ?>
				<?php
				$dist = $m['dist_braldun'];
				switch ($dist) {
					case 0:
						$case = "Sur votre case : ";
						break;
					case 1:
						$case = "&agrave; 1 case : ";
						break;
					default:
						$case = "&agrave; $dist cases : ";
				}
				?>
				<optgroup label="<?php echo $case ?>" style="font-weight:bold"></optgroup>
			<?php endif; ?>
		<option value="<?php echo $m["id_braldun"]?>"><?php echo $m["prenom_braldun"]?> <?php echo $m["nom_braldun"]?> (<?php echo $m["id_braldun"]?>) x:<?php echo $m["x_braldun"]?> , y:<?php echo $m["y_braldun"]?></option>
		<?php endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button' value='Reconna&icirc;tre !' id='bouton_cdm' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_connaissancebralduns");' disabled>
<?php endif; ?>
</div>