<?php include("commun_text_resultat.phtml") ?>
<?php if ($this->okJet1 === true): ?>
	Le Braldûn <?php echo $this->tabCDM['prenom_braldun']?> <?php echo $this->tabCDM['nom_braldun'] ?> (<?php echo $this->tabCDM['id_braldun'] ?>) a les caract&eacute;ristiques suivantes :<br /><br />
	
	Niveau : <?php echo $this->tabCDM['niveau_braldun'] ?> <br />
	Point de vie max : entre <?php echo $this->tabCDM['min_pvmax_braldun'] ?> et <?php echo $this->tabCDM['max_pvmax_braldun'] ?><br />
	Point de vie actuels : entre <?php echo $this->tabCDM['min_pvact_braldun'] ?> et <?php echo $this->tabCDM['max_pvact_braldun'] ?><br />
	Vue : <?php echo $this->tabCDM['max_vue_braldun'] ?> case<?php echo Bral_Util_String::getPluriel($this->tabCDM['max_vue_braldun'])?><br />
	D&eacute;g&acirc;ts : pas plus de <?php echo $this->tabCDM['max_deg_braldun'] ?><br />
	Attaque : pas plus de <?php echo $this->tabCDM['max_att_braldun'] ?><br />
	D&eacute;fense : pas plus de <?php echo $this->tabCDM['max_def_braldun'] ?><br />
	Sagesse : pas plus de <?php echo $this->tabCDM['max_sag_braldun'] ?><br />
	Vigueur : pas plus de <?php echo $this->tabCDM['max_vig_braldun'] ?><br />
	R&eacute;g&eacute;n&eacute;ration : pas plus de <?php echo $this->tabCDM['max_reg_braldun'] ?><br />
	Armure : entre <?php echo $this->tabCDM['min_arm_braldun'] ?> et <?php echo $this->tabCDM['max_arm_braldun'] ?><br />
	Dur&eacute;e du tour : entre <?php echo $this->tabCDM['min_dla_braldun'] ?> et <?php echo $this->tabCDM['max_dla_braldun'] ?><br />
	
<?php else: ?>
	Vous avez manqu&eacute; votre reconnaissance.<br />
<?php endif; ?>


