<? include("commun_text_resultat.phtml") ?>
<? if ($this->okJet1 === true): ?>
	Le monstre <?=$this->tabCDM['nom_monstre'] ?> <?=$this->tabCDM["taille_monstre"]?> (<?=$this->tabCDM['id_monstre'] ?>) a les caract&eacute;ristiques suivantes :<br /><br />
	
	Niveau : entre <?=$this->tabCDM['min_niveau_monstre'] ?> et <?=$this->tabCDM['max_niveau_monstre'] ?><br />
	Point de vie max : entre <?=$this->tabCDM['min_pvmax_monstre'] ?> et <?=$this->tabCDM['max_pvmax_monstre'] ?><br />
	Point de vie actuels : entre <?=$this->tabCDM['min_pvact_monstre'] ?> et <?=$this->tabCDM['max_pvact_monstre'] ?><br />
	Vue : entre <?=$this->tabCDM['min_vue_monstre'] ?> et <?=$this->tabCDM['max_vue_monstre'] ?><br />
	Force : entre <?=$this->tabCDM['min_for_monstre'] ?> et <?=$this->tabCDM['max_for_monstre'] ?><br />
	Agilit&eacute; : entre <?=$this->tabCDM['min_agi_monstre'] ?> et <?=$this->tabCDM['max_agi_monstre'] ?><br />
	Sagesse : entre <?=$this->tabCDM['min_sag_monstre'] ?> et <?=$this->tabCDM['max_sag_monstre'] ?><br />
	Vigueur : entre <?=$this->tabCDM['min_vig_monstre'] ?> et <?=$this->tabCDM['max_vig_monstre'] ?><br />
	R&eacute;g&eacute;n&eacute;ration : entre <?=$this->tabCDM['min_reg_monstre'] ?> et <?=$this->tabCDM['max_reg_monstre'] ?><br />
	Armure : entre <?=$this->tabCDM['min_arm_monstre'] ?> et <?=$this->tabCDM['max_arm_monstre'] ?><br />
	Dur&eacute;e du tour : entre <?=$this->tabCDM['min_dla_monstre'] ?> et <?=$this->tabCDM['max_dla_monstre'] ?><br />
	
	<br />
	Vous avez effectué cette compétence à une distance de <?=$this->distance?> de la cible.
	<br />
	<? if ($this->tabCDM["id_taille_monstre"] != TailleMonstre::ID_TAILLE_BOSS) : ?>
		<? if (count ($this->pister) == 0): ?>
			Vous pouvez pister ce type de monstre !<br />
		<? else: ?>
			Vous ne pouvez pas encore pister ce type de monstre !<br />
			<? if ($this->possedePister === true) : ?>
				Il vous faut reconna&icirc;tre encore au moins : <br />
				<? foreach ($this->pister as $p) : ?>
					1 <?=$p['taille'] ?><br />
				<? endforeach; ?>
			<? endif; ?>
		<? endif; ?>
	<? else:?>
		<? if ($this->possedePister === true) : ?>
			Vous ne pouvez pas pister ce type de monstre.<br>
		<? endif;?>
	<? endif;?>
	
<? else: ?>
	Vous avez manqu&eacute; votre reconnaissance.<br />
<? endif; ?>


