<? include("commun_text_resultat.phtml") ?>
<? if ($this->okJet1 === true): ?>
	Le monstre <?=$this->tabCDM['nom_monstre'] ?> <?=$this->tabCDM["taille_monstre"]?> (<?=$this->tabCDM['id_monstre'] ?>) a les cract&eacute;ristiques suivantes :<br /><br />
	
	Niveau : entre <?=$this->tabCDM['min_niveau_monstre'] ?> et <?=$this->tabCDM['max_niveau_monstre'] ?><br />
	Vue : entre <?=$this->tabCDM['min_vue_monstre'] ?> et <?=$this->tabCDM['max_vue_monstre'] ?><br />
	Force : entre <?=$this->tabCDM['min_for_monstre'] ?> et <?=$this->tabCDM['max_for_monstre'] ?><br />
	Sagesse : entre <?=$this->tabCDM['min_sag_monstre'] ?> et <?=$this->tabCDM['max_sag_monstre'] ?><br />
	Vigueur : entre <?=$this->tabCDM['min_vig_monstre'] ?> et <?=$this->tabCDM['max_vig_monstre'] ?><br />
	R&eacute;g&eacute;n&eacute;ration : entre <?=$this->tabCDM['min_reg_monstre'] ?> et <?=$this->tabCDM['max_reg_monstre'] ?><br />
	Armure : entre <?=$this->tabCDM['min_arm_monstre'] ?> et <?=$this->tabCDM['max_arm_monstre'] ?><br />

<? else: ?>
	Vous avez manqu&eacute; votre reconnaissance.<br />
<? endif; ?>


