<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>

		Vous avez construit une route !<br />
		
		Cette route a les caract&eacute;ristiques suivantes : <br />
		Qualit&eacute; : <?=$this->qualite?><br />
		Position : <?=$this->user->x_hobbit ?>, <?=$this->user->y_hobbit ?><br />
		Date de destruction : le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->route["date_fin_route"]); ?>
		
		<br><br>
		
		<? if ($this->construireRouteContinueOk == true) : ?>
		Vous êtes arrivé en x=<?=$this->user->x_hobbit?>, y=<?=$this->user->y_hobbit?>.
		<? endif;?>
		
		
		<? if ($this->estEvenement): ?>
			<br>
			Regardez &agrave; vos pieds, vous avez d&eacute;couvert quelque chose...
		<? endif; ?>
		
		<br>
		<? if ($this->nbCastarsGagnes > 0): ?>
			Vous avez gagn&eacute; <?=$this->nbCastarsGagnes?> castar<?if ($this->nbCastarsGagnes > 0): echo "s"; endif; ?>
			
			<? if ($this->nbCastarsGagnes == $this->nbCastarsLaban): ?>
				directement plac&eacute;<?if ($this->nbCastarsGagnes > 0): echo "s"; endif; ?> dans votre laban.
			<? else: ?>
				dont <?=$this->nbCastarsATerre?> tomb&eacute;<?if ($this->nbCastarsATerre > 0): echo "s"; endif; ?> &agrave; terre <br>
				et <?=$this->nbCastarsLaban?> dans votre laban.
			<? endif;?>
			
		<? else: ?>
			Vous n'avez gagn&eacute; aucun castar.
		<? endif;?>
		<br>
<? endif; ?>