 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>

Environnement : <?=$this->environnement?>.<br><br>

<? if ($this->route != null) : ?>
	<? if ($this->route["est_route"] == "oui") : ?>
		Une route existe d&eacute;j&agrave; ici...
	<? else : ?>
		<? if ($this->construireOk == true) : ?>
			Pour <?=$this->nb_pa ?> PA, vous pouvez construire une route &agrave; l'endroit où vous &ecirc;tes.
		<? else: ?>
			Vous ne pouvez pas construire de route &agrave; cet endroit
		<? endif;?>
	<? endif; ?>
	<br><br>
<? else: ?>
	Ce terrain n'est pas terrass&eacute;...
<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa === true && $this->construireOk === true) : ?>
<input type='button' class='button1' value='Construire !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_construire");'>
<? endif ?>
