<?php include("commun_text_resultat.phtml") ?>
		
Vous avez couru jusqu'en  : <br />
x=<?php echo $this->user->x_braldun?>, y=<?php echo $this->user->y_braldun?> <br /><br />

<?php if ($this->eauPalissadeRencontree === true) : ?>
	Vous vous &ecirc;tes arr&ecirc;t&eacute; devant un obstacle.
	
	<?php if ($this->estCrevasseEvenement === true) : ?>
	... et ...
	<?php endif?>
	<br /><br />
<?php endif; ?>

<?php if ($this->estCrevasseEvenement === true) : ?>
	<?php Zend_Loader::loadClass("Bral_Helper_Crevasse");
	   echo Bral_Helper_Crevasse::afficheResultat($this->user);
	?>
	<br />
<?php endif;?>
