 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

<?php if ($this->estEngage) : ?>
	Vous &ecirc;tes actuellement engag&eacute;, vous ne pouvez pas courir...<br />
	 
<?php elseif ($this->possedeCharrette == true && $this->courirPossible == false) : ?>
 	Vous ne pouvez pas courir avec votre charrette, elle ne poss&egrave;de pas les
 	caract&eacute;ristiques n&eacute;cessaires !<br /><br />

<?php else: ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez courir jusqu'&agrave; <?php echo $this->distance ?> cases.<br />

	<?php if ($this->courirPossible == false) : ?>
 		Vous &ecirc;tes entour&eacute;, vous ne pouvez pas courir !
  	<?php endif; ?>
	     Position [x;y]
	     <table class='comp_marcher_position'>
	     	<?php $col=null ?>
			<?php foreach ($this->tableau as $case) : ?>
	
			<?php if ($case["change_level"] == 1 && $col == "ok") :
	         echo "</tr>";
			endif; ?>
			<?php if ($case["change_level"] == true) : 
				$col="ok"; ?>
	                  <tr>
			<?php endif; ?>
	          <td class='comp_marcher_position_td' nowrap>
	           <?php echo $case["display"] ?><br />
	
			<?php if ($case["valid"] == true) : ?>
	            <input type='radio' name='valeur_1' id='valeur_1' value='<?php echo $case["x_offset"]."h".$case["y_offset"] ?>' <?php echo $case["default"]?>>
			<?php else: ?>
				&nbsp;
			<?php endif; ?>
	          </td>
	       <?php endforeach; ?>
	       </tr>
	     </table>
	</div>
<?php endif; ?>

<br />
<?php if ($this->assezDePa == true && $this->courirPossible == true && $this->estEngage == false) : ?>
<input type='button' class='button1' value='Courir !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_courir");'>
<?php endif ?>
