<div class='comp_titre'>Courir</div>

 <div class='comp_contenu'>
	 <div id='courrir_text' style="display:block"  onClick="javascript:switch2div('courrir_text','courrir_copie');">
		<? include("commun_text_resultat.phtml") ?>
		
		Vous avez couru jusqu'en  : <br />
		x=<?=$this->user->x_hobbit?>, y=<?=$this->user->y_hobbit?> <br /><br />
		
		<? if ($this->palissadeRencontree === true) : ?>
			Vous vous &ecirc;tes arr&ecirc;t&eacute; devant une palissade<br /><br />
		<? endif; ?>
	 
		Cela vous a cout&eacute; <?=$this->nb_pa?> PA<br />
	 </div>
	 
	 <div id='courrir_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
			include("commun_copie_resultat.phtml");
			
			echo "Vous avez r&eacute;ussi votre course jusqu'en  :";
			echo "x=".$this->user->x_hobbit.", y=".$this->user->y_hobbit;
			if ($this->palissadeRencontree === true) {
				echo "Vous vous &ecirc;tes arr&ecirc;t&eacute; devant une palissade";
				echo "
";
			}
			echo "Cela vous a cout&eacute; ".$this->nb_pa." PA";
			?>
		</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('courir_text','courir_copie');">
<? include("commun_fermer.phtml") ?>