<? include("commun_text_resultat.phtml") ?>
		
Vous avez couru jusqu'en  : <br />
x=<?=$this->user->x_braldun?>, y=<?=$this->user->y_braldun?> <br /><br />

<? if ($this->eauPalissadeRencontree === true) : ?>
	Vous vous &ecirc;tes arr&ecirc;t&eacute; devant une palissade ou devant de l'eau profonde.
	
	<? if ($this->estCrevasseEvenement === true) : ?>
	... et ...
	<? endif?>
	<br /><br />
<? endif; ?>

<? if ($this->estCrevasseEvenement === true) : ?>
	<? Zend_Loader::loadClass("Bral_Helper_Crevasse");
	   echo Bral_Helper_Crevasse::afficheResultat($this->user);
	?>
	<br />
<? endif;?>
