<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true): ?>
	Vous avez creusé un tunnel en 
	<?php echo $this->tunnel["x_tunnel"] ?>, <?php echo $this->tunnel["y_tunnel"] ?>.<br /><br />
	Vous vous êtes déplacé dans ce tunnel.<br />
<?php endif; ?>

<?php if ($this->filonsSupprimes > 0) : ?>
	<br /><b>Vous avez détruit <?php echo $this->filonsSupprimes;?> filon<?php if ($this->filonsSupprimes > 1): echo "s"; endif;?> autour de vous.</b>
<?php endif;?>
<br /><br />