 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
 	<?php if ($this->planteOk === true) : ?>
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez cueillir des &eacute;l&eacute;ments d'une plante...<br /><br />
	 
	 <select name="valeur_1" id="valeur_1"  onchange="javascript:if ($('#valeur_1').value==-1){$('#bouton_cueillir.attr('disabled', true) } else {$('#bouton_cueillir').attr('disabled',false) }">
	 	<option value="-1">(Choisissez une plante)</option>
	 	<?php foreach($this->plantes as $p) : ?>
	 		<option value="<?php echo $p["id_plante"]?>"><?php echo $p["categorie"]?> - <?php echo $p["nom_type"]?> (<?php echo $p["id_plante"]?>)</option>
	 	<?php endforeach; ?>
	 </select>
	 <br /><br />
 	 <?php if ($this->charettePleine == true && $this->possedeCharrette == true) : ?>
 		Votre charette ne peut plus contenir de &eacute;l&eacute;ment.<br />
 	 <?php endif;?>
 	 <?php if ($this->labanPlein == true) : ?>
 		Votre laban ne peut plus contenir de &eacute;l&eacute;ment.<br />
 	 <?php endif;?>
 	 <br />
 	 Choisissez la destination :
	 <br />
	 <?$select="";?>
	 <select name="valeur_2" id="valeur_2">
		<?php if ($this->labanPlein == false ) : ?>
			<?php $select = " selected='selected' ";?>
			<option value="2" <?php echo $select;?>>Votre laban (<?php echo $this->nbPossibleDansLabanMax?> &eacute;l&eacute;ment(s) maximum)</option>
		<?php endif; ?>
		<?php if ( $this->possedeCharrette == true && $this->charettePleine == false ) : ?>
			<?php if ($select == "") $select = " selected='selected' "; else $select="";  ?>
			<option value="1" <?php echo $select;?>>Votre charrette (<?php echo $this->nbPossibleDansCharretteMax?> &eacute;l&eacute;ment(s) maximum)</option>		
		<?php endif; ?>
		<option value="3">Le sol</option>
	 </select>
	 <?php else: ?>
	 Il n'y a pas de plante ici...
	 <?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->planteOk === true ) : ?>
<input type='button' class='button1' id='bouton_cueillir' value='Cueillir !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_cueillir");' disabled>
<?php endif ?>
