 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 
 	<? if ($this->poidsPlaceDisponible !== true) : ?>
		Vous n'avez pas assez de place dans votre laban ! <br>
	 <? elseif ($this->planteOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez cueillir des &eacute;l&eacute;ments d'une plante...<br /><br />
	 
	 <select name="valeur_1" id="valeur_1"  onChange="javascript:if ($('valeur_1').value==-1){$('bouton_cueillir').disabled=true } else {$('bouton_cueillir').disabled=false }">
	 	<option value="-1">(Choisis une plante)</option>
	 	<? foreach($this->plantes as $p) : ?>
	 		<option value="<?=$p["id_plante"]?>"><?=$p["categorie"]?> - <?=$p["nom_type"]?> (<?=$p["id_plante"]?>)</option>
	 	<? endforeach; ?>
	 </select>
	 <? else: ?>
	 Il n'y a pas de plante ici...
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->planteOk === true) : ?>
<input type='button' class='button1' id='bouton_cueillir' value='Cueillir !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_cueillir");' disabled>
<? endif ?>
