<div class='comp_titre'>Cuisiner</div>

 <div class='comp_contenu'>
	 <div id='cuisiner_text' style="display:block"  onClick="javascript:switch2div('cuisiner_text','cuisiner_copie');">
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true):
			$s = "";
			if ($this->nbRation > 1) : $s = "s"; endif;
		?>
				Vous avez r&eacute;ussi votre cuisine.<br> 
				Vous avez transform&eacute;
				1 unit&eacute; de viande pr&eacute;par&eacute;e en : <?=$this->nbRation ?> 
				ration<?=$s ?>.
				<br><br>
				<? if ($this->effetRune) :?>
					Une rune que vous portez a eu de l'effet sur le nombre de rations pr&eacute;par&eacute;.
				<? endif; ?>
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='cuisiner_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
		if ($this->okJet1 === true) {
			$s = "";
			if ($this->nbRation > 1) : $s = "s"; endif;
			
			echo "Vous avez r&eacute;ussi votre cuisine.";
			echo "
";
			echo "Vous avez transform&eacute;";
			echo "1 unit&eacute; de viande pr&eacute;par&eacute;e en ";
			echo $this->nbRation ." ration".$s;
			echo "
";
			if ($this->effetRune) {
				echo "Une rune que vous portez a eu de l'effet sur le nombre de rations pr&eacute;par&eacute;.";
			}
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('cuisiner_text','cuisiner_copie');">
<? include("commun_fermer.phtml") ?>