<?php include("commun_text_resultat.phtml") ?>
		
<?php if ($this->okJet1 === true):
	$s = "";
	if ($this->nbAliment > 1) : $s = "s"; endif;
?>
	Vous avez r&eacute;ussi votre cuisine.<br /> <br />
	
	<?php if ($this->estQuintuple === true) : ?>
		Les Braldûns suivants se sont régalés avec votre banquet : <br />
		<?php foreach($this->bralduns as $h) : ?>
			<?php if ($h['id_braldun'] == $this->user->id_braldun) : ?>
				Vous-même
			<?php else: ?>
				<label class='alabel profil' onclick="ouvrirProfilH('<?php echo $h["id_braldun"]?>');" title='Voir le profil' >
			<?php echo $h["prenom_braldun"]?> <?php echo $h["nom_braldun"]?> (n&deg; <?php echo $h["id_braldun"]?>)
			</label>
			<?php endif;?>
			<br />
		<?php endforeach;?>
	<?php else: ?>
		Vous avez préparé <?php echo $this->nbAliment ?> part<?php echo $s?> de 
		<?php echo $this->typeAlimentCourant["nom_type_aliment"]?> de qualit&eacute; <?php echo $this->qualite?> avec pour effet sur la balance de +<?php echo $this->bbdfAliment?> %
		<br /> (n&deg; <?php echo $this->idAliments;?>).
		<br />
		<?php if ($this->nbAlimentATerre > 0): ?>
			Faute de place, <?php echo $this->nbAlimentATerre ?> part<?php if ($this->nbAlimentATerre > 1): echo "s sont tomb&eacute;s à terre"; else: " est tomb&eacute; à terre"; endif?>.
		<?php endif;?>
		<br /><br />
		
		<?php if ($this->effetRune) :?>
			Une rune que vous portez a eu de l'effet sur le nombre d'aliment pr&eacute;par&eacute; : + 1 part.
		<?php endif; ?>
	<?php endif;?>
	
	<?php if ($this->recetteAvecPotion === true) : ?>
		 La potion utilisée (potion n°<?php echo $this->idPotion?>) sera appliquée lors de la consommation de la préparation.<br />
	<?php endif;?>
<?php else: ?>
	Vous avez manqu&eacute; votre cuisine. Vous avez perdu la moitié des ingrédients nécessaires.<br />
<?php endif; ?>