 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->cuisinerNbViandeOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez cuisiner : <br />
	 	Transformer <?=$this->nbViandePreparee ?> unit&eacute;<? if ($this->nbViandePreparee) : echo "s"; endif;?> de viande pr&eacute;par&eacute;e en ration(s).
	 <? else: ?>
		 Vous n'avez pas assez de viande pr&eacute;par&eacute;e pour cuisiner.<br />
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->cuisinerLieuOk === true && $this->cuisinerNbViandeOk === true) : ?>
<input type='button' class='button1' id='bouton_cuisiner' value='Cuisiner !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_cuisiner");'>
<? endif ?>
