 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	Pour <?=$this->nb_pa ?> PA, vous pouvez d&eacute;busquer du gibier. <br /><br />

	<? if ($this->assezDePa !== true) : ?>
		Vous n'avez pas assez de PA ! <br />
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true) : ?>
<input type='button' class='button1' id='bouton_debusquer' value='D&eacute;busquer !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_debusquer");'>
<? endif ?>