 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	Votre Date Limite d'Action est actuellement fix&eacute;e &agrave; : <br />
 	<?=$this->dlaActuelle?><br />
 	<br />Vous pouvez la d&eacute;caler si vous souhaitez...<br /><br />
 	
 	Le d&eacute;calage s'exprime en heures et en minutes. <br />
 	Choississez le nombre d'heures et / ou minutes de votre décalage.<br /><br />
   <table width='300px' align='center'>
    <th class='comp_titre'>Heures</th>
    <th class='comp_titre'>Minutes</th>
   	<tr>
   		<td>
	   		<select id='valeur_1' name='valeur_1' onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1 || ($('valeur_1').value==0 && $('valeur_2').value==0)){$('bouton_decalerdla').disabled=true } else {$('bouton_decalerdla').disabled=false }">
			<option value='-1'>(Choisis)</option>
			<? foreach ($this->tabHeures as $h): ?>
			<option value='<?=$h?>'><?=$h?></option>
			<? endforeach; ?>
			</select>
   		</td>
   			<select id='valeur_2' name='valeur_2' onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1 || ($('valeur_1').value==0 && $('valeur_2').value==0)){$('bouton_decalerdla').disabled=true } else {$('bouton_decalerdla').disabled=false }">
			<option value='-1'>(Choisis)</option>
			<? foreach ($this->tabMinutes as $m): ?>
			<option value='<?=$m?>'><?=$m?></option>
			<? endforeach; ?>
			</select>
   		<td>
   		</td>
   	</tr>
   </table>
 </div>
<br />
<input type='button' class='button1' id='bouton_decalerdla' value='D&eacute;caler !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_decalerdla");' disabled>
