<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; d&eacute;couper <?=$this->nbRondins ?> <? if ($this->nbRondins > 1) : $s = 's';  else: $s = ''; endif; ?> rondin<?=$s ?> en 
	<? if ($this->quantitePlanches > 1): $s='s'; else: $s=""; endif; ?>
	<?=$this->quantitePlanches  ?> planche<?=$s ?>.
	<br />
<? else: ?>
	Vous avez manqu&eacute; votre d&eacute;coupe.<br />
<? endif; ?>