 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->decouperEchoppeOk === true && $this->decouperPlancheOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez decouper <?=$this->nbRondins ?> <? if ($this->nbRondins > 1) : $s = 's';  else: $s = ''; endif; ?> rondin<?=$s ?> en planche(s) ...<br />
	<? elseif ($this->decouperEchoppeOk == false) : ?>
		Vous ne pouvez d&eacute;couper que dans une de vos &eacute;choppes de Menuisier.
	<? else: ?>
		Vous n'avez pas assez de rondins pour d&eacute;couper
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->decouperEchoppeOk === true && $this->decouperPlancheOk) : ?>
<input type='button' class='button1' id='bouton_decouper' value='D&eacute;couper !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_decouper");'/>
<? endif ?>
