 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
	 <?php if ($this->nbRuneOk === true) : ?>
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez demander ou annuler l'identification d'une rune par un autre Braldûn.<br /><br />
	 
	 En cas de demande d'identification, le Braldûn sélectionné pourra choisir votre rune
	 dans la liste des runes qui lui seront proposées dans sa compétence "Identification des Runes".
	 <br /><br />
	 Vous n'avez donc pas besoin de lui donner votre rune, il faut juste qu'il soit sur la 
	 même case que vous.
	 <br /><br />
	 Choississez la rune : <br />
	 <?php $js='if ($("#valeur_1").val() ==-1){$("#bouton_demanderidentificationrune.attr("disabled", true) } else {$("#bouton_demanderidentificationrune").attr("disabled",false) }';?>
	 <select name="valeur_1" id="valeur_1"  onchange='javascript:<?php echo $js?>'>
	 	<option value="-1">(Choisissez une rune)</option>
	 	<?php foreach($this->runes as $r) : ?>
	 		<option value="<?php echo $r["id_rune"]?>">Rune non identifi&eacute;e n&deg; <?php echo $r["id_rune"]?>
	 		<?php if ($r["id_identification_braldun"] != null) : ?>
	 			Identifiable par <?php echo $r["prenom_identification_braldun"] ?> <?php echo $r["nom_identification_braldun"] ?> (<?php echo $r["id_identification_braldun"] ?>)
	 		<?php endif;?>
	 		</option>
	 	<?php endforeach; ?>
	 </select>
	 
	 <br /><br /><br />
	 Braldûn pouvant identifier cette rune. <br />
	 Laissez vide pour rendre la rune identifiable que par vous même. 
	 <input type="hidden" name="valeur_2" id="valeur_2" value="-1"/>
	 <div id="div_braldun">
		<input type="text" name="recherche_valeur_2_dest" size='30' id="recherche_valeur_2_dest" value="Entrez un nom" onFocus="if(this.value=='Entrez un nom'){this.value='';};activerRechercheBraldunIdentificationRune('valeur_2_dest');" />
		<input type="hidden" name="recherche_valeur_2_dest_actif" id="recherche_valeur_2_dest_actif" value="0" />
		<div class="recherche" id="recherche_valeur_2_dest_update" ></div> <img src="<?php echo $this->config->url->static?>/images/loupe.gif" />
	   	<span id="indicateur_recherche_valeur_2_dest" style="display: none"><img src="<?php echo $this->config->url->static?>/images/wait.gif" alt="Recherche..." /></span>
	   </div>
   				
	 <?php else: ?>
	Vous n'avez aucune rune &agrave; identifier...
	 <?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->nbRuneOk === true) : ?>
<input type='button' class='button1' id='bouton_demanderidentificationrune' value="Valider" onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_demandeidentificationrune");' disabled>
<?php endif ?>
