<?php include("commun_text_resultat.phtml") ?>

La rune n&deg; <?php echo $this->rune["id_rune"] ?> est maintenant identifiable 

<?php if ($this->rune["id_fk_braldun_identification_laban_rune"] != null) : ?>
	par <?php echo $this->rune["prenom_braldun"]?> <?php echo $this->rune["nom_braldun"]?> (<?php echo $this->rune["id_braldun"]?>),
	qui a reçu un message l'informant de cette demande.
<?php else: ?>
	que par vous-même.
<?php endif;?>

<br />
