 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 
 <? if ($this->poidsPlaceDisponible !== true) : ?>
	Vous n'avez pas assez de place dans votre laban ! <br>
 <? else : ?>
	<? if ($this->nCadavres == 0): ?>
 		Il n'y a pas de monstre &agrave; d&eacute;piauter ici...
 	<? else: ?>
 	<br />
 		Pour <?=$this->nb_pa?> PA, vous pouvez d&eacute;piauter :<br /><br />
		<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_depiauter').disabled=true } else {$('bouton_depiauter').disabled=false }">
		<option value='-1'>(Choisis un monstre)</option>
		<? foreach ($this->tabCadavres as $m) : ?>
		<option value="<?=$m["id_monstre"]?>"><? if ($m["est_gibier"]): ?> Gibier : <? endif;?><?=htmlspecialchars($m["nom_monstre"])?> <?=htmlspecialchars($m["taille_monstre"])?>  (<?=$m["id_monstre"]?>)</option>
		<? endforeach; ?>
		</select><br />
 	<? endif; ?>
 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->nCadavres > 0) : ?>
<input type='button' class='button1' id='bouton_depiauter' value='D&eacute;piauter !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_depiauter");' disabled>
<? endif ?>
