<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true):
	$s = "";
	if ($this->nbPeau > 1) : $s = "s"; endif;
?>
	Vous avez d&eacute;piaut&eacute; <?=$this->nbPeau ?> unit&eacute;<?=$s ?> de peau.
	
	<? if ($this->nbViande >= 1) :?>
	<br />
	Le cadavre &eacute;tait un gibier, vous avez &eacute;galement r&eacute;cup&eacute;r&eacute;  <?=$this->nbViande ?> unit&eacute;<? if ($this->nbViande > 1) : echo "s"; endif; ?> de viande.
	<? else: ?>
	<br>
	Vous n'avez pas r&eacute;cup&eacute;r&eacute; de viande.
	<? endif;?>
	
	<br /><br />
	
	<? if ($this->limitationLaban == true) : ?>
		Vous n'avez pas eu assez de place dans votre laban pour contenir tout ce que 
		vous avez dépiauté.
		<br><br>
	<? endif;?>
	
	<? if ($this->effetRune) :?>
		Une rune que vous portez a eu de l'effet sur la quantit&eacute; de peau d&eacute;piaut&eacutee;.
	<? endif; ?>
<? endif; ?>