<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
<div class='comp_contenu'>
<? if ($this->nCadavres == 0): ?>
 	Il n'y a pas de monstre &agrave; d&eacute;piauter ici...
<? else: ?>
<br />
 	Pour <?=$this->nb_pa?> PA, vous pouvez d&eacute;piauter :<br /><br />
	<select name='valeur_1' id="valeur_1" onchange="_get_('/competences/doaction?caction=ask_competence_depiauter&monstre='+this.value);">
	<option value='-1'>(Choisissez un monstre)</option>
	<? foreach ($this->tabCadavres as $m) : ?>
		<option value="<?=$m["id_monstre"]?>" <? if ($m["id_monstre"] == $this->id_monstre_courant || count ($this->tabCadavres) == 1): ?> selected <? endif;?>><? if ($m["est_gibier"]): ?> Gibier : <? endif;?><?=htmlspecialchars($m["nom_monstre"])?> <?=htmlspecialchars($m["taille_monstre"])?>  (<?=$m["id_monstre"]?>)</option>
	<? endforeach; ?>
	</select>
	<br /><br />
	<? if ($this->id_monstre_courant != "" || count ($this->tabCadavres) == 1): ?>
	 	 <? if ($this->charettePleine == true && $this->possedeCharrette == true) : ?>
	 		Votre charette ne peut plus contenir de viande ou de peau.<br /><br />
	 	 <? endif;?>
	 	 <? if ($this->labanPlein == true) : ?>
	 		Votre laban ne peut plus contenir de viande ou de peau.<br /><br />
	 	 <? endif;?>
	 	 Choisissez la destination :
		 <br /><br />
		 <?$select="";?>
		 <select name="valeur_2" id="valeur_2">
			<? if ($this->possedeCharrette == true && $this->charettePleine == false ) : ?>
				<? $select = " selected='selected' ";?>
				<option value="1" <?=$select;?>>Votre charrette (<?=$this->nbPossibleDansCharretteMax?> élément(s) maximum)</option>
			<? endif; ?>
			<? if ( $this->labanPlein == false ) : ?>
				<? if ($select == "") $select = " selected='selected' "; else $select="";  ?>
					<option value="2" <?=$select;?>>Votre laban (<?=$this->nbPossibleDansLabanMax?> élément(s) maximum)</option>
			<? endif; ?>
			<option value="3">Le sol</option>
		 </select>
	<? endif;?>
	<? if ($this->gibier == true) : ?>
		<br /><br />
		En cas de surpoids, préférez-vous garder :
	 	<br /><br />
	 	<select name="valeur_3" id="valeur_3">
	 		<option value="1">La peau</option>
	 	 	<option value="2">La viande</option>
	 	</select>
	<? else :?>
	 	<input type="hidden" name="valeur_3" id="valeur_3" value="1">
	<? endif; ?>
	<br />
<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->nCadavres > 0) : ?>
	<input type='button' class='button1' id='bouton_depiauter' value='D&eacute;piauter !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_depiauter");' <?if ( ($this->id_monstre_courant == "" || $this->id_monstre_courant == -1) && count ($this->tabCadavres) > 1) : ?>disabled<?endif;?>>
<? endif ?>
