<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
<div class='comp_contenu'>
<?php if ($this->nCadavres == 0): ?>
 	Il n'y a pas de monstre &agrave; d&eacute;piauter ici...
<?php else: ?>
<br />
 	Pour <?php echo $this->nb_pa?> PA, vous pouvez d&eacute;piauter :<br /><br />
	<select name='valeur_1' id="valeur_1" onchange="_get_('/competences/doaction?caction=ask_competence_depiauter&monstre='+this.value);">
	<option value='-1'>(Choisissez un monstre)</option>
	<?php foreach ($this->tabCadavres as $m) : ?>
		<option value="<?php echo $m["id_monstre"]?>" <?php if ($m["id_monstre"] == $this->id_monstre_courant || count ($this->tabCadavres) == 1): ?> selected <?php endif;?>><?php if ($m["est_gibier"]): ?> Gibier : <?php endif;?><?php echo htmlspecialchars($m["nom_monstre"])?> <?php echo htmlspecialchars($m["taille_monstre"])?>  (<?php echo $m["id_monstre"]?>)</option>
	<?php endforeach; ?>
	</select>
	<br /><br />
	<?php if ($this->id_monstre_courant != "" || count ($this->tabCadavres) == 1): ?>
	 	 <?php if ($this->charettePleine == true && $this->possedeCharrette == true) : ?>
	 		Votre charette ne peut plus contenir de viande ou de peau.<br /><br />
	 	 <?php endif;?>
	 	 <?php if ($this->labanPlein == true) : ?>
	 		Votre laban ne peut plus contenir de viande ou de peau.<br /><br />
	 	 <?php endif;?>
	 	 Choisissez la destination :
		 <br /><br />
		 <?$select="";?>
		 <select name="valeur_2" id="valeur_2">
			<?php if ($this->possedeCharrette == true && $this->charettePleine == false ) : ?>
				<?php $select = " selected='selected' ";?>
				<option value="1" <?php echo $select;?>>Votre charrette (<?php echo $this->nbPossibleDansCharretteMax?> élément(s) maximum)</option>
			<?php endif; ?>
			<?php if ( $this->labanPlein == false ) : ?>
				<?php if ($select == "") $select = " selected='selected' "; else $select="";  ?>
					<option value="2" <?php echo $select;?>>Votre laban (<?php echo $this->nbPossibleDansLabanMax?> élément(s) maximum)</option>
			<?php endif; ?>
			<option value="3">Le sol</option>
		 </select>
	<?php endif;?>
	<?php if ($this->gibier == true) : ?>
		<br /><br />
		En cas de surpoids, préférez-vous garder :
	 	<br /><br />
	 	<select name="valeur_3" id="valeur_3">
	 		<option value="1">La peau</option>
	 	 	<option value="2">La viande</option>
	 	</select>
	<?php else :?>
	 	<input type="hidden" name="valeur_3" id="valeur_3" value="1">
	<?php endif; ?>
	<br />
<?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->nCadavres > 0) : ?>
	<input type='button' class='button1' id='bouton_depiauter' value='D&eacute;piauter !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_depiauter");' <?php if ( ($this->id_monstre_courant == "" || $this->id_monstre_courant == -1) && count ($this->tabCadavres) > 1) : ?>disabled<?endif;?>>
<?php endif ?>
