<div class='comp_titre'>D&eacute;piauter</div>

 <div class='comp_contenu'>
	 <div id='depiauter_text' style="display:block"  onClick="javascript:switch2div('depiauter_text','depiauter_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true):
			$s = "";
			if ($this->nbPeau > 1) : $s = "s"; endif;
		?>
			Vous avez d&eacute;piaut&eacute; <?=$this->nbPeau ?> unit&eacute;<?=$s ?> de peau. <br>
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='depiauter_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
		if ($this->okJet1 === true) {
			$s = "";
			if ($this->nbViande > 1) : $s = "s"; endif;
			echo " Vous avez d&eacute;piaut&eacute; ".$this->nbPeau." unit&eacute;".$s." de peau";
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('depiauter_text','depiauter_copie');">
<? include("commun_fermer.phtml") ?>