 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='5'>
 <div class='comp_contenu'>
	 
	 Pour <?=$this->nb_pa ?> PA, vous pouvez d&eacute;poser des objets sur la case. <br /><br />
	 	
	 <select name="valeur_1" id="valeur_1"  onChange="if ($('bouton_deposer')) {$('bouton_deposer').disabled=true} ;_get_('/competences/doaction?caction=ask_competence_deposer&valeur_1='+this.value);">
	 	<option value="-1">(Choisis un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->typeElements as $t) : ?>
	 		<option value="<?=$t["id_type_element"]?>" <? if ($t["selected"] == $t["id_type_element"]): echo "selected"; endif;?>><?=htmlspecialchars($t["nom_element"])?></option>
	 	<? endforeach; ?>
	 </select>
	 <br /><br />
	 
	 <? if ($this->type != null) : ?>
	 	<? include("deposer/" . $this->type . ".phtml"); ?>
		<? if ($this->deposerOk === false) : ?>
		 <br />
		 Vous n'avez rien &agrave; d&eacute;poser.
		<? endif; ?>
	 <? endif ?>
	 
</div>

<br />
<?php if ($this->assezDePa == true && $this->deposerOk === true) : ?>
<input type='button' class='button1' id='bouton_deposer' value='D&eacute;poser !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_deposer");' disabled>
<? endif ?>
