<?php include("commun_text_resultat.phtml") ?>
 
 Votre jet de sagesse : <?php echo $this->jetBraldun?><br />
 
 Jet de sagesse des alentours : <?php echo $this->sommeJets?><br /><br />

 <?php if ($this->dissuaderOk === true) : ?>
 Vous avez réussi votre dissuasion, vous êtes maintenant intangible jusqu'à la fin de votre tour (prochaine activation).
 <?php else: ?>
 Vous avez raté votre dissuasion (votre jet &lt; jet des alentours).
 <?php endif;?>
 <br /><br />