 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=($this->n_hobbits*2)?>'>
 <div class='comp_contenu'>
 	
 	Castars : <input type='text' id='cagnottecastars' name='cagnottecastars' value='<?=$this->user->castars_hobbit?>' size='4' disabled> Castar<? if ($this->user->castars_hobbit > 1): echo "s"; endif;?><br /><br />
 	<input type='hidden' id='cagnottecastars_origine' name='cagnottecastars_origine' value='<?=$this->user->castars_hobbit?>'>

	<? if ($this->tabHobbits != null) : ?> 	
	 	<? if ($this->estMaxHobbits === true): ?>
	 		Il y a plus de <?=$this->config->game->competence->distribuerpx->nb_max_hobbit?> hobbits dans votre vue<br /><br />
	 		Seuls les <?=$this->config->game->competence->distribuerpx->nb_max_hobbit?> hobbits les plus proches<br /> sont disponibles pour recevoir des castars<br /><br />
	 	<? endif; ?>
	
		<table align="center">
	 	<? $i=0;
	 	foreach ($this->tabHobbits as $h) : 
	 		$i = $i+2;
	 	?>
	 		<tr>
	 			<td>
	 			<input type='hidden' id='valeur_<?=($i-1)?>' name='valeur_<?=($i-1)?>' value='<?=$h["id_hobbit"]?>'>
	 			<?=htmlspecialchars($h["prenom_hobbit"])?> <?=htmlspecialchars($h["nom_hobbit"])?> (<?=$h["id_hobbit"]?>)
	 			</td>
	 			<td>
	 				<input type='text' id='valeur_<?=$i?>' name='valeur_<?=$i?>' value='0' size='3' maxlength='3' onkeypress="chiffres(event);" onkeyup="if (this.value==''){this.value=0;} var n=0;for (i = 2; i<=$('nb_valeurs').value ; i=i+2) {n=parseInt(n)+parseInt($('valeur_'+i).value); } if ($('cagnottecastars_origine').value < n){n=parseInt(n)-parseInt(this.value); this.value=0 ;} $('cagnottecastars').value=parseInt($('cagnottecastars_origine').value) - parseInt(n); ">
	 			</td>
	 		</tr>
	 	<? endforeach; ?>
	 	</table>
	 <? else: ?>
	 	Il n'y a personne sur votre case pour recevoir des castars.
	 <? endif;?>
 </div>
<br />
<? if ($this->tabHobbits != null) : ?> 	
<input type='button' class='button1' id='bouton_distribuercastars' value='Distribuer !' onClick="if (parseInt($('cagnottecastars_origine').value) > parseInt($('cagnottecastars').value)) {this.disabled=true;_get_('/competences/doaction?caction=do_competence_distribuercastars');} else {alert('Il n\'y a rien &agrave; distribuer');}">
<? endif; ?>