<div class='comp_titre'>Distribuer des PX</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?=($this->n_hobbits*2)?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	Cagnotte : <input type='text' id='cagnotte' name='cagnotte' value='<?=$this->user->px_commun_hobbit?>' size='4' disabled> PX<br><br>
 	<input type='hidden' id='cagnotte_origine' name='cagnotte_origine' value='<?=$this->user->px_commun_hobbit?>'>
 	
 	<? if ($this->estMaxHobbits === true): ?>
 		Il y a plus de <?=$this->config->game->competence->distribuerpx->nb_max_hobbit?> hobbits dans votre vue<br><br>
 		Seuls les <?=$this->config->game->competence->distribuerpx->nb_max_hobbit?> hobbits les plus proches<br> sont disponibles pour recevoir des px<br><br>
 	<? endif; ?>

	<table>
 	<? $i=0;
 	foreach ($this->tabHobbits as $h) : 
 		$i = $i+2;
 	?>
 		<tr>
 			<td>
 			<input type='hidden' id='valeur_<?=($i-1)?>' name='valeur_<?=($i-1)?>' value='<?=$h["id_hobbit"]?>'>
 			<?=$h["nom_hobbit"]?> (<?=$h["id_hobbit"]?>)
 			</td>
 			<td>
 				<input type='text' id='valeur_<?=$i?>' name='valeur_<?=$i?>' value='0' size='3' maxlength='3' onkeypress="chiffres(event);" onChange="if (this.value==''){this.value=0;} var n=0;for (i = 2; i<=$('nb_valeurs').value ; i=i+2) {n=parseInt(n)+parseInt($('valeur_'+i).value); } if ($('cagnotte_origine').value < n){n=parseInt(n)-parseInt(this.value); this.value=0 ;} $('cagnotte').value=parseInt($('cagnotte_origine').value) - parseInt(n); ">
 			</td>
 		</tr>
 	<? endforeach; ?>
 	</table>
 </div>
 </form>
<br>
<input type='button' class='button1' id='bouton_distribuer' value='Distribuer !' onClick="if (parseInt($('cagnotte_origine').value) > parseInt($('cagnotte').value)) {_get_('/competences/DoAction?caction=do_competence_distribuerpx');} else {alert('Il n\'y a rien à distribuer');}">
<? include("commun_fermer.phtml") ?>