<?php include("commun_text_resultat.phtml") ?>
Vous avez distribu&eacute; <?php echo $this->totalDistribution?> castar<?php if ($this->totalDistribution > 1) : echo "s" ; endif;?>.<br /><br />
<table>
 <?php foreach ($this->tabAffiche as $t):?>
 	<tr>
 		<td>
 		<?php echo htmlspecialchars($t["nom_braldun"])?> (<?php echo $t["id_braldun"]?>)
 		</td>
 		<td>
 		<?php echo $t["castars_recus"]?> 
 		Castar<?php if ($t["castars_recus"] > 1): echo "s"; endif;?><?php if ($t["castars_recus_terre"] > 0): ?>, dont <?php echo $t["castars_recus_terre"]?> tomb&eacute;<?php if ($t["castars_recus_terre"] > 1): echo "s"; endif;?> &agrave; terre.
 		<?php endif;?>
 		</td>
 	</tr>
 <?php endforeach; ?>
 </table>