<div class='comp_titre'>Distribuer des PX</div>
 <div class='comp_contenu'>
	 <div id='distribuerpx_text' style="display:block"  onClick="javascript:switch2div('distribuerpx_text','distribuerpx_copie');">
		
	 </div>
	 
	 <div id='distribuerpx_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		?></textarea>
	</div>
 </div>

<input type='button' value='Copier' onClick="javascript:switch2div('distribuerpx_text','distribuerpx_copie');">
<input type='button' value='Fermer' onClick='_get_("/interface/clear");'>