 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo ($this->n_bralduns*2)?>'>
 <div class='comp_contenu'>
 	
 	Castars : <input type='text' id='cagnottecastars' name='cagnottecastars' value='<?php echo $this->user->castars_braldun?>' size='4' disabled> Castar<?php if ($this->user->castars_braldun > 1): echo "s"; endif;?><br /><br />
 	<input type='hidden' id='cagnottecastars_origine' name='cagnottecastars_origine' value='<?php echo $this->user->castars_braldun?>'>

	<?php if ($this->tabBralduns != null) : ?> 	
	 	<?php if ($this->estMaxBralduns === true): ?>
	 		Il y a plus de <?php echo $this->config->game->competence->distribuerpx->nb_max_braldun?> Braldûns sur votre case<br /><br />
	 		Seuls <?php echo $this->config->game->competence->distribuerpx->nb_max_braldun?> Braldûns sont disponibles pour recevoir des castars<br /><br />
	 	<?php endif; ?>
	
		<table align="center">
	 	<?php $i=0;
	 	foreach ($this->tabBralduns as $h) : 
	 		$i = $i+2;
	 	?>
	 		<tr>
	 			<td>
	 			<input type='hidden' id='valeur_<?php echo ($i-1)?>' name='valeur_<?php echo ($i-1)?>' value='<?php echo $h["id_braldun"]?>'>
	 			<?php echo htmlspecialchars($h["prenom_braldun"])?> <?php echo htmlspecialchars($h["nom_braldun"])?> (<?php echo $h["id_braldun"]?>)
	 			</td>
	 			<td>
	 				<input type='text' id='valeur_<?php echo $i?>' name='valeur_<?php echo $i?>' value='0' size='5' maxlength='5' onkeypress="chiffres(event);" onblur="if (this.value==''){this.value=0;}" onkeyup="if (this.value==''){this.value='';} var n=0;for (i = 2; i<=$('#nb_valeurs').val() ; i=i+2) {if ($('#valeur_'+i).value != '') {n=parseInt(n * 1)+parseInt($('#valeur_'+i).value * 1); }} if ($('#cagnottecastars_origine').val() < n){n=parseInt(n * 1)-parseInt(this.value * 1); this.value=0 ;} $('#cagnottecastars').val(parseInt($('#cagnottecastars_origine').val() * 1) - parseInt(n * 1)); ">
	 			</td>
	 		</tr>
	 	<?php endforeach; ?>
	 	</table>
	 <?php else: ?>
	 	Il n'y a personne sur votre case pour recevoir des castars.
	 <?php endif;?>
 </div>
<br />
<?php if ($this->tabBralduns != null) : ?> 	
<input type='button' class='button1' id='bouton_distribuercastars' value='Distribuer !' onclick="if (parseInt($('cagnottecastars_origine').val() * 1) > parseInt($('#cagnottecastars').val() * 1)) {this.disabled=true;_get_('/competences/doaction?caction=do_competence_distribuercastars');} else {alert('Il n\'y a rien &agrave; distribuer');}">
<?php endif; ?>