 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<? if ($this->possedeBallon !== true) :?>
 		Vous n'avez pas le ballon !<br><br>
	<? else: ?>
	 	<? if ($this->nHobbits == 0): ?>
	 		Il n'y a pas de hobbit de votre &eacute;quipe sur votre case<br />
	 	<? else: ?>
	 		Pour <?=$this->nb_pa?> PA, vous pouvez donner le ballon.<br /><br />
			
	 		<? if ($this->nHobbits > 0): ?>
	 		 Hobbit destinataire : <br />
	 			<select name='valeur_1' id="valeur_1" onChange="javascript:if (this.value==-1){$('bouton_donnerballon').disabled=true } else {$('bouton_donnerballon').disabled=false }">
					<option value='-1'>(Choisissez un hobbit)</option>
	 				<? foreach ($this->tabHobbits as $h) : ?>
					<option value="<?=$h["id_hobbit"]?>"><?=$h["prenom_hobbit"]?> <?=$h["nom_hobbit"]?> (<?=$h["id_hobbit"]?>)</option>
					<? endforeach; ?>
				</select><br /><br />
			<? endif;?>
		<? endif; ?>
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->possedeBallon === true) : ?>
<input type='button' class='button1' value='Donner le ballon !' id='bouton_donnerballon' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_donnerballon");' disabled>
<? endif ?>
