 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	<?php if ($this->possedeBallon !== true) :?>
 		Vous n'avez pas le ballon !<br /><br />
	<?php else: ?>
	 	<?php if ($this->nBralduns == 0): ?>
	 		Il n'y a pas de Braldûn de votre &eacute;quipe sur votre case<br />
	 	<?php else: ?>
	 		Pour <?php echo $this->nb_pa?> PA, vous pouvez donner le ballon.<br /><br />
			
	 		<?php if ($this->nBralduns > 0): ?>
	 		 Braldûn destinataire : <br />
	 			<select name='valeur_1' id="valeur_1" onchange="javascript:if (this.value==-1){$('#bouton_donnerballon').attr('disabled', true) } else {$('#bouton_donnerballon').attr('disabled',false) }">
					<option value='-1'>(Choisissez un Braldûn)</option>
	 				<?php foreach ($this->tabBralduns as $h) : ?>
					<option value="<?php echo $h["id_braldun"]?>"><?php echo $h["prenom_braldun"]?> <?php echo $h["nom_braldun"]?> (<?php echo $h["id_braldun"]?>)</option>
					<?php endforeach; ?>
				</select><br /><br />
			<?php endif;?>
		<?php endif; ?>
	<?php endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->possedeBallon === true) : ?>
<input type='button' class='button' value='Donner le ballon !' id='bouton_donnerballon' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_donnerballon");' disabled>
<?php endif ?>
