<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; &eacute;laborer une potion : 
	<br />
	<?=htmlspecialchars($this->typePotionCourante["nom_type_potion"]) ?>, de qualit&eacute; <?=$this->qualite ?>
	et de niveau <?=$this->niveau ?>.
	<br /><br />
	<? if ($this->effetRune) :?>
		Une rune que vous portez a eu de l'effet sur la qualit&eacute; de cette potion.
	<? endif; ?>
<? else: ?>
	Vous avez manqu&eacute; votre potion. <br/>
	La moti&eacute; des composants sont d&eacute;truits.<br />
<? endif; ?>