<div class='comp_titre'>&Eacute;laborer</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->elaborerEchoppeOk === true) : ?>
<input type='button' class='button1' id='bouton_elaborer' value='Concocter !' onClick='this.disabled=true;_get_("/competences/DoAction?caction=do_competence_elaborer");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>