<?php include("commun_text_resultat.phtml") ?>

Vous avez entretenu la zone x:<?php echo $this->etatZone["x"]?> y:<?php echo $this->etatZone["y"]?>. <br /><br />

<?php if ($this->etatZone["etat"] == ChampTaupe::ETAT_ENTRETENU) : ?>
	Vous n'avez pas trouvé de taupe à cet endroit.
<?php else: ?>
	Vous avez trouvé une partie de taupe de taille <?php echo $this->etatZone["taille"] ?> ! <br /><br />
	
	<?php if ($this->taupeDetruite) : ?>
		La taupe est occise.
	<?php else: ?>
		Consultez votre champ pour voir ce qu'il reste à trouver de cette taupe pour l'éliminer complètement.<br />
	<?php endif;?>
<?php endif?>
<br /><br />