 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	Pour <?=$this->nb_pa ?> PA, vous pouvez entretenir un de vos champs.<br /><br />
 	
	 <? if ($this->entretenirChampOk !== true) : ?>
	 	Vous ne pouvez entretenir un de vos champs quand étant dessus et il faut qu'il soit semé au préalable.
	 
	 <? else: ?>
	 	
	 	Vous pouvez directement cliquer sur la case de votre champ à entretenir.<br /><br />
	 	
	 	Choisissez la case à entretenir : <br />  
	 	<select name="valeur_1" id="valeur_1" onchange="if (this.value == -1) {$('bouton_entretenir').disabled = true;}else {$('bouton_entretenir').disabled = false;}">
	 		<option value="-1">(Choisissez une case)</option>
		 <? foreach($this->positions as $k => $v) : ?>
			 <option value="<?=$k ?>" <? if ($v["possible"] == false) : echo 'disabled'; endif;?> <?=$v["selected"]?>> x:<?=$v["x"]?> y:<?=$v["y"]?></option>
		 
		 <? endforeach?>
		 </select>
	 <? endif; ?>
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->entretenirChampOk === true) : ?>
<input type='button' class='button1' id='bouton_entretenir' value='Entretenir !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_entretenir");'>
<? endif ?>
