<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>

	Vous avez entretenu la zone x:<?=$this->etatZone["x"]?> y:<?=$this->etatZone["y"]?>. <br><br>
	
	<? if ($this->etatZone["etat"] == ChampTaupe::ETAT_ENTRETENU) : ?>
		Vous n'avez pas trouvé de taupe à cet endroit.
	<? else: ?>
		Vous avez trouvé une partie de taupe de taille <?=$this->etatZone["taille"] ?> ! <br><br>
		
		Consultez votre champ pour voir ce qu'il reste à trouver de cette taupe pour l'éliminer complètement.<br>
	<? endif?>
<? endif; ?>
<br><br>