<? include("commun_text_resultat.phtml") ?>

<? if ($this->filonOk !== true): ?>
	Il n'y a pas de minerai ici... Il faut sonder !
<? elseif ($this->okJet1 === true):?>
	<? if ($this->minerai["quantite_extraite"] < 1) : ?>
		Vous n'avez rien extrait  
		&agrave; cause de vos malus importants en Force.<br> <br />
	<? else: ?>
		Vous avez extrait avec succ&egrave;s 
		<?=$this->minerai["quantite_extraite"]?> morceau<?if($this->minerai["quantite_extraite"] > 1): echo "x"; endif; ?>
		de <?=$this->minerai["nom_type"]?><br />
		<? if ($this->filonDetruit === true): ?>
			Pfiou, il n'y a plus rien dans le filon...
		<? endif; ?>
		<br /><br />
		<? if ($this->effetRune) :?>
			Une rune que vous portez a eu de l'effet sur la quantit&eacute; de minerai extrait.
		<? endif; ?>
	<? endif; ?>
<? else :  ?>
	<? if ($this->filonDetruit === true) : ?>
		Vous avez tout g&acirc;ch&eacute; ! Les derniers fragments de <?=htmlspecialchars($this->minerai["nom_type"])?>
		tombent en miettes dans vos mains et le filon est d&eacute;truit !
	<? else: ?>
		Des fragments de <?=htmlspecialchars($this->minerai["nom_type"])?> tombent en miettes dans vos mains et sont d&eacute;truits.
	<? endif; ?>
<? endif; ?>