<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true):?>
	<? if ($this->filonOk === true): ?>
		Vous avez extrait avec succ&egrave;s 
		<?=$this->minerai["quantite_extraite"]?> morceau<?if($this->minerai["quantite_extraite"] > 0): echo "x"; endif; ?>
		de <?=$this->minerai["nom_type"]?><br />
		<? if ($this->filonDetruit === true): ?>
			Pfiou, il n'y a plus rien dans le filon...
		<? endif; ?>
		<br /><br />
		<? if ($this->effetRune) :?>
			Une rune que vous portez a eu de l'effet sur la quantit&eacute; de minerai extrait.
		<? endif; ?>
	<? else: ?>
		Il n'y a pas de minerai ici... Il faut sonder !
	<? endif; ?>
<? else :  ?>
	<? if ($this->filonDetruit === true) : ?>
		Vous avez tout g&acirc;ch&eacute; ! Les derniers fragments de <?=htmlentities($this->minerai["nom_type"])?>
		tombent en miettes dans vos mains et le filon est d&eacute;truit !
	<? else: ?>
		Des fragments de <?=$this->minerai["nom_type"]?> tombent en miettes dans vos mains et sont d&eacute;truits.
	<? endif; ?>
<? endif; ?>