<div class='comp_titre'>Extaire un minerai</div>

 <div class='comp_contenu'>
	 <div id='extraire_text' style="display:block"  onClick="javascript:switch2div('extraire_text','extraire_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true):?>
			<? if ($this->filonOk === true): ?>
				Vous avez extrait avec succ&egrave;s 
				<?=$this->minerai["quantite_extraite"]?> morceau<?if($this->minerai["quantite_extraite"] > 0): echo "x"; endif; ?>
				de <?=$this->minerai["nom_type"]?><br>
				<? if ($this->filonDetruit === true): ?>
					Pfiou, il n'y a plus rien dans le filon...
				<? endif; ?>
				<br><br>
				<? if ($this->effetRune) :?>
					Une rune que vous portez a eu de l'effet sur la quantit&eacute; de minerai extrait.
				<? endif; ?>
			<? else: ?>
				Il n'y a pas de minerai ici... Il faut sonder !
			<? endif; ?>
		<? else :  ?>
			<? if ($this->filonDetruit === true) : ?>
				Vous avez tout g&acirc;ch&eacute; ! Les derniers fragments de <?=htmlentities($this->minerai["nom_type"])?>
				tombent en miettes dans vos mains et le filon est d&eacute;truit !
			<? else: ?>
				Des fragments de <?=$this->minerai["nom_type"]?> tombent en miettes dans vos mains et sont d&eacute;truits.
			<? endif; ?>
		<? endif; ?>
		<br><br>
	 </div>
	 
	 <div id='extraire_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
		if ($this->okJet1 === true) {
			if ($this->filonOk === true) {
				echo "Vous avez extrait avec succ&egrave;s ";
				echo $this->minerai["quantite_extraite"]." morceau";
				if($this->minerai["quantite_extraite"] > 0) {
					echo "x";
				}
				echo " de ".$this->minerai["nom_type"];
				if ($this->filonDetruit === true) {
					echo "Pfiou, il n'y a plus rien dans le filon...";
				}
				if ($this->effetRune) {
					echo "
";
					echo "Une rune que vous portez a eu de l'effet sur la quantit&eacute; de minerai extrait.";
				}
			} else {
				echo "Il n'y a pas de minerai ici... Il faut sonder !";
			}
		} else {
			if ($this->filonDetruit === true) {
				echo "Vous avez tout g&acirc;ch&eacute; ! Le filon est d&eacute;truit !";
			} else {
				echo "Des fragments de ".htmlentities($this->minerai["nom_type"]);
				echo " tombent en miettes dans vos mains et sont d&eacute;truits.";
			}
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('extraire_text','extraire_copie');">
<? include("commun_fermer.phtml") ?>