<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; fabriquer une pi&egrave;ce d'&eacute;quipement : 
	<br />
	<?=htmlentities($this->typeEquipementCourant["nom_type_equipement"]) ?>, de qualit&eacute; <?=$this->qualite ?>
	et de niveau <?=$this->niveau ?>.
	<br />
	Il y a <?=$this->nbRunes ?> emplacement<? if ($this->nbRunes > 1) echo 's'; ?> runique<? if ($this->nbRunes > 1) echo 's'; ?>.
	<br /><br />
	<? if ($this->effetRune) :?>
		Une rune que vous portez a eu de l'effet sur la qualit&eacute; de cette pi&egrave;ce d'&eacute;quipement.
	<? endif; ?>
<? else: ?>
	Vous avez manqu&eacute; votre forgeage<br />
<? endif; ?>