<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
<input type="hidden" name="valeur_1" id="valeur_1" value="-1"/>
 <div class='comp_contenu'>
 	
 	La filature d'un Braldûn doit se faire en 4 étapes : <br />
 	 
 <table align="center" class="table_liste" style="width:90%">
 	<?php $i = 1;?>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">1ère étape</td>
	 	<td class="table_liste">Déterminer la cible, disponible s'il vous n'avez aucune filature en cours.</td>
 	</tr>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">2nd étape</td>
	 	<td class="table_liste">Filer sur une gare permet de savoir si la cible est dans la comté</td>
 	</tr>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">3ème étape</td>
	 	<td class="table_liste">Filer sur une mairie permet de savoir si la cible est dans la ville (cette mairie est la mairie dont la cible est la plus proche)</td>
 	</tr>
 	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	 	<td class="table_liste">4ème étape</td>
	 	<td class="table_liste">Filer dans la ville (et au delà) la plus proche.</td>
 	</tr>
 </table>
 	<br /><br />
 	<?php if ($this->filerEnCours != null) : ?>
 		Vous filer actuellement <?php echo $this->filerEnCours["prenom_braldun"]?> <?php echo $this->filerEnCours["nom_braldun"]?> (<?php echo $this->filerEnCours["id_braldun"]?>).<br />
 		Vous avez accompli l'étape <?php echo ($this->filerEnCours["etape_filature"] - 1)?> de la filature.<br /><br />
 		
 		<?php if ($this->filerEnCours["etape_filature"] == 2): ?>
 			Pour terminer l'étape 2, vous devez être sur une gare pour filer.
 		<?php elseif ($this->filerEnCours["etape_filature"] == 3): ?>
 			Pour terminer l'étape 3, vous devez être sur une mairie pour filer.
 		<?php elseif ($this->filerEnCours["etape_filature"] == 4): ?>
 			Vous pouvez maintenant filer votre cible.
 		<?php endif;?>
 		<br />
 		<?php if ($this->positionOk == false) : ?>
 			<u>Vous n'êtes pas en position</u>.
 		<?php else : ?>
 			<u>Vous êtes en position</u>.
 			<br /><br />
 			<?php if ($this->filerEnCours["etape_filature"] == 2): ?>
 			<i>Un braldûn dissimulé sous une cape vous fait signe d'approcher, à l'abri d'un des piliers de la gare.
 			 Sous couvert d'un silence absolu et moyennant 
 			finances , il vous préviendra si votre cible passe par cette gare</i>.<br /><br />
 			<?php elseif ($this->filerEnCours["etape_filature"] == 3): ?>
 			<i>Alors que vous passez sous le porche pour entrer dans la mairie, un braldûn vous agrippe 
 			par le bras et vous entraîne dans un coin sombre. Sous couvert d'un silence absolu et moyennant 
 			finances , il vous préviendra si votre cible passe en ville</i>.<br /><br />
 			<?php endif;?>
 			
 			<?php if ($this->filerEnCours["etape_filature"] == 2 || $this->filerEnCours["etape_filature"] == 3): ?>
 				<?php if ($this->peutCastars) : ?>
 					Vous avez assez de castars.
 				<?php else: ?>
 					Vous avez n'avez pas assez de castars.
 				<?php endif;?>
 			<br />
 			<?php endif;?>
 			
 		<?php endif;?>
 	<?php else: ?>
 		Vous n'avez aucune filature en cours.<br />
 		Vous êtes à la 1ère étape d'une filature.<br /><br />
 		
		Saisissez le Braldûn que vous souhaitez filer : <br />
		<input type="text" name="recherche_valeur_1" size='30' id="recherche_valeur_1" value="Entrez un nom" onFocus="if(this.value=='Entrez un nom'){this.value='';};activerRechercheUniqueBraldun('valeur_1', false, false);" />
		<input type="hidden" name="recherche_valeur_1_actif" id="recherche_valeur_1_actif" value="0" />
		<div class="recherche" id="recherche_valeur_1_update" ></div> <img src="<?php echo $this->config->url->static?>/images/divers/loupe.gif" />
		<span id="indicateur_recherche_valeur_1" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" alt="Recherche..." /></span>
		<br /><br />
	<?php endif;?>
	
	<br /><br />
	Vous pouvez consuler vos filatures dans l'onglet Quêtes / Contrats.<br /><br />
   				
</div>

<br /><br />
<?php if ($this->assezDePa == true && $this->positionOk == true) : ?>
	<?php if ($this->filerEnCours != null) : ?>
		<?php if ($this->peutCastars && $this->filerEnCours["etape_filature"] == 2 || $this->filerEnCours["etape_filature"] == 3): ?>
 			<input type='button' class='button1' value='Filer en payant 50 castars!' onclick='$("#valeur_1").val(1);this.disabled=true;_get_("/competences/doaction?caction=do_competence_filer");'>
 			<input type='button' class='button1' value='Filer sans payer 50 castars!' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_filer");'>
 		<?php else: ?>
 			<input type='button' class='button1' value='Filer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_filer");'>
 		<?php endif;?>
 			
		
	<?php else: ?>
		<input type='button' class='button1' value='Filer !' onclick='if ($("#valeur_1").val() == -1 || $("#recherche_valeur_1").val() == "") {alert("Choisissez un Braldûn"); } else { this.disabled=true;_get_("/competences/doaction?caction=do_competence_filer");}'>
	<?php endif;?>
<?php endif ?>
