<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true): ?>
	<?php if ($this->nbLingots > 0) : ?>
		Vous avez r&eacute;ussi &agrave; fondre <?php echo $this->nbMineraiFondus ?> minerai<?php if($this->nbMineraiFondus > 1):echo 's';endif;?>
		 de <?php echo htmlspecialchars($this->mineraiNomType) ?>.<br />
		Vous avez obtenu <?php echo $this->nbLingots ?> lingot<?php if($this->nbLingots > 1):echo 's';endif;?><br />
	<?php else: ?>
		Vous avez rat&eacute; la fonte de 
		<?php if($this->nbMineraiFondus > 1):?>
			tous vos minerais.
		<?php else: ?>
			votre minerai.
		<?php endif; ?>
		<br />
		Aucun lingot n'est apparu et <?php echo $this->nbMineraiFondus ?> minerai<?php if($this->nbMineraiFondus > 1):echo 's sont perdus'; else: echo ' est perdu'; endif;?>.<br />
	<?php endif; ?>
<?php else: ?>
	Vous avez manqu&eacute; votre fonte, mais aucun minerai n'est perdu.<br />
<?php endif; ?>