 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
	 <? if ($this->fondreEchoppeOk === true && $this->fondreMineraiOk === true) : ?>
	
	 Pour <?=$this->nb_pa ?> PA, vous pouvez fondre jusqu'&agrave; <?=$this->nbMineraiMax ?> <? if ($this->nbMineraiMax > 1) : $s='s'; else: $s=''; endif; ?> minerai<?=$s ?> en lingot(s) ...<br />
	<br />
	 <select name="valeur_1" id="valeur_1"  onchange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1 ){$('bouton_fondre').disabled=true } else {$('bouton_fondre').disabled=false }">
	 	<option value="-1">(Choisissez un minerai)</option>
	 	<? foreach($this->minerais as $m) :
			if ($m["quantite_arriere"]<=1):$s=''; else:$s='s';endif;
	 	?>
	 		<option value="<?=$m["id_type"]?>">En stock : <?=$m["quantite_arriere"]?> minerai<?=$s?> de <?=htmlspecialchars($m["nom_type"])?></option>
	 	<? endforeach; ?>
	 </select>
	 
	 <br /><br />
	 
	 Quantité de minerais à fondre : <br />
	 <select name="valeur_2" id="valeur_2"  onchange="javascript:if ($('valeur_2').value==-1 || $('valeur_1').value==-1){$('bouton_fondre').disabled=true } else {$('bouton_fondre').disabled=false }">
	 	<option value="-1">(Choisissez la quantité à fondre)</option>
	 	<? for($i=1; $i <= $this->nbMineraiMax; $i++) :
	 		if ($i<=1): $s=''; else: $s='s'; endif;
	 	?>
	 		<option value="<?=$i ?>"><?=$i?> minerai<?=$s?></option>
	 	<? endfor; ?>
	 </select>
	 
	<? elseif ($this->fondreEchoppeOk == false) : ?>
		Vous ne pouvez fondre que dans une de vos &eacute;choppes de Forgeron.
	<? else: ?>
		Vous n'avez pas assez de minerai dans votre &eacute;choppe pour fondre...
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->fondreEchoppeOk === true && $this->fondreMineraiOk) : ?>
<input type='button' class='button1' id='bouton_fondre' value='Fondre !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_fondre");' disabled>
<? endif ?>
