 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
	 <?php if ($this->forgerEchoppeOk === true) : ?>
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez forger une pi&egrave;ce d'&eacute;quipement<br /><br />
     
     Type de l'&eacute;quipement :<br />
     <select name="valeur_1" id="valeur_1"  onchange="_get_('/competences/doaction?caction=ask_competence_forger&type_equipement='+this.value);">
	 	<option value="-1">(Choisissez un &eacute;quipement)</option>
	 	<?php foreach($this->typeEquipement as $t) : ?>
	 		<option value="<?php echo $t["id_type_equipement"]?>" <?php echo $t["selected"]?>><?php echo htmlspecialchars($t["nom_type_equipement"])?></option>
	 	<?php endforeach; ?>
	 </select>
	 
	 <br /><br />
	 
	 <?php $js = Bral_Helper_DetailEquipement::afficheRecetteJs($this->niveaux);?>
	 
	 <?php if ($this->niveaux != null) : ?>
	 Niveau de l'&eacute;quipement :<br />
	 <select name="valeur_2" id="valeur_2" onchange="javascript:<?php echo $js?>; if ($('#valeur_1').value==-1 || $('#valeur_2').value==-1 || $('#valeur_3').value==-1){$('#bouton_forger.attr('disabled', true) } else {$('#bouton_forger').attr('disabled',false) }">
	 	<option value="-1">(Choisissez un niveau)</option>
	 	<?php foreach($this->niveaux as $k => $v) : ?>
	 		<?php if ($v["a_afficher"] == true) : ?>
	 		<option value="<?php echo $k?>" <?php if ($v["ressourcesOk"] === false) echo "disabled"; ?>><?php echo htmlspecialchars($v["niveauText"])?></option>
	 		<?php endif; ?>
	 	<?php endforeach; ?>
	 </select>
	 <?php endif; ?>
	
	<?php echo Bral_Helper_DetailEquipement::afficheRecette($this->caracs, $this->niveaux);?>
		
	<br /><br />
	
	<?php if (isset($this->peutRunes)): 
		if ($this->peutRunes === true) : ?>
			Cet &eacute;quipement peut porter des runes.<br />
			 <?php if ($this->runes != null) : ?>
			 Nombre d'emplacements sur l'&eacute;quipement :<br />
			 <select name="valeur_3" id="valeur_3"  onchange="javascript:if ($('#valeur_1').value==-1 || $('#valeur_2').value==-1 || $('#valeur_3').value==-1){$('#bouton_forger.attr('disabled', true) } else {$('#bouton_forger').attr('disabled',false) }">
			 	<option value="-1">(Choisissez un nombre d'emplacements)</option>
			 	<?php foreach($this->runes as $n) : ?>
			 		<option value="<?php echo $n["nombre"]?>"><?php echo $n["nombre"]?> rune<?php if($n["nombre"]>1)echo "s";?></option>
			 	<?php endforeach; ?>
			 </select>
			 <?php endif; ?>
		<?php else: ?>
			<input type='hidden' id='valeur_3' name='valeur_3' value='0'>
			Cet &eacute;quipement ne peut pas porter de rune.<br />
		<?php endif; ?>
	<?php endif; ?>
	
	<?php if (isset($this->cout)): ?>
	<br /><br />Co&ucirc;t : 
	 	<?php foreach($this->cout as $key1 => $value1) :?>
	 			<br />Niveau <?php echo $key1 ?> -&gt; 
		 		<?php 
		 			$i = 0;
		 			foreach($value1 as $c) :
		 			$i++;
		 		?>
		 		<?php echo htmlspecialchars($c["nom"]) ?> : <?php echo $c["cout"] ?> <?php if (isset($c["unite"]) && $c["unite"] != "") :?><?php echo $c["unite"] ?><?php if ($c["cout"] > 1) : echo 's'; endif;?><?php endif; ?><?php if ($i<count($value1))echo ","; else echo "."; ?>
		 	<?php endforeach; ?>
		 	<?php if ($this->niveaux[$key1]["ressourcesOk"] === false) : ?>
		 		Pas assez de ressource dans l'&eacute;choppe
			<?php endif; ?>
	 	<?php endforeach; ?>
	<?php endif; ?>
	
	 <?php elseif ($this->forgerEchoppeOk == false) : ?>
		Vous ne pouvez forger que dans une de vos &eacute;choppes de Forgeron.
	<?php else: ?>
		Vous n'avez aucun lingot pour forger...
	<?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->forgerEchoppeOk === true && $this->etape1 === true) : ?>
<input type='button' class='button1' id='bouton_forger' value='Forger !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_forger&type_equipement="+$("valeur_1").value);' disabled>
<?php endif ?>
