<div class='comp_titre'>Forger</div>

 <div class='comp_contenu'>
	 <div id='forger_text' style="display:block"  onClick="javascript:switch2div('forger_text','forger_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true): ?>
			Vous avez r&eacute;ussi &agrave; forger une pi&egrave;ce d'&eacute;quipement.
		<? else: ?>
			Vous avez manqu&eacute; votre forgeage<br>
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='forger_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
			echo "Votre Jet d'identification : ".$this->jetHobbit;
			echo "
";
			if ($this->okJet1 === true) {
				echo "Vous avez r&eacute;ussi &agrave; forger du minerai de ".htmlentities($this->mineraiNomType);
				echo "
";
			} else {
				echo "Vous avez manqu&eacute; votre forgeage";
			}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('forger_text','forger_copie');">
<? include("commun_fermer.phtml") ?>