<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; forger 
	<?php if ($this->typePiece == "munition") : ?>
		des munitions :
	<?php else: ?>
		une pi&egrave;ce d'&eacute;quipement : 
	<?php endif;?>
	<br />
	<?php echo htmlspecialchars($this->typeEquipementCourant["nom_type_equipement"]) ?>, de qualit&eacute; <?php echo $this->qualite ?>
	et de niveau <?php echo $this->niveau ?>.
	<br />
	<?php if ($this->typePiece != "munition") : ?>
		Il y a <?php echo $this->nbRunes ?> emplacement<?php if ($this->nbRunes > 1) echo 's'; ?> runique<?php if ($this->nbRunes > 1) echo 's'; ?>.
		<br /><br />
		Le bonus apport&eacute; sur l'&eacute;quipement est : <?php echo $this->bonus?>.
	<?php endif;?>
	<br /><br />
	<?php if ($this->effetRune) :?>
		Une rune que vous portez a eu de l'effet sur la qualit&eacute; de cette pi&egrave;ce d'&eacute;quipement.
	<?php endif; ?>
	
	<?php if ($this->competenceAmelioree != null) : ?>
		<br />Vous avez r&eacute;ussi &agrave; am&eacute;liorer votre compétence Produire :
		<br />
		<b><?php echo $this->competenceAmelioree["competence"]["nom_competence"]?> : + <?php echo $this->competenceAmelioree["gain"]?> % </b><br />
	<?php endif;?>
<?php else: ?>
	Vous avez manqu&eacute; votre forgeage.<br/>
	La moiti&eacute; des composants sont d&eacute;truits.<br />
<?php endif; ?>