<div class='comp_titre'>Forger</div>

 <div class='comp_contenu'>
	 <div id='forger_text' style="display:block"  onClick="javascript:switch2div('forger_text','forger_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true): ?>
			Vous avez r&eacute;ussi &agrave; forger une pi&egrave;ce d'&eacute;quipement : 
			<br>
			<?=htmlentities($this->typeEquipementCourant["nom_type_equipement"]) ?>, de qualit&eacute; <?=$this->qualite ?>
			et de niveau <?=$this->niveau ?>.
			<br>
			Il y a <?=$this->nbRunes ?> emplacement<? if ($this->nbRunes > 1) echo 's'; ?> runique<? if ($this->nbRunes > 1) echo 's'; ?>.
			<br><br>
			<? if ($this->effetRune) :?>
				Une rune que vous portez a eu de l'effet sur la qualit&eacute; de cette pi&egrave;ce d'&eacute;quipement.
			<? endif; ?>
		<? else: ?>
			Vous avez manqu&eacute; votre forgeage<br>
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='forger_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
			if ($this->okJet1 === true) {
				echo "Vous avez r&eacute;ussi &agrave; forger une pi&egrave;ce d'&eacute;quipement :";
				echo "
"; 
				echo htmlentities($this->typeEquipementCourant["nom_type_equipement"]);
				echo ", de qualit&eacute; ".$this->qualite;
				echo " et de niveau ".$this->niveau.".";
				$s = "";
				if ($this->nbRunes > 1) $s='s';
				echo "
";
				echo " Il y a ".$this->nbRunes. " emplacement$s";
				echo " runique$s";
				echo "
";
				if ($this->effetRune) {
					echo "Une rune que vous portez a eu de l'effet sur la qualit&eacute; de cette pi&egrave;ce d'&eacute;quipement.";
				}
			} else {
				echo "Vous avez manqu&eacute; votre forgeage";
			}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('forger_text','forger_copie');">
<? include("commun_fermer.phtml") ?>