<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->cibleVisible == false) : ?>
	Aucune cible sur votre case.<br />
	
<?php else: ?>

 	<?php if ($this->okJet1 === true): ?>
 	
		Vous avez attaqu&eacute; avec fr&eacute;n&eacute;sie :<br /> 
		
		<?php foreach($this->retoursAttaques as $retourAttaque) : ?> 
	 		<?php echo htmlspecialchars($retourAttaque["cible"]["nom_cible"])?> (<?php echo $retourAttaque["cible"]["id_cible"]?>) 
			 Jet d'attaque : <span class="resultat" title="<?php echo $retourAttaque["jetAttaquant"]["details"]?>"><?php echo $retourAttaque["jetAttaquant"]["jet"]?> </span>, 
		 <span class="resultat_cache">(<?php echo $retourAttaque["jetAttaquant"]["details"]?>)</span>
		 jet de d&eacute;fense de la cible : <?php echo $retourAttaque["jetCible"]?><br />
			 
		 	<?php if ($retourAttaque["attaqueReussie"] === true) : ?>
		 		<?php if ($retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
		 		Vous avez inflig&eacute; <span class="resultat" title="<?php echo $retourAttaque["jetDegat"]["details"]?>"><?php echo $retourAttaque["jetDegat"]["jet"]?></span> point<?php echo $s?> de d&eacute;g&acirc;t
		 		<?php if ($retourAttaque["critique"] == true): ?>
		 		en attaque critique
		 		<?php endif; ?>
		 		<span class="resultat_cache">(<?php echo $retourAttaque["jetDegat"]["details"]?>)</span>.
		 		<br />
		 		<?php if ($retourAttaque["arm_nat_cible"] > 0) :?>
				 	L'armure naturelle l'a prot&eacute;g&eacute;e.<br />
				<?php endif; ?>
				<?php if ($retourAttaque["arm_eqpt_cible"] > 0) :?>
				 	L'&eacute;quipement l'a prot&eacute;g&eacute;.<br />
				<?php endif; ?>
				 
				Au total, son armure l'a protégé en réduisant les dégâts de <?php echo $retourAttaque["arm_totale_cible"]?>.<br />
				La cible a donc perdu <?php echo $retourAttaque["jetDegatReel"] ?> point<?php if ($retourAttaque["jetDegatReel"] > 1) : ?>s<?php endif;?> de vie.
		 		<br />
		 		<?php if ($retourAttaque["mort"]): ?>
		 			Vous avez 
		 			<?php if ($retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "oui") :?>
			 			plaqu&eacute;
			 		<?php elseif ($retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "non") :?>
			 			mis KO
			 		<?php else: ?>	
			 			tu&eacute; 
			 		<?php endif;?>
		 			<?php echo htmlspecialchars($retourAttaque["cible"]["nom_cible"])?> (<?php echo $retourAttaque["cible"]["id_cible"]?>)<br />
		 			
		 			<?php if ($retourAttaque["gains"] != null) :?>
			 			<?php if (isset($this->retourAttaque["gains"]["butin"])) :?>
			 				Le butin suivant est tombé à terre : 
			 				<?php echo $this->retourAttaque["gains"]["butin"];?><br /><br />
			 			<?php elseif (isset($retourAttaque["gains"]["gainRune"]) && $retourAttaque["gains"]["gainRune"] != false) :?>
			 				Une rune est tomb&eacute;e &agrave; terre <?php if ($retourAttaque["gains"]["gainCastars"] > 0) : ?>
			 				ainsi que <?php echo $retourAttaque["gains"]["gainCastars"]?> castar<?php if ($retourAttaque["gains"]["gainCastars"] > 1): echo "s"; endif;?>
			 				<?php endif;?>.
			 				<br />
			 			<?php elseif ($retourAttaque["gains"]["gainCastars"] > 0) : ?>
			 				<?php echo $this->retourAttaque["gains"]["gainCastars"]?> castar<?php if ($this->retourAttaque["gains"]["gainCastars"] > 1) : 
 								echo "s sont tomb&eacute;s"; 
		 					else:	
		 						echo " est tomb&eacute;";
			 				endif;?>
			 				 &agrave; terre.<br /><br />
			 			<?php endif;?>
			 		<?php endif;?>
		 		<?php endif; ?>
		 		<br />
				<?php if ($retourAttaque["ballonLache"]) : ?>
					<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/ballon.png'/><br />
					Le ballon de soule est tomb&eacute; &agrave; terre !<br />
				<?php endif;?>
				
				<?php if ($this->effetRune) :?>
					Une rune que vous portez a eu de l'effet sur les d&eacute;g&acirc;ts inflig&eacute;s.<br />
				<?php endif; ?>
				
		 	<?php else: ?>
		 		Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
		 		<?php if ($retourAttaque["fragilisee"] === true) : ?>
		 		<br /> La cible est fragilis&eacute;e pour les prochaines attaques
		 		<?php else: ?>
		 		parfaitement.
		 		<?php endif; ?>
		 		<br /><br />
		 	<?php endif; ?>
	 	<?php endforeach;?>
		 	
 		Vous avez gagn&eacute; <?php echo $this->nb_px?> PX<br /><br />
 		<?php include('commun_attaque_resultat.phtml');?>
	<?php else: ?>
		Vous avez manqu&eacute; votre fr&eacute;n&eacute;sie.<br />
	<?php endif; ?>
<?php endif;?>
<?php include("commun_text_effets.phtml") ?>