	 <? include("commun_text_resultat.phtml") ?>
	 	<? if ($this->okJet1 === true): ?>
			 Vous avez attaqu&eacute; <?=htmlspecialchars($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)  N <?=$this->retourAttaque["cible"]["niveau_cible"]?> 
			 avec fr&eacute;n&eacute;sie :<br /><br />
			 Jet d'attaque : <?=$this->retourAttaque["jetAttaquant"]?><br />
			 Jet de d&eacute;fense de la cible : <?=$this->retourAttaque["jetCible"]?><br />
			 
		 	<? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
		 		<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
		 		Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;g&acirc;t
		 		<? if ($this->retourAttaque["critique"]  == true): ?>
		 		en attaque critique
		 		<? endif; ?>
		 		<br /><br />
		 		<? if ($this->retourAttaque["arm_nat_cible"] > 0) :?>
		 			L'armure naturelle l'a prot&eacute;g&eacute;e en réduisant les d&eacute;g&acirc;ts de <?= $this->retourAttaque["arm_nat_cible"]?><br />
		 		<? endif; ?>
		 		<? if ($this->retourAttaque["arm_eqpt_cible"] > 0) :?>
		 			L'&eacute;quipement l'a prot&eacute;g&eacute; en r&eacute;duisant les d&eacute;g&acirc;ts de <?= $this->retourAttaque["arm_eqpt_cible"]?><br />
		 		<? endif; ?>
				La cible a donc perdu <?=$this->retourAttaque["jetDegatReel"] ?> point<? if ($this->retourAttaque["jetDegatReel"] > 1) : ?>s<?endif;?> de vie<br />
		 		<br />
		 		<? if ($this->retourAttaque["mort"]): ?>
		 			<? if ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "oui") :?>
			 			plaqu&eacute;
			 		<? elseif ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "non") :?>
			 			mis KO
			 		<? else: ?>	
			 			tu&eacute; 
			 		<? endif;?>
		 			<?=htmlspecialchars($this->retourAttaque["cible"]["nom_cible"])?> (<?=$this->retourAttaque["cible"]["id_cible"]?>) N<?=$this->retourAttaque["cible"]["niveau_cible"] ?><br /><br />
		 		<? endif; ?>
		 		Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
		 		
		 		<? if ($this->effetRune) :?>
					Une rune que vous portez a eu de l'effet sur les d&eacute;g&acirc;ts inflig&eacute;s.<br />
				<? endif; ?>
				
		 	<? else: ?>
		 		Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
		 		<? if ($this->retourAttaque["fragilisee"] === true) : ?>
		 		<br /> La cible est fragilis&eacute;e pour les prochaines attaques
		 		<? else: ?>
		 		parfaitement.
		 		<? endif; ?>
		 	<? endif; ?>
	 	<? else: ?>
			Vous avez manqu&eacute; votre fr&eacute;n&eacute;sie.<br />
		<? endif; ?>
		<? include("commun_text_effets.phtml") ?>