 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	<? if ($this->frenesieVilleOk == false): ?>
 		Vous ne pouvez pas utiliser cette comp&eacute;tence en ville.<br />
 	<? elseif ($this->nHobbits == 0 && $this->nMonstres == 0): ?>
 		Il n'y a rien &agrave attaquer ici...<br />
 	<? else: ?>
 		Pour <?=$this->nb_pa?> PA, vous pouvez attaquer :<br /><br />
 		
		<? if ($this->nMonstres > 0): ?>
		Un monstre<br />
			<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_frenesie').disabled=true } else {$('valeur_2').value=-1; $('bouton_frenesie').disabled=false }">
			<option value='-1'>(Choisis un monstre)</option>
			<? foreach ($this->tabMonstres as $m) : ?>
			<option value="<?=$m["id_monstre"]?>"><?=htmlspecialchars($m["nom_monstre"])?> <?=htmlspecialchars($m["taille_monstre"])?>  (<?=$m["id_monstre"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
		<? else: ?>
		<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
		<? endif; ?>
		
 		<? if ($this->nHobbits > 0): ?>
 		 Un hobbit<br />
 			<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_frenesie').disabled=true } else {$('valeur_1').value=-1; $('bouton_frenesie').disabled=false }">
			<option value='-1'>(Choisis un hobbit)</option>
 			<? foreach ($this->tabHobbits as $h) : ?>
			<option value="<?=$h["id_hobbit"]?>"><?=htmlspecialchars($h["prenom_hobbit"])?> <?=htmlspecialchars($h["nom_hobbit"])?> (<?=$h["id_hobbit"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
		<? else: ?>
		<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
		<? endif;?>
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->frenesieVilleOk == true) : ?>
<input type='button' class='button1' value='Fr&eacute;n&eacute;sie !' id='bouton_frenesie' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_frenesie");' disabled>
<? endif ?>
