 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <?php if ($this->fumerNbFeuilleOk === true) : ?>
	 	Pour <?php echo $this->nb_pa ?> PA, vous pouvez fumer...
	 	<br /><br />
	 	
		<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('valeur_1').value==-1){$('bouton_fumer').disabled=true } else {$('bouton_fumer').disabled=false }">
			<option value='-1'>(Choisissez un type de feuille)</option>
			<?php foreach ($this->tabLabanTabac as $t) :?>
			<?php $s = ''; if ($t["quantite_feuille_laban_tabac"] > 1): $s='s'; endif; ?>
			<option value="<?php echo $t["id_fk_type_laban_tabac"]?>"><?php echo $t["nom_type_tabac"]?> : <?php echo $t["quantite_feuille_laban_tabac"]?> feuille<?php echo $s?> restante<?php echo $s?></option>
			<?php endforeach; ?>
		</select><br /><br />
				
	 <?php else: ?>
		 <?php if ($this->fumerNbFeuilleOk != true) :?>
		 	Il vous faut au moins une feuille pour fumer<br />
		 <?php endif; ?>
	 <?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->fumerNbFeuilleOk === true) : ?>
<input type='button' class='button1' id='bouton_fumer' value='Fumer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_fumer");' disabled>
<?php endif ?>
