<? include("commun_text_resultat.phtml") ?>

Vous avez fum&eacute; <?=$this->tabac["nom_type_tabac"] ?>.<br /> 

	<? if ($this->competences != null) :?>
		<? if ($this->nbToursBonus > 1) :?>
			Pour ce tour et le prochain, 
		<? else: ?>
			Pour le tour courant, 
		<? endif; ?>
	
		cela rajoute 15% dans les comp&eacute;tences suivantes : <br />
		
		<? foreach($this->competences as $c): ?>
			<?=$c["nom_competence"]?><br />
		<? endforeach;?>
		
		<br />
		Vous aurez ensuite <?=$this->nbToursMalus?> tour<? if ($this->nbToursMalus > 1): echo "s"; endif; ?> de malus (-10%) sur ces comp&eacute;tences.
		
	<? else: ?>
		Vous vous sentez bien, tr&egrave;s relax&eacute;, mais ce tabac n'a aucune influence sur vous.
	<? endif; ?>

<br />
<br />