<div class='comp_titre'>Gardiennage</div>
 <form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='4'>
 <div class='comp_contenu'>
 <table>
  <th class='comp_titre'>Nouveau Gardiennage</th><th class='comp_titre'>Informations</th>
  <tr width='50%'>
   <td>Premier jour :</td>
   <td>
   <select name='valeur_1' id='valeur_1'> 
   	 <? foreach($this->tabJoursDebut as $d) : ?>
     <option value='<?=$d["valeur"]?>'><?=$d["affichage"]?></option>
     <? endforeach; ?>
    </select>
   </td>
  </tr>
  <tr>
   <td>Nombre de jour(s) : </td>
   <td>
   <select name='valeur_2' id='valeur_2'>
    		<option value='1'> 1 </option>
    		<option value='2'> 2 </option>
    		<option value='3'> 3 </option>
    		<option value='4'> 4 </option>
    		<option value='5'> 5 </option>
    </select>
   </td>
  </tr>
  <tr>
   <td>Gardien : </td>
   <td>
   <select name='valeur_3' id='valeur_3'>
     <option value='-1'>(Choisir)</option>
     <? foreach($this->tabGardiens as $g) : ?>
     <option value='<?=$g["id_gardien"]?>'><?=$g["nom_gardien"]." (".$g["id_gardien"].")" ?></option>
     <? endforeach; ?>
    </select>
   </td>
  </tr>
  <tr>
   <td>ou nouveau N° <br />du hobbit Gardien : </td>
   <td>
   <input type='textbox' maxlength='5' size='5' name='valeur_7' id='valeur_7' value=''>
   </td>
  </tr>
  <tr>
   <td></td>
   <td></td>
  </tr>
  <tr>
  <td>Commentaire :</td>
  <td>&nbsp;</td>
  </tr>
  
  <tr>
    <td colspan='2'>
    <textarea onkeyup="this.value = this.value.slice(0, 100)" rows='3' cols='30' name='valeur_4' id='valeur_4'></textarea>
    </td>
  </tr>
 </table>
 </div>
</form>
<br>
<input type='button' value='Gardiennage !' onClick='_get_("/competences/DoAction?caction=do_competence_gardiennage");'>
<input type='button' value='Annuler' onClick='_get_("/interface/clear");'>