<?php if ($this->nouveauGardiennage === true) : ?>
	Gardiennage enregistr&eacute; avec succ&egrave;s
<?php endif; ?>
<?php if (empty($this->tabGardiennage)) : ?>
	Aucun Gardiennage en cours.
<?php else: ?>
	Gardiennage en cours
	<table class="table_liste" style="width:100%;text-align:center">
	<thead class="table_liste">
	  <tr class="table_liste">
	<td>Gardien</td>
	<td>Date de d&eacute;but</td>
	<td>Nombre de jour(s)</td>
	<td>Commentaire</td>
	</tr>
	</thead>
	<?php foreach($this->tabGardiennage as $g): ?>
		<tr>
			<td><?php echo $g["prenom_gardien"]?> <?php echo $g["nom_gardien"]. ' ('.$g["id_gardien"].')';?></td>
			<td><?php echo $g["date_debut"] ?></td>
			<td><?php echo $g["nb_jours"] ?></td>
			<td><?php echo htmlspecialchars(stripslashes($g["commentaire"])) ?></td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php endif;?>
	<br /><br />
<?php if (empty($this->tabGardiennageTrenteJours)) : ?>
	Aucun Gardiennage depuis 30 jours.
<?php else: ?>
	Gardiennage depuis 30 jours
	<table class="table_liste" style="width:100%;text-align:center">
		<thead class="table_liste">
	  <tr class="table_liste">
	<td>Gardien</td>
	<td>Date de d&eacute;but</td>
	<td>Nombre de jour(s)</td>
	<td>Commentaire</td>
	</tr>
	</thead>
	<?php foreach($this->tabGardiennageTrenteJours as $g): ?>
		<tr>
			<td><?php echo $g["prenom_gardien"]?> <?php echo $g["nom_gardien"]. ' ('.$g["id_gardien"].')';?></td>
			<td><?php echo $g["date_debut"] ?></td>
			<td><?php echo $g["nb_jours"] ?></td>
			<td><?php echo htmlspecialchars(stripslashes($g["commentaire"])) ?></td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php endif; ?>
<br /><br />