 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='6'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='voir'>
 <div class='comp_contenu'>
 <? if (!empty($this->messageMax)) : ?>
 	<?=$this->messageMax ?>
 <? else: ?>
 <table width='100%'>
 <tr>
  <th class='comp_titre'>Nouveau Gardiennage</th>
  <th class='comp_titre'>Informations</th>
  </tr>
  <tr>
   <td>Premier jour :</td>
   <td>
   <select name='valeur_2' id='valeur_2'> 
   	 <? foreach($this->tabJoursDebut as $d) : ?>
     <option value='<?=$d["valeur"]?>'><?=$d["affichage"]?></option>
     <? endforeach; ?>
    </select>
   </td>
  </tr>
  <tr>
   <td>Nombre de jour(s) : </td>
   <td>
   <select name='valeur_3' id='valeur_3'>
    		<option value='1'> 1 </option>
    		<option value='2'> 2 </option>
    		<option value='3'> 3 </option>
    		<option value='4'> 4 </option>
    		<option value='5'> 5 </option>
    </select>
   </td>
  </tr>
  <tr>
   <td>Gardien : </td>
   <td>
   <select name='valeur_4' id='valeur_4' onChange="$('valeur_5').value=''">
     <option value='-1'>(Choisir)</option>
     <? if ($this->tabGardiens != null) :?>
     <? foreach($this->tabGardiens as $g) : ?>
     <option value='<?=$g["id_gardien"]?>'><?=$g["prenom_gardien"] ?> <?=$g["nom_gardien"]." (".$g["id_gardien"].")" ?></option>
     <? endforeach; ?>
     <? endif;?>
    </select>
   </td>
  </tr>
  <tr>
   <td>ou Num&eacute;ro <br />du braldun Gardien : </td>
   <td>
   <input type='text' maxlength='5' size='5' name='valeur_5' id='valeur_5' value='' onkeypress="chiffres(event); $('valeur_4').value=-1">
   </td>
  </tr>
  <tr>
   <td></td>
   <td></td>
  </tr>
  <tr>
  <td>Commentaire :</td>
  <td>&nbsp;</td>
  </tr>
  
  <tr>
    <td colspan='2'>
    <textarea onkeyup="this.value = this.value.slice(0, 100)" rows='3' cols='30' name='valeur_6' id='valeur_6'></textarea>
    </td>
  </tr>
 </table>
<br />
Actuellement, vous avez programm&eacute; <?=$this->nbEnCours?> gardiennage<?if ($this->nbEnCours>1) echo 's';?>. <br /> <br /> 
Vous ne pouvez programmer que <?=$this->nbMax?> gardiennages maximum.<br /> <br /> 
Dans le cadre d'un nouveau gardiennage,<br />
 un message automatique sera envoy&eacute; au braldun gardien.<br />
 (message présent &eacute;galement dans vos &eacute;l&eacute;ments envoy&eacute;s de votre messagerie)<br />
<br /> 
 <? endif; ?>
 </div>
<br /> 
<? if (empty($this->messageMax)) : ?>
<input type='button' class='button1' value='Nouveau Gardiennage !' onclick='this.disabled=true;$("valeur_1").value="nouveau"; _get_("/competences/doaction?caction=do_competence_gardiennage");'><br />
<? endif; ?>
<input type='button' class='button1' value='Voir Gardiennage en cours' onclick='this.disabled=true;$("nb_valeurs").value=1;$("valeur_1").value="voir"; _get_("/competences/doaction?caction=do_competence_gardiennage");'><br />
