<? if ($this->nouveauGardiennage === true) : ?>
	Gardiennage enregistr&eacute; avec succ&egrave;s
<? endif; ?>
<? if (empty($this->tabGardiennage)) : ?>
	Aucun Gardiennage en cours.
<? else: ?>
	Gardiennage en cours
	<table>
	<tr>
	<th class='comp_titre'>Gardien</th>
	<th class='comp_titre'>Date de d&eacute;but</th>
	<th class='comp_titre'>Nombre de jour(s)</th>
	<th class='comp_titre'>Commentaire</th>
	</tr>
	<? foreach($this->tabGardiennage as $g): ?>
		<tr>
			<td><?=$g["prenom_gardien"]?> <?=$g["nom_gardien"]. ' ('.$g["id_gardien"].')';?></td>
			<td><?=$g["date_debut"] ?></td>
			<td><?=$g["nb_jours"] ?></td>
			<td><?=htmlspecialchars(stripslashes($g["commentaire"])) ?></td>
		</tr>
	<? endforeach; ?>
	</table>
<? endif; ?>