 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 	
 	<b>Information importante avant de valider l'action</b> : <br /><br />
 	
	Vous ne pouvez pas vous mettre en hibernation avec une inscription &agrave; un match de soule
	et pendant un match. Si vous êtes dans ce cas, il faut d'abord vous désinscrire du match
	avant de passer en hibernation. Si vous êtes en plein match, demandez un gardiennage
	ou laissez vivre tout seul votre Braldûn (30 jours maximum sans activation de votre part, au delà, 
	le Braldûn est supprimé).
	<br /><br />
	Si vous passez en hibernation en étant dans un donjon, vous serez ramené à l'hopital de la ville
	la plus proche en sortie d'hibernation.
	<br /><br />
	Une hibernation dure de 5 jours minimum et commence dès le <b>lendemain</b> de la validation de cette action.<br /><br />
 	
 	Pendant les 5 premiers jours d'hibernation, vous ne pourrez pas vous connecter au jeu. Ensuite, dès la première connexion, 
 	vous sortez d'hibernation.
 	
 	<br /><br />
 	Rappel : Un Braldûn est automatiquement supprimé au bout de 30 jours d'inactivité, 
 	par contre, un Braldûn en hibernation ne sera pas supprimé quelque soit la durée.
	<br /><br />
	
 </div>
<br />
<? if ($this->hibernerPossible === true) : ?>
<input type='button' class='button1' id='bouton_hiberner' value='Hiberner !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_hiberner");'>
<? endif; ?>