<div class='comp_titre'>Identifier des Runes</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->identifierRuneOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez identifier une rune ...<br>
	 <select name="valeur_1" id="valeur_1"  onChange="javascript:if ($('valeur_1').value==-1){$('bouton_identifierrune').disabled=true } else {$('bouton_identifierrune').disabled=false }">
	 	<option value="-1">(Choisis une rune)</option>
	 	<? foreach($this->runes as $r) : ?>
	 		<option value="<?=$r["id_rune"]?>">Rune non identifi&eacute;e n&deg; <?=$r["id_rune"]?></option>
	 	<? endforeach; ?>
	 </select>
	 <? else: ?>
	Vous n'avez aucune rune &agrave; identifier...
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->identifierRuneOk === true) : ?>
<input type='button' class='button1' id='bouton_identifierrune' value='Identifier une rune !' onClick='_get_("/competences/DoAction?caction=do_competence_identifierrune");' disabled>
<? endif ?>
<? include("commun_fermer.phtml") ?>