 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <? if ($this->identifierRuneOk === true) : ?>
	 Pour <?=$this->nb_pa ?> PA, vous pouvez identifier une rune ...<br />
	 <select name="valeur_1" id="valeur_1"  onChange="javascript:if ($('valeur_1').value==-1){$('bouton_identifierrune').disabled=true } else {$('bouton_identifierrune').disabled=false }">
	 	<option value="-1">(Choisis une rune)</option>
	 	<? foreach($this->runes as $r) : ?>
	 		<option value="<?=$r["id_rune"]?>">Rune non identifi&eacute;e n&deg; <?=$r["id_rune"]?></option>
	 	<? endforeach; ?>
	 </select>
	 <? else: ?>
	Vous n'avez aucune rune &agrave; identifier...
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->identifierRuneOk === true) : ?>
<input type='button' class='button1' id='bouton_identifierrune' value='Identifier une rune !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_identifierrune");' disabled>
<? endif ?>
