<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true):?>
	Votre Jet d'identification : <?=$this->jetBraldun ?> <br />
	<? if ($this->identificationReussieOk === true): ?>
		Vous avez r&eacute;ussi &agrave; identifier la rune n&deg; <?=$this->rune["id_rune"] ?><br />
		<? if ($this->rune["image"] != ""): ?>
	    	<img src="/public/images/runes/<?=$this->rune["image"]?>" title="<?=$this->rune["type"]?> (<?=$this->rune["id_rune"]?>)" />
	   	<? endif; ?>
	   	
	   	<? if ($this->rune["id_braldun_possesseur"] != null) :?>
	   		<br /><br /><?=$this->rune["prenom_braldun_possesseur"]?> <?=$this->rune["nom_braldun_possesseur"]?> (<?=$this->rune["id_braldun_possesseur"]?>) a été prévenu de cette identification.
	   		<br /><br />
	   	<? endif;?>
	<? else: ?>
		Vous avez manqu&eacute; votre identification
		<?if ($this->jetBraldunLoin === true) :?>
			<br />et vous &ecirc;tes loin d'identifier cette rune...
		<? endif; ?>
		<br /><br />
	<? endif; ?>
<? endif; ?>

<? if ($this->nb_px == 0) : ?>
	Vous n'avez gagn&eacute; aucun PX<br /><br /> 
<? else: ?>
	Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
<? endif; ?>