<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true):?>
	Votre Jet d'identification : <?php echo $this->jetBraldun ?> <br />
	<?php if ($this->identificationReussieOk === true): ?>
		Vous avez r&eacute;ussi &agrave; identifier la rune n&deg; <?php echo $this->rune["id_rune"] ?><br />
		<?php if ($this->rune["image"] != ""): ?>
	    	<img src="<?php echo $this->config->static->url?>/images/runes/<?php echo $this->rune["image"]?>" title="<?php echo $this->rune["type"]?> (<?php echo $this->rune["id_rune"]?>)" />
	   	<?php endif; ?>
	   	
	   	<?php if ($this->rune["id_braldun_possesseur"] != null) :?>
	   		<br /><br /><?php echo $this->rune["prenom_braldun_possesseur"]?> <?php echo $this->rune["nom_braldun_possesseur"]?> (<?php echo $this->rune["id_braldun_possesseur"]?>) a été prévenu de cette identification.
	   		<br /><br />
	   	<?php endif;?>
	<?php else: ?>
		Vous avez manqu&eacute; votre identification sur la rune n&deg; <?php echo $this->rune["id_rune"] ?>
		<?if ($this->jetBraldunLoin === true) :?>
			<br />et vous &ecirc;tes loin d'identifier cette rune...
		<?php endif; ?>
		<br /><br />
	<?php endif; ?>
<?php endif; ?>

<?php if ($this->nb_px == 0) : ?>
	Vous n'avez gagn&eacute; aucun PX<br /><br /> 
<?php else: ?>
	Vous avez gagn&eacute; <?php echo $this->nb_px?> PX<br /><br />
<?php endif; ?>