<div class='comp_titre'>Lacher une charrette</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>

	 <? if ($this->possedeCharrette === false) : ?>
	 	Vous n'avez pas de charrette...
	 <? else: ?>
		 Pour <?=$this->nb_pa ?> PA, vous pouvez lacher une charrette. <br><br>
	 <? endif; ?>
	 <br>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->possedeCharrette === true) : ?>
<input type='button' class='button1' id='bouton_lachercharrette' value='Lacher une charrette !' onClick='this.disabled=true;_get_("/competences/DoAction?caction=do_competence_lachercharrette");'>
<? endif ?>
<? include("commun_fermer.phtml") ?>