 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <? if ($this->mangerNbAlimentOk === true && $this->mangerBalanceOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez manger 1 aliment. <br><br>
	 	
	 	Aliment &agrave; manger : <br />
 		<select name='valeur_1' id="valeur_1" onChange="if ($('valeur_1').value==-1) {$('bouton_manger').disabled=true } else {$('bouton_manger').disabled=false }">
			<option value='-1'>(Choisissez un aliment)</option>
			<? foreach ($this->tabAliments as $p) : ?>
				<option value="<?=$p["id_aliment"] ?>"><?=htmlspecialchars($p["nom"]) ?> de qualit&eacute; <?=htmlspecialchars($p["qualite"]) ?>,
				 : + <?=$p["bbdf"]?> % </option>
			<? endforeach; ?>
		</select>
		
	 <? else: ?>
		 <? if ($this->mangerNbAlimentOk != true) :?>
		 	Vous n'avez pas assez d'aliment pour manger<br />
		 <? endif; ?>
		 <? if ($this->mangerBalanceOk != true) :?>
		 	Votre estomac est d&eacute;j&agrave; bien rempli !<br />
		 <? endif; ?>
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->mangerNbAlimentOk === true && $this->mangerBalanceOk === true) : ?>
<input type='button' class='button1' id='bouton_manger' value='Manger !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_manger");'>
<? endif ?>
