 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
	 <? if ($this->mangerNbRationOk === true && $this->mangerBalanceOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez manger 1 ration
	 <? else: ?>
		 <? if ($this->mangerNbRationOk != true) :?>
		 	Vous n'avez pas assez de ration pour manger<br />
		 <? endif; ?>
		 <? if ($this->mangerBalanceOk != true) :?>
		 	Votre estomac est d&eacute;j&agrave; bien rempli !<br />
		 <? endif; ?>
	 <? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->mangerNbRationOk === true && $this->mangerBalanceOk === true) : ?>
<input type='button' class='button1' id='bouton_manger' value='Manger !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_manger");'>
<? endif ?>
