 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

 <?=htmlspecialchars($this->environnement) ?>: <?=$this->nb_pa ?> PA, <?=$this->nb_cases ?>
 <?php if ($this->nb_cases == 1) :?>
   case
 <?php else :?>
   cases
 <?php endif; ?>
<br /><br />


<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	<?php if ($this->marcherPossible == false) : ?>
 		Vous &ecirc;tes entour&eacute;, vous ne pouvez pas marcher !
  	<?php endif; ?>
  
  <? if ($this->effetMot == true) : ?>
  	Votre &eacute;quipement a de l'effet sur le co&ucirc;t en PA ou sur le nombre de cases possible.<br /><br />
  <? endif; ?>
  
  <table align='center'>
   <tr>
     <th>Position [x;y]</th>
   </tr>
   <tr>
     <td>
     <table class='comp_marcher_position'>
     	<?php $col=null ?>
		<?php foreach ($this->tableau as $case) : ?>
			<?php if ($case["change_level"] == 1 && $col == "ok") :
	          echo "</tr>";
			endif; ?>
			<?php if ($case["change_level"] == true) : 
				$col="ok"; ?>
	                  <tr>
			<?php endif; ?>
	          <td class='comp_marcher_position_td' nowrap>
	           <?=$case["display"] ?><br />
	
			<?php if ($case["valid"] == true) : ?>
	            <input type='radio' name='valeur_1' id='valeur_1' value='<?php echo $case["x_offset"]."h".$case["y_offset"] ?>' <?=$case["default"]?>>
			<?php else: ?>
				&nbsp;
			<?php endif; ?>
	          </td>
       <?php endforeach; ?>
       </tr>
     </table>
     </td>
    </tr>
  </table>
<? endif ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->marcherPossible === true) : ?>
<input type='button' class='button1' value='Marcher !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_marcher");'>
<? endif ?>
