<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<? else: ?>
	<? include("commun_text_resultat.phtml") ?>
	D&eacute;placement r&eacute;ussi jusqu'en : <br />
	x=<?=$this->user->x_braldun?>, y=<?=$this->user->y_braldun?> 
	
	<? if ($this->user->z_braldun != 0) : ?>
		et z=<?=$this->user->z_braldun?>
	<? endif;?>
	
	<br /><br />
	 
	Type de terrain de d&eacute;part : <?=htmlspecialchars($this->environnement)?><br /><br />
	
	<? if ($this->estCrevasseEvenement === true) : ?>
		<? Zend_Loader::loadClass("Bral_Helper_Crevasse");
		   echo Bral_Helper_Crevasse::afficheResultat($this->user);
		?>
	<br />
	<? endif;?>
<? endif; ?>