 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

<?php if ($this->estEngage == false && $this->estSurRoute == false) : ?>
 <?=htmlspecialchars($this->environnement) ?>: <?=$this->nb_pa ?> PA, <?=$this->nb_cases ?>
 <?php if ($this->nb_cases == 1) :?>
   case
 <?php else :?>
   cases
   <br /><br />
 <?php endif; ?>
<?php endif; ?>


<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
 
 	<?php if ($this->estEngage == true) : ?>
	car vous &ecirc;tes actuellement engag&eacute; <br>et il faut au miminum <?=$this->nb_pa ?> PA pour marcher.
	<?php endif; ?>

<?php else : ?>

	<?php if ($this->estEngage == true) : ?>
	Vous &ecirc;tes actuellement engag&eacute;, vous pouvez marcher de <?=$this->nb_cases?> case pour <?=$this->nb_pa ?> PA.
	<?php endif; ?>
	
	<?php if ($this->estSurRoute == true) : ?>
	Vous &ecirc;tes actuellement sur une route, <br>
	vous pouvez donc marcher de <?=$this->nb_cases?> case<? if ($this->nb_cases > 1) : echo "s"; endif;?> pour <?=$this->nb_pa ?> PA !
	<?php endif; ?>

	<?php if ($this->marcherPossible == false) : ?>
 		Vous &ecirc;tes entour&eacute;, vous ne pouvez pas marcher !
  	<?php endif; ?>
  
  <? if ($this->effetMot == true) : ?>
  	Votre &eacute;quipement a de l'effet sur le co&ucirc;t en PA ou sur le nombre de cases possible.<br /><br />
  <? endif; ?>
  
  <? include('marcher_tableau.phtml'); ?>
<? endif ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->marcherPossible === true) : ?>
<input type='button' class='button1' value='Marcher !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_marcher");'>
<? endif ?>
