<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else: ?>
	<?php include("commun_text_resultat.phtml") ?>
	D&eacute;placement r&eacute;ussi jusqu'en : <br />
	x=<?php echo $this->user->x_braldun?>, y=<?php echo $this->user->y_braldun?> 
	
	<?php if ($this->user->z_braldun != 0) : ?>
		et z=<?php echo $this->user->z_braldun?>
	<?php endif;?>
	
	<br /><br />
	 
	Type de terrain de d&eacute;part : <?php echo htmlspecialchars($this->environnement)?><br /><br />
	
	<?php if ($this->estCrevasseEvenement === true) : ?>
		<?php Zend_Loader::loadClass("Bral_Helper_Crevasse");
		   echo Bral_Helper_Crevasse::afficheResultat($this->user);
		?>
	<br />
	<?php endif;?>
<?php endif; ?>