 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

Pour construire une palissade, vous devez avoir dans votre charrette au minimum
<?php echo $this->nRondinsNecessaires?> rondin<?php if ($this->nRondinsNecessaires > 1): echo "s"; endif;?>.


<?php if ($this->monterPalissadeCharretteOk == false) : ?>
 Vous n'avez pas de charrette ?!
<?php elseif ($this->nRondinsSuffisants == false) : ?>
 Vous n'avez pas assez de rondins.
<?php elseif ($this->monterPalissadeOk == false) : ?>
 Vous ne pouvez pas monter de palissade aux alentours de vous.
<?php else : ?>
  <table align='center'>
   <tr>
     <th>Position [x;y]</th>
   </tr>
   <tr>
     <td>
     <table class='comp_marcher_position'>
     	<?php $col=null ?>
		<?php foreach ($this->tableau as $case) : ?>

		<?php if ($case["change_level"] == 1 && $col == "ok") :
          echo "</tr>";
		 endif; ?>
		<?php if ($case["change_level"] == true) : 
			$col="ok"; ?>
                  <tr>
		<?php endif; ?>
          <td class='comp_marcher_position_td' nowrap>
           <?php echo $case["display"] ?><br />

		<?php if ($case["valid"] == true) : ?>
            <input type='radio' name='valeur_1' id='valeur_1' value='<?php echo $case["x_offset"]."h".$case["y_offset"] ?>' <?php echo $case["default"]?>>
		<?php else: ?>
			&nbsp;
		<?php endif; ?>
          </td>
       <?php endforeach; ?>
       </tr>
     </table>
     </td>
    </tr>
  </table>
<?php endif ?>
</div>

<br />
<?php if ($this->assezDePa === true && $this->monterPalissadeOk === true && $this->nRondinsSuffisants === true) : ?>
<input type='button' class='button1' value='Monter une palissade !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_monterpalissade");'>
<?php endif ?>
