<div class='comp_titre'>Monter une palissade</div>

 <div class='comp_contenu'>
	 <div id='monterpalissade_text' style="display:block"  onClick="javascript:switch2div('monterpalissade_text','monterpalissade_copie');">
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true): ?>
			Vous avez mont&eacute; une palissade avec les caract&eacute;ristiques suivantes : <br>
			Position : <?=$this->palissade["x_palissade"] ?>, <?=$this->palissade["y_palissade"] ?><br>
			Armure naturelle : <?=$this->palissade["armure_naturelle_palissade"] ?><br>
			PV Palissade : <?=$this->palissade["pv_restant_palissade"] ?><br>
			Date de destruction : <?=$this->palissade["date_fin_palissade"] ?>
		<? endif; ?>
		<br>
	 </div>
	 
	 <div id='monterpalissade_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
		if ($this->okJet1 === true) {
			echo "Vous avez mont&eacute; une palissade avec les caract&eacute;ristiques suivantes :";
			echo "
";
			echo "Position : ".$this->palissade["x_palissade"].", ".$this->palissade["y_palissade"];
			echo "
";
			echo "Armure naturelle : ".$this->palissade["armure_naturelle_palissade"];
			echo "
";
			echo "PV Palissade : ".$this->palissade["pv_restant_palissade"];
			echo "
";
			echo "Date de destruction : ".$this->palissade["date_fin_palissade"];
		}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('monterpalissade_text','monterpalissade_copie');">
<? include("commun_fermer.phtml") ?>