<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true): ?>
		Vous avez mont&eacute; une palissade !<br />
		Il vous a fallu <?php echo $this->nRondinsNecessaires ?> rondins.<br /><br />
		
		La palissade a les caract&eacute;ristiques suivantes : <br />
		Position : <?php echo $this->palissade["x_palissade"] ?>, <?php echo $this->palissade["y_palissade"] ?><br />
		Armure naturelle : <?php echo $this->palissade["armure_naturelle_palissade"] ?><br />
		PV Palissade : <?php echo $this->palissade["pv_restant_palissade"] ?><br />
		Date de destruction : le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->palissade["date_fin_palissade"]); ?>
<?php endif; ?>