<div class='comp_titre'>Monter une palissade</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->monterPalissadeOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez monter une palissade. <br>
	 <? else:?>
		 Vous ne pouvez pas monter de palissade ici.<br>
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true && $this->monterPalissadeOk === true) : ?>
<input type='button' class='button1' id='bouton_monterpalissade' value='Monter une palissade !' onClick='_get_("/competences/DoAction?caction=do_competence_monterpalissade");'>
<? endif ?>
<? include("commun_fermer.phtml") ?>