<?php include("commun_text_resultat.phtml") ?>
<?php if ($this->okJet1 === true):?>
	<?php if ($this->trouve === true): ?>
		Le monstre le plus proche, de type : <?php echo $this->monstre["nom_type_monstre"] ?><br /> 
		se situe  
		<?php if ($this->proche === true): ?>
			en X=<?php echo $this->monstre["x_monstre"]?> et Y=<?php echo $this->monstre["y_monstre"]?><br /> 
		<?php endif; ?>
		<?php if ($this->user->y_braldun < $this->monstre["y_monstre"] && $this->user->x_braldun == $this->monstre["x_monstre"]): ?>
		en direction du Nord
		<?php elseif ($this->user->y_braldun < $this->monstre["y_monstre"] && $this->user->x_braldun < $this->monstre["x_monstre"]): ?>
		en direction du Nord Est
		<?php elseif ($this->user->y_braldun < $this->monstre["y_monstre"] && $this->user->x_braldun > $this->monstre["x_monstre"]): ?>
		en direction du Nord Ouest
		<?php elseif ($this->user->y_braldun > $this->monstre["y_monstre"] && $this->user->x_braldun == $this->monstre["x_monstre"]): ?>
		en direction du Sud 
		<?php elseif ($this->user->y_braldun > $this->monstre["y_monstre"] && $this->user->x_braldun < $this->monstre["x_monstre"]): ?>
		en direction du Sud Est		
		<?php elseif ($this->user->y_braldun > $this->monstre["y_monstre"] && $this->user->x_braldun > $this->monstre["x_monstre"]): ?>
		en direction du Sud Ouest
		<?php elseif ($this->user->y_braldun == $this->monstre["y_monstre"] && $this->user->x_braldun < $this->monstre["x_monstre"]): ?>
		en direction de l'Est
		<?php elseif ($this->user->y_braldun == $this->monstre["y_monstre"] && $this->user->x_braldun > $this->monstre["x_monstre"]): ?>
		en direction de l'Ouest
		<?php else: ?>
		sur place !
		<?php endif; ?>
	<?php else: ?>
		Aucun monstre de type <?php echo $this->nomTypeMonstre ?> n'a &eacute;t&eacute; trouv&eacute;e dans un rayon de <?php echo $this->rayon_max;?> cases
	<?php endif; ?>
<br />	
<?php endif; ?>
