<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if (count($this->tabTypeMonstrePistable) == 0) : ?>
 	Vous n'avez pas fait assez de connaissances des monstres pour pouvoir pister !<br />
<?php else: ?>
	<?php if ($this->rayon_precis == 1): $s=''; else: $s='s'; endif ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez pister un type de monstre <br />
	dans un rayon de <i>jet SAG + BM SAG</i> case(s) aux alentours<br />
 	et de mani&egrave;re pr&eacute;cise dans un rayon de <?php echo $this->rayon_precis ?> case<?php echo $s?>.<br /><br />
	<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').val() ==-1){$('#bouton_pister').attr('disabled', true) } else {$('#bouton_pister').attr('disabled',false) }">
		<option value='-1'>(Choisissez un type de monstre)</option>
		<?php foreach ($this->tabTypeMonstrePistable as $m) : ?>
				<option value="<?php echo $m["id_type_monstre"]?>"><?php echo $m["nom_type_monstre"]?></option>
		<?php endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button1' value='Pister !' id='bouton_pister' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_pister");' disabled>
<?php endif; ?>
<br />
<?php if (count($this->tabTypeMonstreCdm) != 0) : ?>
	<br />Connaissance des monstres d&eacute;j&agrave; effectu&eacute;es :<br /><br />
	<table align='center' width='100%'>
	<tr><th width="25%">Type de monstre</th>
	<?php foreach ($this->tabTailleMonstre as $t) : ?>
		<th width="<?php echo 75/count($this->tabTailleMonstre)?>%"><?php echo $t["nom_taille_m_monstre"]?></th>
	<?php endforeach;?>
	</tr>
	<?php foreach ($this->tabTypeMonstreCdm as $t) : ?>
			<tr>
			<td> <?php echo $t["nom_type_monstre"]?> </td>
			<?php foreach ($this->tabTailleMonstre as $taille) : $tailleTrouve = false;?>
				<?php foreach ($t["tailles"] as $tailleCdm) : ?>
					<?php if ($tailleCdm["taille"] == $taille["nom_taille_m_monstre"] ): $tailleTrouve = true;?>
						<td align='center'><font color='red'><?php echo $tailleCdm["nb_manquant"]?></font></td>
					<?php endif;?>
				<?php endforeach; ?>
				<?php if ($tailleTrouve == false) : ?>
					<td align='center'><font color='green'><?php echo $taille["nb_cdm_taille_monstre"]?>/<?php echo $taille["nb_cdm_taille_monstre"]?></font></td>
				<?php endif;?>
			<?php endforeach;?>
			</tr>
	<?php endforeach; ?>
	</table>
<?php endif; ?>
</div>