 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	<?php if ($this->user->est_intangible_braldun == "oui") : ?>
		Vous ne pouvez pas provoquer en étant intangible.
 	<?php elseif ($this->nMonstres == 0): ?>
 		Il n'y a pas de monstre &agrave; provoquer ici....
 	<?php elseif ($this->assezDePa !== true): ?>
 		Vous n'avez pas assez de PA<br />
 	<?php else: ?>
 		Pour <?php echo $this->nb_pa?> PA, vous pouvez provoquer :<br /><br />
 		
		Un monstre<br />
			<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('valeur_1').value==-1){$('bouton_provoquer').disabled=true } else {$('bouton_provoquer').disabled=false }">
			<option value='-1'>(Choisissez un monstre)</option>
			<?php foreach ($this->tabMonstres as $m) : ?>
			<option value="<?php echo $m["id_monstre"]?>"><?php echo $m["nom_monstre"]?> <?php echo $m["taille_monstre"]?>  (<?php echo $m["id_monstre"]?>)</option>
			<?php endforeach; ?>
			</select><br /><br />
	<?php endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->nMonstres > 0) : ?>
<input type='button' class='button1' value='Provoquer !' id='bouton_provoquer' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_provoquer");' disabled>
<?php endif ?>
