<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Provocation de <?=$this->monstre["nom_monstre"]?> <?=$this->monstre["taille_monstre"]?>  (<?=$this->monstre["id_monstre"]?>)
	<br><br>
	 Votre jet de vigueur : <?=$this->jetBraldun?><br>
	 Jet de sagesse du monstre : <?=$this->jetMonstre?><br>
	 
	 <br>
	 
	 <? if ($this->provoquerOk === true) : ?>
	 	Vous avez provoqu&eacute; avec succ&egrave;s. <br>	
	 	
	 	Vous êtes maintenant la cible privil&eacute;gi&eacute;e de ce monstre...<br /><br />
	 	
	 <? else: ?>
	 	Le monstre ne semble pas vous avoir vu.<br>
	 <? endif; ?>

<? else: ?>
	Vous avez manqu&eacute; votre provocation.<br />
<? endif; ?>