 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	<? if ($this->user->est_intangible_braldun == "oui") : ?>
		Vous ne pouvez pas provoquer en étant intangible.
 	<? elseif ($this->nMonstres == 0): ?>
 		Il n'y a pas de monstre &agrave; provoquer ici....
 	<? elseif ($this->assezDePa !== true): ?>
 		Vous n'avez pas assez de PA<br />
 	<? else: ?>
 		Pour <?=$this->nb_pa?> PA, vous pouvez provoquer :<br /><br />
 		
		Un monstre<br />
			<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_provoquer').disabled=true } else {$('bouton_provoquer').disabled=false }">
			<option value='-1'>(Choisissez un monstre)</option>
			<? foreach ($this->tabMonstres as $m) : ?>
			<option value="<?=$m["id_monstre"]?>"><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true && $this->nMonstres > 0) : ?>
<input type='button' class='button1' value='Provoquer !' id='bouton_provoquer' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_provoquer");' disabled>
<? endif ?>
