<?php include("commun_text_resultat.phtml") ?>

 Votre jet de sagesse : <?php echo $this->jetBraldun?><br /> 
 
 Jet de <?php echo $this->caract?> de <?php echo $this->braldun["prenom_braldun"]?> <?php echo $this->braldun["nom_braldun"]?> (<?php echo $this->braldun["id_braldun"]?>): <?php echo $this->jetCible?><br /><br />

 <?php if ($this->psychologieOk === true) : ?>
 Vous avez réussi votre psychologie, 
<?php echo $this->braldun["prenom_braldun"]?> <?php echo $this->braldun["nom_braldun"]?> (<?php echo $this->braldun["id_braldun"]?>)
 n'a maintenant plus de malus de <?php echo $this->caract?> pour le restant de son tour.
 <?php else: ?>
 Vous avez raté votre psychologie.
 <?php endif;?>
 <br /><br />