<div class='comp_titre'>Ramasser</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->ramasserOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez ramasser des objets sur la case. <br /><br />
	 	
	 <? else: ?>
	 Il n'y a rien &agrave; ramasser ici...
	 <? endif; ?>
<? endif ?>
</div>

</form>
<br />
<?php if ($this->assezDePa == true && $this->ramasserOk === true) : ?>
<input type='button' class='button1' id='bouton_ramasser' value='Ramasser !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_ramasser");'>
<? endif ?>
<? include("commun_fermer.phtml") ?>