 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>

	<? if ($this->ramasserGrainesEnvironnementOk !== true) : ?>
		 Vous ne pouvez ramasser des graines que dans un buisson.<br />
	<? else : ?>
		Pour <?=$this->nb_pa ?> PA, vous pouvez ramasser des graines dans ce buisson.<br /><br />
		
		Choisissez la destination des graines : <br />
		<select name="valeur_1" id="valeur_1" onchange="_get_('/competences/doaction?caction=ask_competence_ramassergraines&valeur_1='+this.value);">
	 		<option value="-1">(Choisissez une destination)</option>
			<? foreach($this->destinationRamasser as $d) :?>
				<option value="<?=$d["id_destination"] ?>" <?=$d["selected"]?>><?=$d["texte"] ?></option>
			<? endforeach; ?>
		</select>
	<? endif;?>
	
	<? if ($this->idDestinationCourante != null && $this->placeDispo !== true) :?>
	 	Vous n'avez pas assez de place.
	<? endif;?>
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->ramasserGrainesEnvironnementOk === true && $this->placeDispo !== false && $this->idDestinationCourante != null) : ?>
<input type='button' class='button1' id='bouton_abattrearbre' value='Ramasser des graines !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_ramassergraines");'>
<? endif ?>
