<div class='comp_titre'>Ramasser</div>

 <div class='comp_contenu'>
	 <div id='ramasser_text' style="display:block"  onClick="javascript:switch2div('ramasser_text','ramasser_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		Vous avez ramass&eacute; : <br>
		Rune : <?=$this->nbRunes ?><br>
		<br>
	 </div>
	 
	 <div id='ramasser_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
			echo "Vous avez ramass&eacute; : ";
			echo "
";
			echo "Rune : ".$this->nbRunes;
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('ramasser_text','ramasser_copie');">
<? include("commun_fermer.phtml") ?>