 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 
    <? if ($this->estIntangible) : ?>
	Vous &ecirc;tes actuellement intangible, vous ne pouvez pas ramasser le ballon...<br />
	<? elseif ($this->user->est_soule_braldun == "non") : ?>
		Aucun match de soule en cours. <br>
	<? elseif ($this->ramasserballonOk !== true) : ?>
		Il n'y a pas de ballon sur la case ! <br>
	<? else : ?>
		Vous pouvez ramasser le ballon qui est à vos pieds !<br>
	<? endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->ramasserballonOk === true) : ?>
<input type='button' class='button1' id='bouton_ramasserballon' value='Ramasser le ballon !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_ramasserballon");'>
<? endif ?>