 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
 	<? if ($this->user->est_intangible_braldun == 'oui') :?>
		Vous êtes actuellement intangible, vous ne pouvez pas utiliser cette compétence.<br><br>
	<? elseif ($this->nBralduns == 0): ?>
 		Il n'y a rien aucun Braldûn Ko ici, vous ne pouvez pas utiliser cette compétence...<br />
 	<? elseif ($this->nAliments == 0): ?>
 		Vous n'avez pas d'aliment disponible, vous ne pouvez pas utiliser cette compétence...<br />
 	<? else: ?>
 		Pour <?=$this->nb_pa?> PA, vous pouvez tenter de réanimer un Braldûn KO.<br /><br />
 		
 		Seul les Braldûns de niveau inférieur à votre niveau de sagesse x 2 peuvent être réanimés.<br><br>
 		<? if ($this->nBralduns > 0): ?>
 		 Choississez un Braldûn KO: <br />
 			<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1)) { $('bouton_reanimer').disabled=true } else { $('bouton_reanimer').disabled=false }">
			<option value='-1'>(Choisissez un Braldûn KO)</option>
			<? foreach ($this->tabBralduns as $h) : ?>
			<option value="<?=$h["id_braldun"]?>"><?=$h["prenom_braldun"]?> <?=$h["nom_braldun"]?> (<?=$h["id_braldun"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
		<? endif;?>
		
		<? if ($this->nAliments > 0): ?>
 		 Choississez un aliment: <br />
 			<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1)) { $('bouton_reanimer').disabled=true } else { $('bouton_reanimer').disabled=false }">
			<option value='-1'>(Choisissez un aliment)</option>
			<? foreach ($this->tabAliments as $k => $p) : ?>
				<option value="<?=$p["id_aliment"] ?>"><?=htmlspecialchars($p["nom"]) ?> : + <?=$p["bbdf"]?> % (recette <?=$p["recette"]?>) dans votre <?$p["type"]?></option>
			<? endforeach; ?>
			</select><br /><br />
		<? endif;?>
	<? endif; ?>
	
 </div>

<br />
<?php if ($this->assezDePa == true && $this->user->est_intangible_braldun == 'non' && $this->nBralduns > 0 && $this->nAliments > 0) : ?>
<input type='button' class='button1' value='Réanimer !' id='bouton_reanimer' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_reanimer");' disabled>
<? endif ?>
