<? include("commun_text_resultat.phtml") ?>

 Votre jet de sagesse : <?=$this->jetBraldun?><br> 
 
 Jet de <?=$this->caract?> de <?=$this->braldun["prenom_braldun"]?> <?=$this->braldun["nom_braldun"]?> (<?=$this->braldun["id_braldun"]?>): <?=$this->jetCible?><br><br>

 <? if ($this->reanimationOk === true) : ?>
 Vous avez réussi la réanimation, 
<?=$this->braldun["prenom_braldun"]?> <?=$this->braldun["nom_braldun"]?> (<?=$this->braldun["id_braldun"]?>).
 <? else: ?>
 Vous avez raté la réanimation.
 <? endif;?>
 <br><br>