<?php include("commun_text_resultat.phtml") ?>

 Cible de la réanimation : <?php echo $this->braldun["prenom_braldun"]?> <?php echo $this->braldun["nom_braldun"]?> (<?php echo $this->braldun["id_braldun"]?>).<br /><br />

 Votre premier jet de sagesse : <?php echo $this->jetBraldunPourForce?><br /> 
 Jet de Force de la cible : <?php echo $this->jetCibleForce?><br /><br />
 
 Votre second jet de sagesse : <?php echo $this->jetBraldunPourSagesse?><br /> 
 Jet de Sagesse de la cible : <?php echo $this->jetCibleSagesse?><br /><br />
 
 Votre troisième jet de sagesse : <?php echo $this->jetBraldunPourAgilite?><br /> 
 Jet d'Agilite de la cible : <?php echo $this->jetCibleAgilite?><br /><br />
 
 Votre quatrième jet de sagesse : <?php echo $this->jetBraldunPourVigueur?><br /> 
 Jet de Vigueur de la cible : <?php echo $this->jetCibleVigueur?><br /><br />

 <?php if ($this->nbReussi > 3) : ?>
 
   Vous avez réussi la réanimation, 
   <?php echo $this->braldun["prenom_braldun"]?> <?php echo $this->braldun["nom_braldun"]?> (<?php echo $this->braldun["id_braldun"]?>) est de nouveau debout.
	
	Il possède maintenant <?php echo $this->pvRestants?> Pv.<br />
	 <?php if ($this->nbReussi > 3) : ?>
	 	Sa balance de faim est remontée à <?php echo $this->balanceFaim?>.<br />
	 <?php endif; ?>

 <?php else: ?>
 Vous avez raté la réanimation de <?php echo $this->braldun["prenom_braldun"]?> <?php echo $this->braldun["nom_braldun"]?> (<?php echo $this->braldun["id_braldun"]?>).
 <?php endif;?>
 <br /><br />