 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
 	<?php if ($this->user->est_intangible_braldun == 'oui') :?>
		Vous êtes actuellement intangible, vous ne pouvez pas utiliser cette compétence.<br /><br />
	<?php elseif ($this->nBralduns == 0): ?>
 		Il n'y a rien aucun Braldûn Ko ici, vous ne pouvez pas utiliser cette compétence...<br />
 	<?php elseif ($this->nAliments == 0): ?>
 		Vous n'avez pas d'aliment disponible, vous ne pouvez pas utiliser cette compétence...<br />
 	<?php else: ?>
 		Pour <?php echo $this->nb_pa?> PA, vous pouvez tenter de réanimer un Braldûn KO.<br /><br />
 		
 		Seul les Braldûns de niveau inférieur à votre niveau de sagesse x 2 peuvent être réanimés.<br /><br />
 		<?php if ($this->nBralduns > 0): ?>
 		 Choississez un Braldûn KO: <br />
 			<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').val() ==-1 || $('#valeur_2').val() ==-1) { $('#bouton_reanimer').attr('disabled', true) } else { $('#bouton_reanimer').attr('disabled',false) }">
			<option value='-1'>(Choisissez un Braldûn KO)</option>
			<?php foreach ($this->tabBralduns as $h) : ?>
			<option value="<?php echo $h["id_braldun"]?>"><?php echo $h["prenom_braldun"]?> <?php echo $h["nom_braldun"]?> (<?php echo $h["id_braldun"]?>)</option>
			<?php endforeach; ?>
			</select><br /><br />
		<?php endif;?>
		
		<?php if ($this->nAliments > 0): ?>
 		 Choississez un aliment: <br />
 			<select name='valeur_2' id="valeur_2" onchange="javascript:if ($('#valeur_1').val() ==-1 || $('#valeur_2').val() ==-1) { $('#bouton_reanimer').attr('disabled', true) } else { $('#bouton_reanimer').attr('disabled',false) }">
			<option value='-1'>(Choisissez un aliment)</option>
			<?php foreach ($this->tabAliments as $k => $p) : ?>
				<option value="<?php echo $p["id_aliment"] ?>"><?php echo htmlspecialchars($p["nom"]) ?> : + <?php echo $p["bbdf"]?> % (recette <?php echo $p["recette"]?>) dans votre <?php echo $p["type"]?></option>
			<?php endforeach; ?>
			</select><br /><br />
		<?php endif;?>
	<?php endif; ?>
	
 </div>

<br />
<?php if ($this->assezDePa == true && $this->user->est_intangible_braldun == 'non' && $this->nBralduns > 0 && $this->nAliments > 0) : ?>
<input type='button' class='button1' value='Réanimer !' id='bouton_reanimer' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_reanimer");' disabled>
<?php endif ?>
