 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 
 
 <? if ($this->rayon_precis == 1): $s=''; else: $s='s'; endif ?>
 Pour <?=$this->nb_pa ?> PA, vous pouvez rechercher des plantes <br />
 dans un rayon de <i>jet SAG + BM SAG</i> case(s) aux alentours<br />
 et de mani&egrave;re pr&eacute;cise dans un rayon de <?=$this->rayon_precis ?> case<?=$s?>.<br /><br />
</div>

<? 
$disabled = "";
if ($this->avecChoix) : 
$disabled = "disabled"
?>
Vous ma&icirc;trisez assez la recherche de plante pour choisir ce que vous souhaitez rechercher.<br>
	<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1){$('bouton_rechercherplante').disabled=true } else {$('bouton_rechercherplante').disabled=false }">
	<option value='-1'>(Choississez le type de recherche)</option>
	<optgroup label="Recherche classique" style="font-weight:bold"></optgroup>
	<option value="-2">Plante la plus proche</option>
	<optgroup label="Recherche par type" style="font-weight:bold"></optgroup>
	<? foreach ($this->tabChoix as $k => $v) : ?>
	<option value="<?=$k?>"><?=$v["categorie_type_plante"]?> : <?=$v["nom_type_plante"]?> - <?=$v["nom_type_partieplante"]?></option>
	<? endforeach; ?>
	</select><br /><br />

<? else:?>
<input type='hidden' id='valeur_1' name='valeur_1' value='-3'>
<? endif;?>

<br />
<?php if ($this->assezDePa == true) : ?>
<input type='button' class='button1' id="bouton_rechercherplante" value='Rechercher une plante !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_rechercherplante");' <?=$disabled?>>
<? endif ?>
