 <input type='hidden' id='nb_valeurs-recherchermot' name='nb_valeurs-recherchermot' value='3'>
 <div class='comp_contenu'>
 
 	<?php if ($this->niveauAtelier != null && ($this->niveauAtelier == Bral_Util_Communaute::NIVEAU_EN_CONSTRUCTION || $this->niveauAtelier >= 0)) : ?>
  	 <?php echo Bral_Helper_Communaute::afficheNiveauAtelier($this->niveauAtelier); ?>
  	<?php elseif ($this->user->id_fk_communaute_braldun != null) : ?>
 		Votre communauté ne possède pas d'<?php echo Bral_Helper_Communaute::afficheNiveauAtelier(null, "atelier")?>.<br />
  	<?php endif;?>
  	 
  <?php if (count($this->motsRuniques) > 0) : ?>
  
	 <?php if ($this->rechercherMotOk === true) : ?>
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez rechercher un mot runique ...<br /><br />
	 Ne sont affich&eacute;s que les mots disponibles suivant votre niveau de sagesse.<br /><br />
	 
	 <select name="valeur_1-recherchermot" id="valeur_1-recherchermot" onchange="_get_('/competences/doaction?caction=ask_competence_recherchermot&id_mot='+this.value);">
	 	<option value="-1">(Choisissez un mot)</option>
	 	<?php foreach($this->motsRuniques as $k => $v) : ?>
	 		<option value="<?php echo $k?>" <?php echo $v["selected"]?>><?php echo $v["suffixe_mot_runique"]?></option>
	 	<?php endforeach; ?>
	 </select>
	 <?php if (isset($this->motCourant) ) : ?>
	 <br /><br />
		Glissez une rune sur l'emplacement ci-dessous. L'ordre des runes a une importance,
		vous pouvez les r&eacute;organiser avant de valider la recherche.<br /><br />
		Tous les emplacements runiques doivent &ecirc;tre utilis&eacute;s.<br />
			<br />
			<?php $js="
				function calculNbRuneRecherche(total){ 
					$( '#group1, #group2' ).sortable({
							connectWith: '.liste_runes',
							placeholder: 'ui-state-highlight',
							receive: function(event, ui) { 
							
								liste = $('#group2').sortable('serialize');  
								if (liste.length > 0) {
									tliste = liste.split('&'); 
									nbPlacees = tliste.length;
								} else { 
									nbPlacees = 0; 
								}
								$('#valeur_2-recherchermot').val(nbPlacees); 
								nb = total - nbPlacees;
								$('#dispo').html(nb);
								
								if (nb != 0) { 
									$('#bouton_recherchermot').attr('disabled', true); 
								} else { 
									$('#bouton_recherchermot').attr('disabled', false); 
								}
								text = '';
								val3 = '';
								s = '';
								for (i = 0; i < nbPlacees; i++) {
									text = text + ' ' + $('#item_'+tliste[i].substr(7, tliste[i].length-7))[0].alt;
									if (i > 0) {
										s = 's';
									}
									val3 = val3 + tliste[i].substr(7, tliste[i].length-7) + ',';
								}
								
								$('#valeur_3-recherchermot').val(val3);
								text = 'Rune' + s + ' : ' + text;
								$('#rune_text').html(text);
							}
						}).disableSelection();
					}
					calculNbRuneRecherche(".$this->motCourant["nb_runes"].");
				" ?>
			
			<?php if (count($this->runes) > 0) : ?>
				<input type="button" class='button1' value="Choisir les runes" onclick="<?php echo $js ?>; $('#choix_runes_recherche').show();this.style.display='none';">
			
				<div id="choix_runes_recherche" style="display:none">
				
				<br />
					<?php if ($this->motCourant["nb_runes"] > 1): $s="s"; else:$s=""; endif; ?>Sur <?php echo $this->motCourant["nb_runes"]?> emplacement<?php echo $s?> au total, il en reste <label id="dispo"><?php echo $this->motCourant["nb_runes"]?></label>.
					<br />
					<label id='rune_text'></label>
					<div id="group2" class="liste_runes" style="height:80px">
					</div>
					
					<h3 class="handle">Vos runes disponibles</h3>
					
					<div id="group1" class="liste_runes" style="height:130px ;overflow:auto">
						<?php 
						$i = 0;
							foreach($this->runes as $k => $v) : ?>
								<img id="item_<?php echo $k ?>" class="rune" src="<?php echo $this->config->url->static?>/images/runes/<?php echo $v["image_type_rune"]?>" title="<?php echo $v["nom_type_rune"]?> : <?php echo $v["effet_type_rune"]?>" alt="<?php echo $v["nom_type_rune"] ?>" style="cursor:pointer;"/>
							<?php endforeach; ?>
					</div>
						
					<br />
					<input type="hidden" id="valeur_2-recherchermot" name="valeur_2-recherchermot">
					<input type="hidden" id="valeur_3-recherchermot" name="valeur_3-recherchermot">
					
				</div>
			<?php else: ?>
				Vous n'avez aucune rune dans votre laban
			<?php endif; ?>
		<?php endif;?>
	 <?php else: ?>
		Vous n'avez aucune rune pour rechercher...
	 <?php endif; ?>
 <?php else: ?>
	Vous n'avez pas assez de sagesse pour rechercher un mot.
 <?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->rechercherMotOk === true) : ?>
	<input type='button' class='button1' id='bouton_recherchermot' value='Rechercher !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_recherchermot&id_mot="+$("#valeur_1-recherchermot").val(), "recherchermot");' disabled>
<?php endif ?>