<?php include("commun_text_resultat.phtml") ?>
<?php if ($this->okJet1 === true):?>
	Vous avez recherch&eacute; <?php echo $this->libelleRecherche?>.<br />
	<?php if ($this->trouve === true): ?>
		<?php if ($this->proche === true): ?>
			La plante la plus proche, de cat&eacute;gorie : <?php echo $this->plante["categorie"] ?><br /> 
			se situe en : 
			X=<?php echo $this->plante["x_plante"]?> et Y=<?php echo $this->plante["y_plante"]?><br />
		<?php elseif ($this->proche === false): ?>
			La plante la plus proche, de cat&eacute;gorie : <?php echo $this->plante["categorie"] ?><br /> 
			se situe   
		<?php endif; ?>
		<?php if ($this->user->y_braldun < $this->plante["y_plante"] && $this->user->x_braldun == $this->plante["x_plante"]): ?>
		en direction du Nord.
		<?php elseif ($this->user->y_braldun < $this->plante["y_plante"] && $this->user->x_braldun < $this->plante["x_plante"]): ?>
		en direction du Nord Est.
		<?php elseif ($this->user->y_braldun < $this->plante["y_plante"] && $this->user->x_braldun > $this->plante["x_plante"]): ?>
		en direction du Nord Ouest.
		<?php elseif ($this->user->y_braldun > $this->plante["y_plante"] && $this->user->x_braldun == $this->plante["x_plante"]): ?>
		en direction du Sud.
		<?php elseif ($this->user->y_braldun > $this->plante["y_plante"] && $this->user->x_braldun < $this->plante["x_plante"]): ?>
		en direction du Sud Est.
		<?php elseif ($this->user->y_braldun > $this->plante["y_plante"] && $this->user->x_braldun > $this->plante["x_plante"]): ?>
		en direction du Sud Ouest.
		<?php elseif ($this->user->y_braldun == $this->plante["y_plante"] && $this->user->x_braldun < $this->plante["x_plante"]): ?>
		en direction de l'Est.
		<?php elseif ($this->user->y_braldun == $this->plante["y_plante"] && $this->user->x_braldun > $this->plante["x_plante"]): ?>
		en direction de l'Ouest.
		<?php else: ?>
		sur place !
		<?php endif; ?>
	<?php else: ?>
		Aucune plante n'a &eacute;t&eacute; trouv&eacute;e dans <br />
		un rayon de <?php echo $this->rayon_max;?> cases.
	<?php endif; ?>
<?php endif; ?>