 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
  <input type='hidden' id='valeur_1' name='valeur_1' value='go'>
 <div class='comp_contenu'>
 <? if ($this->rayon_precis == 1): $s=''; else: $s='s'; endif ?>
 Pour <?=$this->nb_pa ?> PA, vous pouvez rechercher des plantes <br />
 dans un rayon de <i>jet VIG + BM SAG</i> case(s) aux alentours<br />
 et de mani&egrave;re pr&eacute;cise dans un rayon de <?=$this->rayon_precis ?> cases<?=$s?>.<br /><br />
</div>

<br />
<?php if ($this->assezDePa == true) : ?>
<input type='button' class='button1' value='Rechercher une plante !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_rechercherplante");'>
<? endif ?>
