<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->okJet1 === true):?>

	Vous avez &eacute;tudi&eacute; 
	le mot <?php echo $this->motCourant["suffixe_mot_runique"]?> avec <?php echo $this->nbRunes ?> 
	rune<?php if ($this->nbRunes > 1) echo "s"; ?> <br /><br />
	 
	Ordre des runes :
	<br />
	<?php foreach($this->tabRunes as $k => $v) : ?>
		<?php echo $v["nom_type_rune"]?>
	<?php endforeach ?>
	<br />
	<?php foreach($this->tabRunes as $k => $v) : ?>
		<img id="item_<?php echo $k ?>" class="rune" src="<?php echo $this->config->static->url?>/images/runes/<?php echo $v["image_type_rune"]?>" title="<?php echo $v["nom_type_rune"]?>" alt="<?php echo $v["nom_type_rune"] ?>"/>
	<?php endforeach ?>
	<br /><br />
	
	<?php if ($this->nbPositionOk == 0 && $this->nbOkMalPlace == 0): ?>
		Vous alignez les runes sur le sol. Vous regardez attentivement .... <br />C'est votre estomac, une heure plus tard, 
		qui vous rappelle à l'ordre : il ne se passera jamais rien avec n'importe quelle rune posée.
	<?php elseif ($this->nbPositionOk == $this->motCourant["nb_runes"] && $this->nbOkMalPlace == 0) : ?>
		Vous alignez les runes sur le sol devant vous. <br />&Agrave; peine avez-vous pos&eacute; la dernière rune que vous êtes sur de vous : vous 
		venez de découvrir le mot runique <?php echo $this->motCourant["suffixe_mot_runique"]?>.<br /> 
		" Combien de temps cette combinaison fonctionnera t-elle ? "<br />
	<?php else : ?>
		Vous alignez les runes sur le sol devant vous. <br />Elles réagissent ! Il se passe quelque chose : <br />
		<?php if ($this->nbPositionOk == 1): ?>
			Vous avez la certitude qu'une des runes est bien positionnée.<br />
		<?php elseif ($this->nbPositionOk > 1): ?>
			Tout s'éclaire, <?php echo $this->nbPositionOk?> runes sont bien positionnées.<br />
		<?php endif; ?>
		<br />
		<?php if ($this->nbOkMalPlace == 1) : ?>
			L'ordre d'une rune n'est pas satisfaisante. Votre intuition vous indique qu'une rune est utile mais pas à sa place.<br />
		<?php elseif ($this->nbOkMalPlace > 1) :?>
			L'ordre de plusieurs runes n'est pas correct. <br />
			Votre intuition vous dit que <?php echo $this->nbOkMalPlace ?> runes sont utilisées
			dans le mot mais qu'elles ne sont pas à leur place.<br />
		<?php endif;?>
	<?php endif;?>
	<br />
	Notez bien toutes les informations citées ici, elles vous seront utiles pour les prochaines recherches ou chez un joallier.
<?php endif; ?>