<div class='comp_titre'>Recherche de Plante</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
 <? if ($this->nb_cases == 1): $s=''; else: $s='s'; endif ?>
 Pour <?=$this->nb_pa ?> PA, vous pouvez rechercher des plantes 
 à <?=$this->nb_cases ?> case<?=$s?> aux alentours.
<? endif ?>
</div>

</form>
<br>
<?php if ($this->assezDePa == true) : ?>
<input type='button' value='Rechercher une plante !' onClick='_get_("/competences/DoAction?caction=do_competence_rechercherplante");'>
<? endif ?>
<input type='button' value='Annuler' onClick='_get_("/interface/clear");'>