 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 	
 	<? if ($this->user->balance_faim_hobbit >= 2): ?>
 	Pour <?=$this->nb_pa ?> PA, vous pouvez récolter jusqu'à <?=$this->user->balance_faim_hobbit ?> éléments dans votre champ.<br><br>
 	
	 	<? if ($this->recolterChampOk !== true) : ?>
			Vous ne pouvez récolter un de vos champs qu'en étant dessus et il faut qu'il soit à l'état récoltable au préalable.
		<? else: ?>
			<select name="valeur_1" id="valeur_1" onChange="if (this.value != -1) { $('bouton_recolter').disabled=false; } else { $('bouton_recolter').disabled=true;}">
		 		<option value="-1">(Choisissez une destination)</option>
				<? foreach($this->destinationTransfert as $d) :?>
					<option value="<?=$d["id_destination"] ?>" <?=$d["selected"] ?>><?=$d["texte"] ?></option>
				<? endforeach; ?>
			</select>	
		<? endif; ?>
 	<? else: ?>
 		Votre balance de faim est trop basse pour pouvoir récolter quelque chose.<br><br>
 	<? endif;?>
	
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->recolterChampOk === true) : ?>
<input type='button' class='button1' id='bouton_recolter' value='Récolter !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_recolter");' disabled>
<? endif ?>
