<?php include("commun_text_resultat.phtml") ?>

Vous avez récolté votre champ situé en x:<?php echo $this->champ["x_champ"]?>, y:<?php echo $this->champ["y_champ"]?>. <br /><br />

Vous avez récupéré <?php echo $this->recolte?>.<br /><br />

<?php if ($this->placeDispo == false) : ?>
	Faute de place, certains éléments sont tombés au sol.<br /><br />
<?php endif;?>

<?php if ($this->taupesVivantes != null) : ?>
	La récolte a été affectée par : <br />
	<?php foreach($this->taupesVivantes as $taille => $numero) : ?>
		<?php foreach($numero as $num => $foo) : ?>
			1 taupe de taille <?php echo $taille?> (n°<?php echo $num?>)<br />
		<?php endforeach;?>
	<?php endforeach;?>
<?php endif;?>

<br />
<?php if ($this->champDetruit) : ?>
	Il n'y a plus rien à récolter dans le champ, il est passé en jachère.
	<br />
	Vous pouvez maitenant re-semer votre champ si vous le souhaitez.
<?php else: ?>
	Il reste encore des éléments à récolter dans le champ.		
<?php endif;?>
<br /><br />