<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'/>
 <div class='comp_contenu'>
<?php if ($this->nbEquipementLaban == 0) : ?>
 	Vous n'avez pas de pi&egrave;ce d'&eacute;quipement dans votre laban !<br /><br />
<?php else: ?>
	Pour <?php echo $this->nb_pa ?> PA, vous pouvez recycler une pi&egrave;ce d'&eacute;quipement :<br /><br />
	
	<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('#valeur_1').val() ==-1){$('#bouton_recycler').attr('disabled', true) } else {$('#bouton_recycler').attr('disabled',false) }">
		<option value='-1'>(Choisissez une pi&egrave;ce)</option>
		<?php foreach ($this->tabEquipementLaban as $e) : ?>
				<option value="<?php echo $e["id_equipement"]?>">N° <?php echo $e["id_equipement"]?> : <?php echo $e["nom"]?> <?php echo $e["suffixe"]?> de qualit&eacute; <?php echo $e["qualite"]?> et de niveau <?php echo $e["niveau"]?></option>
		<?php endforeach; ?>
	</select>
	<br /><br />
	<input type='button' class='button1' value='Recycler !' id='bouton_recycler' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_recyclage");' disabled>
<?php endif; ?>
</div>