 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	
 	Indiquez ici un fait &eacute;minemment notoire... il sera rajout&eacute; dans vos &eacute;v&eacute;nements sur votre profil.<br>
 	<br>
 	Vous pouvez utiliser les raccourcis suivants : <br>
 	Hobbit : [h1] affichera le hobbit n&deg; 1<br>
 	Monstre : [m42] affichera le monstre n&deg; 42<br>
 	Lieu : [l37] affichera le lieu n&deg; 37<br>
 	
 	<br><br>
 	Le verbe : <br>
 	
 	<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value!=-1 && $('valeur_2').value!=''){$('bouton_relater').disabled=false;$('bouton_relater_verif').disabled=false; } else {$('bouton_relater').disabled=true;$('bouton_relater_verif').disabled=true;}">
		<option value='-1'>(Choisis un verbe)</option>
	 	<? foreach($this->verbes as $k => $v): ?>
	 		<option value='<?=$k?>' <? if ($this->idVerbe == $k) :echo "selected"; endif;?>><?=$v?></option>
	 	<? endforeach;?>
 	</select>
	<br /><br>Le Texte : <br>
	<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="80" type="text"> Caract&egrave;res restants<br>
	<input type="text" name="valeur_2" id="valeur_2" class="inputbox" onkeydown="textCount($('valeur_2'),$('characterstyped'),80);" onkeyup="textCount($('valeur_2'),$('characterstyped'),80); if ($('valeur_1').value!=-1 && this.value != '') {$('bouton_relater').disabled=false;$('bouton_relater_verif').disabled=false; } else {$('bouton_relater').disabled=true;$('bouton_relater_verif').disabled=true; }"  maxlength="80" size="40" value="<?=htmlspecialchars($this->texte_original)?>"/>
	
	<? if ($this->texte != null) : ?>
		<br>
		V&eacute;rification : <br>
		<?=$this->texte?>
		<br>
	<? endif;?>
   
 </div>
<br />
Cliquez sur le bouton V&eacute;rifier pour v&eacute;rifier le rendu final. <br>
Une fois bien v&eacute;rifi&eacute; cliquez sur Relater.<br>
Attention, le texte ne pourra pas &ecirc;tre supprim&eacute; ou modifi&eacute; par la suite.
<br><br>
<input type='button' class='button1' id='bouton_relater_verif' value='Vérifier !' onClick='this.disabled=true;_get_("/competences/doaction?caction=ask_competence_relater&valeur_1="+$("valeur_1").value+"&valeur_2="+$("valeur_2").value);' <? if ($this->texte == null): echo "disabled"; endif;?>>
<input type='button' class='button1' id='bouton_relater' value='Relater !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_relater");' <? if ($this->texte == null): echo "disabled"; endif;?>>
