 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 	
 	Indiquez ici un fait &eacute;minemment notoire... il sera rajout&eacute; dans vos &eacute;v&eacute;nements sur votre profil, 
 	ainsi que dans le <a href="http://www.braldahim.com/bourg" target="site">bourg</a>.<br /><br />
 	
 	Si vous utilisez le verbe <b><u>recherche</u></b>, le texte apparaitra uniquement dans le <a href="http://www.braldahim.com/bourg" target="site">bourg</a>
 	 dans la section "Ils recherchent".<br />
 	<br />
 	Vous pouvez utiliser les raccourcis suivants : <br />
 	Braldûn : [b1] affichera le Braldûn n&deg; 1<br />
 	Monstre : [m42] affichera le monstre n&deg; 42<br />
 	Lieu : [l37] affichera le lieu n&deg; 37<br />
 	
 	<br /><br />
 	Le verbe : <br />
 	
 	<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('valeur_1').value!=-1 && $('valeur_2').value!=''){ $('bouton_relater_verif').disabled=false; if ($('premiereVerif').value == 'true') {$('bouton_relater').disabled=false;} } else {$('bouton_relater').disabled=true;$('bouton_relater_verif').disabled=true;}">
		<option value='-1'>(Choisissez un verbe)</option>
	 	<?php foreach($this->verbes as $k => $v): ?>
	 		<option value='<?php echo $k?>' <?php if ($this->idVerbe == $k) :echo "selected"; endif;?>><?php echo $v?></option>
	 	<?php endforeach;?>
 	</select>
	<br /><br />Le Texte : <br />
	<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="80" type="text"> Caract&egrave;res restants<br />
	<input type="text" name="valeur_2" id="valeur_2" class="inputbox" onkeydown="textCount($('valeur_2'),$('characterstyped'),80);" onkeyup="textCount($('valeur_2'),$('characterstyped'),80); if ($('valeur_1').value!=-1 && this.value != '') { $('bouton_relater_verif').disabled=false; if ($('premiereVerif').value == 'true') {$('bouton_relater').disabled=false;} } else {$('bouton_relater').disabled=true;$('bouton_relater_verif').disabled=true;}"  maxlength="80" size="40" value="<?php echo htmlspecialchars($this->texte_original)?>"/>
	
	<input type="hidden" id="premiereVerif" name="premiereVerif" value="<?php if ($this->texte != null) : echo "true"; else: echo "false"; endif; ?>">
	
	<?php if ($this->texte != null) : ?>
		<br /><br />
		V&eacute;rification : tout le texte en gras, votre Prénom et votre Nom <u>compris</u>, apparaitra tel quel dans le <a href="http://www.braldahim.com/bourg" target="site">bourg</a>: <br /><br />
		<b><?php echo $this->texte?></b>
		<br />
	<?php endif;?>
   
 </div>
<br />
Cliquez sur le bouton V&eacute;rifier pour v&eacute;rifier le rendu final. <br />
Une fois bien v&eacute;rifi&eacute; cliquez sur Relater.<br />
Attention, le texte ne pourra pas &ecirc;tre supprim&eacute; ou modifi&eacute; par la suite.
<br /><br />
<input type='button' class='button1' id='bouton_relater_verif' value='Vérifier !' onclick='this.disabled=true;_get_("/competences/doaction?caction=ask_competence_relater&valeur_1="+$("valeur_1").value+"&valeur_2="+$("valeur_2").value);' <?php if ($this->texte == null): echo "disabled"; endif;?>>
<input type='button' class='button1' id='bouton_relater' value='Relater !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_relater");' <?php if ($this->texte == null): echo "disabled"; endif;?>>
