 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	 <?php if ($this->reparermenuisierEchoppeOk === true) : ?>
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez r&eacute;parer une charrette<br />
	 appartenant &agrave; un Braldûn pr&eacute;sent sur votre case.<br />
	 <br />
     
     Charrette &agrave; r&eacute;parer :<br />
     <select name="valeur_1" id="valeur_1"  onchange="if (this.value == -1) {$('#bouton_reparermenuisier').attr('disabled', true)} else {$('#bouton_reparermenuisier').attr('disabled', false)}">
	 	<option value="-1">(Choisissez une charrette)</option>
	 	<?php foreach($this->charrettes as $c) : ?>
	 		<option value="<?php echo $c["id_charrette"]?>" <?php if ($c["possible"] == false) : echo "disabled"; endif; ?>><?php echo $c["nom_type_materiel"]?> 
	 		<?php if (array_key_exists("prenom_braldun", $c)) : ?>
	 			- <?php echo $c["prenom_braldun"]?> <?php echo $c["nom_braldun"]?> (<?php echo $c["id_braldun"]?>)
	 		<?php endif;?>
	 		
	 		 - Coût : <?php echo $c["cout_reparation_planche"]?> planche<?php if ($c["cout_reparation_planche"] > 1): echo "s"; endif; ?></option>
	 	<?php endforeach; ?>
	 </select>
	 
	 <br /><br />
	 	
	 <?php elseif ($this->reparermenuisierEchoppeOk == false) : ?>
		Vous ne pouvez r&eacute;parer que dans une de vos &eacute;choppes de Menuisier.
	<?php else: ?>
		Vous n'avez aucune planche pour reparer...
	<?php endif; ?>
</div>

<br />
<?php if ($this->assezDePa == true && $this->reparermenuisierEchoppeOk === true) : ?>
<input type='button' class='button1' id='bouton_reparermenuisier' value='R&eacute;parer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_reparermenuisier");' disabled>
<?php endif ?>
