 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
	
	Veuillez sélectionner le type de graines à semer : 
	<select name="valeur_1" id="valeur_1" onChange="_get_('/competences/doaction?caction=ask_competence_semer&valeur_1='+this.value);">
 		<option value="-1">(Choisissez un type)</option>
		<? foreach($this->conteneurGraines as $d) :?>
			<option value="<?=$d["id_conteneur"] ?>"><?=$d["texte"] ?></option>
		<? endforeach; ?>
	</select>
		
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->semerChampOk === true) : ?>
<input type='button' class='button1' id='bouton_abattrearbre' value='Semer !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_semer");'>
<? endif ?>
