 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 
	 Pour <?=$this->nb_pa ?> PA, vous pouvez semer des graines sur un de vos champs. <br /><br />
	
	<? if ($this->semerChampOk == false) : ?>
		Vous ne pouvez semer que sur l'un de vos champs en jachère.
	<? else : ?>
		Vous devez au minimum avoir 2 poignées d'une même type de graine pour pouvoir semer.<br /><br />
		Veuillez sélectionner le type de graines à semer : <br />
		<select name="valeur_1" id="valeur_1" onChange="if (this.value == -1) {$('bouton_semer').disabled = true;}else {$('bouton_semer').disabled = false;}">
	 		<option value="-1">(Choisissez un type)</option>
			<? foreach($this->conteneurs as $c) :?>
				<optgroup label="<?=$c["texte_conteneur"] ?>" style="font-weight:bold"></optgroup>
				<? if ($c["graines"] != null) : ?>
					<? foreach($c["graines"] as $g) :?>
						<option value="<?=$g["id_genere"] ?>" <? if ($g["possible"] == false) : echo 'disabled'; endif;?>><?=$g["nom_type_graine"] ?> : <?=$g["quantite"]?> poignée<? if ($g["quantite"] > 1): echo "s"; endif;?></option>
					<? endforeach?>
				<? else :?>
					<option value="-1" disabled>Aucune graine</option>
				<? endif;?>
			<? endforeach; ?>
		</select>
	<? endif;?>
		
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->semerChampOk === true) : ?>
<input type='button' class='button1' id='bouton_semer' value='Semer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_semer");' disabled>
<? endif ?>
