 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
 <div class='comp_contenu'>
 
	 Pour <?php echo $this->nb_pa ?> PA, vous pouvez semer des graines dans un champ. <br /><br />
	
	<?php if ($this->semerChampOk == false) : ?>
		Vous ne pouvez semer que sur un champ en jachère.<br />
		Ce champ doit vous appartenir, ou appartenir à un Braldûn de votre communauté (en ayant un grenier de niveau <?php echo Bral_Util_Communaute::NIVEAU_GRENIER_SEMER?> minimum).
	<?php else : ?>
		Vous devez au minimum avoir 2 poignées d'une même type de graine pour pouvoir semer.<br /><br />
		Veuillez sélectionner le type de graines à semer : <br />
		<select name="valeur_1" id="valeur_1" onchange="if (this.value == -1) {$('#bouton_semer').disabled = true;}else {$('#bouton_semer').disabled = false;}">
	 		<option value="-1">(Choisissez un type)</option>
			<?php foreach($this->conteneurs as $c) :?>
				<optgroup label="<?php echo $c["texte_conteneur"] ?>" style="font-weight:bold"></optgroup>
				<?php if ($c["graines"] != null) : ?>
					<?php foreach($c["graines"] as $g) :?>
						<option value="<?php echo $g["id_genere"] ?>" <?php if ($g["possible"] == false) : echo 'disabled'; endif;?>><?php echo $g["nom_type_graine"] ?> : <?php echo $g["quantite"]?> poignée<?php if ($g["quantite"] > 1): echo "s"; endif;?></option>
					<?php endforeach?>
				<?php else :?>
					<option value="-1" disabled>Aucune graine</option>
				<?php endif;?>
			<?php endforeach; ?>
		</select>
	<?php endif;?>
		
	 <br />
</div>

<br />
<?php if ($this->assezDePa == true && $this->semerChampOk === true) : ?>
<input type='button' class='button1' id='bouton_semer' value='Semer !' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_semer");' disabled>
<?php endif ?>
