<div class='comp_titre'>S'&eacute;quiper</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <form name='myForm'>
 <div class='comp_contenu'>

<?php if ($this->assezDePa == false) : ?>
 Vous n'avez pas assez de PA
<?php else : ?>
	 <? if ($this->sequiperOk === true) : ?>
	 	Pour <?=$this->nb_pa ?> PA, vous pouvez mettre ou enlever une pi&egrave;ce d'&eacute;quipement.<br><br>
	 	
	 	Si vous mettez une pi&egrave;ce d'&eacute;quipement &agrave; la place d'une pi&egrave;ce existante (ou de plusieurs pi&egrave; existantes), la pi&egrave;ce
	 	existante sera automatiquement transf&eacute;r&eacute;e dans votre laban.<br>
	 	
	 	<br>
	 	&Eacute;quipement pr&eacute;sent sur vous : <br>

	 	<table align="center" border='1'>
	 	<? 
	 		foreach($this->typesEmplacement as $k => $e) :
	 			if ($e["ordre_emplacement"] % 2 == 1) : echo "<tr>"; endif;
	 		?>
	 		<td>
	 			
	 			<?=htmlentities($e["nom_type_emplacement"]) ?><br>
	 			<? if (count($e["equipementPorte"]) > 0): ?>
	 				<select name="porte_<?=$k?>" id="porte_<?=$k?>" onChange="for (i=1; i<=<?=$this->nbTypesEmplacement ?>; i++) {if ($('bouton_enlever_'+i)) {$('bouton_enlever_'+i).style.display='none'; ; if (<?=$k?> != i){$('porte_'+i).selectedIndex = 0}} ; if ($('bouton_mettre_'+i)) {$('bouton_mettre_'+i).style.display='none' ; if (<?=$k?> != i){$('laban_'+i).selectedIndex = 0}}} ; if (this.value==-1) {$('bouton_enlever_<?=$k?>').style.display='none'} else {$('bouton_enlever_<?=$k?>').style.display='block'}" >
	 					<option value="-1">(Choisis un &eacute;quipement)</option>
	 					<? foreach($e["equipementPorte"] as $p) : ?>
	 					<option value="<?=$p["id_equipement"] ?>">
	 						<?=htmlentities($p["nom"]) ?>, n&deg;<?=$p["id_equipement"] ?>
	 					</option>
	 					<? endforeach; ?>
	 				</select>
	 				<input type='button' class='button1' id='bouton_enlever_<?=$k?>' value="Enlever (<?=$this->nb_pa ?> PA) !" onClick='this.disabled=true;_get_("/competences/DoAction?caction=do_competence_sequiper");' style="display:none">
	 			<? endif;  ?>
	 		</td>
	 	<? 	if ($e["ordre_emplacement"] % 2 == 0) : echo "</tr>"; endif;
	 	endforeach; ?>
	 	</table>
	 	
	 	<br><br>
	 	&Eacute;quipement pr&eacute;sent dans votre laban : <br>
	 	
	 	<table align="center" border='1'>
	 	<? 
	 		foreach($this->typesEmplacement as $k => $e) :
	 			if ($e["ordre_emplacement"] % 2 == 1) : echo "<tr>"; endif;
	 		?>
	 		<td>
	 			<?=htmlentities($e["nom_type_emplacement"]) ?><br>
	 			<? if (count($e["equipementLaban"]) > 0): ?>
	 				<select name="laban_<?=$k?>" id="laban_<?=$k?>"  onChange="for (i=1; i<=<?=$this->nbTypesEmplacement ?>; i++) {if ($('bouton_enlever_'+i)) {$('bouton_enlever_'+i).style.display='none'; ; if (<?=$k?> != i){$('porte_'+i).selectedIndex = 0}} ; if ($('bouton_mettre_'+i)) {$('bouton_mettre_'+i).style.display='none' ; if (<?=$k?> != i){$('laban_'+i).selectedIndex = 0}}} ; if (this.value==-1) {$('bouton_mettre_<?=$k?>').style.display='none'} else {$('bouton_mettre_<?=$k?>').style.display='block'}">
	 					<option value="-1">(Choisis un &eacute;quipement)</option>
	 					<? foreach($e["equipementLaban"] as $p) : ?>
	 					<option value="<?=$p["id_equipement"] ?>">
	 						<?=htmlentities($p["nom"]) ?>, n&deg;<?=$p["id_equipement"] ?>
	 					</option>
	 					<? endforeach; ?>
	 				</select>
	 				<input type='button' class='button1' id='bouton_mettre_<?=$k?>' value="Mettre (<?=$this->nb_pa ?> PA) !" onClick='this.disabled=true;_get_("/competences/DoAction?caction=do_competence_sequiper");' style="display:none">
	 			<? endif;  ?>
	 		</td>
	 	<? 	if ($e["ordre_emplacement"] % 2 == 0) : echo "</tr>"; endif;
	 	endforeach ?>
	 	</table>
	<? else : ?>
		Vous n'avez pas d'&eacute;quipement &agrave; mettre ou &agrave; enlever..
	<? endif; ?>
<? endif ?>
</div>

</form>
<br>
<? include("commun_fermer.phtml") ?>