<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>
	Vous avez r&eacute;ussi &agrave; tanner <?=$this->nbPeau ?> pi&egrave;ce<? if ($this->nbPeau > 1): echo "s"; endif; ?> de peau en 
	
	<? if ($this->quantiteFourrure > 0): ?>
		<? if ($this->quantiteFourrure > 1): $s='s'; else: $s=""; endif; ?>
		<?=$this->quantiteFourrure  ?> pi&egrave;ce<?=$s ?> de fourrure
	<? endif; ?>
	
	<? if ($this->quantiteCuir > 0): ?>
		<? if ($this->quantiteFourrure > 0): ?>
		et 
		<? endif; ?>
		<? if ($this->quantiteCuir > 1): $s='s'; else: $s=""; endif; ?>
		<?=$this->quantiteCuir  ?> pi&egrave;ce<?=$s ?> de cuir.
	<? endif; ?>
	<br />
<? else: ?>
	Vous avez manqu&eacute; votre tannage<br />
<? endif; ?>