<div class='comp_titre'>Tanner</div>

 <div class='comp_contenu'>
	 <div id='tanner_text' style="display:block"  onClick="javascript:switch2div('tanner_text','tanner_copie');">
		
		<? include("commun_text_resultat.phtml") ?>
		
		<? if ($this->okJet1 === true): ?>
			Vous avez r&eacute;ussi &agrave; tanner deux unit&eacute;s de peau en 
			
			<? if ($this->quantiteFourrure > 0): ?>
				<? if ($this->quantiteFourrure > 1): $s='s'; else: $s=""; endif; ?>
				<?=$this->quantiteFourrure  ?> pi&egrave;ce<?=$s ?> de fourrure.
			<? else : ?>
				<? if ($this->quantiteCuir > 1): $s='s'; else: $s=""; endif; ?>
				<?=$this->quantiteCuir  ?> pi&egrave;ce<?=$s ?> de cuir.
			<? endif; ?>
			<br />
		<? else: ?>
			Vous avez manqu&eacute; votre tannage<br />
		<? endif; ?>
		<br />
	 </div>
	 
	 <div id='tanner_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		
			echo "
";
			if ($this->okJet1 === true) {
				echo "Vous avez r&eacute;ussi &agrave; tanner deux unit&eacute;s de peau en ";
				
				if ($this->quantiteFourrure > 0) {
					if ($this->quantiteFourrure > 1): $s='s'; else: $s=""; endif; 
					echo $this->quantiteFourrure." pi&egrave;ce".$s." de fourrure.";
				} else {
					if ($this->quantiteCuir > 1): $s='s'; else: $s=""; endif;
					echo $this->quantiteCuir." pi&egrave;ce".$s." de cuir.";
				}
				echo "
";
			} else {
				echo "Vous avez manqu&eacute; votre tannage";
			}
	?>
	</textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('tanner_text','tanner_copie');">
<? include("commun_fermer.phtml") ?>