<? include("commun_text_resultat.phtml") ?>

<? if ($this->okJet1 === true): ?>

		Vous avez terrass&eacute; le terrain !<br />
		
		Le terrain terrass&eacute; a les caract&eacute;ristiques suivantes : <br />
		Position : <?=$this->route["x_route"] ?>, <?=$this->route["y_route"] ?><br />
		Date de destruction : le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->route["date_fin_route"]); ?>
		
		<br><br>
		
		<? if ($this->estEvenement === true) : ?>
			<? if ($this->evenementMinerai != null) : ?>
				Vous avez trouv&eacute; un minerai brut de type <?=$this->evenementMinerai["typeMinerai"]?> en raclant la terre !
				Il se trouve maitenant 
				<? if ($this->evenementMinerai["dansLaban"] == true ) : ?>
					dans votre laban
				<? else: ?>
					sur votre case (il n'y a plus de place dans votre laban).
				<? endif;?>
			<? else : ?>
				Vous avez trouv&eacute; une rune en raclant la terre ! Elle se trouve sur votre case.
			<? endif;?>
		<? endif;?>
		<br>
<? endif; ?>