 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>

Environnement : <?=$this->environnement?>.<br><br>

<?php if ($this->terrasserOk == false) : ?>
	Vous ne pouvez pas terrasser &agrave; cet endroit
<?php else : ?>
	Pour <?=$this->nb_pa ?> PA, vous terrasser &agrave; l'endroit où vous &ecirc;tes.
<? endif ?>
</div>

<br />
<?php if ($this->assezDePa === true && $this->terrasserOk === true) : ?>
<input type='button' class='button1' value='Terrasser !' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_terrasser");'>
<? endif ?>
