<? include("commun_text_resultat.phtml") ?>
	Vous avez tir&eacute; sur <?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
	Jet d'attaque : <?=$this->jetAttaquantNonReduit?><br />
	Vous étiez &agrave; une distance de <?=$this->distCible ?> case<? if ($this->distCible > 1) : ?>s<?endif;?><br />
	<? if ($this->palissade === true) : ?>
		et au moins une palissade se trouvait sur la trajectoire du tir !<br />
	<? endif; ?>
	<br>
	Vous avez donc subi un malus de <?=100-100*$this->coef?>%<br />
	Jet d'attaque corrig&eacute; : <?=$this->retourAttaque["jetAttaquant"]?><br />
	Jet de d&eacute;fense de la cible : <?=$this->retourAttaque["jetCible"]?><br />
		 
	 <? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
	 	<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
	 	Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;g&acirc;ts
	 	<? if ($this->retourAttaque["critique"]  == true): ?>
	 		en attaque critique
	 	<? endif; ?>
	 	<br /><br />
	 	<? if ($this->retourAttaque["arm_nat_cible"] > 0) :?>
		 	L'armure naturelle l'a prot&eacute;g&eacute;e.<br />
		<? endif; ?>
		<? if ($this->retourAttaque["arm_eqpt_cible"] > 0) :?>
		 	L'&eacute;quipement l'a prot&eacute;g&eacute;<br />
		<? endif; ?>
		 
		Au total, son armure l'a protégé en réduisant les dégâts de <?=$this->retourAttaque["arm_totale_cible"]?><br />
		<? if ($this->retourAttaque["penetrationArmure"] > 0) : ?>
			<b>Votre pénétration d'armure à réduit l'armure de <?=$this->retourAttaque["penetrationArmure"] ?></b><br>
		<? endif;?>
	 	La cible a donc perdu <?=$this->retourAttaque["jetDegatReel"] ?> point<? if ($this->retourAttaque["jetDegatReel"] > 1) : ?>s<?endif;?> de vie<br />
	 	<br />
	 	<? if ($this->retourAttaque["mort"] === true): ?>
	 		Vous avez 
	 		<? if ($this->retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "oui") :?>
	 			plaqu&eacute;
	 		<? elseif ($this->retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "non") :?>
	 			mis KO
	 		<? else: ?>	
	 			tu&eacute; 
	 		<? endif;?>
 			<?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
 			<? if ($this->retourAttaque["gains"] != null) :?>
	 			<? if (isset($this->retourAttaque["gains"]["gainRune"]) && $this->retourAttaque["gains"]["gainRune"] != false) :?>
	 				Une rune est tomb&eacute;e &agrave; terre <? if ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
	 				ainsi que <?=$this->retourAttaque["gains"]["gainCastars"]?> castar<? if ($this->retourAttaque["gains"]["gainCastars"] > 1): echo "s"; endif;?><? endif;?>.
	 				<br /><br />
	 			<? elseif ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
	 				<?=$this->retourAttaque["gains"]["gainCastars"]?> castar<? if ($this->retourAttaque["gains"]["gainCastars"] > 1) : 
 								echo "s sont tomb&eacute;s"; 
		 					else:	
		 						echo " est tomb&eacute;";
		 				endif;?>
		 				 &agrave; terre.<br /><br />
 				<? endif;?>
 			<? endif;?>
	 	<? endif; ?>
	 	Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
	 	<? if ($this->effetRune) :?>
			Une rune que vous portez a fait effet.<br />
		<? endif; ?>
		
		<? if ($this->retourAttaque["ballonLache"]) : ?>
			<img src='/public/styles/braldahim_defaut/images/vue/ballon.png'/><br>
			Le ballon de soule est tomb&eacute; &agrave; terre !<br>
		<? endif;?>
 	<? else: ?>
	 	Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
	 	<? if ($this->retourAttaque["fragilisee"] === true) : ?>
	 		<br /> La cible est fragilis&eacute;e pour les prochaines attaques
	 	<? else: ?>
	 		parfaitement.
	 	<? endif; ?>
 	<? endif; ?>
	<br />
<? include("commun_text_effets.phtml") ?>