 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
	<? if ($this->armeTirPortee == true) :?>
		<? if (!$this->munitionPortee == true) :?>
			Vous n'avez pas de munition correspondant &agrave; votre arme de tir !<br>
		<? endif; ?>
	<? else: ?>
		Vous ne portez pas d'arme de tir ! <br>
	<? endif; ?>
	
	<? if ($this->armeTirPortee == true &&  $this->munitionPortee == true):?>
		<? if ($this->estRegionPvp == false) :?>
			Vous ne pouvez pas attaquer de hobbit dans cette r&eacute;gion.<br><br>
		<? endif;?>
	 	<? if ($this->nHobbits == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; tirer dans votre distance de tir de <?=$this->tir_nb_cases ?> case<?if ($this->tir_nb_cases > 1): echo 's'; endif; ?><br />
	 	<? else: ?>
	 		Pour <?=$this->nb_pa?> PA, vous pouvez tirer &agrave; <?=$this->tir_nb_cases ?> case<?if ($this->tir_nb_cases > 1): echo 's'; endif; ?>.<br /><br />
	 		 <br /><br />
			<? if ($this->nMonstres > 0): ?>
				Tirer sur un monstre<br />
				<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_2').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisis un monstre)</option>
				<? $dist=-1; ?>
				<? foreach ($this->tabMonstres as $m) : ?>
					<? if ($dist != $m['dist_monstre']) : ?>
						<?
						$dist = $m['dist_monstre'];
						switch ($dist) {
							case 0:
								$case = "Sur votre case : ";
								break;
							case 1:
								$case = "&agrave; 1 case : ";
								break;
							default:
								$case = "&agrave; $dist cases : ";
						}
						?>
						<optgroup label="<?=$case ?>" style="font-weight:bold"></optgroup>
					<? endif; ?>
					<option value="<?=$m["id_monstre"]?>"><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>) x:<?=$m["x_monstre"]?> , y:<?=$m["y_monstre"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<? endif; ?>
			
	 		<? if ($this->nHobbits > 0): ?>
	 		 	Tirer sur un hobbit<br />
	 			<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_1').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisis un hobbit)</option>
				<? $dist=-1; ?>
	 			<? foreach ($this->tabHobbits as $h) : ?>
		 			<? if ($dist != $h['dist_hobbit']) : ?>
						<?
						$dist = $h['dist_hobbit'];
						switch ($dist) {
							case 0:
								$case = "Sur votre case : ";
								break;
							case 1:
								$case = "&agrave; 1 case : ";
								break;
							default:
								$case = "&agrave; $dist cases : ";
						}
						?>
						<optgroup label="<?=$case ?>" style="font-weight:bold"></optgroup>
					<? endif; ?>
					<option value="<?=$h["id_hobbit"]?>"><?=$h["prenom_hobbit"]?> <?=$h["nom_hobbit"]?> (<?=$h["id_hobbit"]?>) x:<?=$h["x_hobbit"]?> , y:<?=$h["y_hobbit"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<? endif;?>
		<? endif; ?>
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : ?>
	<input type='button' class='button1' value='Tirer !' id='bouton_tirer' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_tirer");' disabled>
<? endif ?>