 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
 	<? include('commun_attaque_formulaire.phtml');?>
 
	<? if ($this->armeTirPortee == true) :?>
		<? if (!$this->munitionPortee == true) :?>
			Vous n'avez pas de munition correspondant &agrave; votre arme de tir !<br />
		<? endif; ?>
	<? else: ?>
		Vous ne portez pas d'arme de tir ! <br />
	<? endif; ?>
	
	<? if ($this->course==false) :?>
		Vous &ecirc;tes encercl&eacute;, vous ne pouvez pas courir !<br />
	<? endif; ?>
	
	<? if ($this->armeTirPortee == true &&  $this->munitionPortee == true && $this->course==true && $this->user->est_intangible_braldun == 'non'):?>
	 	<? if ($this->nBralduns == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; attaquer ici ! <br />
	 	<? else: ?>
	 		 <br />
			<? if ($this->nMonstres > 0): ?>
				Tirer en courant sur un monstre<br />
				<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_2').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisissez un monstre)</option>
				<? foreach ($this->tabMonstres as $m) : ?>
					<option value="<?=$m["id_monstre"]?>"><?=$m["nom_monstre"]?> <?=$m["taille_monstre"]?>  (<?=$m["id_monstre"]?>)</option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<? endif; ?>
			
	 		<? if ($this->nBralduns > 0): ?>
	 		 	Tirer sur un Braldûn<br />
	 			<select name='valeur_2' id="valeur_2" onchange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_1').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisissez un Braldûn)</option>
	 			<? foreach ($this->tabBralduns as $h) : ?>
					<option value="<?=$h["id_braldun"]?>"><?=$h["prenom_braldun"]?> <?=$h["nom_braldun"]?> (<?=$h["id_braldun"]?>)</option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<? endif;?>
		<? endif; ?>
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : ?>
	<input type='button' class='button1' value='Tirer !' id='bouton_tirer' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_tirerencourant");' disabled>
<? endif ?>