<?php include("commun_text_resultat.phtml") ?>

<?php if ($this->cibleVisible == false) : ?>
	La cible a disparu, elle ne fait pas partie de votre vue.<br />
	
<?php else: ?>

	Vous avez tir&eacute; sur <?php echo $this->retourAttaque["cible"]["nom_cible"]?> (<?php echo $this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
	Jet d'attaque : <?php echo $this->jetAttaquantNonReduit?><br />
	Vous étiez &agrave; une distance de <?php echo $this->distCible ?> case<?php if ($this->distCible > 1) : ?>s<?php endif;?><br />
	<?php if ($this->palissade === true) : ?>
		et au moins une palissade se trouvait sur la trajectoire du tir !<br />
	<?php endif; ?>
	<br />
	Vous avez donc subi un malus de <?php echo 100-100*$this->coef?>%<br />
	Jet d'attaque corrig&eacute; : <span class="resultat" title="<?php echo $this->retourAttaque["jetAttaquant"]["details"]?>"><?php echo $this->retourAttaque["jetAttaquant"]["jet"]?> </span> 
	 <span class="resultat_cache">(<?php echo $this->retourAttaque["jetAttaquant"]["details"]?>)</span><br />
	 Jet de d&eacute;fense de la cible : <?php echo $this->retourAttaque["jetCible"]?><br />
		 
	 <?php if ($this->retourAttaque["attaqueReussie"] === true) : ?>
	 	<?php if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
	 	Vous avez inflig&eacute; <span class="resultat" title="<?php echo $this->retourAttaque["jetDegat"]["details"]?>"><?php echo $this->retourAttaque["jetDegat"]["jet"]?></span> point<?php echo $s?> de d&eacute;g&acirc;ts
	 	<?php if ($this->retourAttaque["critique"]  == true): ?>
	 		en attaque critique
	 	<?php endif; ?>
	 	<span class="resultat_cache">(<?php echo $this->retourAttaque["jetDegat"]["details"]?>)</span>
	 	<br /><br />
	 	<?php if ($this->retourAttaque["arm_nat_cible"] > 0) :?>
		 	L'armure naturelle l'a prot&eacute;g&eacute;e.<br />
		<?php endif; ?>
		<?php if ($this->retourAttaque["arm_eqpt_cible"] > 0) :?>
		 	L'&eacute;quipement l'a prot&eacute;g&eacute;<br />
		<?php endif; ?>
		 
		Au total, son armure l'a protégé en réduisant les dégâts de <?php echo $this->retourAttaque["arm_totale_cible"]?><br />
		<?php if ($this->retourAttaque["penetrationArmure"] > 0) : ?>
			<b>Votre pénétration d'armure à réduit l'armure de <?php echo $this->retourAttaque["penetrationArmure"] ?></b><br />
		<?php endif;?>
	 	La cible a donc perdu <?php echo $this->retourAttaque["jetDegatReel"] ?> point<?php if ($this->retourAttaque["jetDegatReel"] > 1) : ?>s<?php endif;?> de vie<br />
	 	<br />
	 	<?php if ($this->retourAttaque["mort"] === true): ?>
	 		Vous avez 
	 		<?php if ($this->retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "oui") :?>
	 			plaqu&eacute;
	 		<?php elseif ($this->retourAttaque["cible"]["type_cible"] == "braldun" && $this->user->est_soule_braldun == "non") :?>
	 			mis KO
	 		<?php else: ?>	
	 			tu&eacute; 
	 		<?php endif;?>
 			<?php echo $this->retourAttaque["cible"]["nom_cible"]?> (<?php echo $this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
 			<?php if ($this->retourAttaque["gains"] != null) :?>
	 			<?php if (isset($this->retourAttaque["gains"]["butin"])) :?>
	 				Le butin suivant est tombé à terre : 
	 				<?php echo $this->retourAttaque["gains"]["butin"];?><br /><br />
	 			<?php elseif (isset($this->retourAttaque["gains"]["gainRune"]) && $this->retourAttaque["gains"]["gainRune"] != false) :?>
	 				Une rune est tomb&eacute;e &agrave; terre <?php if ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
	 				ainsi que <?php echo $this->retourAttaque["gains"]["gainCastars"]?> castar<?php if ($this->retourAttaque["gains"]["gainCastars"] > 1): echo "s"; endif;?><?php endif;?>.
	 				<br /><br />
	 			<?php elseif ($this->retourAttaque["gains"]["gainCastars"] > 0) : ?>
	 				<?php echo $this->retourAttaque["gains"]["gainCastars"]?> castar<?php if ($this->retourAttaque["gains"]["gainCastars"] > 1) : 
 								echo "s sont tomb&eacute;s"; 
		 					else:	
		 						echo " est tomb&eacute;";
		 				endif;?>
		 				 &agrave; terre.<br /><br />
 				<?php endif;?>
 			<?php endif;?>
	 	<?php endif; ?>
	 	Vous avez gagn&eacute; <?php echo $this->nb_px?> PX<br /><br />
	 	<?php if ($this->effetRune) :?>
			Une rune que vous portez a fait effet.<br />
		<?php endif; ?>
		
		<?php if ($this->retourAttaque["ballonLache"]) : ?>
			<img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/vue/ballon.png'/><br />
			Le ballon de soule est tomb&eacute; &agrave; terre !<br />
		<?php endif;?>
		
		<?php include('commun_attaque_resultat.phtml');?>
		
		Il vous reste <?php echo $this->nbMunitionsPortees?> munition<?php if ($this->nbMunitionsPortees > 1): echo "s"; endif;?> dans votre laban.
		<br />
		
 	<?php else: ?>
	 	Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
	 	<?php if ($this->retourAttaque["fragilisee"] === true) : ?>
	 		<br /> La cible est fragilis&eacute;e pour les prochaines attaques
	 	<?php else: ?>
	 		parfaitement.
	 	<?php endif; ?>
 	<?php endif; ?>
<?php endif;?>
<?php include("commun_text_effets.phtml") ?>