 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <div class='comp_contenu'>
 
 	<?php include('commun_attaque_formulaire.phtml');?>
 
	<?php if ($this->armeTirPortee == true) :?>
		<?php if (!$this->munitionPortee == true) :?>
			Vous n'avez pas de munition correspondant &agrave; votre arme de tir !<br />
		<?php endif; ?>
	<?php else: ?>
		Vous ne portez pas d'arme de tir ! <br />
	<?php endif; ?>
	
	<?php if ($this->course==false) :?>
		Vous &ecirc;tes encercl&eacute;, vous ne pouvez pas courir !<br />
	<?php endif; ?>
	
	<?php if ($this->armeTirPortee == true &&  $this->munitionPortee == true && $this->course==true && $this->user->est_intangible_braldun == 'non'):?>
	 	<?php if ($this->nBralduns == 0 && $this->nMonstres == 0): ?>
	 		Il n'y a rien &agrave; attaquer ici ! <br />
	 	<?php else: ?>
	 		 <br />
			<?php if ($this->nMonstres > 0): ?>
				Tirer en courant sur un monstre<br />
				<select name='valeur_1' id="valeur_1" onchange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_2').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisissez un monstre)</option>
				<?php foreach ($this->tabMonstres as $m) : ?>
					<option value="<?php echo $m["id_monstre"]?>"><?php echo $m["nom_monstre"]?> <?php echo $m["taille_monstre"]?>  (<?php echo $m["id_monstre"]?>)</option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
				<input type="hidden" name='valeur_1' value="-1" id="valeur_1" >
			<?php endif; ?>
			
	 		<?php if ($this->nBralduns > 0): ?>
	 		 	Tirer sur un Braldûn<br />
	 			<select name='valeur_2' id="valeur_2" onchange="javascript:if ($('valeur_1').value==-1 && $('valeur_2').value==-1){$('bouton_tirer').disabled=true } else {$('valeur_1').value=-1; $('bouton_tirer').disabled=false }">
				<option value='-1'>(Choisissez un Braldûn)</option>
	 			<?php foreach ($this->tabBralduns as $h) : ?>
					<option value="<?php echo $h["id_braldun"]?>"><?php echo $h["prenom_braldun"]?> <?php echo $h["nom_braldun"]?> (<?php echo $h["id_braldun"]?>)</option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2">
			<?php endif;?>
		<?php endif; ?>
	<?php endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : ?>
	<input type='button' class='button1' value='Tirer !' id='bouton_tirer' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_tirerencourant");' disabled>
<?php endif ?>