<? include("commun_text_resultat.phtml") ?>
	<? if ($this->okJet1 === true): ?>
		Vous avez tir&eacute; sur <?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
		
		Jet d'attaque : <?=$this->retourAttaque["jetAttaquant"]?><br />
		Jet de d&eacute;fense de la cible : <?=$this->retourAttaque["jetCible"]?><br />
		 <? if ($this->retourAttaque["attaqueReussie"] === true) : ?>
		 	<? if ($this->retourAttaque["jetDegat"] > 1) : $s='s'; else : $s=''; endif;?>
		 	Vous avez inflig&eacute; <?=$this->retourAttaque["jetDegat"]?> point<?=$s?> de d&eacute;g&acirc;ts
		 	<? if ($this->retourAttaque["critique"]  == true): ?>
		 		en attaque critique
		 	<? endif; ?>
		 	<br /><br />
		 	<? if ($this->retourAttaque["arm_nat_cible"] > 0) :?>
			 	L'armure naturelle l'a prot&eacute;g&eacute;e.<br />
			<? endif; ?>
			<? if ($this->retourAttaque["arm_eqpt_cible"] > 0) :?>
			 	L'&eacute;quipement l'a prot&eacute;g&eacute;<br />
			<? endif; ?>
			 
			Au total, son armure l'a protégé en réduisant les dégâts de <?=$this->retourAttaque["arm_totale_cible"]?><br />
		 	La cible a donc perdu <?=$this->retourAttaque["jetDegatReel"] ?> point<? if ($this->retourAttaque["jetDegatReel"] > 1) : ?>s<?endif;?> de vie<br />
		 	<br />
		 	<? if ($this->retourAttaque["mort"] === true): ?>
		 		Vous avez 
		 		<? if ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "oui") :?>
		 			plaqu&eacute;
		 		<? elseif ($this->retourAttaque["cible"]["type_cible"] == "hobbit" && $this->user->est_soule_hobbit == "non") :?>
		 			mis KO
		 		<? else: ?>	
		 			tu&eacute; 
		 		<? endif;?>
		 		<?=$this->retourAttaque["cible"]["nom_cible"]?> (<?=$this->retourAttaque["cible"]["id_cible"]?>)<br /><br />
		 	<? endif; ?>
		 	Vous avez gagn&eacute; <?=$this->nb_px?> PX<br /><br />
		 	<? if ($this->effetRune) :?>
				Une rune que vous portez a fait effet.<br />
			<? endif; ?>
			
			<? if ($this->retourAttaque["ballonLache"]) : ?>
				<img src='/public/styles/braldahim_defaut/images/vue/ballon.png'/><br>
				Le ballon de soule est tomb&eacute; &agrave; terre !<br>
			<? endif;?>
			
	 	<? else: ?>
		 	Votre attaque a &eacute;t&eacute; esquiv&eacute;e 
		 	<? if ($this->retourAttaque["fragilisee"] === true) : ?>
		 		<br /> La cible est fragilis&eacute;e pour les prochaines attaques
		 	<? else: ?>
		 		parfaitement.
		 	<? endif; ?>
	 	<? endif; ?>
	 	<br />
	 	Vous vous &ecirc;tes d&eacute;plac&eacute; en x=<?=$this->user->x_hobbit ?>, y=<?=$this->user->y_hobbit ?>
		<br />
	<? else: ?>
		Vous avez manqu&eacute; votre tir !<br />
	<? endif; ?>
<? include("commun_text_effets.phtml") ?>