<?php if ($this->niveauMarcheCommunaute >= 0 && ($this->niveauMarcheCommunaute == Bral_Util_Communaute::NIVEAU_EN_CONSTRUCTION || $this->niveauMarcheCommunaute >= 0)) : ?>
	<?php echo Bral_Helper_Communaute::afficheNiveauMarche($this->niveauMarcheCommunaute);?><br />
	Seuls les tenanciers, adjoints et gestionnaires peuvent retirer des éléments du coffre de Communauté.<br />
<?php elseif ($this->user->id_fk_communaute_braldun != null) : ?>
 	Votre communauté ne possède pas de <?php echo Bral_Helper_Communaute::afficheNiveauMarche(null, "marché couvert")?>.
<?php endif;?>
<br />

<?php if (count($this->typeDepart) > 0) : ?>
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo $this->nb_valeurs ?>'/>
		<?php
		$poches = null;
		$jsBtn = "controleQte();";
		$panneau = true;
		?>
		Transbahuter à partir de :<br />
		<select name="valeur_1" id="valeur_1"  onchange="_get_('/competences/doaction?caction=ask_competence_transbahuter&valeur_1='+this.value);">
			<option value="-1">(Choisissez un endroit de d&eacute;part)</option>
			<?php foreach($this->typeDepart as $k => $t) : ?>
			 	<option value="<?php echo $k ?>" <?php if ($t["selected"] == $k || count($this->typeDepart)==1): echo " selected='selected' "; $panneau=$t["panneau"]; endif;?>><?php echo $t["nom_type_depart"]?></option>
			<?php endforeach; ?>
		 </select>
		 <input type="hidden" name="valeur_panneau" id="valeur_panneau" value="<?php echo $panneau ?>"/>
		 <br/><br/>

		<?php if ($this->choixDepart == true) : ?>
			<?php if (count($this->typeArrivee) > 0) : ?>
				<?php include("transbahuter/autres.phtml")?>
				<?php include("transbahuter/runes.phtml")?>
				<?php include("transbahuter/equipements.phtml")?>
				<?php include("transbahuter/potions.phtml")?>
				<?php include("transbahuter/aliments.phtml")?>
				<?php include("transbahuter/munitions.phtml")?>
				<?php include("transbahuter/partiesplantes.phtml")?>
				<?php include("transbahuter/minerais.phtml")?>
				<?php include("transbahuter/graines.phtml")?>
				<?php include("transbahuter/ingredients.phtml")?>
				<?php include("transbahuter/tabacs.phtml")?>
				<?php include("transbahuter/materiels.phtml")?>

				<?php
				$js = "selectAll(11, ".$this->nb_valeurs.");";

				$jsRechercheBraldun = "afficheTransbahuterRechercheBraldun();";
				$jsVente = "afficheTransbahuterVente();";

				$jsFermer = "";
				$jsOuvrir = "";
				if ($poches != null) :
					foreach ($poches as $p) :
						$jsFermer .= "maccordion_fermer($('#$p'));";
						$jsOuvrir .= "maccordion_ouvrir($('#$p'));";
					endforeach;
				endif;
				?>
				<br/>
				<input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onclick="<?php echo $js?>"/>
				<input type='reset' class='button1' id='bouton_selectionnertout' value='Réinitialiser !' onclick="$('#bouton_deposer').attr('disabled', true);"/>
				<?php if ($poches != null): ?>
					<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onclick="<?php echo $jsFermer ?>"/>
					<input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onclick="<?php echo $jsOuvrir ?>"/>
				<?php endif;?>
				<br/><br/>
				Transbahuter vers :<br />
				<?php
					$options = "";
					$poids = "";
					$charretteOuLaban = "";
					$venteSelectionne = false;
					$venteEtalSelectionne = false;
					$coffreBraldunSelectionne = false;
					$reservationCommunauteSelectionnee = false;
					foreach($this->typeArrivee as $idTypeArrivee => $t) {
						$options .="<option value='".$idTypeArrivee."'";
				 		if ($t["selected"] == $idTypeArrivee || count($this->typeArrivee) == 1) {
				 			$options .=" selected='selected' ";
				 			if ($this->ID_ENDROIT_ECHOPPE_ETAL == $t["id_type_arrivee"] || $this->ID_ENDROIT_HOTEL == $t["id_type_arrivee"]) {
				 				$venteSelectionne = true;
				 			}
					 		if ($this->ID_ENDROIT_ECHOPPE_ETAL == $t["id_type_arrivee"]) {
					 			$venteEtalSelectionne = true;
				 			}
				 			if ($this->ID_ENDROIT_COFFRE_BRALDUN == $t["id_type_arrivee"]) {
					 			$coffreBraldunSelectionne = true;
				 			}
					 		if ($this->ID_ENDROIT_RESERVATION_COMMUNAUTE == $t["id_type_arrivee"]) {
					 			$reservationCommunauteSelectionnee = true;
				 			}
				 		}
				 		$options .= ">".$t["nom_type_arrivee"]."</option>";
				 		$poids .= "<input type='hidden' name='poids_".$idTypeArrivee."' id='poids_".$idTypeArrivee."' value='".$t["poids_restant"]."' />";
				 		if ($this->ID_ENDROIT_CHARRETTE == $t["id_type_arrivee"] || $this->ID_ENDROIT_LABAN_BRALDUN == $t["id_type_arrivee"]) {
				 			$charretteOuLaban .= "<input type='hidden' name='id_destination_".$idTypeArrivee."' id='id_destination_".$idTypeArrivee."' value='".$t["id_destination"]."' />";
				 		}
				   	}
				?>
				<select name="valeur_2" id="valeur_2" onchange="<?php echo $jsVente.$jsBtn.$jsRechercheBraldun?>">
					<option value="-1">(Choisissez un endroit d'arriv&eacute;e)</option>
					<?php echo $options ?>
				</select>
				<?php echo $poids ?><br/>
				<?php echo $charretteOuLaban ?>
				<br/>
				<div id="div_poids"></div>
				<?php if ($venteEtalSelectionne || $coffreBraldunSelectionne || $reservationCommunauteSelectionnee) : $visibility = 'visible'; $display = 'block'; else: $visibility = 'hidden'; $display = 'none'; endif ?>
				<input type="hidden" name="valeur_3" id="valeur_3" value="-1"/>
				<div id="div_braldun" style="display :<?php echo $display?>">
					<span id="texte_transbahuter_braldun">
					<?php if ($venteEtalSelectionne) :?>
						<?php echo "Vous pouvez réserver cette vente à un unique Braldûn:"; ?>
					<?php elseif ($reservationCommunauteSelectionnee): ?>
						<?php echo "Vous pouvez réserver ce lot à un unique Braldûn:"; ?>
					<?php elseif ($coffreBraldunSelectionne): ?>
						<?php echo "Entrez le Braldûn destinataire:"; ?>
					<?php endif;?>
					</span><br />
					<input type="text" name="recherche_valeur_3_dest" size='30' id="recherche_valeur_3_dest" value="Entrez un nom" onFocus="if(this.value=='Entrez un nom'){this.value='';};activerRechercheTransbahuterBraldun('valeur_3_dest');" />
					<input type="hidden" name="recherche_valeur_3_dest_actif" id="recherche_valeur_3_dest_actif" value="0" />
					<div class="recherche" id="recherche_valeur_3_dest_update" ></div>
   					<span id="indicateur_recherche_valeur_3_dest" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" alt="Recherche..." /></span>
   				</div>

   				<?php if ($venteSelectionne || $reservationCommunauteSelectionnee) : $display = 'block'; else: $display = 'none'; endif ?>
				<div id="div_vente_transbahuter" style="display :<?php echo $display?>">
					<?php if ($venteSelectionne) : $display = 'block'; else:  $display = 'none'; endif ?>
					<br /><span id="span_vente_transbahuter" style="display :<?php echo $display?>"><b>Les castars sélectionnés ne seront pas pris en compte dans ce transbahutage</b>.</span><br /><br />
					<?php include("transbahuter/vente_formulaire_castars.phtml")?>
   				</div>

				<br/>
				<input type='button' class='button1' id='bouton_deposer' value='Transbahuter !' onclick="charretteOuLaban();if (controlePrixVenteBoutonDeposer()) {this.disabled=true;$('#valeur_10').val(encodePlus($('#valeur_commentaire').val()));_get_('/competences/doaction?caction=do_competence_transbahuter&idCharretteEtal=<?php echo $this->idCharretteEtal?>')};" disabled>
		<?php else : ?>
			Pas de destination possible autre que votre laban et il est plein ! <br/><br/>
		<?php endif; ?>
	<?php endif; ?>
<?php else : ?>
	Vous ne pouvez rien transbahuter !<br/><br/>
<?php endif; ?>