<?php if (count($this->typeDepart) > 0) : ?>
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo $this->nb_valeurs ?>'/>
	<div class='comp_contenu'>
		<?php
		$poches = null;
		$jsBtn = "controleQte();";
		$panneau = true;
		?>
		Transbahuter à partir de :<br />
		<select name="valeur_1" id="valeur_1"  onchange="_get_('/competences/doaction?caction=ask_competence_transbahuter&valeur_1='+this.value);">
			<option value="-1">(Choisissez un endroit de d&eacute;part)</option>
			<?php foreach($this->typeDepart as $t) : ?>
			 	<option value="<?php echo $t["id_type_depart"]?>" <?php if ($t["selected"] == $t["id_type_depart"] || count($this->typeDepart)==1): echo " selected='selected' "; $panneau=$t["panneau"]; endif;?>><?php echo $t["nom_type_depart"]?></option>
			<?php endforeach; ?>
		 </select>
		 <input type="hidden" name="valeur_panneau" id="valeur_panneau" value="<?php echo $panneau ?>"/>
		 <br/><br/>
		
		<?php if ($this->choixDepart == true) : ?>
			<?php if (count($this->typeArrivee) > 0) : ?>
				<?php include("transbahuter/autres.phtml")?>
				<?php include("transbahuter/runes.phtml")?>
				<?php include("transbahuter/equipements.phtml")?>
				<?php include("transbahuter/potions.phtml")?>
				<?php include("transbahuter/aliments.phtml")?>
				<?php include("transbahuter/munitions.phtml")?>
				<?php include("transbahuter/partiesplantes.phtml")?>
				<?php include("transbahuter/minerais.phtml")?>
				<?php include("transbahuter/graines.phtml")?>
				<?php include("transbahuter/ingredients.phtml")?>
				<?php include("transbahuter/tabacs.phtml")?>
				<?php include("transbahuter/materiels.phtml")?>
			
				<?php 
				$js = "selectAll();";
				
				$jsCoffre = "afficheAutreCoffre();";
				$jsVente = "afficheTransbahuterVente();";
				
				$jsFermer = "";
				$jsOuvrir = "";
				foreach ($poches as $p) :
					$jsFermer .= "maccordion_fermer($('$p'));";
					$jsOuvrir .= "maccordion_ouvrir($('$p'));";
				endforeach; 
				?>
				<br/>
				<input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onclick="<?php echo $js?>"/> 
				<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onclick="<?php echo $jsFermer ?>"/>
				<input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onclick="<?php echo $jsOuvrir ?>"/>
				<br/><br/>
				Transbahuter vers :<br />
					<?php 
						$option = "";
						$poids = "";
						$charrette = "";
						foreach($this->typeArrivee as $t){ 
							$option .="<option value='".$t["id_type_arrivee"]."'";
					 		if ($t["selected"] == $t["id_type_arrivee"] || count($this->typeArrivee) == 1) {
					 			$option .=" selected='selected' ";
					 		}
					 		$option .= ">".$t["nom_type_arrivee"]."</option>";
					 		$poids .= "<input type='hidden' name='poids_".$t["id_type_arrivee"]."' id='poids_".$t["id_type_arrivee"]."' value='".$t["poids_restant"]."' />";
					 		if ($t["nom_systeme"] == "Charrette") {
					 			$charrette .= "<input type='hidden' name='id_charrette_".$t["id_type_arrivee"]."' id='id_charrette_".$t["id_type_arrivee"]."' value='".$t["id_charrette"]."' />";
					 		}
					   	}
					?>
				<select name="valeur_2" id="valeur_2" onchange="<?php echo $jsBtn.$jsCoffre.$jsVente?>">
					<option value="-1">(Choisissez un endroit d'arriv&eacute;e)</option>
					<?php echo $option ?>
				</select>
				<?php echo $poids ?><br/>
				<?php echo $charrette ?>
				<br/><br/>
				<input type="hidden" name="valeur_3" id="valeur_3" value="-1"/>
				<div id="div_braldun" style="visibility: hidden;display :none">
					<input type="text" name="recherche_valeur_3_dest" size='30' id="recherche_valeur_3_dest" value="Entrez un nom" onFocus="if(this.value=='Entrez un nom'){this.value='';};activerRechercheCoffreBraldun('valeur_3_dest');" />
					<input type="hidden" name="recherche_valeur_3_dest_actif" id="recherche_valeur_3_dest_actif" value="0" />
					<div class="recherche" id="recherche_valeur_3_dest_update" ></div> <img src="<?php echo $this->config->static->url?>/images/loupe.gif" />
   					<span id="indicateur_recherche_valeur_3_dest" style="display: none"><img src="<?php echo $this->config->static->url?>/images/wait.gif" alt="Recherche..." /></span>
   				</div>
   				
				<div id="div_vente_transbahuter" style="visibility: hidden;display :none">
					<?php include("transbahuter/vente_formulaire.phtml")?>
   				</div>
   				
				<br/>
				<input type='button' class='button1' id='bouton_deposer' value='Transbahuter !' onclick="charrette();this.disabled=true;$('valeur_10').value=encodePlus($('valeur_commentaire').value);_get_('/competences/doaction?caction=do_competence_transbahuter');" disabled>
		<?php else : ?>
			Pas de destination possible autre que votre laban et il est plein ! <br/><br/>
		<?php endif; ?>
	<?php endif; ?>
	</div> 	
<?php else : ?>
	Vous ne pouvez rien transbahuter !<br/><br/>
<?php endif; ?>