<?php if (count($this->typeDepart) > 0) : ?>
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='<?php echo $this->nb_valeurs ?>'/>
	<div class='comp_contenu'>
		<?php
		$poches = null;
		$jsBtn = "controleQte();";
		$panneau = true;
		?>
		Transbahuter à partir de :<br />
		<select name="valeur_1" id="valeur_1"  onchange="_get_('/competences/doaction?caction=ask_competence_transbahuter&valeur_1='+this.value);">
			<option value="-1">(Choisissez un endroit de d&eacute;part)</option>
			<?php foreach($this->typeDepart as $k => $t) : ?>
			 	<option value="<?php echo $k ?>" <?php if ($t["selected"] == $k || count($this->typeDepart)==1): echo " selected='selected' "; $panneau=$t["panneau"]; endif;?>><?php echo $t["nom_type_depart"]?></option>
			<?php endforeach; ?>
		 </select>
		 <input type="hidden" name="valeur_panneau" id="valeur_panneau" value="<?php echo $panneau ?>"/>
		 <br/><br/>
		
		<?php if ($this->choixDepart == true) : ?>
			<?php if (count($this->typeArrivee) > 0) : ?>
				<?php include("transbahuter/autres.phtml")?>
				<?php include("transbahuter/runes.phtml")?>
				<?php include("transbahuter/equipements.phtml")?>
				<?php include("transbahuter/potions.phtml")?>
				<?php include("transbahuter/aliments.phtml")?>
				<?php include("transbahuter/munitions.phtml")?>
				<?php include("transbahuter/partiesplantes.phtml")?>
				<?php include("transbahuter/minerais.phtml")?>
				<?php include("transbahuter/graines.phtml")?>
				<?php include("transbahuter/ingredients.phtml")?>
				<?php include("transbahuter/tabacs.phtml")?>
				<?php include("transbahuter/materiels.phtml")?>
			
				<?php 
				$js = "selectAll(11,$('nb_valeurs').value);";
				
				$jsRechercheBraldun = "afficheTransbahuterRechercheBraldun();";
				$jsVente = "afficheTransbahuterVente();";
				
				$jsFermer = "";
				$jsOuvrir = "";
				if ($poches != null) :
					foreach ($poches as $p) :
						$jsFermer .= "maccordion_fermer($('$p'));";
						$jsOuvrir .= "maccordion_ouvrir($('$p'));";
					endforeach; 
				endif;
				?>
				<br/>
				<input type='button' class='button1' id='bouton_selectionnertout' value='S&eacute;lectionner Tout !' onclick="<?php echo $js?>"/>
				<input type='reset' class='button1' id='bouton_selectionnertout' value='Réinitialiser !' onclick="$('bouton_deposer').disabled=true;"/>
				<?php if ($poches != null): ?> 
					<input type='button' class='button1' id="fermer_poche" name="fermer_poche" value='Fermer Tout' onclick="<?php echo $jsFermer ?>"/>
					<input type='button' class='button1' id="ouvrir_poche" name="ouvrir_poche"  value='Ouvrir Tout' onclick="<?php echo $jsOuvrir ?>"/>
				<?php endif;?>
				<br/><br/>
				Transbahuter vers :<br />
				<?php 
					$options = "";
					$poids = "";
					$charrette = "";
					$venteSelectionne = false;
					$venteEtalSelectionne = false;
					$coffreBraldunSelectionne = false;
					$reservationCommunauteSelectionnee = false;
					foreach($this->typeArrivee as $idTypeArrivee => $t) { 
						$options .="<option value='".$idTypeArrivee."'";
				 		if ($t["selected"] == $idTypeArrivee || count($this->typeArrivee) == 1) {
				 			$options .=" selected='selected' ";
				 			if ($this->ID_ENDROIT_ECHOPPE_ETAL == $t["id_type_arrivee"] || $this->ID_ENDROIT_HOTEL == $t["id_type_arrivee"]) {
				 				$venteSelectionne = true;
				 			}
					 		if ($this->ID_ENDROIT_ECHOPPE_ETAL == $t["id_type_arrivee"]) {
					 			$venteEtalSelectionne = true;
				 			}
				 			if ($this->ID_ENDROIT_COFFRE_BRALDUN == $t["id_type_arrivee"]) {
					 			$coffreBraldunSelectionne = true;
				 			}
					 		if ($this->ID_ENDROIT_RESERVATION_COMMUNAUTE == $t["id_type_arrivee"]) {
					 			$reservationCommunauteSelectionnee = true;
				 			}
				 		}
				 		$options .= ">".$t["nom_type_arrivee"]."</option>";
				 		$poids .= "<input type='hidden' name='poids_".$idTypeArrivee."' id='poids_".$idTypeArrivee."' value='".$t["poids_restant"]."' />";
				 		if ($t["nom_systeme"] == "Charrette") {
				 			$charrette .= "<input type='hidden' name='id_charrette_".$idTypeArrivee."' id='id_charrette_".$idTypeArrivee."' value='".$t["id_charrette"]."' />";
				 		}
				   	}
				?>
				<select name="valeur_2" id="valeur_2" onchange="<?php echo $jsVente.$jsBtn.$jsRechercheBraldun?>">
					<option value="-1">(Choisissez un endroit d'arriv&eacute;e)</option>
					<?php echo $options ?>
				</select>
				<?php echo $poids ?><br/>
				<?php echo $charrette ?>
				<br/><br/>
				
				<?php if ($venteEtalSelectionne || $coffreBraldunSelectionne || $reservationCommunauteSelectionnee) : $visibility = 'visible'; $display = 'block'; else: $visibility = 'hidden'; $display = 'none'; endif ?>
				<input type="hidden" name="valeur_3" id="valeur_3" value="-1"/>
				<div id="div_braldun" style="visibility: <?php echo $visibility?>;display :<?php echo $display?>">
					<span id="texte_transbahuter_braldun">
					<?php if ($venteEtalSelectionne) :?>
						<?php echo "Vous pouvez réserver cette vente à un unique Braldûn:"; ?>
					<?php elseif ($reservationCommunauteSelectionnee): ?>
						<?php echo "Vous pouvez réserver ce lot à un unique Braldûn:"; ?>
					<?php elseif ($coffreBraldunSelectionne): ?>
						<?php echo "Entrez le Braldûn destinataire:"; ?>
					<?php endif;?>
					</span><br />
					<input type="text" name="recherche_valeur_3_dest" size='30' id="recherche_valeur_3_dest" value="Entrez un nom" onFocus="if(this.value=='Entrez un nom'){this.value='';};activerRechercheTransbahuterBraldun('valeur_3_dest');" />
					<input type="hidden" name="recherche_valeur_3_dest_actif" id="recherche_valeur_3_dest_actif" value="0" />
					<div class="recherche" id="recherche_valeur_3_dest_update" ></div> <img src="<?php echo $this->config->static->url?>/images/loupe.gif" />
   					<span id="indicateur_recherche_valeur_3_dest" style="display: none"><img src="<?php echo $this->config->static->url?>/images/wait.gif" alt="Recherche..." /></span>
   				</div>
   				
   				<?php if ($venteSelectionne || $reservationCommunauteSelectionnee) : $visibility = 'visible'; $display = 'block'; else: $visibility = 'hidden'; $display = 'none'; endif ?>
				<div id="div_vente_transbahuter" style="visibility: <?php echo $visibility?>;display :<?php echo $display?>">
					<?php if ($venteSelectionne) : $visibility = 'visible'; $display = 'block'; else: $visibility = 'hidden'; $display = 'none'; endif ?>
					<br /><span style="visibility: <?php echo $visibility?>;display :<?php echo $display?>"><b>Les castars sélectionnés ne seront pas pris en compte dans ce transbahutage</b>.</span><br /><br />
					<?php include("transbahuter/vente_formulaire_castars.phtml")?>
   				</div>
   				
				<br/>
				<input type='button' class='button1' id='bouton_deposer' value='Transbahuter !' onclick="charrette();if (controlePrixVenteBoutonDeposer()) {this.disabled=true;$('valeur_10').value=encodePlus($('valeur_commentaire').value);_get_('/competences/doaction?caction=do_competence_transbahuter&idCharretteEtal=<?php echo $this->idCharretteEtal?>')};" disabled>
		<?php else : ?>
			Pas de destination possible autre que votre laban et il est plein ! <br/><br/>
		<?php endif; ?>
	<?php endif; ?>
	</div> 	
<?php else : ?>
	Vous ne pouvez rien transbahuter !<br/><br/>
<?php endif; ?>