 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
    <?php if ($this->nPotions == 0) :?>
 		Vous n'avez pas de potion ou de vernis dans votre laban.<br />
 	<?php else: ?>
 		
 		Potion ou vernis &agrave; utiliser : <br />
 		<select name='valeur_1' id="valeur_1"  onchange="_get_('/competences/doaction?caction=ask_competence_utiliserpotion&potion='+this.value);">
			<option value='-1'>(Choisissez une potion ou un vernis)</option>
			<?php $tabPotions = "";
				foreach ($this->tabPotions as $p) : 
					if ($p["bm_type"] == "malus") :
						$tabPotions .= "'".$p["id_potion"]."',";
					endif;
			?>
				<option value="<?php echo $p["id_potion"] ?>" <?php echo $p["selected"]?>><?php echo $p["nom_type"]?> <?php echo htmlspecialchars($p["nom"]) ?>, n&deg;<?php echo $p["id_potion"]?>, qualit&eacute; <?php echo htmlspecialchars($p["qualite"]) ?>, 
				 niveau: <?php echo $p["niveau"] ?>
				<?php if ($p["nom_type"] == "Potion") :?>	 
					(<?php echo $p["bm_type"]?>)
				<?php endif; ?>
				</option>
			<?php endforeach; 
			if ($tabPotions != "") :
				$tabPotions = " new Array(".substr($tabPotions, 0, strlen($tabPotions)-1).");" ;
			else:
				$tabPotions = " new Array();";
			endif;
			?>
		</select><br /><br />
		
		<?php if (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "potion") : ?>
			
				<?php if ($this->estRegionPvp == true) : ?>
		 			Vous êtes dans une r&eacute;gion PvP, vous pouvez utiliser une potion de malus sur un Braldûn.
		 			<?php $tabPotions = " new Array();"; ?>
		 		<?php else: ?>
		 			Vous êtes dans une r&eacute;gion non PvP, vous ne pouvez pas utiliser une potion de malus sur un Braldûn neutre (non Redresseur et non Gredin).
		 		<?php endif;?>
		 		<br /><br />
				
				<?php $js=" 
				    function controleTypePotion() {
					    marray = $tabPotions;
					    retour = false;
						for (x in marray) {
							if ($('#valeur_1').val() == marray[x]) {
								alert('Vous ne pouvez pas utiliser de potion de malus en zone PvE sur un Braldûn');
								retour = true;
								break;
							}
						} 
						return retour;
					}
				";
				?>
				
				<?php if ($this->nMonstres > 0 || $this->nBralduns > 0): ?>
		 			Pour <?php echo $this->nb_pa?> PA, vous pouvez utiliser la potion choisie sur : <br /><br />
		 		<?php else: ?>
		 			Aucune cible possible sur votre case.
		 		<?php endif;?>
		 		
				<?php if ($this->nMonstres > 0): ?>
				Un monstre<br />
					<select name='valeur_2' id="valeur_2" onchange="javascript:if ($('#valeur_1').val() ==-1 || $('#valeur_3').val() ==-1 && $('#valeur_2').val() ==-1) {$('#bouton_utiliserpotion').attr('disabled', true) } else {$('#bouton_utiliserpotion').attr('disabled',false) }  $('#valeur_3').val(-1); ">
					<option value='-1'>(Choisissez un monstre)</option>
					<?php foreach ($this->tabMonstres as $m) : ?>
					<option value="<?php echo $m["id_monstre"]?>"><?php echo htmlspecialchars($m["nom_monstre"])?> <?php echo htmlspecialchars($m["taille_monstre"])?>  (<?php echo $m["id_monstre"]?>)</option>
					<?php endforeach; ?>
					</select><br /><br />
				<?php else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2" >
				<?php endif; ?>
				
		 		<?php if ($this->nBralduns > 0): ?>
		 		 Un Braldûn<br />
		 			<select name='valeur_3' id="valeur_3" onchange="javascript:<?php echo $js?>;if (controleTypePotion() || $('#valeur_1').val() ==-1 || $('#valeur_2').val() ==-1 && $('#valeur_3').val() ==-1) {$('#bouton_utiliserpotion').attr('disabled', true) } else {$('#bouton_utiliserpotion').attr('disabled',false) } $('#valeur_2').val(-1); ">
					<option value='-1'>(Choisissez un Braldûn)</option>
					<?php foreach ($this->tabBralduns as $h) : ?>
					<option value="<?php echo $h["id_braldun"]?>"><?php echo htmlspecialchars($h["prenom_braldun"])?> <?php echo htmlspecialchars($h["nom_braldun"])?> (<?php echo $h["id_braldun"]?>)</option>
					<?php endforeach; ?>
					</select><br /><br />
				<?php else: ?>
				<input type="hidden" name='valeur_3' value="-1" id="valeur_3">
				<?php endif;?>
			
		<?php elseif (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "vernis_reparateur" || $this->potionCourante["type_potion"] == "vernis_enchanteur") : // vernis ?>
			
			<?php if ($this->potionCourante["type_potion"] == "vernis_reparateur"):?>
				Vous avez choisi un vernis réparateur. Il ne peut être appliqué que sur les équipements sélectionnés suivant leur ingrédient de base.
			<?php else : ?>
				Vous avez choisi un vernis enchanteur. Il peut être appliqué sur tout type d'équipement.
			<?php endif;?>
			<br /><br />
			Attention, si l'équipement est déjà vernis, il perdra les caractéristiques du vernis précédent.<br />
			Il n'est possible d'appliquer un vernis que sur un équipement de niveau inférieur ou égal au niveau du vernis.
			<br /><br />
			
			<?php if ($this->nEquipementsLaban > 0 || $this->nEquipementsCharrette > 0): ?>
	 			Pour <?php echo $this->nb_pa?> PA, vous pouvez utiliser le vernis choisi sur : <br /><br />
	 		<?php else: ?>
	 			Aucun équipement n'est disponible dans votre laban ou dans votre charrette pour l'application du vernis sélectionné.
	 		<?php endif;?>
		 		
			<?php if ($this->nEquipementsLaban > 0): ?>
				Un équipement présent dans votre laban<br />
				<select name='valeur_2' id="valeur_2" onchange="javascript:$('#valeur_3').val(-1); if ($('#valeur_1').val() ==-1 || $('#valeur_2').val() ==-1) {$('#bouton_utiliserpotion').attr('disabled', true) } else {$('#bouton_utiliserpotion').attr('disabled',false) } ">
				<option value='-1'>(Choisissez un équipement)</option>
				<?php foreach ($this->tabEquipementsLaban as $e) : ?>
					<option value="<?php echo $e["id_equipement"]?>"><?php echo htmlspecialchars($e["nom"])?>, n&deg; <?php echo $e["id_equipement"]?></option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2" >
			<?php endif; ?>
			
	 		<?php if ($this->nEquipementsCharrette > 0): ?>
	 		 	Un équipement présent dans votre charrette<br />
	 			<select name='valeur_3' id="valeur_3" onchange="javascript:$('#valeur_2').val(-1); if ($('#valeur_1').val() ==-1 || $('#valeur_3').val() ==-1) {$('#bouton_utiliserpotion').attr('disabled', true) } else {$('#bouton_utiliserpotion').attr('disabled',false) }  ">
				<option value='-1'>(Choisissez un équipement)</option>
				<?php foreach ($this->tabEquipementsCharrette as $e) : ?>
					<option value="<?php echo $e["id_equipement"]?>"><?php echo htmlspecialchars($e["nom"])?>, n&deg; <?php echo $e["id_equipement"]?></option>
				<?php endforeach; ?>
				</select><br /><br />
			<?php else: ?>
				<input type="hidden" name='valeur_3' value="-1" id="valeur_3">
			<?php endif;?>
		<?php endif;?>
		
	<?php endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : 
	$nom = " !";	
	if (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "potion") : 
		$nom = " la potion !";
	else:
		$nom = " le vernis !";
	endif;
?>
<input type='button' class='button' value='Utiliser<?php echo $nom?>' id='bouton_utiliserpotion' onclick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_utiliserpotion&potion="+$("#valeur_1").val());' disabled>
<?php endif ?>
