<div class='comp_titre'>Utiliser une potion</div>

 <div class='comp_contenu'>
	 <div id='utiliserpotion_text' style="display:block"  onClick="javascript:switch2div('utiliserpotion_text','utiliserpotion_copie');">
	 <? include("commun_text_resultat.phtml") ?>
		 Vous avez utilis&eacute; une potion <?=htmlentities($this->retourPotion['potion']["nom"]) ?> de qualit&eacute; <?=htmlentities($this->retourPotion['potion']["qualite"])?>
		  sur <?=htmlentities($this->retourPotion["cible"]["nom_cible"])?> (<?=$this->retourPotion["cible"]["id_cible"]?>) N<?=$this->retourPotion["cible"]["niveau_cible"]?>.<br />
		  
		  L'effet de la potion porte sur <?=$this->retourPotion['effet']['nb_tour_restant']?> tour<? if ($this->retourPotion['effet']['nb_tour_restant'] > 1): echo 's'; endif; ?>.
		  <br />
		  La cible vient de subir 
		  <?=$this->retourPotion['effet']["nEffet"] ?> point<? if ($this->retourPotion['effet']["nEffet"]): echo 's'; endif; ?> de <?=$this->retourPotion['potion']["bm_type"] ?> sur <?=$this->retourPotion['potion']["caracteristique"]?>
		  <br />
		  L'effet est imm&eacute;diat.<br />
	 
	 </div>
	 
	 <div id='utiliserpotion_copie' style="display:none">
		<textarea onClick="javascript:this.select();" rows=4 cols=40><?
		include("commun_copie_resultat.phtml");
		 echo "Vous avez utilis&eacute; une potion ";
		 echo htmlentities($this->retourPotion['potion']["nom"]). " de qualit&eacute; ".htmlentities($this->retourPotion['potion']["qualite"]);
		 echo "sur ".htmlentities($this->retourPotion["cible"]["nom_cible"])." (".$this->retourPotion["cible"]["id_cible"].") N".$this->retourPotion["cible"]["niveau_cible"].".";
		 echo "
";
		 echo " L'effet de la potion porte sur ".$this->retourPotion['effet']['nb_tour_restant']." tour";
		 if ($this->retourPotion['effet']['nb_tour_restant'] > 1): echo 's'; endif;
		 echo ".
";
		 echo "La cible vient de subir ";
		 echo $this->retourPotion['effet']["nEffet"]. " point";
		 if ($this->retourPotion['effet']["nEffet"]): echo 's'; endif;
		 echo " de ".$this->retourPotion['potion']["bm_type"]." sur ";
		 echo $this->retourPotion['potion']["caracteristique"];
		 echo "
";
		 echo " L'effet est imm&eacute;diat.";
		 echo "
";
		?></textarea>
	</div>
 </div>

<input type='button' class='button1' value='Copier' onClick="javascript:switch2div('utiliserpotion_text','utiliserpotion_copie');">
<? include("commun_fermer.phtml") ?>