 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
    <? if ($this->nPotions == 0) :?>
 		Vous n'avez pas de potion dans votre laban.<br />
 	<? else: ?>
 		Potion &agrave; utiliser : <br />
 		<select name='valeur_1' id="valeur_1" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1 && $('valeur_3').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false }">
			<option value='-1'>(Choisis une potion)</option>
			<? foreach ($this->tabPotions as $p) : ?>
				<option value="<?=$p["id_potion"] ?>"><?=htmlspecialchars($p["nom"]) ?> : qualit&eacute; <?=htmlspecialchars($p["qualite"]) ?>,
				 niveau: <?=$p["niveau"] ?></option>
			<? endforeach; ?>
		</select><br /><br />
		
		<? if ($this->nMonstres > 0 || $this->nHobbits > 0): ?>
 			Pour <?=$this->nb_pa?> PA, vous pouvez utiliser la potion choisie sur : <br /><br />
 		<? else: ?>
 			Aucune cible possible sur votre case.
 		<? endif;?>
 		
		<? if ($this->nMonstres > 0): ?>
		Un monstre<br />
			<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_3').value==-1 && $('valeur_2').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false }  $('valeur_3').value=-1; ">
			<option value='-1'>(Choisis un monstre)</option>
			<? foreach ($this->tabMonstres as $m) : ?>
			<option value="<?=$m["id_monstre"]?>"><?=htmlspecialchars($m["nom_monstre"])?> <?=htmlspecialchars($m["taille_monstre"])?>  (<?=$m["id_monstre"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
		<? else: ?>
		<input type="hidden" name='valeur_2' value="-1" id="valeur_2" >
		<? endif; ?>
		
 		<? if ($this->nHobbits > 0): ?>
 		 Un hobbit<br />
 			<select name='valeur_3' id="valeur_3" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_2').value==-1 && $('valeur_3').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false } $('valeur_2').value=-1; ">
			<option value='-1'>(Choisis un hobbit)</option>
			<? foreach ($this->tabHobbits as $h) : ?>
			<option value="<?=$h["id_hobbit"]?>"><?=htmlspecialchars($h["prenom_hobbit"])?> <?=htmlspecialchars($h["nom_hobbit"])?> (<?=$h["id_hobbit"]?>)</option>
			<? endforeach; ?>
			</select><br /><br />
		<? else: ?>
		<input type="hidden" name='valeur_3' value="-1" id="valeur_3">
		<? endif;?>
		
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : ?>
<input type='button' class='button1' value='Utiliser la potion !' id='bouton_utiliserpotion' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_utiliserpotion");' disabled>
<? endif ?>
