 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <div class='comp_contenu'>
    <? if ($this->nPotions == 0) :?>
 		Vous n'avez pas de potion ou de vernis dans votre laban.<br />
 	<? else: ?>
 		
 		Potion ou vernis &agrave; utiliser : <br />
 		<select name='valeur_1' id="valeur_1"  onChange="_get_('/competences/doaction?caction=ask_competence_utiliserpotion&potion='+this.value);">>
			<option value='-1'>(Choisissez une potion ou un vernis)</option>
			<? $tabPotions = "";
				foreach ($this->tabPotions as $p) : 
					if ($p["bm_type"] == "malus") :
						$tabPotions .= "'".$p["id_potion"]."',";
					endif;
			?>
				<option value="<?=$p["id_potion"] ?>" <?=$p["selected"]?>><?=$p["nom_type"]?> <?=htmlspecialchars($p["nom"]) ?>, n&deg;<?=$p["id_potion"]?>, qualit&eacute; <?=htmlspecialchars($p["qualite"]) ?>, 
				 niveau: <?=$p["niveau"] ?>
				<? if ($p["nom_type"] == "Potion") :?>	 
					(<?=$p["bm_type"]?>)
				<? endif; ?>
				</option>
			<? endforeach; 
			if ($tabPotions != "") :
				$tabPotions = " new Array(".substr($tabPotions, 0, strlen($tabPotions)-1).");" ;
			else:
				$tabPotions = " new Array();";
			endif;
			?>
		</select><br /><br />
		
		<? if (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "potion") : ?>
			
				<? if ($this->estRegionPvp == true) : ?>
		 			Vous êtes dans une r&eacute;gion PvP, vous pouvez utiliser une potion de malus sur un braldun.
		 			<? $tabPotions = " new Array();"; ?>
		 		<? else: ?>
		 			Vous êtes dans une r&eacute;gion non PvP, vous ne pouvez pas utiliser une potion de malus sur un braldun.
		 		<? endif;?>
		 		<br><br>
				
				<? $js=" 
				    function controleTypePotion() {
					    marray = $tabPotions;
					    retour = false;
						for (x in marray) {
							if ($('valeur_1').value == marray[x]) {
								alert('Vous ne pouvez pas utiliser de potion de malus en zone PvE sur un braldun');
								retour = true;
								break;
							}
						} 
						return retour;
					}
				";
				?>
				
				<? if ($this->nMonstres > 0 || $this->nBralduns > 0): ?>
		 			Pour <?=$this->nb_pa?> PA, vous pouvez utiliser la potion choisie sur : <br /><br />
		 		<? else: ?>
		 			Aucune cible possible sur votre case.
		 		<? endif;?>
		 		
				<? if ($this->nMonstres > 0): ?>
				Un monstre<br />
					<select name='valeur_2' id="valeur_2" onChange="javascript:if ($('valeur_1').value==-1 || $('valeur_3').value==-1 && $('valeur_2').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false }  $('valeur_3').value=-1; ">
					<option value='-1'>(Choisissez un monstre)</option>
					<? foreach ($this->tabMonstres as $m) : ?>
					<option value="<?=$m["id_monstre"]?>"><?=htmlspecialchars($m["nom_monstre"])?> <?=htmlspecialchars($m["taille_monstre"])?>  (<?=$m["id_monstre"]?>)</option>
					<? endforeach; ?>
					</select><br /><br />
				<? else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2" >
				<? endif; ?>
				
		 		<? if ($this->nBralduns > 0): ?>
		 		 Un braldun<br />
		 			<select name='valeur_3' id="valeur_3" onChange="javascript:<?=$js?>;if (controleTypePotion() || $('valeur_1').value==-1 || $('valeur_2').value==-1 && $('valeur_3').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false } $('valeur_2').value=-1; ">
					<option value='-1'>(Choisissez un braldun)</option>
					<? foreach ($this->tabBralduns as $h) : ?>
					<option value="<?=$h["id_braldun"]?>"><?=htmlspecialchars($h["prenom_braldun"])?> <?=htmlspecialchars($h["nom_braldun"])?> (<?=$h["id_braldun"]?>)</option>
					<? endforeach; ?>
					</select><br /><br />
				<? else: ?>
				<input type="hidden" name='valeur_3' value="-1" id="valeur_3">
				<? endif;?>
			
		<? elseif (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "vernis_reparateur" || $this->potionCourante["type_potion"] == "vernis_enchanteur") : // vernis ?>
			
			<? if ($this->potionCourante["type_potion"] == "vernis_reparateur"):?>
				Vous avez choisi un vernis réparateur. Il ne peut être appliqué que sur les équipements sélectionnés suivant leur ingrédient de base.
			<? else : ?>
				Vous avez choisi un vernis enchanteur. Il peut être appliqué sur tout type d'équipement.
			<? endif;?>
			<br><br>
			Attention, si l'équipement est déjà vernis, il perdra les caractéristiques du vernis précédent.<br>
			Il n'est possible d'appliquer un vernis que sur un équipement de niveau inférieur ou égal au niveau du vernis.
			<br><br>
			
			<? if ($this->nEquipementsLaban > 0 || $this->nEquipementsCharrette > 0): ?>
	 			Pour <?=$this->nb_pa?> PA, vous pouvez utiliser le vernis choisi sur : <br /><br />
	 		<? else: ?>
	 			Aucun équipement n'est disponible dans votre laban ou dans votre charrette pour l'application du vernis sélectionné.
	 		<? endif;?>
		 		
			<? if ($this->nEquipementsLaban > 0): ?>
				Un équipement présent dans votre laban<br />
				<select name='valeur_2' id="valeur_2" onChange="javascript:$('valeur_3').value=-1; if ($('valeur_1').value==-1 || $('valeur_2').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false } ">
				<option value='-1'>(Choisissez un équipement)</option>
				<? foreach ($this->tabEquipementsLaban as $e) : ?>
					<option value="<?=$e["id_equipement"]?>"><?=htmlspecialchars($e["nom"])?>, n&deg; <?=$e["id_equipement"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_2' value="-1" id="valeur_2" >
			<? endif; ?>
			
	 		<? if ($this->nEquipementsCharrette > 0): ?>
	 		 	Un équipement présent dans votre charrette<br />
	 			<select name='valeur_3' id="valeur_3" onChange="javascript:$('valeur_2').value=-1; if ($('valeur_1').value==-1 || $('valeur_3').value==-1) {$('bouton_utiliserpotion').disabled=true } else {$('bouton_utiliserpotion').disabled=false }  ">
				<option value='-1'>(Choisissez un équipement)</option>
				<? foreach ($this->tabEquipementsCharrette as $e) : ?>
					<option value="<?=$e["id_equipement"]?>"><?=htmlspecialchars($e["nom"])?>, n&deg; <?=$e["id_equipement"]?></option>
				<? endforeach; ?>
				</select><br /><br />
			<? else: ?>
				<input type="hidden" name='valeur_3' value="-1" id="valeur_3">
			<? endif;?>
		<? endif;?>
		
	<? endif; ?>
 </div>

<br />
<?php if ($this->assezDePa == true) : 
	$nom = " !";	
	if (isset($this->potionCourante) && $this->potionCourante["type_potion"] == "potion") : 
		$nom = " la potion !";
	else:
		$nom = " le vernis !";
	endif;
?>
<input type='button' class='button1' value='Utiliser<?=$nom?>' id='bouton_utiliserpotion' onClick='this.disabled=true;_get_("/competences/doaction?caction=do_competence_utiliserpotion&potion="+$("valeur_1").value);' disabled>
<? endif ?>
