<div class="box_pub_login">
<div class="inner">
<p class="titre textalic textsizee center">Association JeuxWeb.org</p>
<div class="contenu">
    <p class="box_contenu3 textalic">
    	Le jeu, le site, les règles, le bugtrack, les forums sont hébergés par l'association <a href="http://www.jeuxweb.org">JeuxWeb.org ASBL</a>.
		<br/>
		<a href="http://www.jeuxweb.org" target="_blank" title="Jeu hébergé par l'Association JeuxWeb.org ASBL">
	  	<img src="<?php echo $this->config->static->url?>/images/externe/banner_jw-156-20.gif" alt="Jeux Web" border="0" height="20" width="156" />
	  </a>
	  <br/>
	  JeuxWeb.org est une Association Sans Buts Lucratifs (asbl)
	</p>
</div>
</div>
</div>