
<div class="box_pub_login">
<div class="inner">
<ul class="titre textalic textsizee">Association JeuxWeb.org</ul>

	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    	Le jeu, le site, le wiki, le bugtrack, les forums sont hébergés par l'association <a href="http://www.jeuxweb.org">JeuxWeb.org ASBL</a>.
			<br>
			<a href="http://www.jeuxweb.org" target="_blank" title="Jeu hébergé par l'Association JeuxWeb.org ASBL">
		  	<img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="Jeux Web" border="0" height="30" width="234">
		  </a>
		  <br>
		  JeuxWeb.org est une Association Sans Buts Lucratifs (asbl)
		</ul>
	</div>

</div>
</div>