<div class="box_authentification">
<div class="inner">
<p class="titrea textalia titreasize0" style="margin-top:-15px;"><?php if ($this->estMobile) : ?> Braldahim Mobile<?php endif;?></p>

<span class="titrea textalib titreasizeb" >Connexion
	<?php if ($this->config->general->production != 1) :?>
		B&ecirc;ta
	<?php endif;?>
</span>

<?php if(!empty($this->message)) :?> 
<div class="message_erreur" id="message_erreur"> 
<?php echo $this->escape($this->message);?> 
</div> 
<?php endif; ?> 

    <br />
    <?php echo Bral_Helper_Bougrie::render(); ?>
    <br />
    
    <form action="/auth/login" method="post">
	    <table width="100%"> 
	    <tr>
   			<td>Email du joueur :</td>
			<td><input type="email" required autofocus name="post_email_braldun" id='post_email_braldun' size='25' maxlength='100'/></td>
	    </tr>
	    <tr>
	    	<td>Mot de passe :</td> 
	    	<td><input type="password" name="post_password_braldun"  size='25'  maxlength='50' required /></td>
	    </tr>
	    </table>
	    
	    <br />
    
    	Gardiennage :
		    oui <input type="radio" id="auth_gardiennage_oui" name="auth_gardiennage" value="oui"/>
		    non <input type="radio" id="auth_gardiennage_non" name="auth_gardiennage" value="non" checked="checked"/> 
		    <br />
		    
		    Activation :
		    oui <input type="radio" id="auth_activation_oui" name="auth_activation" value="oui" checked="checked"/>
		    non <input type="radio" id="auth_activation_non" name="auth_activation" value="non"/>
		    <br /><br />
			    
			     <input type="submit" class='button play' value="Connexion" />
			     
	    <br /><br />
	   <a href="/Perdu">Perdu ?</a> ou <a href="/inscription">Pas encore inscrit ?</a> <br /><br /><br /> 
	    <?php echo new Zend_Date(); ?>
	    
    <?php $s = ""; if ($this->nbConnecte > 1): $s = "s"; endif; ?>
    -  Actuellement <?php echo $this->nbConnecte?> Braldûn<?php echo $s ?> connect&eacute;<?php echo $s?>
    </form> 
    </div>
</div>