<br />
<div class="box_contenu textalic">
	<div class="titre textalic textsizea">
	Marché aux équipements
	</div><br />
	
<table width='100%'>
<tr>
<td>
	Filtre par comté: 
	<br />
	<select id="region" name="region" onchange="document.location.href = '/marcheequipement/?regionselect='+this.value+'&emplacementselect=<?=$this->emplacementSelect?>&equipementselect=<?=$this->equipementSelect?>&uid='+(new Date()).valueOf()">
	<? foreach($this->regions as $k => $e): ?>
		<option value="<?=$k?>" <?if ($this->regionSelect == $k): echo "selected" ; endif;?>><?=$e?></option>
	<? endforeach;?>
	</select>
</td>
<td>
	Filtre par emplacement: 
	<br />
	<select id="emplacement" name="emplacement" onchange="document.location.href = '/marcheequipement/?regionselect<?=$this->regionSelect?>&emplacementselect='+this.value+'&equipementselect=<?=$this->equipementSelect?>&uid='+(new Date()).valueOf()">
	<? foreach($this->emplacements as $k => $e): ?>
		<option value="<?=$k?>" <?if ($this->emplacementSelect == $k): echo "selected" ; endif;?>><?=$e?></option>
	<? endforeach;?>
	</select>
</td>
<td>
	Filtre par équipement:
	<br />
	<select id="equipement" name="equipement" onchange="document.location.href = '/marcheequipement/?regionselect<?=$this->regionSelect?>&emplacementselect=<?=$this->emplacementSelect?>&equipementselect='+this.value+'&uid='+(new Date()).valueOf()">
	<? foreach($this->equipements as $k => $e): ?>
		<option value="<?=$k?>" <?if ($this->equipementSelect == $k): echo "selected" ; endif;?>><?=$e?></option>
	<? endforeach;?>
	</select>
</td>
</tr>
</table>

<br /><br />

<div id="mygrid_container" style="width:770px;height:650px;align:center"></div> 
<script>
	gridQString = '/marcheequipement/renderxml?regionselect=<?=$this->regionSelect?>&emplacementselect=<?=$this->emplacementSelect?>&equipementselect=<?=$this->equipementSelect?>&uid='+(new Date()).valueOf();
	function sortGridOnServer(ind,gridObj,direct){
	    mygrid.clearAll();
	    murl = gridQString+(gridQString.indexOf("?")>=0?"&":"?")+"orderby="+ind+"&direct="+direct;
	    mygrid.loadXML(murl);
	    mygrid.setSortImgState(true,ind,direct);
	    return false;
	}
	
	mygrid = new dhtmlXGridObject('mygrid_container');
	mygrid.setImagePath("/public/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygrid.setHeader("Comté,Date,Braldun,Echoppe,Emplacement,,Objet,Niveau,Prix,Commentaire");
	mygrid.setInitWidths("60,55,100,70,85,32,100,65,90,*");
	mygrid.setColAlign("left,left,left,left,left,left,left,centr,left,left");
	mygrid.setColTypes("ro,ro,link,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setSkin("braldahim");
	mygrid.setColSorting("server,server,server,server,server,server,server,server");
	mygrid.attachEvent("onBeforeSorting",sortGridOnServer);
	mygrid.enableSmartRendering(true,100);
	mygrid.init();
	mygrid.loadXML(gridQString);
	mygrid.setSortImgState(true,1,"des");
</script>

</div>