<div class="box_inscription">
<div class="box_titre1">Inscription d'un nouvel hobbit</div><br />

<form action="<?=$this->baseUrl ?>/inscription/ajouter" method="post">

	<?php if(!empty($this->messages)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php foreach($this->messages as $message) :?>
		<?=$this->escape($message);?><br>
	<?php endforeach; ?>
	</div> 
	<?php endif; ?> 
	
<div>
	<?php if(!empty($this->messagesNom)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php foreach($this->messagesNom as $message) :?>
		<?=$this->escape($message);?><br>
	<?php endforeach; ?>
	</div> 
	<?php endif; ?>
    <label for="hobbit">Hobbit</label><br>
    Entre 5 et 20 caract&egrave;res<br>
    <input type="text" name="nom_hobbit" 
        value="<?php echo $this->escape(trim($this->hobbit->nom_hobbit));?>" size="25" maxlength="20"/>
</div>
<div><br>
	<?php if(!empty($this->messagesEmail)) :?> 
	<div class="message_erreur" id="message_erreur"> 
	<?php foreach($this->messagesEmail as $message) :?>
		<?=$this->escape($message);?><br>
	<?php endforeach; ?>
	</div>
	<?php endif; ?>
    <label for="title">Email</label><br>
    Un email de confirmation vous sera demandé à cette adresse<br>
    <input type="text" name="email_hobbit" value="<?=$this->escape($this->hobbit->email_hobbit);?>" size="25" maxlength="100"/> 
    <?php if(!empty($this->messagesEmailConfirm)) :?> 
	<div class="message_erreur" id="message_erreur"> 
		<?=$this->escape($this->messagesEmailConfirm);?><br>
	</div>
	<?php endif; ?>
	<br><label for="title">Confirmation Email</label><br>
    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->hobbit->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
</div>
<div><br>
	<?php if(!empty($this->messagesPassword)) :?>
	<div class="message_erreur" id="message_erreur"> 
	<?php foreach($this->messagesPassword as $message) :?>
		<?=$this->escape($message);?><br>
	<?php endforeach; ?>
	</div>
	<?php endif; ?>
    <label for="title">Mot de Passe</label><br>
    Entre 5 et 20 caract&egrave;res<br>
    <input type="password" name="password_hobbit" value="" size="25" maxlength="20"/>
	<?php if(!empty($this->messagesPasswordConfirm)) :?> 
	<div class="message_erreur" id="message_erreur"> 
		<?=$this->escape($this->messagesPasswordConfirm);?><br>
	</div>
	<?php endif; ?>
    <br><label for="title">Confirmation Mot de Passe</label><br>
    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
</div>
<div><br>
	<?php if(!empty($this->messagesSexe)) :?> 
	<div class="message_erreur" id="message_erreur"> 
		<?=$this->escape($this->messagesSexe);?><br>
	</div>
	<?php endif; ?>
Sexe du Hobbit : <input type="radio" name="sexe_hobbit" value="feminin">F&eacute;minin 
<input type="radio" name="sexe_hobbit" value="masculin">Masculin <br><br>
</div>

<div id="formbutton">
<input type="hidden" name="id" value="<?php echo $this->hobbit->id; ?>" />
<input type="submit" name="add" value="ajouter" /> <input type="button" name="add" value="Annuler" onClick="javascript:document.location.href='/'"/>
</div>
</form>
</div>
