<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<form action="/inscription/ajouter" method="post">
<div class="box_inscription">
<div class="inner">
    <ul class="titre textalic textsizea">Inscription</ul>
    <ul class="titre textalic textsizeb">Cr&eacute;ation d'un nouvel hobbit</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<ul class="titre textalic textsizec">Contr&ocirc;le</ul>
			<?php if(!empty($this->messageCaptchaInvalide)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->messageCaptchaInvalide?><br />
			</div>
			<?php endif; ?>
			<img src="/public/images/captcha/<?=$this->captcha->getId();?>.png"><br>
			&Eacute;crivez ici le texte que vous voyez ci-dessus : 
			<input type="text" name="captcha[input]" value="" size="10" maxlength="10"/> 
			<input type="hidden" name="captcha[id]" value="<?=$this->captcha->getId();?>" />
			<ul class="titre textalic textsized">Si vous ne voyez pas clairement le texte, <a href="/inscription">recharger la page</a></ul>
			<br>
			<br>

		<?php if(!empty($this->messages)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messages as $message) :?>
				<?=$this->escape($message);?><br />
			<?php endforeach; ?>
		</div> 
		<?php endif; ?> 
		
		<div>

			<ul class="titre textalic textsizec">Nom de Hobbit</ul>
			<label>Un nom de famille vous sera automatiquement attribu&eacute; lors de la validation d'inscription.<br /></label>
			<br />
		    
		    <ul class="titre textalic textsizec">Pr&eacute;nom du Hobbit</ul>
		    <?php if(!empty($this->messagesPrenom)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPrenom as $message) :?>
				<?=$message?><br />
			<?php endforeach; ?>
			</div> 
			<?php endif; ?>
		    
		    Entre 5 et 15 caract&egrave;res<br />
		    La premi&egrave;re lettre de votre pr&eacute;nom sera automatiquement mise en majuscule<br />
		    Les chiffres et les caract&egrave;res sp&eacute;ciaux ne sont pas autoris&eacute;s dans le pr&eacute;nom.<br>
		    Certains pr&eacute;noms sont interdits, d'autres sont d&eacute;j&agrave; utilis&eacute;s.<br><br>
		    
		     Si le pr&eacute;nom que vous choisissez est d&eacute;j&agrave; utilis&eacute; avec le nom tir&eacute; au sort, il sera 
		    suffix&eacute; de <u>Junior</u>. 
		    <br>
		    Ceci arrive tr&egrave;s rarement, mais vous pouvez v&eacute;rifier l'utilisation ou non de 
		    votre pr&eacute;nom en consultant 
		    
		    <a onClick="javascript:ouvrirWin('/voir/hobbits');" title="Cliquez pour voir la liste des hobbits inscrits">
  				la liste des hobbits inscrits.
  			</a>
  	 		<br>
		    
		    <br>
		    <u>Choisissez bien votre pr&eacute;nom</u>, il ne sera pas possible de le changer par la suite.<br>
		    
			<input type="text" name="prenom_hobbit" value="<?=$this->hobbit->prenom_hobbit;?>" size="25" maxlength="15"/>
		</div>
		<div><br />
		   <ul class="titre textalic textsizec">Email</ul>
		  	<?php if(!empty($this->messagesEmail)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesEmail as $message) :?>
				<?=$message;?><br />
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    Un email de confirmation vous sera envoy&eacute; &agrave; cette adresse<br />
		    <input type="text" name="email_hobbit" value="<?=$this->escape($this->hobbit->email_hobbit);?>" size="25" maxlength="100"/> 
		    <?php if(!empty($this->messagesEmailConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->messagesEmailConfirm;?><br />
			</div>
			<?php endif; ?>
			<br /><label for="title">Confirmation Email</label><br />
		    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->hobbit->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
		</div>
		<div><br />

		    <ul class="titre textalic textsizec">Mot de passe</ul>
		    <?php if(!empty($this->messagesPassword)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPassword as $message) :?>
				<?=$message?><br />
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
			
		    Entre 5 et 20 caract&egrave;res<br />
		    <input type="password" name="password_hobbit" value="" size="25" maxlength="20"/>
			<?php if(!empty($this->messagesPasswordConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->messagesPasswordConfirm?><br />
			</div>
			<?php endif; ?>
		    <br /><label for="title">Confirmation Mot de Passe</label><br />
		    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
		</div>
		<div><br />
			<?php if(!empty($this->messagesSexe)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesSexe);?><br />
			</div>
			<?php endif; ?>
			Sexe du Hobbit : <input type="radio" name="sexe_hobbit" value="feminin" 
			<?php if ($this->hobbit->sexe_hobbit == "feminin"): echo "checked"; endif; ?>>F&eacute;minin 
			<input type="radio" name="sexe_hobbit" value="masculin"
			<?php if ($this->hobbit->sexe_hobbit == "masculin"): echo "checked"; endif; ?>>Masculin <br /><br />
		</div>
	
		<div><br />
			Une Comt&eacute; est une r&eacute;gion g&eacute;ographique contenant un certain nombre de 
			villes, de lieux... <br>Vous arriverez dans une des mairies de la Comt&eacute; que vous allez choisir.
			<br><br>
			<!--  Attention, les Comt&eacute;s PVP (PVP : oui ) indiquent des Comt&eacute;s dans lesquelles
			l'attaque des hobbits entre eux est autoris&eacute;e.<br> Il est donc fortemement d&eacute;conseillé
			d'atterir dans une de ces Comt&eacute;s &agrave; la naissance.
			-->
			<br><br>
			
			Choisissez une Comt&eacute; : 
			<select name='id_region' id='id_region'>
				<option value='-1' <? if ($this->id_region == -1) echo "selected" ?>>
					Comt&eacute; Al&eacute;atoire
				</option>
				<? foreach ($this->regions as $k => $v) : ?>
				<option value="<?=$k?>" <? if ($this->id_region == $k) echo "selected" ?>>
					<?=htmlspecialchars($v["nom"])?> - PVP : <?=$v["est_pvp"] ?>
				</option>
				<? endforeach; ?>
			</select><br /><br />
			Vous pourrez bien s&ucirc;r changer de comté au cours du jeu.<br>
			
			<br>

			<ul class="titre textalic textsizec">Charte</ul>
			Vous devez accepter la charte d'utilisation pr&eacute;sent&eacute;e ici :<br>
			<a href="<?=$this->config->general->charte->url?>" target="_blank"><?=$this->config->general->charte->url?></a>.
			<br><br>
			D&egrave;s lors que vous serez inscrit, nous consid&eacute;rerons que vous aurez accept&eacute; la charte du jeu.<br>
		</div>
		<div id="formbutton">
			<input type="submit" class='button1' name="ajouter" value="J'ai lu et j'accepte la charte. Je veux m'inscrire !" /> 
			<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/'"/>
		</div>
		
		</ul>
	</div>
	&nbsp;
</div>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

