<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<form action="<?=$this->baseUrl ?>/inscription/ajouter" method="post">
<div class="box_inscription">
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
<div class="inner">
    <ul class="titre textalic textsizea">Inscription</ul>
    <ul class="titre textalic textsizeb">Cr&eacute;ation d'un nouvel hobbit</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	
		<?php if(!empty($this->messages)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messages as $message) :?>
				<?=$this->escape($message);?><br>
			<?php endforeach; ?>
		</div> 
		<?php endif; ?> 
		
		<div>
			<?php if(!empty($this->messagesPrenom)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPrenom as $message) :?>
				<?=$this->escape($message);?><br>
			<?php endforeach; ?>
			</div> 
			<?php endif; ?>
			<label>Nom de Hobbit : Un nom de famille vous sera automatiquement attribu&eacute;
		    lors de la validation d'inscription.<br>
		    </label>
		    <br>
		    <label for="hobbit">Pr&eacute;nom du Hobbit
		    </label><br>
		    Entre 5 et 10 caract&egrave;res<br>
		    <input type="text" name="prenom_hobbit" 
		        value="<?php echo $this->escape(trim($this->hobbit->prenom_hobbit));?>" size="25" maxlength="20"/>
		</div>
		<div><br>
			<?php if(!empty($this->messagesEmail)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesEmail as $message) :?>
				<?=$message;?><br>
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    <label for="title">Email</label><br>
		    Un email de confirmation vous sera envoyé à cette adresse<br>
		    <input type="text" name="email_hobbit" value="<?=$this->escape($this->hobbit->email_hobbit);?>" size="25" maxlength="100"/> 
		    <?php if(!empty($this->messagesEmailConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesEmailConfirm);?><br>
			</div>
			<?php endif; ?>
			<br><label for="title">Confirmation Email</label><br>
		    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->hobbit->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
		</div>
		<div><br>
			<?php if(!empty($this->messagesPassword)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPassword as $message) :?>
				<?=$this->escape($message);?><br>
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    <label for="title">Mot de Passe</label><br>
		    Entre 5 et 20 caract&egrave;res<br>
		    <input type="password" name="password_hobbit" value="" size="25" maxlength="20"/>
			<?php if(!empty($this->messagesPasswordConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesPasswordConfirm);?><br>
			</div>
			<?php endif; ?>
		    <br><label for="title">Confirmation Mot de Passe</label><br>
		    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
		</div>
		<div><br>
			<?php if(!empty($this->messagesSexe)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesSexe);?><br>
			</div>
			<?php endif; ?>
			Sexe du Hobbit : <input type="radio" name="sexe_hobbit" value="feminin">F&eacute;minin 
			<input type="radio" name="sexe_hobbit" value="masculin">Masculin <br><br>
		</div>
	
		<div><br>
			
			Comt&eacute; : 
			<select name='id_region' id='id_region'>
				<option value='-1' <? if ($this->id_region == -1) echo "selected" ?>>Comt&eacute; Al&eacute;atoire</option>
				<? foreach ($this->regions as $k => $v) : ?>
				<option value="<?=$k?>" <? if ($this->id_region == $k) echo "selected" ?>><?=htmlentities($v)?></option>
				<? endforeach; ?>
			</select><br><br>
		</div>
		<div id="formbutton">
			<input type="submit" class='button1' name="ajouter" value="Inscription !" /> 
			<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/'"/>
		</div>
		
		</ul>
	</div>
	&nbsp;
</div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

