<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<form action="/inscription/ajouter" method="post">
<div class="box_inscription">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Inscription</ul>
    <ul class="titre textalic textsizeb">Cr&eacute;ation d'un nouvel hobbit</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	
		<?php if(!empty($this->messages)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messages as $message) :?>
				<?=$this->escape($message);?><br />
			<?php endforeach; ?>
		</div> 
		<?php endif; ?> 
		
		<div>
			<?php if(!empty($this->messagesPrenom)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPrenom as $message) :?>
				<?=$message?><br />
			<?php endforeach; ?>
			</div> 
			<?php endif; ?>
			<label>Nom de Hobbit : Un nom de famille vous sera automatiquement attribu&eacute;
		    lors de la validation d'inscription.<br />
		    </label>
		    <br />
		    <label for="hobbit">Pr&eacute;nom du Hobbit
		    </label><br />
		    Entre 5 et 15 caract&egrave;res<br />
		    La premi&egrave;re lettre de votre pr&eacute;nom sera automatiquement mise en majuscule<br />
		    <input type="text" name="prenom_hobbit" 
		        value="<?=$this->hobbit->prenom_hobbit;?>" size="25" maxlength="15"/>
		</div>
		<div><br />
			<?php if(!empty($this->messagesEmail)) :?> 
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesEmail as $message) :?>
				<?=$message;?><br />
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    <label for="title">Email</label><br />
		    Un email de confirmation vous sera envoy&eacute; &agrave; cette adresse<br />
		    <input type="text" name="email_hobbit" value="<?=$this->escape($this->hobbit->email_hobbit);?>" size="25" maxlength="100"/> 
		    <?php if(!empty($this->messagesEmailConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesEmailConfirm);?><br />
			</div>
			<?php endif; ?>
			<br /><label for="title">Confirmation Email</label><br />
		    <input type="text" name="email_confirm_hobbit" value="<?=$this->escape($this->hobbit->email_confirm_hobbit);?>" size="25" maxlength="100"/>      
		</div>
		<div><br />
			<?php if(!empty($this->messagesPassword)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPassword as $message) :?>
				<?=$message?><br />
			<?php endforeach; ?>
			</div>
			<?php endif; ?>
		    <label for="title">Mot de Passe</label><br />
		    Entre 5 et 20 caract&egrave;res<br />
		    <input type="password" name="password_hobbit" value="" size="25" maxlength="20"/>
			<?php if(!empty($this->messagesPasswordConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->messagesPasswordConfirm?><br />
			</div>
			<?php endif; ?>
		    <br /><label for="title">Confirmation Mot de Passe</label><br />
		    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
		</div>
		<div><br />
			<?php if(!empty($this->messagesSexe)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesSexe);?><br />
			</div>
			<?php endif; ?>
			Sexe du Hobbit : <input type="radio" name="sexe_hobbit" value="feminin">F&eacute;minin 
			<input type="radio" name="sexe_hobbit" value="masculin">Masculin <br /><br />
		</div>
	
		<div><br />
			Une Comt&eacute; est une r&eacute;gion g&eacute;ographique contenant un certain nombre de 
			villes, de lieux... <br>Vous arriverez 
			dans une des mairies de la Comt&eacute; que vous allez choisir.
			<br><br>
			Attention, les Comt&eacute;s PVP (PVP : oui ) indiquent des Comt&eacute;s dans lesquelles
			l'attaque des hobbits entre eux est autoris&eacute;e.<br> Il est donc fortemement d&eacute;conseillé
			d'atterir dans une de ces Comt&eacute;s &agrave; la naissance.
			<br><br>
			
			Choisissez une Comt&eacute; : 
			<select name='id_region' id='id_region'>
				<option value='-1' <? if ($this->id_region == -1) echo "selected" ?>>
					Comt&eacute; Al&eacute;atoire
				</option>
				<? foreach ($this->regions as $k => $v) : ?>
				<option value="<?=$k?>" <? if ($this->id_region == $k) echo "selected" ?>>
					<?=htmlspecialchars($v["nom"])?> - PVP : <?=$v["est_pvp"] ?>
				</option>
				<? endforeach; ?>
			</select><br /><br />
		</div>
		<div id="formbutton">
			<input type="submit" class='button1' name="ajouter" value="Inscription !" /> 
			<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/'"/>
		</div>
		
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

