<?php echo $this->render('header.phtml'); ?>
<div class="titre textalia textsizea">Braldahim - Inscription</div>

<div class="box_inscription">
<div class="inner">
    <div class="titre textalic textsizea">Inscription r&eacute;ussie !</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    <br />
		F&eacute;licitations, votre Braldûn <?= $this->prenom_braldun ?> 
		vient d'&ecirc;tre cr&eacute;&eacute; mais il n'est pas encore valide.<br /><br />
		
		Il ne poss&egrave;de pas encore de nom de famille, un nom lui sera automatiquement
		attribu&eacute; lors de la validation.<br /><br />
		
		Pour le valider, suivez les indications que vous venez de recevoir
		 &agrave; l'adresse suivante : <br />
		<?= $this->email_braldun ?><br /><br />
		
		Consultez vos messages indésirables si vous ne voyez pas le mail arriver... <br /><br />

		Pour tout problème d'inscription, merci de contacter les Thains à l'adresse suivante : 
		thains @ braldahim.com.<br /><br />
		
		En attendant le mail, nous vous conseillons de lire l'article 
		<a onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/Bien_débuter', 'Wiki');" title="Bien d&eacute;buter">
  			Bien débuter.
  		</a>
		<br /><br />
				 
		Courbettes distingu&eacute;es, <br /><br />
		
		Les Thains.<br /><br />
		
		 <input type="button" class='button1' value="Accueil" onclick="javascript:document.location.href='/'"/>

		</div>
	</div>
	&nbsp;
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>