<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<div class="box_inscription">
<div class="box_titre1">Inscription r&eacute;ussie !</div><br />
	F&eacute;licitations, votre hobbit <?= $this->nom_hobbit ?> 
	vient d'&ecirc;tre cr&eacute;&eacute; mais il n'est pas encore valide.<br><br>
	
	Pour le valider, suivez les indications que vous venez de recevoir
	 à l'adresse suivante : <br>
	<?= $this->email_hobbit ?><br><br>
	
	Courbettes distingu&eacute;es, <br><br>
	
	Les Ma&icirc;tres du Jeu.<br><br>
	
	 <input type="button" value="Accueil" onClick="javascript:document.location.href='/'"/>
</div>

<?php echo $this->render('footer.phtml'); ?>