<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<div class="box_inscription">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Inscription r&eacute;ussie !</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
		F&eacute;licitations, votre hobbit <?= $this->nom_hobbit ?> 
		vient d'&ecirc;tre cr&eacute;&eacute; mais il n'est pas encore valide.<br><br>
		
		Pour le valider, suivez les indications que vous venez de recevoir
		 à l'adresse suivante : <br>
		<?= $this->email_hobbit ?><br><br>
		
		Courbettes distingu&eacute;es, <br><br>
		
		Les Ma&icirc;tres du Jeu.<br><br>
		
		 <input type="button" class='button1' value="Accueil" onClick="javascript:document.location.href='/'"/>

		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>

<?php echo $this->render('footer.phtml'); ?>