Bonjour ! 

Vous venez de vous inscrire sur Braldahim.

Prenom du Braldûn : <?php echo $this->prenom_braldun ?> 

Numero du Braldûn : <?php echo $this->id_braldun ?> 

Pour valider votre compte, allez ici : 
<?php echo $this->urlValidation ?> 

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?php echo $this->adresseSupport ?> 

Nous vous conseillons de lire l'article suivant : http://regles.braldahim.com/wiki/Bien_debuter.   

Une quete initiatique vous est directement offerte, consultez l'onglet quete sur l'interface du jeu pour plus d'informations. 

Bon jeu ! 

--
Les Thains (Maitres du jeu)