Bonjour ! <br /><br />
Vous venez de vous inscrire sur Braldahim.<br /><br />
Prenom du braldun : <?=$this->prenom_braldun ?><br />
Numero du Braldun : <?=$this->id_braldun ?><br /><br />
Pour valider votre compte, allez ici : <br />
<a href="<?=$this->urlValidation ?>"><?=$this->urlValidation ?></a><br /><br />

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br /><br />

Nous vous conseillons de lire l'article suivant : <a href="http://regles.braldahim.com/wiki/Bien_debuter">http://regles.braldahim.com/wiki/Bien_debuter</a>.<br /><br />
<br /><br />

Une quete initiatique vous est directement offerte, consultez l'onglet quete sur l'interface du jeu pour plus d'informations. 

Bon jeu ! <br /><br />

--<br />
Les Thains (Maitres du jeu)