Bonjour ! 

Vous venez de vous inscrire sur Braldahim.

Prenom du hobbit : <?=$this->prenom_hobbit ?> 

Numero du Hobbit : <?=$this->id_hobbit ?> 

Pour valider votre compte, allez ici : 
<?=$this->urlValidation ?> 

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?> 

Nous vous conseillons de lire l'article suivant : http://wiki.braldahim.com/wiki/Bien_debuter.   

Une quete initiatique vous est directement offerte, consultez l'onglet quete sur l'interface du jeu pour plus d'informations. 

Bon jeu ! 

--
Les Thains (Maitres du jeu)