Bienvenue en Braldahim !

Ça y est ! Tu viens de nous rejoindre pour incarner un Semi-Homme ! Tu vas bientôt te rendre compte que la vie des Braldûns, habitants de Braldahim, n'est pas de tout repos.

Pour débuter, une quête t'attend dans l'onglet prévu. C'est une quête initiatique qui pourra te permettre d'apprendre un métier et de découvrir le jeu.

Si tu as des questions, tu pourras certainement trouver des réponses sur le wiki ([url]http://regles.braldahim.com[/url]) où toutes les règles sont détaillées.

N'hésite pas à consulter le guide du débutant qui te guidera pour faire tes premiers pas dans le jeu. ([url]http://regles.braldahim.com/wiki/Bien_debuter[/url])

De plus, si tu souhaites faire part de tes impressions / problèmes, ou encore échanger avec les autres joueurs, tu pourras te connecter au forum (n'oublie pas de créer ton compte !). ([url]http://forums.braldahim.com/[/url])

Bon jeu et à bientôt.

Grace Petits-pieds
