<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<div class="box_inscription">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Validation de l'inscription</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />
		<? if ($this->validationOk) : ?>
			F&eacute;licitations ! Votre validation est prise en compte. <br /> <br />
		
			Pour vous connecter, cliquez ici : 
			<input type="button" class='button1' value="Accueil" onClick="javascript:document.location.href='/'"/>
		
		<? elseif ($this->compteActif == true) :?>
			Vous avez d&eacute;j&agrave; valid&eacute; votre compte
		<? else : ?>
			<b>Une erreur est survenu lors de la validation de votre compte.</b><br /><br />
			
			Veuillez contacter le ma&icirc;tre du jeu à l'adresse suivante :
			<?= $this->emailMaitreJeu ?>. <br /><br />
			N'oubliez pas d'indiquer : <br />
			=> votre nom et num&eacute;ro de hobbit<br />
			=> votre adresse de validation<br />
			=> le probl&egrave;me rencontr&eacute; (avec copie d'&eacute;cran si possible).<br />
		<? endif; ?>
		
		<br /><br />
		Courbettes distingu&eacute;es, <br /><br />
		
		Les Ma&icirc;tres du Jeu.<br /><br />
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>