<?php echo $this->render('header.phtml'); ?>
<ul class="titre textalia textsizea">Braldahim - Inscription</ul>

<div class="box_inscription">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Validation de l'inscription</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />
		<? if ($this->validationOk) : ?>
			F&eacute;licitations ! Votre validation est prise en compte. <br /> <br />
		
			Pour vous connecter, cliquez ici : 
			<input type="button" class='button1' value="Accueil" onClick="javascript:document.location.href='/'"/>
			
			<br><br>
			Ah, un dernier mot avant de vous laisser filer, voici un message qui vous est attribué :
			<br><br>
		
		<? elseif ($this->compteActif == true) :?>
			Vous avez d&eacute;j&agrave; valid&eacute; votre compte.
			<br><br>
			Voici un message que vous avez peut-&ecirc;tre d&eacute;j&agrave; lu :
			<br><br>
		<? else : ?>
			<b>Une erreur est survenue lors de la validation de votre compte.</b><br /><br />
			
			Veuillez contacter les ma&icirc;tres du jeu &agrave; l'adresse suivante :
			<?= $this->emailMaitreJeu ?>. <br /><br />
			N'oubliez pas d'indiquer : <br />
			=> votre nom et num&eacute;ro de hobbit<br />
			=> votre adresse de validation<br />
			=> le probl&egrave;me rencontr&eacute; (avec copie d'&eacute;cran si possible).<br />
		<? endif; ?>
		
		<? if ($this->validationOk || $this->compteActif == true) : ?>
		<table width='40%' align='center'>
 			<tr><td style='text-align:justify; background-color:#CCCC99'>
			Message des Thains : <br>
			Objet : Bienvenue en Braldahim !<br><br>

			Contenu : Ça y est ! Tu viens de nous rejoindre pour incarner un hobbit ! Tu vas bientôt te rendre compte que la vie de hobbit n'est pas de tout repos.
			<br><br>
			Pour débuter, une quête t'attend dans l'onglet prévu. C'est une quête initiatique qui pourra te permettre d'apprendre un métier et de découvrir le jeu.
			<br><br>
			Si tu as des questions, tu pourras certainement trouver des réponses sur le wiki (<a onClick="javascript:ouvrirWin('http://wiki.braldahim.com', 'Wiki');" title="Bien d&eacute;buter">http://wiki.braldahim.com</a>) où toutes les règles sont détaillées.
			<br><br>
			N'hésite pas à consulter le guide du débutant qui te guidera pour faire tes premiers pas dans le jeu. (<a onClick="javascript:ouvrirWin('http://wiki.braldahim.com/wiki/Bien_debuter', 'Bien debuter');" title="Bien d&eacute;buter">http://wiki.braldahim.com/wiki/Bien_débuter</a>)
			<br><br>
			Si tu as des questions, si tu souhaites échanger avec les autres joueurs, tu pourras te connecter au forum (n'oublie pas de créer ton compte !). (<a onClick="javascript:ouvrirWin('http://forums.braldahim.com/', 'Forum');" title="Forums Braldahim">http://forums.braldahim.com</a>)
			<br><br>
			Pour consulter ce message à nouveau, reviens sur cette adresse de validation (que tu as eu par mail).
			<br><br>
			Bon jeu et à bientôt.
			<br><br>
			Les Thains.
			<br><br>
			</td></tr>
 			</table>
		<? endif;?>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>