<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<div class="box_inscription">
<div class="box_titre1">Validation de l'inscription</div><br />
	<? if ($this->validationOk) : ?>
		F&eacute;licitation ! Votre validation est prise en compte. <br> <br>
	
		Pour vous connecter, cliquer ici : 
		<input type="button" class='button1' value="Accueil" onClick="javascript:document.location.href='/'"/>

	<? else : ?>
		<b>Une erreur est survenu lors de la validation de votre compte.</b><br><br>
		
		Veuillez contacter le maitre du jeu à l'adresse suivante :
		<?= $this->emailMaitreJeu ?>. <br><br>
		N'oubliez pas d'indiquer : <br>
		=> votre nom et num&eacute;ro de hobbit<br>
		=> votre adresse de validation<br>
		=> le probl&egrave;me rencontr&eacute;.<br>
	<? endif; ?>
	
	<br><br>
	Courbettes distingu&eacute;es, <br><br>
	
	Les Ma&icirc;tres du Jeu.<br><br>
</div>
<?php echo $this->render('footer.phtml'); ?>