<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Batchs</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    Purge des batchs OK tous les <?php echo Bral_Batchs_Batch::PURGE_NB_JOUR_OK ?> jours glissants.<br />
	    Purge des batchs tous statuts tous les <?php echo Bral_Batchs_Batch::PURGE_NB_JOUR_TOUS?> jours glissants.<br />
	    
	    Nombre OK : <?php echo $this->nbOk?>
	    <br />
	    Nombre KO : <?php echo $this->nbKo?>
	    <br />
	    Nombre En Cours : <?php echo $this->nbEnCours?>
	    <br />
	    Total : <?php echo $this->nbTotal?>
	    <br /><br />
	    Nombre OK 3 derniers jours (du <?php echo $this->dateDebut ?> au <?php echo $this->dateFin?> ) : <?php echo $this->nbOk3jours?> 
	    <br />
	    Nombre KO 3 derniers jours (du <?php echo $this->dateDebut ?> au <?php echo $this->dateFin?> ) : <?php echo $this->nbKo3jours?> 
	    <br />
	      
		<br /><br />
			<table  align='center'>
				<tr>
				<?php foreach ($this->batchs as $h) : ?>
					<?php foreach ($h as $key => $value) : ?>
					<th class='comp_titre'><?php echo $key?></th>
					<?php endforeach; ?>
				<?php break;endforeach; ?>
			
				<?php foreach ($this->batchs as $b) : ?>
				<?php if ($b["etat_batch"] == "OK") :
					$color= "#66CC66";
				   elseif ($b["etat_batch"] == "EN_COURS") :
				   	$color = "#FF9900";
				   else:
				   	$color = "#FF3333";
				   endif;
				?>
				</tr>
				<tr style="background-color:<?php echo $color?>">
					<?php foreach ($b as $key => $value) : ?>
						<td>
						<?php if ($key == "message_batch") : ?>
							<textarea class="inputbox" rows="1" cols="100"><?php echo $value ?></textarea>
						<?php else: ?>
							<?php echo $value ?>
						<?php endif;?>
						</td>
					<?php endforeach; ?>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>