<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Batchs</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    Purge des batchs OK tous les <?=$this->config->batchs->purge->table->batch->nbjours->ok?> jours glissants.<br />
	    Purge des batchs tous statuts tous les <?=$this->config->batchs->purge->table->batch->nbjours->tous?> jours glissants.<br />
	    
	    Nombre OK : <?=$this->nbOk?>
	    <br />
	    Nombre KO : <?=$this->nbKo?>
	    <br />
	    Nombre En Cours : <?=$this->nbEnCours?>
	    <br />
	    Total : <?=$this->nbTotal?>
	    <br /><br />
	    Nombre OK 3 derniers jours (du <?=$this->dateDebut ?> au <?=$this->dateFin?> ) : <?=$this->nbOk3jours?> 
	    <br />
	    Nombre KO 3 derniers jours (du <?=$this->dateDebut ?> au <?=$this->dateFin?> ) : <?=$this->nbKo3jours?> 
	    <br />
	      
		<br /><br />
			<table  align='center'>
				<? foreach ($this->batchs as $h) : ?>
					<? foreach ($h as $key => $value) : ?>
					<th class='comp_titre'><?=$key?></th>
					<? endforeach; ?>
				<? break;endforeach; ?>
			
				<? foreach ($this->batchs as $b) : ?>
				<? if ($b["etat_batch"] == "OK") :
					$color= "#66CC66";
				   elseif ($b["etat_batch"] == "EN_COURS") :
				   	$color = "#FF9900";
				   else:
				   	$color = "#FF3333";
				   endif;
				?>
				<tr style="background-color:<?=$color?>">
					<? foreach ($b as $key => $value) : ?>
						<td>
						<? if ($key == "message_batch") : ?>
							<textarea class="inputbox" rows="1" cols="100"><?=$value ?></textarea>
						<? else: ?>
							<?=$value ?>
						<? endif;?>
						</td>
					<? endforeach; ?>
				</tr>
				<? endforeach; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>