<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Administration Logs</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	  		 <form action="/Administrationbatch/logs" method="post">
				Recherche
				<input type="textbox" name="recherche" value="<?=$this->recherche?>" onkeypress="chiffres(event);" size="10" maxlength="10" />
				
				<select name="fichier">
				<? foreach ($this->fichiers as $f) : ?>
				<option value="<?=$f?>" <? if ($this->fichierChoisi == $f): echo "selected" ; endif;?>><?=$f?></option>
				<? endforeach; ?>
				</select>
				
				<input type="submit" class="button1" name="Rechercher" value="Rechercher" />
				
				<pre>
				<?php 
					if ($this->cmd != "") :
						passthru($this->cmd);
					endif;
				?>
				</pre>
			</form>
	   <?=$this->retour?>
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>