<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Logs</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalia">
	  		 <form action="/Administrationbatch/logs" method="post">
	  		 	
	  		 	Commande <select name="commande">
				<?php foreach ($this->commandes as $f) : ?>
				<option value="<?php echo $f?>" <?php if ($this->commandeChoisie == $f): echo "selected" ; endif;?>><?php echo $f?></option>
				<?php endforeach; ?>
				</select>
				<br />
				Argument : Chiffres exclusivement: Recherche, chaine à recherche, Tail : nombre de ligne<br /> 
				<input type="text" name="recherche" value="<?php echo $this->recherche?>" onkeypress="chiffres(event);" size="10" maxlength="10" />
				<br />
				
				Fichier :
				<select name="fichier">
				<?php foreach ($this->fichiers as $f) : ?>
				<option value="<?php echo $f?>" <?php if ($this->fichierChoisi == $f): echo "selected" ; endif;?>><?php echo $f?></option>
				<?php endforeach; ?>
				</select>
				<input type="submit" class="button1" name="Rechercher" value="Rechercher" />
			</form>
				<pre>
				<?php 
					if ($this->cmd != "") :
						echo "Commande exécutée : ".$this->cmd.PHP_EOL.PHP_EOL;
						passthru($this->cmd);
					endif;
				?>
				</pre>
			
	   <?php echo $this->retour?>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>