<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Gestion</ul>
    	&nbsp;
	<div class="contenu">
	  <ul class="box_contenu1 textalic">
	  
	  	<? if ($this->user->administrateur == true || in_array(Bral_Util_Securite::ROLE_AUTEUR_LIEU, $this->roles)) : ?>
	    <span class="titre textalia textsizec">Description Lieu (Role Auteur)</span>
	    <br />
	    Lieux : 
	 	<select name='administration_lieu' id="administration_lieu" onChange='document.location.href="/Administrationlieu/lieu/mode/simple/idlieu/"+this.value;'>
	 	<option value="-1" selected>Choisissez un lieu</option>
	 	<? foreach ($this->administrationLieux as $l) : ?>
			<option value="<?=$l["id_lieu"]?>"><?=$l["id_lieu"]?> : <?=$l["nom_lieu"]?> (<?=$l["x_lieu"]?>,<?=$l["y_lieu"]?>)</option>
		<? endforeach; ?>
		</select>
	    <br />
	    <? endif;?>
	    <br />
	    
	   	<? if ($this->user->administrateur == true || in_array(Bral_Util_Securite::ROLE_BETA_TESTEUR, $this->roles)) : ?>
	      <span class="titre textalia textsizec">Gestion de son Hobbit (Role Testeur)</span>
		<br>
	    Hobbit Id <?=$this->user->id_hobbit?> <input type='hidden' name='id_hobbit' id='id_hobbit' value='<?=$this->user->id_hobbit?>' size='5'> 
	    <input type='button' name='goFiche' value='Ouvrir Fiche' class='button1'  onClick='document.location.href="/Administrationhobbit/hobbit/mode/simple/idhobbit/"+$("id_hobbit").value;'> 
	   
	    <? endif;?>
	    
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>