<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titrea textalic titreasize0">Gestion</div>
    	&nbsp;
	<div class="contenu">
	  <div class="box_contenu1 textalic">
	  
	  	<?php if ($this->user->administrateur == true || in_array(Bral_Util_Securite::ROLE_AUTEUR_LIEU, $this->roles)) : ?>
	    <span class="titre textalia textsizec">Description Lieu (Rôle Auteur Lieu)</span>
	    <br />
	    Lieux (Hors ruine) : 
	 	<select name='administration_lieu' id="administration_lieu" onchange='document.location.href="/Administrationlieu/lieu/mode/simple/idlieu/"+this.value;'>
	 	<option value="-1" selected>Choisissez un lieu</option>
	 	<?php foreach ($this->administrationLieux as $l) : ?>
			<option value="<?php echo $l["id_lieu"]?>"><?php echo $l["id_lieu"]?> : <?php echo $l["nom_lieu"]?> (<?php echo $l["x_lieu"]?>,<?php echo $l["y_lieu"]?>)</option>
		<?php endforeach; ?>
		</select>
		<?php echo (count($this->administrationLieux));?> lieux.
		
		<br />
	    Lieux (Sans description) : 
	 	<select name='administration_lieu' id="administration_lieu" onchange='document.location.href="/Administrationlieu/lieu/mode/simple/idlieu/"+this.value;'>
	 	<option value="-1" selected>Choisissez un lieu</option>
	 	<?php foreach ($this->administrationSansDescriptionLieux as $l) : ?>
			<option value="<?php echo $l["id_lieu"]?>"><?php echo $l["id_lieu"]?> : <?php echo $l["nom_lieu"]?> (<?php echo $l["x_lieu"]?>,<?php echo $l["y_lieu"]?>)</option>
		<?php endforeach; ?>
		</select>
	    <?php echo (count($this->administrationSansDescriptionLieux));?> lieux.
	    
	    <br />
	    Lieux (Avec description) : 
	 	<select name='administration_lieu' id="administration_lieu" onchange='document.location.href="/Administrationlieu/lieu/mode/simple/idlieu/"+this.value;'>
	 	<option value="-1" selected>Choisissez un lieu</option>
	 	<?php foreach ($this->administrationAvecDescriptionLieux as $l) : ?>
			<option value="<?php echo $l["id_lieu"]?>"><?php echo $l["id_lieu"]?> : <?php echo $l["nom_lieu"]?> (<?php echo $l["x_lieu"]?>,<?php echo $l["y_lieu"]?>)</option>
		<?php endforeach; ?>
		</select>
	    <?php echo (count($this->administrationAvecDescriptionLieux));?> lieux.
	    
	    <br />
	    Lieux (Tous) : 
	 	<select name='administration_lieu' id="administration_lieu" onchange='document.location.href="/Administrationlieu/lieu/mode/simple/idlieu/"+this.value;'>
	 	<option value="-1" selected>Choisissez un lieu</option>
	 	<?php foreach ($this->administrationTousLieux as $l) : ?>
			<option value="<?php echo $l["id_lieu"]?>"><?php echo $l["id_lieu"]?> : <?php echo $l["nom_lieu"]?> (<?php echo $l["x_lieu"]?>,<?php echo $l["y_lieu"]?>)</option>
		<?php endforeach; ?>
		</select>
		<?php echo (count($this->administrationTousLieux));?> lieux.
	    <br /><br /><br />
	    <?php endif;?>
	    <br />
	    
	    <?php if ($this->user->administrateur == true || in_array(Bral_Util_Securite::ROLE_AUTEUR_BOUGRIE, $this->roles)) : ?>
	    <span class="titre textalia textsizec">Description Lieu (Rôle Auteur Bougrie)</span>
	    <br />
	    Bougries : 
	 	<select name='administration_bougrie' id="administration_bougrie" onchange='document.location.href="/Administrationbougrie/bougrie/id_bougrie/"+this.value;'>
	 	<option value="-1" selected>Choisissez une bougrie</option>
	 	<?php foreach ($this->administrationBougries as $b) : ?>
			<option value="<?php echo $b["id_bougrie"]?>"><?php echo $b["id_bougrie"]?></option>
		<?php endforeach; ?>
		</select>
	    <br /><br /><br />
	    <?php endif;?>
	    <br />
	    
	   	<?php if ($this->user->administrateur == true || in_array(Bral_Util_Securite::ROLE_BETA_TESTEUR, $this->roles)) : ?>
	      <span class="titre textalia textsizec">Gestion de son Braldûn (Rôle Testeur)</span>
		<br />
	    Braldûn Id <?php echo $this->user->id_braldun?> <input type='hidden' name='id_braldun' id='id_braldun' value='<?php echo $this->user->id_braldun?>' size='5'> 
	    <input type='button' name='goFiche' value='Ouvrir Fiche' class='button1'  onclick='document.location.href="/Administrationbraldun/braldun/mode/simple/idbraldun/"+$("id_braldun").value;'> 
	   
	    <?php endif;?>
	    
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>