<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Gestion</ul>
    	&nbsp;
	<div class="contenu">
	  <ul class="box_contenu1 textalic">
	  
	  	<? if (in_array(Bral_Util_Securite::ROLE_AUTEUR_LIEU, $this->roles)) : ?>
	    <span class="titre textalia textsizec">Description Lieu (Role Auteur)</span>
	    <br />
	    <br />
	    <br />
	    <? endif;?>
	    
	    
	   	<? if (in_array(Bral_Util_Securite::ROLE_BETA_TESTEUR, $this->roles)) : ?>
	      <span class="titre textalia textsizec">Gestion de son Hobbit (Role Testeur)</span>
	    <br />
		<br>
	    Hobbit Id <?=$this->user->id_hobbit?> <input type='hidden' name='id_hobbit' id='id_hobbit' value='<?=$this->user->id_hobbit?>' size='5'> 
	    <input type='button' name='goFiche' value='Ouvrir Fiche' class='button1'  onClick='document.location.href="/Administrationhobbit/hobbit/mode/simple/idhobbit/"+$("id_hobbit").value;'> 
	   
	    <? endif;?>
	    
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>