  <br />
  <div class="titre textalic textsized">Contrats</div>
  <br /> 
  <br /> 
  Pour obtenir un contrat de Gredin, allez à Fichetrousse dans la maison de contrat.<br />
  Pour obtenir un contrat de Redresseur de Torts, allez à Sarlute dans la maison de contrat.<br />
  <br />
  <br />
  <? if ($this->contrats == null) : ?>
  	Vous n'avez aucun contrat.<br />
  <? else: ?>
  
    <? if ($this->idContratEnCours != null) : ?>
	  <input type='button' class='button1' value='Annuler le contrat en cours - 0 PA' onclick="_get_('/contrat/doaction?caction=ask_contrat_annuler&id_contrat=<?=$this->idContratEnCours?>');">
	  <br /><br />
  	<? endif;?>
  
 	<table width="100%">
 		<tr>
 			<td width="40%" valign="top">
 				<table class="table_liste" style="width:90%">
					<thead class="table_liste">
					  <tr class="table_liste">
						<th colspan="2"> Contrats r&eacute;alis&eacute;s ou en cours<br /></th>
					  </tr>
					</thead>
					
					<tbody>
					 <? foreach($this->contrats as $c) :
					 	$i = 0; 
					 	?>
				  		<tr class="table_liste<?=($i % 2);$i++; ?>" title="Cliquer pour voir le détail" style="cursor:pointer" onclick="Javascript:_get_('/contrat/doaction?caction=ask_contrat_voir&id_contrat=<?=$c["id_contrat"]?>');">
				  		<td class="table_liste">
				  			<?=$c["cible"]?>
				  		</td>
						<td class="table_liste" nowrap>
						  	<? if ($c["etat_contrat"] == "terminé"): ?>
						  		Terminé le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$c["date_fin_contrat"]);?>
						  	<? elseif ($c["etat_contrat"] == "annulé"): ?>
						  		Annulé le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$c["date_fin_contrat"]);?>
						  	<? else: ?>
						  		En Cours, depuis le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$c["date_creation_contrat"]);?>
						  	<? endif;?>
						 </td>
					  	 </tr>
					  <? endforeach;?>
					</tbody>
				</table>
 			</td>
 			<td width="60%" valign="top">
 				<div id="box_contrat_voir">
				<?=$this->htmlContrat?>
				</div>
 			</td>
 		</tr>
 	</table>
 <? endif;?>
 	