<ul class="titre textalic textsizec">Le champ</ul><br />

<br />

<div class="box_contenu1 textalic">
	<table class='vue2d' align='center'>
	<?php 
	$col="";
	echo "<tr><td>&nbsp;</td>";
	foreach($this->tableau as $k => $case) :
     
		if ($case["change_level"] == 1 && $col == "ok") :
			break;
		endif;
		echo "<td>".$case["x"]."</td>";
		if ($case["change_level"] == true) : 
			$col="ok";
		endif;
	endforeach;
	echo "</tr>";
	 
$col="";
foreach($this->tableau as $k => $case) :
	?>
	<?php if ($case["change_level"] == true) : 
		$col="ok"; ?>
		<tr nowrap><td><?=$case["y"]?></td>
    <?php endif; ?>
	<td class='champ2d <?=$case["css_champ"]?>' nowrap title="<?=$case["x"]. "," . $case["y"]?>">
	<? if ($case["taupe"] != null) : ?>
		<img src='/public/styles/braldahim_defaut/images/champ/<?=$case["taupe"]["etat_champ_taupe"]?>.png'>
	<? else: ?>
		
	<? endif;?>
	</td>
<? endforeach; ?>
</tr>
</table>
&nbsp;
</div>