<?php if ($this->champ["phase_champ"] == "seme") : ?>
	Le champ est semé depuis le 
	<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_seme_champ"]);?>, 
	il peut être entretenu pour avoir une meilleure récolte.
	<br /><br />
	La récolte pourra s'effectuer à partir du 
	<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_fin_seme_champ"]);?> pendant 5 jours. 
	<br />
	Estimation de la récolte : <?php echo $this->champ["quantite_champ"]?>.
	<br /><br />
	
	<?php if ($this->possedeEntretenir === true) : ?>
		Cliquez sur une case pour l'entretenir.
	<?php elseif ($this->possedeChamp == true) : ?>
		Vous ne possédez pas la compétence Entretenir pour entretenir ce champ !
	<?php endif;?>
<?php elseif ($this->champ["phase_champ"] == "a_recolter") : ?>
	Le champ peut être récolté ! 
	Dépêchez-vous, s'il n'est pas récolté avant le
	<?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_fin_recolte_champ"]);?>,
	il passera en jachère.<br />
	Estimation de la récolte : <?php echo $this->champ["quantite_champ"]?>.
<?php else : ?>
	Le champ est actuellement en jachère. Si vous avez assez de graines, vous pouvez en semer.
<?php endif; ?>
<br /><br />

<div class="box_contenu1 textalic">

<table class='' align='center'>
<tr>
	<td valign='top'>
	
	<table class='champ2d' align='center'>
	<?php 
	$col="";
	echo "<tr><td>&nbsp;</td>";
	foreach($this->tableau as $k => $case) :
     
		if ($case["change_level"] == 1 && $col == "ok") :
			break;
		endif;
		echo "<td>".$case["x"]."</td>";
		if ($case["change_level"] == true) : 
			$col="ok";
		endif;
	endforeach;
	echo "</tr>";
	 
$col="";
foreach($this->tableau as $k => $case) :
	?>
	<?php if ($case["change_level"] == true) : 
		$col="ok"; ?>
		<tr><td><?php echo $case["y"]?></td>
    <?php endif; ?>
	<td class='champ2d <?php echo $case["css_champ"]?>' nowrap
		<?php if ($this->champ["phase_champ"] == "seme" && $case["taupe"] == null) : ?>
			<?php if ($this->possedeEntretenir) : ?>
				onclick="Javascript:_get_('/competences/doaction?caction=ask_competence_entretenir&position=<?php echo $case["x"]. "-".$case["y"]?>')" style="cursor:pointer;" title='<?php echo $case["x"]. "," . $case["y"]?> : Cliquez pour entretenir'
			<?php else:?>
				title='Vous ne possédez pas la compétence Entretenir !' style="cursor:pointer;" 
			<?php endif;?>
		<?php else: ?>
			title="<?php echo $case["x"]. "," . $case["y"]?>"
		<?php endif;?>
	>
	<?php if ($case["taupe"] != null) : ?>
		<?php include("taupe.phtml"); ?>
	<?php endif;?>
	</td>
<?php endforeach; ?>
</tr>
</table>

</td>
<td valign='top'>

<?php if ($this->champ["phase_champ"] != "jachere") : ?>

<div class="titre textalic textsized">
Culture
</div>
<?php echo $this->champ["nom_type_graine"]; ?>
<br /><br />

<div class="titre textalic textsized">
Taupes vivantes : 
</div>
<?php if (count($this->taupesVivantes) > 0): ?>
	<?php foreach($this->taupesVivantes as $numero => $details) : ?>
		Taupe n°<?php echo $numero?> de taille <?php echo $details["taille"]?>, 
		parties vivantes : <?php echo count($this->taupesVivantes[$numero]["morceaux"])?> / <?php echo count($this->toutes[$numero])?>
		<br />
	<?php endforeach;?>
<?php else: ?>
	Il ne reste plus de taupe vivante.
<?php endif;?>
<br /><br />

<div class="titre textalic textsized">
Taupes occises : <br /> 
</div>

<?php if (count($this->taupesDetruites) > 0): ?>
	<?php foreach($this->taupesDetruites as $numero => $details) : ?>
		Taupe n°<?php echo $numero?> de taille <?php echo $details["taille"]?>,  
		parties détruites : <?php echo count($this->toutes[$numero])?> / <?php echo count($this->toutes[$numero])?>
		<br />
	<?php endforeach;?>
<?php else: ?>
	Aucune taupe n'est occise.
<?php endif;?>

<?php endif;?>

</td>
</tr>
</table>


<br /><br />
Légende : 

<table class='champ' align='center'>
<tr>
	<td class='champ2d jachere'>
	&nbsp;
	</td><td>
		Champ en jachère.
	</td>
</tr>
<tr>
	<td class='champ2d a_recolter'>
	&nbsp;
	</td><td>
		Champ à récolter.
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
	&nbsp;
	</td><td>
		Champ semé.
	</td>
</tr>
<tr>
	<td class='champ2d a_recolter'>
	<img src='<?php echo $this->config->static->url?>/images/champ/vivant.png'>
	</td><td>
		Taupe vivante (visible quand le champ est à récolter).
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
		<img src='<?php echo $this->config->static->url?>/images/champ/detruit.png'>
	</td><td>
		Zone entretenue, taupe détruite.
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
		<img src='<?php echo $this->config->static->url?>/images/champ/entretenu.png'>
	</td><td>
		Zone entretenue, aucune taupe.
	</td>
</tr>

</table>

</div>