<? if ($this->champ["phase_champ"] == "seme") : ?>
	Le champ est semé depuis le 
	<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_seme_champ"]);?>, 
	vous pouvez l'entretenir pour avoir une meilleure récolte.
	<br><br>
	Vous pourrez le récolter à partir du 
	<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_fin_seme_champ"]);?> pendant 5 jours. 
	<br>
	Estimation de la récolte : <?=$this->champ["quantite_champ"]?>.
	<br><br>
	
	<? if ($this->possedeEntretenir == false) : ?>
		Cliquez sur une case pour l'entretenir.
	<? else: ?>
		Vous ne possédez pas la compétence Entretenir pour entretenir votre champ !
	<? endif;?>
<? elseif ($this->champ["phase_champ"] == "a_recolter") : ?>
	Le champ peut-être récolté ! 
	Dépêchez-vous, s'il n'est pas récolté avant le
	<?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->champ["date_fin_recolte_champ"]);?>,
	il passera en jachère. 
<? else : ?>
	Le champ est actuellement en jachère. Si vous avez assez de graines, vous pouvez en semer.
<? endif; ?>
<br /><br />

<div class="box_contenu1 textalic">
	<table class='champ2d' align='center'>
	<?php 
	$col="";
	echo "<tr><td>&nbsp;</td>";
	foreach($this->tableau as $k => $case) :
     
		if ($case["change_level"] == 1 && $col == "ok") :
			break;
		endif;
		echo "<td>".$case["x"]."</td>";
		if ($case["change_level"] == true) : 
			$col="ok";
		endif;
	endforeach;
	echo "</tr>";
	 
$col="";
foreach($this->tableau as $k => $case) :
	?>
	<?php if ($case["change_level"] == true) : 
		$col="ok"; ?>
		<tr nowrap><td><?=$case["y"]?></td>
    <?php endif; ?>
	<td class='champ2d <?=$case["css_champ"]?>' nowrap
		<? if ($case["taupe"] == null && $this->possedeEntretenir) : ?>
			onClick="Javascript:_get_('/competences/doaction?caction=ask_competence_entretenir&position=<?=$case["x"]. "-".$case["y"]?>')" style="cursor:pointer;" title='<?=$case["x"]. "," . $case["y"]?> : Cliquez pour entretenir'
		<? else: ?>
			title="<?=$case["x"]. "," . $case["y"]?>"
		<? endif;?>
	>
	<? if ($case["taupe"] != null) : ?>
		<? include("taupe.phtml"); ?>
	<? endif;?>
	</td>
<? endforeach; ?>
</tr>
</table>

<br><br>
Légende : 

<table class='champ' align='center'>
<tr>
	<td class='champ2d jachere'>
	&nbsp;
	</td><td>
		Champ en jachère.
	</td>
</tr>
<tr>
	<td class='champ2d a_recolter'>
	&nbsp;
	</td><td>
		Champ à récolter.
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
	&nbsp;
	</td><td>
		Champ semé.
	</td>
</tr>
<tr>
	<td class='champ2d a_recolter'>
	<img src='/public/styles/braldahim_defaut/images/champ/vivant.png'>
	</td><td>
		Taupe vivante (visible quand le champ est à récolter).
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
		<img src='/public/styles/braldahim_defaut/images/champ/detruit.png'>
	</td><td>
		Zone entretenue, taupe détruite.
	</td>
</tr>
<tr>
	<td class='champ2d seme'>
		<img src='/public/styles/braldahim_defaut/images/champ/entretenu.png'>
	</td><td>
		Zone entretenue, aucune taupe.
	</td>
</tr>

</table>

</div>