<div id="menu">
	<ul>
		<li class="accueil"><a href="http://www.braldahim.com">Accueil</a></li>
		<li class="jouer"><a href="http://jeu.braldahim.com/auth/login">Jouer</a></li>
		<li class="bourg"><a href="http://www.braldahim.com/bourg">Palmarès</a></li>
		<li class="forums"><a href="http://forum.braldahim.com">Forum</a></li>
		<li class="regles"><a href="http://regles.braldahim.com">Règles</a></li>
		<li class="projet"><a href="http://www.braldahim.com/projet">Le Projet</a></li>
	</ul>
</div>
