<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Pragma" content="no-cache" />
	<title>Braldahim - Scripts Publics</title>
	<meta name="description" content="Braldahim - Jeu Web - Bralduns" />
	<meta name="keywords" content="jeu web, Semi-Homme, Braldûns, MMO, rôle, aventure" />
	<link href="<?php echo $this->config->static->url?>/styles/braldahim-sp-012.css" media="screen" rel="Stylesheet" type="text/css" />
	<link href="<?php echo $this->config->static->url?>/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="alternate" type="application/rss+xml" title="Braldahim - Chronique" href="http://feeds.braldahim.com/braldahim-chronique" />
	
	<script type="text/javascript" src="<?php echo $this->config->static->url?>/scripts/braldahim/m_display-sp-001.js"></script>
	<script type="text/javascript" src="<?php echo $this->config->static->url?>/scripts/prototype_1602/prototype.js"></script>
</head>

<body>
	<div id="header">
<div id="frisetop">
<h1><a href="/">Braldahim - Jeu</a></h1>
</div>
</div>
	<div id="page">
		<?php echo $this->render("menu.phtml"); ?>
		<div id="wrapper">
		<div class="contenu">
			<br /><br />
			<?php echo  $this->layout()->contenu ?>
			<br /><br />
		</div>
		</div>
		<?php echo $this->render("footer.phtml"); ?>
	</div>
</body>
</html>