<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Pragma" content="no-cache" />
	<title>Braldahim - Scripts Publics</title>
	<meta name="description" content="Braldahim - Jeu Web - Bralduns" />
	<meta name="keywords" content="jeu web, Semi-Homme, Braldûns, MMO, rôle, aventure" />
	<link href="<?php echo $this->config->url->static?>/css/braldahim.css?2" media="screen" rel="Stylesheet" type="text/css" />
	<link href="<?php echo $this->config->url->static?>/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="alternate" type="application/rss+xml" title="Braldahim - Chronique" href="http://feeds.braldahim.com/braldahim-chronique" />
	
	<script type="text/javascript" src="<?php echo $this->config->url->static?>/js/jquery-1.6.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->config->url->static?>/js/braldahim.js?1"></script>
	
	<style type="text/css">
	@font-face {
	    font-family: "Cardinal";
	    font-style: normal;
	    font-weight: normal;
	    src: local("☺"), url("/fonts/Cardinal.ttf") format("truetype");
	}
	</style>

</head>

<body>
	<div id="box_warning" class="box_warning" style="display: none"></div>

	<div id="header">
		<div id="frisetop">
			<h1>&nbsp;</h1>
		</div>
		<div id="frisetop">
			<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>
		</div>
		<div id="frisebot">
		</div>
	</div>
	<div id="page">
		<div id="wrapper">
		<div class="contenu">
			<br />
			<?php echo  $this->layout()->contenu ?>
			<br /><br />
		</div>
		</div>
		<script language="Javascript" src="<?php echo $this->config->url->static?>/index/footer"></script>
		<?php echo $this->render("footer.phtml"); ?>
	</div>
</body>
</html>