
<input type="button" class='button1' value="Rentrer dans l'&eacute;choppe" onclick='_get_("/interface/load/?box=box_echoppe");'>
<br /><br />
<div class="titre textalic textsizeb"><?php echo htmlspecialchars($this->nomEchoppe) ?></div>

<br />
[Toutes les informations présentées en dessous sont renseignées par le joueur et ne sont donc pas officielles]

<div style="text-align:left;padding:30px">
	<?php echo Bral_Util_BBParser::bbcodeReplace($this->commentaireEchoppe); ?><br /><br />
</div>


