<?php Zend_Loader::loadClass('Bral_Util_Communaute');?>

Vous vous trouvez sur un Hall de Communauté.
<br /><br />

<div class="titre textalic textsizeb">Communaut&eacute; : <?php echo $this->nomCommunauteLieu ?>, 
	n&deg; <?php echo $this->idCommunauteLieu ?>
 </div>
 
<div class="titre textalic textsizec">Les réservations et mise en vente</div>
<br />

<?php 
$this->estElementsEtalAchat = true;
$this->pocheNomSysteme = "ReservationsVenteCommunaute";
?>
<?php echo $this->render("/interface/commun/lots.phtml"); ?>
<hr />
  
 <br /><br />
<div class="titre textalic textsizeb">Profil Non Officiel</div>
<div class="titre textalic textsizec">Renseign&eacute; par le gestionnaire de la communaut&eacute;</div>
<table width='80%' align='center'>
	<tr><td style='text-align:justify'><?php echo Bral_Util_BBParser::bbcodeReplace($this->descriptionCommunauteLieu); ?>
		</td></tr>
 	</table>
