<?php Zend_Loader::loadClass('Bral_Util_Communaute');?>

Vous vous trouvez sur un Hall de Communauté.
<br /><br />
	<div class="titre textalic textsizeb">Communaut&eacute; : <?php echo $this->nomCommunauteLieu ?>, 
			n&deg; <?php echo $this->idCommunauteLieu ?>
	 </div>
	 
	 <?php if ($this->user->rangCommunaute <= Bral_Util_Communaute::ID_RANG_TENANCIER) : ?>
	 Vous avez les droits de Tenancier. Depuis ce hall, vous pouvez construire
	 des bâtiments de communautés ou augmenter le niveau d'un bâtiment existant.<br />
	 Les ressources nécessaires doivent être présentes dans le coffre de la communauté.<br />
	 
	 <input type='button' class='button1' value='1 PA - Initialiser un nouveau bâtiment' onclick='_get_("/communaute/doaction?caction=ask_communaute_initialiserbatiment");'>
	 <input type='button' class='button1' value='1 PA - Améliorer un bâtiment' onclick='_get_("/communaute/doaction?caction=ask_communaute_ameliorerbatiment");'>
	 <br />
	 <hr />
	 <?php endif; ?>
	 
	 <br /><br />
	<div class="titre textalic textsizeb">Profil Non Officiel</div>
	<div class="titre textalic textsizec">Renseign&eacute; par le gestionnaire de la communaut&eacute;</div>
	<table width='80%' align='center'>
		<tr><td style='text-align:justify'><?php echo Bral_Util_BBParser::bbcodeReplace($this->descriptionCommunauteLieu); ?>
		</td></tr>
 	</table>
