<? if ($this->vendreOk === true) : ?>
	Choississez un aliment (ou plusieurs en appuyant sur ctrl) &agrave; vendre :<br />
	<select multiple size="5" name="valeur_3" id="valeur_3" onChange="<?=$jsBtn?>">
		 <? foreach($this->aliments as $a) :?>
		 	<option value="<?=$a["id_aliment"]?>"><?=$a["nom"] ?> de qualit&eacute; <?=$a["qualite"] ?> (n&deg;<?=$a["id_aliment"] ?>), +<?=$a["bbdf"]?> %</option>
		 <? endforeach; ?>
	</select>
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
<? endif; ?>