<?php if ($this->vendreOk === true) : ?>
	Choississez un aliment (ou plusieurs en appuyant sur ctrl) &agrave; vendre :<br />
	<select multiple size="5" name="valeur_3" id="valeur_3" onchange="if (this.value > 0 && $('valeur_5').value > 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
		 <?php foreach($this->aliments as $a) :?>
		 	<option value="<?php echo $a["id_aliment"]?>"><?php echo $a["nom"] ?> 
		 		<?php if ($a["bbdf"] > 0): ?>
			 		de qualit&eacute; <?php echo $a["qualite"] ?> 
			 	<?php endif;?> 
			 	(n&deg;<?php echo $a["id_aliment"] ?>),<?php if ($a["bbdf"] > 0): ?> +<?php echo $a["bbdf"]?> %<?php endif;?>
		 	</option>
		 <?php endforeach; ?>
	</select>
	<input type='hidden' name='valeur_4' id='valeur_4' value='1' />
<?php endif; ?>