<? if ($this->vendreOk === true) : ?>
 	Choississez un &eacute;l&eacute;ment &agrave; vendre :<br />
	<select name="valeur_3" id="valeur_3" onchange="$('valeur_4').value = 0; $('bouton_vendrehotel').disabled=true">
	 	<option value="-1">(Choisissez un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->autres as $k => $v) :?>
 			<option value="<?=$k?>"><?=$v["nom"] ?> : <?=$v["nb"] ?></option>
	 	<? endforeach; ?>
	</select>
<br /><br />
Quantit&eacute; &agrave; vendre : <br />
<input type='text' maxlength='7' size='7' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event);" onkeyup="if (this.value > 0 && $('valeur_3').value > 0 && $('valeur_5').value > 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
<? endif; ?>