<?php if ($this->vendreOk === true) : ?>
	Choississez un mat&eacute;riel &agrave; mettre en vente : <br />
	<select name="valeur_3" id="valeur_3" onchange="if (this.value > 0 && $('valeur_5').value > 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
	 	<option value="-1">(Choisissez un mat&eacute;riel)</option>
	 	<?php foreach($this->materiels as $e) :?>
	 		<option value="<?php echo $e["id_materiel"]?>">n&deg;<?php echo $e["id_materiel"] ?> <?php echo $e["nom"]?></option>
	 	<?php endforeach; ?>
	</select>
	<input type='hidden' name='valeur_4' id='valeur_4' value='1' />
<?php endif; ?>