<? if (count($this->munitions) > 0) :?>
	Munitions:<br/>
	
	<select name="valeur_3" id="valeur_3" onchange="$('valeur_4').value = 0; $('bouton_vendrehotel').disabled=true ">
	 	<option value="-1">(Choisissez un type de munition brut)</option>
	 	<? foreach($this->munitions as $m) :?>
	 		<option value="<?=$m["id_type_munition"]?>"><?=$m["type"]?> : <?=$m["quantite"]?></option>
	 	<? endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; &agrave; vendre : <br />
	<input type='text' maxlength='7' size='7' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event);" onkeyup="if (this.value > 0 && $('valeur_3').value > 0 && $('valeur_5').value > 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
<? endif; ?>