<?php if (count($this->partiePlantes) > 0) :?>
	&Eacute;lements de Plantes:<br/>
	
	<select name="valeur_3" id="valeur_3" onchange="$('valeur_4').value = 0; $('bouton_vendrehotel').disabled=true ">
		 	<option value="-1">(Choisissez une plante)</option>
	 	<?php foreach($this->partiePlantes as $k => $m) :?>
	 		<option value="<?php echo $k?>"><?php echo $m["nom_forme"]?> : <?php echo $m["quantite"]?> <?php echo $m["type"]?><?php if ($m["quantite"] > 0): echo "s"; endif; ?> de <?php echo $m["type_plante"]?></option>
	 	<?php endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; &agrave; vendre : <br />
	<input type='text' maxlength='7' size='7' name='valeur_4' id='valeur_4' value='0' onkeypress="chiffres(event);" onkeyup="if (this.value > 0 && $('valeur_3').value != -1 && $('valeur_5').value >= 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
<?php endif; ?>