<br><br>
Vous pouvez vendre l'&eacute;quipement &agrave; l'aide de trois unit&eacute;s diff&eacute;rentes : <br>

<? $js = "
	if ($('valeur_2').value !=-1 && $('valeur_3').value != -1 && $('valeur_4').value > 0 && $('valeur_4').value != '' && $('valeur_5').value >= 0 && $('valeur_5').value != '' && $('valeur_6').value !=-1 ) {
		$('bouton_vendrehotel').disabled=false;
	} else {
		$('bouton_vendrehotel').disabled=true;
	}
";
?>

<table class="table_liste" style="width:98%; border:0" >
<tbody>
	<tr class="table_liste" valign="top">
		<td align="right">
			<input type='textbox' maxlength='4' size='4' name='valeur_5' id='valeur_5' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
			unit&eacute;(s) de 
		</td>
		<td align="left">&nbsp;
			<select name="valeur_6" id="valeur_6" onChange="<?=$js ?>">
		 		<option value="-1">(Choisis une unit&eacute;)</option>
				<? foreach($this->unites as $k => $u) :?>
					<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
				<? endforeach; ?>
			</select> OU
		</td>
	</tr>
	<tr>
		<td align="right">
			<input type='textbox' maxlength='4' size='4' name='valeur_7' id='valeur_7' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
			unit&eacute;(s) de 
		</td>
		<td align="left">&nbsp;
			<select name="valeur_8" id="valeur_8">
		 		<option value="-1">(Choisis une unit&eacute;)</option>
				<? foreach($this->unites as $k => $u) :?>
					<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
				<? endforeach; ?>
			</select> OU
		</td>
	</tr>
	<tr>
		<td align="right">
			<input type='textbox' maxlength='4' size='4' name='valeur_9' id='valeur_9' value='' onkeypress="chiffres(event, false);" onKeyup="<?=$js?>">
			unit&eacute;(s) de 
		</td>
		<td align="left">&nbsp;
			<select name="valeur_10" id="valeur_10">
		 		<option value="-1">(Choisis une unit&eacute;)</option>
				<? foreach($this->unites as $k => $u) :?>
					<option value="<?=$k ?>"><?=htmlspecialchars($u["nom_type_unite"]) ?> </option>
				<? endforeach; ?>
			</select>
		</td>
	</tr>
</tbody>
</table>
 
<br />

<ul class="titre textalic textsized" > Commentaire de mise en vente </ul>
<br />
<?=Bral_Helper_BBBoutons::affiche('valeur_commentaire', 100)?>
<input type='hidden' id='valeur_11' name='valeur_11' value='' />
<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="100" type="text"> Caract&egrave;res restants<br>
<textarea name="valeur_commentaire" id="valeur_commentaire" class="inputbox" rows="4" cols="60" onkeydown="textCount($('valeur_commentaire'),$('characterstyped'),100);" onkeyup="textCount($('valeur_commentaire'),$('characterstyped'),100);"></textarea>
