<?php if ($this->vendreOk === true) : ?>
	Choississez une rune &agrave; d&eacute;poser.<br />
	<select name="valeur_3" id="valeur_3" onchange="if (this.value > 0 && $('valeur_5').value > 0 && $('valeur_6').value != -1) {$('bouton_vendrehotel').disabled=false} else {$('bouton_vendrehotel').disabled=true} ">
	 	<option value="-1">(Choisissez une rune)</option>
	 	<?php foreach($this->runes as $r) :?>
	 		<option value="<?php echo $r["id_rune"]?>">Rune n&deg;<?php echo $r["id_rune"] ?>, 
	 		<?php if ($r["est_identifiee"] == "oui") : ?>
	 			<?php echo $r["type"] ?>
	 		<?php else: ?>
	 			rune non identifi&eacute;e
	 		<?php endif; ?>
	 		
	 		</option>
	 	<?php endforeach; ?>
	</select>
	<input type='hidden' name='valeur_4' id='valeur_4' value='1' />
<?php endif; ?>