<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 
 <div class='comp_contenu'>
 
	Id : <?php echo $this->lieu->id_lieu?><br />
	Nom : <?php echo $this->lieu->nom_lieu?> (<?php echo $this->lieu->id_lieu?>)<br />
	X:<?php echo $this->lieu->x_lieu?> <br />
	Y: <?php echo $this->lieu->y_lieu?><br /><br />
	
	 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->lieu->id_lieu?>'><br />
	 X : <input type='text' id='valeur_2' name='valeur_2' value='<?php echo $this->lieu->x_lieu?>'><br />
	 Y : <input type='text' id='valeur_3' name='valeur_3' value='<?php echo $this->lieu->y_lieu?>'><br />
 </div>

</form>
<br />
<input type='button' class='button' id='bouton_deplacerlieu' value='Déplacer' onclick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_deplacerlieu&id_lieu=<?php echo $this->lieu->id_lieu?>");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>