<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='4'>
 
 <div class='comp_contenu'>
 
	Id : Automatique<br />
	
	 X : <input type='text' id='valeur_1' name='valeur_1' value='<?=$this->xEau?>'><br />
	 Y : <input type='text' id='valeur_2' name='valeur_2' value='<?=$this->yEau?>'><br />
	 Z : <input type='text' id='valeur_3' name='valeur_3' value='<?=$this->zEau?>'><br />
	 
	 Type : <br />
	 	<select name='valeur_4' id="valeur_4">
	 	<? foreach ($this->typeEau as $t) : ?>
		<option value="<?=$t["type"]?>" <?=$t["selected"]?>><?=$t["type"]?></option>
		<? endforeach; ?>
		</select><br /><br />
		
		Si une eau existe déjà, elle sera supprimée.
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_inserereau' value='Insérer / Supprimer' onClick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_inserereau");'>
<? echo Bral_Helper_Fermer::affiche(); ?>