<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='7'>
 
 <div class='comp_contenu'>
 
	Id : Automatique<br />
	
	 X : <input type='text' id='valeur_1' name='valeur_1' value='<?=$this->xLieu?>'><br />
	 Y : <input type='text' id='valeur_2' name='valeur_2' value='<?=$this->yLieu?>'><br />
	 
	 Type : <br />
	 	<select name='valeur_3' id="valeur_3">
	 	<? foreach ($this->typeLieux as $t) : ?>
		<option value="<?=$t["type"]["id_type_lieu"]?>" <?=$t["selected"]?>><?=$t["type"]["id_type_lieu"]?> : <?=$t["type"]["nom_type_lieu"]?></option>
		<? endforeach; ?>
		</select><br /><br />
	 
	 Nom : <input type='text' id='valeur_4' name='valeur_4' value="<?=$this->villeEnCours?>"><br />
	 Description : <input type='text' id='valeur_5' name='valeur_5' value="Description <?=$this->villeEnCours?>"><br />
	 
	 Ville : <br>
	 	<select name='valeur_6' id="valeur_6">
	 	<option value="-1">Aucune ville (pour lieu RP par exemple)</option>
	 	<? foreach ($this->villes as $v) : ?>
		<option value="<?=$v["ville"]["id_ville"]?>" <?=$v["selected"]?>><?=$v["ville"]["id_ville"]?> : <?=$v["ville"]["nom_ville"]?> <?=$v["info"]?></option>
		<? endforeach; ?>
		</select><br /><br />
		
		 Est Lieu Soule : <br>
	 	<select name='valeur_7' id="valeur_7">
	 	<? foreach ($this->estSoule as $k => $v) : ?>
			<option value="<?=$k?>"><?=$k?></option>
		<? endforeach; ?>
		</select><br /><br />
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_insererlieu' value='Insérer' onClick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_insererlieu");'>
<? echo Bral_Helper_Fermer::affiche(); ?>