<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='4'>
 
 <div class='comp_contenu'>
 
	Id : Automatique<br />
	
	 X : <input type='text' id='valeur_1' name='valeur_1' value='<?php echo $this->xRoute?>'><br />
	 Y : <input type='text' id='valeur_2' name='valeur_2' value='<?php echo $this->yRoute?>'><br />
	 Z : <input type='text' id='valeur_3' name='valeur_3' value='<?php echo $this->zRoute?>'><br />
	 
	 Type : <br />
	 	<select name='valeur_4' id="valeur_4">
	 	<?php foreach ($this->typeRoute as $t) : ?>
		<option value="<?php echo $t["type"]?>" <?php echo $t["selected"]?>><?php echo $t["type"]?></option>
		<?php endforeach; ?>
		</select><br /><br />
		
		Si une route existe déjà, elle sera supprimée.
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_insererroute' value='Insérer / Supprimer' onclick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_insererroute");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>