<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='8'>
 
 <div class='comp_contenu'>
 
	Id : Automatique<br />
	
	X : <input type='text' id='valeur_1' name='valeur_1' value='<?php echo $this->xPalissade?>'><br />
	Y : <input type='text' id='valeur_2' name='valeur_2' value='<?php echo $this->yPalissade?>'><br />
	Z : <input type='text' id='valeur_3' name='valeur_3' value='<?php echo $this->zPalissade?>'><br />
	PV : <input type='text' id='valeur_4' name='valeur_4' value='1000'><br />
	Armure Naturelle : <input type='text' id='valeur_5' name='valeur_5' value='50'><br />
	nbJour avant destruction : <input type='text' id='valeur_6' name='valeur_6' value='10000'><br />
	Agilité : <input type='text' id='valeur_7' name='valeur_7' value='100'><br />
 
	Destructible ? <br />
	<select name='valeur_8' id="valeur_8">
		<option value="oui">Oui</option>
		<option value="non" selected>Non</option>
	</select><br /><br />

Si une palissade existe déjà, elle sera supprimée.
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_insererpalissade' value='Insérer / Supprimer' onclick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_insererpalissade");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>