<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
<form name='myForm'>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 
 <div class='comp_contenu'>
 
	Id : Automatique<br />
	
	 X : <input type='text' id='valeur_1' name='valeur_1' value='<?=$this->xRoute?>'><br />
	 Y : <input type='text' id='valeur_2' name='valeur_2' value='<?=$this->yRoute?>'><br />
	 
	 Type : <br />
	 	<select name='valeur_3' id="valeur_3">
	 	<? foreach ($this->typeRoute as $t) : ?>
		<option value="<?=$t["type"]?>" <?=$t["selected"]?>><?=$t["type"]?></option>
		<? endforeach; ?>
		</select><br /><br />
		
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_insererroute' value='Insérer' onClick='this.disabled=true;_get_("/administrationajax/doaction?caction=do_administrationajax_insererroute");'>
<? echo Bral_Helper_Fermer::affiche(); ?>