<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Stock Plantes</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<? if ($this->creation === true) : ?>
				<b>Cr&eacute;ation du nouveau stock effectu&eacute;e</b> <br />
			<? endif; ?>
			<form action="/Administrationstockplante/plantes" method="post">
				
				Ajouter un nouveau stock, qui sera actif le : 
				<?=$this->dateCreationStock ?>
				<br><br>
					<span class="titre textalia textsizeb">PV : Prix Vente en castars, par la boutique</span><br>
					<span class="titre textalia textsizeb">PR : Prix Reprise en castars, par la boutique</span><br>
					<span class="titre textalia textsizeb">NB : Quantité initiale</span><br>
				<br><br>
				
				<table width="100%">
				<? 
				$i = -1;
				foreach ($this->regions as $r) : ?>
					<? 
					$i++;
					if ($i % 4 == 0): echo "<tr>"; endif;?>
						<td style="text-align:right">
							<span class="titre textalia textsizec"><?=$r["nom_region"]?></span> <br>
							<? foreach ($r["type_plantes"] as $t) : ?>
							
							<span class="titre textalia textsized"><?=$t["nom"]?> - <?=$t["categorie"] ?></span><br>
							
							<? foreach ($t["parties"] as $p) : ?>
							
								 <?=$p["nom"]?>
								 <span title='Prix Vente en castars' style="cursor:pointer">PV</span> <input type="textbox" name="<?=$p["id_form"]."_vente"?>" size='3' value="<?=$p["prix_unitaire_vente"]?>" />
								 <span title='Prix Reprise en castars' style="cursor:pointer">PR</span> <input type="textbox" name="<?=$p["id_form"]."_reprise"?>" size='3' value="<?=$p["prix_unitaire_reprise"]?>"/>
								 <span title='Prix Reprise en castars' style="cursor:pointer">NB</span> <input type="textbox" name="<?=$p["id_form"]."_nbinitial"?>" size='3' value="<?=$p["nb_brut"]?>"/> <br>
								
								<? endforeach; ?>
								<br>
							<? endforeach; ?>
							<br><br>
						
						</td>
					<? if ($i % 4 == 3): echo "</tr>"; endif;?>
				<? endforeach; ?>
				</table>
				
			<input type="submit" class="button1" name="add" value="Ajouter le nouveau stock" />
			</form>
			
			<br><br>
			<form action="/Administrationstockplante/plantes" method="post">
				Date Stock (AAAA-MM-JJ 00:00:00) 
				
				<select name="dateStock">
					<? foreach($this->listeDates as $k=>$v) : ?>
						<option value="<?=$v?>" <? if ($this->dateStock == $v) : echo "selected"; endif;?>><?=substr($v, 0, 10)?></option>
					<? endforeach;?>
				</select>
				
				<input type="submit" class="button1" name="add" value="Voir stock" />
			</form>
			
		<br /><br />
			
			<? if (count($this->stocks) > 0 ) : ?>
				<table align='center'>
				<th class='comp_titre'>N&deg;</th>
				<th class='comp_titre'>Date</th>
				<th class='comp_titre'>Type Partie</th>
				<th class='comp_titre'>Type Plante</th>
				<th class='comp_titre'>Stock Initial</th>
				<th class='comp_titre'>Stock Restant</th>
				<th class='comp_titre'>Prix Vente par Boutique</th>
				<th class='comp_titre'>Prix Reprise</th>
				<th class='comp_titre'>R&eacute;gion</th>
				
				<? foreach($this->stocks as $r) :?>
					<tr>
						<td><?=$r["id_stock_partieplante"]?></td>
						<td><?=$r["date_stock_partieplante"]?></td>
						<td><?=$r["nom_type_partieplante"]?></td>
						<td><?=$r["nom_type_plante"]?></td>
						<td><?=$r["nb_brut_initial_stock_partieplante"]?></td>
						<td><?=$r["nb_brut_restant_stock_partieplante"]?></td>
						<td><?=$r["prix_unitaire_vente_stock_partieplante"]?></td>
						<td><?=$r["prix_unitaire_reprise_stock_partieplante"]?></td>
						<td><?=$r["nom_region"]?></td>
					</tr>
				<? endforeach;?>
				</table>
			<? else: ?>
			Ancun stock, date <?=$this->dateStock?>
			<? endif;?>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>