<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Infos Jeu</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
			<form action="/Administrationinfojeu/infosjeu" method="post">
			<input type='hidden' name='idinfoEdit' id='idinfoEdit' value='<?=$this->infoJeu["id_info_jeu"]?>'/>
			<? if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<br>
				<ul class="titre textalic textsizeb">Edition de l'Infos n&deg; <?=$this->infoJeu["id_info_jeu"]?>, du <?=$this->infoJeu["date_info_jeu"]?></ul>
				<br>
			<? endif; ?>
			
			<?=Bral_Helper_BBBoutons::affiche('texte_info')?>
	
			<span>Message</span><br>
			<textarea name="texte_info" id="texte_info" class="inputbox" rows="10" cols="60" onkeydown="textCount($('texte_info'),$('characterstyped'),2500);" onkeyup="textCount($('texte_info'),$('characterstyped'),2500);"><?=$this->infoJeu["text_info_jeu"]?></textarea>
			
			<br>
			<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="2500" type="text"> Caract&egrave;res restants<br>
					
			<? if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<input type="submit"  class='button1' name="Editer" value="Editer l'info" />
			<? else :?>
				<input type="submit"  class='button1' name="Ajouter" value="Ajouter l'info" />
			<? endif;?>
			</form>
		<br /><br />
			<table  align='center'>
			<th class='comp_titre'>Id</th>
			<th class='comp_titre'>Date</th>
			<th class='comp_titre'>Est sur Accueil</th>
			<th class='comp_titre'>Texte</th>
			<? if (count($this->infosJeu) > 0) : ?>
				<? $i = 0; 
					foreach ($this->infosJeu as $info) : ?>
					<tr class="table_liste<?=($i % 2);$i++; ?>">
						<td class="table_liste"><?=$info["id_info_jeu"] ?></td>
						<td class="table_liste"><?=$info["date_info_jeu"] ?></td>
						<td class="table_liste"><?=$info["est_sur_accueil_info_jeu"] ?></td>
						<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Editer l'info" onClick='document.location.href="/Administrationinfojeu/infosjeu/idinfo/<?=$info["id_info_jeu"] ?>"'/></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Passer en page d'accueil" onClick='document.location.href="/Administrationinfojeu/estaccueil/idinfo/<?=$info["id_info_jeu"] ?>/"'></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Supprimer de la page d'accueil" onClick='document.location.href="/Administrationinfojeu/estnonaccueil/idinfo/<?=$info["id_info_jeu"] ?>"'/></td>
					</tr>
				<? endforeach; ?>
			<? endif; ?>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>