<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Administration Infos Jeu</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
			<form action="/Administrationinfojeu/infosjeu" method="post">
			<input type='hidden' name='idinfoEdit' id='idinfoEdit' value='<?=$this->infoJeu["id_info_jeu"]?>'/>
			<? if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<br>
				<ul class="titre textalic textsizeb">Edition de l'Infos n&deg; <?=$this->infoJeu["id_info_jeu"]?>, du <?=$this->infoJeu["date_info_jeu"]?></ul>
				<br>
			<? endif; ?>
			
			<?=Bral_Helper_BBBoutons::affiche('texte_info', 200)?>
	
			<span>Message</span><br>
			<textarea name="texte_info" id="texte_info" class="inputbox" rows="10" cols="60" onkeydown="textCount($('texte_info'),$('characterstyped'),200);" onkeyup="textCount($('texte_info'),$('characterstyped'),200);"><?=stripslashes($this->infoJeu["text_info_jeu"])?></textarea>
			
			<br>
			<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="200" type="text"> Caract&egrave;res restants<br>
			
			<br>
			Titre (facultatif) : <input type="text" name="titre_info" id="titre_info" size="50" maxlength="50" class="inputbox" value="<?=$this->infoJeu["titre_info_jeu"]?>"/>
			
			<br>
			Lien article règles : <input type="text" name="lien_wiki_info" id="lien_wiki_info" size="40" maxlength="200" class="inputbox" value="<?=$this->infoJeu["lien_wiki_info_jeu"]?>"/>
			<br>
			Autre lien (post sur le forum par exemple) <input type="text" name="lien_info" id="lien_info" size="40" maxlength="200" class="inputbox" value="<?=$this->infoJeu["lien_info_jeu"]?>"/>
			<br>
			
			<select name='type_info' id="type_info">
				<? foreach ($this->tabTypes as $k => $v) : ?>
				<option value="<?=$k?>" <? if ($this->infoJeu["type_info_jeu"] == $k) : echo "selected"; endif;?>><?=$v?></option>
				<? endforeach; ?>
			</select><br /><br />
			
			<? if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<input type="submit"  class='button1' name="Editer" value="Editer l'info" />
			<? else :?>
				<input type="submit"  class='button1' name="Ajouter" value="Ajouter l'info" />
			<? endif;?>
			</form>
			
			<br />
			
			Valider le flux : <a href='http://validator.w3.org/feed/check.cgi?url=http%3A//jeu.braldahim.com/Feed'>http://validator.w3.org/feed/check.cgi?url=http%3A//jeu.braldahim.com/Feed</a>
			
			<br /><br /><br />
			
			<table  align='center'>
			<th class='comp_titre'>Id</th>
			<th class='comp_titre'>Date</th>
			<th class='comp_titre'>Est sur Accueil</th>
			<th class='comp_titre'>Texte</th>
			<? if (count($this->infosJeu) > 0) : ?>
				<? $i = 0; 
					foreach ($this->infosJeu as $info) : ?>
					<tr class="table_liste<?=($i % 2);$i++; ?>">
						<td class="table_liste"><?=$info["id_info_jeu"] ?></td>
						<td class="table_liste"><?=$info["date_info_jeu"] ?></td>
						<td class="table_liste"><?=$info["est_sur_accueil_info_jeu"] ?></td>
						<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
						<? if ($info["lien_info_jeu"] != null) :?>
							<a href="<?=$info["lien_info_jeu"]?>">...Lire la suite.</a>
						<? endif;?>
						</td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Editer l'info" onClick='document.location.href="/Administrationinfojeu/infosjeu/idinfo/<?=$info["id_info_jeu"] ?>"'/></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Passer en page d'accueil" onClick='document.location.href="/Administrationinfojeu/estaccueil/idinfo/<?=$info["id_info_jeu"] ?>/"'></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Supprimer de la page d'accueil" onClick='document.location.href="/Administrationinfojeu/estnonaccueil/idinfo/<?=$info["id_info_jeu"] ?>"'/></td>
					</tr>
				<? endforeach; ?>
			<? endif; ?>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>