<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Infos Jeu</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
			<form action="/Administrationinfojeu/infosjeu" method="post">
			<input type='hidden' name='idinfoEdit' id='idinfoEdit' value='<?php echo $this->infoJeu["id_info_jeu"]?>'/>
			<?php if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<br />
				<div class="titre textalic textsizeb">Edition de l'Infos n&deg; <?php echo $this->infoJeu["id_info_jeu"]?>, du <?php echo $this->infoJeu["date_info_jeu"]?></div>
				<br />
			<?php endif; ?>
			
			<?php echo Bral_Helper_BBBoutons::affiche('texte_info', 200)?>
	
			<span>Message</span><br />
			<textarea name="texte_info" id="texte_info" class="inputbox" rows="10" cols="60" onkeydown="textCount($('#texte_info'),$('#characterstyped'),200);" onkeyup="textCount($('#texte_info'),$('#characterstyped'),200);"><?php echo stripslashes($this->infoJeu["text_info_jeu"])?></textarea>
			
			<br />
			<input style="background-color: #31401A;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="200" type="text"> Caract&egrave;res restants<br />
			
			<br />
			Titre (facultatif) : <input type="text" name="titre_info" id="titre_info" size="50" maxlength="50" class="inputbox" value="<?php echo $this->infoJeu["titre_info_jeu"]?>"/>
			
			<br />
			Lien article règles : <input type="text" name="lien_wiki_info" id="lien_wiki_info" size="40" maxlength="200" class="inputbox" value="<?php echo $this->infoJeu["lien_wiki_info_jeu"]?>"/>
			<br />
			Autre lien (post sur le forum par exemple) <input type="text" name="lien_info" id="lien_info" size="40" maxlength="200" class="inputbox" value="<?php echo $this->infoJeu["lien_info_jeu"]?>"/>
			<br />
			
			<select name='type_info' id="type_info">
				<?php foreach ($this->tabTypes as $k => $v) : ?>
				<option value="<?php echo $k?>" <?php if ($this->infoJeu["type_info_jeu"] == $k) : echo "selected"; endif;?>><?php echo $v?></option>
				<?php endforeach; ?>
			</select><br /><br />
			
			<?php if ($this->infoJeu["id_info_jeu"] != -1) : ?>
				<input type="submit"  class='button' name="Editer" value="Editer l'info" />
			<?php else :?>
				<input type="submit"  class='button' name="Ajouter" value="Ajouter l'info" />
			<?php endif;?>
			</form>
			
			<br />
			
			Valider le flux : <a href='http://validator.w3.org/feed/check.cgi?url=http%3A//feeds.braldahim.com/braldahim-chronique'>http://validator.w3.org/feed/check.cgi?url=http%3A//feeds.braldahim.com/braldahim-chronique</a>
			
			<br /><br /><br />
			
			<table  align='center'>
			<tr>
			<th class='comp_titre'>Id</th>
			<th class='comp_titre'>Date</th>
			<th class='comp_titre'>Est sur Accueil</th>
			<th class='comp_titre'>Texte</th>
			</tr>
			<?php if (count($this->infosJeu) > 0) : ?>
				<?php $i = 0; 
					foreach ($this->infosJeu as $info) : ?>
					<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
						<td class="table_liste"><?php echo $info["id_info_jeu"] ?></td>
						<td class="table_liste"><?php echo $info["date_info_jeu"] ?></td>
						<td class="table_liste"><?php echo $info["est_sur_accueil_info_jeu"] ?></td>
						<td class="table_liste"><?php echo Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
						<?php if ($info["lien_info_jeu"] != null) :?>
							<a href="<?php echo $info["lien_info_jeu"]?>">...Lire la suite.</a>
						<?php endif;?>
						</td>
						<td class="table_liste"><input type="button"  class='button' name="Editer" value="Editer l'info" onclick='document.location.href="/Administrationinfojeu/infosjeu/idinfo/<?php echo $info["id_info_jeu"] ?>"'/></td>
						<td class="table_liste"><input type="button"  class='button' name="Editer" value="Passer en page d'accueil" onclick='document.location.href="/Administrationinfojeu/estaccueil/idinfo/<?php echo $info["id_info_jeu"] ?>/"'></td>
						<td class="table_liste"><input type="button"  class='button' name="Editer" value="Supprimer de la page d'accueil" onclick='document.location.href="/Administrationinfojeu/estnonaccueil/idinfo/<?php echo $info["id_info_jeu"] ?>"'/></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>