<div class="titre textalic textsizeb">Les Annonces</div><br/>
<?php if (count($this->annonces) > 0) : ?>
    <table class="table_liste" style="width:300px; border: 0px">
		<?php 
			$i = 0; 
			foreach ($this->annonces as $info) : ?>
			<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
				<td class="table_liste">
				
				Le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$info["date_info_jeu"]) ?>
				<br/>
				<?php if (Bral_Util_ConvertDate::get_date_add_time_to_date($info["date_info_jeu"], "36:00:00") > date("Y-m-d H:i:s")): ?>
					<img src="<?php echo $this->config->static->url?>/images/new.gif" alt="information de moins de 36 heures" style="cursor:pointer"/>
					<br/>
				<?php else:?>
					&nbsp;
				<?php endif;?>
				
				<?php if ($info["titre_info_jeu"] != null && $info["titre_info_jeu"] != "") :?>
					<br/>
					<p class="titre textalic textsized center textdark"><?php echo stripslashes($info["titre_info_jeu"])?></p>
					<br />
				<?php endif;?>
				
				<?php echo Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
				<?php if ($info["lien_wiki_info_jeu"] != null) :?>
					<a href="<?php echo htmlspecialchars($info["lien_wiki_info_jeu"])?>">Voir les règles.</a> 
				<?php endif;?>
				<?php if ($info["lien_info_jeu"] != null) :?>
					<br/><a href="<?php echo htmlspecialchars($info["lien_info_jeu"])?>">Discussions.</a>
				<?php endif;?>
				</td>
			</tr>
		<?php endforeach; ?>
		</table>
<?php endif; ?>
<a href="http://jeu.braldahim.com/annonces" class="aWhite">Voir les archives</a>
