<? if (count($this->histoires) > 0) : ?>
    <ul class="titre textalic textsizeb">La Gazette</ul><br>
	<? 
	$i = 0; 
	foreach ($this->histoires as $info) : ?>
		<table style="width:300px">
    	<thead>
    
		<tr>
			<td style="height:200px;text-align: justify; vertical-align:top">
			
			<ul class="box_contenu<?=($i % 2);$i++; ?>" style="height:200px;text-align: justify; vertical-align:top">
			Parution le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$info["date_info_jeu"]) ?>
			<br>
			<? if ($info["titre_info_jeu"] != null && $info["titre_info_jeu"] != "") :?>
				<br>
				<ul class="titre textalic textsized textdark"><?=stripslashes($info["titre_info_jeu"])?></ul>
			<? endif;?>
			
			<? if (Bral_Util_ConvertDate::get_date_add_time_to_date($info["date_info_jeu"], "36:00:00") > date("Y-m-d H:i:s")): ?>
				<img src="/public/images/new.gif" title="information de moins de 36 heures" style="cursor:pointer"/>
			<? else:?>
				&nbsp;
			<? endif;?>
			
			<div class="gazette_histoire">
				<?=Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
				<? if ($info["lien_wiki_info_jeu"] != null) :?>
					<a href="<?=$info["lien_wiki_info_jeu"]?>">...Lire la suite.</a>
				<? endif;?>
			</div>
			
			<? if ($info["lien_info_jeu"] != null) :?>
				<br>Les Braldûns en discutent
				<a href="<?=$info["lien_info_jeu"]?>">sur le forum.</a>
			<? endif;?>
			
			</ul>
			</td>
		</tr>
		</thead>
	</table>
<? endforeach; ?>
<a href="http://jeu.braldahim.com/gazette" class="aWhite">Voir les archives</a>
<? endif; ?>
