<?php if (count($this->histoires) > 0) : ?>
    <div class="titrea textalic textsizeb">La Gazette</div><br/>
	<?php 
	$i = 0; 
	foreach ($this->histoires as $info) : ?>
		<table style="width:300px">    
		<tr>
			<td style="text-align: justify; vertical-align:top">
			
			<div class="box_contenu<?php echo ($i % 2);$i++; ?> braltexte2 braltextefonce" style="text-align: justify;">
			<p class="titre texttitre textdark">Parution le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$info["date_info_jeu"]) ?></p>
			<?php if ($info["titre_info_jeu"] != null && $info["titre_info_jeu"] != "") :?>
				<div class="titre textalic textsized_noshadow textdark"><?php echo stripslashes($info["titre_info_jeu"])?></div>
			<?php endif;?>
			
			<?php if (Bral_Util_ConvertDate::get_date_add_time_to_date($info["date_info_jeu"], "36:00:00") > date("Y-m-d H:i:s")): ?>
				<img src="<?php echo $this->config->static->url?>/images/new.gif" alt="information de moins de 36 heures" style="cursor:pointer"/>
			<?php else:?>
				&nbsp;
			<?php endif;?>
			
			<div class="gazette_histoire">
				<?php echo Bral_Util_BBParser::bbcodeReplace($info["text_info_jeu"]);?>
				<?php if ($info["lien_wiki_info_jeu"] != null) :?>
					<a href="<?php echo htmlspecialchars($info["lien_wiki_info_jeu"])?>">...Lire la suite.</a>
				<?php endif;?>
			</div>
			
			<?php if ($info["lien_info_jeu"] != null) :?>
				<br/>Les Braldûns en discutent
				<a href="<?php echo htmlspecialchars($info["lien_info_jeu"])?>">sur le forum.</a>
			<?php endif;?>
			
			</div>
			</td>
		</tr>
	</table>
<?php endforeach; ?>
<a href="http://jeu.braldahim.com/gazette" class="aWhite">Voir les archives</a>
<?php endif; ?>
