<div class="box_contenu textalic">
	<div class="titre textalic textsizea">
		Bienvenue sur Braldahim !
	</div>
	<table style="width: 100%" align="center">
		<tr>
			<td valign="top" style="width: 150px"></td>
			<td valign="top">
			<div class="box_contenu1" style="width: 250px;">
				<br/>
				Braldahim est un jeu d'aventures et d'entraide dans lequel les
				joueurs peuvent incarner un Semi-Homme.
				<br/>
				<br/>
				Chaque Semi-Homme peut exercer un métier et évolue au rythme de 12
				points d'actions par tranche de 24 heures.
				<br/>
				<br/>
				Le jeu est entièrement gratuit et ouvert à toute personne disposant
				d'une adresse mail et d'un accès internet régulier.
				<br/>
				<br/>
			</div>
			</td>
			<td>
			<div class="titre textalic textsized">
				Inscription
			</div>
			Vous pouvez vous inscrire sur <a href="http://jeu.braldahim.com"
				class="aWhite">http://jeu.braldahim.com</a> et voir comment <a
				href="http://wiki.braldahim.com/wiki/Bien_d%C3%A9buter"
				class="aWhite">bien débuter</a>.<br/>
			<br/><br/>
			<div class="titre textalic textsized">
				Screenshots
			</div>	
				<a href="/public/images/screenshots/braldahim_screen1.png" rel="lightbox[accueil]" title="Braldahim - Interface de jeu - Vue">
				<img src="/public/images/screenshots/braldahim_screen1-small.png" alt=""/>
				</a>
				<a href="/public/images/screenshots/braldahim_screen2.png" rel="lightbox[accueil]" title="Braldahim - Interface de jeu - Équipement">
				<img src="/public/images/screenshots/braldahim_screen2-small.png" alt=""/>
				</a>
				<a href="/public/images/screenshots/braldahim_screen3.png" rel="lightbox[accueil]" title="Braldahim - Interface de jeu - Quête">
				<img src="/public/images/screenshots/braldahim_screen3-small.png" alt=""/>
				</a>
				<a href="/public/images/screenshots/braldahim_screen4.png" rel="lightbox[accueil]" title="Braldahim - Interface de jeu - Titres et Distinctions">
				<img src="/public/images/screenshots/braldahim_screen4-small.png" alt=""/>
				</a>
				
			</td>
		</tr>
	</table>
</div>

<br/>

<div class="box_contenu textalic">
	<table style="width: 100%">
		<tr>
			<td style="width: 130px" valign="top">
			<div id="braldunsite"></div>
			</td>
			<td style="width: 200px;" valign="top"><?=$this->render("index/gazette.phtml"); ?>
			</td>
			<td style="width: 200px;" valign="top"><?=$this->render("index/annonces.phtml"); ?>
			</td>
		</tr>
	</table>

	<p align="center"><a href="http://www.jeuxweb.org" target="_blank"
		class="aWhite">Braldahim est un jeu géré par l'association sans but
	lucratif JeuxWeb.org </a><br/>
	<a href="http://www.jeuxweb.org" target="_blank"><img
		src="http://www.mountyhall.com/images/Banner/banner_jw.gif"
		alt="JeuxWeb" border="0" height="60" width="468"/></a></p>
</div>
