<ul class="box_contenu textalic">
	<ul class="titre textalic textsizea">
	Bienvenue sur Braldahim !
	</ul>
	<br>
	<ul class="titre textalic textsized">
		Le jeu est actuellement en phase de beta-test publique. 
	</ul>
	Vous pouvez vous inscrire sur <a href="http://jeu.braldahim.com">http://jeu.braldahim.com</a>
	et voir comment <a href="http://wiki.braldahim.com/wiki/Bien_d%C3%A9buter">bien débuter</a>.<br>
	<br>
	La fin de la phase de Bêta-Test Publique n'est pas encore connue.<br>
	Tous les comptes créés seront supprimés à la fin de cette phase.<br>
</ul>

<br>

<ul class="box_contenu textalic">
	<table style="width:100%">
	<tr>
		<td style="width:400px" valign="top">
			<img src="/public/images/hobbit-site.gif">
		</td>
		<td style="width:200px;" valign="top">
			<?=$this->render("index/gazette.phtml"); ?>
			
			<?=$this->render("index/annonces.phtml"); ?>
		</td>
	</tr>
	</table>
	
	<p align="center"><a href="http://www.jeuxweb.org" target="_blank" class="AllLinks">Braldahim est un jeu géré par l'association sans but lucratif JeuxWeb.org </a><br>
		<a href="http://www.jeuxweb.org" target="_blank"><img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="JeuxWeb" border="0" height="60" width="468"></a>
	</p>
</ul>