<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Hobbit</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
	    <? if ($this->modificationHobbit === true) :?>
	    	Modification du hobbit prise en compte.
	    <? endif; ?>
	    Compte actif : <?=$this->hobbit["est_compte_actif_hobbit"]?><br>
	    Compte en hibernation : <?=$this->hobbit["est_en_hibernation_hobbit"]?><br>
	    
	    <form action="/Administrationhobbit/hobbit/mode/<?=$this->mode?>/idhobbit/<?=$this->id_hobbit?>" method="post">
		<? if ($this->hobbit == null): ?>
			Hobbit inconnu 
		<? else: 
			$nbElement = 0; ?>
			<input type="button"  class='button1' name="mode" value="Usurpation sans activation DLA (se deconnecter ensuite!)" onClick="document.location.href='/Administrationhobbit/usurpation/idhobbit/<?=$this->id_hobbit?>/activation/non'" <? if ($this->hobbit["est_compte_actif_hobbit"] != "oui") :echo "disabled='disabled'"; endif;?>/> 
			<input type="button"  class='button1' name="mode" value="Usurpation avec activation DLA (se deconnecter ensuite!)" onClick="document.location.href='/Administrationhobbit/usurpation/idhobbit/<?=$this->id_hobbit?>/activation/oui'" <? if ($this->hobbit["est_compte_actif_hobbit"] != "oui") :echo "disabled='disabled'"; endif;?>/><br>
			<? if ($this->mode == "simple") :?>
	 	   		<input type="button"  class='button1' name="mode" value="Passer en vue complexe" onClick="document.location.href='/Administrationhobbit/hobbit/mode/complexe/idhobbit/<?=$this->id_hobbit?>'"/>
	   	 	<? else: ?>
	    		<input type="button"  class='button1' name="mode" value="Passer en vue simple" onClick="document.location.href='/Administrationhobbit/hobbit/mode/simple/idhobbit/<?=$this->id_hobbit?>'"/>
	    	<? endif; ?>
	    
			<table  align='center'>
			<? foreach ($this->hobbit as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?=$key?></td>
				<td>
				<? if ($key == "id_hobbit"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=stripslashes($value)?>">
					<?=$value ?>
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=stripslashes($value)?>">
				<? endif; ?>
				</td>
				<td>				
				<? if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button1' name="Modifier" value="Modifier le hobbit" />
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
			<input type="submit"  class='button1' name="Modifier" value="Modifier le hobbit" />
		<? endif; ?>
		</form>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>