<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Hobbit</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
	    <? if ($this->modificationHobbit === true) :?>
	    	Modification du hobbit prise en compte.
	    <? endif; ?>
	    <form action="/Administrationhobbit/Hobbit/mode/<?=$this->mode?>/idhobbit/<?=$this->id_hobbit?>" method="post">
		<? if ($this->hobbit == null): ?>
			Hobbit inconnu 
		<? else: 
			$nbElement = 0; ?>
			<? if ($this->mode == "simple") :?>
	 	   		<input type="button"  class='button1' name="mode" value="Passer en vue complexe" onClick="document.location.href='/Administrationhobbit/Hobbit/mode/complexe/idhobbit/<?=$this->id_hobbit?>'"/>
	   	 	<? else: ?>
	    		<input type="button"  class='button1' name="mode" value="Passer en vue simple" onClick="document.location.href='/Administrationhobbit/Hobbit/mode/simple/idhobbit/<?=$this->id_hobbit?>'"/>
	    	<? endif; ?>
	    
			<table  align='center'>
			<? foreach ($this->hobbit as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?=$key?></td>
				<td>
				<? if ($key == "id_hobbit"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=$value?>">
					<?=$value ?>
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=htmlentities($value)?>">
				<? endif; ?>
				</td>
				<td>				
				<? if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button1' name="Modifier" value="Modifier le hobbit" />
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
			<input type="submit"  class='button1' name="Modifier" value="Modifier le hobbit" />
		<? endif; ?>
		</form>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>