<?php echo $this->render('header.phtml'); ?>

<form action="/Parametres/betanom" method="post">
<div class="box_parametres">
<div class="inner">
	<ul class="titre textalia textsizea">Mes Param&egrave;tres</ul>
    <ul class="titre textalib textsizeb">R&eacute;glages de fin de version Beta-Test</ul>
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	     <br />
	    <br />
	    
	    Vous pouvez conserver ou non votre nom de famille <b><?=$this->user->nom_hobbit?></b> lors de l'inscription en version finale de Braldahim.<br>
	    <br />
	    <br />
	    Si vous choisissez oui, le contrôle se fera à l'aide de votre email d'inscription en version finale, il faudra donc utiliser la même adresse email 
	    que celle que vous utilisez actuellement : <b><?=$this->user->email_hobbit?></b>. 
	    <br />
	    <br />
	    
	    
		<label for="title">Conserver votre nom de famille actuel lors de l'inscription en version Finale : </label><br />
		
		<input type="radio" id="valeur_1" name="valeur_1" value="oui" <? if ($this->user->beta_conserver_nom_hobbit == "oui"):echo "checked"; endif; ?>>Oui
		<input type="radio" id="valeur_1" name="valeur_1" value="non" <? if ($this->user->beta_conserver_nom_hobbit == "non"):echo "checked"; endif; ?>>Non <br /><br />
	    <br /><br />
	    
	    
	    
		<div id="formbutton">
		<input type="submit" class='button1' name="Modifier" value="Modifier" /> 
		<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/Parametres/'"/>
		</div>
		</ul>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>
