<?php echo $this->render('header.phtml'); ?>

<form id="form_message" action="/Parametres/contacter" method="post">
<div class="box_parametres">
<div class="inner">
	<div class="titre textalic textsizea">Contacter les enquêteurs</div>
    <div class="titre textalic textsizeb">Envoyer un message</div>
	&nbsp;
	<div class="contenu">
	<div class="box_contenu1 textalic">
	
	<? if ($this->idEnquete != null) : ?>
		Votre message est bien envoyé. Un enquêteur vous contactera par mail si besoin.
		<br /><br />
		<input type="button" class='button1' name="Retour" value="Retour" onClick="javascript:document.location.href='/Parametres/'"/>
		 
	<? else: ?>
	   	<table width='70%' align='center'>
 		<tr>
 		<td style='text-align:justify'>
 		
 		 Vous pouvez envoyer un message aux enquêteurs : <br /><br />
		 
		  - Permet de demander l'ouverture d'une enquête sur des Bralduns.
		  Si vous pensez que certains bralduns ne respectent pas la 
		  <a href="http://regles.braldahim.com/wiki/Charte">charte d'admission</a>, 
		  c'est ici qu'il faut le signaler.
		  <br /><br />
		  - Permet de contacter un enquêteur en cas de problème avec votre Braldun.
		  <br /><br />
		  - Permet de contacter un enquêteur pour tout message non "Role Play" envoyé dans le bourg ou dans le "Blabla" sur l'interface de jeu.
 		</td></tr>
 		</table>
		<br />
		Un enquêteur prendra contact avec vous par mail si besoin ensuite.
		
		 <br /><br />
		 
		 Votre message : <br />
		  <textarea rows='10' cols='80' name="message"  id="message"></textarea>
		  <br /><br /></br>
		  <input type="button" class='button1' name="Envoyer" onClick="$('form_message').submit(); " value="Envoyer" />
		  <input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/Parametres/'"/>
	
	 <? endif;?>
		
	 </div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>