<?php echo $this->render('header.phtml'); ?>

<form id="form_description" action="/parametres/description" method="post">
<div class="box_parametres">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<ul class="titre textalia textsizea">Mes Param&egrave;tres</ul>
    <ul class="titre textalib textsizeb">Changer la description</ul>
	&nbsp;
	<div class="contenu">
	<ul class="box_contenu1 textalic">
	
		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
		
		<ul class="titre textalic textsizec">Description</ul><br />
			<input type="button" class='button1' id="bouton_editer" value="Editer la description" 
			onClick="$('label_description').style.display='none'; 
				$('valeur_2').style.display='block' ; 
				$('bouton_description').style.display='block'; 
				 this.style.display='none' ;
				tinyMCE.execCommand('mceAddControl', false, 'valeur_2'); "/>
				
			<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/parametres/'"/>
		 
		 <center>
		 
		  <div id="label_description">
		  <?=stripslashes($this->user->description_hobbit) ?><? if (strlen(trim($this->user->description_hobbit)) == 0 || $this->user->description_hobbit == null) :?> [vide]<? endif; ?>
		  </div>
		  <textarea rows='10' cols='80' name="valeur_2"  id="valeur_2"  style="display:none" ><?=stripslashes($this->user->description_hobbit) ?></textarea>
		 
			  <input type="button" class='button1' id="bouton_description" 
			  	onClick="
				  $('valeur_2').value = escape(tinyMCE.get('valeur_2').getContent());
				  $('label_description').style.display='block'; 
				  $('valeur_2').style.display='none'; 
				  this.style.display='none' ;
				  $('valeur_1').value=2;
				  $('form_description').submit(); " value="Valider" style="display:none" />
			  
		  </center>
	   	</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>