<?php echo $this->render('header.phtml'); ?>

<form id="form_description" action="/Parametres/description" method="post">
<div class="box_parametres">
<div class="inner">
	<div class="titrea textalic titreasize0">Mes Param&egrave;tres</div>
    <div class="titrea textalic titreasizea">Changer la description</div>
	&nbsp;
	<div class="contenu">
	<div class="box_contenu1">
	
		<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
		
		<div class="titre textalic textsizec">Description</div><br />
			<input type="button" class='button1' id="bouton_editer" value="Editer la description" 
			onclick="$('label_description').style.display='none'; 
				$('edition').style.display='block' ; 
				$('bouton_description').style.display='block'; 
				 this.style.display='none' ;"/>
				
			<input type="button" class='button1' name="Annuler" value="Annuler" onclick="javascript:document.location.href='/Parametres/'"/>
		 
			 <br />
			 
			  <div id="label_description">
			  <?php echo Bral_Util_BBParser::bbcodeReplace($this->user->description_braldun) ?><?php if (mb_strlen(trim($this->user->description_braldun)) == 0 || $this->user->description_braldun == null) :?> [vide]<?php endif; ?>
			  </div>
			  
			  <div id="edition" style="display:none">
			  <?php echo Bral_Helper_BBBoutons::affiche('valeur_2', 1000000)?>
			  <textarea rows='10' cols='80' name="valeur_2"  id="valeur_2"><?php echo stripslashes($this->user->description_braldun) ?></textarea>
			 
				  <input type="button" class='button1' id="bouton_description" 
				  	onclick="
					  $('label_description').style.display='block'; 
					  $('edition').style.display='none'; 
					  this.style.display='none' ;
					  $('valeur_1').value=2;
					  $('form_description').submit(); " value="Valider" style="display:none" />
				  
			  </div>
		  
	   	</div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>