<?php echo $this->render('header.phtml'); ?>
<form action="/Parametres/email" method="post">
<div class="box_parametres">
<div class="inner">
	<div class="titre textalia textsizea">Mes Param&egrave;tres</div>
    <div class="titre textalib textsizeb">Changer d'adresse email</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    <br />
		<?php if(!empty($this->messagesPassword)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?=$this->messagesPassword; ?><br />
			</div>
		<? endif; ?>
		<label for="title">Mot de Passe Actuel</label><br />
	    <input type="password" name="email_password_actuel_braldun" value="" size="25" maxlength="20"/>
	    <br /><br />
	
		<?php if(!empty($this->messagesEmailActuel)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?=$this->messagesEmailActuel;?><br />
		</div>
		<?php endif; ?>
	    <label for="title">Adresse mail actuelle</label><br />
	    <input type="text" name="email_actuel_braldun" value="<?=$this->escape($this->email_actuel_braldun);?>" size="25" maxlength="100"/> 
	    
	    <br /><br />
		<?php if(!empty($this->messagesEmailNouveau)) :?> 
		<div class="message_erreur" id="message_erreur"> 
		<?php foreach($this->messagesEmailNouveau as $message) :?>
			<?=$message;?><br />
		<?php endforeach; ?>
		</div>
		<?php endif; ?>
	    <label for="title">Nouvelle adresse mail</label><br />
	    <input type="text" name="email_nouveau_braldun" value="<?=$this->escape($this->email_nouveau_braldun);?>" size="25" maxlength="100"/> 
	    
		<?php if(!empty($this->messagesEmailConfirm)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?=$this->messagesEmailConfirm;?><br />
		</div>
		<?php endif; ?>
		<br /><label for="title">Confirmation nouvelle adresse mail</label><br />
	    <input type="text" name="email_confirm_braldun" value="<?=$this->escape($this->email_confirm_braldun);?>" size="25" maxlength="100"/>      
		<br /><br />
		
		<div id="formbutton">
		<input type="submit" class='button1' name="Modifier" value="Modifier" /> 
		<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/Parametres/'"/>
		</div>
		</div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>