<?php echo $this->render('header.phtml'); ?>

<form id="form_description" action="/Parametres/images" method="post">
<div class="box_parametres">
<div class="inner">
	<div class="titrea textalic titreasize0">Mes Param&egrave;tres</div>
    <div class="titrea textalic titreasizea">Changer d'avatar / de blason</div>
	&nbsp;
	<div class="contenu">
	<div class="box_contenu1 textalic">
		
		<div class="titre textalic textsizec">Mode d'emploi</div><br />
		Pour indiquer un avatar et un blason, vous devez enregistrer vos images sur un site web, puis
		indiquer ici le lien de l'image.<br /> Exemple de site web pouvant stocker vos images : 
		<a href="http://imageshack.us">http://imageshack.us</a><br />
		<br />
		Les images doivent &ecirc;tre <u>strictement</u> de la taille indiqu&eacute;e ci-dessous et au format
		gif, png ou jpg (jpg, jpeg, jpe).
		
		<br /><br />
		Exemple : http://www.image.com/monavatar.gif
		<br /><br />
		
		<div class="titre textalic textsizec">L'Avatar</div><br />
		L'avatar doit &ecirc;tre au format 110px (largeur) x 110px (hauteur). <br/>
		
		<?php if ($this->urlAvatarValide == false) : ?>
			<?php echo Bral_Helper_Image::afficherErreur();?>
		<?php endif; ?>
		<input type='text' id='valeur_1' name='valeur_1' value='<?php echo $this->user->url_avatar_braldun ?>' size="50" maxlength="200">
		
		<div class="titre textalic textsizec">Le Blason</div><br />
		Le blason doit &ecirc;tre au format 300px (largeur) x 400px (hauteur). <br/>
		
		<?php if ($this->urlBlasonValide == false) : ?>
			<?php echo Bral_Helper_Image::afficherErreur();?>
		<?php endif; ?>
		
		<input type='text' id='valeur_2' name='valeur_2' value='<?php echo $this->user->url_blason_braldun ?>' size="50" maxlength="200">
		<br />
		
		<input type="submit" class='button1' id="bouton_valider" value="Valider" />
		<input type="button" class='button1' id="bouton_annuler" value="Annuler" onclick="javascript:document.location.href='/Parametres/'" />
		
		<br /><br />
		<table class="table_liste" style="width:90%">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th>Avatar</th>
				<th>Blason</th>
			  </tr>
			</thead>
			<tbody>
				<tr class="table_liste">
				  <td class="table_liste"><?php echo Bral_Helper_Image::afficherAvatar($this->user->url_avatar_braldun); ?></td>	
				  <td class="table_liste"><?php echo Bral_Helper_Image::afficherBlason($this->user->url_blason_braldun); ?></td>	
				</tr>
			</tbody>
		</table>
	  <br />
	   	</div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>