<?php echo $this->render('header.phtml'); ?>

<form id="form_description" action="/parametres/images" method="post">
<div class="box_parametres">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<ul class="titre textalia textsizea">Mes Param&egrave;tres</ul>
    <ul class="titre textalib textsizeb">Changer d'avatar / de blason</ul>
	&nbsp;
	<div class="contenu">
	<ul class="box_contenu1 textalic">
		
		<ul class="titre textalic textsizec">Mode d'emploi</ul><br />
		Pour indiquer un avatar et un blason, vous devez enregistrer vos images sur un site web, puis
		indiquer ici le lien de l'image.<br /> Exemple de site web pouvant stocker vos images : 
		<a href="http://imageshack.us">http://imageshack.us</a><br />
		<br />
		Les images doivent &ecirc;tes strictement de la taille indiqu&eacute; ci-dessous et au format
		gif, png ou jpg (jpg, jpeg, jpe).
		
		<br /><br />
		Exemple : http://www.image.com/monavatar.gif
		<br /><br />
		
		<ul class="titre textalic textsizec">L'Avatar</ul><br />
		L'avatar doit &ecirc;tre au format 110px × 110px. <br/>
		
		<? if ($this->urlAvatarValide == false) : ?>
			<?=Bral_Helper_Image::afficherErreur();?>
		<? endif; ?>
		<input type='text' id='valeur_1' name='valeur_1' value='<?=$this->user->url_avatar_hobbit ?>' size="50" maxlength="200">
		
		<ul class="titre textalic textsizec">Le Blason</ul><br />
		Le blason doit &ecirc;tre au format 300px × 400px. <br/>
		
		<? if ($this->urlBlasonValide == false) : ?>
			<?=Bral_Helper_Image::afficherErreur();?>
		<? endif; ?>
		
		<input type='text' id='valeur_2' name='valeur_2' value='<?=$this->user->url_blason_hobbit ?>' size="50" maxlength="200">
		<br />
		
		<input type="submit" class='button1' id="bouton_valider" value="Valider" />
		<input type="button" class='button1' id="bouton_annuler" value="Annuler" onClick="javascript:document.location.href='/parametres/'" />
		
		<br /><br />
		<table class="table_liste" style="width:90%">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th>Avatar</th>
				<th>Blason</th>
			  </tr>
			</thead>
			<tbody>
				<tr class="table_liste">
				  <td class="table_liste"><?=Bral_Helper_Image::afficherAvatar($this->user->url_avatar_hobbit); ?></td>	
				  <td class="table_liste"><?=Bral_Helper_Image::afficherBlason($this->user->url_blason_hobbit); ?></td>	
				</tr>
			</tbody>
		</table>
	  <br />
	   	</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>