<?php echo $this->render('header.phtml'); ?>
<div class="box_pamaretres">
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
<div class="inner">
    <ul class="titre textalic textsizea">Mes Param&egrave;tres</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br>
			<? if (!empty($this->message)): ?>
				<?=$this->message; ?><br><br>
			<? endif; ?>
			<input type="button" class='button1' value="Changer de mot de passe" onClick="javascript:document.location.href='/parametres/motdepasse'"/><br>
			<input type="button" class='button1' value="Changer d'adresse mail" onClick="javascript:document.location.href='/parametres/email'"/>
			<br><br>
		</ul>
	</div>
	&nbsp;
</div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
</div>
<?php echo $this->render('footer.phtml'); ?>