<?php echo $this->render('header.phtml'); ?>
<div class="box_pamaretres">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Mes Param&egrave;tres</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br>
			<? if (!empty($this->message)): ?>
				<?=$this->message; ?><br><br>
			<? endif; ?>
			<input type="button" class='button1' value="Changer de mot de passe" onClick="javascript:document.location.href='/parametres/motdepasse'"/><br>
			<input type="button" class='button1' value="Changer d'adresse mail" onClick="javascript:document.location.href='/parametres/email'"/>
			<br><br>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>