<?php echo $this->render('header.phtml'); ?>

<form action="/parametres/motdepasse" method="post">
<div class="box_parametres">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
	<ul class="titre textalia textsizea">Mes Param&egrave;tres</ul>
    <ul class="titre textalib textsizeb">Changer d'adresse email</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />

		<?php if(!empty($this->messagesPasswordActuel)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?=$this->escape($this->messagesPasswordActuel); ?><br />
			</div>
		<? endif; ?>
		<label for="title">Mot de Passe Actuel</label><br />
	    <input type="password" name="password_actuel_hobbit" value="" size="25" maxlength="20"/>
	    <br /><br />
	    
		<?php if(!empty($this->messagesPasswordNouveau)) :?>
			<div class="message_erreur" id="message_erreur"> 
			<?php foreach($this->messagesPasswordNouveau as $message) :?>
				<?=$this->escape($message);?><br />
			<?php endforeach; ?>
			</div>
		<?php endif; ?>
	    <label for="title">Nouveau Mot de Passe</label><br />
	    Entre 5 et 20 caract&egrave;res<br />
	    <input type="password" name="password_nouveau_hobbit" value="" size="25" maxlength="20"/>
		
		<?php if(!empty($this->messagesPasswordConfirm)) :?> 
			<div class="message_erreur" id="message_erreur"> 
				<?=$this->escape($this->messagesPasswordConfirm);?><br />
			</div>
		<?php endif; ?>
	    <br /><label for="title">Confirmation du nouveau Mot de Passe</label><br />
	    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
		<br /><br />
		
		<div id="formbutton">
		<input type="submit" class='button1' name="Modifier" value="Modifier" /> 
		<input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/parametres/'"/>
		</div>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>
