<?php echo $this->render('header.phtml'); ?>
<div class="box_pamaretres">
<div class="box_titre1">Changement de mot de passe</div><br />
<div><br>
<form action="<?=$this->baseUrl ?>/parametres/motdepasse" method="post">

	<?php if(!empty($this->messagesPasswordActuel)) :?>
		<div class="message_erreur" id="message_erreur"> 
		<?=$this->escape($this->messagesPasswordActuel); ?><br>
		</div>
	<? endif; ?>
	<label for="title">Mot de Passe Actuel</label><br>
    <input type="password" name="password_actuel_hobbit" value="" size="25" maxlength="20"/>
    <br><br>
    
	<?php if(!empty($this->messagesPasswordNouveau)) :?>
		<div class="message_erreur" id="message_erreur"> 
		<?php foreach($this->messagesPasswordNouveau as $message) :?>
			<?=$this->escape($message);?><br>
		<?php endforeach; ?>
		</div>
	<?php endif; ?>
    <label for="title">Nouveau Mot de Passe</label><br>
    Entre 5 et 20 caract&egrave;res<br>
    <input type="password" name="password_nouveau_hobbit" value="" size="25" maxlength="20"/>
	
	<?php if(!empty($this->messagesPasswordConfirm)) :?> 
		<div class="message_erreur" id="message_erreur"> 
			<?=$this->escape($this->messagesPasswordConfirm);?><br>
		</div>
	<?php endif; ?>
    <br><label for="title">Confirmation du nouveau Mot de Passe</label><br>
    <input type="password" name="password_confirm_hobbit" value="" size="25" maxlength="20"/>
	<br><br>
	
	<div id="formbutton">
	<input type="submit" name="add" value="Modifier" /> <input type="button" name="add" value="Annuler" onClick="javascript:document.location.href='/parametres/'"/>
	</div>
</form>
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>
