<?php echo $this->render('header.phtml'); ?>

<form id="form_partage" action="/Parametres/partage" method="post">
<div class="box_parametres">
<div class="inner">
	<ul class="titre textalic textsizea">Contacter les enquêteurs</ul>
    <ul class="titre textalic textsizeb">Signaler un partage de connexion</ul>
	&nbsp;
	<div class="contenu">
	<ul class="box_contenu1 textalic">
	
	<? if ($this->erreurBraldun) : ?>
		Une erreur est survenue. Veuillez bien renseigner le n° de Braldun avec lequel vous partagez la connexion.<br />
		<br /><br />
		<input type="button" class='button1' name="Retour" value="Retour" onClick="javascript:document.location.href='/Parametres/partage'"/>
		
	<? elseif ($this->idPartage != null) : ?>
		Votre partage est bien signalé. Un enquêteur vous contactera par mail si besoin.
		<br /><br />
		<input type="button" class='button1' name="Retour" value="Retour" onClick="javascript:document.location.href='/Parametres/'"/>
		 
	<? else: ?>
	   	<table width='70%' align='center'>
 		<tr>
 		<td style='text-align:justify'>
 		
			Vous devez signaler par ce formulaire uniquement les comptes appartenant à des gens qui habitent sous le même toit et/ou partagent la même connexion.
			<br /><br />
			A défaut d'enregistrement, un partage de connexion risque d'être considéré comme du multi-comptes et traité comme tel par les Enquêteurs.
	
	 		</td></tr>
	 		</table>
			<br />
			Un enquêteur prendra contact avec vous par mail si besoin ensuite.
			
			<br /><br />
		 
		 Braldun concerné : 
		<input type="text" name="recherche_valeur_1_voir" size='40' id="recherche_valeur_1_voir" value="Recherche Braldun - Entrez un nom" onFocus='this.value=""; activerRechercheAdminBraldun("valeur_1_voir");' />
		<input type="hidden" name="recherche_valeur_1_voir_actif" id="recherche_valeur_1_voir_actif" value="0" />
		<div class="recherche" id="recherche_valeur_1_voir_update" ></div> <img src="/public/images/loupe.gif" />
		<span id="indicateur_recherche_valeur_1_voir" style="display: none"><img src="/public/images/wait.gif" alt="Recherche..." /></span>
		<br />
	    Identifiant du Braldun (remplit automatiquement) <input type='text' name='id_braldun' id='id_braldun' value='' size='5' readonly> 
	    <br /> <br />
		 Décrivez ici vos liens avec le joueur du Braldun cité ci-dessus  : <br />
		 <textarea rows='10' cols='80' name="message" id="message"></textarea>
		 <br /><br /></br>
		 <input type="button" class='button1' name="bouton_partage"  id="bouton_partage" onClick="if (parseInt($('id_braldun').value * 1) > 0 && $('message').value !='') { $('form_partage').submit(); } else { alert('Veuillez renseigner tous les champs') }" value="Envoyer" />
		 <input type="button" class='button1' name="Annuler" value="Annuler" onClick="javascript:document.location.href='/Parametres/'"/>
	
	 <? endif;?>
		
	 </ul>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>