<?php echo $this->render('header.phtml'); ?>

<form id="form_partage" action="/Parametres/partage" method="post">
<div class="box_parametres">
<div class="inner">
	<div class="titrea textalic titreasize0">Contacter les enquêteurs</div>
    <div class="titrea textalic titreasizea">Signaler un partage de connexion</div>
	&nbsp;
	<div class="contenu">
	<div class="box_contenu1 textalic">
	
	<?php if ($this->erreurBraldun) : ?>
		Une erreur est survenue. Veuillez bien renseigner le n° de Braldûn avec lequel vous partagez la connexion.<br />
		<br /><br />
		<input type="button" class='button1' name="Retour" value="Retour" onclick="javascript:document.location.href='/Parametres/partage'"/>
		
	<?php elseif ($this->idPartage != null) : ?>
		Votre partage est bien signalé. Un enquêteur vous contactera par mail si besoin.
		<br /><br />
		<input type="button" class='button1' name="Retour" value="Retour" onclick="javascript:document.location.href='/Parametres/'"/>
		 
	<?php else: ?>
	   	<table width='70%' align='center'>
 		<tr>
 		<td style='text-align:justify'>
 		
			Vous devez signaler par ce formulaire uniquement les comptes appartenant à des gens qui habitent sous le même toit et/ou partagent la même connexion.
			<br /><br />
			A défaut d'enregistrement, un partage de connexion risque d'être considéré comme du multi-compte et traité comme tel par les Enquêteurs.
	
	 		</td></tr>
	 		</table>
			<br />
			Un enquêteur prendra contact avec vous par mail si besoin ensuite.
			
			<br /><br />
		 
		 Braldûn concerné : 
		<input type="text" name="recherche_valeur_1_voir" size='40' id="recherche_valeur_1_voir" value="Recherche Braldûn - Entrez un nom" onFocus='this.value=""; activerRechercheAdminBraldun("valeur_1_voir");' />
		<input type="hidden" name="recherche_valeur_1_voir_actif" id="recherche_valeur_1_voir_actif" value="0" />
		<div class="recherche" id="recherche_valeur_1_voir_update" ></div> <img src="<?php echo $this->config->url->static?>/images/divers/loupe.gif" />
		<span id="indicateur_recherche_valeur_1_voir" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" alt="Recherche..." /></span>
		<br />
	    Identifiant du Braldûn (rempli automatiquement) <input type='text' name='id_braldun' id='id_braldun' value='' size='5' readonly> 
	    <br /> <br />
		 Décrivez ici vos liens avec le joueur du Braldûn cité ci-dessus  : <br />
		 <textarea rows='10' cols='80' name="message" id="message"></textarea>
		 <br /><br /></br>
		 <input type="button" class='button1' name="bouton_partage"  id="bouton_partage" onclick="if (parseInt($('#id_braldun').val() * 1) > 0 && $('#message').val() !='') { $('#form_partage').submit(); } else { alert('Veuillez renseigner tous les champs') }" value="Envoyer" />
		 <input type="button" class='button1' name="Annuler" value="Annuler" onclick="javascript:document.location.href='/Parametres/'"/>
	
	 <?php endif;?>
		
	 </div>
	</div>
	&nbsp;
</div>
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>