<div class="titre textalic textsizec"><?php echo $titre?></div>
<div class="titre textalic textsizee"><?php echo $sousTitre?></div>

<table class="table_liste">
	<thead class="table_liste">
	   <tr class="table_liste">
	  	<th>
	  		Braldûn
	  	</th>
	  	<th>
	  		Nombre de contrats
	  	</th>
	  </tr>
	</thead>
	<tbody>
	<?php if ($contrats != null): ?>
	  <?php $i = 0; 
	   foreach($contrats as $k => $v) :?>
	  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
	  		<td class="table_liste" width="50%"><?php echo Bral_Util_Lien::remplaceBaliseParNomEtJs("[b".$k."]")?></td>
	  		<td class="table_liste" width="50%"><?php echo $v["nombre"]?></td>
	  	</tr>
	  <?php endforeach; ?>
	<?php else: ?>
	   <tr class="table_liste0">
	   	<td colspan="2" align="center">
	   		Aucun contrat en cours.
	   	</td>
	   </tr>
	<?php endif; ?>
   </tbody>
</table>