<br />
<div class="titrea textalic titreasizea">Le Tableau des Recherchés</div>

<div class="inner">
	<br /> <br />
	<?php $contrats = $this->tabGredins;
	$titre = "Contrats de type Gredins";
	$sousTitre = "mettre KO un Redresseur de Torts"?>
	<?php include("contrats.phtml"); ?>
	<br /> <br /> <br />
	<?php $contrats = $this->tabRedresseurs;
	$titre = "Contrats de type Redresseurs de Torts";
	$sousTitre = "mettre KO un Gredin"?>
	<?php include("contrats.phtml"); ?>
</div>

