<br />
<div class="titre textalic textsizeb">
 Le Tableau des Recherchés
</div>

<table style="width:100%">
<tr>
	<td style="width:500px; border: 0px solid #791E1E;" valign="top">
			<div class="inner">
					<br /><br />
					<? $contrats = $this->tabGredins;
					$titre = "Contrats de type Gredins";
					$sousTitre = "mettre KO un Redresseur de Torts"?>
					<? include("contrats.phtml"); ?>
					<br /><br /><br />
					<? $contrats = $this->tabRedresseurs;
					$titre = "Contrats de type Redresseurs de Torts";
					$sousTitre = "mettre KO un Gredin"?>
					<? include("contrats.phtml"); ?>
			</div>
	</td>
</tr>
</table>
		

