<br>
<ul class="titre textalic textsizeb">
 Le Tableau des Recherchés
</ul>

<table style="width:100%">
<tr>
	<td style="width:500px; border: 0px solid #791E1E;" valign="top">
		<?=$this->render("commun/box_header.phtml"); ?>
			<div class="inner">
					<br><br>
					<? $contrats = $this->tabGredins;
					$titre = "Contrats de type Gredins";
					$sousTitre = "mettre KO un Redresseur de Tors"?>
					<? include("contrats.phtml"); ?>
					<br><br><br>
					<? $contrats = $this->tabRedresseurs;
					$titre = "Contrats de type Redresseurs de Tors";
					$sousTitre = "mettre KO un Gredin"?>
					<? include("contrats.phtml"); ?>
			</div>
		<?=$this->render("commun/box_bottom.phtml"); ?>
	</td>
</tr>
</table>
		

