<br />
<div class="box_contenu textalic">
	<div class="titre textalic textsizeb">
	Marché aux aliments
	</div><br />
	
<table width='100%'>
<tr>
<td>
	Filtre par comté: 
	<br />
	<select id="region" name="region" onChange="document.location.href = '/marchealiment/?regionselect='+this.value+'&alimentselect=<?=$this->alimentSelect?>&uid='+(new Date()).valueOf()">
	<? foreach($this->regions as $k => $e): ?>
		<option value="<?=$k?>" <?if ($this->regionSelect == $k): echo "selected" ; endif;?>><?=$e?></option>
	<? endforeach;?>
	</select>
</td>
<td>
	Filtre par aliment :
	<br />
	<select id="aliment" name="aliment" onChange="document.location.href = '/marchealiment/?regionselect<?=$this->regionSelect?>&alimentselect='+this.value+'&uid='+(new Date()).valueOf()">
	<? foreach($this->aliments as $k => $e): ?>
		<option value="<?=$k?>" <?if ($this->alimentSelect == $k): echo "selected" ; endif;?>><?=$e?></option>
	<? endforeach;?>
	</select>
</td>
</tr>
</table>

<br /><br />

<div id="mygrid_container" style="width:770px;height:650px;align:center"></div> 
<script>
	gridQString = '/marchealiment/renderxml?regionselect=<?=$this->regionSelect?>&alimentselect=<?=$this->alimentSelect?>&uid='+(new Date()).valueOf();
	function sortGridOnServer(ind,gridObj,direct){
	    mygrid.clearAll();
	    murl = gridQString+(gridQString.indexOf("?")>=0?"&":"?")+"orderby="+ind+"&direct="+direct;
	    mygrid.loadXML(murl);
	    mygrid.setSortImgState(true,ind,direct);
	    return false;
	}
	
	mygrid = new dhtmlXGridObject('mygrid_container');
	mygrid.setImagePath("/public/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygrid.setHeader("Comté,Date,Braldun,Echoppe,,Objet,Qualité,Recette,Bonus,Prix,Commentaire");
	mygrid.setInitWidths("60,55,100,80,40,115,60,70,47,65,*");
	mygrid.setColAlign("left,left,left,left,left,left,left,left,left,left,left");
	mygrid.setColTypes("ro,ro,link,ro,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setSkin("braldahim");
	mygrid.setColSorting("server,server,server,server,server,server");
	mygrid.attachEvent("onBeforeSorting",sortGridOnServer);
	mygrid.enableSmartRendering(true,100);
	mygrid.init();
	mygrid.loadXML(gridQString);
	mygrid.setSortImgState(true,1,"des");
</script>

</div>