Bonjour ! <br /><br />

Votre Braldûn <?php echo $this->braldun["prenom_braldun"] ?> <?php echo $this->braldun["nom_braldun"] ?> (N°<?php echo $this->braldun["id_braldun"] ?>) a été supprimé. <br /><br />

Soit vous n'avez jamais activé votre compte, soit vous ne l'avez pas joué depuis plus de <?php echo $this->nbJours?> jours.

Pour créer un nouveau braldun, rendez-vous ici : <br />
<a href="<?php echo $this->urlJeu ?>"><?php echo $this->urlJeu ?></a><br /><br />

A bientôt ! <br /><br />

--<br />
Les Maitres du jeu