Bonjour ! <br /><br />

Votre Braldûn vous réclame, corps et âme. <br /><br />

Il sera supprimé le <?=$this->dateSuppression?> si vous ne le jouez pas avant.
Si toutefois vous ne pouvez pas le jouer pendant plusieurs jours, nous vous conseillons de le mettre en hibernation.
En hibernation, votre Braldûn ne sera pas supprimé et n'apparaîtra pas dans le monde de Braldahim.
<br /><br />

Email : <?=$this->braldun["email_braldun"] ?> <br /><br />

Braldun : <?=$this->braldun["prenom_braldun"] ?> <?=$this->braldun["nom_braldun"] ?><br /><br />

Numero du Braldûn :<?=$this->braldun["id_braldun"] ?><br /><br />

Pour vous connecter, rendez-vous ici : <br />
<a href="<?=$this->urlJeu ?>"><?=$this->urlJeu ?></a><br /><br />

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?=$this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Les Maitres du jeu