Bonjour ! <br /><br />

Votre Braldûn vous réclame, corps et âme. <br /><br />

Il sera supprimé le <?php echo $this->dateSuppression?> si vous ne le jouez pas avant.
Si toutefois vous ne pouvez pas le jouer pendant plusieurs jours, nous vous conseillons de le mettre en hibernation.
En hibernation, votre Braldûn ne sera pas supprimé et n'apparaîtra pas dans le monde de Braldahim.
<br /><br />

Email : <?php echo $this->braldun["email_braldun"] ?> <br /><br />

Braldun : <?php echo $this->braldun["prenom_braldun"] ?> <?php echo $this->braldun["nom_braldun"] ?><br /><br />

Numero du Braldûn :<?php echo $this->braldun["id_braldun"] ?><br /><br />

Pour vous connecter, rendez-vous ici : <br />
<a href="<?php echo $this->urlJeu ?>"><?php echo $this->urlJeu ?></a><br /><br />

Si vous rencontrez un souci, merci d'indiquer ce qu'il se passe via l'adresse suivante : 
<?php echo $this->adresseSupport ?><br /><br />

Bon jeu ! <br /><br />

--<br />
Les Maitres du jeu