Bonjour ! 

Votre Braldûn <?php echo $this->braldun["prenom_braldun"] ?> <?php echo $this->braldun["nom_braldun"] ?> (N°<?php echo $this->braldun["id_braldun"] ?>) a été supprimé.

Soit vous n'avez jamais activé votre compte, soit vous ne l'avez pas joué depuis plus de <?php echo $this->nbJours?> jours. 

Pour créer un nouveau braldun, rendez-vous ici : <?php echo $this->urlJeu ?> 

A bientôt ! 

--
Les Maitres du jeu