<style type="text/css">

<? $coef = 7;
$largeur = $this->terrainCourant["x_max_soule_terrain"] - $this->terrainCourant["x_min_soule_terrain"];
$hauteur = $this->terrainCourant["y_max_soule_terrain"] - $this->terrainCourant["y_min_soule_terrain"];
?>

#terrain {
	width:<?=($largeur * $coef) ?>px;
	height:<?=($hauteur * $coef) ?>px;
	background-color: #6B8E23;
	position:relative;
	left:3em;
}

.ballon {
    width: 8px;
    height: 6px;
    background-color: #F4A460;
    border: 1px solid #8B0000;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    position:absolute;
    bottom:0px;
    margin:0px;
    cursor:pointer;
    left:<?= -4 + ($this->matchEnCours["x_ballon_soule_match"] - $this->terrainCourant["x_min_soule_terrain"]) * $coef ?>px; 
    top:<?= -3 + ($this->matchEnCours["y_ballon_soule_match"] - $this->terrainCourant["y_min_soule_terrain"]) * $coef ?>px; 
}

.bande {
	width:100%;
	height:6px;
	background-color: #9ACD32;
	position:absolute;
	margin:0px;
}
.haut {top:0px;}
.milieu {top:<?=(($hauteur/2 * $coef) - 2) ?>px;}
.bas {bottom:0px;}

.camp {
	width:100%;
	height:6px;
	position:absolute;
	margin:0px;
	
	filter:alpha(opacity=50);
	-moz-opacity:0.5;
	-khtml-opacity: 0.5;
	opacity: 0.5;
}

.equipeA {top:20%;}
.terrain {top:45%;}
.equipeB {bottom:20%;}

.joueur {
    width: 6px;
    height: 6px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    position:absolute;
    bottom:0px;
    margin:0px;
    cursor:pointer;
}

</style>


<div id="terrain">
<p class="bande haut"></p>
<p class="bande milieu"></p>
<p class="bande bas"></p>
<p class="camp terrain" style="color:#eeeeee">
	<?=$this->terrainCourant["nom_soule_terrain"]?>
	<br><br>
	Dimensions Terrain : <?=$this->terrainCourant["x_max_soule_terrain"] - $this->terrainCourant["x_min_soule_terrain"]?> x <?=$this->terrainCourant["y_max_soule_terrain"] - $this->terrainCourant["y_min_soule_terrain"]?>
</p>
<p class="camp equipeA" style="color:red">Camp équipe A :<br> <?=$this->equipes["equipea"]["nom_equipe"]?></p>
<p class="camp equipeB" style="color:blue">Camp équipe B :<br> <?=$this->equipes["equipeb"]["nom_equipe"]?></p>
<p class="ballon" title="Ballon en X:<?=$this->matchEnCours["x_ballon_soule_match"]?>, Y:<?=$this->matchEnCours["y_ballon_soule_match"]?>"></p>
<?php $equipe = $this->equipes["equipea"]; $backgroundColor="red"; $nomEquipe="Équipe A";include("carteequipe.phtml")?>
<?php $equipe = $this->equipes["equipeb"]; $backgroundColor="blue"; $nomEquipe="Équipe B"; include("carteequipe.phtml")?>
</div>