<?
// On trie suivant X puis Y puis equipe
foreach ($joueurs as $key => $row) {
	$x[$key] = $row['x_braldun'];
	$y[$key] = $row['y_braldun'];
	$eq[$key] = $row['camp_soule_equipe'];
}
array_multisort($x, SORT_ASC, $y, SORT_ASC, $eq, SORT_ASC, $joueurs);

$xini = null;
$yini = null;
$colini = null;
$eqini = null;
foreach($joueurs as $j):
  if ($j["est_ko_braldun"] == "non") :
  	  if ($j["camp_soule_equipe"] == "a") { 
  	  	$backgroundColor = "red";
  	  	$nomEquipe = "&Eacute;quipe A";
  	  }
  	  else {
  	  	$backgroundColor = "blue";
  	  	$nomEquipe = "&Eacute;quipe B";
  	  }
  	  if ($j["x_braldun"] == $xini && $j["y_braldun"] == $yini){
  	  	if ($colini != $backgroundColor){
  	  		$backgroundColor = "purple";
  	  	}
  	  	if ($nomEquipe != $eqini) {
  	  		$textBraldun .= "<br><center>".$nomEquipe."</center>";
  	  	}
  	  }
  	  else {
  	  	$textBraldun = "<br><center>".$nomEquipe."</center>";
  	  }
	  
  	  $eqini = $nomEquipe;
  	  $textBraldun .= '<label class=\\\'alabel profil\\\' onClick=ouvrirProfilH('.$j["id_braldun"].'); title=\\\'Voir le profil\\\' >'.addslashes($j["prenom_braldun"]).' '.addslashes($j["nom_braldun"]).' ('.$j["id_braldun"].')</label>, niv.'.$j["niveau_braldun"];
  	  $textBraldun .= ' <img src=\\\'/public/images/puce_event.gif\\\' title=\\\'Voir les événements\\\' border=\\\'0\\\' onClick=ouvrirEvenementsH('.$j["id_braldun"].'); style=\\\'cursor:pointer\\\'/> ';
	  $textBraldun .= ' <img src=\\\'/public/images/uddeim/env.gif\\\' title=\\\'Envoyer un message\\\' alt=\\\'Ecrire\\\' border=\\\'0\\\' onClick=ecrireMessage('.$j["id_braldun"].'); style=\\\'cursor:pointer\\\'/><br> ';
	  $title = "Position : x=".$j['x_braldun'].", y=".$j['y_braldun'];
  	  $xini = $j["x_braldun"];
  	  $yini = $j["y_braldun"];
  	  $colini = $backgroundColor;
  	  
  	  echo "<div class='braltip'>";
  	  echo Bral_Helper_Tooltip::render($textBraldun, $title);
  	  echo '<span class="joueur" style=\'';
	  echo "left:".(-3 + ($j["x_braldun"] - $this->matchEnCours["x_min_soule_terrain"]) * $coef)."px;"; 
	  echo "top:".(-3 + ($this->matchEnCours["y_max_soule_terrain"] - $j["y_braldun"]) * $coef)."px;";
	  echo "background-color:".$backgroundColor.";";
	  echo ";'></span>";
	  echo "</div>";
  endif;
endforeach; ?>