<style type="text/css">

<?php $coef = 7;
$largeur = $this->terrainCourant["x_max_soule_terrain"] - $this->terrainCourant["x_min_soule_terrain"];
$hauteur = $this->terrainCourant["y_max_soule_terrain"] - $this->terrainCourant["y_min_soule_terrain"];
if ($this->matchEnCours["x_ballon_soule_match"] != null && $this->matchEnCours["y_ballon_soule_match"]) :
	$xBallon = $this->matchEnCours["x_ballon_soule_match"];
	$yBallon = $this->matchEnCours["y_ballon_soule_match"];
else : 
	$xBallon = $this->porteur["x_braldun"];
	$yBallon = $this->porteur["y_braldun"];
endif;
?>

#terrain {
	width:<?php echo ($largeur * $coef) ?>px;
	height:<?php echo ($hauteur * $coef) ?>px;
	background-color: #6B8E23;
	position:relative;
	left:3em;
}

.ballon {
    width: 8px;
    height: 6px;
    background-color: #F4A460;
    border: 1px solid #8B0000;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    position:absolute;
    bottom:0px;
    margin:0px;
    cursor:pointer;
    left:<?php echo  -4 + ($xBallon - $this->terrainCourant["x_min_soule_terrain"]) * $coef ?>px; 
    top:<?php echo  -3 + ($this->terrainCourant["y_max_soule_terrain"] - $yBallon) * $coef ?>px; 
}

.bande {
	width:100%;
	height:6px;
	background-color: #9ACD32;
	position:absolute;
	margin:0px;
}
.haut {top:0px;}
.milieu {top:<?php echo (($hauteur/2 * $coef) - 2) ?>px;}
.bas {bottom:0px;}

.camp {
	width:100%;
	height:6px;
	position:absolute;
	margin:0px;
	
	filter:alpha(opacity=50);
	-moz-opacity:0.5;
	-khtml-opacity: 0.5;
	opacity: 0.5;
}

.equipeA {top:20%;}
.terrain {top:45%;}
.equipeB {bottom:20%;}

.joueur {
    width: 6px;
    height: 6px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    position:absolute;
    bottom:0px;
    margin:0px;
    cursor:pointer;
}

</style>


<div id="terrain">
<p class="bande haut"></p>
<p class="bande milieu"></p>
<p class="bande bas"></p>
<p class="camp terrain" style="color:#eeeeee">
	<?php echo $this->terrainCourant["nom_soule_terrain"]?>
	<br /><br />
	Dimensions Terrain : <?php echo $this->terrainCourant["x_max_soule_terrain"] - $this->terrainCourant["x_min_soule_terrain"]?> x <?php echo $this->terrainCourant["y_max_soule_terrain"] - $this->terrainCourant["y_min_soule_terrain"]?>
</p>
<p class="camp equipeA" style="color:red">Camp équipe A :<br /> <?php echo $this->equipes["equipea"]["nom_equipe"]?></p>
<p class="camp equipeB" style="color:blue">Camp équipe B :<br /> <?php echo $this->equipes["equipeb"]["nom_equipe"]?></p>
<p class="ballon" title="Ballon en X:<?php echo $xBallon?>, Y:<?php echo $yBallon?>"></p>
<?php $joueurs = $this->joueurs; include("carteequipe.phtml");?>
</div>