
<table class="table_liste" style="width:100%">
	<thead class="table_liste">
	  <tr class="table_liste">
		<th><?=$nomEquipe?> : <?=$equipe["nom_equipe"]?></th>
	  </tr>
	</thead>
	<tbody>
		<? if ($equipe["joueurs"] != null && count($equipe["joueurs"]) > 0): ?>
		  	<? 
		  	$i = 0; 
		  	foreach($equipe["joueurs"] as $j): ?>
		  		<tr class="table_liste<?=($i % 2);$i++; ?>">
			  		<td class="table_liste" nowrap>
			  		<a onClick="javascript:ouvrirWin('/voir/hobbit/?hobbit=<?=$j["id_hobbit"]?>');" title="Cliquez pour voir le profil">
			  		<?=$j["prenom_hobbit"]?> <?=$j["nom_hobbit"]?> (<?=$j["id_hobbit"]?>)
			  		</a>
			  		<? if ($this->matchEnCours != null) : ?>
			  		en <span title="Position X, Y" style="cursor:pointer"><?=$j["x_hobbit"]?>, <?=$j["y_hobbit"]?></span>
			  		<? endif;?>
		  		</tr>
		  	<? endforeach; ?>
		<? else: ?>
		Aucun joueur
		<? endif; ?>
  	</tbody>
</table>