<div style="height:300px;overflow: auto; min-height: 60px;">
<br>
	<table class="table_liste">
		<thead class="table_liste">
		  <tr class="table_liste">
		  	<th colspan="3">
		  		&Eacute;v&eacute;nements du match n&deg;<?=$this->matchEnCours["id_soule_match"]?>
		  	</th>
		  </tr>
		</thead>
		<? if ($this->evenements != null): ?>
		<tbody>
	  <? $i = 0; 
	  foreach($this->evenements as $e): ?>
	  	<tr class="table_liste<?=($i % 2);$i++; ?>">
	  		<td class="table_liste"><?=$e["date_evenement"]?></td>
	  		<td class="table_liste"><?=$e["details_evenement"]?></td>
	  	</tr>
	  <? endforeach; ?>
	  </tbody>
	   <? else: ?>
	   <tr class="table_liste">
	   	<td colspan="5">
	   		Aucun &eacute;v&eacute;nement
	   	</td>
	   </tr>
	   <? endif; ?>
	</table>
</div>