<br /><br />

<div class="titre textalic textsizec">Messages de l'équipe</div>

<input type="button" class='button1' name="rafraichir_soule" id="rafraichir_soule" value="Rafraîchir" onclick="Javascript:_get_('/interface/load/?box=box_soule');"/>

<table class="table_liste" style="width:80%;text-align:center">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>Date</th>
	  	<th>Braldûn</th>
		<th width='70%'>Message</th>
	  </tr>
	</thead>
	 	<tr class="table_liste">
   		<td colspan="3">
		<ul id="navigation" style="width:100%;text-align:center" >
			<li id="pocheSouleMessage">
			<h3 id="pocheSouleMessage-head" class="head" onclick="maccordion(this);" >
			<input type="button" class='button1' name="nouveau_msg" id="nouveau_msg" value="Nouveau Message"/> 
			</h3>
			<? if ($this->matchEnCours != null) : ?>
			<ul id="pocheSouleMessage-body" style="display:none">
			<? else: ?>
			<ul id="pocheSouleMessage-body" style="display:block">
			<? endif;?>
				<li>
					<?php include("nouveau.phtml")?>
				</li>
			</ul>
			</li>
		</ul>
		</td>
   	</tr>

  <? if (count($this->souleMessages) > 0): ?>
	<tbody>
  	<? $i = 0; 
  	foreach($this->souleMessages as $e): ?>
  		<tr class="table_liste<?=($i % 2);$i++; ?>">
  			<td class="table_liste"><?=$e["date"]?>&nbsp;</td>
  			<td class="table_liste"><?=$e["braldun"]?>&nbsp;</td>
	  		<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($e["message"]);?>&nbsp;</td>
  		</tr>
  	<? endforeach; ?>
  	</tbody>
   <? else: ?>
   	<tr class="table_liste">
   		<td colspan="3">
   			Aucun message
   		</td>
   	</tr>
<? endif; ?>
</table>
