<form name="myForm" id="myForm">
	<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='-1'>
	<input type='hidden' name='valeur_1' id='valeur_1' value='envoi' />

<br /><br />

	<?=Bral_Helper_BBBoutons::affiche('valeur_messagesoule', 1000)?>
	
	<span>Message</span><br />
	<textarea name="valeur_messagesoule" id="valeur_messagesoule" class="inputbox" rows="10" cols="60" 
	onkeydown="textCount($('valeur_messagesoule'),$('characterstypedsoule'),1000);" 
	onkeyup="textCount($('valeur_messagesoule'),$('characterstypedsoule'),1000);if ($('valeur_messagesoule').value.length > 2) {$('envoyer_msg_soule').disabled=false} else {$('envoyer_msg_soule').disabled=true}"></textarea>
	
	<br />
	<input style="background-color: lightgray;" readonly="readonly" name="characterstypedsoule" id="characterstypedsoule" size="4" maxlength="4" value="1000" type="text"> Caract&egrave;res restants<br />
	<input type="button" class='button1' name="envoyer_msg_soule" id="envoyer_msg_soule" value="Envoyer" onClick="Javascript:$('nb_valeurs').value=1;$('valeur_1').value=encodePlus($('valeur_messagesoule').value);_get_('/soule/doaction?caction=do_soule_message', true);" disabled/> 
</form>
