Vous avez amélioré avec succès le bâtiment suivant : <br />

<?php echo $this->nomLieu?>.<br />

Le bâtiment est maintenant en construction vers le niveau <?php echo $this->niveauSuivant?>.<br /><br />

Pour le construire complètement, chaque Braldûn de la communauté peut aller sur le bâtiment et
utiliser l'action "Construire un bâtiment" pour faire progresser la construction.<br /><br />
La progression de chaque construction est visible dans l'onglet "Communauté". <br /><br />
