<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>

<?php if ($this->batiment == null) :?>
<br /><br />
	Il n'y a aucun bâtiment à construire où vous êtes.
<?php else : ?>

<div class="titre textalic textsizec"><?php echo $this->batiment['lieu']['nom_lieu']?></div><br />


<table class="table_liste" style='width:200px'>
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th colspan='3'>État de la construction vers le niveau <?php echo $this->batiment['lieu']['niveau_prochain_lieu']?></th>
	  </tr>
	</thead>
	<tbody>
		<tr class="table_liste0">
			<td class="table_liste" nowrap>
				<?php echo Bral_Helper_Communaute::afficheBarreConstruction($this->batiment['couts']['cout_pa'], $this->batiment['lieu']["nb_pa_depenses_lieu"]); ?>
				<?php echo Bral_Helper_Communaute::afficheBarreConstruction($this->batiment['couts']['cout_castar'], $this->batiment['lieu']["nb_castars_depenses_lieu"]); ?>
			</td>
			<td class="table_liste" nowrap>
				<?php echo $this->batiment['lieu']["nb_pa_depenses_lieu"]." / ". $this->batiment['couts']['cout_pa'] ?> PA
				<br />
				<?php echo $this->batiment['lieu']["nb_castars_depenses_lieu"]." / ".$this->batiment['couts']['cout_castar'] ?> Castars
			</td>
		</tr>
	</tbody>
</table>

<br />
Vous avez <?php echo $this->user->castars_braldun ?> castar<?php if ($this->user->castars_braldun > 1): echo 's'; endif; ?> 
 et <?php echo $this->user->pa_braldun ?> PA restant<?php if ($this->user->pa_braldun > 1): echo 's'; endif; ?>.<br />

<br /><br />

Participation à la construction du bâtiment (1 PA minimum) : 
 <table width='100%' align='center'>
    <tr>
    <th class=''>PA</th>
    <th class=''>&nbsp;</th>
    <th class=''>Castars</th>
    </tr>
   	<tr>
   		<td>
	   		<select id='valeur_1' name='valeur_1' onchange="javascript:if ($('#valeur_1').val() ==-1){$('#bouton_construirebatiment').attr('disabled', true) } else { $('#bouton_construirebatiment').attr('disabled',false) }">
			<option value='-1'>(Choisis)</option>
			<?php foreach ($this->tabPA as $h): ?>
			<option value='<?php echo $h?>'><?php echo $h?></option>
			<?php endforeach; ?>
			</select>
   		</td>
   		<td>Et</td>
   		<td>
   			<input type='text' maxlength='7' size='7' name='valeur_2' id='valeur_2' value='0' onkeypress="chiffres(event);"  onkeyup="if (this.value > <?php echo $this->user->castars_braldun?>) this.value=<?php echo $this->user->castars_braldun?>">
   		</td>
   	</tr>
   </table>
   
<br /><br />
<input type='button' class='button1' id='bouton_construirebatiment'  value='Construire un bâtiment !' onclick='this.disabled=true;_get_("/communaute/doaction?caction=do_communaute_construirebatiment");' disabled>
  
 <?php endif;?>
 
 <br /><br />