Vous avez dépensé <?php echo $this->participationPA ?> PA et 
 <?php echo $this->participationCastars ?> castar<?php if ($this->participationCastars > 1): echo 's'; endif; ?>

dans la construction du bâtiment 
<?php echo $this->nomLieu?>.<br /><br />

<?php if ($this->niveauAtteint) : ?>
	<b>Félicitations, le bâtiment est totalement construit !</b>
<?php else: ?>
	Le bâtiment est toujours en construction vers le niveau <?php echo $this->batiment['lieu']['niveau_prochain_lieu']?>.<br /><br />
<?php endif;?>
