Vous avez initialisé avec succès le bâtiment suivant : <br />

<?php echo $this->nomLieu?>, de niveau 0.<br />

Le bâtiment est automatiquement en construction vers le niveau 1.<br /><br />

Pour le construire complètement, chaque Braldûn de la communauté peut aller sur le bâtiment et
utiliser l'action "Construire un bâtiment" pour faire progresser la construction.<br /><br />
La progression de chaque construction est visible dans l'onglet "Communauté". <br /><br />

Une fois la construction niveau 1 terminée, le bâtiment offrira de nouvelles possibilités pour la communauté, ainsi que des points d'influence.<br /><br />
