<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>

<b>Informations</b> : vous ne pouvez pas construire deux bâtiments de même type.<br />
Seuls les tenanciers, adjoints et gestionnaires peuvent initialiser un nouveau bâtiment. <br />

<b>Coût en PA de l'initialisation du bâtiment</b> : <?php echo $this->nb_pa?>. <br />

<br />
Une fois initialisé, le bâtiment sera au niveau 0 et automatiquement en construction vers le niveau 1.<br />

Ensuite, pour le construire complètement, chaque Braldûn de la communauté pourra aller sur le bâtiment et
utiliser l'action "Construire un bâtiment" pour faire progresser la construction.<br />
La progression de chaque construction est visible dans l'onglet "Communauté". <br />

Une fois la construction terminée, le bâtiment offrira de nouvelles possibilités pour la communauté, ainsi que des points d'influence.<br /><br />


<?php if ($this->typeLieux == null || count($this->typeLieux) <= 0) :?>
	Vous avez déjà construit tous les types de bâtiments possibles. <br />

<?php else : ?>

Choisissez un type de bâtiment : <br />
<select name='valeur_1' id="valeur_1">
	<?php foreach ($this->typeLieux as $t) : ?>
		<option value="<?php echo $t["type"]["id_type_lieu"]?>" <?php echo $t["selected"]?>><?php echo $t["type"]["nom_type_lieu_communaute"]?> : <?php echo $t["type"]["nom_type_lieu"]?></option>
	<?php endforeach; ?>
</select>

<br /><br />
Choisissez une position pour le bâtiment : 

<table align='center'>
   <tr>
     <th>Position [x;y]</th>
   </tr>
   <tr>
     <td>
     <table class='comp_marcher_position'>
     	<?php $col=null ?>
		<?php foreach ($this->tableau as $case) : ?>

		<?php if ($case["change_level"] == 1 && $col == "ok") :
          echo "</tr>";
		 endif; ?>
		<?php if ($case["change_level"] == true) : 
			$col="ok"; ?>
                  <tr>
		<?php endif; ?>
          <td class='comp_marcher_position_td' nowrap>
           <?php echo $case["display"] ?><br />

		<?php if ($case["valid"] == true) : ?>
            <input type='radio' name='valeur_2' id='valeur_2' value='<?php echo $case["x_offset"]."h".$case["y_offset"] ?>' <?php echo $case["default"]?>>
		<?php else: ?>
			&nbsp;
		<?php endif; ?>
          </td>
       <?php endforeach; ?>
       </tr>
     </table>
     </td>
    </tr>
  </table>
  
  <input type='button' class='button1' value='Initialiser un bâtiment !' onclick='this.disabled=true;_get_("/communaute/doaction?caction=do_communaute_initialiserbatiment");'>
  
 <?php endif;?>