<?php echo $this->render('header.phtml'); ?>
<form action="/charte/accepter" method="post">

<div class="box_gardiennage">
<div class="inner">
	<ul class="titre textalic textsizea">Sondage</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    <br />
      	Merci d'avoir répondu. <br />
      	<br /><br />
			<input type="button" name="deconnexion" class='button1' value="Retour au jeu" onClick="javascript:document.location.href='/interface'"/>
		</ul>
	</div>
	&nbsp;
</div>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

