<?php echo $this->render('header.phtml'); ?>
<form action="/sondage/" method="post">

<div class="box_gardiennage">
<div class="inner">
	<div class="titre textalic textsizea">Sondage</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    <br />
      	Merci de répondre au sondage suivant : <br /><br />
      	
      	<?php echo nl2br($this->sondage["question_sondage"])?>
      	
      	<?php if ($this->erreur != "") : ?>
      	<br /><br />Une erreur est survenue : <br />
      	<?php echo $this->erreur?><br /><br />
      	<?php endif;?>
      	
      	<br /><br />
      	
		Serez-vous présent à l'IRL le samedi 3 juillet 2010?
		
		<select name='reponse_1'>
				<option value='-1'>Choisir une réponse</option>
				<option value='oui'>Oui</option>
				<option value='non'>Non</option>
		</select><br /><br />
		
		Serez-vous présent à l'IRL le dimanche 4 juillet 2010 ?
		
		<select name='reponse_2'>
				<option value='-1'>Choisir une réponse</option>
				<option value='oui'>Oui</option>
				<option value='non'>Non</option>
		</select><br /><br />
		
		Souhaitez-vous dormir sur place ?
		
		<select name='reponse_3'>
				<option value='-1'>Choisir une réponse</option>
				<option value='oui'>Oui</option>
				<option value='non'>Non</option>
		</select><br /><br />
		
      	Tout autre commentaire à transmettre pour l'organisation 
      	(Si toutefois vous ne savez pas encore si vous venez ou non par exemple) :<br />
		<textarea name="commentaire" id="commentaire" class="inputbox" rows="10" cols="60" onkeydown="textCount($('#texte_abus'),$('#characterstyped'),2500);" onkeyup="textCount($('#commentaire'),$('#characterstyped'),2500);"></textarea>
		
		<br />
		<input style="background-color: #31401A;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="2500" type="text"> Caract&egrave;res restants<br />
		
	
      	<br /><br />
		<div id="formbutton">
			<input type="submit" name="repondre" class='button1' value="Répondre" />
			<input type="button" name="deconnexion" class='button1' value="Ne pas répondre et se d&eacute;connecter" onclick="javascript:document.location.href='/auth/logout'"/>
		</div>
		</div>
	</div>
	&nbsp;
</div>
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>

