<?php echo $this->render('header.phtml'); ?> 
<div id="logo">
<a href="http://www.braldahim.com">Braldahim</a><br />
  <a href="/"> -> Jeu</a><br />
  <a href="http://regles.braldahim.com"> -> R&egrave;gles</a><br />
  <a href="http://forum.braldahim.com"> -> Forums</a><br />
</div> 
 
<div class="box_infos_jeu">
<div class="inner">
	<ul class="titre textalia textsizea">Braldahim</ul>

	<div class="contenu">
	    <ul class="box_contenu1">
	    	<ul class="titre textalic textsizeb">
		    	<br><br>
		    	Braldahim est actuellement indisponible.
	    	</ul> 
	    	<br>
	    	Rendez-vous sur le <a href="http://forum.braldahim.com/viewforum.php?f=2">forums Annonce de l'&eacute;quipe</a> pour plus d'informations.
	    	<br><br>
	      </ul>
	</div>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>  
