<?php echo $this->render('header.phtml'); ?> 
<div id="logo">
<a href="http://www.braldahim.com">Braldahim</a><br />
  <a href="/"> -&gt; Jeu</a><br />
  <a href="http://regles.braldahim.com"> -&gt; R&egrave;gles</a><br />
  <a href="http://forum.braldahim.com"> -&gt; Forums</a><br />
</div> 
 
<div class="box_infos_jeu">
<div class="inner">
	<div class="titre textalia textsizea">Braldahim</div>

	<div class="contenu">
	    <div class="box_contenu1">
	    	<div class="titre textalic textsizeb">
		    	<br /><br />
		    	Braldahim est actuellement indisponible.
	    	</div> 
	    	<br />
	    	Rendez-vous sur le <a href="http://forum.braldahim.com/viewforum.php?f=2">forums Annonce de l'&eacute;quipe</a> pour plus d'informations.
	    	<br /><br />
	      </div>
	</div>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>  
