<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
	<div class="titre textalia textsizea">Administration</div>
    <div class="titre textalic textsizeb">Cr&eacute;ation Monstres</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    	
			<table align='center'>
			<tr>
			<td colspan='20'>
			<form action="/Administrationmonstre/creation" method="post">
				Type<br />
				
				<select name="id_type">
				<?php foreach ($this->typesMonstre as $t) : ?>
				<option value="<?php echo $t["id_type_monstre"]?>" <?php if ($t["nom_groupe_monstre"] == "Gibier"): echo 'disabled'; endif; ?>><?php echo $t["nom_groupe_monstre"]?> - <?php echo $t["nom_type"]?> (min:<?php echo $t["nb_membres_min"]?>, max:<?php echo $t["nb_membres_max"]?>) </option>
				<?php endforeach; ?>
				</select>
				<br /><br />
				
				<br />Création dans la zone : <br />
				(non utilisé si des coodonnées sont utilisées ci-dessous, mais à remplir tout de même)
				<br />
				<select name="id_zone" onchange="javascript:t=this.value.split(':'); $('x_min_zone').value=t[0]; $('x_max_zone').value=t[1]; $('y_min_zone').value=t[2]; $('y_max_zone').value=t[3]">
				<option value=":::">
					(Zones pr&eacute;d&eacute;finies)
				</option>
				<?php foreach ($this->zones as $z) : ?>
				<option value="<?php echo $z["x_min"]?>:<?php echo $z["x_max"]?>:<?php echo $z["y_min"]?>:<?php echo $z["y_max"]?>">
					Zone <?php echo $z["id_zone"]?> xmin:<?php echo $z["x_min"]?> xmax:<?php echo $z["x_max"]?>, ymin <?php echo $z["y_min"]?> ymax:<?php echo $z["y_max"]?>
				</option>
				<?php endforeach; ?>
				</select>
				<br />				
				X min
				<input type="text" name="x_min_zone" id="x_min_zone" size="4" maxlength="4" />
				X max
				<input type="text" name="x_max_zone" id="x_max_zone" size="4" maxlength="4" />
				Y min
				<input type="text" name="y_min_zone" id="y_min_zone" size="4" maxlength="4" />
				Y max
				<input type="text" name="y_max_zone" id="y_max_zone" size="4" maxlength="4" />
				
				<br /><br />
				Facultatif : le monstre restera à l'intérieur de ces coordonnées (laissez vide si pas de rayon défini): <br />
				X Position départ
				<input type="text" name="x_position" id="x_position" size="4" maxlength="4" />
				Y Position départ
				<input type="text" name="y_position" id="y_position" size="4" maxlength="4" />
				X min
				<input type="text" name="x_min_position" id="x_min_position" size="4" maxlength="4" />
				X max
				<input type="text" name="x_max_position" id="x_max_position" size="4" maxlength="4" />
				Y min
				<input type="text" name="y_min_position" id="y_min_position" size="4" maxlength="4" />
				Y max
				<input type="text" name="y_max_position" id="y_max_position" size="4" maxlength="4" />
				
				<br /><br />
					Nombre de monstre<br />
					(Cr&eacute;ation automatique de groupe)
				<input type="text" name="nombre" onkeypress="chiffres(event);" size="3" maxlength="3" />
				
			<input type="submit" class="button1" name="Ajouter" value="Ajouter" />
			</form>
			</td>
			</tr>
			</table>
			<br /><br />
			<?php if ($this->creation === true): ?>
			<div class="titre textalic textsizeb">R&eacute;sultats Cr&eacute;ation</div>
				Cr&eacute;ation de <?php echo count($this->tabCreation["monstres"])?> monstre(s) et de <?php echo count($this->tabCreation["groupesMonstres"])?> groupe(s) de monstres<br />
				
				<?php if ($this->tabCreation["groupesMonstres"] != null) : ?>
					Groupes : <br />
					<?php foreach($this->tabCreation["groupesMonstres"] as $g): ?>
						Groupe Id <?php echo $g["id_groupe_monstre"]?> Nombre de membres <?php echo $g["nb_membres_max_groupe_monstre"]?><br />
					<?php endforeach; ?>
				<?php endif; ?>
				
				Monstres : <br />
				<?php foreach($this->tabCreation["monstres"] as $g): ?>
					Monstre Id <?php echo $g["id_monstre"]?> <?php echo $g["nom_type"]?> (<?php echo $g["taille"]?>) 
					niveau:<?php echo $g["niveau_monstre"]?> pv:<?php echo $g["pv_restant_monstre"]?>
					x:<?php echo $g["x_monstre"]?> y:<?php echo $g["y_monstre"]?>
					FOR:<?php echo $g["force_base_monstre"]?> SAG:<?php echo $g["sagesse_base_monstre"]?>
					AGI:<?php echo $g["agilite_base_monstre"]?> VIG:<?php echo $g["vigueur_base_monstre"]?>
					ARMNAT :<?php echo $g["armure_naturelle_monstre"]?> DLA:<?php echo $g["duree_base_tour_monstre"]?>
					 <input type='button' name='goFicheMonstre' value='Ouvrir Fiche'   class='button1'  onclick='document.location.href="/Administrationmonstre/monstre/mode/simple/idmonstre/<?php echo $g["id_monstre"]?>"'> 
	   				<input type='button' name='goProfilMonstre' value='Ouvrir Profil Public' class='button1' onclick='javascript:ouvrirWin("/voir/monstre/?monstre=<?php echo $g["id_monstre"]?>");'> <br />
				<?php endforeach; ?>
				
			<?php endif; ?>
				
			<br /><br /><br /><br />
			<div class="titre textalic textsizea">Statistiques actuelles</div><br />
			
			<table>
			<tr>
			<td valign="top">
				
				<div class="titre textalic textsizec">Stats globales</div>
	
				Nombre de groupe actuellement en base : <?php echo $this->stats["nb_groupes"] ?><br />
				Nombre de monstre actuellement en base : <?php echo $this->stats["nb_monstres"] ?><br />
				Pourcentage de couverture globale : <?php echo $this->stats["couverture_globale"] ?> % (si l'on consid&egrave;re 1 monstre par case).<br />
	
				<br />
				<br /><div class="titre textalic textsizec">Nombre de monstres par type</div>
				<?php foreach($this->stats["nb_monstre_par_type"] as $t): ?>
					<?php echo $t["nom_type"]?> : <?php echo $t["nombre"]?><br />
				<?php endforeach; ?>
				
				<br />
				<div class="titre textalic textsizec">Nombre de monstres par taille</div>
				<?php foreach($this->stats["nb_monstre_par_taille"] as $t): ?>
					<?php echo $t["nom_feminin"]?> / <?php echo $t["nom_masculin"]?> : <?php echo $t["nombre"]?><br />
				<?php endforeach; ?>
				
			</td>
			<td>
				<div class="titre textalic textsizec">Couverture par zone</div>
			
				<table class="table_liste">
				<thead class="table_liste">
				<tr class="table_liste">
					<th>N&deg;</th>
					<th>Environnement</th>
					<th>Villes</th>
					<th>x_min</th>
					<th>x_max</th>
					<th>y_min</th>
					<th>y_max</th>
					<th>Nombre Cases</th>
					<th>Nombre Monstres</th>
					<th>Couverture</th>
				</tr>
				</thead>
				<?php foreach ($this->zones as $zone) : ?>
					<tr>
						<td><?php echo $zone["id_zone"] ?></td>
						<td><?php echo $zone["environnement"] ?></td>
						<td><?php echo $zone["villes"] ?></td>
						<td><?php echo $zone["x_min"] ?></td>
						<td><?php echo $zone["x_max"] ?></td>
						<td><?php echo $zone["y_min"] ?></td>
						<td><?php echo $zone["y_max"] ?></td>
						<td><?php echo $zone["nombre_cases"] ?></td>
						<td><?php echo $zone["nombre_monstres"] ?></td>
						<td><?php echo $zone["couverture"] ?> % </td>
					</tr>
				<?php endforeach; ?>
				</table>
			</td>
			</tr>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>