<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
	<div class="titre textalia textsizea">Administration</div>
    <div class="titre textalic textsizeb">Cr&eacute;ation Monstres</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    	
			<table align='center'>
			<tr>
			<td colspan='20'>
			<form action="/Administrationmonstre/creation" method="post">
				Type<br />
				
				<select name="id_type">
				<? foreach ($this->typesMonstre as $t) : ?>
				<option value="<?=$t["id_type_monstre"]?>" <? if ($t["nom_groupe_monstre"] == "Gibier"): echo 'disabled'; endif; ?>><?=$t["nom_groupe_monstre"]?> - <?=$t["nom_type"]?> (min:<?=$t["nb_membres_min"]?>, max:<?=$t["nb_membres_max"]?>) </option>
				<? endforeach; ?>
				</select>
				<br /><br />
				
				<br />Création dans la zone : <br />
				(non utilisé si des coodonnées sont utilisées ci-dessous, mais à remplir tout de même)
				<br />
				<select name="id_zone" onchange="javascript:t=this.value.split(':'); $('x_min_zone').value=t[0]; $('x_max_zone').value=t[1]; $('y_min_zone').value=t[2]; $('y_max_zone').value=t[3]">
				<option value=":::">
					(Zones pr&eacute;d&eacute;finies)
				</option>
				<? foreach ($this->zones as $z) : ?>
				<option value="<?=$z["x_min"]?>:<?=$z["x_max"]?>:<?=$z["y_min"]?>:<?=$z["y_max"]?>">
					Zone <?=$z["id_zone"]?> xmin:<?=$z["x_min"]?> xmax:<?=$z["x_max"]?>, ymin <?=$z["y_min"]?> ymax:<?=$z["y_max"]?>
				</option>
				<? endforeach; ?>
				</select>
				<br />				
				X min
				<input type="text" name="x_min_zone" id="x_min_zone" size="4" maxlength="4" />
				X max
				<input type="text" name="x_max_zone" id="x_max_zone" size="4" maxlength="4" />
				Y min
				<input type="text" name="y_min_zone" id="y_min_zone" size="4" maxlength="4" />
				Y max
				<input type="text" name="y_max_zone" id="y_max_zone" size="4" maxlength="4" />
				
				<br /><br />
				Facultatif : le monstre restera à l'intérieur de ces coordonnées (laissez vide si pas de rayon défini): <br />
				X Position départ
				<input type="text" name="x_position" id="x_position" size="4" maxlength="4" />
				Y Position départ
				<input type="text" name="y_position" id="y_position" size="4" maxlength="4" />
				X min
				<input type="text" name="x_min_position" id="x_min_position" size="4" maxlength="4" />
				X max
				<input type="text" name="x_max_position" id="x_max_position" size="4" maxlength="4" />
				Y min
				<input type="text" name="y_min_position" id="y_min_position" size="4" maxlength="4" />
				Y max
				<input type="text" name="y_max_position" id="y_max_position" size="4" maxlength="4" />
				
				<br /><br />
					Nombre de monstre<br />
					(Cr&eacute;ation automatique de groupe)
				<input type="text" name="nombre" onkeypress="chiffres(event);" size="3" maxlength="3" />
				
			<input type="submit" class="button1" name="Ajouter" value="Ajouter" />
			</form>
			</td>
			</tr>
			</table>
			<br /><br />
			<? if ($this->creation === true): ?>
			<div class="titre textalic textsizeb">R&eacute;sultats Cr&eacute;ation</div>
				Cr&eacute;ation de <?=count($this->tabCreation["monstres"])?> monstre(s) et de <?=count($this->tabCreation["groupesMonstres"])?> groupe(s) de monstres<br />
				
				<? if ($this->tabCreation["groupesMonstres"] != null) : ?>
					Groupes : <br />
					<? foreach($this->tabCreation["groupesMonstres"] as $g): ?>
						Groupe Id <?=$g["id_groupe_monstre"]?> Nombre de membres <?=$g["nb_membres_max_groupe_monstre"]?><br />
					<? endforeach; ?>
				<? endif; ?>
				
				Monstres : <br />
				<? foreach($this->tabCreation["monstres"] as $g): ?>
					Monstre Id <?=$g["id_monstre"]?> <?=$g["nom_type"]?> (<?=$g["taille"]?>) 
					niveau:<?=$g["niveau_monstre"]?> pv:<?=$g["pv_restant_monstre"]?>
					x:<?=$g["x_monstre"]?> y:<?=$g["y_monstre"]?>
					FOR:<?=$g["force_base_monstre"]?> SAG:<?=$g["sagesse_base_monstre"]?>
					AGI:<?=$g["agilite_base_monstre"]?> VIG:<?=$g["vigueur_base_monstre"]?>
					ARMNAT :<?=$g["armure_naturelle_monstre"]?> DLA:<?=$g["duree_base_tour_monstre"]?>
					 <input type='button' name='goFicheMonstre' value='Ouvrir Fiche'   class='button1'  onclick='document.location.href="/Administrationmonstre/monstre/mode/simple/idmonstre/<?=$g["id_monstre"]?>"'> 
	   				<input type='button' name='goProfilMonstre' value='Ouvrir Profil Public' class='button1' onclick='javascript:ouvrirWin("/voir/monstre/?monstre=<?=$g["id_monstre"]?>");'> <br />
				<? endforeach; ?>
				
			<? endif; ?>
				
			<br /><br /><br /><br />
			<div class="titre textalic textsizea">Statistiques actuelles</div><br />
			
			<table>
			<tr>
			<td valign="top">
				
				<div class="titre textalic textsizec">Stats globales</div>
	
				Nombre de groupe actuellement en base : <?=$this->stats["nb_groupes"] ?><br />
				Nombre de monstre actuellement en base : <?=$this->stats["nb_monstres"] ?><br />
				Pourcentage de couverture globale : <?=$this->stats["couverture_globale"] ?> % (si l'on consid&egrave;re 1 monstre par case).<br />
	
				<br />
				<br /><div class="titre textalic textsizec">Nombre de monstres par type</div>
				<? foreach($this->stats["nb_monstre_par_type"] as $t): ?>
					<?=$t["nom_type"]?> : <?=$t["nombre"]?><br />
				<? endforeach; ?>
				
				<br />
				<div class="titre textalic textsizec">Nombre de monstres par taille</div>
				<? foreach($this->stats["nb_monstre_par_taille"] as $t): ?>
					<?=$t["nom_feminin"]?> / <?=$t["nom_masculin"]?> : <?=$t["nombre"]?><br />
				<? endforeach; ?>
				
			</td>
			<td>
				<div class="titre textalic textsizec">Couverture par zone</div>
			
				<table class="table_liste">
				<thead class="table_liste">
				<tr class="table_liste">
					<th>N&deg;</th>
					<th>Environnement</th>
					<th>Villes</th>
					<th>x_min</th>
					<th>x_max</th>
					<th>y_min</th>
					<th>y_max</th>
					<th>Nombre Cases</th>
					<th>Nombre Monstres</th>
					<th>Couverture</th>
				</tr>
				</thead>
				<? foreach ($this->zones as $zone) : ?>
					<tr>
						<td><?=$zone["id_zone"] ?></td>
						<td><?=$zone["environnement"] ?></td>
						<td><?=$zone["villes"] ?></td>
						<td><?=$zone["x_min"] ?></td>
						<td><?=$zone["x_max"] ?></td>
						<td><?=$zone["y_min"] ?></td>
						<td><?=$zone["y_max"] ?></td>
						<td><?=$zone["nombre_cases"] ?></td>
						<td><?=$zone["nombre_monstres"] ?></td>
						<td><?=$zone["couverture"] ?> % </td>
					</tr>
				<? endforeach; ?>
				</table>
			</td>
			</tr>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>