<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Monstre</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <?php if ($this->modificationMonstre === true) :?>
	    	Modification du monstre prise en compte.
	    <?php endif; ?>
	    
	     <form action="/Administrationbatch/logs" method="post">
  		 	<input type="hidden" name="commande" value="grep" />
  		 	<input type="hidden" name="recherche" value="<?php echo $this->id_monstre?>" />
  		 	<input type="hidden" name="fichier" value="bral_viemonstre.log" />
			<input type="submit" class="button" name="Rechercher" value="Derniers Event Logs" />
		</form>
		
	    <form action="/Administrationmonstre/monstre/mode/<?php echo $this->mode?>/idmonstre/<?php echo $this->id_monstre?>" method="post">
		<?php if ($this->monstre == null): ?>
			Monstre inconnu 
		<?php else: 
			$nbElement = 0; ?>
			
			<input type='button' name='goProfilMonstre' value='Ouvrir Profil Public' class='button' onclick='javascript:ouvrirWin("/voir/monstre/?monstre=<?php echo $this->id_monstre?>");'>
	   
			<?php if ($this->mode == "simple") :?>
	 	   		<input type="button"  class='button' name="mode" value="Passer en vue complexe" onclick="document.location.href='/Administrationmonstre/monstre/mode/complexe/idmonstre/<?php echo $this->id_monstre?>'"/>
	   	 	<?php else: ?>
	    		<input type="button"  class='button' name="mode" value="Passer en vue simple" onclick="document.location.href='/Administrationmonstre/monstre/mode/simple/idmonstre/<?php echo $this->id_monstre?>'"/>
	    	<?php endif; ?>
	    	
			<table  align='center'>
			<?php foreach ($this->monstre as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?php echo $key?></td>
				<td>
				<?php if ($key == "id_monstre"): ?>
					<input type='hidden' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
					<?php echo $value ?>
				<?php else: ?>
					<input type='text' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
				<?php endif; ?>
				</td>
				<td>				
				<?php if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button' name="Modifier" value="Modifier le monstre" />
				<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
			</table>
			<input type="submit"  class='button' name="Modifier" value="Modifier le monstre" />
		<?php endif; ?>
		</form>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>