<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Administration Monstre</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
	    <? if ($this->modificationMonstre === true) :?>
	    	Modification du monstre prise en compte.
	    <? endif; ?>
	    
	     <form action="/Administrationbatch/logs" method="post">
  		 	<input type="hidden" name="commande" value="grep" />
  		 	<input type="hidden" name="recherche" value="<?=$this->id_monstre?>" />
  		 	<input type="hidden" name="fichier" value="bral_viemonstre.log" />
			<input type="submit" class="button1" name="Rechercher" value="Derniers Event Logs" />
		</form>
		
	    <form action="/Administrationmonstre/monstre/mode/<?=$this->mode?>/idmonstre/<?=$this->id_monstre?>" method="post">
		<? if ($this->monstre == null): ?>
			Monstre inconnu 
		<? else: 
			$nbElement = 0; ?>
			
			<input type='button' name='goProfilMonstre' value='Ouvrir Profil Public' class='button1' onclick='javascript:ouvrirWin("/voir/monstre/?monstre=<?=$this->id_monstre?>");'> 
	   
			<? if ($this->mode == "simple") :?>
	 	   		<input type="button"  class='button1' name="mode" value="Passer en vue complexe" onClick="document.location.href='/Administrationmonstre/monstre/mode/complexe/idmonstre/<?=$this->id_monstre?>'"/>
	   	 	<? else: ?>
	    		<input type="button"  class='button1' name="mode" value="Passer en vue simple" onClick="document.location.href='/Administrationmonstre/monstre/mode/simple/idmonstre/<?=$this->id_monstre?>'"/>
	    	<? endif; ?>
	    	
			<table  align='center'>
			<? foreach ($this->monstre as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?=$key?></td>
				<td>
				<? if ($key == "id_monstre"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=stripslashes($value)?>">
					<?=$value ?>
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=stripslashes($value)?>">
				<? endif; ?>
				</td>
				<td>				
				<? if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button1' name="Modifier" value="Modifier le monstre" />
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
			<input type="submit"  class='button1' name="Modifier" value="Modifier le monstre" />
		<? endif; ?>
		</form>
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>