<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
<ul class="titre textalia textsizea">
	Administration
</ul>
<ul class="titre textalic textsizeb">
	Référentiel Monstres
</ul>
&nbsp;
<div class="contenu">
<ul class="box_contenu1 textalic">

	<table>
		<tr>
			<td width='60%'>

			<form
				action="/Administrationmonstre/referentiel/<?=$this->nomAction?>"
				method="post">
			<table align='center'>
				<tr>
					<td>Type</td>
					<td><select name="id_type">
					<? foreach ($this->typesMonstre as $t) : ?>
						<option value="<?=$t["id_type_monstre"]?>"
						<?if($this->referenceCourante["id_type_monstre"] == $t["id_type_monstre"]){echo "selected";}?>><?=$t["nom_type"]?></option>
						<? endforeach; ?>
					</select></td>
				</tr>
				<tr>
					<td>Taille</td>
					<td><select name="id_taille">
					<? foreach ($this->taillesMonstre as $t) : ?>
						<option value="<?=$t["id_taille_monstre"]?>"
						<?if($this->referenceCourante["id_taille_monstre"] == $t["id_taille_monstre"]){echo "selected";}?>><?=$t["nom_feminin"]?>
						/ <?=$t["nom_masculin"]?></option>
						<? endforeach; ?>
					</select></td>
				<tr>
					<td>Niveau Min</td>
					<td><input type="textbox" name="niveau_min"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["niveau_min"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Max</td>
					<td><input type="textbox" name="niveau_max"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["niveau_max"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Min Force</td>
					<td><input type="textbox" name="min_niveau_force"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["min_niveau_force"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Max Force</td>
					<td><input type="textbox" name="max_niveau_force"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["max_niveau_force"]?>" /></td>
				</tr>
				<tr>
					<td>BM Force</td>
					<td><input type="textbox" name="bm_force"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_force"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Min Sagesse</td>
					<td><input type="textbox" name="min_niveau_sagesse"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["min_niveau_sagesse"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Max Sagesse</td>
					<td><input type="textbox" name="max_niveau_sagesse"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["max_niveau_sagesse"]?>" /></td>
				</tr>
				<tr>
					<td>BM Sagesse</td>
					<td><input type="textbox" name="bm_sagesse"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_sagesse"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Min Vigueur</td>
					<td><input type="textbox" name="min_niveau_vigueur"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["min_niveau_vigueur"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Max Vigueur</td>
					<td><input type="textbox" name="max_niveau_vigueur"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["max_niveau_vigueur"]?>" /></td>
				</tr>
				<tr>
					<td>BM Vigueur</td>
					<td><input type="textbox" name="bm_vigueur"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_vigueur"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Min Agilité</td>
					<td><input type="textbox" name="min_niveau_agilite"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["min_niveau_agilite"]?>" /></td>
				</tr>
				<tr>
					<td>Niveau Max Agilité</td>
					<td><input type="textbox" name="max_niveau_agilite"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["max_niveau_agilite"]?>" /></td>
				</tr>
				<tr>
					<td>BM Agilité</td>
					<td><input type="textbox" name="bm_agilite"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_agilite"]?>" /></td>
				</tr>
				<tr>
					<td>BM Attaque</td>
					<td><input type="textbox" name="bm_attaque"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_attaque"]?>" /></td>
				</tr>
				<tr>
					<td>BM Defense</td>
					<td><input type="textbox" name="bm_defense"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_defense"]?>" /></td>
				</tr>
				<tr>
					<td>BM Degat</td>
					<td><input type="textbox" name="bm_degat"
						size="3" maxlength="2"
						value="<?=$this->referenceCourante["bm_degat"]?>" /></td>
				</tr>
				<tr>
					<td>Vue</td>
					<td><input type="textbox" name="vue" onkeypress="chiffres(event);"
						size="3" maxlength="4"
						value="<?=$this->referenceCourante["vue"]?>" /></td>
				</tr>
				<tr>
					<td>Coef PV</td>
					<td><input type="textbox" name="coef_pv_ref_monstre"
						size="3" maxlength="4"
						value="<?=$this->referenceCourante["coef_pv_ref_monstre"]?>" /></td>
				</tr>
				<tr>
					<td>ArmNat Min Alea</td>
					<td><input type="textbox" name="alea_min_armnat"
						size="3" maxlength="4"
						value="<?=$this->referenceCourante["alea_min_armnat"]?>" /></td>
				</tr>
				<tr>
					<td>ArmNat Max Alea</td>
					<td><input type="textbox" name="alea_max_armnat"
						size="3" maxlength="4"
						value="<?=$this->referenceCourante["alea_max_armnat"]?>" /></td>
				</tr>
				<tr>
					<td colspan='2'><? if ($this->modifier === true): ?> <input
						type="submit" class="button1" name="Modifier"
						value="Modifier la référence" /> <input
						type="button" class="button1" name="Annuler" value="Annuler"
						onClick="document.location.href='/Administrationmonstre/referentiel/'" />

						<? else: ?> 
						<!-- <input type="submit" class="button1" name="Ajouter"
						value="Ajouter une nouvelle référence" /> --> 
						<? endif; ?>
					</td>
				</tr>
			</table>
			</form>

			</td>

			<td>Rappel : <br>
			Definition de l'armure naturelle : <br>

			<pre style="text-align: left; width: 70%">
				$aleaArmNat = Lancé de dé entre ArmNatAleaMin et ArmNatAleaMax.
				$armure_naturelle_monstre = floor(($force_base_monstre + $vigueur_base_monstre) / 5) + $aleaArmNat;
		</pre> Définition des PV: <pre style="text-align: left; width: 70%">
				$pv_restant_monstre = (20 + $niveau_vigueur * 4) * 2;
				$pv_restant_monstre = $pv_restant_monstre * $referenceCourante["coef_pv_ref_monstre"];
</pre> 
			</td>
		</tr>
	</table>
	<br />
	<br />

	<table class="table_liste" style="width:90%">
		<thead class="table_liste">
			<tr class="table_liste">
				<th>ID</th>
				<th>Type</th>
				<th>Taille</th>
				<th>Niveau Min</th>
				<th>Niveau Max</th>
				<th>Niv Min Force</th>
				<th>Niv Max Force</th>
				<th>BM Force</th>
				<th>Niv Min Sagesse</th>
				<th>Niv Max Sagesse</th>
				<th>BM Sagesse</th>
				<th>Niv Min Vigueur</th>
				<th>Niv Max Vigueur</th>
				<th>BM Vigueur</th>
				<th>Niv Min Agilite</th>
				<th>Niv Max Agilite</th>
				<th>BM Agilite</th>
				<th>BM Attaque</th>
				<th>BM Defense</th>
				<th>BM Degat</th>
				<th>Vue</th>
				<th>ArmNat AleaMin</th>
				<th>ArmNat AleaMax</th>
				<th>Coef PV</th>
				<th>Estim pvMin</th>
				<th>Edition</th>
			</tr>
		</thead>
		<? foreach ($this->refMonstre as $r) : ?>
		<tr>
			<td><?=$r["id_ref_monstre"] ?></td>
			<td><?=$r["nom_type"] ?></td>
			<td><?=$r["taille"] ?></td>
			<td><?=$r["niveau_min"] ?></td>
			<td><?=$r["niveau_max"] ?></td>
			<td><?=$r["min_niveau_force"] ?></td>
			<td><?=$r["max_niveau_force"] ?></td>
			<td><?=$r["bm_force"] ?></td>
			<td><?=$r["min_niveau_sagesse"] ?></td>
			<td><?=$r["max_niveau_sagesse"] ?></td>
			<td><?=$r["bm_sagesse"] ?></td>
			<td><?=$r["min_niveau_vigueur"] ?></td>
			<td><?=$r["max_niveau_vigueur"] ?></td>
			<td><?=$r["bm_vigueur"] ?></td>
			<td><?=$r["min_niveau_agilite"] ?></td>
			<td><?=$r["max_niveau_agilite"] ?></td>
			<td><?=$r["bm_agilite"] ?></td>
			<td><?=$r["bm_attaque"] ?></td>
			<td><?=$r["bm_defense"] ?></td>
			<td><?=$r["bm_degat"] ?></td>
			<td><?=$r["vue"] ?></td>
			<td><?=$r["alea_min_armnat"] ?></td>
			<td><?=$r["alea_max_armnat"] ?></td>
			<td nowrap><?=$r["coef_pv_ref_monstre"] ?></td>
			<td><?=$r["estimation_pv_min"]?></td>
			<td><input type="button" class="button1" name="Modifier"
				value="Modifier"
				onClick="document.location.href='/Administrationmonstre/referentiel/modifier/<?=$r["id_ref_monstre"] ?>';" /></td>
		</tr>
		<? endforeach; ?>
	</table>
</ul>
</div>
&nbsp;</div>
</div>
		<?php echo $this->render('footer.phtml'); ?>