<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
	<ul class="titre textalia textsizea">Administration</ul>
    <ul class="titre textalic textsizeb">Répartition des Monstres</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
		
		<table class="table_liste">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th>Nid Id</th>
				<th>Nb dans Nid</th>
				<th>Nb Vivant</th>
				<th>Nb Total</th>
				<th>Couverture demandée</th>
				<th>Couverture réelle</th>
				<th>Couverture par Type</th>
				<th>Carte</th>
			  </tr>
			</thead>
			
			<tbody>
		  	<? $i = 0; 
		  	foreach($this->zonesNids as $z) : ?>
		  		<tr class="table_liste<?=($i % 2);$i++; ?>" valign="top">
			  		<td class="table_liste"><?=$z["id_zone_nid"]?>
				  		<? if ($z["estVille"] == "oui") : ?>
				  			Zone de Ville
				  		<? endif;?>
			  		</td>
			  		<td class="table_liste"><?=$z["nbDansNids"]?></td>
			  		<td class="table_liste"><?=$z["nbVivants"]?></td>
			  		<td class="table_liste"><?=$z["nbTotal"]?></td>
			  		<td class="table_liste"><?=$z["couvertureDemandee"]?></td>
			  		<td class="table_liste"><?=$z["couvertureReelle"]?>%</td>
			  		<td>
			  		
			  		<div id='detaila_<?=$z["id_zone_nid"]?>' style="display:block" >
			  			<input type='button' class='button1' value='Afficher' onClick="javascript:switch2div('detaila_<?=$z["id_zone_nid"]?>','detailb_<?=$z["id_zone_nid"]?>');">
					</div>
					
			  		 <div id='detailb_<?=$z["id_zone_nid"]?>' style="display:none" >
			  		 
				  		<table class="table_liste">
						<thead class="table_liste">
						  <tr class="table_liste">
							<th nowrap>Id Type</th>
							<th nowrap>Type</th>
							<th nowrap>Niveau Moyen</th>
							<th nowrap>Nb dans Nid</th>
							<th nowrap>Nb Vivant</th>
							<th nowrap>Total demandé</th>
							<th nowrap>Total réel</th>
							<th nowrap>Manque</th>
						  </tr>
						</thead>
						<tbody>
							<? foreach($this->typesMonstres as $k => $m) : //$z["details"] as $k => $t) : 
								if (array_key_exists($k, $z["details"]) && isset($z["details"][$k]["totalDemande"])) :
								$t = $z["details"][$k];
							?>
								<tr class="table_liste">
								<td class="table_liste" nowrap><?=$this->typesMonstres[$k]["nom"]?> (<?=$k?>)</td>
								<td class="table_liste" nowrap><?=$this->typesMonstres[$k]["type"]?></td>
								<td class="table_liste" nowrap><?=$t["niveauMoyen"]?></td>
								<td class="table_liste" nowrap><?=$t["dansNids"]?></td>
								<td class="table_liste" nowrap><?=$t["vivants"]?></td>
								<td class="table_liste" nowrap><? if (isset($t["totalDemande"])): echo $t["totalDemande"]; else : echo 0; endif; ?></td>
								<td class="table_liste" nowrap><? if (isset($t["totalDemande"])): echo $t["totalReel"]; else : echo 0; endif; ?></td>
								<td class="table_liste" nowrap><? if (isset($t["totalDemande"])): echo $t["manque"]; else : echo 0; endif; ?></td>
								</tr>
							<? else: ?>
							  <tr class="table_liste">
								<td class="table_liste" colspan="8">Monstre <?=$this->typesMonstres[$k]["nom"]?> (<?=$k?>) non defini pour cette zone</td>
								</tr>
							  <?
							    endif;
							endforeach;?>
						</tbody>
						</table>
						<input type='button' class='button1' value='Cacher' onClick="javascript:switch2div('detaila_<?=$z["id_zone_nid"]?>','detailb_<?=$z["id_zone_nid"]?>');">
					
			  		 </div>
			  		</td>
			  		<td>
			  		 <a href='/Administrationcarte/carte?monstres=1&coef=0.5&zonenidmin=<?=$z["id_zone_nid"]?>&zonenidmax=<?=$z["id_zone_nid"]?>'>Carte</a>
			  		</td>
		  		</tr>
		  	<? endforeach; ?>
		  	</tbody>
	  	
	  	</table>
		
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>
