<?php include('voirHeader.phtml'); ?>
<br />
<div class="box_public">
<div class="inner">

<br />

<?php if ($this->connu == false) : ?>
	<div class="titrea textalic titreasizea">Braldûn Inconnu</div>
<?php else : ?>
    <div class="titrea textalic titreasizea"><?php echo $this->braldun["prenom_braldun"] ?> <?php echo $this->braldun["nom_braldun"] ?><?php 
    if ($this->ancien === false && $this->braldun["titre_courant_braldun"] != null) : ?>, 
    <?php echo $this->braldun["titre_courant_braldun"] ?>
    <?php endif;?>
     </div>
     <div class="titre textalic textsized">
      Braldûn n&deg;<?php echo $this->braldun["id_braldun"] ?>
     </div>
     
    <?php if ($this->ancien) : ?>
	    <div class="titrea textalic titreasized">
	    Ce Braldûn a disparu, il n'est plus joué.
	    </div>
    <?php endif;?>
	&nbsp;
	
	<div class="contenu">
	    <div class="box_contenu1 textalic">
				<input type='button' class='button' value='Profil' onclick='document.location.href="/voir/braldun/?braldun=<?php echo $this->braldun["id_braldun"] ?>"'>
				 <?php if ($this->ancien === false) : ?>
					<input type='button' class='button' value='&Eacute;v&eacute;nements' onclick='_get_("/voir/doaction?caction=ask_voir_braldun&braldun=<?php echo $this->braldun["id_braldun"] ?>&menu=evenements");'>
					<input type='button' class='button' value='Distinctions' onclick='_get_("/voir/doaction?caction=ask_voir_braldun&braldun=<?php echo $this->braldun["id_braldun"] ?>&menu=distinctions");'>
				 <?php endif; ?>
				<input type='button' class='button' value='Famille' onclick='_get_("/voir/doaction?caction=ask_voir_braldun&braldun=<?php echo $this->braldun["id_braldun"] ?>&menu=famille");'>
			<div id="box_voir_braldun_inner">
				<?php echo $this->flux; ?>
			</div>
		</div>
	</div>
	&nbsp;
<?php endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
