<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

    <div class="titrea textalic titreasizea">Les Braldûns</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<br />
				<br />
				<input type='hidden' id='nb_valeurs-voir_bralduns' name='nb_valeurs-voir_bralduns' value='9'>
				<input type="hidden" name='valeur_1-voir_bralduns' id="valeur_1-voir_bralduns" value="-1" >
				<input type="hidden" name='valeur_2-voir_bralduns' id="valeur_2-voir_bralduns" value="<?php echo $this->filtre ?>" >
				<input type="hidden" name='valeur_3-voir_bralduns' id="valeur_3-voir_bralduns" value="<?php echo $this->page ?>" >
				<input type="hidden" name='valeur_4-voir_bralduns' id="valeur_4-voir_bralduns" value="<?php echo $this->filtre?>" >
				<input type="hidden" name='valeur_5-voir_bralduns' id="valeur_5-voir_bralduns" value="<?php echo $this->ordre ?>" >
				<input type="hidden" name='valeur_6-voir_bralduns' id="valeur_6-voir_bralduns" value="<?php echo $this->sensOrdre ?>" >
				<input type="hidden" name='valeur_7-voir_bralduns' id="valeur_7-voir_bralduns" value="<?php echo $this->filtrePrenom ?>" >
				<input type="hidden" name='valeur_8-voir_bralduns' id="valeur_8-voir_bralduns" value="-1" >
				<input type="hidden" name='valeur_9-voir_bralduns' id="valeur_9-voir_bralduns" value="-1" >
				
				Filtrer par niveau : 
				<select name='select_valeur_2' id='select_valeur_2' onchange="Javascript:_get_('/voir/doaction?caction=ask_voir_bralduns&valeur_1=f&valeur_2='+ this.value + '&valeur_3=0&valeur_4=-1&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>&valeur_7='+ $('#select_valeur_7').val(), 'voir_bralduns')">
				    <option value="-1">Tous les niveaux</option>
					<?php foreach ($this->tabNiveaux as $n) : ?>
				  	<option value='<?php echo $n["niveau_braldun"]?>' <?php if ($this->filtre == $n["niveau_braldun"]){echo "selected";}?>>Niveau <?php echo $n["niveau_braldun"]?></option>
				  	<?php endforeach; ?>
			  	</select>
			  	<br />
			  	
			  	Filtrer par la première lettre du prénom : 
				<select name='select_valeur_7' id='select_valeur_7'  onchange="Javascript:_get_('/voir/doaction?caction=ask_voir_bralduns&valeur_1=f&valeur_2='+ $('#select_valeur_2').val() + '&valeur_3=0&valeur_4=-1&valeur_5=<?php echo $this->ordre ?>&valeur_6=<?php echo $this->sensOrdre ?>&valeur_7='+this.value, 'voir_bralduns')">
				    <option value="-1">Tous les prénoms</option>
					<?php foreach ($this->tabLettres as $k => $v) : ?>
				  	<option value='<?php echo $k?>' <?php if ($this->filtrePrenom == $k){echo "selected";}?>><?php echo $v?></option>
				  	<?php endforeach; ?>
			  	</select>
			  	<br />
			  	
  			<div id="box_voir_bralduns_inner">
				<?php include('bralduns/liste.phtml'); ?>
			</div>
		</div>
	</div>
	&nbsp;
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
