<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

<?php if ($this->connue == false) : ?>
	<div class="titrea textalic titreasizea">Communaut&eacute; inconnue</div>
<?php else : ?>
    <div class="titrea textalic titreasizea">Communaut&eacute; : <?php echo $this->communaute["nom_communaute"] ?>, n&deg; <?php echo $this->communaute["id_communaute"] ?></div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onclick='document.location.href="/voir/communaute/?communaute=<?php echo $this->communaute["id_communaute"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_communaute&communaute=<?php echo $this->communaute["id_communaute"] ?>&menu=membres");' title="Voir les membres">Membres</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_communaute_inner">
				<?php include('communaute/profil.phtml'); ?>
			</div>
	</div>
	</div>
	&nbsp;
<?php endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>

