<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

    <div class="titrea textalic titreasizea">Les Communautés</div>
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
				<input type='hidden' id='nb_valeurs-voir_communautes' name='nb_valeurs-voir_communautes' value='9'>
				<input type="hidden" name='valeur_1-voir_communautes' id="valeur_1-voir_communautes" value="-1" >
				<input type="hidden" name='valeur_2-voir_communautes' id="valeur_2-voir_communautes" value="<?php echo $this->filtre ?>" >
				<input type="hidden" name='valeur_3-voir_communautes' id="valeur_3-voir_communautes" value="<?php echo $this->page ?>" >
				<input type="hidden" name='valeur_4-voir_communautes' id="valeur_4-voir_communautes" value="<?php echo $this->filtre?>" >
				<input type="hidden" name='valeur_5-voir_communautes' id="valeur_5-voir_communautes" value="<?php echo $this->ordre ?>" >
				<input type="hidden" name='valeur_6-voir_communautes' id="valeur_6-voir_communautes" value="<?php echo $this->sensOrdre ?>" >
				<input type="hidden" name='valeur_7-voir_communautes' id="valeur_7-voir_communautes" value="-1" >
				<input type="hidden" name='valeur_8-voir_communautes' id="valeur_8-voir_communautes" value="-1" >
				<input type="hidden" name='valeur_9-voir_communautes' id="valeur_9-voir_communautes" value="-1" >
  			<div id="box_voir_communautes_inner">
				<?php include('communautes/liste.phtml'); ?>
			</div>
		</div>
	</div>
	&nbsp;
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
