<? include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

    <ul class="titre textalic textsizea">Communautés</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
				<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='9'>
				<input type="hidden" name='valeur_1' id="valeur_1" value="-1" >
				<input type="hidden" name='valeur_2' id="valeur_2" value="<?=$this->filtre ?>" >
				<input type="hidden" name='valeur_3' id="valeur_3" value="<?=$this->page ?>" >
				<input type="hidden" name='valeur_4' id="valeur_4" value="<?=$this->filtre?>" >
				<input type="hidden" name='valeur_5' id="valeur_5" value="<?=$this->ordre ?>" >
				<input type="hidden" name='valeur_6' id="valeur_6" value="<?=$this->sensOrdre ?>" >
				<input type="hidden" name='valeur_7' id="valeur_7" value="-1" >
				<input type="hidden" name='valeur_8' id="valeur_8" value="-1" >
				<input type="hidden" name='valeur_8' id="valeur_9" value="-1" >
  			<div id="box_voir_communautes_inner">
				<? include('communautes/liste.phtml'); ?>
			</div>
		</ul>
	</div>
	&nbsp;
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
