<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

<?php if ($this->connu == false) : ?>
	<div class="titrea textalic textsizea">&Eacute;quipement Inconnu</div>
<?php else : ?>
    <div class="titrea textalic textsizea">
    <?php echo $this->equipement["nom"]." ".addslashes($this->equipement["suffixe"])." de qualit&eacute; ".$this->equipement["qualite"] ?>
     </div>
     <div class="titre textalic textsized">
      &Eacute;quipement n&deg;<?php echo $this->equipement["id_equipement"]?><br />
     </div>
     
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onclick='document.location.href="/voir/equipement/?equipement=<?php echo $this->equipement["id_equipement"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_equipement&equipement=<?php echo $this->equipement["id_equipement"] ?>&menu=historique");' title="Voir l'historique">Historique</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_equipement_inner">
				<?php echo $this->flux; ?>
			</div>
		</div>
	</div>
	&nbsp;
<?php endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
