<? include('voirHeader.phtml'); ?>

<div class="box_public">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">

<? if ($this->connu == false) : ?>
	<ul class="titre textalic textsizea">Hobbit Inconnu</ul>
<? else : ?>
    <ul class="titre textalic textsizea"><?=$this->hobbit["prenom_hobbit"] ?> <?=$this->hobbit["nom_hobbit"] ?><? 
    if ($this->hobbit["titre_courant_hobbit"] != null) : ?>, 
    <?=$this->hobbit["titre_courant_hobbit"] ?>
    <? endif;?>
     </ul>
     <ul class="titre textalic textsized">
      Hobbit n&deg;<?=$this->hobbit["id_hobbit"] ?>
     </ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onClick='document.location.href="/voir/hobbit/?hobbit=<?=$this->hobbit["id_hobbit"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onClick='_get_("/voir/doaction?caction=ask_voir_hobbit&hobbit=<?=$this->hobbit["id_hobbit"] ?>&menu=evenements");' title="Voir les &eacute;v&eacute;nements">&Eacute;v&eacute;nements</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_hobbit_inner">
				<? include('hobbit/profil.phtml'); ?>
			</div>
		</ul>
	</div>
	&nbsp;
<? endif; ?>
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>

<?php echo $this->render('footer.phtml'); ?>
