<?php echo $this->render('header.phtml'); ?>

<div class="box_public">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Braldahim - Hobbit</ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<table class="table_liste">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th>Profil</th>
				<th>&Eacute;v&egrave;nements</th>
			  </tr>
			</thead>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>

