<? include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

<? if ($this->connu == false) : ?>
	<div class="titre textalic textsizea">Mat&eacute;riel inconnu</div>
<? else : ?>
    <div class="titre textalic textsizea">
    <?= $this->materiel["nom"]." n°".$this->materiel["id_materiel"]?>
     </div>
     
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onclick='document.location.href="/voir/materiel/?materiel=<?=$this->materiel["id_materiel"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_materiel&materiel=<?=$this->materiel["id_materiel"] ?>&menu=historique");' title="Voir l'historique">Historique</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_materiel_inner">
				<?=$this->flux; ?>
			</div>
		</div>
	</div>
	&nbsp;
<? endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
