<? include('voirHeader.phtml'); ?>

<div class="box_administration">
<div class="inner">
    <ul class="titre textalic textsizea">Monstre</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    
		<? if ($this->monstre == null): ?>
			Monstre inconnu 
		<? else: 
			$nbElement = 0; ?>
	    
			<table  align='center'>
			<? foreach ($this->monstre as $key => $value) : 
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?=$key?></td>
				<td>
				<? if ($key == "id_monstre"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=$value?>">
					<?=$value ?>
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=$value?>">
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
		<? endif; ?>
		</ul>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>