<? include('voirHeader.phtml'); ?>

<div class="box_public">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">

<? if ($this->connu == false) : ?>
	<ul class="titre textalic textsizea">Monstre Inconnu</ul>
<? else : ?>
    <ul class="titre textalic textsizea">Monstre n&deg; <?=$this->monstre["id_monstre"] ?>, 
    <? if ($this->monstre["genre_type_monstre"] == 'feminin') : ?>
    	<?=$this->monstre["nom_taille_f_monstre"] ?>
    <? else: ?>
    	<?=$this->monstre["nom_taille_m_monstre"] ?>
    <? endif; ?>
    <?=$this->monstre["nom_type_monstre"] ?>
     </ul>
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onClick='document.location.href="/voir/monstre/?monstre=<?=$this->monstre["id_monstre"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onClick='_get_("/voir/doaction?caction=ask_voir_monstre&monstre=<?=$this->monstre["id_monstre"] ?>&menu=evenements");' title="Voir les &eacute;v&eacute;nements">&Eacute;v&eacute;nements</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_monstre_inner">
				<?=$this->flux; ?>
			</div>
		</ul>
	</div>
	&nbsp;
<? endif; ?>
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>

<?php echo $this->render('footer.phtml'); ?>
