<?php include('voirHeader.phtml'); ?>

<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Monstre</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
		<?php if ($this->monstre == null): ?>
			Monstre inconnu 
		<?php else: 
			$nbElement = 0; ?>
	    
			<table  align='center'>
			<?php foreach ($this->monstre as $key => $value) : 
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre'><?php echo $key?></td>
				<td>
				<?php if ($key == "id_monstre"): ?>
					<input type='hidden' name="<?php echo $key ?>" value="<?php echo $value?>">
					<?php echo $value ?>
				<?php else: ?>
					<input type='text' name="<?php echo $key ?>" value="<?php echo $value?>">
				<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
			</table>
		<?php endif; ?>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>