<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

<?php if ($this->connu == false) : ?>
	<div class="titrea textalic textsizea">Potion ou Vernis Inconnu</div>
<?php else : ?>
    <div class="titrea textalic textsizea">
    <?php echo  $this->potion["nom_type"]." ".$this->potion["nom"]. " n°".$this->potion["id_potion"]?>
     </div>
     
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onclick='document.location.href="/voir/potion/?potion=<?php echo $this->potion["id_potion"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_potion&potion=<?php echo $this->potion["id_potion"] ?>&menu=historique");' title="Voir l'historique">Historique</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_potion_inner">
				<?php echo $this->flux; ?>
			</div>
		</div>
	</div>
	&nbsp;
<?php endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
