<? include('voirHeader.phtml'); ?>

<div class="box_public">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">

<? if ($this->connu == false) : ?>
	<ul class="titre textalic textsizea">Potion ou Vernis Inconnu</ul>
<? else : ?>
    <ul class="titre textalic textsizea">
    <?= $this->potion["nom_type"]." ".$this->potion["nom"]. " n°".$this->potion["id_potion"]?>
     </ul>
     
	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onClick='document.location.href="/voir/potion/?potion=<?=$this->potion["id_potion"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onClick='_get_("/voir/doaction?caction=ask_voir_potion&potion=<?=$this->potion["id_potion"] ?>&menu=historique");' title="Voir l'historique">Historique</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_potion_inner">
				<?=$this->flux; ?>
			</div>
		</ul>
	</div>
	&nbsp;
<? endif; ?>
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>

<?php echo $this->render('footer.phtml'); ?>
