<?php include('voirHeader.phtml'); ?>

<div class="box_public">
<div class="inner">

<?php if ($this->connu == false) : ?>
	<div class="titrea textalic titreasizea">Rune inconnue</div>
<?php else : ?>
    <div class="titrea textalic titreasizea">
    Rune n°<?php echo $this->rune["id_rune"]?>
     </div>
     
	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<table class="table_liste" style="width:150px;">
			<thead class="table_liste">
			  <tr class="table_liste">
				<th style="cursor:pointer" onclick='document.location.href="/voir/rune/?rune=<?php echo $this->rune["id_rune"] ?>"' title="Voir le profil">Profil</th>
				<th style="cursor:pointer" onclick='_get_("/voir/doaction?caction=ask_voir_rune&rune=<?php echo $this->rune["id_rune"] ?>&menu=historique");' title="Voir l'historique">Historique</th>
			  </tr>
			</thead>
			</table>
			<div id="box_voir_rune_inner">
				<?php echo $this->flux; ?>
			</div>
		</div>
	</div>
	&nbsp;
<?php endif; ?>
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>
