<?php echo $this->render('headerHead.phtml'); ?>
<?php echo $this->render('headerDiv.phtml'); ?>
<?php echo $this->render('headerAuth.phtml'); ?>
<?php echo $this->render('headerRacine.phtml'); ?>

 <div class="inner_top" style="height:25px; text-align:center">
  <a href="/voir/bralduns">Braldûns</a> | 
  <a href="/voir/communautes">Communaut&eacute;s</a> |
  &nbsp;&nbsp;&nbsp;
	<?php if ($this->user) : ?>
		<input type="search" name="recherche_valeur_2_voir" size='40' id="recherche_valeur_2_voir" value="Recherche Braldûn - Entrez un nom" onFocus='this.value=""; activerRechercheVoirBraldun("valeur_2_voir");' />
		<input type="hidden" name="recherche_valeur_2_voir_actif" id="recherche_valeur_2_voir_actif" value="0" />
		<span id="indicateur_recherche_valeur_2_voir" style="display: none"><img src="<?php echo $this->config->url->static?>/images/divers/loader.gif" alt="Recherche..." /></span>
	<?php endif; ?>
 </div>
<div style="height:2px">&nbsp;</div>

<?php echo $this->render('headerDiv.phtml'); ?>