<br />
<div class="titre textalic textsized">Terminez toutes les quêtes d'une comté pour accéder à un Donjon</div>
<br />
<?php if ($this->user->niveau_braldun < 10) : ?>
	<b> Attention : les qu&ecirc;tes ne sont accessibles qu'&agrave; partir du niveau 10 !</b>
	<br /><br /> 
<?php endif;?>
 <table width="100%">
 	<tr>
 		<td width="40%" valign="top">
 			<table class="table_liste" style="width:90%">
				<thead class="table_liste">
				  <tr class="table_liste">
					<th colspan='2'> Qu&ecirc;tes r&eacute;alis&eacute;es ou en cours<br /></th>
				  </tr>
				</thead>
				
				<tbody>
				 <?php foreach($this->lieuxQuetes as $region) :
				 	$i = 0; 
				 	?>
				 	<tr class="table_liste">
						<td class="table_liste_th" colspan='2'><?php echo $region["nom"]?></td>
				 	</tr>
				 	<?php foreach($region["lieux"] as $l) : ?>
			  		<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
			  		<td class="table_liste">
			  			<?php if ($l["id_quete"] != null) : ?>
						  	<label class="alabel" onclick="Javascript:_get_('/quete/doaction?caction=ask_quete_voir&id_quete=<?php echo $l["id_quete"]?>');">
						  	Qu&ecirc;te de la <?php echo $l["nom_lieu"]?>
						  	</label> 
					  	<?php else: ?>
						  	<label>
						  	Qu&ecirc;te de la <?php echo $l["nom_lieu"]?>
						  	</label>
					  	<?php endif;?>
					  	
					  	(<a title="Cliquez pour voir <?php echo $l["nom_ville"]?> dans les règles" style="text-decoration: none" onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/<?php echo $l["nom_ville"]?>')";><?php echo $l["nom_ville"]?></a>)
					  
					</td>
					<td class="table_liste" nowrap>
					  	<?php if ($l["date_fin_quete"] != null): ?> 
					  		Terminée
					  	<?php elseif ($l["en_cours"] === true): ?>
					  		En Cours
					  	<?php else: ?>
					  		Non Débutée
					  	<?php endif;?>
					 </td>
				  	 </tr>
				  	<?php endforeach;?>
				  <?php endforeach;?>
				</tbody>
			</table>
 		</td>
 		<td width="60%" valign="top">
 			<div id="box_quete_voir">
			<?php echo $this->htmlQuete?>
			</div>
 		</td>
 	</tr>
 </table>
