<ul class="titre textalic textsizec">D&eacute;tail (priv&eacute;)</ul>
  <ul class="box_contenu1 textalic">
  <br />
  	<? if ($this->evenement != null) : ?>
  		<?=$this->evenement["date"]?> : <?=$this->evenement["type"]?> - <?=$this->evenement["details"]?><br />
  		<input type='hidden' id='nb_valeurs' name='nb_valeurs' value=''>
  		<input type='hidden' name='valeur_1' id='valeur_1' value='envoi' />
		<input type='hidden' name='valeur_2' id='valeur_2' value='' />
		<input type='hidden' name='valeur_3' id='valeur_3' value='' />
	  <textarea style="background-color:#CCCC99;" id="detail_evenement_prive" rows="10" cols="85" readonly >
<?=$this->evenement["details_bot"] ?></textarea>
   <? else: ?>
   		Aucun &eacute;v&eacute;nement s&eacute;lectionn&eacute;.
   <? endif; ?>
   <br /><br />
   
   <input type="button" class='button1' name="Envoyer" value="Transf&eacute;rer dans un message" onClick="Javascript:$('nb_valeurs').value=3;$('valeur_1').value='envoi';$('valeur_2').value =-1;$('valeur_3').value=$('detail_evenement_prive').value; _get_('/messagerie/doaction?caction=do_messagerie_message'); my_switch('box_messagerie','boite_c');" />
  </ul>