<div class="box_contenu1 textalic">
	<div class="titre textalic textsizeb">
		&nbsp; Calcul de votre mot de passe restreint
	</div>
	<br />
	Votre mot de passe actuel :
	<form action='/md5'><input type='password' name='md5_source'
		id='md5_source' value='' size='20' /> <input
		type='submit' value='MD5' class='button1' /> <?php if ($this->md5_value != "") : ?>
	
	<br /><br />
	
	Mot de passe restreint :<br /> <br />
	<?php echo $this->md5_value ?>
	<?php endif; ?></form>
	
	<br /><br />
	
	<input type="button" class='button1'
		onclick="document.location.href='/'"
		value="Retour à la page des Scripts Publics" />
	<br /><br />
</div>
