<? include("box_header.phtml") ?>
<div class="inner">

<ul class="titre textalic textsizeb">
	<ul class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onClick='_get_("/interface/load/?box=box_lieu");' value="Sortir du champ">
	</ul>
		<?=$this->nomChamp ?><br/><br/>
	</ul>
 	<div class="contenuC">
 		<ul class="box_contenu1 textalic">
			<br /><br /><br />
			
			En Jachère.
			
			<br />
 		</ul>
 	</div>
</div>
<? include("box_bottom.phtml") ?>