<? include("box_header.phtml") ?>
<div class="inner">

<div class="titre textalic textsizeb">
	<div class="titre textalia" style="position:Absolute">
	<input type="button" class='button1' onclick='_get_("/interface/load/?box=box_lieu");' value="Sortir du champ">
	</div>
		<?=$this->nomChamp ?><br/><br/>
	</div>
 	<div class="contenuC">
 		<div class="box_contenu1 textalic">
			<br /><br /><br />
			
			En Jachère.
			
			<br />
 		</div>
 	</div>
</div>
<? include("box_bottom.phtml") ?>