<div class="titre textalic textsizec">Construction des champs</div>
 <div class="contenuc">
  <div class="box_contenu1 textalic">
  <br />
  	
  	Pour obtenir un champ, rendez-vous dans &agrave; l'<a title="Cliquez pour voir l''Office Notariale dans les règles" style="text-decoration: none" onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/Office_Notarial')";>Office Notarial</a>.<br /> 
  	Vous ne pourrez obtenir de champ que dans la Comt&eacute; o&ugrave; vous 
  	serez. <br />
 	
 	<?php if ($this->niveauGrenier != null && ($this->niveauGrenier == Bral_Util_Communaute::NIVEAU_EN_CONSTRUCTION || $this->niveauGrenier >= 0)) : ?>
 		<?php echo Bral_Helper_Communaute::afficheNiveauGrenier($this->niveauGrenier);?>
 	<?php elseif ($this->user->id_fk_communaute_braldun != null) : ?>
 		Votre communauté ne possède pas de <?php echo Bral_Helper_Communaute::afficheNiveauGrenier(null, "grenier")?>.
 	<?php endif;?>
 	
 	<br />
	<?php if ($this->nChamps < 1) : ?>
  		Aucun champ.<br /><br />
   	<?php else: ?>
   	
   	<table class="table_liste" style='width:100%'>
		<thead class="table_liste">
		  <tr class="table_liste">
		  <th>Champ</th>
		  <th>Propriétaire</th>
		  <th>Comté</th>
		  <th>État</th>
		  </tr>
	  </thead>
	  <tbody>
	  
	  	<?php foreach($this->champs as $c) :?>
	  		<tr class='alabel'  style="cursor:pointer" title="Cliquez pour regarder le contenu du champ" onclick="_get_('/champs/doaction?caction=ask_champs_voir&valeur_1=<?php echo $c["id_champ"]?>')">
	  			<td class="table_liste">
	  				<?php echo $c["nom_champ"] ?> [<?php echo $c["x_champ"] ?> ; <?php echo $c["y_champ"] ?>]
	  			</td>
	  			<td class="table_liste"><?php echo $c["braldun"] ?></td>
	  			<td class="table_liste"><?php echo $c["nom_region"] ?></td>
	  			<td class="table_liste">
	  			<?php echo $c["nom_type_graine"] ?> 
	  			<?php if ($c["phase_champ"] == "seme") : ?>
					en pleine croissance !
				<?php elseif ($this->champ["phase_champ"] == "a_recolter") : ?>
					À récolter
				<?php else : ?>
					en friche
				<?php endif; ?>
  				</td>
	  			</tr>	  			
   		<?php endforeach; ?>
	   </tbody>
	   </table>
   	<?php endif; ?>
   	
	<br /><br />
   </div>
</div>
