<div class="titre textalic textsizec">Construction des champs</div>
 <div class="contenuc">
  <div class="box_contenu1 textalic">
  <br />
  	
  	Pour obtenir un champ, rendez-vous dans &agrave; l'<a title="Cliquez pour voir l''Office Notariale dans les règles" style="text-decoration: none" onclick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/Office_Notarial')";>Office Notarial</a>.<br /> 
  	Vous ne pourrez obtenir de champ que dans la Comt&eacute; o&ugrave; vous 
  	serez. <br />
 	
 	<br />
	<?php if ($this->nChamps < 1) : ?>
  		Vous n'avez aucun champ.<br /><br />
   	<?php else: ?>
	   	<table class="table_liste">
		<thead class="table_liste">
		  <tr class="table_liste">
		  	<?php $i = 0;
			   $champ = false;
			   foreach($this->tabRegions as $r) : ?>
					<th><?php echo htmlspecialchars($r["nom_region"]); ?></th>
			<?php endforeach; ?>
		  </tr>
		</thead>
		<tbody>
		   <tr>
	   		<?php foreach($this->tabRegions as $r) : ?>
	   			<td class="table_liste">
	   			<?php if ($r["champs"] != null) :?>
			   		<?php foreach($r["champs"] as $c) :?>
		   				<span class='alabel' style="cursor:pointer" title="Cliquez pour regarder le contenu du champ" onclick="_get_('/champs/doaction?caction=ask_champs_voir&valeur_1=<?php echo $c["id_champ"]?>')">
		   					<?php echo $c["nom_champ"] ?> [<?php echo $c["x_champ"] ?> ; <?php echo $c["y_champ"] ?>]
		   				</span><br />
			   		<?php endforeach; ?>
		   		<?php endif; ?>
		   		</td>
	   		<?php endforeach;?>
		   </tr>
		</tbody>
		</table>
	<?php endif; ?>
	
	<br /><br />
   </div>
</div>
