<div class="titre textalic textsizec">Construction des champs</div>
 <div class="contenuc">
  <div class="box_contenu1 textalic">
  <br />
  	
  	Pour obtenir un champ, rendez-vous dans &agrave; l'<a title="Cliquez pour voir l''Office Notariale dans les règles" style="text-decoration: none" onClick="javascript:ouvrirWin('http://regles.braldahim.com/wiki/Office_Notarial')";>Office Notarial</a>.<br /> 
  	Vous ne pourrez obtenir de champ que dans la Comt&eacute; o&ugrave; vous 
  	serez. <br />
 	
 	<br />
	<? if ($this->nChamps < 1) : ?>
  		Vous n'avez aucun champ.<br /><br />
   	<? else: ?>
	   	<table class="table_liste">
		<thead class="table_liste">
		  <tr class="table_liste">
		  	<? $i = 0;
			   $champ = false;
			   foreach($this->tabRegions as $r) : ?>
					<th><?=htmlspecialchars($r["nom_region"]); ?></th>
			<? endforeach; ?>
		  </tr>
		</thead>
		<tbody>
		   <tr>
	   		<? foreach($this->tabRegions as $r) : ?>
	   			<td class="table_liste">
	   			<? if ($r["champs"] != null) :?>
			   		<? foreach($r["champs"] as $c) :?>
		   				<span class='alabel' style="cursor:pointer" title="Cliquez pour regarder le contenu du champ" onClick="_get_('/champs/doaction?caction=ask_champs_voir&valeur_1=<?=$c["id_champ"]?>')">
		   					<?=$c["nom_champ"] ?> [<?=$c["x_champ"] ?> ; <?=$c["y_champ"] ?>]
		   				</span><br />
			   		<? endforeach; ?>
		   		<? endif; ?>
		   		</td>
	   		<? endforeach;?>
		   </tr>
		</tbody>
		</table>
	<? endif; ?>
	
	<br /><br />
   </div>
</div>
