<div class='comp_titre'>Modifier le nom du champ</div>
 <input type='hidden' id='nb_valeurs-champs_modifiernom' name='nb_valeurs-champs_modifiernom' value='2'>
 <input type='hidden' id='valeur_1-champs_modifiernom' name='valeur_1-champs_modifiernom' value='<?php echo $this->idChamp ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	<br />
 	Entrez le nom du champ : <br />
	<input id="valeur_2-champs_modifiernom" name="valeur_2-champs_modifiernom" type="text" value="<?php echo htmlspecialchars($this->champ["nom_champ"])?>" size="22" maxlength="30"/>
	
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_modifiernom' value='Modifier le nom' onclick='this.disabled=true;_get_("/champs/doaction?caction=do_champs_modifiernom", "champs_modifiernom");'>
<?php echo Bral_Helper_Fermer::affiche(); ?>