<div class='comp_titre'>Modifier le nom du champ</div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='2'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->idChamp ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
 	<br />
 	Entrez le nom du champ : <br>
	<input id="valeur_2" name="valeur_2" type="text" value="<?=htmlspecialchars($this->champ["nom_champ"])?>" size="22" maxlength="30"/>
	
 </div>

</form>
<br />
<input type='button' class='button1' id='bouton_modifiernom' value='Modifier le nom' onClick='this.disabled=true;_get_("/champs/doaction?caction=do_champs_modifiernom");'>
<? echo Bral_Helper_Fermer::affiche(); ?>