<div class='comp_titre'>Modifier la description du champ</div>
 <input type='hidden' id='nb_valeurs-champs_modifierdescription' name='nb_valeurs-champs_modifierdescription' value='2'>
 <input type='hidden' id='valeur_1-champs_modifierdescription' value='<?php echo $this->idChamp ?>'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	
	<br />
	<?php echo Bral_Helper_BBBoutons::affiche('valeur_descriptionchamp', 2500)?>
	<input type='hidden' id='valeur_2-champs_modifierdescription' value='' />
	<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="<?php echo (2500-mb_strlen($this->champ["commentaire_champ"]))?>" type="text"> Caract&egrave;res restants<br />
	<textarea name="valeur_descriptionchamp" id="valeur_descriptionchamp" class="inputbox" rows="10" cols="60" onkeydown="textCount($('#valeur_descriptionchamp'),$('#characterstyped'),2500);" onkeyup="textCount($('#valeur_descriptionchamp'),$('#characterstyped'),2500);"><?php echo Bral_Util_BBParser::bbcodeStripPlus($this->champ["commentaire_champ"])?></textarea>
		
 </div>
</form>
<br />
<input type='button' class='button1' id='bouton_modifierdescription' value='Modifier la description' onclick='this.disabled=true;$("valeur_2-champs_modifierdescription").value=encodePlus($("valeur_descriptionchamp").val());_get_("/champs/doaction?caction=do_champs_modifierdescription", "champs_modifierdescription", true);'>
<?php echo Bral_Helper_Fermer::affiche(); ?>