<div style="text-align:left; position:Absolute; padding: 0px; ">
<input type="button" class='button1' onclick='_get_("/champs/doaction?caction=ask_champs_liste");' value="Retour">
</div>

<div class="titre textalic textsizec">
<?php if ($this->champ["nom_champ"] != null && $this->champ["nom_champ"] != "") : ?>
	<?php echo htmlspecialchars($this->champ["nom_champ"])?>,
<?php endif; ?>
Champ <br /></div>
<div class="titre textalic textsizec"><?php echo htmlspecialchars($this->champ["nom_region"])?>, x:<?php echo $this->champ["x_champ"]?>, y:<?php echo $this->champ["y_champ"]?></div>
<br />

    <?php if ($this->estSurChamp === true && $this->user->activation == true): 
  		$disabled = "";
  	   else:
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre champ, vous n'avez pas acc&egrave;s aux actions...<br />
  	<?php endif; ?>

 <input type="button" class='button1' value="0 PA - Modifier le nom" 
 onclick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifiernom&valeur_1=<?php echo $this->champ["id_champ"] ?>')" <?php echo $disabled?> />
 <input type="button" class='button1' value="0 PA - Modifier la description"
  onclick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifierdescription&valeur_1=<?php echo $this->champ["id_champ"] ?>')" <?php echo $disabled?>/>
 
<hr> <br />

<div class="titre textalic textsizec">Le champ</div><br />

<?php 
if ($this->competences != null) :
	foreach($this->competences as $c) : ?>
		<?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
	      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
	    else:
	      $attr = " disabled ";
	    endif;?>
	    <input type="button" class='button1' value="<?php echo $c["pa_utilisation"]?> PA - <?php echo $c["nom"]?><?php if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?php echo $attr?>>
	<?php endforeach;
endif;?>
<br /><br />
 <?php include('voir/grille.phtml')?>