<div style="text-align:left; position:Absolute; padding: 0px; ">
<input type="button" class='button' onclick='_get_("/champs/doaction?caction=ask_champs_liste");' value="Retour">
</div>

<div class="titre textalic textsizec">
<?php if ($this->champ["nom_champ"] != null && $this->champ["nom_champ"] != "") : ?>
	<?php echo htmlspecialchars($this->champ["nom_champ"])?><br />
<?php endif; ?>
Champ appartenant à <?php echo $this->champ["braldun"]?><br /></div>
<div class="titre textalic textsizec"><?php echo htmlspecialchars($this->champ["nom_region"])?>, x:<?php echo $this->champ["x_champ"]?>, y:<?php echo $this->champ["y_champ"]?></div>
<br />

  <?php if ($this->possedeChamp === true): ?>
	 <input type="button" class='button' value="0 PA - Modifier le nom"
	 onclick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifiernom&valeur_1=<?php echo $this->champ["id_champ"] ?>')" <?php echo $disabled?> />
	 <input type="button" class='button' value="0 PA - Modifier la description"
	  onclick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifierdescription&valeur_1=<?php echo $this->champ["id_champ"] ?>')" <?php echo $disabled?>/>
 <?php endif; ?>
 
<hr> 
<?php if ($this->niveauGrenier != null && ($this->niveauGrenier == Bral_Util_Communaute::NIVEAU_EN_CONSTRUCTION || $this->niveauGrenier >= 0)) : ?>
 		<?php echo Bral_Helper_Communaute::afficheNiveauGrenier($this->niveauGrenier);?><br />
<?php elseif ($this->user->id_fk_communaute_braldun != null) : ?>
 		Votre communauté ne possède pas de <?php echo Bral_Helper_Communaute::afficheNiveauGrenier(null, "grenier")?>.<br />
<?php endif;?>
 	
<div class="titre textalic textsizec">Le champ</div>

<?php 
if ($this->competences != null) :
	foreach($this->competences as $c) : ?>
		<?php if ($this->user->pa_braldun >=$c["pa_utilisation"]) : 
	      $attr = "onclick=\"Javascript:_get_('/competences/doaction?caction=ask_competence_".$c["nom_systeme"]."')\"";
	    else:
	      $attr = " disabled ";
	    endif;?>
	    <input type="button" class='button' value="<?php echo $c["pa_utilisation"]?> PA - <?php echo $c["nom"]?><?php if ($c["pourcentage_init"] < 100) : echo " ".$c["pourcentage"]." %"; endif; ?>" <?php echo $attr?>>
	<?php endforeach; ?>
<?php else: ?>
	<i>Aucune compétence d'agriculture disponible</i>.
<?php endif;?>
<br /><br />
 <?php include('voir/grille.phtml')?>