<ul style="text-align:left; position:Absolute; padding: 0px; ">
<input type="button" class='button1' onClick='_get_("/champs/doaction?caction=ask_champs_liste");' value="Retour">
</ul>

<ul class="titre textalic textsizec">
<?if ($this->champ["nom_champ"] != null && $this->champ["nom_champ"] != "") : ?>
	<?=htmlspecialchars($this->champ["nom_champ"])?>,
<? endif; ?>
Champ <br></ul>
<ul class="titre textalic textsizec"><?=htmlspecialchars($this->champ["nom_region"])?>, x:<?=$this->champ["x_champ"]?>, y:<?=$this->champ["y_champ"]?></ul>
<br />

    <? if ($this->estSurChamp === true && $this->user->activation == true): 
  		$disabled = "";
  	   else:
  		$disabled = "disabled" ;
  	?>
  		Vous n'&ecirc;tes pas dans votre champ, vous n'avez pas acc&egrave;s aux actions...<br />
  	<? endif; ?>

 <input type="button" class='button1' value="0 PA - Modifier le nom" 
 onClick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifiernom&valeur_1=<?=$this->champ["id_champ"] ?>')" <?=$disabled?> />
 <input type="button" class='button1' value="0 PA - Modifier la description"
  onClick="Javascript:_get_('/champs/doaction?caction=ask_champs_modifierdescription&valeur_1=<?=$this->champ["id_champ"] ?>')" <?=$disabled?>/>
 
<hr> <br />

 <? //include('voir/grille.phtml')?>