<footer id="footer">
	 <div class="inner_footer">
	 	<span id='date_heure' class=''>&nbsp;</span>   <span id='nb_connectes' class=''>&nbsp;</span>
	 	
	 	<p class="a">❧</p>
	 	
		<nav id="links">
			<div>
				<ul>
					<li>
						Le Projet 
						<ul class="menu">
							<li class="leaf first"><a href="<?php echo Zend_Registry::get("config")->url->site?>/projet" title="">L'Équipe</a></li>
							<li class="leaf"><a href="<?php echo Zend_Registry::get("config")->url->site?>/sources" title="">Code Source</a></li>
							<li class="leaf"><a href="<?php echo Zend_Registry::get("config")->url->sp?>" title="">API Externes</a></li>
							<li class="leaf last"><a href="<?php echo Zend_Registry::get("config")->url->site?>/abus/" class="aWhite">Signaler un abus</a></li>
						</ul>					
					</li>
				</ul>
			</div>
			<div>
				<ul>
					<li>
						Médias 
						<ul class="menu">
							<li class="leaf first"><a href="http://feeds.braldahim.com/braldahim-chronique" class="feed">Flux RSS</a></li>
							<li class="leaf last"><a href="http://twitter.com/#!/braldahim" title="">Twitter</a></li>
							<li class="leaf last"><a href="<?php echo Zend_Registry::get("config")->url->site?>/chat/" title="">Chat</a></li>
						</ul>					
					</li>
				</ul>
			</div>
			<div>

				<ul>
					<li>	
						L'association JeuxWeb.org						
						<ul class="menu">
							<li class="leaf first last"><a href="http://www.jeuxweb.org">JeuxWeb.org</a></li>
							<li class="leaf"><a href="http://mountyhall.com/" title="MountyHall">MountyHall</a></li>
							<li class="leaf first last"><a href="http://www.monde-de-thaanis.com/" title="Le Monde de Thäanis">Le Monde de Thäanis</a>
							<li class="leaf first last"><a href="<?php echo Zend_Registry::get("config")->url->site?>" title="Braldahim">Braldahim</a>
							</li>
						</ul>					
					</li>
				</ul>
			</div>
			
			<div>

				<ul>
					<li>	
						Pub						
							<ul class="menu"><li class="leaf first"><a href="http://www.sitacados.com/sites-jeux-gratuits-jeux-roles.html" class="aWhite" title="Jeux de rôle" target="_blank">RPG</a></li>
								<li class="leaf"><a href="http://www.jeux-alternatifs.com/Braldahim-jeu301_hit-parade_1_1.html" target="_blank"><img src="<?php echo Zend_Registry::get("config")->url->static?>/images/pub/jeux-alter.gif" alt="" border="0" /></a></li>
								<li class="leaf last"><a href="http://www.gamersroom.com/vote.php?num=1615" title="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs"><img src="<?php echo Zend_Registry::get("config")->url->static?>/images/pub/gamesroom.gif" alt="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs" style="border:none" /></a></li>
							</ul>					
					</li>
				</ul>
			</div>
			
			<div>
				<ul>
					<li>	
						Technique					
						<ul class="menu">
							<li class="leaf first"><a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a></li>
							<li class="leaf last"><a href="http://www.w3.org/html/logo/"><img src="<?php echo Zend_Registry::get("config")->url->static?>/images/pub/html5-badge-h-css3.png" height="32" alt="HTML5 Powered with CSS3 / Styling" title="HTML5 Powered with CSS3 / Styling" /></a></li>
						</ul>					
					</li>
				</ul>
			</div>
		</nav>
	 </div>
</footer>