<div id="menuhead">
	<nav id="nav-main">
	<ul class="menu">
		<li class="leaf first"><a title="" href="<?php echo Zend_Registry::get("config")->url->site?>/">Accueil</a>
		</li>
		<li class="leaf"><a title=""
			href="<?php echo Zend_Registry::get("config")->url->jeu?>/">Jouer</a>
		</li>
		<li class="expanded"><a title="" href="<?php echo Zend_Registry::get("config")->url->site?>/bourg">Le
				Bourg</a>
			<ul class="menu">
				<li class="leaf first"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/palmares">Palmarès</a>
				</li>
				<li class="leaf first"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/brasserie">La Brasserie des Sports</a>
				</li>
				<li class="leaf first"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/chambre">La Chambre des métiers</a>
				</li>
				<li class="leaf first"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/tableaurecherches">Tableaux des Recherchés</a>
				</li>
				<li class="leaf first"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/hotel">Hôtel des Ventes</a>
				</li>
				<li class="leaf last"><a title=""
					href="<?php echo Zend_Registry::get("config")->url->site?>/etals">Étals</a>
				</li>
			</ul>
		</li>
		<li class="leaf"><a title=""
			href="http://forum.braldahim.com">Forum</a>
		</li>
		<li class="leaf last"><a title=""
			href="<?php echo Zend_Registry::get("config")->url->regles?>">Règles</a>
			<ul class="menu">
				<li class="leaf first"><a title=""
					href="http://regles.braldahim.com/wiki/Livre:Comp%C3%A9tences/Tableau">Compétences</a>
				</li>
				<li class="leaf "><a title=""
					href="http://regles.braldahim.com/wiki/Livre:M%C3%A9tiers/Tableau">Métiers</a>
				</li>
				<li class="leaf "><a title=""
					href="http://regles.braldahim.com/wiki/Livre:Territoire/Ressources/Runes/Liste">Runes</a>
				</li>
				
				<li class="leaf"><a title=""
					href="http://regles.braldahim.com/wiki/Livre:Territoire/Villes">Villes</a>
				</li>
				
				<li class="leaf last"><a title=""
					href="http://regles.braldahim.com/wiki/Livre:Territoire/B%C3%A2timents">Bâtiments</a>
				</li>
				
			</ul>
			
		</li>
	</ul>
	</nav>
</div>