<div id="menuhead">
	<nav id="nav-main">
	<ul class="menu">
		<li class="leaf first"><a title="" href="/">Accueil</a>
		</li>
		<li class="leaf"><a title=""
			href="http://jeu.braldahim.com/auth/login">Jouer</a>
		</li>
		<li class="expanded"><a title="" href="/bourg">Le
				Bourg</a>
			<ul class="menu">
				<li class="leaf first"><a title=""
					href="/palmares">Palmarès</a>
				</li>
				<li class="leaf first"><a title=""
					href="/brasserie">La Brasserie des Sports</a>
				</li>
				<li class="leaf first"><a title=""
					href="/chambre">La Chambre des métiers</a>
				</li>
				<li class="leaf first"><a title=""
					href="/tableaurecherches">Tableaux des Recherchés</a>
				</li>
				<li class="leaf first"><a title=""
					href="/hotel">Hôtel des Ventes</a>
				</li>
				<li class="leaf last"><a title=""
					href="/etals">Étals</a>
				</li>
			</ul>
		</li>
		<li class="leaf"><a title=""
			href="http://forum.braldahim.com">Forum</a>
		</li>
		<li class="leaf last"><a title=""
			href="http://regles.braldahim.com">Règles</a>
		</li>
	</ul>
	</nav>
</div>