<?php Zend_Loader::loadClass("Bral_Helper_DetailEquipement"); ?>

<table class="table_liste" style="width:90%" <?php if ($this->idEquipementsTable != false) : ?> id="<?php echo $this->idEquipementsTable?>"<?php endif; ?>>
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
	  	<th>&nbsp;</th>
		<th>Nom</th>
		<th>Niveau</th>
		<th>Caract&eacute;ristiques</th>
		<?php if ($this->estElementsEtal === true) : ?>
			<th>Prix</th>
			<th>Commentaire du vendeur</th>
		<?php endif; ?>
		<?php if ($this->estElementsEtalAchat === true) : ?>
			<th>Marchander / Acheter</th>
		<?php endif; ?>
	  </tr>
	</thead>
	<tbody>
		<?php if (count($this->equipements) > 0) :?>
		
			<?php foreach($this->equipements as $em) : ?>
			   	 <tr class="table_liste">
				  	<th colspan="8" class="table_liste_th">Position : <?php echo $em["nom_type_emplacement"] ?></th>
			  	</tr>
			   	<?php 
			   	  $i = 0;
			      foreach($em["equipements"] as $e) :?>
					<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
				  		<td class="table_liste"><?php echo $e["id_equipement"] ?></td>
				  		<td class="table_liste"><img src='<?php echo $this->config->static->url?>/styles/braldahim_defaut/images/type_equipement/type_equipement_<?php echo $e["id_type_equipement"]?>.png' alt="<?php echo htmlspecialchars($e["nom"]) ?>"/></td>
				  		<td class="table_liste"><?php echo $e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?></td>
				  		<td class="table_liste"><?php echo $e["niveau"] ?></td>
				  		<td class="table_liste">
				  			<div class='braltip'>
				  			<?php echo Bral_Helper_DetailEquipement::afficherTooltip($e);?>
				  			<img src="<?php echo $this->config->static->url?>/images/info_icon.gif"/>
				  			</div>
				  		</td>
				  		<?php if ($this->estElementsEtal === true) : ?>
							<td class="table_liste" nowrap><?php echo Bral_Helper_DetailEquipement::afficherPrix($e);?></td>
							<td class="table_liste"><?php echo Bral_Util_BBParser::bbcodeReplace($e["commentaire_vente_echoppe_equipement"])?></td>
						<?php endif; ?>
						<?php if ($this->estElementsEtalAchat === true) : ?>
							<td class="table_liste">
							<input type="button" class='button1' onclick='_get_("/echoppe/doaction?caction=ask_echoppe_acheterequipement&idEquipement=<?php echo $e["id_equipement"] ?>");' value="<?php echo $this->config->game->echoppe->nb_pa_service ?> PA - Acheter">
							</td>
						<?php endif; ?>
				  	</tr>
				  <?php endforeach; ?>
			<?php endforeach; ?>
		<?php else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune pi&egrave;ce d'&eacute;quipement</i></td></tr>
		<?php endif; ?>
	</tbody>
</table>