<? Zend_Loader::loadClass("Bral_Helper_DetailEquipement"); ?>
<table class="table_liste">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
		<th>Nom</th>
		<th>Qualit&eacute;</th>
		<th>Niveau</th>
		<th>Nombre d'emplacements runiques</th>
	  </tr>
	</thead>
	<tbody>
		<? $i = 0;
		   foreach($this->equipements as $e) :?>
				<tr class="table_liste<?=($i % 2);$i++; ?>" <?=Bral_Helper_DetailEquipement::afficherJs($e);?> >
			  		<td class="table_liste"><?=$e["id_equipement"] ?></td>
			  		<td class="table_liste"><?=htmlentities($e["nom"]) ?></td>
			  		<td class="table_liste"><?=htmlentities($e["qualite"]) ?></td>
			  		<td class="table_liste"><?=$e["niveau"] ?></td>
			  		<td class="table_liste"><?=$e["nb_runes"] ?></td>
			  	</tr>
		<? endforeach; ?>
	</tbody>
</table>