<? Zend_Loader::loadClass("Bral_Helper_DetailEquipement"); ?>
<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>

<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
	  	<th>&nbsp;</th>
		<th>Nom</th>
		<th>Niveau</th>
		<th>Caract&eacute;ristiques</th>
		<? if ($this->estEquipementsPotionsEtal === true) : ?>
			<th>Prix</th>
			<th>Commentaire du vendeur</th>
		<? endif; ?>
		<? if ($this->estEquipementsPotionsEtalAchat === true) : ?>
			<th>Marchander / Acheter</th>
		<? endif; ?>
	  </tr>
	</thead>
	<tbody>
		<? if (count($this->equipements) > 0) :?>
			<? $i = 0;
			   foreach($this->equipements as $e) :?>
					<tr class="table_liste<?=($i % 2);$i++; ?>">
				  		<td class="table_liste"><?=$e["id_equipement"] ?></td>
				  		<td class="table_liste"><img src='/public/styles/braldahim_defaut/images/type_equipement/type_equipement_<?=$e["id_type_equipement"]?>.png' alt="<?=htmlspecialchars($e["nom"]) ?>"/></td>
				  		<td class="table_liste"><?=$e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?></td>
				  		<td class="table_liste"><?=$e["niveau"] ?></td>
				  		<td class="table_liste">
				  			<img src="/public/images/info_icon.gif" <?=Bral_Helper_DetailEquipement::afficherJs($e);?> />
				  		</td>
				  		<? if ($this->estEquipementsPotionsEtal === true) : ?>
							<td class="table_liste" nowrap><?=Bral_Helper_DetailEquipement::afficherPrix($e);?></td>
							<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($e["commentaire_vente_echoppe_equipement"])?></td>
						<? endif; ?>
						<? if ($this->estEquipementsPotionsEtalAchat === true) : ?>
							<td class="table_liste">
							<input type="button" class='button1' onClick='$("nb_valeurs").value=1;$("valeur_1").value=<?=$e["id_equipement"] ?>;_get_("/echoppe/doaction?caction=ask_echoppe_acheterequipement");' value="<?=$this->config->game->echoppe->nb_pa_service ?> PA - Acheter">
							</td>
						<? endif; ?>
				  	</tr>
			<? endforeach; ?>
		<? else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune pi&egrave;ce d'&eacute;quipement</i></td></tr>
		<? endif; ?>
	</tbody>
</table>