<? 
Zend_Loader::loadClass('Bral_Helper_Contenu');
?>
<table class="table_liste" style="width:auto; padding:5px;" >
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<? foreach ($this->munitions as $m) :  ?>
		<th style="width:auto; padding:5px;" ><?=htmlspecialchars($m["type"])?></th>
		<? endforeach; ?>
	  </tr>
	</thead>
	<tbody>
		<tr class="table_liste">
		<? foreach ($this->munitions as $m) : ?>
		 	<td class="table_liste">
		 		<?=Bral_Helper_Contenu::afficheMunition($m)?>
		 	</td>
		<? endforeach; ?>
		</tr>
	</tbody>
</table>
