<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
<div class="inner">
	<ul class="titre textalia textsizea">Administration</ul>
    <ul class="titre textalic textsizeb">Cr&eacute;ation Monstres</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    	<form action="/administrationmonstres/creation" method="post">
			<table align='center'>
			<tr>
			<td colspan='20'>
				<select name="id_zone" onChange="javascript:t=this.value.split(':'); $('x_min').value=t[0]; $('x_max').value=t[1]; $('y_min').value=t[2]; $('y_max').value=t[3]">
					<option value=":::">
						(Zones pr&eacute;d&eacute;finies)
					</option>
					<? foreach ($this->zones as $z) : ?>
					<option value="<?=$z["x_min"]?>:<?=$z["x_max"]?>:<?=$z["y_min"]?>:<?=$z["y_max"]?>">
						Zone <?=$z["id_zone"]?>
					</option>
					<? endforeach; ?>
					</select>
			</td>
			</tr>
			<tr>
				<td>
					Type
				</td>
				<td>
					<select name="id_type">
					<? foreach ($this->typesMonstre as $t) : ?>
					<option value="<?=$t["id_type_monstre"]?>"><?=$t["nom_type"]?></option>
					<? endforeach; ?>
					</select>
				</td>
				<td>
					X min
				</td>
				<td>
					<input type="textbox" name="x_min" id="x_min" size="4" maxlength="4" />
				</td>
				<td>
					X max
				</td>
				<td>
					<input type="textbox" name="x_max" id="x_max" size="4" maxlength="4" />
				</td>
				<td>
					Y min
				</td>
				<td>
					<input type="textbox" name="y_min" id="y_min" size="4" maxlength="4" />
				</td>
				<td>
					Y max
				</td>
				<td>
					<input type="textbox" name="y_max" id="y_max" size="4" maxlength="4" />
				</td>
				<td>
					Nombre de monstre<br />
					(Cr&eacute;ation automatique de groupe)
				</td>
				<td>
					<input type="textbox" name="nombre" onkeypress="chiffres(event);" size="3" maxlength="3" />
				</td>
			</tr>
			</table>
			<input type="submit" class="button1" name="Ajouter" value="Ajouter" />
			</form>
			
			<br /><br />
			<? if ($this->creation === true): ?>
			<ul class="titre textalic textsizeb">R&eacute;sultats Cr&eacute;ation</ul>
				Cr&eacute;ation de <?=count($this->tabCreation["monstres"])?> monstre(s) et de <?=count($this->tabCreation["groupesMonstres"])?> groupe(s) de monstres<br />
				
				Groupes : <br />
				<? foreach($this->tabCreation["groupesMonstres"] as $g): ?>
					Groupe Id <?=$g["id_groupe_monstre"]?> Nombre de membres <?=$g["nb_membres_max_groupe_monstre"]?><br />
				<? endforeach; ?>
				
				Monstres : <br />
				<? foreach($this->tabCreation["monstres"] as $g): ?>
					Monstre Id <?=$g["id_monstre"]?> <?=$g["nom_type"]?> (<?=$g["taille"]?>) 
					niveau:<?=$g["niveau_monstre"]?> pv:<?=$g["pv_restant_monstre"]?>
					x:<?=$g["x_monstre"]?> y:<?=$g["y_monstre"]?>
					FOR:<?=$g["force_base_monstre"]?> SAG:<?=$g["sagesse_base_monstre"]?>
					AGI:<?=$g["agilite_base_monstre"]?> VIG:<?=$g["vigueur_base_monstre"]?>
					ARMNAT :<?=$g["armure_naturelle_monstre"]?> DLA:<?=$g["duree_base_tour_monstre"]?><br />
				<? endforeach; ?>
			<? endif; ?>
			
			<br /><ul class="titre textalic textsizea">Statistiques actuelles</ul><br />

			Nombre de groupe actuellement en base : <?=$this->stats["nb_groupes"] ?><br />
			Nombre de monstre actuellement en base : <?=$this->stats["nb_monstres"] ?><br />
			Pourcentage de couverture globale : <?=$this->stats["couverture_globale"] ?> % (si l'on considère 1 monstre par case).<br />

			<br />
			<br /><ul class="titre textalic textsizec">Nombre de monstres par type</ul>
			<? foreach($this->stats["nb_monstre_par_type"] as $t): ?>
				<?=$t["nom_type"]?> : <?=$t["nombre"]?><br />
			<? endforeach; ?>
			
			<br />
			<br /><ul class="titre textalic textsizec">Nombre de monstres par taille</ul>
			<? foreach($this->stats["nb_monstre_par_taille"] as $t): ?>
				<?=$t["nom_feminin"]?> / <?=$t["nom_masculin"]?> : <?=$t["nombre"]?><br />
			<? endforeach; ?>
			<br />
			<br /><ul class="titre textalic textsizec">Couverture par zone</ul>
			<table align='center'>
			<th class='comp_titre'>N°</th>
			<th class='comp_titre'>Environnement</th>
			<th class='comp_titre'>Villes</th>
			<th class='comp_titre'>x_min</th>
			<th class='comp_titre'>x_max</th>
			<th class='comp_titre'>y_min</th>
			<th class='comp_titre'>y_max</th>
			<th class='comp_titre'>Nombre Cases</th>
			<th class='comp_titre'>Nombre Monstres</th>
			<th class='comp_titre'>Couverture</th>
			<? foreach ($this->zones as $zone) : ?>
				<tr>
					<td><?=$zone["id_zone"] ?></td>
					<td><?=htmlentities($zone["environnement"]) ?></td>
					<td><?=htmlentities($zone["villes"]) ?></td>
					<td><?=$zone["x_min"] ?></td>
					<td><?=$zone["x_max"] ?></td>
					<td><?=$zone["y_min"] ?></td>
					<td><?=$zone["y_max"] ?></td>
					<td><?=$zone["nombre_cases"] ?></td>
					<td><?=$zone["nombre_monstres"] ?></td>
					<td><?=$zone["couverture"] ?> % </td>
				</tr>
			<? endforeach; ?>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
</div>
<?php echo $this->render('footer.phtml'); ?>