<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
	<div class="box_corners">
		<span class="corners-top"><span></span></span>
	</div>
<div class="inner">
    <ul class="titre textalic textsizea">Administration R&eacute;f&eacute;rentiel Monstres</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">

			<form action="<?=$this->baseUrl ?>/administrationmonstres/referentiel/<?=$this->nomAction?>" method="post">
			<table align='center'>
			<tr>
				<td>
					Type
				</td>
				<td>
					<select name="id_type">
					<? foreach ($this->typesMonstre as $t) : ?>
					<option value="<?=$t["id_type_monstre"]?>"  <?if($this->referenceCourante["id_type_monstre"] == $t["id_type_monstre"]){echo "selected";}?>><?=$t["nom_type"]?></option>
					<? endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					Taille
				</td>
				<td>
					<select name="id_taille">
					<? foreach ($this->taillesMonstre as $t) : ?>
					<option value="<?=$t["id_taille_monstre"]?>" <?if($this->referenceCourante["id_taille_monstre"] == $t["id_taille_monstre"]){echo "selected";}?>><?=htmlentities($t["nom_feminin"])?> / <?=htmlentities($t["nom_masculin"])?></option>
					<? endforeach; ?>
					</select>
				</td>
			<tr>
			<tr>
				<td>
					Niveau Min
				</td>
				<td>
					<input type="textbox" name="niveau_min" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["niveau_min"]?>" />
				</td>
				</tr>
			<tr>
				<td>
					Niveau Max
				</td>
				<td>
					<input type="textbox" name="niveau_max" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["niveau_max"]?>" />
				</td>
				</tr>
			<tr>
				<td>
					Force
				</td>
				<td>
					<input type="textbox" name="p_force" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["p_force"]?>"/> %
				</td>
				</tr>
			<tr>
				<td>
					Sagesse
				</td>
				<td> 
					<input type="textbox" name="p_sagesse" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["p_sagesse"]?>" /> %
				</td>
				</tr>
			<tr>
				<td>
					Vigueur
				</td>
				<td>
					<input type="textbox" name="p_vigueur" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["p_vigueur"]?>" /> %
				</td>
				</tr>
			<tr>
				<td>
					Agilit&eacute;
				</td>
				<td>
					<input type="textbox" name="p_agilite" onkeypress="chiffres(event);" size="3" maxlength="2" value="<?=$this->referenceCourante["p_agilite"]?>" /> %
				</td>
				</tr>
			<tr>
				<td>
					Vue
				</td>
				<td>
					<input type="textbox" name="vue" onkeypress="chiffres(event);" size="3" maxlength="2"  value="<?=$this->referenceCourante["vue"]?>"/> 
				</td>
			</tr>
			<tr>
				<td colspan='2'>
					<? if ($this->modifier === true): ?>
						<input type="submit" class="button1" name="Modifier" value="Modifier la r&eacute;f&eacute;rence" />
						<input type="button" class="button1" name="Annuler" value="Annuler" onClick="document.location.href='<?=$this->baseUrl ?>/administrationmonstres/referentiel/'" />
						
					<? else: ?>
						<input type="submit" class="button1" name="Ajouter" value="Ajouter une nouvelle r&eacute;f&eacute;rence" />
					<? endif; ?>
				</td>
			</tr>
			</table>
			</form>
		<br><br>
			<table align='center'>
			<th class='comp_titre'>ID</th>
			<th class='comp_titre'>Type</th>
			<th class='comp_titre'>Taille</th>
			<th class='comp_titre'>Niveau Min</th>
			<th class='comp_titre'>Niveau Max</th>
			<th class='comp_titre'>% Force</th>
			<th class='comp_titre'>% Sagesse</th>
			<th class='comp_titre'>% Vigueur</th>
			<th class='comp_titre'>% Agilite</th>
			<th class='comp_titre'>Vue</th>
			<th class='comp_titre'>Edition</th>
			<? foreach ($this->refMonstre as $r) : ?>
				<tr>
					<td><?=$r["id_ref_monstre"] ?></td>
					<td><?=htmlentities($r["nom_type"]) ?></td>
					<td><?=htmlentities($r["taille"]) ?></td>
					<td><?=$r["niveau_min"] ?></td>
					<td><?=$r["niveau_max"] ?></td>
					<td><?=$r["p_force"] ?></td>
					<td><?=$r["p_sagesse"] ?></td>
					<td><?=$r["p_vigueur"] ?></td>
					<td><?=$r["p_agilite"] ?></td>
					<td><?=$r["vue"] ?> % </td>
					<td> <input type="button" class="button1" name="Modifier" value="Modifier" onClick="document.location.href='<?=$this->baseUrl ?>/administrationmonstres/referentiel/modifier/<?=$r["id_ref_monstre"] ?>';"/></td>
				</tr>
			<? endforeach; ?>
			</table>
		</ul>
	</div>
	&nbsp;
</div>
	<div class="box_corners">
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>