<?php echo $this->render('/commun/menu_bourg.phtml')?>
<br />
<div class="box_contenu textalic">
	<div class="titre textalic textsizea">
	Marché au Tabac
	</div><br />
	
<div id="mygrid_container" style="width:770px;height:650px;align:center"></div> 
<script>
	gridQString = '/marchetabac/renderxml?uid='+(new Date()).valueOf();
	
	mygrid = new dhtmlXGridObject('mygrid_container');
	mygrid.setImagePath("<?php echo $this->config->static->url?>/scripts/dhtmlxGrid-2.0.0/codebase/imgs/"); 
	mygrid.setHeader("Comté,Date,,Partie,Prix Vente Unitaire,Prix Reprise Unitaire,Stock Initial,Stock Restant");
	mygrid.setInitWidths("118,95,50,110,85,118,118,90,90");
	mygrid.setColAlign("left,center,center,center,right,right,right,right,right");
	mygrid.setColTypes("ro,ro,ro,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setSkin("braldahim");
	mygrid.setColSorting("str,str,str,str,str,str,str,str");
	mygrid.init();
	mygrid.loadXML(gridQString);
	mygrid.setSortImgState(true,3,"des");
</script>

</div>