<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<?=Bral_Helper_Box::haut(); ?>
<div class="inner">
    <ul class="titre textalic textsizea">Administration Cr&eacute;ation</ul>
    	&nbsp;
	<div class="contenu">
	    <ul class="box_contenu1 textalic">
	    TODO
		</ul>
	</div>
	&nbsp;
</div>
<?=Bral_Helper_Box::bas(); ?>
</div>
<?php echo $this->render('footer.phtml'); ?>