

<ul class="resultats">
<? if (count($this->tabHobbits) == 0): ?>
	<li class="resultat">Aucun Hobbit</li>
<? elseif (count($this->tabHobbits) > 15): ?>
	<li class="resultat">Trop de hobbits !</li>
<? else: ?>
	<?php
		foreach ($this->tabHobbits as $h) : 
	?>
		<li class="resultat" id_hobbit='<?=$h["id_hobbit"]?>' champ='<?=$this->champ?>' valeur='<?=htmlentities($h["nom"])?>'><?
			$pos = stripos($h["nom"], $this->pattern);
			$nom = htmlentities(substr($h["nom"], 0, $pos)) . '<font color="red">'.htmlentities(substr($h["nom"], $pos , strlen($this->pattern))) .'</font>'.htmlentities(substr($h["nom"], $pos + strlen($this->pattern)));

			echo $nom ." (".$h["id_hobbit"].")" ?></li>
	<?php endforeach; ?>
<? endif; ?>
</ul>