<? if (Zend_Registry::get("estMobile")) :?>
Heure serveur : <span id='date_heure' class=''>&nbsp;</span>
<? elseif (!Zend_Registry::get("estMobile") && !Zend_Registry::get("estWork")) :?>
<? if (isset($this->user) ): ?>

<br/>
</div>
<? endif;?>
<div id="frisebot" ></div>
 <div class="inner_bot">
  <div class="inner_footer">
 	<span id='date_heure' class=''>&nbsp;</span>
 	| <a href="http://www.braldahim.com">www.braldahim.com</a>
 	<? if (isset($this->user) && isset($this->user->email_braldun)) : ?> 
 	| <span id='nb_connectes' class=''>&nbsp;</span><br/>
 	<? endif;?>
 	<table align="center">
 	<tr>
 		<td align="center">
		 	<a href="http://www.jeuxweb.org">Braldahim est hébergé par l'Association JeuxWeb.org ASBL</a> | 
 		</td>
 		<td>
 		<a href="http://www.braldahim.com/abus/">Signaler un abus</a> | 
 		</td>
 		<td>
 		<a href="http://feeds.braldahim.com/braldahim-chronique" class="feed">Flux RSS</a>
 		</td>
 	</tr>
 	</table>
 	<a href="http://www.jeuxweb.org" target="_blank" title="Braldahim est hébergé par l'Association JeuxWeb.org ASBL">
 		<img src="<?=$this->config->static->url?>/images/externe/banner_jw-156-20.gif" alt="Jeux Web" border="0" height="20" width="156" />
	</a>
	<br/>
	<p style="text-align:center;font-size:9px;">
<a href="http://www.jeux-alternatifs.com/Braldahim-jeu301_hit-parade_1_1.html" target="_blank"><img src="<?=$this->config->static->url?>/images/externe/hitP_88x31_v2.gif" border="0" alt="" width="88px" height="31px"/></a>
<a href="http://www.gamersroom.com/vote.php?num=1615" title="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs"><img src="<?=$this->config->static->url?>/images/externe/bouton4.gif" width="88px" height="31px" alt="Annuaire des jeux en ligne gratuits - Jeux web - Jeux alternatifs" style="border:none" /></a>
<a href="http://www.sitacados.com/sites-jeux-gratuits-jeux-roles.html"  title="Jeux de rôle" target="_blank">RPG</a>
</p>
	
<br/><br/>
 	
</div>
</div>
<? endif;?>

<?php echo $this->render('footer-scripts.phtml'); ?>  