<div id="frisebot" ></div>
 <div class="inner_bot">
 	<span id='date_heure' class=''>&nbsp;</span>
 	<a href="http://www.braldahim.com">www.braldahim.com</a>
 	<? if (isset($this->user) && isset($this->user->email_hobbit)) : ?> 
 		| <span id='nb_connectes' class=''>&nbsp;</span><br>
 	<? endif;?>
 	<table align="center">
 		<tr>
 			<td align="center">
			 	<a href="http://www.jeuxweb.org">Braldahim est hébergé par l'Association JeuxWeb.org ASBL</a> | 
 			</td>
 			<td>
 			<a href="http://www.braldahim.com/abus/">Signaler un abus</a> | 
 			</td>
 			<td>
 			<a href="http://jeu.braldahim.com/Feed/" class="feed">Flux RSS</a>
 			</td>
 		</tr>
 	</table>
 	<a href="http://www.jeuxweb.org" target="_blank" title="Braldahim est hébergé par l'Association JeuxWeb.org ASBL" alt="JeuxWeb.org">
 		<img src="http://www.mountyhall.com/images/Banner/banner_jw.gif" alt="Jeux Web" border="0" height="20" width="156">
	</a>
 	<br><br>
 	
 </div>

<? if ($this->config->tracker->enabled == "1") : ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("<?=$this->config->tracker->id?>");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<? endif; ?>

<?="</body></html>"?>
