<?php if ($this->config->tracker->enabled == "1") : ?>
<script type="text/javascript">
var _gaq = _gaq || [];
<?php Zend_Loader::loadClass("Bral_Util_Tracker"); ?>_gaq.push(['_setAccount', '<?php echo Bral_Util_Tracker::getKey()?>']);_gaq.push(['_trackPageview']);
(function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();
</script>
<?php endif; ?>
</body></html>