
<script type="text/javascript" src="/public/scripts/overlib_423/allbraldahim.js"></script>
<script type="text/javascript" src="/public/scripts/sorthtmltable_200/sortHTMLTable.js"></script>
<script type="text/javascript" src="/public/scripts/modalbox_160/modalbox.js"></script>

<? if ($this->config->tracker->enabled == "1") : ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("<?=$this->config->tracker->id?>");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<? endif; ?>

</body></html>
