<?php if (isset($this->user)): ?>

<?php if (Zend_Registry::get("estMobile")): ?>
<div id="wrappermobile">
<div id="box_cockpit"></div>
<div id="racinemobile" class="box_racine">
<?php else: ?>
<div id="wrapper">
<div id="racine" class="box_racine">
</div>
		<div id="box_cockpit"></div>
		<div id=menu_actions></div>
		<input type='hidden' id='nb_valeurs-competencefavorite' name='nb_valeurs-competencefavorite' value='1'>
		<input type='hidden' id='valeur_1-competencefavorite' name='valeur_1-competencefavorite' value='-1'><br/>
		<?php endif; ?>

	<?php endif; ?>
