<div id="header">
	<div id="frisetopa">
	<?php if (Zend_Registry::get("estWork")) : ?>
		<h1><a href="/">Work</a></h1>
	<?php else:?>
		<h1><a href="/">Braldahim - Jeu</a></h1>
	<?php endif;?>
	</div>
	<div id="frisetop">
	
	<?php if (Zend_Registry::get("estWork")) : ?>
		<center><input type='button' class='button1' value='Afficher / Cacher les liens' onclick="switch2div('menuWork', 'menuFoo');"></center>
		<div id='menuFoo' style="display:none"></div>
		<div id='menuWork' style="display:none">
			<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>
		</div>
	<?php else: ?>
		<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>	
	<?php endif;?>

	</div>
	<div id="frisebot">
	</div>
</div>