<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr"> 
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	
	<script type="text/javascript" src="/public/scripts/prototype_1602/prototype.js"></script> 
	<script type="text/javascript" src="/public/scripts/scriptaculous_181/scriptaculous.js" ></script>
	<script type="text/javascript" src="/public/scripts/modalbox_160/modalbox.js"></script>
	<!-- <script type="text/javascript" src="/public/scripts/braldahim/braldahim_001/braldahim.js-BAK"></script>-->
    
	<script type="text/javascript" src="/public/scripts/braldahim/m_action-004.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/m_display-009.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/m_recherche-006.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/uddeimtools-001.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/bbsmile-001.js"></script>
	
	<script type="text/javascript" src="/public/scripts/overlib_421/overlib.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_421/overlib_exclusive.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_421/overlib_fade.js"></script>
	
	<title>Braldahim</title>
	<link href="/public/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" media="screen" href="/public/styles/braldahim_defaut/uddeim.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/public/styles/braldahim_defaut/braldahim-003.css" />
</head>