<div id="erreur" class="box_erreur" style="display:none"></div>
<div id="erreur_catch" class="box_erreur" style="display:none">
<textarea id="erreur_catch_contenu" rows="15" cols="60"></textarea>
</div>

<? if (isset($this->user) ): ?>

<? if ($this->estMobile):?>
<div id="wrappermobile">
<div id="racinemobile" class="box_racine">
<? else:?>
<div id="wrapper">
<div id="racine" class="box_racine">
<? endif;?>
</div>
<? endif; ?>


