<div id="header">
	<div id="frisetopa">
	<?php if (Zend_Registry::get("estWork")) : ?>
		<h1><a href="/">Work</a></h1>
	<?php else:?>
		<h1><a href="/">Braldahim - Jeu</a></h1>
	<?php endif;?>
	</div>
	<div id="frisetop">
	
	<?php if (Zend_Registry::get("estWork")) : ?>
		<center><input type='button' class='button1' value='Afficher / Cacher les liens' onclick="switch2div('menuFoo', 'menu');"></center>
		<div id='menuFoo'></div>
	<?php endif;?>

	<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>
	
	</div>
	<div id="frisebot">
	</div>
</div>