<?php if (isset($this->user) && isset($this->user->email_braldun) && $this->controleur != "voir") : ?> 

<div id="header">
	<div id="frisetopa">
		<?php if (!Zend_Registry::get("estMobile")):?><h1>&nbsp;</h1><?php endif;?>
		
		
		<?php if (!Zend_Registry::get("estMobile")):?>
		 <?php if ($this->user->administrateur === true) : ?>
			  	<span class='alabel' onclick='_get_("/administrationajax/doaction?caction=do_administrationajax_activeradminvue");'>[Admin Vue]</span>
			  <?php endif; ?>
		  <?php echo $this->escape($this->user->prenom_braldun);?> <?php echo $this->escape($this->user->nom_braldun);?> |
		 
			 <?php if ($this->user->administrateur === true) : ?>
			  	<a href="/Administration/" class="menu_lien">Administration</a> |
			 <?php endif; ?>
			 <?php if ($this->user->administrateur === true || $this->user->gestion === true) : ?>
				 <a href="/Gestion/" class="menu_lien">Gestion</a> |
			 <?php endif; ?>
			 <a href="/interface/" class="menu_lien">Interface</a> |
		 <?php endif;?>
		 <?php if ($this->user->gardeEnCours === false) : ?>
		  	<a href="/Parametres/" class="menu_lien">Param&egrave;tres</a> |
		 <?php endif; ?>
		 <?php if (!Zend_Registry::get("estMobile")):?>
			 <a href="http://regles.braldahim.com/wiki/Charte">Charte</a> | 
			 <label class="alabel" style="text-decoration:underline" onclick="javascript:ouvrirWin('/voir/');">Voir</label> |
		 <?php endif;?> 
		 <a href="/auth/logout"> D&eacute;connexion </a>
		 
		 <?php if ($this->user->gardeEnCours === true) : ?>
		 	| <a href="/Gardiennage/" style="background-color:#FF6347;"> Gardiennage de <?php echo htmlspecialchars($this->user->prenom_braldun) ?> <?php echo htmlspecialchars($this->user->nom_braldun) ?> (<?php echo $this->user->id_braldun?>) en cours</a>
		 <?php endif; ?>
		 
		 <div style="line-height: 22px;">&nbsp;</div>
		 
		 <div class='braltip lune' >
		  <?php if (!Zend_Registry::get("estMobile")):?>
		  	  <?php Zend_Loader::loadClass("Bral_Helper_Lune"); echo Bral_Helper_Lune::affiche(); ?>
		  <?php endif;?>
		 </div>		 
		
		<?php if (Zend_Registry::get("estMobile")):?>
		<?php $s=""; if ($this->user->points_distinctions_braldun > 1): $s='s'; endif; ?>
	   			<span title="Points actualisés une fois par jour." onclick='Javascript:_get_("/interface/load/?box=box_titres");' class="pointsdistinctions"><?php echo $this->user->points_distinctions_braldun ?> point<?php echo $s?></span>
		<?php else: ?>
			<?php $s=""; if ($this->user->points_distinctions_braldun > 1): $s='s'; endif; ?>
	   		<span title="Points actualisés une fois par jour." onclick='Javascript:_get_("/interface/load/?box=box_titres");' class="pointsdistinctions"><?php echo $this->user->points_distinctions_braldun ?> point<?php echo $s?> de distinction</span>
	   	<?php endif;?>
	</div>
	<?php if (!Zend_Registry::get("estMobile")):?>
	<div id="frisetop">
		<?php if (Zend_Registry::get("estWork")) : ?>
		<center><input type='button' class='button1' value='Afficher / Cacher les liens' onclick="switch2div('menuWork', 'menuFoo');"></center>
		<div id='menuFoo' style="display:none"></div>
		<div id='menuWork' style="display:none">
			<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>
		</div>
	<?php else: ?>
		<script language="Javascript" src="<?php echo $this->config->url->static?>/index/menu"></script>	
	<?php endif;?>
	</div>
	<div id="frisebot">
	</div>
	<?php else:?>
		Heure serveur : <span id='date_heure' class=''>&nbsp;</span>
	<?php endif;?>
</div>
	
	<?php if ($this->controleur == "interface") : ?>
	<div id="boite_d">
	<button class="butCarnet" title="Carnet" onclick='Javascript:_get_("/interface/load/?box=box_carnet");' title="Carnet">Carnet</button>
	<button class="butMessagerie" title="Messagerie" onclick='Javascript:_get_("/interface/load/?box=box_messagerie");' title="Carnet">&nbsp;</button>
	</div>
<?php endif; ?>

<?php endif; ?>
