<div id="modalPage">
    <div class="modalBackground"></div>
    <div class="modalContainer">
 		<div id="box_chargement" class="box_chargement">
			 <div class="inner chargement">
			 Chargement en Cours<br/><img src="<?php echo $this->config->url->static?>/images/wait.gif" alt="" width="16" height="16"/>
		 	</div>
		 </div>
    </div>
</div>
<div id="box_warning" class="box_warning" style="display: none"></div>