<div id="modalPage">
    <div class="modalBackground"></div>
    <div class="modalContainer">
 		<div id="box_chargement" class="box_chargement">
			 Chargement en Cours<br/><img src="<?php echo $this->config->url->static?>/images/divers/loading.gif" alt="" width="16" height="16"/>
		 </div>
    </div>
</div>
<div id="box_warning" class="box_warning" style="display: none"></div>
<div id="box_effets" class="box_effets" style="display: none"></div>
<div id="box_personnage" class="box_personnage" style="display: none"></div>
<div id="box_competences" class="box_competences" style="display: none"></div>
<div id="box_messagerie" class="box_messagerie" style="display: none"></div>
<div id="box_carnet" class="box_carnet" style="display: none"></div>
<div id="box_titres" class="box_titres" style="display: none"></div>
<div id="box_laban" class="box_laban" style="display: none"></div>
<div id="box_charrette" class="box_charrette" style="display: none"></div>
<div id="box_coffre" class="box_coffre" style="display: none"></div>
<input type="hidden" id="vueFixee" value="-1">