<br/>
<br/>
<table width="300px;" align="center">
	<tr>
		<td>
		<div class="inner">
		<div class="contenu">
		<ul class="titre textalic textsizeb">
			<a href="/gazette" title="Voir les Archives de la Gazette"
				style="text-decoration: none">Archives de La Gazette</a>
		</ul>

		<ul class="titre textalic textsizeb">
			<a href="/annonces" title="Voir les Archives des Annonces"
				style="text-decoration: none">Archives des Annonces</a>
		</ul>
		</div>
		</div>
		</td>
	</tr>
</table>
