<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr"> 
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/prototype.js"></script>

	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/scriptaculous.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/modalbox.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/tiny_mce/tiny_mce.js"></script>
    
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/m_action.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/m_display.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/m_recherche.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/overlib/overlib.js"><!-- overLIB (c) Erik Bosrup --></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/overlib/overlib_exclusive.js"><!-- overLIB (c) Erik Bosrup --></script>
	
	<script language="javascript" type="text/javascript">
		tinyMCE.init({
			mode : "textareas",
			theme : "advanced",
			elements : "valeur_10",
			theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,bullist,numlist,undo,redo",
			theme_advanced_buttons2 : "",
			theme_advanced_buttons3 : "",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "center",
			language : 'fr',
		});
	</script>
	
	<title><?php echo $this->escape($this->title); ?></title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/braldahim_defaut/site.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/braldahim_defaut/modalbox.css" />
</head>

<?php if($this->user && $this->controleur == "interface") : ?> 
 <body onLoad="_get_('<?=$this->baseUrl ?>/interface/boxes');">
<?php else: ?>
<body>

<?php endif; ?>
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>

<?php if (isset($this->user) && isset($this->user->nom_hobbit)) : ?> 
<b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4"></b><b class="xb5"></b><b class="xb6"></b><b class="xb7"></b>
 <div class="inner">
 <span id='date_heure' class=''>&nbsp;</span>
  <?=$this->escape($this->user->nom_hobbit);?> | 
  <? if ($this->user->administrateur === true) : ?>
  	<a href="<?=$this->baseUrl ?>/administration/" class="menu_lien">Administration</a> |
  <? endif; ?>
  <a href="<?=$this->baseUrl ?>/interface/" class="menu_lien">Interface</a> |
  <? if ($this->user->gardeEnCours === false) : ?>
  	<a href="<?=$this->baseUrl ?>/parametres/" class="menu_lien">Param&egrave;tres</a> |
  <? endif; ?>  
  <a href="<?=$this->baseUrl ?>/auth/logout"> D&eacute;connexion </a>
  
 </div>
<b class="xb7"></b><b class="xb6"></b><b class="xb5"></b><b class="xb4"></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
<?php endif; ?>

<?php if ($this->user && ($this->controleur == "interface")) : ?> 
  <div id="box_action" class="box_action" style="display:none"></div>
  <div id="erreur" class="box_erreur" style="display:none"></div>
  <div id="informations" class="box_informations" style="display:none"></div>
  <div id="box_chargement" class="box_chargement" style="display:block">
	 <b class="xb1"></b><b class="xb2"></b><b class="xb3"></b><b class="xb4" style='background-color:#CC6666'></b><b class="xb5" style='background-color:#CC6666'></b><b class="xb6" style='background-color:#CC6666'></b><b class="xb7" style='background-color:#CC6666'></b>
	 <div class="inner" style='background-color:#CC6666'>
	 Chargement en Cours<br><img src="<?=$this->baseUrl ?>/public/images/wait.gif" />
	 </div>
	 <b class="xb7" style='background-color:#CC6666'></b><b class="xb6" style='background-color:#CC6666'></b><b class="xb5" style='background-color:#CC6666'></b><b class="xb4" style='background-color:#CC6666'></b><b class="xb3"></b><b class="xb2"></b><b class="xb1"></b>
  </div>
  <div id="racine" class="box_racine">
<?php endif; ?>
</div>