<? include('headerHead.phtml'); ?>
<? if($this->user && $this->controleur == "interface") : ?>
<body onload="_get_('/interface/boxes');">
<? else: ?>
<body>
<? endif; ?>

<? if (Zend_Registry::get("estWork")) : ?>
<span style=" border : 2px solid;float:left;position:absolute; z-index:-10">
Instance Work Braldahim : moins d'images, plus sobre et discrète</span>
</div>
<? endif; ?>
<!--[if lt IE 8]>
<div style=" border : 2px solid red;background-color:red;float:center;position:absolute; width:100%; z-index:10000">
<big>Vous utilisez Internet Explorer 6 ou 7. Braldahim n'est pas compatible avec Internet Explorer 6 et 7.
Plus d'information <a href="http://regles.braldahim.com/wiki/Braldahim_sous_Internet_Explorer">sur le wiki.</a>
Vous pouvez utiliser <a href="http://www.mozilla-europe.org/fr/firefox/">Firefox</a>, <a href="http://www.apple.com/fr/safari/">Safari</a>, <a href="http://www.opera.com/">Opéra</a> etc...</big>
</div>
<![endif]-->

<? include('headerDiv.phtml'); ?>

<? include('headerAuth.phtml'); ?>

<? include('headerMenu.phtml'); ?>

<? if ($this->user && ($this->controleur == "interface")) : ?>
<div id="BB_overlay" style="display: none;" class="BBoverlay"></div>
<div id="BB_windowwrapper" style="display: none">
<div id="BB_window">
<div id="BB_frame">
	<div id="BB_header">
		<div id="BB_titre"></div>
		<a id="BB_close" title="Fermer" href="#" onclick="fermeBralBox()" style="display:none"><span>×</span></a>
	</div>

	<div id="box_action" class="box_action" style="display: none"></div>
	<div id="box_informations" class="box_informations" style="display: none"></div>
	<div id="box_warning" class="box_warning" style="display: none"></div>
</div>
</div>
</div>


<? endif; ?> <? include('headerErreurRacine.phtml'); ?>