<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr"> 
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	
	<script type="text/javascript" src="/public/scripts/prototype_1602/prototype.js"></script> 
	<script type="text/javascript" src="/public/scripts/scriptaculous_181/scriptaculous.js" ></script>
	<script type="text/javascript" src="/public/scripts/modalbox_160/modalbox.js"></script>
	<!-- <script type="text/javascript" src="/public/scripts/braldahim/braldahim_001/braldahim.js-BAK"></script>-->
    
	<script type="text/javascript" src="/public/scripts/braldahim/m_action-009.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/m_display-013.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/m_recherche-008.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/uddeimtools-001.js"></script>
	<script type="text/javascript" src="/public/scripts/braldahim/bbsmile-001.js"></script>
	
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib_exclusive.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib_fade.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib_anchor.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib_positioncap.js"></script>
	<script type="text/javascript" src="/public/scripts/overlib_423/overlib_draggable.js"></script>
	
	
	<title>Braldahim</title>
	<link href="/public/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" media="screen" href="/public/styles/braldahim_defaut/uddeim.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/public/styles/braldahim_defaut/braldahim-019.css" />
	<link rel="apple-touch-icon" href="/public/images/mobile/icone-iphone.png"/>
	
	<link media="only screen and (max-device-width: 480px)"  href="/public/styles/braldahim_defaut/iphone-001.css" type="text/css" rel="stylesheet">
	
</head>