
<br /><br />
<ul class="titre textalic textsizea">Profil Officiel</ul>
<br />

<table class="table_liste" style="width:90%;">
	
  <tr class="table_liste">
	<th rowspan="8"><?=Bral_Helper_Image::afficherAvatar($this->hobbit["url_avatar_hobbit"]); ?></th>
	<th>Date de cr&eacute;ation</th>
	<th>Le <?=Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y \&\a\g\r\a\v\e\; H:i:s ',$this->hobbit["date_creation_hobbit"]); ?></th>
  </tr>
  <tr class="table_liste">
	<th>Communaut&eacute;</th>
	<td class="table_liste" nowrap>
	<? if ($this->communaute == null) : ?>
		<i>Aucune</i>
	<? else: ?>
		<a href="/voir/communaute/?communaute=<?=$this->communaute["id_communaute"] ?>">
		<?=$this->communaute["nom_communaute"] ?>, n&deg;<?=$this->communaute["id_communaute"] ?>
		</a>
	<? endif; ?>
	</td>
  </tr>
  <tr class="table_liste">
	<th>Niveau</th>
	<td class="table_liste"><?=$this->hobbit["niveau_hobbit"] ?></td>
  </tr>
  <tr class="table_liste">
	<th>Nombre de morts</th>
	<td class="table_liste"><?=$this->hobbit["nb_mort_hobbit"] ?></td>
  </tr>
  <tr class="table_liste">
	<th>Nombre de meurtres Hobbit</th>
	<td class="table_liste"><?=$this->hobbit["nb_hobbit_kill_hobbit"] ?></td>
  </tr>
  <tr class="table_liste">
	<th>Nombre de meurtres Monstre</th>
	<td class="table_liste"><?=$this->hobbit["nb_monstre_kill_hobbit"] ?></td>
  </tr>
  <tr class="table_liste" valign="top">
	<th>M&eacute;tier<? if ($this->possedeMetier && $this->tabMetierCourant != null && count($this->tabMetiers) > 0) :
		echo "s";
	   endif; ?>
	</th>
	<td class="table_liste">
	<? if (!$this->possedeMetier): ?>
	   	Aucun m&eacute;tier
	<? else : ?>
			<? $liste = "";?>
		   	Actuellement :
		  	 	<?=$this->tabMetierCourant["nom"] ?>
			<br /><br />
		   	<? if (count($this->tabMetiers) == 1): ?>
		   		Il pratique &eacute;galement le m&eacute;tier suivant : <br />
		   	<? elseif (count($this->tabMetiers) > 1): ?>
		   		Il pratique &eacute;galement les m&eacute;tiers suivants : <br />
		   	<? endif; ?>	
		   	<? if (count($this->tabMetiers) > 1): ?>
				<?
				$liste = "";
				foreach ($this->tabMetiers as $m) :
				$liste .= $m["nom"].", ";
				  endforeach; ?>
				  <? 
				  if ($liste != "") {
				  	$liste = mb_substr($liste, 0, -2); 
				  }
				  ?>
		    <? endif; ?>
		    <? if ($liste != "") : ?>
		    	<?=$liste ?>
		    <? endif;?>
	   <? endif; ?>
	</td>
  </tr>
  <tr class="table_liste">
	<th>Équipement</th>
	<td class="table_liste"><?=Bral_Helper_ProfilEquipement::afficher($this->tabTypesEmplacement); ?></td>
  </tr>
</table>

<br /><br />

<ul class="titre textalic textsizea">Profil Non Officiel</ul>
<ul class="titre textalic textsizec">Renseign&eacute; par le joueur</ul>
<table class="table_liste" style="width:90%;">
<tr class="table_liste">
	<td class="table_liste" style="text-align:left; width:10%;'">
		<?=Bral_Helper_Image::afficherBlason($this->hobbit["url_blason_hobbit"]); ?>
	</td>
	<td class="table_liste">
		<?=Bral_Util_BBParser::bbcodeReplace($this->hobbit["description_hobbit"]); ?>
	</td>
</tr>
</table>
<br /><br />