<? Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
 
<table class="table_liste" style="width:90%" <? if ($this->idPotionsTable != false) : ?> id="<?=$this->idPotionsTable?>"<? endif; ?>>
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
	  	<th>&nbsp;</th>
		<th>Nom</th>
		<th>Qualit&eacute;</th>
		<th>Niveau</th>
		<th>Type</th>
		<th>Effet sur</th>
		<th>Caract&eacute;ristiques</th>
		<? if ($this->estElementsEtal === true) : ?>
			<th>Prix</th>
			<th>Commentaire du vendeur</th>
		<? endif; ?>
		<? if ($this->estElementsEtalAchat === true) : ?>
			<th>Marchander / Acheter</th>
		<? endif; ?>
	  </tr>
	</thead>
	<tbody>
		<? if (count($this->potions) > 0) :?>
			<? $i = 0;
			   foreach($this->potions as $p) :?>
				  <tr class="table_liste<?=($i % 2);$i++; ?>">
			  		<td class="table_liste"><?=$p["id_potion"] ?></td>
			  		<td class="table_liste"><img src='/public/styles/braldahim_defaut/images/type_potion/type_potion_<?=$p["id_type_potion"]?>.png' alt="<?=htmlspecialchars($p["nom"])?>"/></td>
			  		<td class="table_liste"><?=htmlspecialchars($p["nom"]) ?></td>
			  		<td class="table_liste"><?=htmlspecialchars($p["qualite"]) ?></td>
			  		<td class="table_liste"><?=$p["niveau"] ?></td>
			  		<td class="table_liste">
			  		<?=$p["nom_type"] ?>
			   		</td>
			  		<td class="table_liste">
			  		<? if ($p["bm_type"] == null) : ?>
			  			État équipement
			  		<? else :?>
				  		<?=$p["bm_type"] ?> <?=$p["caracteristique"] ?>
				  		<? if ($p["bm2_type"] != null) : ?>
				  			<br /><?=$p["bm2_type"] ?> <?=$p["caracteristique2"] ?>
				  		<? endif;?>
			  		<? endif;?>
			  		</td>
			  		<td class="table_liste">
			  			<div class='braltip'>
			  			<?=Bral_Helper_DetailPotion::afficherTooltip($p);?>
						<img src="/public/images/info_icon.gif"/>
						</div>
					</td>
			  		<? if ($this->estElementsEtal === true) : ?>
						<td class="table_liste" nowrap><?=Bral_Helper_DetailPotion::afficherPrix($p);?></td>
						<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($p["commentaire_vente_echoppe_potion"])?></td>
					<? endif; ?>
					<? if ($this->estElementsEtalAchat === true) : ?>
						<td class="table_liste">
						<input type="button" class='button1' onclick='_get_("/echoppe/doaction?caction=ask_echoppe_acheterpotion&idPotion=<?=$p["id_potion"] ?>");' value="<?=$this->config->game->echoppe->nb_pa_service ?> PA - Acheter">
						</td>
					<? endif; ?>
				  </tr>
			<? endforeach; ?>
		<? else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune potion ou vernis</i></td></tr>
		<? endif; ?>
	</tbody>
</table>