<? Zend_Loader::loadClass("Bral_Helper_DetailPotion"); ?>
<input type='hidden' id='nb_valeurs' name='nb_valeurs' value='1'>
<input type='hidden' id='valeur_1' name='valeur_1' value='-1'>
 
<table class="table_liste" style="width:90%">
	<thead class="table_liste">
	  <tr class="table_liste">
	  	<th>N&deg;</th>
		<th>Nom</th>
		<th>Qualit&eacute;</th>
		<th>Niveau</th>
		<th>Type</th>
		<th>Effet sur</th>
		<th>Caract&eacute;ristiques</th>
		<? if ($this->estEquipementsPotionsEtal === true) : ?>
			<th>Prix</th>
			<th>Commentaire du vendeur</th>
		<? endif; ?>
		<? if ($this->estEquipementsPotionsEtalAchat === true) : ?>
			<th>Marchander / Acheter</th>
		<? endif; ?>
	  </tr>
	</thead>
	<tbody>
		<? if (count($this->potions) > 0) :?>
			<? $i = 0;
			   foreach($this->potions as $p) :?>
				  <tr class="table_liste<?=($i % 2);$i++; ?>">
			  		<td class="table_liste"><?=$p["id_potion"] ?></td>
			  		<td class="table_liste"><?=htmlspecialchars($p["nom"]) ?></td>
			  		<td class="table_liste"><?=htmlspecialchars($p["qualite"]) ?></td>
			  		<td class="table_liste"><?=$p["niveau"] ?></td>
			  		<td class="table_liste"><?=$p["bm_type"] ?></td>
			  		<td class="table_liste"><?=$p["caracteristique"] ?></td>
			  		<td class="table_liste">
						<img src="/public/images/info_icon.gif" <?=Bral_Helper_DetailPotion::afficherJs($p);?> />
					</td>
			  		<? if ($this->estEquipementsPotionsEtal === true) : ?>
						<td class="table_liste" nowrap><?=Bral_Helper_DetailPotion::afficherPrix($p);?></td>
						<td class="table_liste"><?=Bral_Util_BBParser::bbcodeReplace($p["commentaire_vente_echoppe_potion"])?></td>
					<? endif; ?>
					<? if ($this->estEquipementsPotionsEtalAchat === true) : ?>
						<td class="table_liste">
						<input type="button" class='button1' onClick='$("nb_valeurs").value=1;$("valeur_1").value=<?=$p["id_potion"] ?>; _get_("/echoppe/doaction?caction=ask_echoppe_acheterpotion");' value="<?=$this->config->game->echoppe->nb_pa_service ?> PA - Acheter">
						</td>
					<? endif; ?>
				  </tr>
			<? endforeach; ?>
		<? else: ?>
			<tr class="table_liste"><td class="table_liste" colspan="20"><i>aucune potion</i></td></tr>
		<? endif; ?>
	</tbody>
</table>