CREATE TABLE `recette_equipements` (
  `id_recette_equipement` int(11) NOT NULL auto_increment,
  `id_fk_type_recette_equipement` int(11) NOT NULL,
  `niveau_recette_equipement` int(11) NOT NULL,
  `poids_recette_equipement` float NOT NULL,
  `qualite_recette_equipement` enum('mediocre','standard','bonne') NOT NULL,
  `armure_recette_equipement` int(11) NOT NULL,
  `force_recette_equipement` int(11) NOT NULL,
  `agilite_recette_equipement` int(11) NOT NULL,
  `vigueur_recette_equipement` int(11) NOT NULL,
  `sagesse_recette_equipement` int(11) NOT NULL,
  `vue_recette_equipement` int(11) NOT NULL,
  `bm_attaque_recette_equipement` int(11) NOT NULL,
  `bm_degat_recette_equipement` int(11) NOT NULL,
  `bm_defense_recette_equipement` int(11) NOT NULL,
  `id_fk_metier_recette_equipement` int(11) NOT NULL,
  `cuir_recette_equipement` int(11) NOT NULL,
  `fourrure_recette_equipement` int(11) NOT NULL,
  `planche_recette_equipement` int(11) NOT NULL,
  `tambe_recette_equipement` int(11) NOT NULL,
  `anga_recette_equipement` int(11) NOT NULL,
  `mithril_recette_equipement` int(11) NOT NULL,
  `galvorn_recette_equipement` int(11) NOT NULL,
  `emplacement_recette_equipement` enum('tete','cou','corps','ceinture','main','main gauche','main droite','deux mains') NOT NULL,
  PRIMARY KEY  (`id_recette_equipement`),
  KEY `id_fk_metier_recette_equipement` (`id_fk_metier_recette_equipement`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1