<? if ($this->deposerOk === true) : ?>
 	Choississez un &eacute;l&eacute;ment &agrave; d&eacute;poser &agrave; terre.<br />
	<select name="valeur_2" id="valeur_2" onChange="if (this.value > 0) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	 	<option value="-1">(Choisis un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->autres as $k => $v) :?>
 			<option value="<?=$k?>"><?=$v["nom"] ?> : <?=$v["nb"] ?></option>
	 	<? endforeach; ?>
	</select>
<? endif; ?>
<br />
Quantit&eacute; &agrave; d&eacute;poser : <br />
	<input type='textbox' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);">

	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />