Choississez un &eacute;quipement (ou plusieurs en cliquant sur ctrl) &agrave; d&eacute;poser.<br />
<select multiple size="5" name="valeur_10" id="valeur_10" onChange="<?=$jsBtn?>">
	 <? foreach($this->equipements as $e) :?>
	 	<option value="<?=$e["id_equipement"]?>">n&deg;<?=$e["id_equipement"] ?> <?=$e["nom"]." ".addslashes($e["suffixe"])." de qualit&eacute; ".$e["qualite"] ?>, niveau <?=$e["niveau"] ?></option>
	 <? endforeach; ?>
</select>