<? if (count($this->munitions) > 0) :?>
	Munitions:<br/>
	
	<select name="valeur_2" id="valeur_2" onChange="if (($('valeur_2').value > 0 && $('valeur_3').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	 	<option value="-1">(Choisis un type de munition brut)</option>
	 	<? foreach($this->munitions as $m) :?>
	 		<option value="<?=$m["id_type_munition"]?>"><?=$m["type"]?> : <?=$m["quantite"]?></option>
	 	<? endforeach; ?>
	</select>
	<br/>
	Quantit&eacute; &agrave; d&eacute;poser : <br />
	<input type='text' maxlength='7' size='7' name='valeur_3' id='valeur_3' value='0' onkeypress="chiffres(event);" onkeyup="if (($('valeur_2').value > 0 && $('valeur_3').value > 0)) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true}">
	
<? else: ?>
	Aucune munition &agrave; d&eacute;poser.
	<input type='hidden' name='valeur_2' id='valeur_2' value='-1' />
	<input type='hidden' name='valeur_3' id='valeur_3' value='0' />
<? endif; ?>
	<input type='hidden' name='valeur_4' id='valeur_4' value='0' />
	<input type='hidden' name='valeur_5' id='valeur_5' value='0' />
<br>