Choississez une potion &agrave; d&eacute;poser &agrave; terre.<br />
<? if ($this->deposerOk === true) : ?>
<select name="valeur_2" id="valeur_2" onChange="if (this.value > 0) {$('bouton_deposer').disabled=false} else {$('bouton_deposer').disabled=true} ">
	 	<option value="-1">(Choisis une potion)</option>
	 	<? foreach($this->potions as $p) :?>
	 		<option value="<?=$p["id_potion"]?>">Potion <?=htmlentities($p["nom"]) ?> de qualit&eacute; <?=htmlentities($p["qualite"]) ?> (n&deg;<?=$p["id_potion"] ?>) </option>
	 	<? endforeach; ?>
</select>
<? endif; ?>