Choississez une rune (ou plusieurs en cliquant sur ctrl) &agrave; d&eacute;poser.<br />
<select multiple size="5" name="valeur_8" id="valeur_8" onChange="<?=$jsBtn?>">
	 <? foreach($this->runes as $r) :?>
	 	<option value="<?=$r["id_rune"]?>">Rune n&deg;<?=$r["id_rune"] ?>, 
	 	<? if ($r["est_identifiee"] == "oui") : ?>
	 		<?=$r["type"] ?>
	 	<? else: ?>
	 		rune non identifi&eacute;e
	 	<? endif; ?>
	 	</option>
	 <? endforeach; ?>
</select>