<?php if ($this->effetPotion == true) :
	$nb = count($this->effetPotionPotions);
	if ($nb > 1) { $s = 's'; $verb = 'ont'; } else { $s =''; $verb = 'a'; }
	?>
	<br /><b><?php echo $nb ?> potion<?php echo $s ?> <?php echo $verb?> eu de l'effet sur vous.</b><br />
	
	<?php foreach($this->effetPotionPotions as $e) : ?>
		<?php echo htmlspecialchars($e["potion"]["nom"]) ?> de qualit&eacute; <?php echo htmlspecialchars($e["potion"]["qualite"]) ?>, 
		niveau <?php echo $e["potion"]["niveau"] ?> : <br />
		<?php echo $e["retourPotion"]["nEffet"] ?> point<?php if ($e["retourPotion"]["nEffet"]): echo 's'; endif; ?> de <?php echo $e["potion"]["bm_type"] ?> sur <?php echo $e["potion"]["caracteristique"]?>
		et <?php echo $e["retourPotion"]["nb_tour_restant"] ?> tour<?php $s = ''; if ($e["retourPotion"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?php echo $s ?>.<br /><br />
	<?php endforeach; ?>
<?php endif; ?>