<?php
	if ($this->effetMotB) {
			echo "Votre casque de Spiritualit&eacute; vous donne un bonus de deux fois son niveau en sagesse.";
	}
	
	if ($this->effetMotE) {
		echo "Votre arme des Vampires a r&eacute;duit votre vie maximum. Cependant, si vous r&eacute;ussissez une attaque,"; 
		echo "vous gagnerez en PV la moiti&eacute; des d&eacute;g&acirc;ts inflig&eacutes;s (avec au maxium trois fois le ";
		echo "niveau de l'arme).";
		echo"
";
	}
	
	if ($this->effetMotK) {
		echo "Votre arme de Pr&eacute;cision double votre son bonus d'attaque (ou divise par deux son malus s'il est n&eacute;gatif).";
		echo"
";
	}
		
	if ($this->effetMotM) {
		echo "Votre arme de R&acute;flexes double son bonus de d&eacute;fense (ou divise par deux son malus s'il est n&eacute;gatif).";
		echo"
";
	}
	
	if ($this->effetMotN) {
		if ($this->effetMotNPointsDegats > 1) : $s = 's'; else: $s = ''; endif;
		echo "Votre armure de Feu C&eacute;leste inflige ".$this->effetMotNPointsDegats." point".$s." de d&eacute;g&acirc;t".$s." &agrave; tout ce qui se trouve sur sa case.";
		echo"
";
		include("tour_effet_touches_copie.phtml");
	}
		
	if ($this->effetMotO) {
		echo "Votre armure de B&eacute;n&eacute;diction Divine procure une aura de soin donnant des PVs de deux fois son niveau, &agrave; tout ce qui se trouve sur sa case.";
		echo"
";
		include("tour_effet_touches_copie.phtml");
	}
	
	if ($this->effetMotU) {
		if ($this->effetMotUPointsDegats > 1) : $s = 's'; else: $s = ''; endif;
		echo "Votre armure de Nosferatu inflige un souffle vampirique de ".$this->effetMotUPointsDegats." point".$s." de d&eacute;g&acirc;t".$s." &agrave; tout ce qui se trouve sur sa case.";
		echo"
";
		include("tour_effet_touches_copie.phtml");
	}
	
	if ($this->effetMotV) {
		echo "Votre casque de Vision augmente votre vue de deux cases.";
		echo"
";
	}
?>