<? if ($this->effetBraldun == true) :
	$nb = count($this->effetBraldunEffets);
	if ($nb > 1) { $s = 's'; $verb = 'ont'; } else { $s =''; $verb = 'a'; }
	?>
	<br /><b><?=$nb ?> effet<?=$s ?> <?=$verb?> eu de l'influence sur vous.</b><br />
	
	<? foreach($this->effetBraldunEffets as $e) : ?>
		<? if ($e["effet"]["caracteristique"] == "STOUT") : ?>
			<?=$e["effet"]["texte_calcule_effet_braldun"]?>
		<? else: ?>
			<?=$e["retourEffet"]["nEffet"] ?> point<? if ($e["retourEffet"]["nEffet"]): echo 's'; endif; ?> de <?=$e["effet"]["bm_type"] ?> sur 
			<? if ($e["effet"]["caracteristique"] == "ATTDEGDEF") : ?>
				ATT / DEG / DEF
			<? else: ?>
				<?=$e["effet"]["caracteristique"]?>
			<? endif;?>
		<? endif;?>
		et <?=$e["retourEffet"]["nb_tour_restant"] ?> tour<? $s = ''; if ($e["retourEffet"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> 
		restant<?=$s ?>.
		<? if ($e["effet"]["actif"] == false):?>
			-> Effet non cumulable donc non actif.
		<? endif;?>
		<br />
	<? endforeach; ?>
	<br />
<? endif; ?>