<?php if ($this->effetBraldun == true) :
	$nb = count($this->effetBraldunEffets);
	if ($nb > 1) { $s = 's'; $verb = 'ont'; } else { $s =''; $verb = 'a'; }
	?>
	<br /><b><?php echo $nb ?> effet<?php echo $s ?> <?php echo $verb?> eu de l'influence sur vous.</b><br />
	
	<?php foreach($this->effetBraldunEffets as $e) : ?>
		<?php if ($e["effet"]["caracteristique"] == "PAMARCHER" ||
		       $e["effet"]["caracteristique"] == "STOUT" || 
		       $e["effet"]["caracteristique"] == "TOUR") : ?>
			<?php echo $e["effet"]["texte_calcule_effet_braldun"]?>
		<?php else: ?>
			<?php echo $e["retourEffet"]["nEffet"] ?> point<?php if ($e["retourEffet"]["nEffet"]): echo 's'; endif; ?> de <?php echo $e["effet"]["bm_type"] ?> sur 
			<?php if ($e["effet"]["caracteristique"] == "ATTDEGDEF") : ?>
				ATT / DEG / DEF
			<?php else: ?>
				<?php echo $e["effet"]["caracteristique"]?>
			<?php endif;?>
		<?php endif;?>
		<?php if ($e["effet"]["caracteristique"] != "TOUR") : ?>
			et <?php echo $e["effet"]["nb_tour_restant"] ?> tour<?php $s = ''; if ($e["effet"]["nb_tour_restant"] > 1) : $s= 's' ; endif; echo $s;?> restant<?php echo $s ?>
		<?php endif;?>
		<?php if ($e["effet"]["texte_effet_braldun"]) : ?>
			: <i><?php echo $e["effet"]["texte_effet_braldun"]?></i>
		<?php endif;?>
		<?php if ($e["effet"]["actif"] == false):?>
			   Effet non cumulable donc non actif.
		<?php endif;?>
		<br />
	<?php endforeach; ?>
	<br />
<?php endif; ?>