<? if ($this->sortieSoule != null): ?>
	<br />
	<img src='/public/styles/braldahim_defaut/images/vue/ballon.png'/>
	<br /><br />
	<? if ($this->sortieSoule["resultat"] == "victoire") : ?>
		Votre équipe, "<b><?=$this->sortieSoule["equipeBraldun"]?></b>" s'est montrée supérieure à 
		"<b><?=$this->sortieSoule["equipeAdverse"]?></b>" et a emporté le match.<br />
		
		C'est sous les ovations du public que vous sortez du terrain pour rejoindre la 
		charrette de retour.
		Votre coach vous félicite et partage les gains de la buvette que vous pouvez
		consulter dans vos événements.
	<? else: ?>
		Votre équipe,  "<b><?=$this->sortieSoule["equipeBraldun"]?></b>" 
		s'est fait battre à plates coutures par "<b><?=$this->sortieSoule["equipeAdverse"]?></b>", et a perdu le match.
		C'est sous les huées du public que vous sortez du terrain pour rejoindre la charrette de retour.
		Votre coach vous félicite malgré tout et partage les gains de la buvette que vous pouvez
		consulter dans vos événements.
	<? endif;?>
	<br />
	<img src='/public/styles/braldahim_defaut/images/vue/ballon.png'/>
	<br /><br />
<? endif; ?>
