<?		 
if (isset($this->ciblesEffet["hobbitTouches"]) || isset($this->ciblesEffet["monstreTouches"]) &&
	($this->ciblesEffet["hobbitTouches"] != null || $this->ciblesEffet["monstreTouches"] != null)) {
	echo "Vous avez touch&eacute; : ";
	echo "
";
}
if (isset($this->ciblesEffet["hobbitTouches"]) && $this->ciblesEffet["hobbitTouches"] != null) {
	foreach($this->ciblesEffet["hobbitTouches"] as $val) {
		$h = $val["hobbit"];
		echo htmlspecialchars($h["prenom_hobbit"]). " ". htmlspecialchars($h["nom_hobbit"]). " (".$h["id_hobbit"].")";
	
		if (isset($val["retourAttaque"])) {
			echo " : ".$val["retourAttaque"]["jetDegat"]." point";
			if ($val["retourAttaque"]["jetDegat"] > 1) { 
				echo "s";
			}
			echo " de d&eacute;g&acirc;ts";
		}
		echo "
";
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_copie_effets.phtml");
	}
}
if (isset($this->ciblesEffet["monstreTouches"]) && $this->ciblesEffet["monstreTouches"] != null) {
	foreach($this->ciblesEffet["monstreTouches"] as $val) {
		$m = $val["monstre"];
		echo htmlspecialchars($m["nom_type_monstre"]). " (".$m["id_monstre"].")";
		echo "
";
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_copie_effets.phtml");
	}
}
if (isset($this->ciblesEffet["hobbitMorts"]) && $this->ciblesEffet["hobbitMorts"] != null) {
	if ($this->user->est_soule_hobbit == "oui") {
		echo "Vous avez plaqu&eacute; : ";
	} else {
		echo "Vous avez mis KO : ";
	}
	echo "
";
	foreach($this->ciblesEffet["hobbitMorts"] as $val) {
		$h = $val["hobbit"];
		echo htmlspecialchars($h["prenom_hobbit"]). " ". htmlspecialchars($h["nom_hobbit"]). " (".$h["id_hobbit"].")";
		echo "
";
	}
}
if (isset($this->ciblesEffet["monstreMorts"]) && $this->ciblesEffet["monstreMorts"] != null) {
	echo "
Vous avez tu&eacute; : ";
	echo "
";
	foreach($this->ciblesEffet["monstreMorts"] as $val) {
		$m = $val["monstre"];
		echo htmlspecialchars($m["nom_type_monstre"]). " (".$m["id_monstre"].")";
		echo "
";
	}
}