<?php if (isset($this->ciblesEffet["braldunTouches"]) || isset($this->ciblesEffet["monstreTouches"]) &&
	  ($this->ciblesEffet["braldunTouches"] != null || $this->ciblesEffet["monstreTouches"] != null)) : ?>
	Vous avez touch&eacute; : <br />
<?php endif; ?>
<?php if (isset($this->ciblesEffet["braldunTouches"]) && $this->ciblesEffet["braldunTouches"] != null) : ?>
	<?php foreach($this->ciblesEffet["braldunTouches"] as $val) :
		$h = $val["braldun"];?>
		<?php echo htmlspecialchars($h["prenom_braldun"])?>  <?php echo htmlspecialchars($h["nom_braldun"])?> (<?php echo $h["id_braldun"]?>)
		<?php if (isset($val["retourAttaque"])) :?>
			: <?php echo $val["retourAttaque"]["jetDegat"] ?> point<?php if ($val["retourAttaque"]["jetDegat"] > 1) { echo "s"; }?> de d&eacute;g&acirc;ts
		<?php endif; ?>
		<br />
		<?php 
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_text_effets.phtml");
		?>
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->ciblesEffet["monstreTouches"]) && $this->ciblesEffet["monstreTouches"] != null) : ?>
	<?php foreach($this->ciblesEffet["monstreTouches"] as $val) : 
		$m = $val["monstre"]; ?>
		<?php echo htmlspecialchars($m["nom_type_monstre"])?> (<?php echo $m["id_monstre"]?>)<br />
		<?php 
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_text_effets.phtml");
		?>
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->ciblesEffet["braldunMorts"]) && $this->ciblesEffet["braldunMorts"] != null) : ?>
	Vous avez 
	<?php if ($this->user->est_soule_braldun == "oui") :?>
		plaqu&eacute; : 
	<?php else: ?>
		mis KO :
	<?php endif;?>
	<br />
	<?php foreach($this->ciblesEffet["braldunMorts"] as $val) : 
		$h = $val["braldun"];?>
		<?php echo htmlspecialchars($h["prenom_braldun"])?>  <?php echo htmlspecialchars($h["nom_braldun"])?> (<?php echo $h["id_braldun"]?>)<br />
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->ciblesEffet["monstreMorts"]) && $this->ciblesEffet["monstreMorts"] != null) : ?>
	<br />Vous avez tu&eacute; : <br />
	<?php foreach($this->ciblesEffet["monstreMorts"] as $val) : 
		$m = $val["monstre"];?>
		<?php echo htmlspecialchars($m["nom_type_monstre"])?> (<?php echo $m["id_monstre"]?>)<br />
	<?php endforeach; ?>
<?php endif; ?>
		