<? if (isset($this->ciblesEffet["braldunTouches"]) || isset($this->ciblesEffet["monstreTouches"]) &&
	  ($this->ciblesEffet["braldunTouches"] != null || $this->ciblesEffet["monstreTouches"] != null)) : ?>
	Vous avez touch&eacute; : <br />
<? endif; ?>
<? if (isset($this->ciblesEffet["braldunTouches"]) && $this->ciblesEffet["braldunTouches"] != null) : ?>
	<? foreach($this->ciblesEffet["braldunTouches"] as $val) :
		$h = $val["braldun"];?>
		<?=htmlspecialchars($h["prenom_braldun"])?>  <?=htmlspecialchars($h["nom_braldun"])?> (<?=$h["id_braldun"]?>)
		<? if (isset($val["retourAttaque"])) :?>
			: <?=$val["retourAttaque"]["jetDegat"] ?> point<? if ($val["retourAttaque"]["jetDegat"] > 1) { echo "s"; }?> de d&eacute;g&acirc;ts
		<? endif; ?>
		<br />
		<? 
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_text_effets.phtml");
		?>
	<? endforeach; ?>
<? endif; ?>
<? if (isset($this->ciblesEffet["monstreTouches"]) && $this->ciblesEffet["monstreTouches"] != null) : ?>
	<? foreach($this->ciblesEffet["monstreTouches"] as $val) : 
		$m = $val["monstre"]; ?>
		<?=htmlspecialchars($m["nom_type_monstre"])?> (<?=$m["id_monstre"]?>)<br />
		<? 
		$this->retourAttaque = $val["retourAttaque"];
		echo $this->render("competences/commun_text_effets.phtml");
		?>
	<? endforeach; ?>
<? endif; ?>
<? if (isset($this->ciblesEffet["braldunMorts"]) && $this->ciblesEffet["braldunMorts"] != null) : ?>
	Vous avez 
	<? if ($this->user->est_soule_braldun == "oui") :?>
		plaqu&eacute; : 
	<? else: ?>
		mis KO :
	<? endif;?>
	<br />
	<? foreach($this->ciblesEffet["braldunMorts"] as $val) : 
		$h = $val["braldun"];?>
		<?=htmlspecialchars($h["prenom_braldun"])?>  <?=htmlspecialchars($h["nom_braldun"])?> (<?=$h["id_braldun"]?>)<br />
	<? endforeach; ?>
<? endif; ?>
<? if (isset($this->ciblesEffet["monstreMorts"]) && $this->ciblesEffet["monstreMorts"] != null) : ?>
	<br />Vous avez tu&eacute; : <br />
	<? foreach($this->ciblesEffet["monstreMorts"] as $val) : 
		$m = $val["monstre"];?>
		<?=htmlspecialchars($m["nom_type_monstre"])?> (<?=$m["id_monstre"]?>)<br />
	<? endforeach; ?>
<? endif; ?>
		