<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Lieu</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <? if ($this->modificationLieu === true) :?>
	    	Modification du lieu prise en compte.
	    <? endif; ?>
	    
	    <form action="/Administrationlieu/lieu/mode/<?=$this->mode?>/idlieu/<?=$this->id_lieu?>" method="post">
		<? if ($this->lieu == null): ?>
			Lieu inconnu 
		<? else: 
			$nbElement = 0; ?>
			<? if ($this->user->administrateur) : ?>
				<? if ($this->mode == "simple") :?>
		 	   		<input type="button"  class='button1' name="mode" value="Passer en vue complexe" onClick="document.location.href='/Administrationlieu/lieu/mode/complexe/idlieu/<?=$this->id_lieu?>'"/>
		   	 	<? else: ?>
		    		<input type="button"  class='button1' name="mode" value="Passer en vue simple" onClick="document.location.href='/Administrationlieu/lieu/mode/simple/idlieu/<?=$this->id_lieu?>'"/>
		    	<? endif; ?>
	    	<? endif;?>
	    
			<table  align='center'>
			<? foreach ($this->lieu as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre' valign="top"><?=$key?></td>
				<td>
				<? if ($key == "id_lieu"): ?>
					<input type='hidden' name="<?=$key ?>" value="<?=stripslashes($value)?>">
					<?=$value ?>
				<? elseif ($key == "description_lieu"): ?>
					
					<div id="label_description">
					  <?=Bral_Util_BBParser::bbcodeReplace($value) ?><? if (mb_strlen(trim($value)) == 0 || $value == null) :?> [vide]<? endif; ?>
					  </div>
					  
					  <div id="edition" style="display:block">
					  <?=Bral_Helper_BBBoutons::affiche($key)?>
					  <textarea rows='10' cols='80' name="<?=$key?>"  id="<?=$key?>"><?=stripslashes($value) ?></textarea>
					  </div>
					  
				<? else: ?>
					<input type='text' name="<?=$key ?>" value="<?=stripslashes($value)?>">
				<? endif; ?>
				</td>
				<td>				
				<? if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button1' name="Modifier" value="Modifier le lieu" />
				<? endif; ?>
				</td>
			</tr>
			<? endforeach; ?>
			</table>
			<input type="submit"  class='button1' name="Modifier" value="Modifier le lieu" />
		<? endif; ?>
		</form>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>