<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Lieu</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <?php if ($this->modificationLieu === true) :?>
	    	Modification du lieu prise en compte.
	    <?php endif; ?>
	    
	    <form action="/Administrationlieu/lieu/mode/<?php echo $this->mode?>/idlieu/<?php echo $this->id_lieu?>" method="post">
		<?php if ($this->lieu == null): ?>
			Lieu inconnu 
		<?php else: 
			$nbElement = 0; ?>
			<?php if ($this->user->administrateur) : ?>
				<?php if ($this->mode == "simple") :?>
		 	   		<input type="button"  class='button' name="mode" value="Passer en vue complexe" onclick="document.location.href='/Administrationlieu/lieu/mode/complexe/idlieu/<?php echo $this->id_lieu?>'"/>
		   	 	<?php else: ?>
		    		<input type="button"  class='button' name="mode" value="Passer en vue simple" onclick="document.location.href='/Administrationlieu/lieu/mode/simple/idlieu/<?php echo $this->id_lieu?>'"/>
		    	<?php endif; ?>
	    	<?php endif;?>
	    
			<table  align='center'>
			<?php foreach ($this->lieu as $key => $value) : 
				if ($this->mode == "simple") {
					if (!in_array($key, $this->keySimple)) {
						continue;
					}
				}
				$nbElement++;	
			?>
			<tr>
				<td class='comp_titre' valign="top"><?php echo $key?></td>
				<td>
				<?php if ($key == "id_lieu"): ?>
					<input type='hidden' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
					<?php echo $value ?>
				<?php elseif ($key == "description_lieu"): ?>
					
					<div id="label_description">
					  <?php echo Bral_Util_BBParser::bbcodeReplace($value) ?><?php if (mb_strlen(trim($value)) == 0 || $value == null) :?> [vide]<?php endif; ?>
					  </div>
					  
					  <div id="edition" style="display:block">
					  <?php echo Bral_Helper_BBBoutons::affiche($key)?>
					  <textarea rows='10' cols='80' name="<?php echo $key?>"  id="<?php echo $key?>"><?php echo stripslashes($value) ?></textarea>
					  </div>
					  
				<?php else: ?>
					<input type='text' name="<?php echo $key ?>" value="<?php echo stripslashes($value)?>">
				<?php endif; ?>
				</td>
				<td>				
				<?php if ($nbElement % 8 == 0) :?>
				<input type="submit"  class='button' name="Modifier" value="Modifier le lieu" />
				<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
			</table>
			<input type="submit"  class='button' name="Modifier" value="Modifier le lieu" />
		<?php endif; ?>
		</form>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>