
<table class="table_liste" style="width:95%">
<thead class="table_liste">
<tr class="table_liste">
	<th colspan="4">Recherche dans l'Hôtel des Ventes</th>
</tr>
</thead>
<tr>
<td colspan='3'>
		<select name="hotel_menu_recherche_pratique" id="hotel_menu_recherche_pratique" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Recherches pratiques</option>
		<?php foreach($this->menuRecherchePratique as $m) : ?>
			<option value="<?php echo $m["numero_element"]?>" <?php echo $m["selected"]?>><?php echo $m["nom"]?></option>
		<?php endforeach;?>
		</select>
</td>
</tr>
<tr>
	<td>
		<select name="hotel_menu_recherche_equipements" id="hotel_menu_recherche_equipements" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Équipements</option>
		<?php foreach($this->menuRechercheEquipement as $m) : ?>
			<optgroup label="<?php echo $m["titre"]?>" style="font-weight:bold"></optgroup>
			<?php foreach($m["elements"] as $e) : ?>
				<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom"]?></option>
			<?php endforeach; ?>
		<?php endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_potions" id="hotel_menu_recherche_potions" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Potions et Vernis</option>
		<?php foreach($this->menuRecherchePotion as $e) : ?>
			<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom_type"]?> <?php echo $e["nom"]?></option>
		<?php endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_materiels" id="hotel_menu_recherche_materiels" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matériels</option>
		<?php foreach($this->menuRechercheMateriel as $m) : ?>
			<option value="<?php echo $m["numero_element"]?>"><?php echo $m["nom"]?></option>
		<?php endforeach;?>
		</select>
	</td>
</tr>
<tr>
	<td>
		<select name="hotel_menu_recherche_munitions" id="hotel_menu_recherche_munitions" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Munitions</option>
		<?php foreach($this->menuRechercheMunition as $m) : ?>
			<option value="<?php echo $m["numero_element"]?>"><?php echo $m["nom"]?></option>
		<?php endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_matieres_premieres" id="hotel_menu_recherche_matieres_premieres" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matières Premières</option>
		<?php foreach($this->menuRechercheMatieresPremieres as $m) : ?>
			<optgroup label="<?php echo $m["titre"]?>" style="font-weight:bold"></optgroup>
			<?php foreach($m["elements"] as $e) : ?>
				<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom"]?></option>
			<?php endforeach; ?>
		<?php endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_matieres_transformees" id="hotel_menu_recherche_matieres_transformees" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Matières Transformées</option>
		<?php foreach($this->menuRechercheMatieresTransformees as $m) : ?>
			<optgroup label="<?php echo $m["titre"]?>" style="font-weight:bold"></optgroup>
			<?php foreach($m["elements"] as $e) : ?>
				<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom"]?></option>
			<?php endforeach; ?>
		<?php endforeach;?>
		</select>
	</td>
</tr>
<tr>
	<td>
		<select name="hotel_menu_recherche_runes" id="hotel_menu_recherche_runes" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Runes</option>
		<?php foreach($this->menuRechercheRune as $e) : ?>
			<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom"]?></option>
		<?php endforeach;?>
		</select>
	</td>
	<td>
		<select name="hotel_menu_recherche_aliments_ingredients" id="hotel_menu_recherche_aliments_ingredients" onchange="jsMenuHotel(this.id, this.value)">
		<option value="-1">Aliments / Ingrédients</option>
		<?php foreach($this->menuRechercheAlimentsIngredients as $m) : ?>
			<optgroup label="<?php echo $m["titre"]?>" style="font-weight:bold"></optgroup>
			<?php foreach($m["elements"] as $e) : ?>
				<option value="<?php echo $e["numero_element"]?>"><?php echo $e["nom"]?></option>
			<?php endforeach; ?>
		<?php endforeach;?>
		</select>
	</td>
	<td>&nbsp;
	</td>
	</tr>
</tr>
</table>

