<div class="box_contenu textalic">

	<table width="100%">
		<tr valign="top">
			<td  width="50%">
				<div class="titre textalic textsizeb">
				Historique
				</div>
				<br/>
				<div class="titre textalic textsizee">Décembre 2005</div>
				Yvonnick débute le projet. Les premières idées tournent autour d'un jeu GPL dont la structure pourrait être récupérée pour d'autres jeux. Le jeu se développe en PHP 5 Objet. 
				<br/><br/>
				<div class="titre textalic textsizee">Janvier 2006</div>
				Pierre rejoint le projet et apporte tout un tas d'idées... 
				<br/><br/>
				<div class="titre textalic textsizee">Novembre 2006</div>
				Refonte du jeu en Java / Webwork / Hibernate... 
				<br/><br/>
				<div class="titre textalic textsizee">Mai 2007</div>
				Refonte du jeu en PHP 5 à l'aide du Zend Framework. 
				Le développement est alors bien plus rapide.
				<br/><br/>
				<div class="titre textalic textsizee">Janvier 2008</div>
				Dépôt de candidature auprès de l'association JeuxWeb.org, acceptée 2 mois plus tard    Mai 2008 : Ouverture du jeu en Beta fermée.
				<br/><br/>
				<div class="titre textalic textsizee">Mai 2008</div>
				Ouverture du jeu en beta test, les développements continuent.
				<br/><br/>
				<div class="titre textalic textsizee">Février 2009</div>
				Ouverture du jeu en beta publique.
				<br/><br/>
				<div class="titre textalic textsizee">Mai 2010</div>
				Fin de la beta publique, après 150 évolutions différentes et 250 corrections d'anomalies en un peu plus d'un an.<br/>
				Ouverture de Braldahim I - L'éveil des Braldûns.
			
			</td>
			<td style="border-left: 1px solid #000000;" width="50%">
				<div class="titre textalic textsizeb">
				L'équipe
				</div>
				<br/>
				
				<div class="titre textalic textsizee">Gaëlle, Alias Sabrik Holtrenkhill</div>
				Tests
				<br/><br/>
				<div class="titre textalic textsizee">Pierre, Alias Fuleng Micolgrac</div>
				Règles
				<br/><br/>
				<div class="titre textalic textsizee">Maxime, Alias Pulg' Maltertre</div>
				Développement
				<br/><br/>
				<div class="titre textalic textsizee">Simon, Alias Simsagace Courluc</div>
				Rôle Play
				<br/><br/>
				<div class="titre textalic textsizee">Yvonnick, Alias Boule Hondevice</div>
				Architecture, Développement
				<br/><br/><br/><br/>
								
				<div class="titre textalic textsizeb">
				Remerciements
				</div>
				<br/>
				<div class="titre textalic textsizee">Olivier</div>
				Pour les dessins originaux de Braldahim.<br/>
				<a href="http://www.haleinesfraiches.com/" class="aWhite">Site web</a>, 
				<a href="http://roughstuff.over-blog.com/" class="aWhite">Blog</a>
				<br/><br/>
				<div class="titre textalic textsizee">Quentin</div>
				Pour les dessins originaux de Braldahim.<br/>
				<a href="/sources" class="aWhite">Plus d'infos</a>
				<br/><br/>
				
				<div class="titre textalic textsizee">Yootheme</div>
				Pour les graphiques des popups.<br/>
				<a href="http://www.yootheme.com/" class="aWhite">Site web</a>
				<br/><br/><br/><br/>
				
				<div class="titre textalic textsizeb">
				Sources, Licence, Hébergement
				</div>
				<a href="/sources" class="aWhite">Plus d'infos.</a>
			</td>
		</tr>
	</table>
</div>