<div class="box_contenu textalic">
<table width="100%">
	<tr valign="top">
		<td style="width:25%">
		<img src='/images/braldun-site.png' style='width:90%; margin-top:60px'/>
		</td>
		<td  style="width:75%; text-align:justify">
			<div class="titre textalic textsizeb">
			Le Projet
			</div>
			<br/>
			
			Braldahim n'est pas un jeu vidéo ! Braldahim est un jeu de rôle en ligne, ne nécessitant qu'un simple navigateur et une connexion
			internet pour pouvoir y jouer. Chaque joueur incarne un personnage qu'il pourra faire évoluer dans le vaste univers mis en place.
			Il sera sans doute difficile de jouer seul, l'entraide et la communication sont des éléments essentiels pour prendre plaisir à jouer.
			Attention, c'est peut-être un jeu de rôle, mais il ne faut pas forcément être fan de ce genre de jeu pour accrocher à Braldahim.
			<br/><br/>
			Il y a des <a class="aWhite" href='http://regles.braldahim.com'>règles</a>, peut-être beaucoup, mais elles ne vous seront pas indispensables
			pour débuter. Vous ne les consulterez qu'au moment opportun, lorsque vous aurez envie de mieux comprendre le fonctionnement du jeu.
			
			<br/><br/>
			Que les choses soient claires, Braldahim est un jeu <b>totalement gratuit</b> ! 
			Il n'y a pas d'abonnement, pas de boutique réelle dans le jeu, Braldahim se veut être accessible pour tous les budgets.
			<br/>
			L'équipe ne souhaite pas gagner de l'argent avec ce projet, c'est aussi pour cela que 
			<a href="http://www.jeuxweb.org" target="_blank"  class="aWhite">JeuxWeb.org, Association Sans But Lucratif (ASBL)</a>
			a accepté d'accueilir Braldahim sur ses serveurs.
			<br/><br/>
			
			Braldahim est également un projet libre, sous <a class="aWhite" href='http://public.braldahim.com/licence.txt'>licence GPLv3</a>, 
			certaines créations telles que des images ou des textes sont également proposées
			sous Licence Créative Commons. Les détails des licences sont <a href="/sources" class="aWhite">présentés ici</a>. Si le projet vous plaît et
			que vous souhaitez participer à son développement, même ponctuellement, n'hésitez pas à nous contacter : <b>thains AROB braldahim.com</b> (remplacer AROB par @)
			ou sur <a class="aWhite" href='http://forum.braldahim.com'>le forum officiel</a>.
			
			<br />Pour les développeurs, vous pouvez également développer vos propres "outils" ou aides de jeu via 
			les <a class="aWhite" href='http://sp.braldahim.com'>API mises à disposition</a>.
		</td>
	</tr>
</table>
<table width="100%">
	<tr valign="top">
		<td  colspan="2" style="border-bottom: 1px solid #000000;">
		&nbsp;
		</td>
	</tr>
	<tr valign="top">
		<td  width="50%">
			<div class="titre textalic textsizeb">
			Historique
			</div>
			<br/>
			<div class="titre textalic textsizee">Décembre 2005</div>
			Yvonnick débute le projet. Les premières idées tournent autour d'un jeu GPL dont la structure pourrait être récupérée pour d'autres jeux. Le jeu se développe en PHP 5 Objet. 
			<br/><br/>
			<div class="titre textalic textsizee">Janvier 2006</div>
			Pierre rejoint le projet et apporte tout un tas d'idées... 
			<br/><br/>
			<div class="titre textalic textsizee">Novembre 2006</div>
			Refonte du jeu en Java / Webwork / Hibernate... 
			<br/><br/>
			<div class="titre textalic textsizee">Mai 2007</div>
			Refonte du jeu en PHP 5 à l'aide du Zend Framework. 
			Le développement est alors bien plus rapide.
			<br/><br/>
			<div class="titre textalic textsizee">Janvier 2008</div>
			Dépôt de candidature auprès de l'association JeuxWeb.org, acceptée 2 mois plus tard.
			<br/><br/>
			<div class="titre textalic textsizee">Mai 2008</div>
			Ouverture du jeu en beta fermée, les développements continuent.
			<br/><br/>
			<div class="titre textalic textsizee">Février 2009</div>
			Ouverture du jeu en beta publique.
			<br/><br/>
			<div class="titre textalic textsizee">Mai 2010</div>
			Fin de la beta publique, après 150 évolutions différentes et 250 corrections d'anomalies en un peu plus d'un an.<br/>
			Ouverture de Braldahim I - L'éveil des Braldûns.
			<br/><br/>
			<div class="titre textalic textsizee">Juillet 2010</div>
			Lancement du <a class="aWhite" href='http://regles.braldahim.com/wiki/Chapitre_II_-_L%27%C3%A9veil_des_Gredins'>Chapitre II - L'éveil des Gredins</a>.
			<br/><br/>
			<div class="titre textalic textsizee">Novembre 2010</div>
			Lancement du <a class="aWhite" href='http://regles.braldahim.com/wiki/Chapitre_III_-_L%27H%C3%A9ritage_des_Nains'>Chapitre III - L'héritage des nains</a>.<br/>
		</td>
		<td style="border-left: 1px solid #000000;" width="50%">
			<div class="titre textalic textsizeb">
			L'équipe
			</div>
			<br/>
			
			<div class="titre textalic textsizee">Gaëlle, Alias Sabrik Holtrenkhill</div>
			Tests
			<br/><br/>
			<div class="titre textalic textsizee">Pierre, Alias Fuleng Micolgrac</div>
			Règles
			<br/><br/>
			<div class="titre textalic textsizee">Maxime, Alias Pulg' Maltertre</div>
			Développement
			<br/><br/>
			<div class="titre textalic textsizee">Simon, Alias Simsagace Courluc</div>
			Rôle Play
			<br/><br/>
			<div class="titre textalic textsizee">Yvonnick, Alias Boule Hondevice</div>
			Architecture, Développement
			<br/><br/><br/><br/>
							
			<div class="titre textalic textsizeb">
			Remerciements
			</div>
			<br/>
			<div class="titre textalic textsizee">Olivier</div>
			Pour les dessins originaux de Braldahim.<br/>
			<a href="http://www.haleinesfraiches.com/" class="aWhite">Site web</a>, 
			<a href="http://roughstuff.over-blog.com/" class="aWhite">Blog</a>
			<br/><br/>
			<div class="titre textalic textsizee">Quentin</div>
			Pour les dessins originaux de Braldahim.<br/>
			<a href="/sources" class="aWhite">Plus d'infos</a>
			<br/><br/><br/><br/>
			
			<div class="titre textalic textsizeb">
			Sources, Développement, Licence, Hébergement
			</div>
			<a href="/sources" class="aWhite">Plus d'infos.</a>
			
		</td>
	</tr>
</table>
</div>