<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Plantes</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
			<?php if ($this->creation === true) : ?>
			<b>Cr&eacute;ation de <?php echo $this->nb_creation ?> plantes</b> <br />
			<b>Les plantes créées en villes ont été ensuite supprimées</b>.<br />
			<?php endif; ?>
			<form action="/Administrationplante/plantes" method="post">
			<table align='center'>
			<tr>
			<th class='comp_titre'>Zone</th>
			<th class='comp_titre'>Plante</th>
			<th class='comp_titre'>Couverture</th>
			</tr>
			<tr valign='top'>
				<td>
					<select name="id_zone">
					<?php foreach ($this->zones as $z) : ?>
					<option value="<?php echo $z["id_zone"]?>"><?php echo $z["id_zone"]?></option>
					<?php endforeach; ?>
					</select>
				</td>
				<td>
					<select name="id_type_plante">
					<?php foreach ($this->typePlantes as $p) : ?>
					<option value="<?php echo $p["id_type_plante"]?>"><?php echo $p["nom"]?> - <?php echo $p["categorie"] ?> - <?php echo $p["environnement"]?> - A:<?php echo $p["nom_partie_1"]?> - B:<?php echo $p["nom_partie_2"]?> - C:<?php echo $p["nom_partie_3"]?> - D:<?php echo $p["nom_partie_4"] ?></option>
					<?php endforeach; ?>
					</select>
					<br />
					Quantit&eacute; partie A : min <input type="text" name="partie_1a" onkeypress="chiffres(event);" /> max : <input type="text" name="partie_1b" onkeypress="chiffres(event);" /><br />
					Quantit&eacute; partie B : min <input type="text" name="partie_2a" onkeypress="chiffres(event);" /> max : <input type="text" name="partie_2b" onkeypress="chiffres(event);" /> <br />
					Quantit&eacute; partie C : min <input type="text" name="partie_3a" onkeypress="chiffres(event);" /> max : <input type="text" name="partie_3b" onkeypress="chiffres(event);" /> <br />
					Quantit&eacute; partie D : min <input type="text" name="partie_4a" onkeypress="chiffres(event);" /> max : <input type="text" name="partie_4b" onkeypress="chiffres(event);" /> <br />
				</td>
				<td>
					<select name="couverture">
					<?php for ($i=1; $i<100; $i++) : ?>
						<option value="<?php echo $i?>"><?php echo $i?> %</option>
					<?php endfor; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td colspan='3'> <input type="submit" class="button1" name="add" value="Ajouter la couverture de plante" /></td>
			</tr>
			</table>
			</form>
		<br /><br />
			<table align='center'>
			<tr>
			<th class='comp_titre'>N&deg;</th>
			<th class='comp_titre'>Environnement</th>
			<th class='comp_titre'>Ville</th>
			<th class='comp_titre'>x_min</th>
			<th class='comp_titre'>x_max</th>
			<th class='comp_titre'>y_min</th>
			<th class='comp_titre'>y_max</th>
			<th class='comp_titre'>Nombre Cases</th>
			<th class='comp_titre'>Nombre Plantes</th>
			<th class='comp_titre'>Couverture</th>
			</tr>			
			<?php foreach ($this->zones as $zone) : ?>
				<tr>
					<td><?php echo $zone["id_zone"] ?></td>
					<td><?php echo $zone["environnement"] ?></td>
					<td><?php echo $zone["villes"] ?></td>
					<td><?php echo $zone["x_min"] ?></td>
					<td><?php echo $zone["x_max"] ?></td>
					<td><?php echo $zone["y_min"] ?></td>
					<td><?php echo $zone["y_max"] ?></td>
					<td><?php echo $zone["nombre_cases"] ?></td>
					<td><?php echo $zone["nombre_plantes"] ?></td>
					<td><?php echo $zone["couverture"] ?> % </td>
					<td>
					
					</td>
				</tr>
			<?php endforeach; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>