<?php echo $this->render('header.phtml'); ?>
<div class="box_administration">
<div class="inner">
    <div class="titre textalic textsizea">Administration Bougrie</div>
    	&nbsp;
	<div class="contenu">
	    <div class="box_contenu1 textalic">
	    
	    <input type="button"  class='button1' name="Nouvelle Bougrie" value="Nouvelle Bougrie" onclick="document.location.href='/Administrationbougrie/bougrie'"/>
	    <br /><br />
			<form action="/Administrationbougrie/bougrie" method="post">
			<input type='hidden' name='id_bougrie' id='id_bougrie' value='<?php echo $this->bougrie["id_bougrie"]?>'/>
			<?php if ($this->bougrie["id_bougrie"] != -1) : ?>
				<br />
				<div class="titre textalic textsizeb">Edition de la bougrie n&deg; <?php echo $this->bougrie["id_bougrie"]?></div>
				<br />
			<?php endif; ?>
			
			<?php echo Bral_Helper_BBBoutons::affiche('texte_bougrie', 500)?>
	
			<span>Message</span><br />
			<textarea name="texte_bougrie" id="texte_bougrie" class="inputbox" rows="10" cols="60" onkeydown="textCount($('texte_bougrie'),$('characterstyped'),500);" onkeyup="textCount($('texte_bougrie'),$('characterstyped'),500);"><?php echo stripslashes($this->bougrie["texte_bougrie"])?></textarea>
			<br />
			Lien vers les règles (facultatif) : <input type="text" name="regle_bougrie" id="regle_bougrie" size="50" maxlength="500" class="inputbox" value="<?php echo $this->bougrie["regle_bougrie"]?>"/>
			<br />
			<input style="background-color: lightgray;" readonly="readonly" name="characterstyped" id="characterstyped" size="4" maxlength="4" value="500" type="text">Caract&egrave;res restants<br /><br />
			
			<?php if ($this->bougrie["id_bougrie"] != -1) : ?>
				<input type="submit"  class='button1' name="Editer" value="Editer la Bougrie" />
			<?php else :?>
				<input type="submit"  class='button1' name="Ajouter" value="Ajouter la Bougrie" />
			<?php endif;?>
			
			</form>
			
			<br /><br /><br />
			
			<table  align='center'>
			<tr>
			<th class='comp_titre'>Id</th>
			<th class='comp_titre'>Texte</th>
			<th class='comp_titre'>Règle</th>
			</tr>
			<?php if (count($this->bougries) > 0) : ?>
				<?php $i = 0; 
					foreach ($this->bougries as $bougrie) : ?>
					<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
						<td class="table_liste"><?php echo $bougrie["id_bougrie"] ?></td>
						<td class="table_liste"><?php echo Bral_Util_BBParser::bbcodeReplace($bougrie["texte_bougrie"]);?></td>
						<td class="table_liste"><?php if ($bougrie["regle_bougrie"] != null && $bougrie["regle_bougrie"] != "") :?><a href='<?php echo $bougrie["regle_bougrie"];?>'>Règle</a><?php else:?>n/a<?php endif;?></td>
						<td class="table_liste"><input type="button"  class='button1' name="Editer" value="Editer la bougrie" onclick='document.location.href="/Administrationbougrie/bougrie/id_bougrie/<?php echo $bougrie["id_bougrie"] ?>"'/></td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			</table>
		</div>
	</div>
	&nbsp;
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>