<div class="<?php echo $this->conteneur; ?>" id="<?php echo $this->conteneur; ?>">
  <input type='hidden' id='switch_<?php echo $this->conteneur; ?>' value='<?php echo $this->liste ?>'/>

  <?php foreach($this->onglets as $onglet) : ?>
  	<input type='hidden' id='loaded_<?php echo $onglet["nom"] ?>' value='<?php echo $onglet["chargementInBoxes"] ?>'/>
    <span id='onglet_<?php echo $onglet["nom"] ?>' class='onglet <?php echo $onglet["css"] ?>' onclick='Javascript:my_switch("<?php echo $onglet["nom"] ?>","<?php echo $this->conteneur ?>"); '>
      &nbsp;<?php echo $onglet["titre"] ?>&nbsp;
    </span>
  <?php endforeach; ?>
  <hr />
  <?php echo $this->data ?>
</div>