<div class="titrea textalic textsizea">Le Bourg</div>

<div class="box_contenu textalic">
<br/>
	<table style="width:100%" cellspacing="0">
	<tr>
		<td style="width:200px" valign="top">
			<a class='bralbutton' onclick='document.location.href="/palmares"'><span>L'office des Palmarès</span></a>
			
			<br/><br/>
			<a class='bralbutton' onclick='document.location.href="/brasserie"'><span>La brasserie des sports</span></a>
			
		</td>
		<td style="width:200px;" valign="top">
			<a class='bralbutton' onclick='document.location.href="/chambre"'><span>La chambre des m&eacute;tiers</span></a>
			<br/><br/>
			<a class='bralbutton' onclick='document.location.href="/tableaurecherches"'><span>Tableaux des Recherchés</span></a>
			<br/><br/>
		</td>
		<td style="width:200px;" valign="top">
			<div class="titrea textalic textsizec" style='position: absolute;top:38px; right:0px'>Les Marchés</div>
			<a class='bralbutton' onclick='document.location.href="/hotel"'><span>Hôtel des Ventes</span></a>
			<br/><br/>
			<a class='bralbutton' onclick='document.location.href="/etals"'><span>Étals</span></a>
		</td>
	</tr>
	</table>
</div>