<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?=$this->vente["vente"]["id_vente"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?=$this->nb_pa ?> PA<br />
	
	Objet : 
	
	<? if ($this->vente["vente"]["type_vente"] == "materiel") : ?>
		<? $this->materiels = array($this->vente["objet"]); ?>
		<?=$this->render("/interface/commun/materiels/materiels.phtml"); ?>
	<? elseif ($this->vente["vente"]["type_vente"] == "equipement"): ?>
		<? $this->equipements = array($this->vente["objet"]); ?>
		<?=$this->render("/interface/commun/equipements/equipements.phtml"); ?>
	<? else : ?>
		<?=$this->vente["objet"]["nom"]; ?>
	<? endif; ?>
	<br />
	
	<? if ($this->vente["objet"]["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br>
	<? endif; ?>
	
	<? if (count($this->prix) > 0) : ?>
		
		<? if ($this->vente["objet"]["est_charrette"] === false) : ?>
			<?
			$jsTrue = "";
			$jsFalse = "";
			$js = "";
			foreach($this->prix as $k => $p) {
				if ($p["possible"] === true) {
					$jsTrue .= "$('bouton_acheterhotel".$k."').disabled = true,";
					$jsFalse .= "$('bouton_acheterhotel".$k."').disabled = false,";
				}
			}
			if ($jsTrue != "" && $jsFalse != "") {
				$jsTrue = substr($jsTrue, 0, strlen($jsTrue)-1);
				$jsFalse = substr($jsFalse, 0, strlen($jsFalse)-1);
				$js = " if (this.value == -1) {".$jsTrue."} else {".$jsFalse."}";
			}
			?>
			Destination : <br>
			<select name="valeur_3" id="valeur_3" onChange="<? if ($js!= ""): echo $js; endif;?>">
		 		<option value="-1">(Choisissez une destination)</option>
				<? foreach($this->destinationTransfert as $d) :?>
					<option value="<?=$d["id_destination"] ?>" <? if ($d["possible"] == false): echo "disabled"; endif;?>><?=$d["texte"] ?> <? if ($d["possible"] == false): echo " : pas assez de place"; endif;?></option>
				<? endforeach; ?>
			</select>
		<? else :?>
			 <input type='hidden' id='valeur_3' name='valeur_3' value='laban'>
		<? endif;?>
		
		<br>
		
		<? if ($this->vente["objet"]["charrette_possible"] === false) : ?>
				Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?=$this->vente["objet"]["charrette_detail"]?>
		<? else: ?>	
		<br>
			<ul class="titre textalic textsizec">Prix</ul>
			<br>
			<? foreach($this->prix as $k => $p) : ?>
				<?=$p["id_destination"] ?> : <?=$p["prix"] ?> <?=$p["nom"] ?>
				<? if ($this->assezDePa == false): ?>
					: Pas assez de PA
				<? elseif ($this->vente["objet"]["charrette_possible"] === false) : ?>
					<br>
					Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?=$this->vente["objet"]["charrette_detail"]?>
				<? elseif ($p["possible"] === true && $this->vente["objet"]["place_dispo"] === true) : ?>
					<input type='button' class='button1' id='bouton_acheterhotel<?=$k?>' value='Acheter !' onClick='this.disabled=true;$("valeur_2").value=<?=$k ?>; _get_("/hotel/doaction?caction=do_hotel_acheter");' <? if ($this->vente["objet"]["est_charrette"] == false) : echo "disabled"; endif;?>
				<? elseif ($this->vente["objet"]["place_dispo"] == false): ?>
					: Pas assez de place disponible
				<? else: ?>
					: Pas assez de ressources
				<? endif; ?>
				<br />
			<? endforeach; ?>
		<? endif;?>
	<? endif; ?>
	
 </div>

</form>
<br />
<? echo Bral_Helper_Fermer::affiche(); ?>