<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='3'>
 <input type='hidden' id='valeur_1' name='valeur_1' value='<?php echo $this->vente["vente"]["id_vente"] ?>'>
 <input type='hidden' id='valeur_2' name='valeur_2' value='-1'>
 <form name='myForm'>
 <div class='comp_contenu'>
	<br />
	
	Co&ucirc;t du service : <?php echo $this->nb_pa ?> PA<br />
	
	Objet : 
	
	<?php if ($this->vente["vente"]["type_vente"] == "materiel") : ?>
		<?php $this->materiels = array($this->vente["objet"]); ?>
		<?php echo $this->render("/interface/commun/materiels/materiels.phtml"); ?>
	<?php elseif ($this->vente["vente"]["type_vente"] == "equipement"): ?>
		
		<?php if (floor($this->user->niveau_braldun / 10) < $this->vente["objet"]["niveau"]) : ?>
			Attention ! Vous n'avez pas le niveau requis pour équiper cette pièce.
		<?php endif;?>
		<?php  
			$equipements = null;
			$equipements[$this->vente["objet"]["id_type_emplacement"]]["equipements"][] = $this->vente["objet"];
			$equipements[$this->vente["objet"]["id_type_emplacement"]]["nom_type_emplacement"] = $this->vente["objet"]["emplacement"];
			$this->equipements = $equipements;
			?>
		<?php echo $this->render("/interface/commun/equipements/equipements.phtml"); ?>
	<?php else : ?>
		<?php echo $this->vente["objet"]["nom"]; ?>.<br />
	<?php endif; ?>
	<br />
	
	<?php if ($this->vente["objet"]["place_dispo"] === false) : ?>
		Il n'y a pas assez de place dans votre laban et dans votre charrette (si vous en avez une). <br />
	<?php endif; ?>
	
	<?php if (count($this->prix) > 0) : ?>
		
		<?php if ($this->vente["objet"]["est_charrette"] === false) : ?>
			<?
			$jsTrue = "";
			$jsFalse = "";
			$js = "";
			foreach($this->prix as $k => $p) {
				if ($p["possible"] === true) {
					$jsTrue .= "$('bouton_acheterhotel".$k."').disabled = true,";
					$jsFalse .= "$('bouton_acheterhotel".$k."').disabled = false,";
				}
			}
			if ($jsTrue != "" && $jsFalse != "") {
				$jsTrue = substr($jsTrue, 0, strlen($jsTrue)-1);
				$jsFalse = substr($jsFalse, 0, strlen($jsFalse)-1);
				$js = " if (this.value == -1) {".$jsTrue."} else {".$jsFalse."}";
			}
			?>
			Destination : <br />
			<select name="valeur_3" id="valeur_3" onchange="<?php if ($js!= ""): echo $js; endif;?>">
		 		<option value="-1">(Choisissez une destination)</option>
				<?php foreach($this->destinationTransfert as $d) :?>
					<option value="<?php echo $d["id_destination"] ?>" <?php if ($d["possible"] == false): echo "disabled"; endif;?>><?php echo $d["texte"] ?> <?php if ($d["possible"] == false): echo " : pas assez de place"; endif;?></option>
				<?php endforeach; ?>
			</select>
		<?php else :?>
			 <input type='hidden' id='valeur_3' name='valeur_3' value='laban'>
		<?php endif;?>
		
		<br />
		
		<?php if ($this->vente["objet"]["charrette_possible"] === false) : ?>
				Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?php echo $this->vente["objet"]["charrette_detail"]?>
		<?php else: ?>	
		<br />
			<div class="titre textalic textsizec">Prix</div>
			<br />
			<?php foreach($this->prix as $k => $p) : ?>
				<?php echo $p["id_destination"] ?> : <?php echo $p["prix"] ?> <?php echo $p["nom"] ?>
				<?php if ($this->assezDePa == false): ?>
					: Pas assez de PA
				<?php elseif ($this->vente["objet"]["charrette_possible"] === false) : ?>
					<br />
					Vous n'avez pas les caract&eacute;ristiques suffisantes pour tirer la charrette : <?php echo $this->vente["objet"]["charrette_detail"]?>
				<?php elseif ($p["possible"] === true && $this->vente["objet"]["place_dispo"] === true) : ?>
					<input type='button' class='button1' id='bouton_acheterhotel<?php echo $k?>' value='Acheter !' onclick='this.disabled=true;$("valeur_2").value=<?php echo $k ?>; _get_("/hotel/doaction?caction=do_hotel_acheter");' <?php if ($this->vente["objet"]["est_charrette"] == false) : echo "disabled"; endif;?>/>
				<?php elseif ($this->vente["objet"]["place_dispo"] == false): ?>
					: Pas assez de place disponible
				<?php else: ?>
					: Pas assez de ressources
				<?php endif; ?>
				<br />
			<?php endforeach; ?>
		<?php endif;?>
	<?php endif; ?>
	
 </div>

</form>
<br />
<?php echo Bral_Helper_Fermer::affiche(); ?>