Vous avez mis en vente : <br />
<?php echo $this->objetVente?> <br /><br />

contre : <br />

<?php 
$n = 0;
foreach($this->textePrixVente as $t) : ?>
	<?php if ($n > 0): echo "<br /> OU "; endif;?>
	<?php echo $t["texte"]; $n++?> 
<?php endforeach; ?>
<br /><br />
Cette vente porte le n&deg;<?php echo $this->idVente?>.<br /><br />

Si cette vente ne trouve pas d'acheteur avant <?php echo $this->dateFinVente?>, son 
contenu sera directement renvoyé dans votre coffre.
