Vous avez mis en vente : <br />
<?=$this->objetVente?> <br><br>

contre : <br>

<? 
$n = 0;
foreach($this->textePrixVente as $t) : ?>
	<? if ($n > 0): echo "<br> OU "; endif;?>
	<?=$t["texte"]; $n++?> 
<? endforeach; ?>
<br><br>
Cette vente porte le n&deg;<?=$this->idVente?>.<br><br>

Si cette vente ne trouve pas d'acheteur avant <?=$this->dateFinVente?>, son 
contenu sera directement renvoyé dans votre coffre.
