<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='11'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	L'Hôtel des Ventes vous demande 1 castar pour l'utilisation de ce service.<br />
 	Si toutefois votre vente ne trouve pas d'acquéreur au bout de 30 jours, le
 	contenu de la vente sera directement renvoyé dans votre coffre. L'Hôtel gardera bien sûr la commission.<br />

 	<br />
 	<?php if ($this->estSurEchoppe === true) : ?>
 		Vous pouvez vendre à l'Hôtel des Ventes des éléments créés dans votre atelier.
 	<?php else: ?>
	Vous pouvez vendre des &eacute;l&eacute;ments pr&eacute;sents dans votre laban <br />
 	ou dans votre charrette si vous en avez une.
 	<?php endif;?>
 	<br />
 	
 	<?php if ($this->assezDePa == false) :?>
 		Vous n'avez pas assez de PA.
 	<?php elseif ($this->assezDeCastars == false) : ?>
 		Vous n'avez pas assez de Castar.
 	<?php else: ?>
 	Vendre à partir de :<br />
	<select name="valeur_1" id="valeur_1"  onchange="_get_('/hotel/doaction?caction=ask_hotel_vendre&valeur_1='+this.value);">
		<option value="-1">(Choisissez un endroit de d&eacute;part)</option>
		<?php foreach($this->typeDepart as $t) : ?>
		 	<option value="<?php echo $t["id_type_depart"]?>" <?php echo $t["selected"]?>><?php echo $t["nom_type_depart"]?></option>
		<?php endforeach; ?>
	 </select>
	 <br/><br/>

 	
 	<?php if ($this->choixDepart != null) : ?>
	 <select name="valeur_2" id="valeur_2"  onchange="if ($('bouton_vendrehotel')) {$('bouton_vendrehotel').disabled=true} ;_get_('/hotel/doaction?caction=ask_hotel_vendre&valeur_1=<?php echo $this->idTypeCourantDepart?>&valeur_2='+this.value);">
	 	<option value="-1">(Choisissez un &eacute;l&eacute;ment)</option>
	 	<?php foreach($this->typeElements as $t) : ?>
	 		<option value="<?php echo $t["id_type_element"]?>" <?php if ($t["selected"] == $t["id_type_element"]): echo "selected"; endif;?>><?php echo htmlspecialchars($t["nom_element"])?></option>
	 	<?php endforeach; ?>
	 </select>
	 <br /><br />
	<?php endif;?>
		 
	<?php if ($this->typeCourant != null) : ?>
		<?php if ($this->vendreOk === true) : ?>
	 		<?php include("vendre/" . $this->typeCourant . ".phtml"); ?>
	 		<?php include("vendre/prix.phtml"); ?>
		<?php else : ?>
		 <br />
		 Vous n'avez rien &agrave; vendre
		<?php endif; ?>
	<?php endif ?>
	<?php endif; ?> 
 </div>

</form>
<br />
<?php if ($this->assezDePa && $this->assezDeCastars && $this->choixDepart && $this->vendreOk > 0) : ?>
<input type='button' class='button1' id='bouton_vendrehotel' value='Mettre en vente !' onclick='this.disabled=true;$("valeur_11").value=encodePlus($("valeur_commentaire").value);_get_("/hotel/doaction?caction=do_hotel_vendre");' disabled>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>