<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='11'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	L'Hôtel des Ventes vous demande 1 castar pour l'utilisation de ce service.<br />
 	Si toutefois votre vente ne trouve pas d'acquéreur au bout de 30 jours, le
 	contenu de la vente sera directement renvoyé dans votre coffre. L'Hôtel gardera bien sûr la commission.<br />

 	<br />
 	<? if ($this->estSurEchoppe === true) : ?>
 		Vous pouvez vendre à l'Hôtel des Ventes des éléments créés dans votre atelier.
 	<? else: ?>
	Vous pouvez vendre des &eacute;l&eacute;ments pr&eacute;sents dans votre laban <br />
 	ou dans votre charrette si vous en avez une.
 	<? endif;?>
 	<br />
 	
 	<? if ($this->assezDePa == false) :?>
 		Vous n'avez pas assez de PA.
 	<? elseif ($this->assezDeCastars == false) : ?>
 		Vous n'avez pas assez de Castar.
 	<? else: ?>
 	Vendre à partir de :<br />
	<select name="valeur_1" id="valeur_1"  onchange="_get_('/hotel/doaction?caction=ask_hotel_vendre&valeur_1='+this.value);">
		<option value="-1">(Choisissez un endroit de d&eacute;part)</option>
		<? foreach($this->typeDepart as $t) : ?>
		 	<option value="<?=$t["id_type_depart"]?>" <?=$t["selected"]?>><?=$t["nom_type_depart"]?></option>
		<? endforeach; ?>
	 </select>
	 <br/><br/>

 	
 	<? if ($this->choixDepart != null) : ?>
	 <select name="valeur_2" id="valeur_2"  onchange="if ($('bouton_vendrehotel')) {$('bouton_vendrehotel').disabled=true} ;_get_('/hotel/doaction?caction=ask_hotel_vendre&valeur_1=<?=$this->idTypeCourantDepart?>&valeur_2='+this.value);">
	 	<option value="-1">(Choisissez un &eacute;l&eacute;ment)</option>
	 	<? foreach($this->typeElements as $t) : ?>
	 		<option value="<?=$t["id_type_element"]?>" <? if ($t["selected"] == $t["id_type_element"]): echo "selected"; endif;?>><?=htmlspecialchars($t["nom_element"])?></option>
	 	<? endforeach; ?>
	 </select>
	 <br /><br />
	<? endif;?>
		 
	<? if ($this->typeCourant != null) : ?>
		<? if ($this->vendreOk === true) : ?>
	 		<? include("vendre/" . $this->typeCourant . ".phtml"); ?>
	 		<? include("vendre/prix.phtml"); ?>
		<? else : ?>
		 <br />
		 Vous n'avez rien &agrave; vendre
		<? endif; ?>
	<? endif ?>
	<? endif; ?> 
 </div>

</form>
<br />
<?php if ($this->assezDePa && $this->assezDeCastars && $this->choixDepart && $this->vendreOk > 0) : ?>
<input type='button' class='button1' id='bouton_vendrehotel' value='Mettre en vente !' onclick='this.disabled=true;$("valeur_11").value=encodePlus($("valeur_commentaire").value);_get_("/hotel/doaction?caction=do_hotel_vendre");' disabled>
<? endif ?>
<? echo Bral_Helper_Fermer::affiche(); ?>