<input type="button" class='button1' onClick='_get_("/hotel/doaction?caction=ask_hotel_vendre");' value="<?=$this->paUtilisationHotel ?> PA - Vendre">

<br><br>

<table>
	<tr>
		<td width="80%" valign="top">
			<div id="box_hotel_resultats" style="height:430px;overflow: auto; min-height: 80px;"><? include("voir/resultats.phtml");?></div>
		</td>
		<td width="20%" valign="top"><? include("voir/menu.phtml");?></td>
	</tr>
</table>