<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <form name='myForm'>
 <div class='comp_contenu'>
 	<? if ($this->filerEnCours != null) : ?>
		Voulez-vous vraiement annuler la filature en cours ?
	<? else: ?>
		Vous n'avez aucune filature à annuler.
	<? endif;?>
 </div>

</form>
<br />
<? if ($this->filerEnCours != null) : ?>
<input type='button' class='button1' id='bouton_annuler' value='Annuler la filature' onclick='this.disabled=true;_get_("/filature/doaction?caction=do_filature_annuler");'/>
<? endif;?>

<? echo Bral_Helper_Fermer::affiche(); ?>