
	<table class="table_liste" style="width:100%">
		<thead class="table_liste">
		  <tr class="table_liste">
			<th colspan="4">
			Filature de <?php echo Bral_Util_Lien::remplaceBaliseParNomEtJs("[b".$this->filature["id_fk_cible_braldun_filature"]."]");?>
		  	<?php if ($this->filature["date_fin_filature"] != null): ?> 
		  		terminée le <?php echo Bral_Util_ConvertDate::get_datetime_mysql_datetime('d/m/y',$this->filature["date_fin_filature"]) ?>
		  	<?php else: ?>
		  		en cours
		  	<?php endif;?>
			</th>
		  </tr>
		  <tr class="table_liste">
		  	<th>Date</th>
			<th>D&eacute;tails</th>
		  </tr>
		</thead>
		<tbody>
		<?php if ($this->historique != null): ?>
		  <?php $i = 0; 
		  foreach($this->historique as $e): ?>
		  	<tr class="table_liste<?php echo ($i % 2);$i++; ?>">
		  		<td class="table_liste">
			  		<?php echo $e["date_historique_filature"]?>
		  		</td>
		  		<td class="table_liste">
			  		<?php echo $e["details_historique_filature"]?>
		  		</td>
		  	</tr>
		  <?php endforeach; ?>
		  
		<?php else: ?>
		   <tr class="table_liste">
		   	<td colspan="5">
		   		Aucun historique
		   	</td>
		   </tr>
		<?php endif; ?>
	   </tbody>
	</table>
					