<br />
<div class="box_contenu textalic">
	<div class="titre textalic textsizea">Hôtel des Ventes</div><br />
	
Même si l'Hôtel des Ventes peut contenir des équipements, potions, matériels, il ne présente pas les éléments en vente dans les échoppes.

<input type="button" class='button1' onclick="javascript:ouvrirWin('http://www.braldahim.com/etals');" value="0 PA - Voir les étals">

<br /><br /><br />

<?php //include("voir/menu.phtml");?>
<br /><br />


<div id="box_hotel_resultats"><?php include("voir/resultats.phtml");?></div>
<br /><br />
</div>