<br>
<ul class="box_contenu textalic" style="width:800px;">
	<ul class="titre textalic textsizeb">
	Hôtel des Ventes
	</ul><br>
	
Même si l'Hôtel des Ventes peut contenir des équipements, potions, matériels, il ne présente pas les éléments en vente dans les échoppes.

<br>Vous pouvez consulter le marché aux équipements / potions / vernis / matériels dans le Bourg ou directement par le biais des actions suivantes : <br>

<input type="button" class='button1' onClick="javascript:ouvrirWin('http://www.braldahim.com/marcheequipement');" value="0 PA - Voir le marché aux équipements">
<input type="button" class='button1' onClick="javascript:ouvrirWin('http://www.braldahim.com/marchepotion');" value="0 PA - Voir le marché aux potions et vernis">
<input type="button" class='button1' onClick="javascript:ouvrirWin('http://www.braldahim.com/marchemateriel');" value="0 PA - Voir le marché aux matériels">

<br><br><br>

<? include("voir/menu.phtml");?>
<br><br>


<div id="box_hotel_resultats"><? include("voir/resultats.phtml");?></div>
<br><br>
</ul>