<div class='comp_titre'><?=htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='0'>
 <div class='comp_contenu'>
 <br>
	 <? if ($this->possedeCharrette === false) : ?>
	 	Vous n'avez pas de charrette...
	 <? else: ?>
		 Pour <?=$this->nb_pa ?> PA, vous pouvez l&acirc;cher votre charrette. <br /><br />
	 <? endif; ?>
	 <br />
</div>
<?php if ($this->assezDePa == true && $this->possedeCharrette === true) : ?>
<input type='button' class='button1' id='bouton_lachercharrette' value='L&acirc;cher une charrette !' onClick='this.disabled=true;_get_("/charrette/doaction?caction=do_charrette_lacher");'>
<? endif ?>