<div class='comp_titre'><?php echo htmlspecialchars($this->titreAction) ?></div>
 <input type='hidden' id='nb_valeurs' name='nb_valeurs' value='4'>
 <div class='comp_contenu'>
 	<?php if ($this->possedeCharrette === false) : ?>
	 	Vous n'avez pas de charrette...
	 <?php elseif ($this->possedeSabot === false) : ?>
	 	Vous n'avez pas de sabot.
	 <?php else: ?>
	 	Le sabot : lorsqu'une charrette possède un sabot, le propriétaire de la charrette
	 	configure le sabot (code 0000 par défaut). S'il lâche sa charrette, elle ne pourra
	 	être attrapée que si le code est connu du Braldûn tentant de l'attrapper.  
	 	
	 	<br /><br />
	 	<br />
		Pour 0 PA, vous pouvez configurer le sabot de la charrette. <br />
		
		Code : 
		<select id='valeur_1' name='valeur_1'>
		<?php foreach ($this->chiffres as $c): ?>
		<option value='<?php echo $c?>' <?php if ($this->charrette["sabot_1_charrette"] == $c): echo "selected"; endif;?>><?php echo $c?></option>
		<?php endforeach; ?>
		</select>
		
		<select id='valeur_2' name='valeur_2'>
		<?php foreach ($this->chiffres as $c): ?>
		<option value='<?php echo $c?>' <?php if ($this->charrette["sabot_2_charrette"] == $c): echo "selected"; endif;?>><?php echo $c?></option>
		<?php endforeach; ?>
		</select>
		
		<select id='valeur_3' name='valeur_3'>
		<?php foreach ($this->chiffres as $c): ?>
		<option value='<?php echo $c?>' <?php if ($this->charrette["sabot_3_charrette"] == $c): echo "selected"; endif;?>><?php echo $c?></option>
		<?php endforeach; ?>
		</select>
		
		<select id='valeur_4' name='valeur_4'>
		<?php foreach ($this->chiffres as $c): ?>
		<option value='<?php echo $c?>' <?php if ($this->charrette["sabot_4_charrette"] == $c): echo "selected"; endif;?>><?php echo $c?></option>
		<?php endforeach; ?>
		</select>
			
			
	 <?php endif; ?>
	 <br />
</div>

<br />
<?php if ($this->possedeCharrette === true && $this->possedeSabot === true) : ?>
<input type='button' class='button1' id='bouton_sabot' value='Configurer' onclick='this.disabled=true;_get_("/charrette/doaction?caction=do_charrette_sabot");'>
<?php endif ?>
<?php echo Bral_Helper_Fermer::affiche(); ?>